name = "RequestProject"
defaultTargets = ["Algebra", "AlgebraicMagnetism", "AlgebraicNuclearPhysics", "AlgebraicPhysics", "AlgebraicReality", "AlgebraicSpaceTheory", "AlgebraicSpacetime", "AlgebraicTheoryOfAlgebra", "AlgebraicTime", "Analysis", "CategoryTheory", "Combinatorics", "Duality", "Electricity", "Exploration", "Factoring", "Forbidden", "Foundations", "GazingPool", "Information", "Logic", "Millennium", "Neural", "NumberTheory", "OptimalPlanning", "Oracle", "Photon", "Physics", "Prediction", "Probability", "Pythagorean", "Quantum", "QuantumTropicalComputing", "RandomMatrix", "Stereographic", "TheoryOfEverything", "Topology", "Tropical", "ZeroKnowledge"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "Algebra"
globs = ["Algebra.+"]

[[lean_lib]]
name = "AlgebraicMagnetism"
globs = ["AlgebraicMagnetism.+"]

[[lean_lib]]
name = "AlgebraicNuclearPhysics"
globs = ["AlgebraicNuclearPhysics.+"]

[[lean_lib]]
name = "AlgebraicPhysics"
globs = ["AlgebraicPhysics.+"]

[[lean_lib]]
name = "AlgebraicReality"
globs = ["AlgebraicReality.+"]

[[lean_lib]]
name = "AlgebraicSpaceTheory"
globs = ["AlgebraicSpaceTheory.+"]

[[lean_lib]]
name = "AlgebraicSpacetime"
globs = ["AlgebraicSpacetime.+"]

[[lean_lib]]
name = "AlgebraicTheoryOfAlgebra"
globs = ["AlgebraicTheoryOfAlgebra.+"]

[[lean_lib]]
name = "AlgebraicTime"
globs = ["AlgebraicTime.+"]

[[lean_lib]]
name = "Analysis"
globs = ["Analysis.+"]

[[lean_lib]]
name = "CategoryTheory"
globs = ["CategoryTheory.+"]

[[lean_lib]]
name = "Combinatorics"
globs = ["Combinatorics.+"]

[[lean_lib]]
name = "Duality"
globs = ["Duality.+"]

[[lean_lib]]
name = "Electricity"
globs = ["Electricity.+"]

[[lean_lib]]
name = "Exploration"
globs = ["Exploration.+"]

[[lean_lib]]
name = "Factoring"
globs = ["Factoring.+"]

[[lean_lib]]
name = "Forbidden"
globs = ["Forbidden.+"]

[[lean_lib]]
name = "Foundations"
globs = ["Foundations.+"]

[[lean_lib]]
name = "GazingPool"
globs = ["GazingPool.+"]

[[lean_lib]]
name = "Information"
globs = ["Information.+"]

[[lean_lib]]
name = "Logic"
globs = ["Logic.+"]

[[lean_lib]]
name = "Millennium"
globs = ["Millennium.+"]

[[lean_lib]]
name = "Neural"
globs = ["Neural.+"]

[[lean_lib]]
name = "NumberTheory"
globs = ["NumberTheory.+"]

[[lean_lib]]
name = "OptimalPlanning"
globs = ["OptimalPlanning.+"]

[[lean_lib]]
name = "Oracle"
globs = ["Oracle.+"]

[[lean_lib]]
name = "Photon"
globs = ["Photon.+"]

[[lean_lib]]
name = "Physics"
globs = ["Physics.+"]

[[lean_lib]]
name = "Prediction"
globs = ["Prediction.+"]

[[lean_lib]]
name = "Probability"
globs = ["Probability.+"]

[[lean_lib]]
name = "Pythagorean"
globs = ["Pythagorean.+"]

[[lean_lib]]
name = "Quantum"
globs = ["Quantum.+"]

[[lean_lib]]
name = "QuantumTropicalComputing"
globs = ["QuantumTropicalComputing.+"]

[[lean_lib]]
name = "RandomMatrix"
globs = ["RandomMatrix.+"]

[[lean_lib]]
name = "Stereographic"
globs = ["Stereographic.+"]

[[lean_lib]]
name = "TheoryOfEverything"
globs = ["TheoryOfEverything.+"]

[[lean_lib]]
name = "Topology"
globs = ["Topology.+"]

[[lean_lib]]
name = "Tropical"
globs = ["Tropical.+"]

[[lean_lib]]
name = "ZeroKnowledge"
globs = ["ZeroKnowledge.+"]
