/-
# Energy transfer among interacting modes

This file complements the energy estimate in `EnergyMethod`.  It formalizes a
finite-mode statement relevant to turbulence: if nonlinear interactions are
energy conserving globally, any gain of energy in one collection of modes is
exactly balanced by a loss in its complement.  This is the algebraic core of
spectral energy transfer, without asserting a direction of cascade.
-/

import Mathlib

namespace NavierStokes
namespace Turbulence

variable {ι V : Type*} [DecidableEq ι]
  [NormedAddCommGroup V] [InnerProductSpace ℝ V]

/-- Modal energy-transfer rate generated by a nonlinear interaction `N` at a
state `u`. -/
def modalTransfer (N : ι → V) (u : ι → V) (i : ι) : ℝ :=
  inner ℝ (N i) (u i)

/-- Transfer into a finite collection of modes. -/
def transferInto (N : ι → V) (u : ι → V) (modes : Finset ι) : ℝ :=
  ∑ i ∈ modes, modalTransfer N u i

/-- For a finite truncation, global nonlinear energy conservation forces exact
exchange between any set of modes and its complement. -/
theorem transferInto_complement_eq_neg {all : Finset ι} {low : Finset ι}
    (hsub : low ⊆ all) (N u : ι → V)
    (hconserve : transferInto N u all = 0) :
    transferInto N u (all \ low) = -transferInto N u low := by
  have hsum := Finset.sum_sdiff_eq_sub (f := modalTransfer N u) hsub
  unfold transferInto at hconserve ⊢
  rw [hsum, hconserve]
  ring

/-- Consequently, positive transfer into a chosen band entails an equal
negative transfer into the remaining modes. -/
theorem transferInto_complement_negative {all : Finset ι} {band : Finset ι}
    (hsub : band ⊆ all) (N u : ι → V)
    (hconserve : transferInto N u all = 0)
    (hgain : 0 < transferInto N u band) :
    transferInto N u (all \ band) < 0 := by
  rw [transferInto_complement_eq_neg hsub N u hconserve]
  exact neg_neg_of_pos hgain

/-- The magnitudes of the two transfers agree. -/
theorem norm_transferInto_complement_eq {all : Finset ι} {band : Finset ι}
    (hsub : band ⊆ all) (N u : ι → V)
    (hconserve : transferInto N u all = 0) :
    ‖transferInto N u (all \ band)‖ = ‖transferInto N u band‖ := by
  rw [transferInto_complement_eq_neg hsub N u hconserve, norm_neg]

end Turbulence
end NavierStokes