#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════╗
║  DEMO 1: The Clifford Algebra Cl(1,3) — Spacetime Algebra          ║
║  The Algebraic Theory of Spacetime                                  ║
╚══════════════════════════════════════════════════════════════════════╝

Demonstrates the 16-dimensional algebra generated by {γ₀, γ₁, γ₂, γ₃}
with the Minkowski signature (+, −, −, −).

We use the 4×4 Dirac (gamma) matrix representation.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
import matplotlib.gridspec as gridspec

# ══════════════════════════════════════════════════════════════════
# Section 1: Define the Gamma Matrices (Dirac representation)
# ══════════════════════════════════════════════════════════════════

# Pauli matrices
sigma_1 = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_3 = np.array([[1, 0], [0, -1]], dtype=complex)
I2 = np.eye(2, dtype=complex)

# Dirac gamma matrices in the Dirac (standard) representation
# γ⁰ = diag(I, -I), γⁱ = [[0, σⁱ], [-σⁱ, 0]]
gamma = np.zeros((4, 4, 4), dtype=complex)
gamma[0] = np.block([[I2, np.zeros((2,2))], [np.zeros((2,2)), -I2]])
gamma[1] = np.block([[np.zeros((2,2)), sigma_1], [-sigma_1, np.zeros((2,2))]])
gamma[2] = np.block([[np.zeros((2,2)), sigma_2], [-sigma_2, np.zeros((2,2))]])
gamma[3] = np.block([[np.zeros((2,2)), sigma_3], [-sigma_3, np.zeros((2,2))]])

# Minkowski metric η = diag(+1, -1, -1, -1)
eta = np.diag([1.0, -1.0, -1.0, -1.0])

# ══════════════════════════════════════════════════════════════════
# Section 2: Verify the Clifford Algebra Relation
# ══════════════════════════════════════════════════════════════════

print("=" * 60)
print("  CLIFFORD ALGEBRA VERIFICATION")
print("  {γμ, γν} = γμγν + γνγμ = 2ημν I₄")
print("=" * 60)

I4 = np.eye(4, dtype=complex)
all_correct = True
for mu in range(4):
    for nu in range(4):
        anticomm = gamma[mu] @ gamma[nu] + gamma[nu] @ gamma[mu]
        expected = 2 * eta[mu, nu] * I4
        check = np.allclose(anticomm, expected)
        if not check:
            all_correct = False
        if mu <= nu:
            symbol = "✓" if check else "✗"
            print(f"  {{γ{mu}, γ{nu}}} = {2*eta[mu,nu]:+.0f} · I₄  {symbol}")

print(f"\n  All Clifford relations satisfied: {'YES ✓' if all_correct else 'NO ✗'}")

# ══════════════════════════════════════════════════════════════════
# Section 3: Build all 16 basis elements
# ══════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("  THE 16 BASIS ELEMENTS OF Cl(1,3)")
print("=" * 60)

from itertools import combinations

basis_labels = []
basis_matrices = []

# Grade 0: scalar (identity)
basis_labels.append("1")
basis_matrices.append(I4.copy())

# Grade 1: vectors
for i in range(4):
    basis_labels.append(f"γ{i}")
    basis_matrices.append(gamma[i].copy())

# Grade 2: bivectors
for i, j in combinations(range(4), 2):
    label = f"γ{i}{j}"
    basis_labels.append(label)
    basis_matrices.append(gamma[i] @ gamma[j])

# Grade 3: trivectors
for i, j, k in combinations(range(4), 3):
    label = f"γ{i}{j}{k}"
    basis_labels.append(label)
    basis_matrices.append(gamma[i] @ gamma[j] @ gamma[k])

# Grade 4: pseudoscalar
basis_labels.append("γ0123")
gamma5 = gamma[0] @ gamma[1] @ gamma[2] @ gamma[3]
basis_matrices.append(gamma5)

print(f"\n  Total basis elements: {len(basis_labels)}")
print(f"  Grading: 1 + 4 + 6 + 4 + 1 = {1+4+6+4+1}")

grades = [0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4]
for g in range(5):
    elems = [basis_labels[i] for i in range(16) if grades[i] == g]
    print(f"  Grade {g}: {', '.join(elems)}")

# Verify pseudoscalar I² = -1
I_sq = gamma5 @ gamma5
print(f"\n  Pseudoscalar I = γ₀γ₁γ₂γ₃")
print(f"  I² = {'−1 ✓' if np.allclose(I_sq, -I4) else 'NOT −1 ✗'}")

# ══════════════════════════════════════════════════════════════════
# Section 4: Visualization — The Multivector Grading
# ══════════════════════════════════════════════════════════════════

fig = plt.figure(figsize=(16, 10))
fig.suptitle("The Algebraic Theory of Spacetime\nClifford Algebra Cl(1,3) — The 16-Dimensional Spacetime Algebra",
             fontsize=16, fontweight='bold', y=0.98)

gs = gridspec.GridSpec(2, 2, hspace=0.35, wspace=0.3)

# Panel 1: The Pascal triangle / grading structure
ax1 = fig.add_subplot(gs[0, 0])
ax1.set_xlim(-2, 8)
ax1.set_ylim(-1, 6)
ax1.set_aspect('equal')
ax1.set_title("Multivector Grading Structure", fontsize=13, fontweight='bold')
ax1.axis('off')

grade_data = [
    (0, [("1", "Scalar")], '#2ecc71'),
    (1, [("γ₀",""),("γ₁",""),("γ₂",""),("γ₃","")], '#3498db'),
    (2, [("γ₀₁",""),("γ₀₂",""),("γ₀₃",""),("γ₁₂",""),("γ₁₃",""),("γ₂₃","")], '#e74c3c'),
    (3, [("γ₀₁₂",""),("γ₀₁₃",""),("γ₀₂₃",""),("γ₁₂₃","")], '#9b59b6'),
    (4, [("I=γ₀₁₂₃", "Pseudoscalar")], '#f39c12'),
]

y_positions = [5, 4, 3, 2, 1]
for grade, (g, elems, color) in enumerate(grade_data):
    y = y_positions[grade]
    n = len(elems)
    x_start = 3 - (n - 1) * 0.55
    for i, (label, desc) in enumerate(elems):
        x = x_start + i * 1.1
        circle = plt.Circle((x, y), 0.4, facecolor=color, edgecolor='black',
                            alpha=0.8, linewidth=1.5)
        ax1.add_patch(circle)
        ax1.text(x, y, label, ha='center', va='center', fontsize=7,
                fontweight='bold', color='white')
    ax1.text(-1.5, y, f"Grade {g}\n(dim {n})", ha='center', va='center',
            fontsize=9, fontweight='bold', color=color)

ax1.text(3, -0.3, "Total dimension: 1+4+6+4+1 = 16 = 2⁴", ha='center',
        fontsize=10, style='italic')

# Panel 2: The anticommutation pattern (multiplication table heatmap)
ax2 = fig.add_subplot(gs[0, 1])

# Compute {γμ, γν} / 2 for the 4 generators
anticomm_table = np.zeros((4, 4))
for mu in range(4):
    for nu in range(4):
        anticomm = gamma[mu] @ gamma[nu] + gamma[nu] @ gamma[mu]
        # Extract the scalar coefficient (trace / 4)
        anticomm_table[mu, nu] = np.real(np.trace(anticomm)) / 4

im = ax2.imshow(anticomm_table, cmap='RdBu_r', vmin=-1.5, vmax=1.5)
ax2.set_xticks(range(4))
ax2.set_yticks(range(4))
ax2.set_xticklabels(['γ₀', 'γ₁', 'γ₂', 'γ₃'], fontsize=12)
ax2.set_yticklabels(['γ₀', 'γ₁', 'γ₂', 'γ₃'], fontsize=12)
ax2.set_title("Clifford Relation: ½{γμ, γν} = ημν", fontsize=13, fontweight='bold')

for i in range(4):
    for j in range(4):
        val = anticomm_table[i, j]
        ax2.text(j, i, f"{val:+.0f}", ha='center', va='center',
                fontsize=14, fontweight='bold',
                color='white' if abs(val) > 0.5 else 'black')

plt.colorbar(im, ax=ax2, shrink=0.8, label='ημν')

# Panel 3: Basis element properties (squares)
ax3 = fig.add_subplot(gs[1, 0])

squares = []
for i, mat in enumerate(basis_matrices):
    sq = mat @ mat
    # Extract scalar part
    tr = np.real(np.trace(sq)) / 4
    squares.append(tr)

colors_bar = []
for i, s in enumerate(squares):
    if s > 0:
        colors_bar.append('#2ecc71')
    elif s < 0:
        colors_bar.append('#e74c3c')
    else:
        colors_bar.append('#95a5a6')

bars = ax3.bar(range(16), squares, color=colors_bar, edgecolor='black', linewidth=0.5)
ax3.set_xticks(range(16))
ax3.set_xticklabels(basis_labels, rotation=45, ha='right', fontsize=8)
ax3.set_ylabel("e² (scalar part)", fontsize=11)
ax3.set_title("Squares of Basis Elements", fontsize=13, fontweight='bold')
ax3.axhline(y=0, color='black', linewidth=0.5)
ax3.set_ylim(-1.5, 1.5)

# Add grade coloring strip
grade_colors = ['#2ecc71', '#3498db', '#3498db', '#3498db', '#3498db',
                '#e74c3c', '#e74c3c', '#e74c3c', '#e74c3c', '#e74c3c', '#e74c3c',
                '#9b59b6', '#9b59b6', '#9b59b6', '#9b59b6', '#f39c12']
for i, c in enumerate(grade_colors):
    ax3.bar(i, 0.05, bottom=-1.45, color=c, width=0.8)

# Panel 4: The algebra-physics dictionary
ax4 = fig.add_subplot(gs[1, 1])
ax4.axis('off')
ax4.set_title("Algebra ↔ Physics Dictionary", fontsize=13, fontweight='bold')

dictionary = [
    ("Grade 0 (Scalar)", "Mass, charge, proper time", '#2ecc71'),
    ("Grade 1 (Vector)", "Position, momentum, current", '#3498db'),
    ("Grade 2 (Bivector)", "EM field F, angular momentum", '#e74c3c'),
    ("Grade 3 (Trivector)", "Dual current, magnetic monopole", '#9b59b6'),
    ("Grade 4 (Pseudoscalar)", "Orientation, chirality γ₅", '#f39c12'),
    ("Rotor RvR̃", "Lorentz transformation", '#1abc9c'),
    ("∇F = J", "Maxwell's equations (all 4!)", '#e67e22'),
    ("I² = −1", "Spacetime orientation", '#c0392b'),
]

for i, (alg, phys, color) in enumerate(dictionary):
    y = 0.92 - i * 0.115
    # Algebra box
    bbox = FancyBboxPatch((0.02, y - 0.04), 0.38, 0.08,
                          boxstyle="round,pad=0.01", facecolor=color,
                          edgecolor='black', alpha=0.3, transform=ax4.transAxes)
    ax4.add_patch(bbox)
    ax4.text(0.21, y, alg, transform=ax4.transAxes, ha='center', va='center',
            fontsize=8.5, fontweight='bold')
    # Arrow
    ax4.annotate('', xy=(0.57, y), xytext=(0.43, y),
                xycoords='axes fraction', textcoords='axes fraction',
                arrowprops=dict(arrowstyle='->', color=color, lw=2))
    # Physics box
    bbox2 = FancyBboxPatch((0.58, y - 0.04), 0.38, 0.08,
                           boxstyle="round,pad=0.01", facecolor=color,
                           edgecolor='black', alpha=0.15, transform=ax4.transAxes)
    ax4.add_patch(bbox2)
    ax4.text(0.77, y, phys, transform=ax4.transAxes, ha='center', va='center',
            fontsize=8.5)

plt.savefig('/workspace/request-project/Algebraic Spacetime/demos/fig1_clifford_algebra.png',
            dpi=150, bbox_inches='tight', facecolor='white')
plt.close()

print("\n✓ Figure saved: fig1_clifford_algebra.png")
print("\n" + "=" * 60)
print("  DEMO 1 COMPLETE")
print("=" * 60)
