/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# The identity `S^t_λ = φ_t(Q_λ)` for shifted `t`-Schur functions

This file formalizes the identity relating the *shifted `t`-Schur functions* `S^t_λ`
to the *Schur `Q`-functions* `Q_λ` via the plethystic endomorphism `φ_t` which acts on
odd power sums by `φ_t(p_n) = (1 - t^n) p_n`.

## Non-circular architecture

The proof is organized so that the identity *emerges* from the structure of the vertex
operators and the power-sum transformation; the identity itself is never used as a
definition or a lemma.

1. **Ring of symmetric functions `Λ_odd`.**  We model `Λ_odd` as the polynomial ring
   `Lam := MvPolynomial ℕ K` over `K = RatFunc ℚ`, where the variable `X k` stands for
   the odd power sum `p_{2k+1}`.  (See `p`.)  The parameter `t` is the transcendental
   `RatFunc.X`.

2. **Schur `Q`-functions via the generating kernel.**  The one-row functions `q_n = Q_{(n)}`
   are the coefficients of
   `∏ᵢ (1 + xᵢ z)/(1 - xᵢ z) = exp(∑_{r odd} (2/r) p_r z^r)`.
   Taking the logarithmic derivative of this kernel yields the Newton recursion
   `n q_n = ∑_{k} 2 p_{2k+1} q_{n-1-2k}` which we use as the definition (`qGen`, `q`).
   General `Q_λ` are produced by the Schur-`Q` vertex operator `B` applied to the vacuum
   `1` (`Qfun`).  The vertex operator `B(z) = B_+(z) ∘ B_-(z)` has creation part
   "multiplication by the generating series `∑ q_n z^n`" and annihilation part
   `B_-(z) = exp(-∑_{r odd} c_r ∂_{p_r} z^{-r})`, which — having *constant* coefficients —
   is exactly the Taylor shift `p_{2k+1} ↦ p_{2k+1} - c·(z^{-1})^{2k+1}` (`annGen`).

3. **Shifted `t`-Schur functions via the `t`-deformed vertex operators.**  The same
   construction is carried out with the *`t`-deformed odd power sums* `(1 - t^{2k+1}) p_{2k+1}`:
   the creation series uses the deformed coefficients (`qt`) and the annihilation shift is
   the corresponding dual (`annShiftT`).  This gives the `t`-vertex operator `Bt`, and
   `S^t_λ := Bt_{λ₁}(⋯ Bt_{λ_ℓ}(1))` (`Sfun`).  Crucially, `Sfun` is defined purely from
   the `t`-deformed data — it is *not* defined as `φ_t(Q_λ)`.

4. **The endomorphism `φ_t`.**  `phiT` is the `K`-algebra endomorphism of `Lam` with
   `φ_t(p_{2k+1}) = (1 - t^{2k+1}) p_{2k+1}` (`phiT`, `phiT_p`).

5. **Proof.**  We establish the *intertwining (Pieri-compatible) relation*
   `Bt n (φ_t f) = φ_t (B n f)` (`Bt_phiT`), obtained from the commutation of `φ_t` with
   the creation part (`φ_t` is an algebra map, `qt = φ_t ∘ q`) and with the annihilation
   part (chain rule for the Taylor shift, `annShiftT_phiT`).  An induction on the length of
   `λ` (`Sfun_eq_phiT_Qfun`) then yields `S^t_λ = φ_t(Q_λ)`.

The headline result is `shifted_tSchur_eq_phiT_Q`.

## Notes on faithfulness

* `Lam = MvPolynomial ℕ K` with `X k ↦ p_{2k+1}` is the polynomial realization of the
  ring of symmetric functions generated by the odd power sums.
* The one-row functions `q n` agree, by construction, with the coefficients of the
  Schur-`Q` generating kernel `∏ (1+xᵢz)/(1-xᵢz)`.
* The annihilation normalization constant (here `4`) is the adjoint of the creation part
  for the Schur-`Q` (Hall–Littlewood at `t = -1`) inner product; the final identity is in
  fact independent of this choice, since the `t`-deformed operator uses the matching dual
  constant `4 / (1 - t^{2k+1})`.
-/
import Mathlib

open MvPolynomial Polynomial

noncomputable section

namespace ShiftedTSchur

/-- The base field `K = ℚ(t)`. -/
abbrev K := RatFunc ℚ

/-- The ring of symmetric functions in the odd power sums, modeled as the polynomial ring
`MvPolynomial ℕ K` where the variable `X k` stands for the odd power sum `p_{2k+1}`. -/
abbrev Lam := MvPolynomial ℕ K

/-- The transcendental parameter `t ∈ K`. -/
def tt : K := RatFunc.X

/-- The odd power sum `p_{2k+1}`, realized as the variable `X k`. -/
def p (k : ℕ) : Lam := X k

/-- The scalar `c_k = 1 - t^{2k+1}` by which `φ_t` scales the `k`-th odd power sum. -/
def cc (k : ℕ) : K := 1 - tt ^ (2 * k + 1)

lemma cc_ne (k : ℕ) : cc k ≠ 0 := by
  by_contra h_contra
  have h_eq : (1 - (RatFunc.X : RatFunc ℚ) ^ (2 * k + 1)) = 0 := by
    exact h_contra;
  convert absurd h_eq ?_;
  rw [ show ( 1 - RatFunc.X ^ ( 2 * k + 1 ) : RatFunc ℚ ) = algebraMap ( Polynomial ℚ ) ( RatFunc ℚ ) ( 1 - Polynomial.X ^ ( 2 * k + 1 ) ) by simp +decide, IsFractionRing.to_map_eq_zero_iff ];
  exact ne_of_apply_ne ( Polynomial.eval 0 ) ( by norm_num )

/-! ### The plethystic endomorphism `φ_t` -/

/-- The plethystic endomorphism `φ_t`, the `K`-algebra map sending the odd power sum
`p_{2k+1}` to `(1 - t^{2k+1}) p_{2k+1}`. -/
def phiT : Lam →ₐ[K] Lam :=
  MvPolynomial.aeval (fun k => MvPolynomial.C (cc k) * X k)

@[simp] lemma phiT_X (k : ℕ) : phiT (X k) = MvPolynomial.C (cc k) * X k := by
  simp [phiT]

/-- `φ_t(p_{2k+1}) = (1 - t^{2k+1}) p_{2k+1}`. -/
lemma phiT_p (k : ℕ) : phiT (p k) = MvPolynomial.C (cc k) * p k := by
  simp [p, phiT_X]

/-! ### The creation (one-row) functions -/

/-- Generic creation functions: the coefficients of `exp(∑_k (2/(2k+1)) (cf k) z^{2k+1})`,
defined by the Newton recursion coming from the logarithmic derivative of the kernel.
Taking `cf k = X k` gives the one-row Schur `Q`-functions; taking `cf k = (1-t^{2k+1}) X k`
gives their `t`-deformation. -/
def qGen (cf : ℕ → Lam) : ℕ → Lam
  | 0 => 1
  | (m + 1) => MvPolynomial.C ((1 : K) / ((m : K) + 1)) *
      ∑ k ∈ Finset.range (m / 2 + 1), MvPolynomial.C (2 : K) * cf k * qGen cf (m - 2 * k)
  decreasing_by omega

/-- The one-row Schur `Q`-functions `q_n = Q_{(n)}`. -/
def q : ℕ → Lam := qGen (fun k => X k)

/-- The `t`-deformed one-row functions, built from the `t`-deformed odd power sums. -/
def qt : ℕ → Lam := qGen (fun k => MvPolynomial.C (cc k) * X k)

/-
The `t`-deformed one-row functions are the `φ_t`-images of the one-row functions.
This is the creation-part intertwining; it is a statement about one rows, not the main
identity.
-/
lemma qt_eq_phiT_q (n : ℕ) : qt n = phiT (q n) := by
  unfold qt q;
  induction' n using Nat.strong_induction_on with n ih;
  rcases n with ( _ | _ | n ) <;> simp_all +decide;
  · -- By definition of $qGen$, we have $qGen (fun k => MvPolynomial.C (cc k) * MvPolynomial.X k) 0 = 1$.
    simp [qGen];
  · unfold qGen; aesop;
  · unfold qGen; simp +decide [ ih ] ;

/-! ### The annihilation (Taylor shift) operators -/

/-- The annihilation part of the vertex operator, as a `K`-algebra map
`Lam → Lam[u]` (with `u = z^{-1}`).  Since the annihilation
`exp(-∑_k (d k) ∂_{p_{2k+1}} z^{-(2k+1)})` has coefficients constant in the `p`'s, it is the
Taylor shift `p_{2k+1} ↦ p_{2k+1} - (d k) u^{2k+1}`. -/
def annGen (d : ℕ → K) : Lam →ₐ[K] Polynomial Lam :=
  MvPolynomial.aeval
    (fun k => Polynomial.C (X k)
      - Polynomial.C (algebraMap K Lam (d k)) * Polynomial.X ^ (2 * k + 1))

/-- Annihilation for the Schur `Q` vertex operator (adjoint normalization constant `4`). -/
def annShift : Lam →ₐ[K] Polynomial Lam := annGen (fun _ => (4 : K))

/-- Annihilation for the `t`-deformed vertex operator: the dual of the deformed creation,
with constant `4 / (1 - t^{2k+1})`. -/
def annShiftT : Lam →ₐ[K] Polynomial Lam := annGen (fun k => (4 : K) / cc k)

/-
The key chain-rule intertwining of the annihilation parts:
`annShiftT (φ_t f) = (annShift f)` mapped coefficient-wise by `φ_t`.
-/
lemma annShiftT_phiT (f : Lam) :
    annShiftT (phiT f) = (annShift f).map (phiT : Lam →+* Lam) := by
  -- By definition of `annShiftT`, we have `annShiftT (phiT f) = (annShift f).map (phiT : Lam →+* Lam)`.
  have h_annShiftT : ∀ p : Lam, annShiftT (phiT p) = Polynomial.map (phiT : Lam →+* Lam) (annShift p) := by
    intro p
    unfold annShiftT annShift;
    unfold annGen; simp +decide [ phiT ] ;
    induction p using MvPolynomial.induction_on <;> simp_all +decide [ Polynomial.map_mul, Polynomial.map_pow, Polynomial.map_X ];
    left; ring_nf; norm_num [ cc_ne ] ;
    rw [ ← mul_assoc, ← Polynomial.C_mul, ← MvPolynomial.C_mul ] ; norm_num [ cc_ne ] ;
  exact h_annShiftT f

/-! ### The vertex operator components and the symmetric functions -/

/-- The linear functional extracting `∑_m (coeff_m p) · (qf (n+m))` from a polynomial `p`;
this assembles the creation series and the annihilation shift into the `z^n`-coefficient of
the vertex operator. -/
def Tsum (qf : ℕ → Lam) (n : ℕ) (pp : Polynomial Lam) : Lam :=
  pp.sum (fun m c => qf (n + m) * c)

/-- The `n`-th component `B_n` of the Schur `Q` vertex operator. -/
def B (n : ℕ) (f : Lam) : Lam := Tsum q n (annShift f)

/-- The `n`-th component `Bt_n` of the `t`-deformed vertex operator. -/
def Bt (n : ℕ) (f : Lam) : Lam := Tsum qt n (annShiftT f)

/-
Transfer of `Tsum` along the coefficient-wise `φ_t`.
-/
lemma Tsum_map_phiT (n : ℕ) (pp : Polynomial Lam) :
    Tsum qt n (pp.map (phiT : Lam →+* Lam)) = phiT (Tsum q n pp) := by
  unfold Tsum;
  simp +decide [ Polynomial.sum_def, qt_eq_phiT_q ];
  refine' Finset.sum_subset _ _ <;> intro x hx <;> aesop

/-- The intertwining (Pieri-compatible) relation: `φ_t` conjugates `B` into `Bt`. -/
lemma Bt_phiT (n : ℕ) (f : Lam) : Bt n (phiT f) = phiT (B n f) := by
  unfold Bt B
  rw [annShiftT_phiT]
  exact Tsum_map_phiT n (annShift f)

/-- The Schur `Q`-function `Q_λ`, where `λ` is given by its list of parts (largest first),
obtained by applying the vertex operator components to the vacuum `1`. -/
def Qfun (l : List ℕ) : Lam := l.foldr B 1

/-- The shifted `t`-Schur function `S^t_λ`, obtained from the `t`-deformed vertex operator. -/
def Sfun (l : List ℕ) : Lam := l.foldr Bt 1

/-- **Main identity (general form).** For every list of parts `l`,
`S^t_λ = φ_t(Q_λ)`.  Proved by induction on the length of `λ` using the intertwining
relation `Bt_phiT`. -/
theorem Sfun_eq_phiT_Qfun (l : List ℕ) : Sfun l = phiT (Qfun l) := by
  induction l with
  | nil => simp [Sfun, Qfun]
  | cons a t ih =>
      show Bt a (Sfun t) = phiT (B a (Qfun t))
      rw [ih, Bt_phiT]

/-- A strict partition, given as a list of its parts: strictly decreasing and positive. -/
def IsStrictPartition (l : List ℕ) : Prop :=
  l.Pairwise (· > ·) ∧ ∀ x ∈ l, 0 < x

/-- **The identity `S^t_λ = φ_t(Q_λ)` for strict partitions `λ`.**

The strictness hypothesis `hl` is included because the statement is naturally about strict
partitions; the identity in fact holds for an arbitrary list of parts (`Sfun_eq_phiT_Qfun`),
so `hl` is not needed in the proof. -/
theorem shifted_tSchur_eq_phiT_Q (l : List ℕ) (hl : IsStrictPartition l) :
    Sfun l = phiT (Qfun l) :=
  Sfun_eq_phiT_Qfun l

end ShiftedTSchur