/-
# Sheffer Algebra: Basic Definitions and Properties

The softplus function σ(x) = log(1 + eˣ) generates a rich algebra of smooth functions
through composition with affine maps. This file establishes the core definitions and
fundamental properties.
-/
import Mathlib

open Real Filter Topology

noncomputable section

/-! ## Core Definitions -/

/-- The softplus function σ(x) = log(1 + eˣ). -/
def softplus (x : ℝ) : ℝ := Real.log (1 + Real.exp x)

/-- The logistic sigmoid function S(x) = eˣ / (1 + eˣ). -/
def logisticSigmoid (x : ℝ) : ℝ := Real.exp x / (1 + Real.exp x)

/-- Sheffer expressions: the free algebra generated by softplus under
    affine pre-composition and affine combination. -/
inductive ShefferExpr : Type where
  | base : ShefferExpr
  | affinePrecomp (a b : ℝ) (e : ShefferExpr) : ShefferExpr
  | affineComb (α β γ : ℝ) (e₁ e₂ : ShefferExpr) : ShefferExpr

/-- Evaluation of a Sheffer expression at a real number. -/
noncomputable def ShefferExpr.eval : ShefferExpr → ℝ → ℝ
  | .base => softplus
  | .affinePrecomp a b e => fun x => e.eval (a * x + b)
  | .affineComb α β γ e₁ e₂ => fun x => α * e₁.eval x + β * e₂.eval x + γ

/-- The Sheffer algebra: the set of all functions expressible as Sheffer expressions. -/
def ShefferAlg : Set (ℝ → ℝ) := {f | ∃ e : ShefferExpr, f = e.eval}

/-! ## Basic Softplus Properties -/

/-- 1 + exp(x) > 0 for all x. -/
theorem one_plus_exp_pos (x : ℝ) : 0 < 1 + Real.exp x := by
  linarith [Real.exp_pos x]

/-- softplus is always positive. -/
theorem softplus_pos (x : ℝ) : 0 < softplus x := by
  unfold softplus
  exact Real.log_pos (by linarith [Real.exp_pos x])

/-- softplus(0) = log 2. -/
theorem softplus_zero : softplus 0 = Real.log 2 := by
  unfold softplus; simp [Real.exp_zero]; norm_num

/-- The logistic sigmoid is always between 0 and 1. -/
theorem logisticSigmoid_pos (x : ℝ) : 0 < logisticSigmoid x := by
  unfold logisticSigmoid
  exact div_pos (Real.exp_pos x) (one_plus_exp_pos x)

theorem logisticSigmoid_lt_one (x : ℝ) : logisticSigmoid x < 1 := by
  unfold logisticSigmoid
  rw [div_lt_one (one_plus_exp_pos x)]
  linarith

/-- Sigmoid satisfies S(x) + S(-x) = 1. -/
theorem logisticSigmoid_add_neg (x : ℝ) : logisticSigmoid x + logisticSigmoid (-x) = 1 := by
  unfold logisticSigmoid
  rw [Real.exp_neg]
  have h : (0:ℝ) < Real.exp x := Real.exp_pos x
  have h1 : (0:ℝ) < 1 + Real.exp x := by linarith
  have h2 : (0:ℝ) < 1 + (Real.exp x)⁻¹ := by positivity
  field_simp; ring

/-- softplus is the antiderivative of sigmoid: σ'(x) = S(x). -/
theorem hasDerivAt_softplus (x : ℝ) : HasDerivAt softplus (logisticSigmoid x) x := by
  unfold softplus logisticSigmoid
  have h1 : (0 : ℝ) < 1 + Real.exp x := one_plus_exp_pos x
  have h2 : (1 : ℝ) + Real.exp x ≠ 0 := ne_of_gt h1
  have := HasDerivAt.log ((hasDerivAt_const x (1 : ℝ)).add (Real.hasDerivAt_exp x)) h2
  simp at this
  exact this

/-- softplus ∈ ShefferAlg. -/
theorem softplus_mem_sheffer : softplus ∈ ShefferAlg :=
  ⟨.base, rfl⟩

/-- ShefferAlg is closed under affine pre-composition. -/
theorem sheffer_affinePrecomp {f : ℝ → ℝ} (hf : f ∈ ShefferAlg) (a b : ℝ) :
    (fun x => f (a * x + b)) ∈ ShefferAlg := by
  obtain ⟨e, rfl⟩ := hf
  exact ⟨.affinePrecomp a b e, rfl⟩

/-- ShefferAlg is closed under affine combination. -/
theorem sheffer_affineComb {f g : ℝ → ℝ} (hf : f ∈ ShefferAlg) (hg : g ∈ ShefferAlg)
    (α β γ : ℝ) : (fun x => α * f x + β * g x + γ) ∈ ShefferAlg := by
  obtain ⟨ef, rfl⟩ := hf
  obtain ⟨eg, rfl⟩ := hg
  exact ⟨.affineComb α β γ ef eg, rfl⟩

/-- The identity function is in ShefferAlg: x = σ(x) - σ(-x). -/
theorem id_eq_softplus_diff (x : ℝ) : x = softplus x - softplus (-x) := by
  unfold softplus
  rw [Real.exp_neg]
  have h1 : (0:ℝ) < 1 + Real.exp x := by linarith [Real.exp_pos x]
  have h2 : (0:ℝ) < 1 + (Real.exp x)⁻¹ := by positivity
  rw [← Real.log_div (ne_of_gt h1) (ne_of_gt h2)]
  have : (1 + Real.exp x) / (1 + (Real.exp x)⁻¹) = Real.exp x := by field_simp; ring
  rw [this, Real.log_exp]

theorem id_mem_sheffer : (fun x : ℝ => x) ∈ ShefferAlg := by
  have hmem := sheffer_affineComb softplus_mem_sheffer
    (sheffer_affinePrecomp softplus_mem_sheffer (-1) 0) 1 (-1) 0
  convert hmem using 1
  ext x
  have h1 := id_eq_softplus_diff x
  have h2 : softplus (-x) = softplus ((-1) * x + 0) := by congr 1; ring
  linarith

/-- Constant functions are in ShefferAlg. -/
theorem const_mem_sheffer (c : ℝ) : (fun _ : ℝ => c) ∈ ShefferAlg := by
  have hmem := sheffer_affineComb softplus_mem_sheffer softplus_mem_sheffer 0 0 c
  convert hmem using 1
  ext x; ring

/-- Affine functions a*x + b are in ShefferAlg. -/
theorem affine_mem_sheffer (a b : ℝ) : (fun x : ℝ => a * x + b) ∈ ShefferAlg := by
  have hmem := sheffer_affineComb id_mem_sheffer softplus_mem_sheffer a 0 b
  convert hmem using 1
  ext x; ring

/-
softplus is Lipschitz with constant 1.
-/
theorem softplus_lipschitz : LipschitzWith 1 softplus := by
  have h_deriv_bound : ∀ x, |deriv softplus x| ≤ 1 := by
    unfold softplus;
    norm_num [ Real.differentiableAt_exp, ne_of_gt ( add_pos zero_lt_one ( Real.exp_pos _ ) ) ];
    exact fun x => abs_le.mpr ⟨ by rw [ le_div_iff₀ ] <;> linarith [ Real.exp_pos x ], by rw [ div_le_iff₀ ] <;> linarith [ Real.exp_pos x ] ⟩;
  apply_rules [ lipschitzWith_of_nnnorm_deriv_le ];
  exact fun x => DifferentiableAt.log ( by norm_num [ Real.differentiableAt_exp ] ) ( by positivity )

/-- softplus is monotone. -/
theorem softplus_mono : Monotone softplus := by
  intro x y hxy
  unfold softplus
  apply Real.log_le_log (one_plus_exp_pos x)
  linarith [Real.exp_le_exp.mpr hxy]

/-- softplus is strictly monotone. -/
theorem softplus_strictMono : StrictMono softplus := by
  intro x y hxy
  unfold softplus
  apply Real.log_lt_log (one_plus_exp_pos x)
  linarith [Real.exp_lt_exp.mpr hxy]

/-- softplus has no fixed point: σ(x) > x for all x. -/
theorem softplus_gt_id (x : ℝ) : softplus x > x := by
  show x < softplus x
  unfold softplus
  rw [Real.lt_log_iff_exp_lt (one_plus_exp_pos x)]
  linarith

/-- softplus is differentiable everywhere. -/
theorem softplus_differentiable : Differentiable ℝ softplus := by
  intro x
  exact (hasDerivAt_softplus x).differentiableAt

/-- softplus is continuous. -/
theorem softplus_continuous : Continuous softplus :=
  softplus_differentiable.continuous

/-- softplus is injective (follows from strict monotonicity). -/
theorem softplus_injective : Function.Injective softplus :=
  softplus_strictMono.injective

end