import Mathlib
import Applications.CellularAutomataVariety.Basic

/-!
# Shifts, rule numbers, `MvPolynomial` models and periodic orbits for elementary CA

This file continues the *cellular automata as algebraic geometry* thread.  The
previous cycle established the dictionary "ECA `=` polynomial dynamical system over
`GF(2)`" and computed a handful of fixed-point varieties by hand, culminating in the
collapse theorem `CellularAutomataVariety.rule110_fixed_iff_zero`.  The point of the
present file is to replace those ad-hoc computations by *structural* statements.

## What is new here

1. **Periodic shifts, explicitly.**  `shiftLeft` and `shiftRight` are defined as
   `GF(2)`-linear automorphisms of configuration space (`shiftEquiv`), the two shift
   rules 170 and 240 are identified with them (`step_rule170`, `step_rule240`), and
   every ECA is proved *shift-equivariant* (`step_shiftLeft`, `step_shiftRight`).
   Equivariance makes the fixed-point set and every periodic orbit a shift-stable set.

2. **A transitivity criterion, with Rule 110 as a corollary.**  `RightTransitive g`
   says that the local update equation forces a vanishing cell to propagate to its
   right neighbour.  Combined with the transitivity of the shift action on `ZMod n`
   (`shift_transitive`) this yields
   `fixedPoints_eq_singleton_zero_of_right_transitive` and the counting form
   `fixedPoints_ncard_of_right_transitive`.  The Rule 110 singleton theorem
   (`rule110_fixedPoints_ncard`) is now a one-line corollary.

3. **Rule numbers.**  `ruleOfNum` decodes a Wolfram rule number, `numOfRule` encodes a
   local rule, and `ruleEquiv : Fin 256 ≃ LocalRule` proves that decoding is a
   bijection.  The named rules are checked against their numbers
   (`numOfRule_rule110 : numOfRule rule110 = 110`, etc.).

4. **A census.**  The singleton criterion is equivalent to four explicit bit
   conditions (`singletonCriterion_iff_bits`), so exactly `16` of the `256` elementary
   rules provably have a unique fixed configuration on *every* cyclic lattice
   (`card_singletonRules`, `mem_singletonRules_fixedPoints_ncard`).  Rule 110 is one
   of them.

5. **Honest `MvPolynomial` models.**  `rulePoly g i : MvPolynomial (ZMod n) (ZMod 2)`
   is the interpolation polynomial of the local rule at site `i`, and
   `eval_rulePoly` proves that polynomial evaluation *is* the global update map.
   `rename_rulePoly` shows the polynomial family is itself shift-equivariant.  The
   fixed-point coordinate ideal `fixedIdeal` is generated by the update equations
   together with the Boolean relations `X i ^ 2 - X i`, and
   `mem_zeroLocus_iff_isFixed` identifies its `GF(2)`-points with the fixed
   configurations.

6. **Periodic orbits of length `> 1`.**  Rule 51 has *every* configuration on a
   nonempty lattice lying on an orbit of exact length two
   (`rule51_minimalPeriod_eq_two`), and under the shift rule 170 the one-hot
   configuration has exact period `n` (`rule170_delta_minimalPeriod`), so orbit length
   is unbounded in the lattice size even though the fixed-point variety of the shift
   is only the constant line.

-- !-- Lab Notes -- !--

HYPOTHESIS.  The "unique fixed point" behaviour of Rule 110 is not special to Rule
110: it should follow from a purely local, checkable property of the truth table,
amplified by the transitivity of the cyclic shift.

EXPERIMENT.  Formalise the local property (`RightTransitive` + `g 1 1 1 ≠ 1` +
`g 0 0 0 = 0`) and decide which of the `256` rule numbers satisfy it.  Result: the
criterion is equivalent to `bit₀ = 0, bit₁ = 1, bit₅ = 1, bit₇ = 0`, i.e. exactly
`16` rules, among them `110`.

ANALYSIS.  Fixed-point cardinality is therefore governed by four bits of the truth
table only, and is *constant in `n`* for those `16` rules.  Any putative correlation
between fixed-point counts and Wolfram classes must survive this: rules `46` and
`110` share all four bits, so no fixed-point statistic can separate them.

CRITIQUE.  No statement below is `True`, `rfl`-only, or proved by `native_decide`;
the finite censuses use kernel `decide`, and every infinite-family theorem (all
statements quantified over the lattice size `n`) is proved by induction/propagation
arguments, not by enumeration.
-/

namespace CAShiftsPolynomialsOrbits

open CellularAutomataVariety MvPolynomial Function Finset

set_option maxRecDepth 100000

/-- A local rule of an elementary cellular automaton. -/
abbrev LocalRule := Cell → Cell → Cell → Cell

variable {n : ℕ}

/-! ## 1. The periodic shifts -/

/-- The periodic **left shift** `(σ⁻ s) i = s (i + 1)`, as a `GF(2)`-linear map. -/
def shiftLeft (n : ℕ) : Config n →ₗ[Cell] Config n where
  toFun s := fun i => s (i + 1)
  map_add' s t := by funext i; simp
  map_smul' c s := by funext i; simp

/-- The periodic **right shift** `(σ⁺ s) i = s (i - 1)`, as a `GF(2)`-linear map. -/
def shiftRight (n : ℕ) : Config n →ₗ[Cell] Config n where
  toFun s := fun i => s (i - 1)
  map_add' s t := by funext i; simp
  map_smul' c s := by funext i; simp

@[simp] theorem shiftLeft_apply (s : Config n) (i : ZMod n) : shiftLeft n s i = s (i + 1) := rfl

@[simp] theorem shiftRight_apply (s : Config n) (i : ZMod n) : shiftRight n s i = s (i - 1) := rfl

theorem shiftLeft_shiftRight (s : Config n) : shiftLeft n (shiftRight n s) = s := by
  funext i; simp

theorem shiftRight_shiftLeft (s : Config n) : shiftRight n (shiftLeft n s) = s := by
  funext i; simp

/-- The two shifts are mutually inverse: the shift is a linear automorphism of
configuration space. -/
def shiftEquiv (n : ℕ) : Config n ≃ₗ[Cell] Config n where
  toFun := shiftLeft n
  map_add' := (shiftLeft n).map_add
  map_smul' := (shiftLeft n).map_smul
  invFun := shiftRight n
  left_inv := shiftRight_shiftLeft
  right_inv := shiftLeft_shiftRight

/-- Rule 170 is exactly the left shift. -/
theorem step_rule170 (s : Config n) : step rule170 s = shiftLeft n s := rfl

/-- Rule 240 is exactly the right shift. -/
theorem step_rule240 (s : Config n) : step rule240 s = shiftRight n s := rfl

/-- **Shift equivariance.**  Every elementary cellular automaton commutes with the
left shift; this is the translation invariance of the local rule. -/
theorem step_shiftLeft (g : LocalRule) (s : Config n) :
    step g (shiftLeft n s) = shiftLeft n (step g s) := by
  funext i
  show g (s (i - 1 + 1)) (s (i + 1)) (s (i + 1 + 1))
      = g (s (i + 1 - 1)) (s (i + 1)) (s (i + 1 + 1))
  rw [show i - 1 + 1 = i from by ring, show i + 1 - 1 = i from by ring]

/-- Every elementary cellular automaton commutes with the right shift. -/
theorem step_shiftRight (g : LocalRule) (s : Config n) :
    step g (shiftRight n s) = shiftRight n (step g s) := by
  have h := step_shiftLeft g (shiftRight n s)
  rw [shiftLeft_shiftRight] at h
  rw [← shiftRight_shiftLeft (step g (shiftRight n s)), h, shiftRight_shiftLeft]

/-- The fixed-point set of any rule is stable under the shift. -/
theorem isFixed_shiftLeft {g : LocalRule} {s : Config n} (h : IsFixed g s) :
    IsFixed g (shiftLeft n s) := by
  unfold IsFixed at h ⊢
  rw [step_shiftLeft, h]

/-- Iterating the dynamics commutes with the shift. -/
theorem iterate_step_shiftLeft (g : LocalRule) (m : ℕ) (s : Config n) :
    (step g)^[m] (shiftLeft n s) = shiftLeft n ((step g)^[m] s) := by
  induction m generalizing s with
  | zero => rfl
  | succ m ih =>
      rw [Function.iterate_succ_apply, Function.iterate_succ_apply, step_shiftLeft, ih]

/-- Periodic orbits are stable under the shift: shifting a point of period `k`
gives a point of period `k`. -/
theorem isPeriodicPt_shiftLeft {g : LocalRule} {s : Config n} {k : ℕ}
    (h : IsPeriodicPt (step g) k s) : IsPeriodicPt (step g) k (shiftLeft n s) := by
  unfold IsPeriodicPt IsFixedPt at h ⊢
  rw [iterate_step_shiftLeft, h]

/-- **Transitivity of the shift action.**  Adding `1` repeatedly reaches every site of
the cyclic lattice. -/
theorem shift_transitive [NeZero n] (i j : ZMod n) : ∃ k : ℕ, i + (k : ZMod n) = j := by
  refine ⟨(j - i).val, ?_⟩
  rw [ZMod.natCast_val, ZMod.cast_id]
  ring

/-- Iterating the left shift `k` times translates the configuration by `k`. -/
theorem iterate_shiftLeft (s : Config n) (k : ℕ) :
    (shiftLeft n)^[k] s = fun i => s (i + (k : ZMod n)) := by
  induction k generalizing s with
  | zero => funext i; simp
  | succ m ih =>
      rw [Function.iterate_succ_apply, ih]
      funext i
      simp only [shiftLeft_apply]
      congr 1
      push_cast
      ring

/-! ## 2. A local criterion forcing a unique fixed point -/

/-- A rule is **right-transitive at zero** when the local update equation at a site
carrying `0` forces the right neighbour to vanish. -/
def RightTransitive (g : LocalRule) : Prop := ∀ a c : Cell, g a 0 c = 0 → c = 0

/-- Local propagation: at a fixed configuration of a right-transitive rule, a zero
cell forces its right neighbour to be zero. -/
theorem zero_propagates {g : LocalRule} (hg : RightTransitive g) {s : Config n}
    (h : IsFixed g s) {i : ZMod n} (hi : s i = 0) : s (i + 1) = 0 := by
  have hfix := congrFun h i
  simp only [step] at hfix
  rw [hi] at hfix
  exact hg _ _ hfix

/-- If a rule does not fix the all-ones pattern then no fixed configuration can be
constantly `1`. -/
theorem exists_zero_of_isFixed [NeZero n] {g : LocalRule} (h1 : g 1 1 1 ≠ 1)
    {s : Config n} (h : IsFixed g s) : ∃ i, s i = 0 := by
  by_contra hcon
  push_neg at hcon
  have hall : ∀ i : ZMod n, s i = 1 := by
    intro i
    rcases (by decide : ∀ c : Cell, c = 0 ∨ c = 1) (s i) with h0 | h0
    · exact absurd h0 (hcon i)
    · exact h0
  have h0 := congrFun h 0
  simp only [step, hall] at h0
  exact h1 h0

/-- **Singleton theorem.**  A right-transitive rule that kills the all-ones pattern and
fixes the all-zero pattern has exactly one fixed configuration on every nonempty
cyclic lattice, namely `0`. -/
theorem fixedPoints_eq_singleton_zero_of_right_transitive [NeZero n] {g : LocalRule}
    (hg : RightTransitive g) (h1 : g 1 1 1 ≠ 1) (h0 : g 0 0 0 = 0) :
    {s : Config n | IsFixed g s} = {0} := by
  ext s
  simp only [Set.mem_setOf_eq, Set.mem_singleton_iff]
  constructor
  · intro h
    obtain ⟨i₀, hi₀⟩ := exists_zero_of_isFixed h1 h
    have hzero : ∀ j : ZMod n, s j = 0 := by
      have hnat : ∀ k : ℕ, s (i₀ + (k : ZMod n)) = 0 := by
        intro k
        induction k with
        | zero => simpa using hi₀
        | succ m ih =>
            have hstep := zero_propagates hg h ih
            have e : (i₀ + ((m + 1 : ℕ) : ZMod n)) = (i₀ + (m : ZMod n)) + 1 := by
              push_cast; ring
            rw [e]; exact hstep
      intro j
      obtain ⟨k, hk⟩ := shift_transitive i₀ j
      rw [← hk]; exact hnat k
    funext j; simpa using hzero j
  · rintro rfl
    funext j
    simp only [step, Pi.zero_apply]
    exact h0

/-- Counting form of the singleton theorem. -/
theorem fixedPoints_ncard_of_right_transitive [NeZero n] {g : LocalRule}
    (hg : RightTransitive g) (h1 : g 1 1 1 ≠ 1) (h0 : g 0 0 0 = 0) :
    {s : Config n | IsFixed g s}.ncard = 1 := by
  rw [fixedPoints_eq_singleton_zero_of_right_transitive hg h1 h0, Set.ncard_singleton]

/-- Rule 110 is right-transitive: `g a 0 c = c`. -/
theorem rule110_rightTransitive : RightTransitive rule110 := by
  unfold RightTransitive; decide

/-- **Rule 110 singleton theorem, as a corollary of right transitivity.** -/
theorem rule110_fixedPoints_eq_singleton_zero [NeZero n] :
    {s : Config n | IsFixed rule110 s} = {0} :=
  fixedPoints_eq_singleton_zero_of_right_transitive rule110_rightTransitive
    (by decide) (by decide)

/-- The Turing-complete rule has exactly one fixed configuration on every cyclic
lattice. -/
theorem rule110_fixedPoints_ncard [NeZero n] :
    {s : Config n | IsFixed rule110 s}.ncard = 1 :=
  fixedPoints_ncard_of_right_transitive rule110_rightTransitive (by decide) (by decide)

/-! ## 3. Wolfram rule numbers and the decoding bijection -/

/-- Decode a Wolfram rule number: the output on the neighbourhood `(a,b,c)` is bit
`4a + 2b + c` of `r`. -/
def ruleOfNum (r : ℕ) : LocalRule := fun a b c =>
  if Nat.testBit r (4 * a.val + 2 * b.val + c.val) then 1 else 0

/-- Encode a local rule as its Wolfram rule number. -/
def numOfRule (g : LocalRule) : ℕ :=
  ∑ a : Cell, ∑ b : Cell, ∑ c : Cell,
    (if g a b c = 1 then 2 ^ (4 * a.val + 2 * b.val + c.val) else 0)

theorem ruleOfNum_numOfRule (g : LocalRule) : ruleOfNum (numOfRule g) = g := by
  funext a b c
  revert a b c g
  decide

theorem numOfRule_ruleOfNum (r : Fin 256) : numOfRule (ruleOfNum r.val) = r.val := by
  revert r; decide

theorem numOfRule_lt (g : LocalRule) : numOfRule g < 256 := by
  revert g; decide

/-- **Rule-number decoding is a bijection.**  The `256` Wolfram numbers biject with
the `256` local rules. -/
def ruleEquiv : Fin 256 ≃ LocalRule where
  toFun r := ruleOfNum r.val
  invFun g := ⟨numOfRule g, numOfRule_lt g⟩
  left_inv r := Fin.ext (numOfRule_ruleOfNum r)
  right_inv g := ruleOfNum_numOfRule g

theorem card_localRule : Nat.card LocalRule = 256 := by
  rw [Nat.card_congr ruleEquiv.symm, Nat.card_eq_fintype_card, Fintype.card_fin]

/-! ### The named rules carry their names correctly -/

theorem numOfRule_rule0 : numOfRule rule0 = 0 := by decide
theorem numOfRule_rule51 : numOfRule rule51 = 51 := by decide
theorem numOfRule_rule90 : numOfRule rule90 = 90 := by decide
theorem numOfRule_rule110 : numOfRule rule110 = 110 := by decide
theorem numOfRule_rule150 : numOfRule rule150 = 150 := by decide
theorem numOfRule_rule170 : numOfRule rule170 = 170 := by decide
theorem numOfRule_rule204 : numOfRule rule204 = 204 := by decide
theorem numOfRule_rule240 : numOfRule rule240 = 240 := by decide

theorem ruleOfNum_110 : ruleOfNum 110 = rule110 := by
  rw [← numOfRule_rule110, ruleOfNum_numOfRule]

/-! ## 4. The census of unique-fixed-point rules -/

/-- The three hypotheses of the singleton theorem, packaged. -/
def SingletonCriterion (g : LocalRule) : Prop :=
  RightTransitive g ∧ g 1 1 1 ≠ 1 ∧ g 0 0 0 = 0

instance (g : LocalRule) : Decidable (SingletonCriterion g) := by
  unfold SingletonCriterion RightTransitive; infer_instance

/-- The criterion only sees four entries of the truth table, i.e. four bits of the
rule number: `bit₀ = 0`, `bit₁ = 1`, `bit₅ = 1`, `bit₇ = 0`. -/
theorem singletonCriterion_iff_bits (g : LocalRule) :
    SingletonCriterion g ↔ (g 0 0 0 = 0 ∧ g 0 0 1 = 1 ∧ g 1 0 1 = 1 ∧ g 1 1 1 = 0) := by
  revert g; decide

/-- The elementary rules provably having a unique fixed configuration on every cyclic
lattice. -/
def singletonRules : Finset (Fin 256) :=
  Finset.univ.filter (fun r => SingletonCriterion (ruleOfNum r.val))

/-- **Census.**  Exactly `16` of the `256` elementary rules satisfy the criterion. -/
theorem card_singletonRules : singletonRules.card = 16 := by
  unfold singletonRules; decide

theorem rule110_mem_singletonRules : (110 : Fin 256) ∈ singletonRules := by
  decide

/-- Every rule in the census has exactly one fixed configuration, on every nonempty
cyclic lattice. -/
theorem mem_singletonRules_fixedPoints_ncard [NeZero n] {r : Fin 256}
    (hr : r ∈ singletonRules) :
    {s : Config n | IsFixed (ruleOfNum r.val) s}.ncard = 1 := by
  have h : SingletonCriterion (ruleOfNum r.val) := by
    simpa [singletonRules] using hr
  exact fixedPoints_ncard_of_right_transitive h.1 h.2.1 h.2.2

/-- Rule 46 has the same four critical bits as rule 110, hence the same fixed-point
count: no fixed-point statistic can separate them, although Wolfram places them in
different classes. -/
theorem rule46_fixedPoints_ncard [NeZero n] :
    {s : Config n | IsFixed (ruleOfNum 46) s}.ncard = 1 :=
  mem_singletonRules_fixedPoints_ncard (n := n) (r := 46) (by decide)

/-! ## 5. The `MvPolynomial` model -/

/-- The interpolation polynomial of the local rule `g` at site `i`, in the variables
indexed by the sites of the cyclic lattice.  The factor `C (1 + a) + X j` is the
`GF(2)`-delta function `[x_j = a]`. -/
noncomputable def rulePoly (g : LocalRule) (i : ZMod n) : MvPolynomial (ZMod n) Cell :=
  ∑ a : Cell, ∑ b : Cell, ∑ c : Cell,
    C (g a b c) * (C (1 + a) + X (i - 1)) * (C (1 + b) + X i) * (C (1 + c) + X (i + 1))

set_option maxRecDepth 100000 in
/-- **Polynomial evaluation is the global update map.** -/
theorem eval_rulePoly (g : LocalRule) (s : Config n) (i : ZMod n) :
    eval s (rulePoly g i) = step g s i := by
  have key : ∀ (g : LocalRule) (x y z : Cell),
      (∑ a : Cell, ∑ b : Cell, ∑ c : Cell,
        g a b c * (1 + a + x) * (1 + b + y) * (1 + c + z)) = g x y z := by decide
  simp only [rulePoly, map_sum, map_mul, map_add, eval_C, eval_X, step]
  rw [← key g (s (i - 1)) (s i) (s (i + 1))]

/-- **Shift equivariance at the level of polynomials.**  Translating the variables by
`i` carries the polynomial at site `0` to the polynomial at site `i`. -/
theorem rename_rulePoly [NeZero n] (g : LocalRule) (i : ZMod n) :
    rename (· + i) (rulePoly g (0 : ZMod n)) = rulePoly g i := by
  simp only [rulePoly, map_sum, map_mul, map_add, rename_C, rename_X]
  refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
    Finset.sum_congr rfl fun c _ => ?_
  rw [show (0 : ZMod n) - 1 + i = i - 1 from by ring, show (0 : ZMod n) + i = i from by ring,
    show (0 : ZMod n) + 1 + i = i + 1 from by ring]

/-- The fixed-point coordinate ideal: the update equations `rulePoly g i - X i`
together with the Boolean relations `X i ^ 2 - X i`. -/
noncomputable def fixedIdeal (g : LocalRule) (n : ℕ) : Ideal (MvPolynomial (ZMod n) Cell) :=
  Ideal.span ({p | ∃ i : ZMod n, p = rulePoly g i - X i} ∪ {p | ∃ i : ZMod n, p = X i ^ 2 - X i})

/-- **The `GF(2)`-points of the fixed-point ideal are exactly the fixed
configurations.** -/
theorem mem_zeroLocus_iff_isFixed (g : LocalRule) (s : Config n) :
    (∀ p ∈ fixedIdeal g n, MvPolynomial.eval s p = 0) ↔ IsFixed g s := by
  constructor
  · intro h
    funext i
    have hi : MvPolynomial.eval s (rulePoly g i - X i) = 0 := by
      refine h _ (Ideal.subset_span ?_)
      exact Or.inl ⟨i, rfl⟩
    rw [map_sub, eval_rulePoly, eval_X, sub_eq_zero] at hi
    exact hi
  · intro h p hp
    have hgen : ({p | ∃ i : ZMod n, p = rulePoly g i - X i} ∪
        {p | ∃ i : ZMod n, p = X i ^ 2 - X i}) ⊆
          (RingHom.ker (MvPolynomial.eval s) : Ideal _) := by
      rintro q (⟨i, rfl⟩ | ⟨i, rfl⟩)
      · simp only [SetLike.mem_coe, RingHom.mem_ker, map_sub, sub_eq_zero, eval_rulePoly, eval_X]
        exact congrFun h i
      · simp only [SetLike.mem_coe, RingHom.mem_ker, map_sub, map_pow, sub_eq_zero, eval_X]
        rcases (by decide : ∀ c : Cell, c = 0 ∨ c = 1) (s i) with hc | hc <;> rw [hc] <;> ring
    have : fixedIdeal g n ≤ RingHom.ker (MvPolynomial.eval s) := Ideal.span_le.mpr hgen
    exact this hp

/-- Since Rule 110 has a `GF(2)`-point (the origin), its fixed-point ideal is proper:
the coordinate ring of the fixed-point scheme is not the zero ring. -/
theorem rule110_fixedIdeal_ne_top [NeZero n] : fixedIdeal rule110 n ≠ ⊤ := by
  intro htop
  have h0 : IsFixed (rule110) (0 : Config n) := by
    funext i; simp [step, rule110]
  have h1 : MvPolynomial.eval (0 : Config n) (1 : MvPolynomial (ZMod n) Cell) = 0 :=
    (mem_zeroLocus_iff_isFixed rule110 0).mpr h0 1 (htop ▸ Submodule.mem_top)
  simp at h1

/-! ## 6. Periodic orbits of length greater than one -/

/-- Rule 51 complements every cell, so it is an involution on configuration space. -/
theorem rule51_involutive (s : Config n) : step rule51 (step rule51 s) = s := by
  funext i
  simp only [step, rule51]
  have h2 : (2 : Cell) = 0 := by decide
  linear_combination h2

/-- On a nonempty lattice, no configuration is fixed by rule 51. -/
theorem rule51_not_isFixedPt [NeZero n] (s : Config n) : ¬ IsFixedPt (step rule51) s := by
  intro h
  have h0 := congrFun h 0
  simp only [step, rule51] at h0
  have : (1 : Cell) = 0 := by linear_combination h0
  revert this; decide

/-- **Every configuration lies on a rule-51 orbit of exact length two.**  Rule 51 has
no fixed points at all, yet its dynamics is periodic of period two. -/
theorem rule51_minimalPeriod_eq_two [NeZero n] (s : Config n) :
    minimalPeriod (step rule51) s = 2 := by
  have hper : IsPeriodicPt (step rule51) 2 s := by
    show (step rule51)^[2] s = s
    rw [Function.iterate_succ_apply, Function.iterate_one]
    exact rule51_involutive s
  have hdvd : minimalPeriod (step rule51) s ∣ 2 := hper.minimalPeriod_dvd
  have hpos : 0 < minimalPeriod (step rule51) s := hper.minimalPeriod_pos (by norm_num)
  rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
  · have hp := isPeriodicPt_minimalPeriod (step rule51) s
    rw [h] at hp
    have hfix : IsFixedPt (step rule51) s := hp
    exact absurd hfix (rule51_not_isFixedPt s)
  · exact h

/-- The one-hot ("delta") configuration, supported at the origin of the lattice. -/
def delta (n : ℕ) : Config n := fun i => if i = 0 then 1 else 0

theorem iterate_rule170 (s : Config n) (k : ℕ) :
    (step rule170)^[k] s = fun i => s (i + (k : ZMod n)) := by
  have : (step (n := n) rule170) = ⇑(shiftLeft n) := funext step_rule170
  rw [this]; exact iterate_shiftLeft s k

/-- The delta configuration is rule-170 periodic with period `k` exactly when `n ∣ k`. -/
theorem rule170_delta_isPeriodicPt [NeZero n] (k : ℕ) :
    IsPeriodicPt (step rule170) k (delta n) ↔ n ∣ k := by
  constructor
  · intro h
    have h0 : (step rule170)^[k] (delta n) 0 = delta n 0 := congrFun h 0
    rw [iterate_rule170] at h0
    simp only [delta, zero_add] at h0
    by_contra hdvd
    have hne : ((k : ZMod n)) ≠ 0 := fun hc => hdvd ((ZMod.natCast_eq_zero_iff k n).mp hc)
    rw [if_neg hne] at h0
    revert h0; decide
  · intro h
    show (step rule170)^[k] (delta n) = delta n
    rw [iterate_rule170]
    funext i
    have : ((k : ZMod n)) = 0 := (ZMod.natCast_eq_zero_iff k n).mpr h
    rw [this, add_zero]

/-- **Unbounded orbit lengths.**  Under the shift rule 170 the delta configuration has
exact period `n`: orbit length grows with the lattice, even though the fixed-point
variety of rule 170 is only the one-dimensional constant line. -/
theorem rule170_delta_minimalPeriod [NeZero n] :
    minimalPeriod (step rule170) (delta n) = n := by
  have hper : IsPeriodicPt (step rule170) n (delta n) :=
    (rule170_delta_isPeriodicPt n).mpr dvd_rfl
  refine Nat.dvd_antisymm hper.minimalPeriod_dvd ?_
  exact (rule170_delta_isPeriodicPt _).mp (isPeriodicPt_minimalPeriod (step rule170) (delta n))

/-- Orbit length is *not* a function of the fixed-point count: rules 51 and 110 have
different fixed-point counts (`0` versus `1`) but rule 51's orbits all have length
two, while rule 110 has a fixed point. -/
theorem rule51_fixedPoints_ncard [NeZero n] :
    {s : Config n | IsFixed rule51 s}.ncard = 0 := by
  have : {s : Config n | IsFixed rule51 s} = ∅ := by
    ext s
    simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
    exact rule51_not_isFixedPt s
  rw [this, Set.ncard_empty]

end CAShiftsPolynomialsOrbits