#!/usr/bin/env python3
"""PiAgentClient v3: Pi-Agent as the central brain using glm-5.1:cloud.

Key changes from v2:
- Uses httpx HTTP API (not subprocess) to call ollama
- Model: glm-5.1:cloud
- Dynamically writes Aristotle prompts (no templates)
- Has full Catalog awareness via CatalogAnalyzer
- Evaluates Aristotle results for quality
- Classifies file placement into domain directories
- Supports research modes: prove, formalize, counterexample, sorry_fill
"""

import json
import re
import textwrap
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Any

import httpx

from catalog_analyzer import CatalogAnalyzer, CatalogFileSummary
from research_memory import ResearchMemory


@dataclass
class ResearchConcept:
    """A concept mined or generated by pi-agent."""
    title: str
    domain: str
    concept_description: str
    mathematical_framing: str
    lean_guess: str = ""
    novelty_estimate: float = 0.0
    breakthrough_potential: float = 0.0
    key_references: List[str] = field(default_factory=list)
    catalog_references: List[str] = field(default_factory=list)
    research_mode: str = "prove"  # prove | formalize | counterexample | sorry_fill


# System prompts for each Pi-Agent function
_DIRECTION_SYSTEM_PROMPT = textwrap.dedent("""\
    You are Pi-Agent, an elite mathematical research director. Your role is to
    analyze a theorem catalog, identify gaps and novel research directions, and
    select the most promising area for investigation.

    You have access to the full catalog summary and recent experiment history.
    Your goal is to pick a domain and concept that will produce interesting,
    novel, and formally provable results. Avoid repetition with recent experiments.

    You MUST respond with valid JSON only. No markdown, no commentary outside the JSON.
""")

_PROMPT_WRITING_SYSTEM_PROMPT = textwrap.dedent("""\
    You are Pi-Agent, an expert at crafting research briefs for a brilliant
    formal mathematician named Aristotle. Aristotle works in Lean 4 and has
    access to the full Mathlib library.

    Your job is to write compelling, open-ended research briefs that inspire
    Aristotle to produce interesting, novel, and rigorous mathematical results.
    You are NOT writing a template or filling in blanks. You are writing a
    genuine research communication from one mathematician to another.

    Key principles:
    - Be specific about what you want, but leave room for Aristotle's creativity
    - Reference specific theorems, definitions, and structures from the catalog
    - Explain WHY this direction is interesting, not just WHAT to prove
    - Choose the research mode that best fits the concept:
        - "prove": Prove a new theorem
        - "formalize": Formalize informal mathematics from notes/papers
        - "counterexample": Find a counterexample to a conjecture
        - "sorry_fill": Complete existing proofs that have sorry placeholders
    - The brief should feel like a research direction from a colleague, not a
      homework assignment

    You MUST respond with the complete prompt text only. No JSON wrapper, no
    metadata, just the prompt that will be sent directly to Aristotle.
""")

_QUALITY_SYSTEM_PROMPT = textwrap.dedent("""\
    You are Pi-Agent, evaluating the quality of a formal proof result from
    Aristotle (a Lean 4 theorem prover). You must assess whether the result
    is trivial, partial, or substantial.

    Criteria:
    - TRIVIAL: Proves tautologies (True := by trivial), uses only trivial tactics,
      proves statements that are obviously true, or has no mathematical depth
    - PARTIAL: Has some substance but contains many sorries, is incomplete, or
      proves only simple corollaries while leaving the main claim unproven
    - SUBSTANTIAL: Proves a non-trivial theorem with a complete or nearly complete
      proof, uses interesting tactics or mathematical insights, contributes
      genuinely new mathematics

    You MUST respond with valid JSON only: {"quality": "trivial|partial|substantial",
    "should_retry": bool, "retry_strategy": "...", "confidence": 0.0-1.0,
    "analysis": "..."}
""")

_CLASSIFICATION_SYSTEM_PROMPT = textwrap.dedent("""\
    You are Pi-Agent, classifying a Lean 4 theorem file into the correct domain
    in a mathematical catalog. The catalog has these domains:

    Algebra, Bridges, Computation, Cryptography, EML, Geometry, Logic,
    MachineLearning, Physics, Pythagorean, Shared, Speculative, Tropical

    Based on the mathematical content of the file, choose the most appropriate
    domain and subdirectory. Consider the main definitions, theorem statements,
    and mathematical concepts used.

    You MUST respond with valid JSON only: {"domain": "...", "subdirectory": "...",
    "target_path": "...", "is_complete_proof": bool, "confidence": 0.0-1.0,
    "reason": "..."}
""")


class PiAgentClient:
    """v3 Pi-Agent client: glm-5.1:cloud via ollama HTTP API.

    The brain of Aether v3. Handles:
    - Research direction selection
    - Dynamic prompt writing
    - Result quality evaluation
    - File classification and placement
    """

    OLLAMA_BASE_URL = "http://127.0.0.1:11434"

    def __init__(
        self,
        model: str = "glm-5.1:cloud",
        memory: Optional[ResearchMemory] = None,
        catalog_root: Optional[Path] = None,
        timeout: int = 300,
    ):
        self.model = model
        self.memory = memory
        self.catalog_root = Path(catalog_root) if catalog_root else None
        self.timeout = timeout
        self.client = httpx.Client(timeout=timeout)

        # CatalogAnalyzer for reference selection
        self.catalog_analyzer: Optional[CatalogAnalyzer] = None
        if self.catalog_root and self.catalog_root.exists():
            self.catalog_analyzer = CatalogAnalyzer(self.catalog_root)

    def _call_ollama(self, system: str, user: str) -> str:
        """Call ollama HTTP API with system + user prompts. Returns raw text."""
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "stream": False,
            "options": {
                "temperature": 0.85,
                "top_p": 0.92,
                "num_predict": 4096,
            },
        }
        try:
            response = self.client.post(
                f"{self.OLLAMA_BASE_URL}/api/chat",
                json=payload,
                timeout=self.timeout,
            )
            response.raise_for_status()
            data = response.json()
            content = data.get("message", {}).get("content", "")
            if not content:
                content = data.get("response", "")
            return content
        except httpx.TimeoutException:
            return f"[OLLAMA_TIMEOUT: Request timed out after {self.timeout}s]"
        except httpx.HTTPStatusError as e:
            return f"[OLLAMA_HTTP_ERROR: {e.response.status_code} {e.response.text[:200]}]"
        except Exception as e:
            return f"[OLLAMA_ERROR: {e}]"

    def _parse_json_response(self, raw: str) -> Optional[Dict[str, Any]]:
        """Try to extract JSON from an LLM response."""
        # Try direct parse
        try:
            return json.loads(raw.strip())
        except json.JSONDecodeError:
            pass

        # Try to find JSON in markdown code block
        json_match = re.search(r'```(?:json)?\s*\n?(.*?)\n?```', raw, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group(1).strip())
            except json.JSONDecodeError:
                pass

        # Try to find JSON object anywhere in the text
        json_match = re.search(r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}', raw, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group())
            except json.JSONDecodeError:
                pass

        return None

    # ------------------------------------------------------------------
    # Research direction selection
    # ------------------------------------------------------------------

    def select_research_direction(
        self,
        domains: List[Dict[str, Any]],
        recent_history: Optional[List[Dict]] = None,
    ) -> ResearchConcept:
        """Pi-Agent analyzes the Catalog and picks a research direction.

        Returns a ResearchConcept with domain, concept details, catalog references,
        and research_mode chosen by the LLM.
        """
        # Build catalog summary
        catalog_summary = ""
        if self.catalog_analyzer:
            self.catalog_analyzer.scan()
            catalog_summary = self.catalog_analyzer.get_domain_summary_for_prompt()

        # Build exclusion prompt from memory
        exclusion = ""
        if self.memory:
            exclusion = self.memory.build_exclusion_prompt()

        # Build success patterns from memory
        success_patterns = ""
        if self.memory:
            success_patterns = self.memory.build_success_patterns()

        # Build domain list for prompt
        domain_descriptions = []
        for d in domains:
            domain_descriptions.append(
                f"- {d.get('id', d.get('name', '?'))}: {d.get('description', d.get('name', '?'))} "
                f"(frontier: {d.get('frontier', 'open')}, "
                f"seed domains: {', '.join(str(x) for x in d.get('seed_domains', d.get('seed_concepts', []))[:3])})"
            )

        user_prompt = textwrap.dedent(f"""\
            Select the most promising research direction for this cycle.

            ## Available Domains
            {chr(10).join(domain_descriptions)}

            ## Catalog Summary
            {catalog_summary if catalog_summary else "No catalog summary available."}

            ## Recent Experiments (avoid repeating these)
            {exclusion if exclusion else "No recent experiments."}

            ## Successful Patterns (emulate these)
            {success_patterns if success_patterns else "No successful patterns yet."}

            Select ONE domain and ONE specific concept to investigate. Choose something
            novel, interesting, and likely to produce substantial formal mathematics.

            Respond with JSON:
            {{
              "domain": "domain_id",
              "concept_title": "snake_case_title_for_the_theorem",
              "concept_description": "2-3 sentence description of the concept and why it matters",
              "mathematical_framing": "formal mathematical statement or sketch",
              "lean_guess": "optional Lean 4 sketch of the theorem statement",
              "catalog_references": ["Domain/Subdir/File.lean", ...],
              "research_mode": "prove|formalize|counterexample|sorry_fill",
              "novelty_estimate": 0.0-1.0,
              "breakthrough_potential": 0.0-1.0,
              "key_references": ["reference1", "reference2"]
            }}
        """)

        raw = self._call_ollama(_DIRECTION_SYSTEM_PROMPT, user_prompt)
        parsed = self._parse_json_response(raw)

        if parsed:
            return ResearchConcept(
                title=parsed.get("concept_title", "unnamed_concept"),
                domain=parsed.get("domain", domains[0]["id"] if domains else "speculative"),
                concept_description=parsed.get("concept_description", ""),
                mathematical_framing=parsed.get("mathematical_framing", ""),
                lean_guess=parsed.get("lean_guess", ""),
                catalog_references=parsed.get("catalog_references", []),
                research_mode=parsed.get("research_mode", "prove"),
                novelty_estimate=float(parsed.get("novelty_estimate", 0.5)),
                breakthrough_potential=float(parsed.get("breakthrough_potential", 0.5)),
                key_references=parsed.get("key_references", []),
            )

        # Fallback: pick a random domain
        import random
        domain = random.choice(domains) if domains else {"id": "speculative", "name": "Speculative"}
        return ResearchConcept(
            title=f"research_concept_{int(time.time())}",
            domain=domain.get("id", "speculative"),
            concept_description="Auto-generated research direction.",
            mathematical_framing="TBD",
            research_mode="prove",
        )

    # ------------------------------------------------------------------
    # Dynamic prompt writing
    # ------------------------------------------------------------------

    def write_aristotle_prompt(
        self,
        concept: ResearchConcept,
        catalog_references: Optional[List[str]] = None,
        catalog_context: str = "",
        recent_successes: Optional[List[Dict]] = None,
        recent_failures: Optional[List[Dict]] = None,
    ) -> str:
        """Dynamically write the full Aristotle prompt.

        Pi-Agent receives the concept, the referenced Catalog files,
        and research history. It writes the entire prompt text --
        research brief, context, instructions, deliverables.

        This replaces PromptEngine entirely. No templates.
        """
        refs = catalog_references or concept.catalog_references or []

        # Build reference section
        ref_section = ""
        if refs and self.catalog_analyzer:
            ref_section = self.catalog_analyzer.build_catalog_context_string(refs)
        elif catalog_context:
            ref_section = catalog_context

        # Research mode instructions
        mode_instructions = {
            "prove": textwrap.dedent("""\
                Research Mode: PROVE

                You are asked to discover and prove a new theorem. Start from the
                mathematical context provided and find an interesting, non-trivial
                result that can be formally proven in Lean 4. The theorem should be
                specific enough to prove, but general enough to be mathematically
                interesting. Avoid trivial tautologies.
            """),
            "formalize": textwrap.dedent("""\
                Research Mode: FORMALIZE

                You are given informal mathematical ideas, notes, or a paper excerpt.
                Your task is to formalize these ideas in Lean 4. Translate the
                informal mathematics into precise definitions and theorem statements,
                then prove what you can. If some parts require new axioms, declare
                them clearly and prove consequences.
            """),
            "counterexample": textwrap.dedent("""\
                Research Mode: COUNTEREXAMPLE

                You are asked to find a counterexample to a stated conjecture. If
                the conjecture is false, provide a specific counterexample formalized
                in Lean 4 and prove that it contradicts the conjecture. If the
                conjecture is actually true, prove it instead.
            """),
            "sorry_fill": textwrap.dedent("""\
                Research Mode: SORRY_FILL

                You are given Lean 4 files that contain `sorry` placeholders. Your
                task is to fill in all `sorry` placeholders with complete, rigorous
                proofs. Use the surrounding context and imports to determine the
                correct proof strategy. Do not change the theorem statements.
            """),
        }

        mode_instruction = mode_instructions.get(concept.research_mode, mode_instructions["prove"])

        # Build history section
        history_section = ""
        if recent_successes:
            success_titles = [s.get("concept_title", s.get("title", "?")) for s in recent_successes[:5]]
            history_section += f"\nRecent successful concepts: {', '.join(success_titles)}\n"
        if recent_failures:
            failure_titles = [f.get("concept_title", f.get("title", "?")) for f in recent_failures[:5]]
            failure_reasons = [f.get("reason", "unknown") for f in recent_failures[:5]]
            history_section += f"\nRecent failures (avoid these approaches): "
            for title, reason in zip(failure_titles, failure_reasons):
                history_section += f"\n  - {title}: {reason}"

        user_prompt = textwrap.dedent(f"""\
            Write a research brief for Aristotle, a brilliant Lean 4 formal
            mathematician. The brief should be open-ended, inspiring, and specific.

            ## Concept to Investigate
            - Title: {concept.title}
            - Domain: {concept.domain}
            - Description: {concept.concept_description}
            - Mathematical Framing: {concept.mathematical_framing}
            {"- Lean Sketch: " + concept.lean_guess if concept.lean_guess else ""}
            - Research Mode: {concept.research_mode}

            {mode_instruction}

            ## Catalog Context
            The theorem catalog has these relevant files that you should study as
            context. They contain existing theorems, definitions, and structures
            that you can build upon:

            {ref_section if ref_section else "No specific files referenced. Use Mathlib and general knowledge."}

            {history_section if history_section else ""}

            ## Deliverables
            Produce a complete Lean 4 file with:
            1. All necessary imports (import Mathlib)
            2. Any new definitions needed for the theorem
            3. The theorem statement(s) with complete proofs
            4. Brief comments explaining the proof strategy (using -- comments)

            Additionally produce:
            - A research report (RESEARCH_REPORT.md) explaining the mathematical
              significance, the proof approach, and connections to existing work
            - A Python demonstration (demo.py) showing the key idea with concrete
              examples using only stdlib
            - An SVG diagram (diagram.svg) visualizing the main concept
            - A discussion article (DISCUSSION.md) written in Scientific American
              style, accessible to a general audience

            Write the complete research brief now. Be specific, creative, and
            mathematically rigorous. This is a conversation between mathematicians,
            not a homework assignment.
        """)

        raw = self._call_ollama(_PROMPT_WRITING_SYSTEM_PROMPT, user_prompt)
        return raw if raw and not raw.startswith("[OLLAMA") else user_prompt

    # ------------------------------------------------------------------
    # Result quality evaluation
    # ------------------------------------------------------------------

    def evaluate_result_quality(
        self,
        result_lean: str,
        concept: ResearchConcept,
        prompt: str,
    ) -> Dict[str, Any]:
        """Pi-Agent evaluates the quality of an Aristotle result.

        Returns: {
            "quality": "trivial" | "partial" | "substantial",
            "should_retry": bool,
            "retry_strategy": str,
            "confidence": float,
            "analysis": str
        }
        """
        # Truncate very long results for the LLM
        lean_preview = result_lean[:3000] if len(result_lean) > 3000 else result_lean

        # Quick heuristic pre-check
        if self._is_trivially_obvious(lean_preview):
            return {
                "quality": "trivial",
                "should_retry": True,
                "retry_strategy": "Result is trivially obvious. Request a more specific, non-trivial theorem.",
                "confidence": 0.9,
                "analysis": "Heuristic: contains trivial proof patterns.",
            }

        user_prompt = textwrap.dedent(f"""\
            Evaluate this Lean 4 proof result.

            ## Original Concept
            - Title: {concept.title}
            - Domain: {concept.domain}
            - Research Mode: {concept.research_mode}
            - Description: {concept.concept_description[:500]}

            ## Lean 4 Result
            ```lean
            {lean_preview}
            ```

            Is this result trivial, partial, or substantial? Consider:
            - Does it prove something mathematically interesting and non-obvious?
            - Is the proof complete or does it have many sorries?
            - Does it contribute new mathematics or just restate known facts?

            Respond with JSON:
            {{
              "quality": "trivial|partial|substantial",
              "should_retry": true/false,
              "retry_strategy": "what to change if retrying",
              "confidence": 0.0-1.0,
              "analysis": "brief explanation"
            }}
        """)

        raw = self._call_ollama(_QUALITY_SYSTEM_PROMPT, user_prompt)
        parsed = self._parse_json_response(raw)

        if parsed:
            return {
                "quality": parsed.get("quality", "partial"),
                "should_retry": parsed.get("should_retry", True),
                "retry_strategy": parsed.get("retry_strategy", ""),
                "confidence": float(parsed.get("confidence", 0.5)),
                "analysis": parsed.get("analysis", ""),
            }

        # Fallback: heuristic evaluation
        sorry_count = lean_preview.count("sorry")
        theorem_count = lean_preview.count("theorem ") + lean_preview.count("lemma ")
        if sorry_count == 0 and theorem_count > 0:
            return {
                "quality": "substantial",
                "should_retry": False,
                "retry_strategy": "",
                "confidence": 0.6,
                "analysis": "Fallback heuristic: no sorries, has theorems.",
            }
        elif sorry_count > 0 and theorem_count > 0:
            return {
                "quality": "partial",
                "should_retry": True,
                "retry_strategy": "Fill remaining sorries or simplify theorem.",
                "confidence": 0.5,
                "analysis": "Fallback heuristic: has sorries and theorems.",
            }
        else:
            return {
                "quality": "trivial",
                "should_retry": True,
                "retry_strategy": "Generate a more specific concept.",
                "confidence": 0.4,
                "analysis": "Fallback heuristic: no theorems found.",
            }

    def _is_trivially_obvious(self, lean_source: str) -> bool:
        """Quick heuristic check for obviously trivial results."""
        if "True := by trivial" in lean_source:
            return True
        if "True := by simp" in lean_source and "sorry" not in lean_source:
            return True
        lines = [l.strip() for l in lean_source.splitlines() if l.strip() and not l.strip().startswith("--")]
        if len(lines) < 5:
            trivial_tactics = {"trivial", "simp", "exact True.intro", "exact trivial", "rfl"}
            if any(t in lean_source for t in trivial_tactics):
                return True
        if "theorem " in lean_source and "True :=" in lean_source:
            return True
        return False

    # ------------------------------------------------------------------
    # Retry improvement
    # ------------------------------------------------------------------

    def suggest_retry_improvement(
        self,
        concept: ResearchConcept,
        previous_prompt: str,
        result_lean: str,
        quality_assessment: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Pi-Agent suggests how to improve a failed/trivial result.

        Returns dict with revised_concept_description, revised_prompt,
        revised_catalog_references, revised_research_mode, confidence.
        """
        lean_preview = result_lean[:2000] if len(result_lean) > 2000 else result_lean

        user_prompt = textwrap.dedent(f"""\
            The previous research attempt produced a {quality_assessment.get('quality', 'unknown')} result.

            ## Original Concept
            - Title: {concept.title}
            - Domain: {concept.domain}
            - Description: {concept.concept_description[:500]}
            - Mode: {concept.research_mode}

            ## Quality Assessment
            - Quality: {quality_assessment.get('quality', 'unknown')}
            - Analysis: {quality_assessment.get('analysis', 'N/A')}
            - Retry strategy: {quality_assessment.get('retry_strategy', 'N/A')}

            ## Result (what went wrong)
            ```lean
            {lean_preview}
            ```

            Suggest improvements. You can:
            1. Make the concept more specific and mathematically precise
            2. Change the research mode (e.g., from "prove" to "formalize" or "counterexample")
            3. Select different catalog references that are more relevant
            4. Completely change direction if the original concept was flawed

            Respond with JSON:
            {{
              "revised_concept_description": "new, more specific description",
              "revised_prompt": "full revised prompt text to send to Aristotle",
              "revised_catalog_references": ["Domain/File.lean", ...],
              "revised_research_mode": "prove|formalize|counterexample|sorry_fill",
              "confidence": 0.0-1.0
            }}
        """)

        raw = self._call_ollama(_DIRECTION_SYSTEM_PROMPT, user_prompt)
        parsed = self._parse_json_response(raw)

        if parsed:
            return {
                "revised_concept_description": parsed.get("revised_concept_description", concept.concept_description),
                "revised_prompt": parsed.get("revised_prompt", previous_prompt),
                "revised_catalog_references": parsed.get("revised_catalog_references", concept.catalog_references),
                "revised_research_mode": parsed.get("revised_research_mode", concept.research_mode),
                "confidence": float(parsed.get("confidence", 0.5)),
            }

        # Fallback
        return {
            "revised_concept_description": concept.concept_description + " (retry: be more specific)",
            "revised_prompt": previous_prompt,
            "revised_catalog_references": concept.catalog_references,
            "revised_research_mode": concept.research_mode,
            "confidence": 0.3,
        }

    # ------------------------------------------------------------------
    # File classification
    # ------------------------------------------------------------------

    def classify_file_placement(
        self,
        lean_source: str,
        file_name: str,
        concept: ResearchConcept,
    ) -> Dict[str, Any]:
        """Classify a Lean file into the correct Catalog location.

        Returns dict with domain, subdirectory, target_path,
        is_complete_proof, confidence, reason.
        """
        source_preview = lean_source[:3000] if len(lean_source) > 3000 else lean_source

        # Get domain files for context
        domain_files = ""
        if self.catalog_analyzer:
            self.catalog_analyzer.scan()
            domain_files = self.catalog_analyzer.get_domain_summary_for_prompt()

        user_prompt = textwrap.dedent(f"""\
            Classify this Lean 4 file into the correct domain in the catalog.

            ## File: {file_name}
            ```lean
            {source_preview}
            ```

            ## Concept Context
            - Domain: {concept.domain}
            - Research Mode: {concept.research_mode}

            ## Catalog Domains
            {domain_files if domain_files else "Algebra, Bridges, Computation, Cryptography, EML, Geometry, Logic, MachineLearning, Physics, Pythagorean, Shared, Speculative, Tropical"}

            Choose the most appropriate domain and subdirectory. The file should go
            where its mathematical content is most naturally at home.

            Respond with JSON:
            {{
              "domain": "DomainName",
              "subdirectory": "SubdirectoryName",
              "target_path": "DomainName/SubdirectoryName/FileName.lean",
              "is_complete_proof": true/false,
              "confidence": 0.0-1.0,
              "reason": "brief explanation"
            }}
        """)

        raw = self._call_ollama(_CLASSIFICATION_SYSTEM_PROMPT, user_prompt)
        parsed = self._parse_json_response(raw)

        if parsed:
            return {
                "domain": parsed.get("domain", concept.domain),
                "subdirectory": parsed.get("subdirectory", ""),
                "target_path": parsed.get("target_path", f"{concept.domain}/AutoResearch/{file_name}"),
                "is_complete_proof": parsed.get("is_complete_proof", "sorry" not in lean_source),
                "confidence": float(parsed.get("confidence", 0.5)),
                "reason": parsed.get("reason", ""),
            }

        # Fallback: use concept domain with heuristic
        sorry_count = lean_source.count("sorry")
        is_complete = sorry_count == 0
        if is_complete:
            return {
                "domain": concept.domain,
                "subdirectory": "",
                "target_path": f"{concept.domain}/{file_name}",
                "is_complete_proof": True,
                "confidence": 0.4,
                "reason": "Fallback: used concept domain, proof appears complete.",
            }
        else:
            return {
                "domain": "Speculative",
                "subdirectory": "AutoResearch",
                "target_path": f"Speculative/AutoResearch/{file_name}",
                "is_complete_proof": False,
                "confidence": 0.4,
                "reason": f"Fallback: proof has {sorry_count} sorries, placed in Speculative.",
            }