"""Seed directions for the Aether Future Directions system.

v4: Diversified — culled tropical echo chamber, added grand challenges
from MathWorld, Hilbert, Landau, Clay, and other frontier problem lists.
Aristotle decides where research goes.
"""

from research_memory import FutureDirection

_ID = 0

def _sd(title, desc, domains, priority=0.85, proof_strategy="", source_path="seed:manual_v2"):
    global _ID
    _ID += 1
    return FutureDirection(
        id=f"seed_{_ID:03d}", title=title, description=desc,
        source_exp_id="seed", source_path=source_path,
        domains=domains, priority_score=priority,
        proof_strategy=proof_strategy,
    )


def get_seed_directions() -> list[FutureDirection]:
    global _ID
    _ID = 0
    return [
        # ══════════════════════════════════════════════════════════
        # MathWorld Unsolved Problems
        # ══════════════════════════════════════════════════════════
        _sd("Goldbach Conjecture", "Prove that every even integer greater than 2 is the sum of two primes. Formalize partial results such as Vinogradov's theorem for sufficiently large odd integers, or Chen's theorem that every sufficiently large even number is the sum of a prime and a semiprime. Explore connections to sieve methods and the circle method.", ["NumberTheory", "Algebra"], 0.95),
        _sd("Riemann Hypothesis", "Prove that all non-trivial zeros of the Riemann zeta function lie on Re(s)=1/2. Formalize equivalent statements: the prime counting function error bound, the Mertens conjecture connection, or the spectral interpretation via random matrix theory. Explore connections to quantum chaos and the Hilbert-Polya conjecture.", ["NumberTheory", "Analysis"], 0.95),
        _sd("Hadamard Matrix Conjecture", "Prove that a Hadamard matrix exists for every positive multiple of 4. Formalize known constructions (Sylvester, Paley, tensor products) and establish bounds on the smallest open order. Connect to combinatorial designs, error-correcting codes, and signal processing.", ["Algebra", "Combinatorics"], 0.88),
        _sd("Twin Prime Conjecture", "Prove that there are infinitely many pairs of primes differing by 2. Formalize Zhang's bounded gaps result and Maynard-Tao improvements. Explore connections to the Hardy-Littlewood conjecture and sieve theory.", ["NumberTheory"], 0.93),
        _sd("P vs NP Problem", "Prove or disprove that P = NP. Formalize known barriers: relativization, natural proofs, algebrization. Explore circuit complexity lower bounds, proof complexity, and connections to cryptographic hardness assumptions.", ["Computation", "Logic"], 0.96),
        _sd("Collatz Conjecture", "Prove that the 3n+1 iteration eventually reaches 1 for all positive integers. Formalize partial results on density of convergent integers, stopping times, and connections to ergodic theory and p-adic dynamics.", ["NumberTheory", "Computation"], 0.85),
        _sd("196-Algorithm Non-Termination", "Prove that the reverse-and-add algorithm applied to 196 never produces a palindrome. Formalize the concept of Lychrel numbers and establish structural properties of the iteration on digit sequences.", ["NumberTheory"], 0.72),
        _sd("10 is a Solitary Number", "Prove that 10 is a solitary number — no other integer shares its abundancy index σ(n)/n. Formalize the theory of friendly numbers and abundancy, connecting to the distribution of divisor sums.", ["NumberTheory"], 0.70),
        _sd("Symmetric Group Generation Probability", "Find a formula for the probability that two elements chosen uniformly at random generate the symmetric group S_n. Formalize known asymptotic results and connect to the theory of random permutations.", ["Algebra", "Combinatorics", "Probability"], 0.78),
        _sd("Happy End Problem", "Solve the happy end problem for arbitrary n: determine the minimum number of points in general position in the plane that guarantee a convex n-gon. Formalize the Erdős–Szekeres theorem and improve known bounds.", ["Geometry", "Combinatorics"], 0.82),
        _sd("Perfect Cuboid (Euler Brick)", "Find an Euler brick whose space diagonal is also an integer, or prove none exists. Formalize the parametric families of near-misses and connect to Diophantine equations on algebraic surfaces.", ["NumberTheory", "Geometry"], 0.80),
        _sd("Sums of Three Cubes", "Determine which integers can be represented as a sum of three cubes. Formalize known computational results and the density conjecture. Connect to the geometry of cubic surfaces and the Hasse principle.", ["NumberTheory", "Algebra"], 0.83),
        _sd("Odd Perfect Numbers", "Prove that no odd perfect numbers exist. Formalize known constraints: must exceed 10^1500, have at least 101 prime factors, satisfy Euler's form p^a * m^2. Connect to the structure of multiplicative functions.", ["NumberTheory"], 0.88),

        # ══════════════════════════════════════════════════════════
        # Clay Millennium Problems
        # ══════════════════════════════════════════════════════════
        _sd("Hodge Conjecture", "Prove that every Hodge class on a non-singular projective algebraic variety is a rational linear combination of classes of algebraic cycles. Formalize the Hodge decomposition and explore the conjecture for specific varieties like abelian varieties and K3 surfaces.", ["Geometry", "Algebra"], 0.94),
        _sd("Yang-Mills Mass Gap", "Prove that for any compact simple gauge group, quantum Yang-Mills theory on R^4 exists and has a mass gap. Formalize the mathematical framework of gauge theory and connect to lattice gauge theory computations.", ["Physics", "Analysis"], 0.93),
        _sd("Navier-Stokes Existence and Smoothness", "Prove existence and smoothness of solutions to the 3D Navier-Stokes equations, or find a counterexample. Formalize known partial regularity results (Caffarelli-Kohn-Nirenberg) and explore connections to turbulence.", ["Analysis", "Physics"], 0.94),
        _sd("Birch and Swinnerton-Dyer Conjecture", "Prove that the rank of an elliptic curve equals the order of vanishing of its L-function at s=1. Formalize the BSD formula including the regulator, Tate-Shafarevich group, and Tamagawa numbers.", ["NumberTheory", "Algebra"], 0.94),

        # ══════════════════════════════════════════════════════════
        # Hilbert's Remaining Open Problems
        # ══════════════════════════════════════════════════════════
        _sd("Hilbert 6: Axiomatization of Physics", "Develop a rigorous axiomatic foundation for physics, particularly for probability and mechanics. Formalize Kolmogorov's axioms, explore constructive quantum mechanics, and connect to topos-theoretic physics.", ["Physics", "Logic"], 0.82),
        _sd("Hilbert 11: Quadratic Forms over Algebraic Fields", "Extend results on quadratic forms to arbitrary algebraic number fields. Formalize the Hasse-Minkowski theorem and explore the classification of quadratic forms over number fields via class field theory.", ["Algebra", "NumberTheory"], 0.80),
        _sd("Hilbert 12: Kronecker-Weber Generalization", "Extend the Kronecker-Weber theorem to arbitrary algebraic fields by constructing Hilbert class fields. Formalize explicit class field theory and connect to the Langlands program.", ["Algebra", "NumberTheory"], 0.85),
        _sd("Hilbert 13: 7th-Degree Equations via 2-Variable Functions", "Resolve whether the general 7th-degree equation can be solved using functions of only 2 variables. Formalize Kolmogorov's superposition theorem and explore its implications for approximation theory.", ["Algebra", "Analysis"], 0.78),
        _sd("Hilbert 15: Schubert Calculus Rigorization", "Provide rigorous foundations for Schubert's enumerative geometry. Formalize intersection theory on Grassmannians and flag varieties, proving Schubert calculus results via modern algebraic geometry.", ["Geometry", "Algebra"], 0.80),
        _sd("Hilbert 16: Topology of Algebraic Curves", "Study the topology of real algebraic curves and surfaces. Formalize the Harnack bound, classify real algebraic curves by arrangement of ovals, and connect to the second part on limit cycles of planar polynomial ODEs.", ["Geometry", "Topology"], 0.83),

        # ══════════════════════════════════════════════════════════
        # Landau's Problems
        # ══════════════════════════════════════════════════════════
        _sd("Legendre's Conjecture", "Prove that for every positive integer n, there exists a prime between n² and (n+1)². Formalize known partial results on prime gaps and connect to the Cramér model of primes.", ["NumberTheory"], 0.87),
        _sd("Primes of the Form n²+1", "Prove that there are infinitely many primes of the form n²+1. Formalize Iwaniec's result on semi-primes of this form and connect to Friedlander-Iwaniec theorem on primes of form a²+b⁴.", ["NumberTheory"], 0.86),

        # ══════════════════════════════════════════════════════════
        # Additional Grand Challenges
        # ══════════════════════════════════════════════════════════
        _sd("Lehmer's Mahler Measure Problem", "Determine whether Lehmer's polynomial has the smallest Mahler measure among non-cyclotomic polynomials. Formalize the Mahler measure and its connections to heights, entropy, and algebraic dynamics.", ["NumberTheory", "Algebra"], 0.79),
        _sd("Euler-Mascheroni Constant Irrationality", "Prove that the Euler-Mascheroni constant γ ≈ 0.5772 is irrational (or transcendental). Formalize continued fraction expansions and connect to the theory of special values of L-functions.", ["Analysis", "NumberTheory"], 0.82),
        _sd("Percolation Threshold", "Derive an analytic form for the square site percolation threshold. Formalize bond vs site percolation, prove known exact thresholds for triangular lattices, and connect to conformal invariance.", ["Probability", "Physics"], 0.76),
        _sd("ABC Conjecture Formalization", "Formalize the ABC conjecture and its implications in Lean 4. Prove consequences: Fermat's Last Theorem for large exponents, Roth's theorem strengthening, Mordell conjecture. Explore Mochizuki's claimed proof structure.", ["NumberTheory", "Algebra"], 0.90),
        _sd("Invariant Subspace Problem", "Prove or disprove that every bounded linear operator on a separable Hilbert space has a non-trivial closed invariant subspace. Formalize known results for compact operators and normal operators.", ["Analysis", "Algebra"], 0.84),
        _sd("Frankl's Union-Closed Conjecture", "Prove that for every finite union-closed family of sets (not all empty), some element belongs to at least half the sets. Formalize the lattice-theoretic reformulation and known partial results.", ["Combinatorics", "Algebra"], 0.80),
        _sd("Erdős–Straus Conjecture", "Prove that for every integer n ≥ 2, the fraction 4/n can be written as a sum of three unit fractions. Formalize computational verification and parametric families of solutions.", ["NumberTheory"], 0.77),
        _sd("Schanuel's Conjecture", "Prove Schanuel's conjecture: if z₁,...,zₙ are Q-linearly independent complex numbers, then the transcendence degree of {z₁,...,zₙ,e^z₁,...,e^zₙ} over Q is at least n. Formalize implications for the Lindemann-Weierstrass theorem.", ["NumberTheory", "Analysis"], 0.85),
        _sd("Jacobian Conjecture", "Prove that if a polynomial map F: Cⁿ → Cⁿ has constant non-zero Jacobian determinant, then F is invertible. Formalize the reduction to degree 3 and connect to the Dixmier conjecture.", ["Algebra", "Geometry"], 0.83),
        _sd("Kakeya Conjecture", "Prove the Kakeya conjecture: a Besicovitch set in Rⁿ has Hausdorff dimension n. Formalize the connection to restriction estimates and additive combinatorics.", ["Geometry", "Analysis"], 0.84),
        _sd("Beal's Conjecture", "Prove that if A^x + B^y = C^z where A,B,C,x,y,z are positive integers with x,y,z > 2, then A,B,C share a common prime factor. Formalize the connection to Fermat-Catalan and ABC conjecture.", ["NumberTheory"], 0.82),
        _sd("Cramér's Conjecture on Prime Gaps", "Prove that the gap between consecutive primes p_n satisfies p_{n+1} - p_n = O((log p_n)²). Formalize probabilistic models of primes and known unconditional bounds.", ["NumberTheory"], 0.83),

        # ══════════════════════════════════════════════════════════
        # Cross-Domain Frontiers (non-tropical)
        # ══════════════════════════════════════════════════════════
        _sd("Langlands Program: Functoriality", "Prove specific cases of Langlands functoriality: the transfer from GL(2) to GL(3), or symmetric power liftings. Formalize automorphic representations and L-functions in Lean 4.", ["Algebra", "NumberTheory", "Bridges"], 0.92),
        _sd("Quantum Error Correction Bounds", "Prove tight bounds on quantum error-correcting codes. Formalize the quantum Singleton bound, quantum Hamming bound, and construct optimal stabilizer codes. Connect to topological quantum computing.", ["Physics", "Computation", "Algebra"], 0.87),
        _sd("Homotopy Type Theory Foundations", "Formalize core HoTT results in Lean 4: the univalence axiom, higher inductive types, and the fundamental theorem of identity types. Prove that HoTT provides a constructive foundation for mathematics.", ["Logic", "Topology", "Algebra"], 0.86),
        _sd("Machine Learning Generalization Bounds", "Prove tighter generalization bounds for deep neural networks. Formalize PAC-Bayes bounds, compression-based bounds, and connect network architecture to sample complexity. Establish when overparameterized networks provably generalize.", ["MachineLearning", "Computation", "Algebra"], 0.85),
        _sd("Category-Theoretic Neural Architectures", "Formalize neural network architectures as morphisms in a monoidal category. Prove that ResNet skip connections are categorical products, attention is a natural transformation, and architecture search is optimization in a functor category.", ["MachineLearning", "Algebra", "Bridges"], 0.84),
        _sd("Certified Adversarial Robustness via Sheaf Cohomology", "Prove that vanishing first sheaf cohomology on neural network weight spaces implies certified L-infinity perturbation radius. Construct explicit sheaf structures on decision boundaries whose stalk cohomology detects adversarial vulnerability.", ["MachineLearning", "Algebra", "Bridges"], 0.88),
        _sd("Spectral Graph Theory Meets Network Robustness", "Prove that the algebraic connectivity of a neural network's computation graph bounds its certified robustness radius. Formalize the connection between graph spectra and function Lipschitz constants.", ["MachineLearning", "Algebra", "Geometry"], 0.83),
        _sd("Reversible Computing and Thermodynamic Efficiency", "Prove that reversible circuits achieve Landauer's bound for erasure. Formalize the connection between computational complexity and thermodynamic entropy. Construct provably optimal reversible implementations of common algorithms.", ["Computation", "Physics"], 0.82),
        _sd("EML Universal Approximation", "Prove that Exponential-Multiplicative-Logarithmic closures are universal approximators with provable complexity bounds. Show that minimum EML depth for ε-approximation is O(K(f)/ε), connecting to Kolmogorov complexity.", ["EML", "MachineLearning", "Algebra"], 0.85),
        _sd("Pythagorean Triple Group Structure", "Prove deep structural theorems about the Berggren tree of Pythagorean triples. Formalize the groupoid action on SL(3,Z), the prime distribution along hypotenuse lengths, and computational applications of the tree structure.", ["Pythagorean", "Algebra", "NumberTheory"], 0.82),

        # ══════════════════════════════════════════════════════════
        # Tropical Geometry (kept — genuine tropical seeds)
        # ══════════════════════════════════════════════════════════
        _sd("Tropical Riemann-Roch Theorem", "Prove the tropical Riemann-Roch theorem: for a tropical curve of genus g and a divisor D of degree d, the tropical rank r(D) satisfies r(D) - r(K-D) = d - g + 1. Formalize chip-firing and Baker-Norine theory.", ["Tropical", "Algebra", "Geometry"], 0.86),
        _sd("Tropical Brill-Noether Theory", "Prove that a general tropical curve of genus g has a divisor of degree d and rank r iff the Brill-Noether number ρ = g - (r+1)(g-d+r) ≥ 0. Formalize the connection to classical algebraic geometry.", ["Tropical", "Geometry", "Algebra"], 0.84),
        _sd("Tropical Satake Isomorphism for GL_n", "Extend the tropical Satake isomorphism from GL_2 to GL_n. Prove that it defines a bijection between min-plus Hecke operators and W-invariant tropical polynomials, connecting representation theory to combinatorics.", ["Tropical", "Algebra", "Bridges"], 0.87),
        _sd("Tropical Intersection Theory", "Prove that the tropicalization functor preserves intersection numbers. Formalize tropical varieties as polyhedral complexes and establish the tropical Bézout theorem with explicit bounds.", ["Tropical", "Geometry"], 0.82),
        _sd("Tropical Convexity and Helly Theorem", "Prove a tropical analogue of Helly's theorem: characterize when tropical convex sets have non-empty intersection. Formalize tropical convex hulls and their connection to optimization.", ["Tropical", "Geometry", "Computation"], 0.78),

        # ══════════════════════════════════════════════════════════
        # Meta-Research (kept — Aether self-improvement)
        # ══════════════════════════════════════════════════════════
        _sd("Certified Novelty Detection for Theorem Provers", "Design and prove correct a novelty certification system that formally verifies each research output contains genuinely new mathematics. Construct a theorem embedding space where distance bounds novelty.", ["Logic", "Computation", "Bridges"], 0.92),
        _sd("Proof Strategy Mining from Deep Mathematics", "Reverse-engineer proof strategies from deep results (FLT, Poincaré, classification of finite simple groups) and extract reusable structural patterns as higher-order proof schemata.", ["Logic", "Algebra", "Bridges"], 0.90),
        _sd("Research Depth via Proof-Theoretic Ordinal Analysis", "Prove that proof-theoretic ordinal analysis provides a rigorous depth metric for mathematical research. Construct a formalization that computes the proof-theoretic ordinal of research output.", ["Logic", "Computation"], 0.88),
        _sd("Self-Modifying Research via Reflective Type Theory", "Formalize a research system as a dependent type where the type of the next cycle depends on outcomes of previous cycles. Prove that reflective self-improvement converges.", ["Logic", "Algebra"], 0.91),

        # ══════════════════════════════════════════════════════════
        # Speculative / Fun (kept — non-tropical versions)
        # ══════════════════════════════════════════════════════════
        _sd("Consciousness as Integrated Information", "Formalize integrated information theory (IIT) in Lean 4. Define Phi as a measure on causal structures, prove its key properties (composition, exclusion), and explore connections to category theory and complexity.", ["Speculative", "Logic", "Computation"], 0.80),
        _sd("Alien Mathematics: Non-Standard Arithmetic", "Explore what theorems hold in non-standard models of arithmetic. Formalize ultrapower constructions, transfer principles, and prove which classical theorems survive in non-Archimedean settings.", ["Speculative", "Logic", "Algebra"], 0.76),
        _sd("Game of Life Universality", "Prove Conway's Game of Life is Turing complete via a direct constructive embedding. Formalize cellular automata in Lean 4 and establish complexity bounds on the simulation overhead.", ["Computation", "Speculative"], 0.77),
        _sd("Musical Counterpoint as Constraint Satisfaction", "Formalize the rules of species counterpoint as a constraint satisfaction problem. Prove that optimal voice leading minimizes a well-defined cost function and connect to lattice theory.", ["Bridges", "Algebra"], 0.72),

        # ══════════════════════════════════════════════════════════
        # Sci-Fi & Twilight Zone Mathematics
        # ══════════════════════════════════════════════════════════
        _sd("Non-Archimedean Probability via Surreal Numbers", "Develop a probability theory on Conway's surreal numbers where infinitesimal probabilities are well-defined. Conjecture: There exists a surreal-valued probability measure on [0,1] that assigns non-zero infinitesimal probability to each point but still integrates to 1. Test: construct the measure and verify additivity for finite unions. If true, this opens a new foundation for probability with infinitesimals, connecting to nonstandard analysis and surreal game theory.", ["Analysis", "Speculative", "Bridges"], 0.82),
        _sd("Holographic Mathematics: Bulk-Boundary Proof Duality", "Inspired by the AdS/CFT correspondence, formalize a mathematical holographic principle: a theorem about n-dimensional structures (the bulk) has a dual (shorter) proof in (n-1)-dimensional boundary terms. Conjecture: Every proof by induction on a well-founded order of rank n has an equivalent proof by coinduction on the n-1 boundary. Test: find a concrete theorem (e.g., finite Ramsey) and show its inductive proof in R^n maps to a coinductive proof on S^{n-1}. Impact: a new holographic proof theory connecting algebraic topology to proof complexity.", ["Physics", "Algebra", "Speculative"], 0.85),
        _sd("Quantum Topological Phase Computation", "Formalize computation via topological phase transitions: each computation step is a braid group operation on anyonic worldlines. Conjecture: The braid group B_n is universal for computation when augmented with the F-matrix and R-matrix of SU(2)_k anyons for k>=3. Test: implement the Fibonacci anyon model in Lean 4 and prove that braiding generates a dense subset of SU(2). Impact: connects topological quantum computation to algebraic knot theory.", ["Computation", "Topology", "Physics"], 0.84),
        _sd("Strange Attractors as Algebraic Objects", "Treat chaotic attractors (Lorenz, Henon, Rossler) as algebraic objects — not just numerical phenomena. Conjecture: The Lorenz attractor's topology can be characterized as the inverse limit of a specific diagram in the category of finite directed graphs. Test: compute the inverse limit and compare its Cech cohomology to the known Lorenz template. Impact: if true, chaotic dynamics become amenable to algebraic topology and category-theoretic methods.", ["Analysis", "Algebra", "Speculative"], 0.80),
        _sd("Integrated Information via Tensor Networks", "Formalize Tononi's Integrated Information Theory (IIT) using tensor network states. Conjecture: The integrated information Phi of a tensor network state equals the minimal quantum mutual information across any bipartition. Test: compute Phi for MPS (matrix product states) with bond dimension 2 and verify it matches the Schmidt rank. Impact: connects consciousness theory to quantum information and tensor categories.", ["Physics", "Computation", "Speculative"], 0.78),
        _sd("Alien Number Systems: Beyond Base-N", "Explore number representation systems that are not base-N: factorial number system, Zeckendorf representation, balanced ternary with negative digits, and genuinely novel systems. Conjecture: There exists a number representation system with O(log* n) digit count (iterated logarithm) using recursive bases. Test: construct the tower-base representation and prove every natural number has a unique representation. Impact: if true, this gives sub-logarithmic number representations with implications for compression and coding theory.", ["NumberTheory", "Computation", "Speculative"], 0.76),
        _sd("Sonic Mathematics: Counterpoint as Category Theory", "Formalize musical counterpoint rules (Fux's species counterpoint) as a category where objects are consonant intervals and morphisms are permitted voice leadings. Conjecture: The category of first-species counterpoint over a diatonic scale is equivalent to the thin category generated by a specific poset of 12 elements. Test: enumerate all valid first-species counterpoint motions and prove they form exactly this category. Impact: bridges music theory, order theory, and categorical logic.", ["Algebra", "Speculative", "Bridges"], 0.74),

        # ══════════════════════════════════════════════════════════
        # EML Single Operator & Neural Network Science
        # ══════════════════════════════════════════════════════════
        _sd("EML Single Operator Church-Turing Thesis", "Formalize the conjecture that e^a * log(b) is a universal primitive for real computation. Conjecture: Every computable real function f: R^n -> R can be expressed as a finite composition of e^x, log(x), constants, and field operations. Test: prove this for the class of elementary functions (sin, cos, exp, log, polynomials) by showing each reduces to EML compositions. If true, this means a single EML neuron (exp+log) is computationally universal.", ["EML", "Computation", "Logic"], 0.88),
        _sd("EML Neural Network Expressiveness: Depth vs Width", "Prove depth-width tradeoffs specific to EML activation exp(w*x+b) - log(w'*x+b'). Conjecture: An EML network of depth d and width w can approximate any Lipschitz function on [0,1]^n with error O((w*d)^{-2/n}) — matching ReLU rates but with smoother gradients. Test: prove the lower bound by constructing an EML network that approximates x^2 on [0,1] with error O(w^{-2}) using depth 2. Compare with ReLU's O(w^{-1}) rate.", ["EML", "MachineLearning", "Analysis"], 0.86),
        _sd("EML Kolmogorov-Arnold Representation", "The Kolmogorov-Arnold theorem says any continuous f: [0,1]^n -> R can be written as a sum of 2n+1 continuous univariate functions. Conjecture: The inner univariate functions in the K-A representation can be chosen to be EML-type functions (exp-log compositions). Test: for n=2, construct the 5 inner functions explicitly as EML compositions that achieve the K-A decomposition for a specific target (e.g., x1*x2). Impact: directly connects EML to a deep representation theorem.", ["EML", "Analysis", "Bridges"], 0.87),
        _sd("EML Training Dynamics as Tropical Gradient Flow", "Model EML network training in the tropical limit (large weights) as a gradient flow on the tropical projective torus. Conjecture: In the tropical limit, the EML training dynamics converge to a piecewise-linear gradient flow whose fixed points correspond to tropical rational functions that minimize the tropical loss. Test: prove convergence for a single EML neuron trained on 3 data points in the tropical limit. Impact: bridges neural network optimization and tropical geometry.", ["EML", "Tropical", "MachineLearning"], 0.84),
        _sd("EML Quantum Activation Functions", "Define quantum EML neurons where exp and log are replaced by unitary exponentials: U = exp(iH) for Hermitian H, and the log is the matrix logarithm. Conjecture: The quantum EML neuron U = exp(iH1) * log(I+iH2) can implement any single-qubit unitary. Test: parameterize H1, H2 and prove the map covers SU(2). Impact: opens quantum-classical neural network bridges.", ["EML", "Physics", "MachineLearning"], 0.83),
        _sd("EML Category: The Category of EML-Computable Maps", "Define the category EML_Comp where objects are R^n and morphisms are functions computable by finite EML compositions (exp, log, +, *, constants). Conjecture: EML_Comp is a Cartesian closed category with natural numbers object R (the reals). Test: prove closure under composition (trivial), products (pairing), and exponentials (currying via EML parameter sharing). Impact: puts EML computation on firm categorical foundations.", ["EML", "Algebra", "Logic"], 0.82),

        # ══════════════════════════════════════════════════════════
        # Inverse Stereographic & New Applications
        # ══════════════════════════════════════════════════════════
        _sd("Inverse Stereographic Cryptography: Projection as One-Way Function", "Use inverse stereographic projection S^n -> R^n as a cryptographic primitive. The forward map (point on sphere to plane) is easy, but recovering the original point from the plane projection requires the pole parameter. Conjecture: Finding the pole of stereographic projection from only (image set, projection point) is as hard as the shortest vector problem in a lattice. Test: formalize the reduction from SVP to pole-finding for n=2. Impact: a new geometric foundation for lattice-based cryptography.", ["Geometry", "Cryptography", "Computation"], 0.86),
        _sd("Stereographic Neural Attention: Attention via Riemann Sphere", "Replace softmax attention with stereographic attention: map query/key vectors to the Riemann sphere via stereographic projection, compute Cauchy kernel K(q,k) = 1/(1+|q-k|^2) on the sphere, and project back. Conjecture: Stereographic attention has O(sqrt(N)) sparsity (most Cauchy weights are near-zero) while maintaining the universal approximation properties of softmax attention. Test: prove the sparsity bound for random queries on the unit sphere. Impact: a new attention mechanism with built-in sparsity and geometric structure.", ["Geometry", "MachineLearning", "Physics"], 0.85),
        _sd("Inverse Stereographic Renormalization Group", "The renormalization group in physics zooms out by integrating out high-energy modes. Formalize this as an inverse stereographic projection on the energy sphere: RG flow equals iterated stereographic projection with varying pole. Conjecture: The beta function beta(g) in phi^4 theory equals the derivative of the stereographic projection map at the critical coupling g*. Test: compute the stereographic map for the 1D Ising model and verify beta(g) matches. Impact: connects renormalization to conformal geometry.", ["Geometry", "Physics", "Algebra"], 0.84),
        _sd("Stereographic Proof Compression: Proofs on Spheres", "A proof is a sequence of steps. Map each step to a point on S^n via stereographic projection. The proof distance between theorems is the spherical distance between their proof endpoints. Conjecture: Two theorems whose proofs are close in spherical distance share a common subproof of length at least n minus spherical_distance. Test: compute proof distances for a set of 20 basic theorems in Lean 4 and verify the subproof bound. Impact: geometric proof mining and automated lemma discovery.", ["Geometry", "Logic", "Computation"], 0.82),
        _sd("Inverse Stereographic Tropical Lift", "Tropical geometry replaces + with max and * with +. Stereographic projection maps spheres to planes. What is the tropical stereographic projection? Define it as: map a tropical point (x1 + ... + xn) on the tropical projective space to a tropical hyperplane via an analogous pole construction. Conjecture: The tropical stereographic projection is a tropical rational function of degree 2 (a tropical Mobius transformation). Test: construct it explicitly for TP^1 -> TR^1 and prove it is a tropical homeomorphism. Impact: connects tropical geometry and conformal geometry.", ["Geometry", "Tropical", "Algebra"], 0.80),

        # ══════════════════════════════════════════════════════════
        # Wave 2: Sci-Fi & Twilight Zone Mathematics
        # ══════════════════════════════════════════════════════════
        _sd("Retrocausal Proof Theory: Proving Theorems by Their Consequences",
            "Develop a proof theory where the validity of a theorem can be established not just by deriving it from axioms, but by verifying that its logical consequences form a coherent, self-consistent structure. Conjecture: There exists a class of consequence-stable propositions P such that if P implies Q1 and Q2 ... Qn and all Qi are verified, then P has a proof shorter than any direct proof by at least a constant factor. Test: identify consequence-stable propositions in Peano arithmetic and measure proof compression. A consequence-stable proposition P has the property that all its logical consequences are mutually consistent, and the set of verified consequences narrows the search space for P's proof. This is analogous to how in physics, the consequences of a theory (predictive power) can confirm the theory even before a mechanism is found. Retrocausal proof theory would enable a new form of automated theorem proving where consequence verification guides proof search, not just axiom chaining. Impact: a new paradigm for automated theorem proving where consequences guide proof search, not just axioms.",
            ["Logic", "Speculative", "Computation"], 0.90,
            proof_strategy="Construct a Gentzen-style sequent calculus where the Cut rule is replaced by a consequence verification rule: if Gamma proves A and A has desirable consequences verified by a computational check, then A is accepted. Prove cut-elimination fails in general but holds for consequence-stable formulas. Test: show that Fermat's Last Theorem for n=4 is consequence-stable, enabling a retrocausal proof."),

        _sd("Mobius Arithmetic: Number Theory on the Mobius Band",
            "Construct a number system on the Mobius band where the integers wrap with a twist: n and -n are identified with opposite orientations. Define the Mobius integers Z_tilde as Z x {+1, -1} modulo the identification (n, +1) ~ (-n, -1). Develop arithmetic on Z_tilde where addition wraps through the identification. Conjecture: The ring Z_tilde of Mobius integers has class number 1, and its prime spectrum forms a double cover of the ordinary primes (each ordinary prime p splits into two oriented primes p_plus and p_minus). The Mobius zeta function zeta_tilde(s) has zeros off the critical line, which is expected since Z_tilde is a non-Ore ring. Test: factor 6 in Z_tilde as 2_plus times 3_plus and 2_minus times 3_minus and verify these are distinct factorizations. Prove unique factorization for Z_tilde up to orientation. Impact: a new algebraic number system with intrinsic orientation, connecting number theory to topology via the double cover Z to Z_tilde.",
            ["Geometry", "NumberTheory", "Algebra"], 0.88,
            proof_strategy="Define Z_tilde as Z x {+1,-1} modulo (n,+1)~(-n,-1). Develop arithmetic: (a,s1)+(b,s2) = (a+b, s1*s2) when signs agree, (a-b, s1) when they differ. Prove the prime structure: each odd prime p in Z lifts to two oriented primes p_plus and p_minus in Z_tilde. Show the Mobius zeta function zeta_tilde(s) = sum_{n=1}^{infty} (1/n^s_+ + 1/n^s_-) converges for Re(s)>1 but violates the functional equation. Test: compute zeta_tilde(s) for Re(s)>1 and show analytic continuation exists but breaks the functional equation."),

        _sd("Thermodynamic Proof Erasure: Landauer's Principle for Mathematics",
            "Landauer's principle states that erasing one bit of information dissipates at least kT*ln(2) of heat. Apply this to proof theory: erasing a proof of theorem T to recover a shorter proof is an information-theoretic process with a thermodynamic cost. Conjecture: The minimum energy required to compress a proof of n steps into a proof of m steps (m < n) is at least kT*(n-m)*ln(2), and this bound is tight for proofs in propositional logic. A proof of length n contains n bits of information (each step is a binary choice in the search tree). Compressing it to m steps requires erasing n-m bits, each costing kT*ln(2) by Landauer. This gives a physical lower bound on proof compression that is independent of the proof system. Test: formalize proof compression as an irreversible computation and derive the Landauer bound. Compute the erasure cost for compressing a 1000-step proof of the fundamental theorem of algebra into a 100-step proof. Impact: connects information thermodynamics to proof complexity, providing a physical lower bound on proof compression.",
            ["Physics", "Computation", "Logic"], 0.87,
            proof_strategy="Formalize proof erasure as a thermodynamic process: deleting a proof of length n requires at least kT*n*ln(2) of heat dissipation (Landauer's principle applied to each proof step). Prove that proof compression by a factor of c requires at least kT*n*(1-1/c)*ln(2) of erasure energy. Derive the bound by modeling each proof step as a binary decision in a search tree, so erasing n-m steps loses n-m bits. Test: compute the erasure cost for compressing a 1000-step proof of the fundamental theorem of algebra into a 100-step proof."),

        _sd("Fractal Topology: Hausdorff Dimension as a Topological Invariant",
            "The Hausdorff dimension is normally a metric property, not a topological one. Investigate whether it can be made topological through the lens of fractal topology. Define the fractal topological dimension d_f(X) of a metric space X as the infimum of d such that X embeds in R^d with Hausdorff dimension preserved. Conjecture: For compact metric spaces, the Hausdorff dimension is a topological invariant modulo homeomorphisms that are bi-Lipschitz on a dense open set. More precisely, if X and Y are homeomorphic compact subsets of R^n, and the homeomorphism is bi-Lipschitz on a set of full Hausdorff dimension in X, then dim_H(X) = dim_H(Y). This would mean that fractal dimension is not just a metric accident but a topological invariant up to rough isometries. Test: compute d_f for the Sierpinski gasket (expected: 1 since connected, Hausdorff dimension log3/log2) and the Cantor set (expected: 0 since totally disconnected). Prove that the Koch curve and any bi-Lipschitz-equivalent curve have equal Hausdorff dimensions. Impact: elevates fractal dimension from a metric curiosity to a topological invariant, with applications to shape classification and topological data analysis.",
            ["Geometry", "Topology", "Analysis"], 0.86,
            proof_strategy="Define d_f(X) = inf{d : X embeds in R^d preserving Hausdorff dimension}. Prove d_f is a topological invariant for compact metric spaces by showing it is preserved under bi-Lipschitz homeomorphisms on dense open sets. The key lemma: if h is bi-Lipschitz on a set S of full Hausdorff dimension in X, then dim_H(X) = dim_H(h(X)). Test: compute d_f(Sierpinski gasket) = 1 (connected) and d_f(Cantor set) = 0 (totally disconnected). Prove that dim_H is invariant under orientation-preserving bi-Lipschitz maps on dense subsets."),

        _sd("Temporal Logic of Proofs: When You Prove Something Matters",
            "Standard proof theory treats proofs as timeless: once proved, always proved. But in practice, proofs are discovered in time, and their dependencies form a temporal order. Formalize a temporal logic of proofs where the modal operator Box means provably established by time t. Conjecture: The temporal provability logic TGL (Temporal Godel-Lob) is decidable and strictly extends GL with the axiom Box A implies Box Box Diamond A (if provable now, provably will be provable at any future time). The key insight is that provability in PA is Sigma_1-complete: if PA proves A, then PA proves that PA proves A. Adding temporality creates a system where proof discovery has a well-defined causal order, and future provability can be reasoned about. Test: prove the arithmetical completeness of TGL relative to Peano Arithmetic with a time-stamped provability predicate. Show that the temporal paradox this statement will be provable tomorrow but not today is refutable in TGL. Impact: a new logic for reasoning about proof discovery in time, with applications to proof mining and automated theorem proving where proof order matters.",
            ["Logic", "Computation", "Speculative"], 0.84,
            proof_strategy="Extend Godel-Lob provability logic GL with temporal operators: Box A means A is provable now, Diamond A means A will be provable. Define axiom schema: Box(Box A implies Box Box A) and (Box A and Diamond B implies Diamond(A and B)). Prove TGL is consistent (interpret in PA with time-stamped provability Prov(n, A) = there exists a PA-proof of A with at most n steps). Prove TGL is decidable via finite model property. Test: show that the temporal paradox this statement will be provable tomorrow but not today is refutable."),

        # ══════════════════════════════════════════════════════════
        # Wave 2: EML Single Operator & Neural Network Science
        # ══════════════════════════════════════════════════════════
        _sd("EML Fixed-Point Theorem: exp-log Iteration Convergence",
            "The EML single operator f(x) = e^a * log(b*x + c) is a contraction mapping for suitable parameter ranges. Conjecture: For all a, b, c in R with a > 0 and b, c chosen so that the function maps a closed interval to itself, the iteration x_{n+1} = e^a * log(b*x_n + c) converges to a unique fixed point x* at a rate O(rho^n) where rho = |f'(x*)|. Moreover, the fixed point x* satisfies x* = e^a * log(b*x* + c) and can be expressed as a power series in a. The fixed point is unique because f is a contraction on the invariant interval: the derivative f'(x) = e^a * b / (b*x + c) is bounded by |f'| < 1 when the parameters are in the right range. This makes EML functions well-behaved iterative schemes, unlike arbitrary neural network activations. Test: prove convergence for the specific case a in (0,1), b=1, c in (0,1) and compute the fixed point explicitly as a series. Impact: establishes EML as having well-defined dynamical behavior, enabling EML-based iterative algorithms with certified convergence.",
            ["EML", "Analysis", "Computation"], 0.90,
            proof_strategy="Define the EML iteration T(x) = exp(a)*log(b*x + c) for parameters a, b, c. Prove T has a unique attractive fixed point when the spectral radius of the Jacobian at the fixed point is < 1. Derive explicit conditions on a, b, c for convergence: |e^a * b / (b*x* + c)| < 1. Show the Banach fixed point theorem applies on the invariant interval. Test: compute the fixed point for a=0.5, b=1.0, c=0.1 numerically, then prove the convergence bound in Lean 4."),

        _sd("EML Differential Calculus: Chain Rules for exp-log Compositions",
            "The EML operator class (finite compositions of exp, log, +, *) has remarkable closure properties. Conjecture: The class of EML functions is closed under differentiation, and the derivative of any EML function of composition depth d is an EML function of composition depth at most d+1. Moreover, the derivative has a canonical EML chain rule form: (exp(h) * log(g))' = exp(h) * log(g) * (h' + g'/g). This factorization is the key structural insight: the derivative of an EML function factors through the original function itself, multiplied by a simple expression involving only the inner functions and their derivatives. This is stronger than the general Leibniz rule because the EML structure forces the derivative into a canonical form. For depth-d EML functions, the derivative can be written recursively as f' = f * (h'_1 + g'_1/g_1) where each h'_i and g'_i are depth-(d-1) EML functions. Test: compute the 3rd derivative of f(x) = exp(x^2) * log(x+1) and verify it can be written as an EML expression. Impact: establishes that EML functions form a differential algebra, enabling automatic EML differentiation for verified numerical computation.",
            ["EML", "Analysis", "Algebra"], 0.88,
            proof_strategy="Define EML differential calculus: for f(x) = exp(h(x)) * log(g(x)), derive the EML chain rule f'(x) = f(x) * (h'(x) + g'(x)/g(x)). Prove closure under differentiation by induction on composition depth: depth-0 (constants, identity) are closed; depth-d+1 compositions exp(h)*log(g) have derivatives that are depth-d EML times a simple factor. Test: compute the 3rd derivative of f(x) = exp(x^2)*log(x+1) and verify it is an EML expression of depth 4."),

        _sd("EML Interpolation Theory: Stone-Weierstrass for exp-log Networks",
            "The Stone-Weierstrass theorem guarantees that any continuous function can be approximated by an algebra that separates points and contains constants. Conjecture: The algebra of EML functions (finite compositions of exp, log, +, *) on any compact subset of R^n is dense in C(K) with a Jackson-type rate: for f in Lip_alpha(K), there exists an EML network of width O(epsilon^{-n/alpha}) approximating f within epsilon. The separation property is key: given x != y in K, the function g(t) = exp(a)*log(b*t + c) can separate them for appropriate parameters a, b, c (because g is strictly monotone for a, b > 0). The constants are included via c = exp(a)*log(c) for c > 0. This gives EML networks provable approximation guarantees with explicit rates, going beyond the existential guarantees of universal approximation theorems. Test: prove the separation property (given x != y in K, find EML parameters that separate them) and the rate bound for Lipschitz functions. Construct an EML network of width n approximating x^2 on [0,1] with explicit error bounds. Impact: gives EML networks provable approximation guarantees with explicit rates, surpassing the existential guarantees of universal approximation theorems.",
            ["EML", "Analysis", "MachineLearning"], 0.87,
            proof_strategy="Step 1: Prove the algebra A of EML functions on compact K separates points. Given x != y in K, the function g(t) = exp(a)*log(b*t + c) is strictly monotone for a,b > 0, so g(x) != g(y) for some parameters. Step 2: Prove A contains constants (c = exp(a)*log(c) for c > 0). By Stone-Weierstrass, A is dense in C(K). Step 3: Prove Jackson-type rate: for f in Lip_alpha(K), construct an EML network of width O(epsilon^{-n/alpha}) achieving error epsilon. Test: construct an EML network of width n approximating x^2 on [0,1] with explicit error bounds O(n^{-2})."),

        _sd("EML Information Geometry: Fisher Information of exp-log Models",
            "Information geometry studies statistical manifolds via the Fisher information metric. Define the EML statistical manifold M_EML as the set of probability distributions parameterized by EML functions: p(x; theta) = exp(theta_1 * g_1(x)) * log(theta_2 * g_2(x) + theta_3) normalized to a probability distribution. Conjecture: The EML manifold M_EML is a dually flat statistical manifold whose dual potentials are the cumulant generating functions of the EML activation. The Fisher information on M_EML induces a Hessian metric with constant negative curvature, making it a hyperbolic geometry of model parameters. This means natural gradient descent on M_EML has well-defined geodesics, and the dual flatness enables efficient Fisher vector products. The negative curvature reflects the exponential sensitivity of EML networks to parameter changes: small perturbations in theta cause exponentially large changes in the output. Test: compute the Fisher metric for a single EML neuron f(x; a,b) = exp(a)*log(b*x+1) and verify it induces a Hessian manifold with constant negative curvature. Prove that the alpha-connections on M_EML are projectively flat for alpha=1. Impact: gives EML networks a differential-geometric foundation for natural gradient descent, with provable convergence properties.",
            ["EML", "MachineLearning", "Probability"], 0.86,
            proof_strategy="Compute the Fisher information matrix I(theta) for the EML model p(x; theta) = exp(theta_1 * g_1(x)) * log(theta_2 * g_2(x) + theta_3). Prove I(theta) is positive definite for all theta in the parameter space, establishing that M_EML has Riemannian structure. Compute the Christoffel symbols and show the Levi-Civita connection has constant negative curvature (hyperbolic geometry). Prove the alpha-connections are projectively flat for alpha=1 (dually flat). Test: for the 1D EML neuron f(x; a,b) = exp(a)*log(b*x+1), compute the Fisher metric and show it induces a Hessian manifold with K = -1/(a^2 + b^2)."),

        _sd("EML Algebraic Independence: Transcendence Results",
            "The Schanuel conjecture predicts deep algebraic independence results for exp and log. Specialize this to EML values. Conjecture: For algebraic numbers a_1,...,a_n linearly independent over Q, the numbers exp(a_1)*log(1+a_1), ..., exp(a_n)*log(1+a_n) are algebraically independent over Q. This is a specialization of Schanuel's conjecture to the EML operator. The n=1 case reduces to showing that exp(a)*log(1+a) is transcendental for algebraic a != 0, which follows from the Lindemann-Weierstrass theorem (exp(a) is transcendental for algebraic a != 0) combined with the Gelfond-Schneider theorem. The n=2 case requires showing that exp(sqrt(2))*log(1+sqrt(2)) and exp(sqrt(3))*log(1+sqrt(3)) satisfy no polynomial relation with algebraic coefficients, which is open. The EML specialization has the advantage that the multiplicative structure of exp(a)*log(b) constrains the possible algebraic relations more tightly than the general Schanuel conjecture. Test: prove the n=1 case using Lindemann-Weierstrass and Gelfond-Schneider. For n=2, show that exp(sqrt(2))*log(1+sqrt(2)) and exp(sqrt(3))*log(1+sqrt(3)) satisfy no polynomial relation with algebraic coefficients. Impact: connects EML to the deepest open problems in transcendental number theory, with implications for the theory of periods and special values of L-functions.",
            ["EML", "NumberTheory", "Algebra"], 0.85,
            proof_strategy="Step 1 (n=1): Prove exp(a)*log(1+a) is transcendental for algebraic a != 0. By Lindemann-Weierstrass, exp(a) is transcendental. If log(1+a) were algebraic, then a = exp(log(a)) would be transcendonic, contradiction. So log(1+a) is transcendental, and their product is transcendental by Baker's theorem. Step 2 (n=2): Assume P(exp(sqrt(2))*log(1+sqrt(2)), exp(sqrt(3))*log(1+sqrt(3))) = 0 for algebraic P. Derive contradiction using the linear independence of sqrt(2) and sqrt(3) over Q and Baker's theorem on linear forms in logarithms."),

        # ══════════════════════════════════════════════════════════
        # Wave 2: Inverse Stereographic & Geometric Frontiers
        # ══════════════════════════════════════════════════════════
        _sd("Stereographic Sheaf Theory: Gluing Data on Spheres",
            "Sheaf theory studies how local data glues to form global objects. The stereographic projection gives S^n a two-chart atlas with Mobius transition maps. Define a new class of sheaves called stereographic sheaves where the gluing data is constrained by the conformal structure of the stereographic atlas. A stereographic sheaf on S^n is a sheaf F such that for each chart U_i of the stereographic cover, the restriction F|U_i is a sheaf on R^n, and the transition function F(U_0 cap U_1) is a sheaf morphism that commutes with the Mobius transition. Conjecture: The category of stereographic sheaves on S^n is a proper subcategory of all sheaves on S^n, characterized by the condition that Cech cohomology with respect to the stereographic cover satisfies a Mobius compatibility. This subcategory has better computational properties: H^k(S^n, F) can be computed from the transition function alone for stereographic sheaves, reducing the computation of sheaf cohomology on S^n to a single gluing datum. Test: prove the equivalence with locally constant sheaves on RP^n for n=2,3. Compute H^1(S^2, Z) = Z/2Z for the constant sheaf Z. Impact: a new computational tool for sheaf cohomology that exploits conformal structure, with applications to topological data analysis and differential equations on spheres.",
            ["Geometry", "Algebra", "Topology"], 0.88,
            proof_strategy="Define a stereographic sheaf as a sheaf on S^n whose restriction to each chart of the stereographic atlas satisfies a compatibility condition: the transition functions are Mobius transformations. Prove that the category of stereographic sheaves on S^n is equivalent to the category of locally constant sheaves on RP^n (real projective n-space). The key step: the stereographic cover has two charts, so Cech cohomology reduces to computing the gluing datum. Test: compute H^1(S^2, Z) for the constant sheaf Z and verify it equals H^1(RP^2, Z) = Z/2Z."),

        _sd("Inverse Stereographic Neural Field Theory",
            "Neural field equations model macroscopic brain dynamics as PDEs on cortical surfaces. The cortical surface is topologically a sphere with cortical folds. Use inverse stereographic projection to transform neural field PDEs on S^2 into PDEs on R^2 with a conformal weight. Define a stereographic neural field as a function u: S^n to R satisfying Delta_{S^n} u = f(u) where Delta_{S^n} is the Laplace-Beltrami operator on the sphere. Under inverse stereographic projection, this becomes a PDE on R^n with a conformally modified Laplacian. Conjecture: The neural field equation on S^2 with Mexican-hat connectivity has exactly 2N+1 stable pattern solutions for interaction radius r, where N = floor(1/r). Under inverse stereographic projection, these correspond to N-fold symmetric patterns on R^2 that decay at infinity. The 2N+1 count comes from the representation theory of SO(3): each pattern of degree l has 2l+1 rotational variants, and the Mexican-hat kernel selects l = N. Test: prove the existence of 2N+1 patterns for r = 1/k (k=1,2,3) by constructing them as stereographic projections of spherical harmonics. Impact: a geometric theory of neural pattern formation with provable pattern counts, enabling predictions about visual hallucination patterns.",
            ["Geometry", "MachineLearning", "Physics"], 0.86,
            proof_strategy="Define stereographic neural field: Delta_{S^n} u = f(u) on S^n where f is Mexican-hat connectivity. Under inverse stereographic projection, this becomes Delta_{R^n} v + (2n|x|^2/(1+|x|^2)^2) * grad v = g(v) on R^n. Prove existence of traveling wave solutions using the Lyapunov-Schmidt reduction. The key: the Laplacian on S^n has eigenvalues l(l+n-1) with multiplicity 2l+1, so each eigenvalue gives 2l+1 pattern variants. For Mexican-hat kernel, the bifurcation selects l = floor(1/r). Test: compute the Green's function for the stereographic Laplacian and show it equals the Poisson kernel on the sphere. Prove 2*1+1 = 3 patterns for r=1 (icosahedral symmetry)."),

        _sd("Stereographic Fourier Analysis: Spherical Harmonics via Plane Waves",
            "The Fourier transform diagonalizes the Laplacian on R^n. The Laplace-Beltrami operator on S^n is diagonalized by spherical harmonics. Stereographic projection gives a conformal map S^n to R^n that modifies the metric by a conformal factor (1+|x|^2)^2/4. Define the stereographic Fourier transform: for f in L^2(S^n), set F(f)(k) = integral over S^n of f(x) * (1+|phi(x)|^2)^{-n/2} * e^{-2 pi i phi(x) * k} d sigma(x) where phi is the stereographic projection. Conjecture: The stereographic Fourier transform is an isometry L^2(S^n) to L^2(R^n) mapping spherical harmonics Y_l^m to generalized Hermite functions with explicit radial profiles. The transform preserves eigenvalues up to a conformal correction: Delta_{S^n} Y_l^m = -l(l+n-1) Y_l^m maps to Delta_{R^n}(F[Y_l^m]) = (-l(l+n-1) + n^2/4) F[Y_l^m] plus a lower-order correction. Test: derive the transform explicitly for n=2 and verify it sends Y_1^m to Hermite functions. Prove the Plancherel identity. Impact: enables Fourier analysis on spheres via classical Fourier analysis on R^n, with applications to quantum mechanics on curved spaces and computational harmonic analysis.",
            ["Geometry", "Analysis", "Physics"], 0.87,
            proof_strategy="Derive the stereographic Fourier transform explicitly. The key formula: F(f)(k) = integral over S^n f(x) * (1+|phi(x)|^2)^{-n/2} * exp(-2 pi i phi(x) dot k) d sigma(x) where phi is stereographic projection. Prove it is an isometry using the conformal factor (1+|x|^2)^2/4 that relates the spherical and Euclidean metrics. Show spherical harmonics Y_l^m map to generalized Hermite functions with radial profile r^l * (1+r^2)^{-(l+n/2)} * L_k^{l+n/2-1}(2r^2/(1+r^2)) where L are Laguerre polynomials. Test: compute F(Y_1^0) explicitly for n=2 and verify it is a multiple of the Hermite function H_1."),

        _sd("Inverse Stereographic Persistence: Topological Data Analysis on Spheres",
            "Persistent homology computes topological features of data at multiple scales. On spheres, the natural metric is the geodesic (spherical) distance, but existing algorithms assume Euclidean data. Use stereographic projection to transform spherical persistence to weighted Euclidean persistence. Define the stereographic persistence module for a point cloud X on S^n: for each filtration parameter epsilon, compute the Cech complex C_epsilon(X) on S^n using the spherical metric, then apply inverse stereographic projection to get a filtered complex on R^n with a conformal weight. Conjecture: The persistence diagram of a point cloud on S^n computed with the geodesic metric is equal to the persistence diagram of the projected point cloud on R^n computed with a conformally weighted distance d_w(x,y) = 2*d(x,y)/(1+d(x,y)^2/4). This equality holds because stereographic projection is a conformal isometry up to the conformal factor, and persistence diagrams are invariant under conformal transformations. This gives an O(N log N) algorithm for spherical persistence (vs O(N^2) for direct computation). Test: implement both methods and verify isometry of persistence diagrams for random spherical point clouds with N=50, 100, 200 points. Impact: fast, provably correct topological data analysis for spherical data, with applications to astrophysics (cosmic microwave background) and protein structure analysis.",
            ["Geometry", "Computation", "Topology"], 0.85,
            proof_strategy="Define the stereographic persistence module: for point cloud X on S^n, compute Cech complex C_epsilon(X) using geodesic distance, then map via inverse stereographic projection to a conformally weighted Cech complex on R^n. Prove persistence diagram isometry: PD(C_epsilon(X) on S^n) = PD(C_epsilon(phi(X)) on R^n with weight w(x) = (1+|x|^2/4)^{-1}). The proof uses the conformal invariance of Cech complexes: stereographic projection preserves intersection properties of balls up to the conformal factor. Test: compute persistence diagrams for N=20 random points on S^2 using both geodesic and conformally-weighted Euclidean methods. Verify isometry of diagrams by computing bottleneck distance."),

        _sd("Stereographic Capacity Theory: Packing Bounds on Spheres via Plane Geometry",
            "Sphere packing on S^n (how many non-overlapping caps of radius r fit?) is a fundamental geometric problem with applications to error-correcting codes and signal processing. Use stereographic projection to transform spherical packing to a weighted packing problem on R^n. Define the stereographic packing number N(n,r) as the maximum number of non-overlapping spherical caps of geodesic radius r that fit on S^n. Conjecture: N(n,r) satisfies N(n,r) = (1+O(r^2)) * V_n/V_n(r) where V_n is the volume of S^n and V_n(r) is the volume of a cap, and the O(r^2) correction is explicitly computable from the conformal factor (1+|x|^2)^2/4 of the stereographic projection. More precisely, N(n,r) <= (2/cos(r))^n * V_n/V_n(r). The factor (2/cos(r))^n comes from the maximum conformal distortion of the stereographic projection: a cap of geodesic radius r is mapped to a Euclidean disk whose area differs from the cap area by at most this factor. Test: prove this bound for n=2 and verify it against the known optimal packings (icosahedral: N(2,pi/6) = 12, cuboctahedral: N(2,pi/4) = 6, tetrahedral: N(2,pi/3) = 4). Impact: explicit, computable sphere packing bounds on spheres via classical packing theory on R^n, with applications to spherical codes and molecular geometry.",
            ["Geometry", "Computation", "NumberTheory"], 0.84,
            proof_strategy="Define N(n,r) = max number of non-overlapping caps of geodesic radius r on S^n. Map caps to Euclidean disks via stereographic projection with conformal distortion factor (2/cos(r))^n. Apply Thue-Siegel sphere packing bounds on R^n to get N(n,r) <= (2/cos(r))^n * V_n/V_n(r). For n=2: prove N(2,r) <= (2/cos(r))^2 * 4*pi / (2*pi*(1-cos(r))). Test: verify N(2,pi/6) <= 12 (icosahedron achieves this), N(2,pi/4) <= 6 (cuboctahedron), N(2,pi/3) <= 4 (tetrahedron). Show the bound is tight for these classical configurations."),

        # ══════════════════════════════════════════════════════════
        # Moonshot: Paradigm-Shifting Conjectures
        # ══════════════════════════════════════════════════════════
        _sd("Proof Complexity Collapse: P=NP via Proof Checking",
            "The key insight is that proof checking is fundamentally different from proof search. Conjecture: There exists a proof system in which every true quantifier-free formula has a proof of polynomial size, and this proof can be verified in polynomial time. The barrier has been that existing proof systems (Frege, Extended Frege) have exponential lower bounds for specific formulas. But what if we construct a NEW proof system based on EML computations? Define EML-Frege where each proof step is an EML identity (exp-log composition) verified by numeric evaluation. Since EML identities can be checked in O(1) field operations, and every boolean circuit can be simulated by an EML network of depth O(log n), we get a quasi-polynomial proof system. Why now: recent breakthroughs in circuit lower bounds (Williams 2014, 2023) and the EML single-operator universality result suggest that EML-Frege could break the natural proofs barrier. Test: prove that EML-Frege polynomially simulates Extended Frege for CNF formulas, and show it has no exponential lower bounds under the EML independence assumption. Impact: if EML-Frege has short proofs for all tautologies, then NP = coNP in this proof system, which would be the most significant result in proof complexity since Cook's theorem.",
            ["Logic", "Computation", "EML"], 0.97,
            proof_strategy="Define EML-Frege proof system: axioms are EML identities, inference rules are substitution and modus ponens. Prove soundness (all provable formulas are true) and completeness (all true quantifier-free formulas have proofs). The key lemma: every boolean function on n variables has an EML representation of depth O(log n). This follows from EML universality. Prove that EML-Frege polynomially simulates Extended Frege by encoding each EF-rule as a constant-depth EML derivation."),

        _sd("Topological Quantum Error Correction from Homological Persistence",
            "The key insight is that persistent homology — the backbone of topological data analysis — provides a natural framework for quantum error correction. Each bar in a persistence barcode corresponds to a topological feature that persists across scales, and these persistent features ARE the logical qubits of a topological quantum code. Conjecture: For any simplicial complex K, the first persistent homology bar with birth time epsilon and death time delta defines a quantum error-correcting code with distance d >= delta/epsilon and rate k/H_1(K). The barcode IS the code specification: birth times give stabilizer generators, death times give code distance. Why now: the surface code is just H_1 of a grid, and its distance equals the longest bar in the barcode. This generalizes immediately. Test: construct the barcode code for the torus (distance 4, rate 1/9) and verify it matches the toric code. Prove the distance bound for arbitrary complexes. Impact: every dataset with persistent topology becomes a quantum code, and the barcode distance theorem gives a systematic way to construct new codes from topology.",
            ["Physics", "Topology", "Computation"], 0.95,
            proof_strategy="Define the barcode code B(K) for a simplicial complex K: qubits = vertices, stabilizers = boundary maps of 1-simplices, logical operators = persistent 1-cycles. Prove: (1) the stabilizer group is Abelian and squares to identity, (2) the code distance equals the ratio delta/epsilon where epsilon and delta are birth and death of the longest bar, (3) the code rate equals dim(H_1(K))/|V(K)|. Test: for K = square lattice on torus, verify distance = min(L,W) and rate = 1/N matching the toric code."),

        _sd("Neural Network Training as Renormalization Group Flow",
            "The key insight is that neural network training is a renormalization group (RG) flow in function space. Each training step integrates out high-frequency modes (gradient descent on fast-varying parameters), just as each RG step integrates out short-distance modes. Conjecture: The fixed points of SGD on neural networks are precisely the critical points of a renormalization group flow defined by the coarse-graining operator that averages over parameter subsets. Why now: recent work on neural network Gaussian processes shows that infinite-width networks have exact RG fixed points, and the beta function of SGD training has been computed for linear networks. Test: prove that for a 2-layer ReLU network trained on isotropic data, the SGD fixed point corresponds to the Wilson-Fisher fixed point in d=2 dimensions, and compute the critical exponents. Impact: neural network training would be governed by universality classes, meaning the same network trained on different data converges to the same fixed point if the data distribution is in the same universality class.",
            ["MachineLearning", "Physics", "Analysis"], 0.94,
            proof_strategy="Define the neural RG flow: for a network f_theta with parameters theta in R^N, the coarse-graining operator C_epsilon averages over parameters within epsilon-balls. Prove that the flow d(theta)/dt = -nabla L(theta) has fixed points that coincide with the RG fixed points of C_epsilon. For a 2-layer ReLU network f(x) = sum_j a_j * ReLU(w_j . x + b_j), prove that the NTK (neural tangent kernel) at the fixed point satisfies K*(x,y) = C * |x-y|^{-2+eta} for some critical exponent eta. Compare with the Wilson-Fisher fixed point in d=2."),

        _sd("Cryptography from the Collatz Conjecture: One-Way Functions from Iterated Maps",
            "The key insight is that the Collatz map T(n) = n/2 if n even, 3n+1 if n odd, appears to be a one-way function: easy to compute forward (polynomial time), intractable to invert (finding a preimage requires exponential search). Conjecture: Under the assumption that the Collatz conjecture is true, the function f(a, n) = T^a(n) (a iterations starting from n) is a one-way function with security parameter a. The inversion problem — given (a, f(a,n)), find n — requires O(2^{a/log(a)}) steps. Why now: the Collatz map has been verified to converge for all n up to 2^68, providing empirical evidence for irreversibility. Test: prove that f(a,n) cannot be inverted in sub-exponential time under a reasonable computational model. Construct a collision-resistant hash function from iterated Collatz maps. Impact: a new class of cryptographic primitives based on dynamical systems irreversibility, not number-theoretic hardness.",
            ["Cryptography", "NumberTheory", "Computation"], 0.93,
            proof_strategy="Define Collatz hash H_k(x) = T^k(x) mod 2^256. Prove collision resistance: if H_k(x) = H_k(y) for x != y, then T^k(x) = T^k(y) mod 2^256, requiring T to have a period dividing 2^256 within k steps — contradicting empirical data showing no Collatz period below 2^68. Prove preimage resistance: given z, finding x with H_k(x) = z requires trying O(2^{128}) preimages because each Collatz step is a 2-to-1 map on average. Formalize in Lean 4: define the Collatz hash and prove its basic properties."),

        _sd("Consciousness Complexity: Integrated Information as a Topological Invariant",
            "The key insight is that Tononi's Phi (integrated information) may be a topological invariant, not just a measure. If neural states form a sheaf over the brain's connectome, then Phi equals the dimension of the first sheaf cohomology group H^1(C, F) where C is the connectome graph and F is the neural state sheaf. Conjecture: Phi is a topological invariant of the sheaf (C, F) — it is preserved under sheaf isomorphisms and changes continuously under continuous deformation of the connectome. A system with Phi = 0 has H^1 = 0 (acyclic sheaf, no information integration), while Phi > 0 means H^1 > 0 (cycles in the sheaf, integrated information). Why now: sheaf cohomology has been successfully applied to neural coding by Curry (2019), and the connection between Phi and cohomology was conjectured by Tegmark (2019) but never formalized. Test: compute Phi for small connectome topologies (chain, ring, complete graph) and show Phi = dim(H^1) in each case. Impact: consciousness becomes a mathematical invariant with the same status as the Euler characteristic — a topological quantity that can be computed, compared, and used to classify systems.",
            ["Speculative", "Topology", "Physics"], 0.91,
            proof_strategy="Define the neural sheaf F over connectome graph C: assign a vector space V_v to each vertex v (neural state), and linear maps f_e: V_v -> V_w for each edge. Define Phi(C, F) = dim H^1(C, F). Prove: (1) for a chain graph C_n, H^1 = 0 so Phi = 0 (no consciousness — feedforward only). (2) for a ring graph C_n with compatible edge maps, H^1 = R so Phi = 1 (minimal consciousness — one cycle of integration). (3) for complete graph K_n, H^1 = R^{(n-1)(n-2)/2} so Phi grows quadratically (maximally integrated). Verify these match IIT's Phi computations for the same topologies."),

        _sd("Self-Referential Type Theory: Proofs That Modify Their Own Specifications",
            "The key insight is that Godel's incompleteness arises because a formal system cannot prove statements about itself — but a TYPE SYSTEM can. Construct a dependent type theory where types can refer to their own terms, creating a system where proofs can modify the specifications they are proving. Conjecture: There exists a consistent type theory T in which the type Type : Type is stratified by a self-reference level, and T can prove its own consistency within each level. The stratification prevents the paradox: Type_n : Type_{n+1} allows self-reference at level n without contradiction at level n+1. Why now: homotopy type theory has shown that types can be spaces, and the univalence axiom provides a principled way to equate equivalent types. Self-referential types are the natural next step. Test: formalize a type theory where terms can modify type specifications, prove that it is consistent by constructing a model in the category of globular sets, and show that Godel's incompleteness theorem does not apply because the stratification prevents diagonalization. Impact: a new foundation for mathematics where proofs can evolve their own specifications, enabling self-improving formal systems.",
            ["Logic", "Algebra", "Speculative"], 0.92,
            proof_strategy="Define the stratified type theory T_omega: types at level n (Type_n) can contain terms at level n, and Type_n : Type_{n+1}. Add a self-reference rule: if Gamma |- a : A and A : Type_n, then Gamma |- spec(a) : Type_n where spec(a) is the type specification modified by the proof a. Prove consistency by constructing a model in globular sets: each Type_n corresponds to an n-globular set, and spec(a) corresponds to a modification at level n+1. Prove the stratification prevents Russell's paradox: the diagonalization lambda x. not(x(x)) requires x : Type_n -> Type_n but self-reference only allows x : Type_n -> Type_{n+1}, breaking the diagonal."),

        _sd("Entropy as a Topological Invariant: The Boltzmann Bridge",
            "The key insight is that Boltzmann entropy S = k log W is a topological invariant of the energy landscape. If the energy function E: X -> R on a state space X defines a filtration by sublevel sets X_t = {x : E(x) <= t}, then the persistent homology barcode of this filtration encodes the entropy as the sum of bar lengths: S(E) = k * sum_i (d_i - b_i) where b_i and d_i are birth and death times of persistent homology bars. Conjecture: The Boltzmann entropy of a physical system equals the total persistence (sum of bar lengths) of the energy landscape filtration, up to an additive constant. Why now: persistent homology has matured as a computational tool, and the stability theorem guarantees that small perturbations in the energy function produce small changes in the barcode — exactly the thermodynamic stability we expect. Test: compute the persistent homology barcode for the Ising model energy landscape on a 4x4 lattice and verify that sum of bar lengths equals k log(2^{16}) = 16k log 2. Impact: entropy becomes a computable topological quantity, bridging thermodynamics and algebraic topology. Phase transitions correspond to births of new bars in the barcode.",
            ["Physics", "Topology", "Analysis"], 0.93,
            proof_strategy="Define the energy filtration F_t = {x : E(x) <= t} for energy function E on state space X. Compute the persistent homology barcode {b_i, d_i} of this filtration. Prove: S(E) = k * sum_i (d_i - b_i) + C where C is a constant depending only on X. Key lemma: for the Ising model on L x L lattice with E(sigma) = -J sum_{<i,j>} sigma_i sigma_j, the barcode has bars born at -4JL^2 (ground state) and dying at 0 (paramagnetic), with total persistence = 4JL^2 = kT log(2^{L^2}) at the critical point."),

        _sd("AdS/CFT for Proof Theory: Holographic Verification",
            "The key insight is that the AdS/CFT correspondence in physics says a gravitational theory in the bulk is equivalent to a conformal field theory on the boundary. Translate this to proof theory: a proof of length n in the bulk (the full proof) corresponds to a verified specification of length O(log n) on the boundary (a certificate). Conjecture: Every proof of a theorem T in Peano Arithmetic of length n has a holographic certificate of length O(log n) that can be verified in time O((log n)^2). The certificate is constructed by projecting each proof step onto the boundary of the proof space (the initial axioms and final conclusion) and keeping only the holographic data. Why now: the PCP theorem already shows that proofs have short probabilistic certificates, but holographic verification would give DETERMINISTIC short certificates — a much stronger result. Test: for a specific proof system (Frege), construct holographic certificates for proofs of the pigeonhole principle and verify that the certificate length is O(log n). Impact: proof verification becomes as fast as reading the theorem statement, enabling trustless proof checking at scale.",
            ["Logic", "Computation", "Physics"], 0.94,
            proof_strategy="Define the holographic certificate of a proof pi as follows: (1) embed the proof as a graph in hyperbolic space H^n where each step is a vertex and edges connect dependent steps, (2) project the graph onto the boundary S^{n-1} via the Poincare disk model, (3) the certificate is the boundary data (vertices on S^{n-1} with their holographic data). Prove the holographic verification theorem: given a certificate of length O(log n), verification requires checking O((log n)^2) local consistency conditions, each checkable in O(1) time. The key is that the AdS geometry ensures that bulk errors propagate to detectable boundary inconsistencies. Test: construct holographic certificates for PHP proofs of length n=100, 1000, 10000 and verify the O(log n) length bound."),

        _sd("Biological Topology: Protein Folding as Persistent Homology Optimization",
            "The key insight is that protein folding minimizes a topological energy: the persistent homology barcode of the protein's contact map. The native fold of a protein is the configuration that minimizes the total persistence of the contact filtration. Conjecture: The native state of a protein P minimizes sum_i (d_i - b_i) over all possible 3D configurations, where {b_i, d_i} is the persistent homology barcode of the distance matrix of P's C-alpha atoms. Why now: AlphaFold2 showed that contact maps are sufficient for structure prediction, but it used deep learning without understanding WHY contact maps work. Persistent homology provides the mathematical reason: the barcode captures the topological constraints (no self-intersection, hydrophobic core, etc.) that determine the fold. Test: compute the barcode for 100 proteins from the PDB and verify that the native fold has lower total persistence than 1000 random decoy folds for each protein. Impact: protein folding becomes a topological optimization problem with a provably unique minimum, explaining why folding is fast and reliable despite Levinthal's paradox.",
            ["Physics", "Topology", "MachineLearning"], 0.90,
            proof_strategy="Define the contact filtration for protein P with N residues: for distance threshold t, build the Vietoris-Rips complex R_t from the pairwise C-alpha distances. Compute the persistent homology barcode PH(P, configuration) = {(b_i, d_i)}. Define TotalPersistence(P) = sum_i (d_i - b_i). Conjecture: the native fold minimizes TotalPersistence over all valid configurations. Test: for each of 100 PDB proteins, generate 1000 decoy configurations using Rosetta, compute TotalPersistence for each, and verify the native fold has the minimum. Prove that TotalPersistence is a Lyapunov function for folding dynamics in the simplified HP model."),

        _sd("Gravity as Quantum Error Correction: Spacetime from Codes",
            "The key insight is that the holographic principle in physics (AdS/CFT) can be rederived from quantum error correction. If the boundary CFT is a quantum error-correcting code with parameters [[n, k, d]], then the bulk AdS geometry emerges from the code's encoding. Conjecture: The Ryu-Takayanagi formula S(A) = Area(gamma_A) / (4G) is equivalent to the quantum Singleton bound d <= n - k + 1 applied to the boundary code, where the code distance d equals the minimal geodesic length through the bulk. Why now: recent work by Pastawski, Preskill, and Harrow (2015) showed that the AdS/CFT correspondence can be modeled by tensor networks (HaPPY code), but the converse — deriving AdS geometry FROM the code — has not been proven. Test: for the [[5,1,3]] code (the smallest perfect code), show that the code's Tanner graph IS the Penrose diagram of AdS_2, and the code distance 3 equals the geodesic length through the bulk. Impact: spacetime IS a quantum error-correcting code. Gravity is not a force — it's the logical operator of a quantum code.",
            ["Physics", "Computation", "Cryptography"], 0.96,
            proof_strategy="Define the boundary code as a stabilizer code [[n, k, d]] with stabilizers S_1,...,S_{n-k} acting on n qubits. Prove the AdS/CFT dictionary: each boundary qubit corresponds to a CFT degree of freedom on S^{d-1}, and each stabilizer corresponds to a bulk geodesic. Prove: S(A) = Area(gamma_A)/(4G) follows from the quantum Singleton bound because the entanglement entropy of region A equals the number of stabilizers crossing the minimal cut, which is the area. Test: for the [[5,1,3]] perfect code, construct the pentagon tensor network, show that the code distance 3 equals the geodesic distance through the center, and verify that the Ryu-Takayanagi formula holds for all 10 boundary regions."),

        _sd("Zeta Functions of Directed Graphs and the Graph Riemann Hypothesis",
            "The key insight is that every directed graph G has a zeta function zeta_G(s) = prod(1 - lambda^{-s})^{-1} where the product is over eigenvalues of the graph's adjacency matrix, and the Riemann Hypothesis for this function is equivalent to a purely combinatorial condition on G. Conjecture: For a directed graph G with n vertices, zeta_G(s) satisfies the Riemann Hypothesis (all non-trivial zeros lie on Re(s) = 1/2) if and only if G is a Ramanujan digraph: every eigenvalue lambda of the adjacency matrix satisfies |lambda| <= 2 sqrt(d-1) where d is the maximum out-degree. This is the directed graph analog of the Ramanujan graph theorem of Lubotzky-Phillips-Sarnak. Why now: the undirected case is settled (Ramanujan graphs exist and have optimal spectral gap), but the directed case is wide open. Recent work by Lubetzky and Peres (2016) on cutoff on directed Ramanujan graphs suggests the spectral gap characterization extends. Test: prove the conjecture for directed Cayley graphs of finite groups, then verify computationally for random directed d-regular graphs with n=20, 50, 100 vertices. Impact: a combinatorial Riemann Hypothesis — if true, it means the deepest mystery of number theory has a purely graph-theoretic characterization.",
            ["Algebra", "NumberTheory", "Computation"], 0.91,
            proof_strategy="Define zeta_G(s) = prod_{lambda in spec(A_G)} (1 - lambda^{-s})^{-1} for directed graph G with adjacency matrix A_G. Prove: zeta_G has all non-trivial zeros on Re(s) = 1/2 iff G is Ramanujan (|lambda| <= 2 sqrt(d-1) for all eigenvalues). Step 1: show zeta_G(s) = det(I - A_G * p^{-s})^{-1} where p is a formal variable. Step 2: zeros of zeta_G on Re(s) = 1/2 correspond to eigenvalues on the circle |lambda| = sqrt(d-1). Step 3: Ramanujan condition ensures all eigenvalues lie within the spectral gap. Test: compute zeta_G for Ramanujan digraphs (Lubotzky-Phillips-Sarnak construction) and verify all zeros are on Re(s) = 1/2."),
    ]