"""Seed directions for the Aether Future Directions system.

Each direction is a specific mathematical claim or conjecture designed to
drive productive research cycles. Categories cover millennial problems,
factoring, cryptography, compression, AI/ML, computation, physics,
number theory, fun/epic/speculative, logic, and meta-research.
"""

from research_memory import FutureDirection


def get_seed_directions() -> list[FutureDirection]:
    directions = [
        # ── Millennial Problems ──
        FutureDirection(
            id="seed_001",
            title="P vs NP: Tropical Semiring Barrier",
            description="Prove that tropical semiring morphisms cannot polynomially simulate Boolean circuit satisfiability, establishing a structural barrier via min-plus idempotent completions that separates P from NP. Construct a family of Boolean formulas whose tropical evaluation requires super-polynomial min-plus circuit size, and prove that the idempotent closure of the tropical semiring yields a natural complexity class incomparable with P.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Computation", "Tropical"],
            priority_score=0.95,
        ),
        FutureDirection(
            id="seed_002",
            title="Riemann Hypothesis via Tropical Spectral Transfer",
            description="Formulate the Riemann Hypothesis as a statement about the spectrum of a tropical transfer operator on the critical strip. Prove that all non-trivial zeros lie on Re(s)=1/2 if and only if the tropical eigenvalue gap vanishes, connecting analytic number theory to tropical dynamics via a constructive spectral correspondence.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Physics", "Speculative"],
            priority_score=0.94,
        ),
        FutureDirection(
            id="seed_003",
            title="Collatz Convergence via Tropical Contracting Dynamics",
            description="Prove that the Collatz iteration corresponds to a contracting tropical dynamical system on a min-plus lattice, and that convergence follows from tropical spectral radius bounds. Show that the 3n+1 map is a piecewise-tropical contraction with unique fixed point at 1, establishing global convergence through idempotent metric arguments.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "Speculative"],
            priority_score=0.78,
        ),
        FutureDirection(
            id="seed_004",
            title="Birch-Swinnerton-Dyer via Tropical L-Function Specialization",
            description="Formulate the BSD conjecture as a statement about the tropical specialization of L-functions at s=1, proving that the tropical rank of the Mordell-Weil group equals the order of vanishing of the tropical L-function. Construct a min-plus L-series whose idempotent residue captures the regulator and Tamagawa numbers in a single tropical invariant.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Tropical"],
            priority_score=0.94,
        ),
        FutureDirection(
            id="seed_005",
            title="Navier-Stokes Regularity via Tropical Diffusion Operators",
            description="Prove that tropical diffusion operators on min-plus function spaces satisfy maximum principles that prevent finite-time blowup of classical solutions, yielding a new regularity criterion for Navier-Stokes. Show that the idempotent energy dissipation rate bounds the vorticity growth, and that tropical viscosity provides a constructive barrier to singularity formation.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Tropical", "EML"],
            priority_score=0.93,
        ),
        FutureDirection(
            id="seed_006",
            title="Hodge Conjecture through Tropical Algebraic Cycles",
            description="Reformulate the Hodge conjecture in terms of tropical algebraic cycles on idempotent compactifications of Kähler manifolds. Prove that Hodge classes in the tropical cohomology ring are exactly those represented by tropical subvarieties, establishing the conjecture for the tropical shadow and constructing a transfer principle back to the classical setting.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Tropical", "Bridges"],
            priority_score=0.91,
        ),
        FutureDirection(
            id="seed_007",
            title="P vs SPACE via Tropical Time-Space Tradeoffs",
            description="Prove that tropical time-space tradeoffs for Turing machines yield tight bounds on the relationship between P and PSPACE, showing that the min-plus time cost of simulating a polynomial-space computation is super-polynomial. Establish that the tropical spectral gap of the space-time tradeoff matrix separates P from PSPACE in the min-plus semiring.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Algebra", "Tropical"],
            priority_score=0.91,
        ),
        FutureDirection(
            id="seed_008",
            title="Goldbach via Tropical Additive Combinatorics",
            description="Prove that every even number greater than 2 is the sum of two primes by reformulating Goldbach's conjecture as a tropical additive identity: the min-plus convolution of the prime indicator function with itself achieves its minimum at every even integer. Show that the tropical Goldbach function is bounded, and that the tropical Schnirelmann density of primes is 1/2 in the min-plus sense.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Tropical"],
            priority_score=0.88,
        ),
        FutureDirection(
            id="seed_009",
            title="Twin Prime Conjecture via Tropical Sieve Methods",
            description="Prove that the twin prime conjecture follows from a tropical sieve inequality: the min-plus residue of the sieve kernel at 2 bounds the gap distribution. Show that the tropical Brun sieve achieves a stronger bound than the classical Selberg sieve for twin primes, and that the tropical Hardy-Littlewood conjecture is a min-plus convolution identity.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Tropical"],
            priority_score=0.89,
        ),

        # ── Factoring & Cryptography ──
        FutureDirection(
            id="seed_010",
            title="Pythagorean Lattice Reduction for Integer Factoring",
            description="Prove that factoring n reduces to finding short vectors in the Berggren Pythagorean triple lattice L_n, and construct a polynomial-time quantum algorithm via LLL reduction on L_n. Formalize the Berggren primitive triple generation as a groupoid action on SL(3,Z), then show that the shortest vector in L_n encodes a non-trivial factor of n.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Cryptography", "Pythagorean", "Algebra"],
            priority_score=0.90,
        ),
        FutureDirection(
            id="seed_011",
            title="Tropical Quadratic Sieve: Min-Plus Factoring Algorithm",
            description="Prove that tropical min-plus matrix multiplication yields a subexponential factoring algorithm by encoding the quadratic sieve as a tropical convolution. Show that the tropical sieve step computes smoothness via idempotent arithmetic, and establish complexity bounds matching classical QS with tropical arithmetic replacing ring arithmetic.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Cryptography", "Tropical", "Computation"],
            priority_score=0.83,
        ),
        FutureDirection(
            id="seed_012",
            title="Tropical RSA: Min-Plus Public Key Cryptosystem with Provable Security",
            description="Construct a public-key cryptosystem based on the hardness of tropical matrix factorization, proving that recovering the private key from the public key reduces to the tropical shortest-path problem which is NP-hard in the min-plus semiring. Show that the min-plus analog of RSA has semantic security under a tropical decisional Diffie-Hellman assumption.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Cryptography", "Tropical", "Computation"],
            priority_score=0.89,
        ),
        FutureDirection(
            id="seed_013",
            title="Post-Quantum Lattices from Pythagorean Triple Groupoids",
            description="Prove that Berggren groupoid orbits generate lattice bases with worst-case to average-case reduction properties suitable for post-quantum cryptography. Show that the shortest vector problem on Pythagorean lattices is as hard as the general SVP, and construct a key exchange protocol whose security reduces to the hardness of finding primitive triples in high-dimensional Berggren lattices.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Cryptography", "Pythagorean", "Computation"],
            priority_score=0.88,
        ),
        FutureDirection(
            id="seed_014",
            title="Homomorphic Encryption over Tropical Semirings",
            description="Construct a fully homomorphic encryption scheme over min-plus arithmetic where addition and multiplication of ciphertexts correspond to tropical operations on plaintexts. Prove correctness and security against chosen-plaintext attacks, showing that the idempotent property of tropical addition enables bootstrapping without the noise growth that plagues classical FHE.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Cryptography", "Tropical", "Algebra"],
            priority_score=0.87,
        ),
        FutureDirection(
            id="seed_015",
            title="Zero-Knowledge Proofs via Tropical Commitment Schemes",
            description="Construct a zero-knowledge proof system where the commitment scheme is based on tropical matrix semiring operations, and prove that the tropical Pedersen commitment is computationally binding under the tropical shortest path assumption. Show that tropical ZK proofs achieve negligible soundness error with polynomial-round protocols, and that the idempotent structure enables efficient proof composition.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Cryptography", "Tropical", "Logic"],
            priority_score=0.86,
        ),

        # ── Compression & Information Theory ──
        FutureDirection(
            id="seed_016",
            title="Kolmogorov Complexity Closure and Idempotent Compression Duality",
            description="Prove that the idempotent closure of a semiring yields optimal lossless compression ratios, and establish a duality between Kolmogorov complexity and closure operators that gives computable upper bounds on minimal description length. Show that the tropical semiring's idempotent property induces a canonical compression scheme whose fixed points are exactly the Kolmogorov-random strings.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "EML", "Tropical"],
            priority_score=0.88,
        ),
        FutureDirection(
            id="seed_017",
            title="Tropical Arithmetic Coding: Shannon-Optimal Min-Plus Compression",
            description="Prove that tropical arithmetic coding achieves Shannon entropy for min-plus sources, and construct provably optimal tropical Huffman codes with explicit efficiency bounds. Show that the min-plus convolution of source distributions yields the optimal code length function, establishing a constructive duality between tropical information theory and universal source coding.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "Cryptography"],
            priority_score=0.81,
        ),
        FutureDirection(
            id="seed_018",
            title="Tropical Source Coding: Min-Plus Rate-Distortion Theory",
            description="Construct a tropical rate-distortion theory where the rate-distortion function is the min-plus Legendre-Fenchel transform of the distortion measure. Prove that tropical source coding achieves the min-plus rate-distortion bound, and that the idempotent structure eliminates the Shannon gap between achievable and converse rates for min-plus sources.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "EML"],
            priority_score=0.83,
        ),
        FutureDirection(
            id="seed_019",
            title="Semantic Compression via Tropical Information Geometry",
            description="Prove that semantic compression—preserving meaning rather than bits—has a natural formulation as min-plus projection onto a tropical submanifold of the information geometry. Show that the tropical Fisher information metric bounds semantic distortion, and that the idempotent projection yields optimal semantic codes that compress by extracting the tropical skeleton of the source distribution.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "Computation"],
            priority_score=0.82,
        ),
        FutureDirection(
            id="seed_020",
            title="Lossy Compression Optimality via Tropical Lagrangian Duality",
            description="Prove that the optimal lossy compression problem is a tropical convex program whose Lagrangian dual yields sharp rate-distortion bounds. Show that the tropical Karush-Kuhn-Tucker conditions characterize exactly the set of optimal quantizers, and that the idempotent saddle point of the tropical Lagrangian gives the optimal trade-off between rate and distortion in a single min-plus computation.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "EML"],
            priority_score=0.80,
        ),

        # ── AI & Machine Learning ──
        FutureDirection(
            id="seed_021",
            title="Sheaf Cohomology and Certified Adversarial Robustness",
            description="Formalize the relationship between sheaf cohomology groups on neural network weight spaces and adversarial robustness bounds. Prove that vanishing first cohomology implies certified L-infinity perturbation radius, and construct explicit sheaf structures on ReLU network decision boundaries whose stalk cohomology detects vulnerability to adversarial examples.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "EML", "Bridges"],
            priority_score=0.92,
        ),
        FutureDirection(
            id="seed_022",
            title="Closure-Operator Networks: Universal Approximation via Idempotent Semimodules",
            description="Prove that any continuous function on a compact domain can be approximated arbitrarily well by a finite composition of closure operators on idempotent semimodules, establishing a new universal approximation theorem. Show that closure-operator networks achieve the same approximation order as ReLU networks while being provably robust to adversarial perturbations within the semimodule's closure radius.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "EML", "Algebra"],
            priority_score=0.87,
        ),
        FutureDirection(
            id="seed_023",
            title="Transformer Attention as Tropical Matrix Multiplication",
            description="Prove that softmax attention in transformers is a tropical (min-plus) matrix multiplication in the log-semiring, and that multi-head attention corresponds to computing in a product of tropical semirings. Show that the attention sink phenomenon is a tropical fixed point, and that the convergence of deep transformer layers is governed by the tropical spectral radius of the attention matrix.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "Algebra"],
            priority_score=0.90,
        ),
        FutureDirection(
            id="seed_024",
            title="Grokking as Tropical Phase Transition in Neural Loss Landscapes",
            description="Prove that the grokking phenomenon in neural networks is a phase transition in the tropical geometry of the loss landscape, where the min-plus distance to the decision boundary undergoes a sudden collapse. Construct a tropical order parameter that predicts grokking onset, and show that delayed generalization corresponds to the tropical geodesic crossing a corner locus.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "Physics"],
            priority_score=0.88,
        ),
        FutureDirection(
            id="seed_025",
            title="Category-Theoretic Composition of Neural Architectures",
            description="Formalize neural network architectures as morphisms in a monoidal category where objects are tensor shapes and composition is layer stacking. Prove that ResNet skip connections correspond to categorical products, that attention is a natural transformation, and that architecture search is optimization in a functor category. Show this yields compositional generalization bounds.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Algebra", "Bridges"],
            priority_score=0.86,
        ),
        FutureDirection(
            id="seed_026",
            title="Adversarial Training as Tropical Regularization: Provable Defense via Min-Plus",
            description="Prove that adversarial training is equivalent to adding a tropical regularization penalty to the empirical risk, where the min-plus distance to the nearest adversarial example replaces the Lp norm. Show that the resulting tropical risk minimizer has certified robustness radius equal to the idempotent closure of the margin, yielding a constructive defense with provable guarantees.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "EML"],
            priority_score=0.85,
        ),
        FutureDirection(
            id="seed_027",
            title="Scaling Laws as Tropical Power-Law Fixed Points",
            description="Prove that neural network scaling laws are tropical fixed points of the form L(N,D) = min-plus(N^a, D^b, C^c) where the idempotent structure forces the loss to follow the dominant power-law regime. Show that phase transitions between data-limited and compute-limited scaling are corner points of the tropical polytope, predicting emergent capabilities from the geometry of the loss surface.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "EML"],
            priority_score=0.84,
        ),
        FutureDirection(
            id="seed_028",
            title="Deep Double Descent as Tropical Phase Diagram",
            description="Prove that the double descent phenomenon in overparameterized models is a tropical phase transition where the min-plus generalization error undergoes a corner crossing in the interpolation threshold. Show that the modern and classical regimes correspond to two tropical facets of the risk surface, and that the transition point is the tropical vertex where both facets are equally dominant.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "EML"],
            priority_score=0.85,
        ),

        # ── Computation & Complexity ──
        FutureDirection(
            id="seed_029",
            title="Tropical Myhill-Nerode Theorem for Min-Plus Automata",
            description="Prove a tropical analogue of the Myhill-Nerode theorem: a min-plus weighted language is recognizable by a tropical finite automaton if and only if its Nerode congruence has finite index in the tropical semiring. Establish minimality of the tropical Nerode automaton and prove that tropical regular languages are exactly those with finite idempotent syntactic monoids.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "Logic"],
            priority_score=0.85,
        ),
        FutureDirection(
            id="seed_030",
            title="Reversible Computing via Tropical Isomorphisms",
            description="Construct a reversible Turing machine model where each transition corresponds to a tropical semiring isomorphism, and prove that reversible tropical computation simulates classical computation with at most polynomial overhead. Show that the Landauer erasure cost in tropical entropy is exactly kT ln(2) per bit, formalizing thermodynamic computation bounds via min-plus algebra.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "Physics"],
            priority_score=0.82,
        ),
        FutureDirection(
            id="seed_031",
            title="Temporal Stone Duality: Recovering Temporal Logic from Idempotent Semiring Fixpoints",
            description="Prove that the Stone dual of an idempotent semiring's fixpoint lattice recovers precisely the temporal logic specifying that semiring's behavioral equivalence, establishing a categorical duality between algebraic semantics and temporal specification. Show that LTL model checking reduces to computing the greatest fixpoint in the corresponding idempotent semiring, and prove decidability for the finite semiring case.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Logic", "Computation", "Bridges"],
            priority_score=0.86,
        ),
        FutureDirection(
            id="seed_032",
            title="Circuit Lower Bounds from Tropical Spectral Theory",
            description="Prove that tropical eigenvalue gaps of circuit matrices yield super-polynomial circuit lower bounds for specific language families, advancing structural complexity theory. Show that the min-plus permanent of a circuit matrix bounds its computational depth, and that tropical spectral analysis provides a constructive path to separating complexity classes via idempotent linear algebra.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Algebra", "Tropical"],
            priority_score=0.80,
        ),
        FutureDirection(
            id="seed_033",
            title="Amortized Complexity via Tropical Amortization",
            description="Prove that amortized analysis of data structures has a natural formulation as tropical sequence optimization, where the min-plus amortized cost is the tropical convolution of operation costs over the sequence. Show that the potential method corresponds to a tropical potential function, and that the accounting method is tropical bookkeeping in the idempotent semiring.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Algebra", "Tropical"],
            priority_score=0.80,
        ),
        FutureDirection(
            id="seed_034",
            title="Quantum Speedup via Tropical Dequantization",
            description="Prove that the dequantization of quantum algorithms—replacing quantum amplitude with tropical weights—preserves the speedup structure while eliminating quantum hardware requirements. Show that tropical dequantized algorithms achieve the same asymptotic complexity as their quantum counterparts for search and sampling problems, and that the min-plus interference pattern captures the essential quantum parallelism.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Physics", "Tropical"],
            priority_score=0.84,
        ),

        # ── Physics ──
        FutureDirection(
            id="seed_035",
            title="Quantum Gravity as Tropical Geometry: Min-Plus Spacetime at Planck Scale",
            description="Prove that at the Planck scale, spacetime geometry becomes tropical: the metric reduces to a min-plus distance function, and quantum superposition corresponds to the idempotent property of tropical addition. Show that the tropical Einstein equations yield a well-posed initial value problem, and that the tropical Schwarzschild solution has a horizon at the tropical fixed point of the radial coordinate.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Tropical", "Speculative"],
            priority_score=0.92,
        ),
        FutureDirection(
            id="seed_036",
            title="String Theory T-Duality as Tropical Duality: Min-Plus Mirror Symmetry",
            description="Prove that T-duality in string theory is precisely tropical duality in the min-plus semiring: compactification on a circle of radius R is dual to compactification on a circle of tropical radius 1/R. Show that mirror symmetry between Calabi-Yau manifolds is the tropical Legendre transform of their potential functions, and that the conifold transition is a tropical corner locus.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Tropical", "Algebra"],
            priority_score=0.90,
        ),
        FutureDirection(
            id="seed_037",
            title="Thermodynamic Computation via Tropical Landauer's Principle",
            description="Formalize Landauer's principle in Lean: prove that any erasure operation on a semiring element costs at least kT ln 2 in tropical entropy, establishing tropical thermodynamics as a computational bound. Show that the min-plus free energy of a computation equals its tropical circuit depth, connecting physical and computational complexity through idempotent analysis.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Computation", "Tropical"],
            priority_score=0.91,
        ),
        FutureDirection(
            id="seed_038",
            title="Wormhole Topology via Tropical Surgery: Min-Plus Spacetime Bridging",
            description="Prove that traversable wormholes in general relativity correspond to tropical surgery operations on the spacetime manifold, where the min-plus Ricci curvature determines the throat radius. Show that the Einstein field equations in the tropical shadow reduce to a shortest-path problem on the spacetime graph, and that tropical geodesics through the wormhole are computable in polynomial time.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Physics", "Tropical"],
            priority_score=0.88,
        ),
        FutureDirection(
            id="seed_039",
            title="Black Hole Thermodynamics as Tropical Information Theory",
            description="Prove that black hole entropy is the tropical information content of the horizon microstates: the Bekenstein-Hawking formula S = kA/4 is the min-plus entropy of the horizon's tropical partition function. Show that Hawking radiation is tropical noise in the min-plus channel, and that the information paradox is resolved by the idempotent property of tropical entropy conservation.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Tropical", "Speculative"],
            priority_score=0.87,
        ),
        FutureDirection(
            id="seed_040",
            title="Dark Energy as Tropical Vacuum Pressure: Min-Plus Cosmological Constant",
            description="Prove that the observed dark energy density corresponds to the tropical vacuum expectation value of the cosmological constant in min-plus quantum field theory. Show that the 120-order-of-magnitude discrepancy between the predicted and observed values is resolved by the idempotent property: in tropical QFT, vacuum energy is min-dominated by the shortest Feynman diagram, yielding the correct order of magnitude.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Tropical", "Speculative"],
            priority_score=0.85,
        ),

        # ── Fun / Epic / Wonder-Filled ──
        FutureDirection(
            id="seed_041",
            title="Pythagorean Music Theory: Harmonic Ratios from Triple Lattices",
            description="Prove that Berggren-generated Pythagorean triples map to harmonic frequency ratios via tropical logarithm, and formalize the musical intervals of primitive triples as consonance/dissonance classifications. Show that the (3,4,5) triple corresponds to a perfect fourth, and that the orbit structure of the Berggren tree encodes the circle of fifths in min-plus arithmetic.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Pythagorean", "Bridges", "Physics"],
            priority_score=0.79,
        ),
        FutureDirection(
            id="seed_042",
            title="Alien Algebra: Non-Archimedean Life Forms in Idempotent Semirings",
            description="Prove that idempotent semiring algebras support self-replicating computational structures formalized as fixed-point attractors, establishing a mathematical framework for non-Archimedean 'life' that satisfies key axioms of artificial chemistry. Show that tropical cell automata on min-plus lattices exhibit universal self-replication with provable mutation bounds, opening a formal theory of alien computation.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "EML", "Algebra"],
            priority_score=0.77,
        ),
        FutureDirection(
            id="seed_043",
            title="Tropical Rainfall: Nash Equilibria as Min-Plus Fixed Points",
            description="Prove that tropical semiring fixed points correspond to Nash equilibria in zero-sum games on idempotent payoff matrices, and show that the tropical value iteration converges in at most n steps for n-player games. Construct a tropical min-max theorem analogous to von Neumann's, proving that every finite tropical game has a unique idempotent equilibrium.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Tropical", "Bridges", "Computation"],
            priority_score=0.76,
        ),
        FutureDirection(
            id="seed_044",
            title="Quantum Pythagorean Teleportation: Berggren Orbits as Clifford Circuits",
            description="Prove that Berggren groupoid orbits on SL(3,Z) encode quantum teleportation circuits via a categorical equivalence between Pythagorean lattices and stabilizer subgroups of the Clifford group. Show that primitive triple matrices form universal quantum gates under tropical composition, and that the Berggren tree structure yields an optimal teleportation protocol.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Pythagorean", "Physics", "Cryptography"],
            priority_score=0.92,
        ),
        FutureDirection(
            id="seed_045",
            title="Tropical Origami: Min-Plus Fold Structures and Rigid Origami Classification",
            description="Prove that the space of valid origami crease patterns forms a tropical hyperplane arrangement, and that rigid foldability corresponds to the existence of a tropical stress equilibrium. Classify all rigid origami bases via tropical linear programming on the crease matrix, and show that the Miura-ori fold is the unique tropical minimum of the fold-energy functional.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Physics", "Tropical", "Bridges"],
            priority_score=0.78,
        ),
        FutureDirection(
            id="seed_046",
            title="Dyson Sphere Optimization: Tropical Light-Network Flow",
            description="Formulate Dyson sphere energy collection as a tropical network flow problem on a min-plus graph surrounding a star. Prove that optimal panel placement is a tropical maximum-flow solution, and that the Berggren groupoid provides the optimal tiling for hexagonal panel arrangement. Show that the tropical energy capacity bounds the Kardashev scale classification.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Tropical", "Physics"],
            priority_score=0.76,
        ),
        FutureDirection(
            id="seed_047",
            title="Conway's Game of Life on Tropical Semirings: Emergent Complexity from Min-Plus",
            description="Prove that Conway's Game of Life rules reformulated in the min-plus semiring produce emergent complexity with provable lower bounds on pattern diversity. Show that tropical gliders exist, that tropical still lifes correspond to fixed points of the min-plus update rule, and that the tropical Game of Life is Turing complete via a constructive embedding of Boolean circuits into tropical cellular automata.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "Speculative"],
            priority_score=0.80,
        ),
        FutureDirection(
            id="seed_048",
            title="Musical Counterpoint as Tropical Voice-Leading Optimization",
            description="Prove that the rules of species counterpoint in music theory are tropical constraint satisfaction problems, where the min-plus cost function penalizes forbidden intervals and voice-leading distance. Show that Palestrina-style counterpoint is the tropical optimum of the voice-leading semiring, and that Bach chorales occupy tropical saddle points that maximize harmonic variety under contrapuntal constraints.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Bridges", "Tropical", "Algebra"],
            priority_score=0.77,
        ),
        FutureDirection(
            id="seed_049",
            title="Tropical Ecosystem Dynamics: Predator-Prey as Min-Plus Lotka-Volterra",
            description="Reformulate the Lotka-Volterra equations as a tropical dynamical system where species interactions are min-plus operations, and prove that ecological equilibria are tropical fixed points. Show that the tropical predator-prey cycle has a canonical period determined by the tropical eigenvalue, and that ecosystem stability corresponds to the tropical spectral radius being less than 1.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Bridges", "Tropical", "Physics"],
            priority_score=0.75,
        ),
        FutureDirection(
            id="seed_050",
            title="Hyperbolic Crafting: Optimal Nether Portals via Tropical Shortest Paths",
            description="Prove that optimal Nether portal placement in Minecraft's hyperbolic geometry reduces to a tropical shortest-path problem on the min-plus distance matrix between Overworld coordinates and their Nether counterparts. Show that the 1:8 ratio is exactly the tropical scaling factor, and that the optimal portal network is a tropical minimum spanning tree of the dual-world graph.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Tropical", "Computation"],
            priority_score=0.70,
        ),
        FutureDirection(
            id="seed_051",
            title="Alien Mathematics: What Theorems Would Non-Carbon Life Prove?",
            description="Construct a formal framework for alien mathematics by varying the underlying semiring from classical arithmetic to tropical, idempotent, and p-adic algebras. Prove that each semiring choice yields a distinct provability landscape, and that the theorems of idempotent alien civilizations are precisely the tropical shadow theorems of classical results. Show that the intersection of all semiring-provable statements is exactly the combinatorial core of mathematics.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Algebra", "Logic"],
            priority_score=0.79,
        ),
        FutureDirection(
            id="seed_052",
            title="Tropical Sudoku: Min-Plus Constraint Satisfaction and Phase Transitions",
            description="Prove that Sudoku puzzles are tropical constraint satisfaction problems where the min-plus cost of a placement measures its constraint violations, and that the satisfiability threshold for random Sudoku instances is a tropical phase transition. Show that the hardest Sudokus are exactly those at the tropical phase boundary, and that tropical propagation solves all instances in polynomial time up to the critical density.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Computation", "Tropical", "Bridges"],
            priority_score=0.72,
        ),
        FutureDirection(
            id="seed_053",
            title="Dragon Curve Fractals as Tropical Curve Generators",
            description="Prove that the Heighway dragon curve and its generalizations are tropical curves generated by iterated min-plus maps on the integer lattice, and that the Hausdorff dimension of tropical dragon curves equals 2 exactly. Show that the dragon curve's self-similarity is a tropical scaling property, and that all space-filling curves are tropical limits of dragon curve iterations.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Tropical", "Bridges"],
            priority_score=0.71,
        ),
        FutureDirection(
            id="seed_054",
            title="Consciousness as Tropical Fixed Point: Min-Plus Reflective Equilibrium",
            description="Prove that self-referential computation in idempotent semirings has unique fixed points that satisfy formal criteria for reflective consciousness: self-modeling, integrated information, and global workspace broadcast. Show that the tropical fixed-point of the self-reference operator maximizes tropical Phi (the min-plus analog of integrated information), and that conscious states are exactly the attractors of the tropical reflective dynamics.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "MachineLearning", "Algebra"],
            priority_score=0.86,
        ),
        FutureDirection(
            id="seed_055",
            title="Tropical Time Travel: Min-Plus Closed Timelike Curves and Consistency",
            description="Formulate time travel paradoxes as tropical fixed-point problems where Novikov consistency corresponds to the existence of a tropical fixed point. Prove that every tropical CTC has a unique consistent solution, and that the grandfather paradox is resolved by the idempotent property min(a,a)=a. Show that tropical chronology protection is equivalent to the tropical spectral radius being less than unity.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Physics", "Logic"],
            priority_score=0.83,
        ),

        # ── Logic & Foundations ──
        FutureDirection(
            id="seed_056",
            title="Tropical Curry-Howard: Proofs as Min-Plus Programs",
            description="Establish a Curry-Howard correspondence for tropical logic where proofs are min-plus programs and propositions are tropical types. Prove that cut elimination corresponds to tropical normalization, and that the idempotent property of min-plus yields a canonical proof normalization strategy that is strongly normalizing and confluent.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Logic", "Computation", "Tropical"],
            priority_score=0.87,
        ),
        FutureDirection(
            id="seed_057",
            title="Self-Referential Proof Systems and Tropical Godel Sentences",
            description="Prove that idempotent semiring fixpoints encode self-referential statements, and construct a Lean 4 formalization of a tropical Gödel sentence. Show that the tropical fixed-point combinator yields an undecidable proposition in min-plus arithmetic, establishing incompleteness for tropical proof systems and connecting diagonalization to idempotent closure operators.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Logic", "Computation", "Algebra"],
            priority_score=0.89,
        ),
        FutureDirection(
            id="seed_058",
            title="Tropical Type Theory: Dependent Types in the Min-Plus Semiring",
            description="Construct a dependent type theory where types are tropical sets and terms are min-plus functions, proving that type checking in tropical type theory is decidable and that the tropical identity type corresponds to min-plus equality. Show that tropical inductive types satisfy tropical initial algebra semantics, and that the tropical universe hierarchy is well-founded by the idempotent ordering.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Logic", "Algebra", "Tropical"],
            priority_score=0.86,
        ),
        FutureDirection(
            id="seed_059",
            title="Homotopy Type Theory via Tropical Higher Inductive Types",
            description="Prove that higher inductive types in homotopy type theory have tropical shadows where the path type becomes min-plus equidistance, and that the tropical univalence axiom is a decidable min-plus identity. Show that tropical HoTT captures the combinatorial skeleton of homotopy types while eliminating the topological complexity, yielding a computational interpretation of univalence.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Logic", "Algebra", "Bridges"],
            priority_score=0.84,
        ),
        FutureDirection(
            id="seed_060",
            title="Holographic Proof Renormalization: Ultrametric Compression of Formal Derivations",
            description="Develop an ultrametric theory of proof compression where the p-adic valuation of a derivation measures its local complexity, and prove that renormalization group flow on proof spaces converges to fixed points representing minimal proofs. Show that the tropical ultrametric distance between two proofs bounds their semantic distance, and that holographic renormalization yields a decidable approximation to theoremhood.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Logic", "Physics"],
            priority_score=0.93,
        ),

        # ── Pythagorean / Number Theory ──
        FutureDirection(
            id="seed_061",
            title="Emergent Computation in Pythagorean Orbit Lattices",
            description="Prove that the Berggren groupoid orbit lattice on SL(3,Z) supports universal computation via a constructed cellular automaton, establishing Pythagorean triples as a computational substrate. Show that the orbit structure of primitive triples encodes Turing-complete transition rules, and that the lattice's geometric properties guarantee computational universality with polynomial overhead.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Pythagorean", "Computation", "Speculative"],
            priority_score=0.90,
        ),
        FutureDirection(
            id="seed_062",
            title="Tropical Knot Theory: Min-Plus Invariants for Knot Classification",
            description="Construct tropical knot invariants by evaluating classical knot polynomials (Jones, Alexander) in the min-plus semiring, and prove that tropical Jones polynomials distinguish knots that classical Jones cannot. Show that the tropical skein relation yields a canonical simplification of knot diagrams, and that the tropical crossing number is a sharp lower bound on the classical crossing number.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Tropical", "Bridges"],
            priority_score=0.81,
        ),
        FutureDirection(
            id="seed_063",
            title="Fermat's Last Theorem as Tropical Diophantine Constraint",
            description="Prove that Fermat's Last Theorem admits a tropical formulation: the tropical Fermat equation x^n +_trop y^n = z^n has no primitive solutions in the min-plus semiring for n >= 3. Show that the tropical Fermat curve is a tropical hyperplane arrangement whose empty intersection with the tropical integer lattice proves the tropical case, and construct a transfer principle that recovers the classical result.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Pythagorean", "Algebra", "Tropical"],
            priority_score=0.87,
        ),
        FutureDirection(
            id="seed_064",
            title="Pythagorean Prime Distribution via Tropical Zeta Functions",
            description="Construct a tropical zeta function for the Berggren tree of Pythagorean triples and prove that its zeros encode the distribution of primes along hypotenuse lengths. Show that the tropical Euler product over primitive triples converges on the critical strip, and that the Berggren zeta function satisfies a functional equation connecting the tropical distributions of legs and hypotenuses.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Pythagorean", "Algebra", "Tropical"],
            priority_score=0.85,
        ),

        # ── Neural Network Theory ──
        FutureDirection(
            id="seed_065",
            title="Neural Tangent Kernel in the Tropical Limit",
            description="Prove that the neural tangent kernel of an infinitely wide network converges to a tropical kernel in the min-plus limit, and that training dynamics in the tropical NTK regime are governed by tropical gradient flow on a polyhedral loss surface. Show that the tropical NTK is constant along tropical flat directions, yielding a precise characterization of feature learning vs. lazy training.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "Algebra"],
            priority_score=0.83,
        ),
        FutureDirection(
            id="seed_066",
            title="Tropical Neural Code Classification with Provable Margins",
            description="Prove that tropical convex hulls of neural firing patterns classify stimulus identities with provable margin bounds, establishing tropical geometry as a formal framework for neural coding theory. Show that the tropical convex hull of a neural code's receptive fields determines its combinatorial classification capacity.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["MachineLearning", "Tropical", "Bridges"],
            priority_score=0.84,
        ),

        # ── Meta-Research: Improving Aether & Aristotle ──
        FutureDirection(
            id="seed_067",
            title="Aether Self-Improvement: Certified Novelty Detection via Theorem Embedding Uniqueness",
            description="Design and prove correct a novelty certification system for Aether that formally verifies each research output contains genuinely new mathematics, not trivial rephrasings of known results. Construct a theorem embedding space where each known result occupies a unique region, and prove that the embedding distance between a proposed result and the nearest known result bounds the novelty gap. Show that this certification can be automated as a Lean 4 tactic that rejects derivative work and flags genuinely novel contributions.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "Algebra"],
            priority_score=0.97,
        ),
        FutureDirection(
            id="seed_068",
            title="Aristotle Quality Amplification: Proof Strategy Mining from Millennial-Grade Mathematics",
            description="Reverse-engineer the proof strategies of the deepest results in mathematics (Fermat's Last Theorem, Poincaré conjecture, the classification of finite simple groups) and construct a Lean 4 formalization that extracts their reusable structural patterns. Prove that these strategies compose into higher-order proof schemata that generalize across domains, and show that Aristotle can be bootstrapped with these schemata to produce master-class research rather than shallow variations.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "Bridges"],
            priority_score=0.98,
        ),
        FutureDirection(
            id="seed_069",
            title="Research Depth Guarantees via Proof-Theoretic Ordinal Analysis",
            description="Prove that proof-theoretic ordinal analysis provides a rigorous depth metric for mathematical research, and construct a Lean 4 formalization that computes the proof-theoretic ordinal of each Aether output. Show that results exceeding a threshold ordinal depth are guaranteed to be non-trivial, and prove that the ordinal depth of a research cycle bounds the conceptual innovation of its output. Establish that cycles with depth below the threshold can be automatically rejected or escalated for deeper investigation.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "Computation"],
            priority_score=0.96,
        ),
        FutureDirection(
            id="seed_070",
            title="Aristotle Prompt Engineering: Category-Theoretic Prompt Optimization via Adjunction",
            description="Prove that the space of research prompts forms a category where prompt quality is measured by the adjunction between the prompt functor and the output quality functor. Construct a universal property that characterizes optimal prompts as those that are left-adjoint to the evaluation functor, and show that this adjunction can be computed via a Galois connection between prompt features and output quality metrics. Formalize this in Lean 4 and prove that iteratively applying the adjunction converges to a fixed-point prompt that maximizes research depth.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Algebra", "MachineLearning"],
            priority_score=0.95,
        ),
        FutureDirection(
            id="seed_071",
            title="Research Package Quality via Certified Mathematical Significance Metrics",
            description="Define and formalize a mathematical significance metric that goes beyond correctness to measure the depth, novelty, and impact of a research result. Prove that the significance metric is a monotone function on the lattice of mathematical knowledge, and that results exceeding a significance threshold are guaranteed to advance the field. Show that this metric can be computed from the Lean 4 proof term structure alone, enabling fully automated quality gates that reject shallow work and elevate master-class contributions.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "EML"],
            priority_score=0.97,
        ),
        FutureDirection(
            id="seed_072",
            title="Aether Evolution: Self-Modifying Research Strategies via Reflective Type Theory",
            description="Prove that a research system can be formalized as a dependent type where the type of the next research cycle depends on the outcomes of previous cycles. Construct a reflective type theory where the system's own research strategy is a first-class citizen that can be analyzed, improved, and verified. Show that this reflective architecture enables Aether to prove theorems about its own proof strategies, identify systematic weaknesses, and self-correct toward higher-quality output. Formalize the metatheorem that reflective self-improvement converges.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "Algebra"],
            priority_score=0.99,
        ),
        FutureDirection(
            id="seed_073",
            title="From Shallow to Deep: Formalizing the Depth Gap in Automated Mathematics",
            description="Prove that there exists a formal depth gap between trivial rephrasings of known results and genuinely new mathematics, and construct a Lean 4 formalization that computes this gap. Show that the depth gap is characterized by the minimum number of conceptual leaps (definition introductions, type changes, perspective shifts) required to connect the new result to the nearest known result. Prove that Aether outputs below a depth threshold are provably derivative, and establish that the depth gap is computable from proof terms.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "Computation"],
            priority_score=0.96,
        ),
        FutureDirection(
            id="seed_074",
            title="Aristotle Architecture: Compositional Research via Mathematical Theory Morphisms",
            description="Prove that mathematical theories form a category where theory morphisms preserve structure and enable compositional research. Construct a Lean 4 formalization of theory morphisms that allows Aristotle to compose results across domains by applying structure-preserving maps. Show that master-class research emerges from composing deep theory morphisms that no single domain could produce alone, and prove that the compositionality law guarantees that composed results are at least as deep as their components.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Algebra", "Bridges"],
            priority_score=0.95,
        ),
        FutureDirection(
            id="seed_075",
            title="Aether Quality Control: Automated Counterexample Generation as Research Stress Testing",
            description="Prove that automated counterexample generation is a sound method for stress-testing mathematical conjectures before they are promoted to theorems. Construct a Lean 4 tactic that, given a proposed result, generates maximally-difficult counterexample candidates in the negation of the result's type, and proves that a conjecture that survives this stress test has a provably lower false-positive rate. Show that integrating this into Aether's research pipeline eliminates shallow or false conjectures before resources are spent on proof attempts.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "Computation"],
            priority_score=0.94,
        ),
        FutureDirection(
            id="seed_076",
            title="Master-Class Research via Conceptual Dependency Graphs and Critical Path Analysis",
            description="Prove that the conceptual dependency graph of a mathematical theory has a critical path whose length bounds the minimum conceptual depth required to discover any result in that theory. Construct a Lean 4 formalization that extracts conceptual dependency graphs from proof terms, computes the critical path, and proves that results discovered by traversing the critical path are deeper than those discovered by shallow exploration. Show that Aether can use critical path analysis to guide research toward master-class results that require conceptual breakthroughs rather than incremental variations.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Algebra", "Computation"],
            priority_score=0.98,
        ),
        FutureDirection(
            id="seed_077",
            title="Aristotle Bootstrapping: Learning to Prove Harder Theorems from Easy Ones via Curricula",
            description="Prove that a mathematical curriculum — an ordered sequence of theorems of increasing difficulty — can be formally constructed such that each theorem's proof only requires techniques learned from the preceding theorems. Show that such curricula exist for any mathematical theory of sufficient depth, and that the curriculum length bounds the minimum number of research cycles needed to reach the theory's frontier. Formalize curriculum construction in Lean 4 and prove that Aristotle bootstrapped with a curriculum produces progressively deeper results, converging to master-class quality.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Meta", "Logic", "MachineLearning"],
            priority_score=0.97,
        ),

        # ── Galaxy-Scale & Sci-Fi ──
        FutureDirection(
            id="seed_078",
            title="Galaxy-Scale Computation: Tropical Distributed Systems Across Light-Years",
            description="Prove that distributed computation across galactic distances with lightspeed latency is optimally modeled as a tropical network flow where min-plus propagation delay replaces classical synchronization. Show that the tropical diameter of the galaxy-scale network determines the optimal parallel speedup, and that idempotent message aggregation eliminates the need for consensus protocols.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Speculative", "Computation", "Tropical"],
            priority_score=0.74,
        ),
        FutureDirection(
            id="seed_079",
            title="Tropical Language Evolution: Min-Plus Phylogenetics and Glottochronology",
            description="Prove that language divergence follows a tropical diffusion process on the min-plus metric space of lexical items, and that the tropical distance between languages is an optimal phylogenetic distance. Show that glottochronological dating is recovered as tropical distance estimation, and that the tropical phylogenetic tree is the unique min-plus Steiner tree of the language family.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Bridges", "Tropical", "Computation"],
            priority_score=0.73,
        ),
        FutureDirection(
            id="seed_080",
            title="Emergent Math: Self-Organizing Theorem Discovery in Idempotent Algebras",
            description="Prove that idempotent algebras exhibit self-organizing theorem discovery: given a set of axioms, the idempotent closure automatically generates a lattice of consequences that converges to a fixed-point theory. Show that this fixed-point theory contains all theorems provable from the axioms, and that the tropical spectral radius of the closure operator bounds the depth of the deepest discoverable theorem. Construct a Lean 4 formalization that demonstrates emergent theorem discovery in the min-plus semiring.",
            source_exp_id="seed",
            source_path="seed:manual_v3",
            domains=["Algebra", "Logic", "Tropical"],
            priority_score=0.80,
        ),
    ]
    return directions