import Pythagorean.CayleyHamiltonian.Basic
import Pythagorean.CayleyHamiltonian.Enumeration

/-!
# The index-two "alternating word" criterion

Suppose the connection set of a Cayley graph on `G` contains two elements `x, y` such that
`c := x * y` has order `n`, `|G| = 2n`, and `x ∉ ⟨c⟩`.  Then `G` is the disjoint union of the
two cosets `⟨c⟩` and `⟨c⟩x`, and the alternating word

`1, x, xy, xyx, (xy)², (xy)²x, …`

visits every vertex exactly once and closes up because `c ^ n = 1`.  This handles precisely the
situation in which *neither* generator lies in the large cyclic subgroup, so that the torus and
generalized-dihedral constructions do not apply.

Main results:

* `CayleyHamiltonian.isHamiltonian_of_index_two_pair` : the general criterion.
* `CayleyHamiltonian.isHamiltonian_of_two_involutions` : the special case of two involutions
  generating `G`, where the hypothesis `x ∉ ⟨xy⟩` is automatic.
-/

namespace CayleyHamiltonian

open SimpleGraph

variable {G : Type*} [Group G] [Fintype G] [DecidableEq G] {S : Set G}

/-- The alternating enumeration `1, x, xy, xyx, (xy)², …`. -/
def cosetEnum (x y : G) (i : ℕ) : G := (x * y) ^ (i / 2) * (if i % 2 = 1 then x else 1)

omit [Fintype G] [DecidableEq G] in
private lemma cosetEnum_eq (x y : G) (i : ℕ) :
    cosetEnum x y i = (x * y) ^ (i / 2) * (if i % 2 = 1 then x else 1) := rfl

/-- **Index-two alternating criterion.**  If the connection set contains `x` and `y` with
`orderOf (x * y) = n ≥ 2`, `|G| = 2n`, and `x` outside the cyclic subgroup generated by
`x * y`, then the Cayley graph is hamiltonian. -/
theorem isHamiltonian_of_index_two_pair {x y : G} {n : ℕ} (hx : x ∈ S) (hy : y ∈ S)
    (hn : 2 ≤ n) (hord : orderOf (x * y) = n) (hcard : Fintype.card G = 2 * n)
    (hxnot : x ∉ Subgroup.zpowers (x * y)) :
    (cayleyGraph G S).IsHamiltonian := by
  have hcn : (x * y) ^ n = 1 := by rw [← hord]; exact pow_orderOf_eq_one _
  have hx1 : x ≠ 1 := fun h => hxnot (h ▸ one_mem _)
  have hy1 : y ≠ 1 := by
    intro h
    exact hxnot (by rw [h, mul_one]; exact Subgroup.mem_zpowers x)
  -- injectivity ingredients
  have hkey : ∀ t t' : ℕ, t < n → t' < n → (x * y) ^ t = (x * y) ^ t' → t = t' := by
    intro t t' ht ht' h
    have hmod := (pow_eq_pow_iff_modEq (x := x * y)).1 h
    rw [hord, Nat.ModEq, Nat.mod_eq_of_lt ht, Nat.mod_eq_of_lt ht'] at hmod
    exact hmod
  have hmixed : ∀ t t' : ℕ, (x * y) ^ t ≠ (x * y) ^ t' * x := by
    intro t t' h
    refine hxnot ?_
    have hxeq : x = ((x * y) ^ t')⁻¹ * (x * y) ^ t := by rw [h, inv_mul_cancel_left]
    have hmem : ((x * y) ^ t')⁻¹ * (x * y) ^ t ∈ Subgroup.zpowers (x * y) :=
      Subgroup.mul_mem _
        (Subgroup.inv_mem _ (Subgroup.pow_mem _ (Subgroup.mem_zpowers _) t'))
        (Subgroup.pow_mem _ (Subgroup.mem_zpowers _) t)
    rwa [← hxeq] at hmem
  refine isHamiltonian_of_enum (n := 2 * n) (by omega) (by rw [hcard]) (cosetEnum x y) ?_ ?_ ?_
  · -- consecutive vertices are adjacent
    intro i
    rw [cosetEnum_eq, cosetEnum_eq]
    rcases Nat.even_or_odd i with hpar | hpar
    · obtain ⟨t, ht⟩ := hpar
      have h1 : i % 2 = 0 := by omega
      have h2 : (i + 1) % 2 = 1 := by omega
      have h3 : (i + 1) / 2 = i / 2 := by omega
      rw [h1, h2, h3, if_neg (by omega), if_pos rfl, mul_one]
      exact adj_mul_of_mem hx hx1
    · obtain ⟨t, ht⟩ := hpar
      have h1 : i % 2 = 1 := by omega
      have h2 : (i + 1) % 2 = 0 := by omega
      have h3 : (i + 1) / 2 = i / 2 + 1 := by omega
      rw [h1, h2, h3, if_pos rfl, if_neg (by omega), mul_one]
      have hstep : (x * y) ^ (i / 2 + 1) = (x * y) ^ (i / 2) * x * y := by
        rw [pow_succ, mul_assoc]
      rw [hstep]
      exact adj_mul_of_mem hy hy1
  · -- injectivity on one period
    intro i i' hi hi' hEq
    rw [cosetEnum_eq, cosetEnum_eq] at hEq
    have hd : i / 2 < n := by omega
    have hd' : i' / 2 < n := by omega
    have hhalf : i / 2 = i' / 2 ∧ i % 2 = i' % 2 := by
      rcases Nat.even_or_odd i with hpar | hpar <;> rcases Nat.even_or_odd i' with hpar' | hpar'
      · obtain ⟨t, ht⟩ := hpar
        obtain ⟨t', ht'⟩ := hpar'
        rw [if_neg (by omega), if_neg (by omega), mul_one, mul_one] at hEq
        exact ⟨hkey _ _ hd hd' hEq, by omega⟩
      · obtain ⟨t, ht⟩ := hpar
        obtain ⟨t', ht'⟩ := hpar'
        rw [if_neg (by omega), if_pos (by omega), mul_one] at hEq
        exact absurd hEq (hmixed _ _)
      · obtain ⟨t, ht⟩ := hpar
        obtain ⟨t', ht'⟩ := hpar'
        rw [if_pos (by omega), if_neg (by omega), mul_one] at hEq
        exact absurd hEq.symm (hmixed _ _)
      · obtain ⟨t, ht⟩ := hpar
        obtain ⟨t', ht'⟩ := hpar'
        rw [if_pos (by omega), if_pos (by omega)] at hEq
        exact ⟨hkey _ _ hd hd' (mul_right_cancel hEq), by omega⟩
    omega
  · -- periodicity
    intro i
    rw [cosetEnum_eq, cosetEnum_eq, show (i + 2 * n) / 2 = i / 2 + n by omega,
      show (i + 2 * n) % 2 = i % 2 by omega, pow_add, hcn, mul_one]

/-- **Two-involution criterion.**  If the connection set contains two involutions `x, y` which
generate `G`, and `|G| = 2 · orderOf (x * y)`, then the Cayley graph is hamiltonian.  Here the
hypothesis `x ∉ ⟨xy⟩` of `isHamiltonian_of_index_two_pair` is automatic. -/
theorem isHamiltonian_of_two_involutions {x y : G} {n : ℕ} (hx : x ∈ S) (hy : y ∈ S)
    (hx2 : x * x = 1) (hn : 2 ≤ n) (hord : orderOf (x * y) = n)
    (hcard : Fintype.card G = 2 * n)
    (hgen : Subgroup.closure ({x, y} : Set G) = ⊤) :
    (cayleyGraph G S).IsHamiltonian := by
  refine isHamiltonian_of_index_two_pair hx hy hn hord hcard ?_
  have hZ : Nat.card (Subgroup.zpowers (x * y)) = n := by rw [Nat.card_zpowers, hord]
  intro hxin
  have hyin : y ∈ Subgroup.zpowers (x * y) := by
    have hmem : x * (x * y) ∈ Subgroup.zpowers (x * y) :=
      Subgroup.mul_mem _ hxin (Subgroup.mem_zpowers _)
    rwa [← mul_assoc, hx2, one_mul] at hmem
  have hEq : Subgroup.zpowers (x * y) = ⊤ := by
    refine eq_top_iff.2 ?_
    rw [← hgen]
    exact (Subgroup.closure_le _).2 (Set.pair_subset hxin hyin)
  rw [hEq] at hZ
  have hcong : Nat.card (⊤ : Subgroup G) = Nat.card G :=
    Nat.card_congr (Subgroup.topEquiv).toEquiv
  rw [hcong, Nat.card_eq_fintype_card, hcard] at hZ
  omega

end CayleyHamiltonian