import Mathlib

/-!
# Denominators of rational points on Mordell curves `E_N : y² = x³ + N`

This file develops the *denominator theory* of rational points on the Mordell
curve `E_N : y² = x³ + N` (`N : ℤ`), the arithmetic object behind the folklore
conjecture that denominators of multiples of a rational point only involve the
primes of bad reduction `{2, 3} ∪ {p : p ∣ N}`.

Main results.

* `MordellDenominators.den_sq_eq_den_cube` : for any rational point,
  `y.den ^ 2 = x.den ^ 3`.
* `MordellDenominators.exists_den_param` : consequently there is `e ≥ 1` with
  `x.den = e ^ 2` and `y.den = e ^ 3` (the classical `(e², e³)` shape).
* `MordellDenominators.prime_dvd_x_den_iff_dvd_y_den`, `sq_dvd_x_den`,
  `cube_dvd_y_den` : a prime dividing one denominator divides both, to order
  `≥ 2` resp. `≥ 3`; i.e. the point lies in the kernel of reduction there.
* `MordellDenominators.dbl_onCurve` : the duplication formula lands on the
  curve again.
* `MordellDenominators.dvd_den_dblX_of_dvd_den` : the kernel of reduction at
  any prime `ℓ` is stable under duplication — once a prime enters a
  denominator it stays for the whole doubling orbit.

Everything is elementary (no `EllipticCurve` API is needed) and explicit, so
that the counterexamples in `Counterexample.lean` and the infinite family in
`Family.lean` can be checked against these general theorems.
-/

namespace MordellDenominators

/-! ## Basic definitions -/

/-- The affine Mordell curve `E_N : y² = x³ + N` over `ℚ`. -/
def OnCurve (N : ℤ) (x y : ℚ) : Prop := y ^ 2 = x ^ 3 + (N : ℚ)

/-- Discriminant of `E_N`, namely `Δ = -432 N²`.  Its prime divisors are
`{2, 3} ∪ {p : p ∣ N}`; these are the "bad primes" of the conjecture. -/
def disc (N : ℤ) : ℤ := -432 * N ^ 2

/-- A prime is *bad* for `E_N` when it divides `6N` (equivalently, when it
divides the discriminant `-432 N²`). -/
def BadPrime (N : ℤ) (l : ℕ) : Prop := l.Prime ∧ (l : ℤ) ∣ 6 * N

/-- A prime is *good* for `E_N` when it does not divide `6N`. -/
def GoodPrime (N : ℤ) (l : ℕ) : Prop := l.Prime ∧ ¬ ((l : ℤ) ∣ 6 * N)

/-- `x`-coordinate of `2P` given `x = x(P)`, from the duplication formula
`x(2P) = (x⁴ - 8Nx) / (4(x³ + N))`. -/
def dblX (N : ℤ) (x : ℚ) : ℚ := (x ^ 4 - 8 * (N : ℚ) * x) / (4 * (x ^ 3 + (N : ℚ)))

/-- `y`-coordinate of `2P`, `y(2P) = λ (x - x(2P)) - y` with `λ = 3x²/(2y)`. -/
def dblY (N : ℤ) (x y : ℚ) : ℚ := (3 * x ^ 2 / (2 * y)) * (x - dblX N x) - y

/-- Duplication as a map on affine points. -/
def dbl (N : ℤ) (P : ℚ × ℚ) : ℚ × ℚ := (dblX N P.1, dblY N P.1 P.2)

/-- `2^n P`, obtained by iterating duplication. -/
def dblIter (N : ℤ) (n : ℕ) (P : ℚ × ℚ) : ℚ × ℚ := (dbl N)^[n] P

/-- The *only-bad-primes* conjecture for the doubling orbit of `P` on `E_N`:
every prime occurring in the denominator of an `x`-coordinate of `2^n P`
divides `6N`, i.e. is a prime of bad reduction.

The points `2^n P` are among the multiples `nP`, so refuting this statement
refutes the conjecture as usually stated (over all multiples of `P`); the
doubling orbit is used because it is generated by the single explicit
duplication formula. -/
def OnlyBadPrimes (N : ℤ) (P : ℚ × ℚ) : Prop :=
  ∀ n : ℕ, ∀ l : ℕ, l.Prime → l ∣ (dblIter N n P).1.den → (l : ℤ) ∣ 6 * N

/-! ## A divisibility criterion for denominators -/

/-- The cross-multiplication identity for a rational written as `A / B`. -/
theorem num_mul_den_eq {q : ℚ} {A B : ℤ} (hB : B ≠ 0)
    (hq : q = (A : ℚ) / (B : ℚ)) : q.num * B = A * (q.den : ℤ) := by
  have hB' : (B : ℚ) ≠ 0 := Int.cast_ne_zero.mpr hB
  have hd : ((q.den : ℚ)) ≠ 0 := by
    exact_mod_cast q.den_nz
  have key : (q.num : ℚ) * (B : ℚ) = (A : ℚ) * (q.den : ℚ) := by
    have h1 : (q.num : ℚ) = q * (q.den : ℚ) := (Rat.mul_den_eq_num q).symm
    rw [h1, hq]
    field_simp
  exact_mod_cast key

/-- If `q = A / B` with a prime `ℓ` dividing `B` but not `A`, then `ℓ` divides
the reduced denominator of `q`. -/
theorem prime_dvd_den_of_eq_div {q : ℚ} {A B : ℤ} (hB : B ≠ 0)
    (hq : q = (A : ℚ) / (B : ℚ)) {l : ℕ} (hl : l.Prime)
    (hlB : (l : ℤ) ∣ B) (hlA : ¬ (l : ℤ) ∣ A) : l ∣ q.den := by
  have keyZ : q.num * B = A * (q.den : ℤ) := num_mul_den_eq hB hq
  have hdvd : (l : ℤ) ∣ A * (q.den : ℤ) := by
    rw [← keyZ]; exact Dvd.dvd.mul_left hlB _
  have hlp : Prime (l : ℤ) := Nat.prime_iff_prime_int.mp hl
  rcases hlp.dvd_mul.mp hdvd with h | h
  · exact absurd h hlA
  · exact_mod_cast h

/-! ## The `(e², e³)` shape of denominators -/

/-- For a rational point on `y² = x³ + N` with `N` an integer, the denominators
satisfy `den(y)² = den(x)³`. -/
theorem den_sq_eq_den_cube {N : ℤ} {x y : ℚ} (h : OnCurve N x y) :
    y.den ^ 2 = x.den ^ 3 := by
  have h1 : (y ^ 2).den = (x ^ 3 + (N : ℚ)).den := by rw [h]
  rwa [Rat.den_pow, Rat.add_intCast_den, Rat.den_pow] at h1

/-- The classical shape of denominators on a Mordell curve: there is a positive
integer `e` with `x.den = e²` and `y.den = e³`. -/
theorem exists_den_param {N : ℤ} {x y : ℚ} (h : OnCurve N x y) :
    ∃ e : ℕ, 0 < e ∧ x.den = e ^ 2 ∧ y.den = e ^ 3 := by
  have hkey := den_sq_eq_den_cube h
  have hx0 : 0 < x.den := x.pos
  have hdvd2 : x.den ^ 2 ∣ y.den ^ 2 := by
    rw [hkey]; exact pow_dvd_pow _ (by norm_num)
  have hdvd : x.den ∣ y.den := (Nat.pow_dvd_pow_iff (two_ne_zero)).mp hdvd2
  obtain ⟨e, he⟩ := hdvd
  have hcancel : x.den ^ 2 * e ^ 2 = x.den ^ 2 * x.den :=
    calc x.den ^ 2 * e ^ 2 = (x.den * e) ^ 2 := by ring
      _ = y.den ^ 2 := by rw [he]
      _ = x.den ^ 3 := hkey
      _ = x.den ^ 2 * x.den := by ring
  have hxe : x.den = e ^ 2 := (Nat.eq_of_mul_eq_mul_left (by positivity) hcancel).symm
  have he0 : 0 < e := by
    rcases Nat.eq_zero_or_pos e with rfl | h' 
    · simp [hxe] at hx0
    · exact h'
  exact ⟨e, he0, hxe, by rw [he, hxe]; ring⟩

/-- A prime divides `x.den` iff it divides `y.den`. -/
theorem prime_dvd_x_den_iff_dvd_y_den {N : ℤ} {x y : ℚ} (h : OnCurve N x y)
    {l : ℕ} (hl : l.Prime) : l ∣ x.den ↔ l ∣ y.den := by
  obtain ⟨e, _, hx, hy⟩ := exists_den_param h
  constructor
  · intro hd
    rw [hx] at hd
    rw [hy]
    exact Dvd.dvd.trans (hl.dvd_of_dvd_pow hd) (dvd_pow_self e (by norm_num))
  · intro hd
    rw [hy] at hd
    rw [hx]
    exact Dvd.dvd.trans (hl.dvd_of_dvd_pow hd) (dvd_pow_self e (by norm_num))

/-- A prime in a denominator occurs to order at least `2` in `x.den`. -/
theorem sq_dvd_x_den {N : ℤ} {x y : ℚ} (h : OnCurve N x y) {l : ℕ}
    (hl : l.Prime) (hd : l ∣ x.den) : l ^ 2 ∣ x.den := by
  obtain ⟨e, _, hx, _⟩ := exists_den_param h
  rw [hx] at hd ⊢
  exact pow_dvd_pow_of_dvd (hl.dvd_of_dvd_pow hd) 2

/-- A prime in a denominator occurs to order at least `3` in `y.den`. -/
theorem cube_dvd_y_den {N : ℤ} {x y : ℚ} (h : OnCurve N x y) {l : ℕ}
    (hl : l.Prime) (hd : l ∣ x.den) : l ^ 3 ∣ y.den := by
  obtain ⟨e, _, hx, hy⟩ := exists_den_param h
  rw [hx] at hd
  rw [hy]
  exact pow_dvd_pow_of_dvd (hl.dvd_of_dvd_pow hd) 3

/-- **Integral model.**  Writing `x = a/e²` and `y = b/e³` (with `a = x.num`,
`b = y.num`), the curve equation becomes the integral identity
`b² = a³ + N e⁶`. -/
theorem curve_integral_model {N : ℤ} {x y : ℚ} (h : OnCurve N x y) {e : ℕ}
    (hxe : x.den = e ^ 2) (hye : y.den = e ^ 3) :
    y.num ^ 2 = x.num ^ 3 + N * (e : ℤ) ^ 6 := by
  have he0 : 0 < e := by
    rcases Nat.eq_zero_or_pos e with rfl | h'
    · exfalso; simp at hxe
    · exact h'
  have hex : (e : ℚ) ≠ 0 := by exact_mod_cast he0.ne'
  have hx : x * (e : ℚ) ^ 2 = (x.num : ℚ) := by
    conv_lhs => rw [← Rat.num_div_den x, hxe]
    push_cast
    field_simp
  have hy : y * (e : ℚ) ^ 3 = (y.num : ℚ) := by
    conv_lhs => rw [← Rat.num_div_den y, hye]
    push_cast
    field_simp
  have hcurve : y ^ 2 = x ^ 3 + (N : ℚ) := h
  have : ((y.num ^ 2 : ℤ) : ℚ) = ((x.num ^ 3 + N * (e : ℤ) ^ 6 : ℤ) : ℚ) := by
    push_cast
    rw [← hx, ← hy]
    calc (y * (e : ℚ) ^ 3) ^ 2 = y ^ 2 * (e : ℚ) ^ 6 := by ring
      _ = (x ^ 3 + (N : ℚ)) * (e : ℚ) ^ 6 := by rw [hcurve]
      _ = (x * (e : ℚ) ^ 2) ^ 3 + (N : ℚ) * (e : ℚ) ^ 6 := by ring
  exact_mod_cast this

/-! ## The duplication formula -/

/-- Duplication sends a rational point with `y ≠ 0` to a rational point. -/
theorem dbl_onCurve {N : ℤ} {x y : ℚ} (h : OnCurve N x y) (hy : y ≠ 0) :
    OnCurve N (dblX N x) (dblY N x y) := by
  have hN : (N : ℚ) = y ^ 2 - x ^ 3 := by
    have := h; unfold OnCurve at this; linarith
  unfold OnCurve dblY dblX
  rw [hN]
  have h4 : (4 : ℚ) * (x ^ 3 + (y ^ 2 - x ^ 3)) ≠ 0 := by
    have h2 : y ^ 2 ≠ 0 := pow_ne_zero _ hy
    intro hc; apply h2; nlinarith [hc]
  field_simp
  ring

/-! ## Stability of the kernel of reduction under duplication -/

/-- **Explicit integral fraction for the duplicated `x`-coordinate.**  With
`x = a/e²` and `y = b/e³` one has
`x(2P) = (a⁴ - 8N a e⁶) / (4 b² e²)`, a quotient of integers (not necessarily in
lowest terms). -/
theorem dblX_eq_div {N : ℤ} {x y : ℚ} (h : OnCurve N x y) {e : ℕ} (he0 : 0 < e)
    (hxe : x.den = e ^ 2) (hye : y.den = e ^ 3) (hy : y ≠ 0) :
    dblX N x = ((x.num ^ 4 - 8 * N * x.num * (e : ℤ) ^ 6 : ℤ) : ℚ) /
      (((4 * y.num ^ 2 * (e : ℤ) ^ 2 : ℤ)) : ℚ) := by
  set a : ℤ := x.num with ha
  set b : ℤ := y.num with hb
  have hex : (e : ℚ) ≠ 0 := by exact_mod_cast he0.ne'
  have hxeq : x = (a : ℚ) / ((e : ℚ) ^ 2) := by
    have h2 : ((e : ℚ) ^ 2) = (x.den : ℚ) := by rw [hxe]; push_cast; ring
    rw [h2, ha, Rat.num_div_den]
  have hyeq : y = (b : ℚ) / ((e : ℚ) ^ 3) := by
    have h3 : ((e : ℚ) ^ 3) = (y.den : ℚ) := by rw [hye]; push_cast; ring
    rw [h3, hb, Rat.num_div_den]
  have hx3 : x ^ 3 + (N : ℚ) = y ^ 2 := h.symm
  have hb0 : b ≠ 0 := by
    intro h0
    exact hy (by rw [hyeq, h0]; simp)
  have hbq : (b : ℚ) ≠ 0 := Int.cast_ne_zero.mpr hb0
  have hnum : x ^ 4 - 8 * (N : ℚ) * x =
      ((a ^ 4 - 8 * N * a * (e : ℤ) ^ 6 : ℤ) : ℚ) / ((e : ℚ) ^ 8) := by
    rw [hxeq]; push_cast; field_simp
  have hden : 4 * (x ^ 3 + (N : ℚ)) = ((4 * b ^ 2 : ℤ) : ℚ) / ((e : ℚ) ^ 6) := by
    rw [hx3, hyeq]; push_cast; field_simp
  unfold dblX
  rw [hnum, hden]
  push_cast
  field_simp

/-- If a prime divides `x.den` then the `y`-coordinate cannot vanish. -/
theorem ne_zero_of_dvd_den {N : ℤ} {x y : ℚ} (h : OnCurve N x y) {l : ℕ}
    (hl : l.Prime) (hd : l ∣ x.den) : y ≠ 0 := by
  obtain ⟨e, he0, hxe, hye⟩ := exists_den_param h
  intro hy0
  have hy1 : y.den = 1 := by rw [hy0]; rfl
  rw [hye] at hy1
  have he1 : e = 1 := by
    have := Nat.pow_eq_one.mp hy1
    tauto
  have hx1 : x.den = 1 := by rw [hxe, he1]; norm_num
  rw [hx1] at hd
  exact hl.one_lt.ne' (Nat.dvd_one.mp hd)

/-- **The kernel of reduction is stable under duplication.**  If a prime `ℓ`
divides the denominator of `x(P)` for a rational point `P` on `E_N`, then it
divides the denominator of `x(2P)` as well.  Hence a prime that appears once in
the orbit appears in every later doubling. -/
theorem dvd_den_dblX_of_dvd_den {N : ℤ} {x y : ℚ} (h : OnCurve N x y)
    {l : ℕ} (hl : l.Prime) (hd : l ∣ x.den) :
    l ∣ (dblX N x).den := by
  obtain ⟨e, he0, hxe, hye⟩ := exists_den_param h
  have hy : y ≠ 0 := ne_zero_of_dvd_den h hl hd
  have hb0 : y.num ≠ 0 := Rat.num_ne_zero.mpr hy
  have hle : (l : ℤ) ∣ (e : ℤ) := by
    have : l ∣ e := hl.dvd_of_dvd_pow (by rw [← hxe]; exact hd)
    exact_mod_cast this
  have hla : ¬ (l : ℤ) ∣ x.num := by
    intro hcon
    have h1 : l ∣ x.num.natAbs := by simpa using Int.natAbs_dvd_natAbs.mpr hcon
    have := Nat.Coprime.eq_one_of_dvd (Nat.Coprime.coprime_dvd_left h1 x.reduced) hd
    exact hl.one_lt.ne' this
  have heZ : (e : ℤ) ≠ 0 := by exact_mod_cast he0.ne'
  refine prime_dvd_den_of_eq_div (A := x.num ^ 4 - 8 * N * x.num * (e : ℤ) ^ 6)
    (B := 4 * y.num ^ 2 * (e : ℤ) ^ 2) (by positivity)
    (dblX_eq_div h he0 hxe hye hy) hl ?_ ?_
  · exact Dvd.dvd.mul_left (dvd_pow hle (by norm_num)) _
  · intro hcon
    have h6 : (l : ℤ) ∣ 8 * N * x.num * (e : ℤ) ^ 6 :=
      Dvd.dvd.mul_left (dvd_pow hle (by norm_num)) _
    have : (l : ℤ) ∣ x.num ^ 4 := by
      have := dvd_add hcon h6
      simpa using this
    exact hla ((Nat.prime_iff_prime_int.mp hl).dvd_of_dvd_pow this)

/-! ## Orbits under duplication -/

/-- The first step of the doubling orbit is the duplication formula. -/
theorem dblIter_one_fst (N : ℤ) (P : ℚ × ℚ) : (dblIter N 1 P).1 = dblX N P.1 := by
  simp [dblIter, dbl]

/-- If `x³ + N = 0` has no integral solution then `E_N` has no rational point
of order two, so duplication never leaves the affine part of the curve. -/
theorem no_two_torsion (N : ℤ) (hN : ∀ m : ℤ, m ^ 3 + N ≠ 0) {x y : ℚ}
    (h : OnCurve N x y) : y ≠ 0 := by
  intro hy0
  obtain ⟨e, he0, hxe, hye⟩ := exists_den_param h
  have hy1 : y.den = 1 := by rw [hy0]; rfl
  rw [hye] at hy1
  have he1 : e = 1 := by
    have := Nat.pow_eq_one.mp hy1
    tauto
  have hx1 : x.den = 1 := by rw [hxe, he1]; norm_num
  have hxnum : (x.num : ℚ) = x := by
    conv_rhs => rw [← Rat.num_div_den x]
    rw [hx1]
    simp
  have hzero : ((x.num ^ 3 + N : ℤ) : ℚ) = 0 := by
    have h' := h
    unfold OnCurve at h'
    rw [hy0] at h'
    push_cast
    rw [hxnum]
    linarith
  exact hN x.num (by exact_mod_cast hzero)

/-- Every point of the doubling orbit of a point on a curve without rational
2-torsion is again a point of the curve. -/
theorem dblIter_onCurve {N : ℤ} (hnt : ∀ x y : ℚ, OnCurve N x y → y ≠ 0)
    {P : ℚ × ℚ} (h : OnCurve N P.1 P.2) :
    ∀ n : ℕ, OnCurve N (dblIter N n P).1 (dblIter N n P).2 := by
  intro n
  induction n with
  | zero => simpa [dblIter] using h
  | succ k ih =>
      have : dblIter N (k + 1) P = dbl N (dblIter N k P) := by
        simp [dblIter, Function.iterate_succ_apply']
      rw [this]
      exact dbl_onCurve ih (hnt _ _ ih)

/-- **Persistence of denominator primes along the doubling orbit.**  A prime
dividing the denominator of `x(2^n P)` divides the denominator of `x(2^m P)`
for every `m ≥ n`. -/
theorem dvd_den_dblIter_of_dvd {N : ℤ} (hnt : ∀ x y : ℚ, OnCurve N x y → y ≠ 0)
    {P : ℚ × ℚ} (h : OnCurve N P.1 P.2) {l : ℕ} (hl : l.Prime) {n : ℕ}
    (hd : l ∣ (dblIter N n P).1.den) :
    ∀ m : ℕ, l ∣ (dblIter N (n + m) P).1.den := by
  intro m
  induction m with
  | zero => simpa using hd
  | succ k ih =>
      have hstep : dblIter N (n + k + 1) P = dbl N (dblIter N (n + k) P) := by
        simp [dblIter, Function.iterate_succ_apply']
      have : n + (k + 1) = n + k + 1 := by ring
      rw [this, hstep]
      exact dvd_den_dblX_of_dvd_den (dblIter_onCurve hnt h (n + k)) hl ih

end MordellDenominators