/-
Cyclotomic reciprocity: the arithmetic Frobenius of a cyclotomic ring is the
"catalog map" `ζ ↦ ζ ^ p`.

This file advances direction 4 of the Hilbert-class-field research thread
("Compatibility with cyclotomic reciprocity over `ℚ`") by proving, in full
generality and without any class field theory, that on a ring generated over
`ℤ` by a root of unity `ζ`, an endomorphism is an arithmetic Frobenius at a
prime `Q` above a rational prime `p` **iff** it sends `ζ` to `ζ ^ p`, and that
such an endomorphism is unique.
-/
import Mathlib

namespace Catalog.Pythagorean.CyclotomicFrobenius

open Algebra Polynomial

section Abstract

variable {A : Type*} [CommRing A]

/-- **Frobenius congruence on `ℤ[ζ]`.**  If `σ` is a ring endomorphism of a commutative
ring `A` with `σ ζ = ζ ^ p` for a prime `p`, then `σ x ≡ x ^ p (mod p)` for every `x`
in the subring generated by `ζ` over `ℤ`. -/
theorem sub_pow_mem_span_of_mem_adjoin {p : ℕ} (hp : p.Prime) {ζ : A} (σ : A →+* A)
    (hσ : σ ζ = ζ ^ p) {x : A} (hx : x ∈ Algebra.adjoin ℤ ({ζ} : Set A)) :
    σ x - x ^ p ∈ Ideal.span ({(p : A)} : Set A) := by
  have hFermat : ∀ n : ℤ, (n : A) - (n : A) ^ p ∈ Ideal.span ({(p : A)} : Set A) := by
    intro n
    have heq : (n : A) ^ p = ((n ^ p : ℤ) : A) := by rw [Int.cast_pow]
    rw [heq]
    have hdiv : (p : ℤ) ∣ ((n : ℤ) ^ p - n) := by
      haveI := Fact.mk hp
      rw [← ZMod.intCast_zmod_eq_zero_iff_dvd]
      simp only [Int.cast_sub, Int.cast_pow]
      rw [ZMod.pow_card, sub_self]
    rw [Ideal.mem_span_singleton]
    obtain ⟨k, hk⟩ := hdiv
    have hk' : (n : A) ^ p - (n : A) = (p : A) * k := by
      have h1 : (n : A) ^ p - (n : A) = ((n ^ p : ℤ) : A) - ((n : ℤ) : A) := by rw [heq]
      have h2 : ((n ^ p : ℤ) : A) - ((n : ℤ) : A) = ((n ^ p - n : ℤ) : A) := by rw [Int.cast_sub]
      have h3 : ((n ^ p - n : ℤ) : A) = (p : A) * k := by rw [hk, Int.cast_mul, Int.cast_natCast]
      exact h1.trans (h2.trans h3)
    exact ⟨-k, by rw [← heq]; linear_combination -hk'⟩
  induction hx using Algebra.adjoin_induction with
  | algebraMap n =>
    simp [hFermat]
  | mem a ha =>
    simp only [Set.mem_singleton_iff] at ha
    simp [ha, hσ]
  | add x y _ _ ih1 ih2 =>
    rw [Ideal.mem_span_singleton] at ih1 ih2 ⊢
    obtain ⟨u, hu⟩ := ih1
    obtain ⟨v, hv⟩ := ih2
    rw [add_comm, add_pow]
    use u + v - ∑ m ∈ Finset.Ico 1 p, y ^ m * x ^ (p - m) * ((p.choose m / p : ℕ) : A)
    simp only [map_add]
    rw [Finset.sum_range_succ]
    simp [Nat.choose_self]
    -- The sum ∑_{m<p} y^m x^{p-m} C(p,m) = x^p + ∑_{1≤m<p} y^m x^{p-m} * p * (C(p,m)/p)
    have hsum : ∑ m ∈ Finset.range p, y ^ m * x ^ (p - m) * ↑(p.choose m) =
        x ^ p + (p : A) * ∑ m ∈ Finset.Ico 1 p, y ^ m * x ^ (p - m) * ((p.choose m / p : ℕ) : A) := by
      have hp_pos : 0 < p := hp.pos
      -- Split off m=0 term: Finset.range p \ {0} = Finset.Ico 1 p
      have hsplit : ∑ m ∈ Finset.range p, y ^ m * x ^ (p - m) * ↑(p.choose m) =
          x ^ p + ∑ m ∈ Finset.Ico 1 p, y ^ m * x ^ (p - m) * ↑(p.choose m) := by
        have heq : Finset.range p \ {0} = Finset.Ico 1 p := by
          ext m
          simp [Finset.mem_Ico, Finset.mem_sdiff]
          omega
        rw [Finset.sum_eq_sum_diff_singleton_add (Finset.mem_range.mpr hp_pos)]
        simp [Nat.choose_zero_right, heq]
        ring
      rw [hsplit]
      congr 1
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl fun m hm => ?_
      have hm1 : 1 ≤ m := Finset.mem_Ico.mp hm |>.1
      have hmp : m < p := Finset.mem_Ico.mp hm |>.2
      have hdiv : (p : ℕ) ∣ p.choose m := hp.dvd_choose_self (by linarith) (by linarith)
      obtain ⟨k, hk⟩ := hdiv
      rw [hk, Nat.mul_div_cancel_left k hp_pos, Nat.cast_mul]
      ring
    rw [hsum]
    calc σ y + σ x - (x ^ p + (p : A) * ∑ m ∈ Finset.Ico 1 p, y ^ m * x ^ (p - m) * ((p.choose m / p : ℕ) : A) + y ^ p)
        = (y ^ p + (p : A) * v) + (x ^ p + (p : A) * u) - (x ^ p + (p : A) * ∑ m ∈ Finset.Ico 1 p, y ^ m * x ^ (p - m) * ((p.choose m / p : ℕ) : A) + y ^ p) := by
          rw [show σ y = y ^ p + (p : A) * v by linear_combination hv]
          rw [show σ x = x ^ p + (p : A) * u by linear_combination hu]
      _ = (p : A) * (u + v - ∑ m ∈ Finset.Ico 1 p, y ^ m * x ^ (p - m) * ((p.choose m / p : ℕ) : A)) := by ring
  | mul x y _ _ hx hy =>
    rw [Ideal.mem_span_singleton] at hx hy ⊢
    have hσxy : σ (x * y) = σ x * σ y := by simp
    have hxpyp : (x * y) ^ p = x ^ p * y ^ p := by ring
    rw [hσxy, hxpyp]
    obtain ⟨u, hu⟩ := hx
    obtain ⟨v, hv⟩ := hy
    use u * σ y + x ^ p * v
    linear_combination hu * σ y + x ^ p * hv

/-- Version of `sub_pow_mem_span_of_mem_adjoin` when `ζ` generates the whole ring. -/
theorem sub_pow_mem_span_of_adjoin_eq_top {p : ℕ} (hp : p.Prime) {ζ : A}
    (htop : Algebra.adjoin ℤ ({ζ} : Set A) = ⊤) (σ : A →+* A) (hσ : σ ζ = ζ ^ p) (x : A) :
    σ x - x ^ p ∈ Ideal.span ({(p : A)} : Set A) :=
  sub_pow_mem_span_of_mem_adjoin hp σ hσ (htop ▸ Algebra.mem_top)

/-- Two ring endomorphisms of `ℤ[ζ]` that agree on `ζ` are equal. -/
theorem ringHom_ext_of_adjoin_eq_top {ζ : A} (htop : Algebra.adjoin ℤ ({ζ} : Set A) = ⊤)
    (σ τ : A →+* A) (h : σ ζ = τ ζ) : σ = τ := by
  apply RingHom.ext
  intro x
  have hx : x ∈ Algebra.adjoin ℤ ({ζ} : Set A) := by rw [htop]; exact Algebra.mem_top
  induction hx using Algebra.adjoin_induction with
  | algebraMap n => simp
  | mem a ha => simp_all
  | add x y _ _ ihx ihy => simp_all
  | mul x y _ _ ihx ihy => simp_all

end Abstract

section Frobenius

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]

/-- **The catalog map is a Frobenius.**  If `S` is generated over `ℤ` by `ζ`, `Q` is an ideal
of `S` lying over a prime of `R` with residue cardinality the prime `p`, and `p ∈ Q`, then any
`R`-algebra endomorphism of `S` with `σ ζ = ζ ^ p` is an arithmetic Frobenius at `Q`. -/
theorem isArithFrobAt_of_map_eq {ζ : S} (htop : Algebra.adjoin ℤ ({ζ} : Set S) = ⊤)
    {p : ℕ} (hp : p.Prime) {Q : Ideal S} (hcard : Nat.card (R ⧸ Q.under R) = p)
    (hpQ : (p : S) ∈ Q) (σ : S →ₐ[R] S) (hσ : σ ζ = ζ ^ p) :
    σ.IsArithFrobAt Q := by
  intro x
  rw [hcard]
  have h := sub_pow_mem_span_of_adjoin_eq_top hp htop (σ.toRingHom) hσ x
  rw [Ideal.mem_span_singleton] at h
  obtain ⟨y, hy⟩ := h
  rw [AlgHom.toRingHom_eq_coe] at hy
  convert Q.mul_mem_right y hpQ using 1

/-- **A Frobenius is the catalog map.**  Conversely, an arithmetic Frobenius at `Q` sends a
root of unity of order prime to the residue characteristic to its `p`-th power. -/
theorem map_eq_of_isArithFrobAt [IsDomain S] {ζ : S} {n : ℕ} (hζ : ζ ^ n = 1)
    {Q : Ideal S} (hn : (n : S) ∉ Q) {p : ℕ} (hcard : Nat.card (R ⧸ Q.under R) = p)
    (σ : S →ₐ[R] S) (hσ : σ.IsArithFrobAt Q) : σ ζ = ζ ^ p := by
  -- IsArithFrobAt means ∀ x, σ x - x ^ Nat.card (R ⧸ Q.under R) ∈ Q
  -- With hcard, this is ∀ x, σ x - x ^ p ∈ Q
  have hσ' : ∀ x : S, σ x - x ^ p ∈ Q := fun x => by
    simpa [hcard] using hσ x
  -- Key facts:
  -- 1. (σ ζ)^n = σ(ζ^n) = σ(1) = 1
  -- 2. ζ^{pn} = (ζ^n)^p = 1
  -- 3. σ ζ ≡ ζ^p [PMOD Q]
  -- We use that (σ ζ)^n = (ζ^p)^n = 1, and if σ ζ ≠ ζ^p, we get n ∈ Q, contradiction
  have h1 : (σ ζ) ^ n = 1 := by rw [← map_pow, hζ, map_one]
  have h2 : (ζ ^ p) ^ n = 1 := by rw [← pow_mul, mul_comm, pow_mul, hζ, one_pow]
  -- Let a = σ ζ, b = ζ^p. We have a^n = b^n = 1 and a - b ∈ Q.
  set a := σ ζ with ha_def
  set b := ζ ^ p with hb_def
  have hab : a - b ∈ Q := hσ' ζ
  -- a^n - b^n = 0 = (a - b) * Σ_{i=0}^{n-1} a^i * b^{n-1-i}
  have hdiff : a ^ n - b ^ n = 0 := by rw [h1, h2, sub_self]
  -- If a ≠ b, then the sum Σ must be 0
  by_cases ha_eq_b : a = b
  · exact ha_eq_b
  · -- a ≠ b, so the sum is zero
    have hne : a - b ≠ 0 := sub_ne_zero.mpr ha_eq_b
    have hsum_eq : (∑ i ∈ Finset.range n, a ^ i * b ^ (n - 1 - i)) = 0 := by
      have hprod : (∑ i ∈ Finset.range n, a ^ i * b ^ (n - 1 - i)) * (a - b) = a ^ n - b ^ n := by
        rw [geom_sum₂_mul]
      rw [hdiff] at hprod
      exact mul_eq_zero.mp hprod |>.resolve_right hne
    -- Now we derive a contradiction: the sum ≡ n * b^(n-1) [PMOD Q]
    -- Since the sum = 0 ∈ Q and b^(n-1) is a unit, n ∈ Q
    have hsum_in_Q : (∑ i ∈ Finset.range n, a ^ i * b ^ (n - 1 - i)) ∈ Q := by rw [hsum_eq]; exact Q.zero_mem
    -- Since a ≡ b [PMOD Q], the sum ≡ n * b^(n-1) [PMOD Q]
    have hab_mod : a ≡ b [SMOD Q] := by
      unfold SModEq
      rw [Submodule.Quotient.eq]
      exact hab
    -- Since a ≡ b [SMOD Q], the sum ≡ n * b^(n-1) [SMOD Q]
    have hsum_mod : (∑ i ∈ Finset.range n, a ^ i * b ^ (n - 1 - i)) ≡ n * b ^ (n - 1) [SMOD Q] := by
      have hterm : ∀ i ∈ Finset.range n, a ^ i * b ^ (n - 1 - i) ≡ b ^ (n - 1) [SMOD Q] := by
        intro i hi
        rw [SModEq]
        have heq : (Ideal.Quotient.mk Q) (a ^ i * b ^ (n - 1 - i)) = (Ideal.Quotient.mk Q) (b ^ (n - 1)) := by
          rw [RingHom.map_mul, RingHom.map_pow, RingHom.map_pow]
          have hab_i : (Ideal.Quotient.mk Q) a = (Ideal.Quotient.mk Q) b := hab_mod
          rw [hab_i, ← RingHom.map_pow, ← RingHom.map_pow]
          rw [← RingHom.map_mul]
          congr 1
          rw [← pow_add, add_tsub_cancel_of_le (Nat.le_sub_one_of_lt (Finset.mem_range.mp hi))]
        exact heq
      -- Sum of congruences gives the result
      calc (∑ i ∈ Finset.range n, a ^ i * b ^ (n - 1 - i))
          ≡ ∑ i ∈ Finset.range n, b ^ (n - 1) [SMOD Q] := by
            simp only [SModEq] at hterm ⊢
            convert Finset.sum_congr rfl hterm using 1 <;> simp
        _ = n * b ^ (n - 1) := by simp
    -- Now we have sum ≡ n * b^(n-1) [SMOD Q] and sum = 0 ∈ Q
    -- So n * b^(n-1) ∈ Q
    have hn_b_mod : (n : S) * b ^ (n - 1) ∈ Q := by
      rw [SModEq] at hsum_mod
      rw [hsum_eq] at hsum_mod
      have : (0 : S) - (n : S) * b ^ (n - 1) ∈ Q := Ideal.Quotient.eq.mp hsum_mod
      simpa using this
    -- Since b^n = 1, b is a unit, so b^(n-1) is a unit
    have hb_unit : IsUnit b := by
      rw [isUnit_iff_exists_inv]
      use b ^ (n - 1)
      cases n with
      | zero => simp_all
      | succ m => simp only [add_tsub_cancel_right] at *; rw [mul_comm, ← pow_succ, h2]
    have hbneg1_unit : IsUnit (b ^ (n - 1)) := hb_unit.pow _
    -- Since n * b^(n-1) ∈ Q and b^(n-1) is a unit, n ∈ Q
    have hn_in_Q : (n : S) ∈ Q := by
      obtain ⟨u, hu⟩ := hbneg1_unit
      have h1 : (n : S) = ((n : S) * b ^ (n - 1)) * u⁻¹ := by
        rw [← hu]
        simp [mul_assoc]
      rw [h1]
      exact Q.mul_mem_right _ hn_b_mod
    contradiction

/-- **Cyclotomic reciprocity, ring-theoretic form.**  For a domain `S = ℤ[ζ]` with `ζ` a root
of unity of order `n` invertible modulo `Q`, and `Q` a prime with residue field of prime
cardinality `p` (with `p ∈ Q`), an endomorphism is the arithmetic Frobenius at `Q` exactly when
it is the catalog map `ζ ↦ ζ ^ p`. -/
theorem isArithFrobAt_iff_map_eq [IsDomain S] {ζ : S} {n : ℕ} (hζ : ζ ^ n = 1)
    (htop : Algebra.adjoin ℤ ({ζ} : Set S) = ⊤) {Q : Ideal S} (hn : (n : S) ∉ Q)
    {p : ℕ} (hp : p.Prime) (hcard : Nat.card (R ⧸ Q.under R) = p) (hpQ : (p : S) ∈ Q)
    (σ : S →ₐ[R] S) : σ.IsArithFrobAt Q ↔ σ ζ = ζ ^ p :=
  ⟨fun h => map_eq_of_isArithFrobAt hζ hn hcard σ h,
   fun h => isArithFrobAt_of_map_eq htop hp hcard hpQ σ h⟩

/-- **Uniqueness of the Frobenius in cyclotomic rings.**  No unramifiedness hypothesis is
needed: the generator `ζ` has a forced image. -/
theorem eq_of_isArithFrobAt [IsDomain S] {ζ : S} {n : ℕ} (hζ : ζ ^ n = 1)
    (htop : Algebra.adjoin ℤ ({ζ} : Set S) = ⊤) {Q : Ideal S} (hn : (n : S) ∉ Q)
    {p : ℕ} (hcard : Nat.card (R ⧸ Q.under R) = p) (σ τ : S →ₐ[R] S)
    (hσ : σ.IsArithFrobAt Q) (hτ : τ.IsArithFrobAt Q) : σ = τ := by
  have hσζ : σ ζ = ζ ^ p := map_eq_of_isArithFrobAt hζ hn hcard σ hσ
  have hτζ : τ ζ = ζ ^ p := map_eq_of_isArithFrobAt hζ hn hcard τ hτ
  have h_gen : σ.toRingHom = τ.toRingHom :=
    ringHom_ext_of_adjoin_eq_top htop _ _ (hσζ.trans hτζ.symm)
  exact AlgHom.ext fun x => congrArg (fun f : S →+* S => f x) h_gen

end Frobenius


/-!
## The cyclotomic Artin map over `ℚ`

We now identify the isomorphism `(ZMod n)ˣ ≃* Gal(ℚ(ζₙ)/ℚ)` (the *catalog map*
`u ↦ (ζ ↦ ζ ^ u)`) with the arithmetic Frobenius on the order `ℤ[ζ]`, for every rational
prime `p` coprime to `n`.
-/

open IsCyclotomicExtension

section Order

variable {L : Type*} [Field L] (ζ : L)

/-- The order `ℤ[ζ]` inside a cyclotomic field. -/
abbrev cycOrder : Subalgebra ℤ L := Algebra.adjoin ℤ ({ζ} : Set L)

theorem zeta_mem_cycOrder : ζ ∈ cycOrder ζ := Algebra.self_mem_adjoin_singleton ℤ ζ

/-- `ℤ[ζ]` is generated over `ℤ` by `ζ`, viewed as one of its own elements. -/
theorem adjoin_zeta_cycOrder_eq_top :
    Algebra.adjoin ℤ ({(⟨ζ, zeta_mem_cycOrder ζ⟩ : cycOrder ζ)} : Set (cycOrder ζ)) = ⊤ := by
  apply le_antisymm le_top
  intro x _
  have hx : x.val ∈ Algebra.adjoin ℤ ({ζ} : Set L) := by simp [cycOrder]
  -- The subtype coercion is the inclusion map, which is an algebra hom
  have hinj : Function.Injective (fun y : cycOrder ζ => (y : L)) := Subtype.coe_injective
  -- Define the algebra homomorphism
  let ι : cycOrder ζ →ₐ[ℤ] L := {
    toFun := (↑)
    map_one' := rfl
    map_mul' := fun _ _ => rfl
    map_zero' := rfl
    map_add' := fun _ _ => rfl
    commutes' := fun _ => rfl
  }
  -- The image of ⟨ζ, _⟩ under ι is ζ
  have hι : ι ⟨ζ, zeta_mem_cycOrder ζ⟩ = ζ := rfl
  -- Show that ι maps adjoin ℤ {⟨ζ, _⟩} to adjoin ℤ {ζ}
  have hmap : (Algebra.adjoin ℤ ({⟨ζ, zeta_mem_cycOrder ζ⟩} : Set (cycOrder ζ))).map ι =
      Algebra.adjoin ℤ ({ζ} : Set L) := by
    refine le_antisymm ?_ ?_
    · apply Subalgebra.map_le.mpr (Algebra.adjoin_le _)
      rintro s rfl
      show (⟨ζ, zeta_mem_cycOrder ζ⟩ : cycOrder ζ) ∈ Subalgebra.comap ι (Algebra.adjoin ℤ ({ζ} : Set L))
      simp [hι]
    · apply Algebra.adjoin_le_iff.mpr
      simp only [Set.singleton_subset_iff]
      exact Subalgebra.mem_map.mpr ⟨⟨ζ, zeta_mem_cycOrder ζ⟩, Algebra.subset_adjoin (by simp), hι.symm⟩
  -- Now use hmap: since hx : ι x ∈ adjoin ℤ {ζ} = map ι (adjoin ℤ {⟨ζ, _⟩}),
  -- there exists y in the adjoin with ι y = ι x, and by injectivity x = y.
  rw [← hmap] at hx
  obtain ⟨y, hy, hyx⟩ := hx
  have : y = x := by simp at hyx; exact hinj hyx
  exact this ▸ hy

end Order

section CatalogMap

variable {n : ℕ} [NeZero n] {L : Type*} [Field L] [Algebra ℚ L]
  [IsCyclotomicExtension {n} ℚ L] {ζ : L}

/-- `IsPrimitiveRoot.autToPow` does not depend on the choice of primitive root. -/
theorem autToPow_eq_autToPow {ζ' : L} (hζ : IsPrimitiveRoot ζ n) (hζ' : IsPrimitiveRoot ζ' n)
    (σ : L ≃ₐ[ℚ] L) : hζ.autToPow ℚ σ = hζ'.autToPow ℚ σ := by
  have hspec1 := hζ.autToPow_spec ℚ σ
  have hspec2 := hζ'.autToPow_spec ℚ σ
  -- σ ζ and σ ζ' are both primitive nth roots
  -- There exists k < n such that ζ' = ζ^k
  obtain ⟨k, hk_lt, hk_eq⟩ := hζ.eq_pow_of_pow_eq_one hζ'.pow_eq_one
  -- k must be coprime to n since ζ' is primitive
  have hk_coprime : k.Coprime n := by
    have h : IsPrimitiveRoot (ζ ^ k) n := by rwa [hk_eq]
    by_contra hnk
    simp only [Nat.Coprime] at hnk
    have hn_ge_2 : 1 < n := by
      by_contra hn_le
      push_neg at hn_le
      interval_cases n <;> simp_all
    have hk_ne : k ≠ 0 := by
      intro hk0
      subst hk0
      simp at hk_eq hk_lt
      have h' : IsPrimitiveRoot (1 : L) n := by simpa using h
      have : n ∣ 1 := h'.2 1 (by simp)
      exact absurd this (Nat.not_dvd_of_pos_of_lt zero_lt_one hn_ge_2)
    have hgcd := Nat.gcd_pos_of_pos_left n (Nat.pos_of_ne_zero hk_ne)
    have hnk' : k.gcd n ≠ 1 := hnk
    have hgcd_gt : 1 < k.gcd n := Nat.one_lt_iff_ne_zero_and_ne_one.mpr ⟨Nat.ne_zero_of_lt hgcd, hnk'⟩
    have hdvd_n : k.gcd n ∣ n := by rw [Nat.gcd_comm]; exact Nat.gcd_dvd_left n k
    obtain ⟨m, hm⟩ := hdvd_n
    have hm_pos : 0 < m := by nlinarith
    have hm_lt : m < n := by nlinarith
    -- (ζ^k)^m = 1, contradicting minimality of n
    have hpow : (ζ ^ k) ^ m = 1 := by
      rw [← pow_mul]
      have hdvd_k : k.gcd n ∣ k := by rw [Nat.gcd_comm]; exact Nat.gcd_dvd_right n k
      obtain ⟨l, hl⟩ := hdvd_k
      rw [hl]
      have hg : k.gcd n * l * m = n * l := by
        have : k.gcd n ∣ k.gcd n * m := dvd_mul_right _ _
        simp only [mul_comm] at *
        nlinarith
      rw [hg, pow_mul, hζ.pow_eq_one, one_pow]
    exact Nat.not_dvd_of_pos_of_lt hm_pos hm_lt (h.2 m hpow)
  -- Compute σ ζ' in two ways
  have h1 : σ ζ' = (σ ζ) ^ k := by rw [← hk_eq, map_pow]
  set a := hζ.autToPow ℚ σ with ha_def
  set a' := hζ'.autToPow ℚ σ with ha'_def
  have h2 : (σ ζ) ^ k = ζ ^ (ZMod.val (a : ZMod n) * k) := by
    rw [← hspec1]
    rw [pow_mul]
  have h3 : ζ' ^ (ZMod.val (a' : ZMod n) : ℕ) = ζ ^ ((k : ℕ) * ZMod.val (a' : ZMod n)) := by rw [← hk_eq]; ring
  -- Combine: σ ζ' = ζ ^ (a.val * k) = ζ' ^ a'.val = ζ ^ (k * a'.val)
  have heq : ζ ^ (ZMod.val (a : ZMod n) * k) = ζ ^ (k * ZMod.val (a' : ZMod n)) := by
    calc ζ ^ (ZMod.val (a : ZMod n) * k) = (σ ζ) ^ k := h2.symm
      _ = σ ζ' := h1.symm
      _ = ζ' ^ (ZMod.val (a' : ZMod n)) := hspec2.symm
      _ = ζ ^ (k * ZMod.val (a' : ZMod n)) := h3
  -- Since ζ is primitive, a.val * k ≡ k * a'.val (mod n)
  have hmod : ZMod.val (a : ZMod n) * k ≡ k * ZMod.val (a' : ZMod n) [MOD n] := by
    have hζ_ord : orderOf ζ = n := by
      exact orderOf_eq_of_pow_and_pow_div_prime (NeZero.pos n) hζ.pow_eq_one (by
        intro p hp hpn
        have hlt : n / p < n := Nat.div_lt_self (NeZero.pos n) hp.one_lt
        exact fun h => absurd (hζ.2 (n / p) h) (Nat.not_dvd_of_pos_of_lt (Nat.div_pos (Nat.le_of_dvd (NeZero.pos n) hpn) hp.pos) hlt))
    have hζ_ne : ζ ≠ 0 := hζ.ne_zero (NeZero.ne n)
    -- We need: x ≡ y [MOD n] where x = a.val * k and y = k * a'.val
    -- Given: ζ^x = ζ^y
    -- This means ζ^(x-y) = 1 when x ≥ y, or ζ^(y-x) = 1 when y > x
    -- In either case, n ∣ |x - y|, so x ≡ y [MOD n]
    by_cases hle : ZMod.val (a : ZMod n) * k ≤ k * ZMod.val (a' : ZMod n)
    · have hpow : ζ ^ (k * ZMod.val (a' : ZMod n)) = ζ ^ (ZMod.val (a : ZMod n) * k) * ζ ^ (k * ZMod.val (a' : ZMod n) - ZMod.val (a : ZMod n) * k) := by
        rw [← pow_add, add_tsub_cancel_of_le hle]
      rw [heq.symm] at hpow
      have hpos : ζ ^ (ZMod.val (a : ZMod n) * k) ≠ 0 := pow_ne_zero _ hζ_ne
      have h1 : ζ ^ (k * ZMod.val (a' : ZMod n) - ZMod.val (a : ZMod n) * k) = 1 := by
        have hpow' : ζ ^ (ZMod.val (a : ZMod n) * k) * ζ ^ (k * ZMod.val (a' : ZMod n) - ZMod.val (a : ZMod n) * k) = ζ ^ (ZMod.val (a : ZMod n) * k) * 1 := by
          rw [mul_one, eq_comm]; exact hpow
        exact mul_left_cancel₀ hpos hpow'
      have hdvd : n ∣ (k * ZMod.val (a' : ZMod n) - ZMod.val (a : ZMod n) * k) := by
        have := orderOf_dvd_iff_pow_eq_one.mpr h1
        rw [hζ_ord] at this
        exact this
      rw [Nat.modEq_iff_dvd]
      convert hdvd using 2
      all_goals norm_cast
    · push_neg at hle
      have hpow : ζ ^ (ZMod.val (a : ZMod n) * k) = ζ ^ (k * ZMod.val (a' : ZMod n)) * ζ ^ (ZMod.val (a : ZMod n) * k - k * ZMod.val (a' : ZMod n)) := by
        rw [← pow_add, add_tsub_cancel_of_le (le_of_lt hle)]
      rw [heq] at hpow
      have hpos : ζ ^ (k * ZMod.val (a' : ZMod n)) ≠ 0 := pow_ne_zero _ hζ_ne
      have h1 : ζ ^ (ZMod.val (a : ZMod n) * k - k * ZMod.val (a' : ZMod n)) = 1 := by
        have hpow' : ζ ^ (k * ZMod.val (a' : ZMod n)) * ζ ^ (ZMod.val (a : ZMod n) * k - k * ZMod.val (a' : ZMod n)) = ζ ^ (k * ZMod.val (a' : ZMod n)) * 1 := by
          rw [mul_one, eq_comm]; exact hpow
        exact mul_left_cancel₀ hpos hpow'
      have hdvd : n ∣ (ZMod.val (a : ZMod n) * k - k * ZMod.val (a' : ZMod n)) := by
        have := orderOf_dvd_iff_pow_eq_one.mpr h1
        rw [hζ_ord] at this
        exact this
      rw [Nat.modEq_iff_dvd]
      have hle2 : (a : ZMod n).val * k ≥ k * (a' : ZMod n).val := le_of_lt hle
      have : (↑(k * (a' : ZMod n).val) : ℤ) - ↑((a : ZMod n).val * k) = -((↑((a : ZMod n).val * k) : ℤ) - ↑(k * (a' : ZMod n).val)) := by ring
      rw [this]
      simp only [dvd_neg]
      exact_mod_cast hdvd
  -- From hmod : a.val * k ≡ k * a'.val [MOD n] and hk_coprime, deduce a.val ≡ a'.val [MOD n]
  have hmod' : (a : ZMod n).val ≡ (a' : ZMod n).val [MOD n] := by
    have h1 : (k : ZMod n) * (a : ZMod n) = (k : ZMod n) * (a' : ZMod n) := by
      rw [Nat.ModEq] at hmod
      have := congr_arg (fun x : ℕ => (x : ZMod n)) hmod
      simp only [Nat.cast_mul, ZMod.natCast_mod] at this
      simp (config := {singlePass := true}) at this
      rw [mul_comm] at this
      simp_all
    have hk_unit : IsUnit (k : ZMod n) := (ZMod.unitOfCoprime k hk_coprime).isUnit
    have h2 : (a : ZMod n) = (a' : ZMod n) := hk_unit.mul_left_cancel h1
    simp [h2]
    rfl
  -- From hmod' and the fact that val is injective on ZMod n, deduce a = a'
  have hval_eq : (a : ZMod n).val = (a' : ZMod n).val := by
    have ha_lt : (a : ZMod n).val < n := ZMod.val_lt _
    have ha'_lt : (a' : ZMod n).val < n := ZMod.val_lt _
    rw [Nat.ModEq, Nat.mod_eq_of_lt ha_lt, Nat.mod_eq_of_lt ha'_lt] at hmod'
    exact hmod'
  have h3 : (a : ZMod n) = (a' : ZMod n) := by
    apply ZMod.val_injective
    exact hval_eq
  exact Units.ext h3

omit [IsCyclotomicExtension {n} ℚ L] in
/-- **The catalog description of `autToPow`.**  An automorphism of a cyclotomic field is sent
by `IsPrimitiveRoot.autToPow` to the residue class of `m` exactly when it is the catalog map
`ζ ↦ ζ ^ m`. -/
theorem autToPow_eq_unitOfCoprime_iff (hζ : IsPrimitiveRoot ζ n) {m : ℕ} (hm : m.Coprime n)
    (σ : L ≃ₐ[ℚ] L) : hζ.autToPow ℚ σ = ZMod.unitOfCoprime m hm ↔ σ ζ = ζ ^ m := by
  have hspec := hζ.autToPow_spec ℚ σ
  constructor
  · intro h
    rw [h] at hspec
    rw [hspec.symm]
    simp only [ZMod.unitOfCoprime]
    -- Goal: ζ ^ (↑m).val = ζ ^ m
    -- (↑m).val = m % n, and ζ ^ m = ζ ^ (m % n)
    rw [ZMod.val_natCast]
    have hm_eq : m = m % n + n * (m / n) := (Nat.mod_add_div m n).symm
    conv_rhs => rw [hm_eq]
    rw [pow_add, pow_mul, hζ.pow_eq_one, one_pow, mul_one]
  · intro h
    -- hspec: ζ ^ (autToPow ℚ hζ σ).val = σ ζ
    -- h: σ ζ = ζ ^ m
    -- So ζ ^ (autToPow ℚ hζ σ).val = ζ ^ m
    rw [h] at hspec
    -- hspec: ζ ^ (autToPow ℚ hζ σ).val = ζ ^ m
    -- The autToPow is a unit in (ZMod n)ˣ
    set u := hζ.autToPow ℚ σ with hu_def
    -- hspec says ζ ^ u.val = ζ ^ m
    -- Since ζ is primitive, u.val ≡ m (mod n)
    have h_eq : Nat.ModEq n u.val.val m := by
      simp only [Nat.ModEq]
      -- hspec : ζ ^ u.val.val = ζ ^ m
      -- We use that ζ has exact order n
      -- From ζ^a = ζ^b, we get ζ^(a-b) = 1, so n | (a-b)
      -- Hence a ≡ b (mod n)
      have key : ζ ^ (u.val.val % n) = ζ ^ (m % n) := by
        conv_lhs at hspec => rw [← Nat.mod_add_div (u.val.val) n]
        conv_rhs at hspec => rw [← Nat.mod_add_div m n]
        simp only [pow_add, pow_mul, hζ.pow_eq_one, one_pow, mul_one] at hspec
        exact hspec
      have hlt_u : (u.val.val : ℕ) % n < n := Nat.mod_lt _ (NeZero.pos n)
      have hlt_m : m % n < n := Nat.mod_lt _ (NeZero.pos n)
      exact hζ.pow_inj (by simp [hlt_u]) (by simp [hlt_m]) key
    -- h_eq : u.val.val ≡ m [MOD n]
    -- u and ZMod.unitOfCoprime m hm are both units with the same val
    rw [Units.ext_iff]
    -- Need to show u.val = (ZMod.unitOfCoprime m hm).val
    -- Both are congruent to m mod n, and are in ZMod n
    have h2 : (u.val.val : ℕ) % n = m % n := h_eq
    simp [ZMod.unitOfCoprime]
    -- Goal: u.val = (m : ZMod n)
    -- u.val = (u.val.val : ZMod n) by definition of val
    -- (u.val.val : ZMod n) = (m : ZMod n) since u.val.val % n = m % n
    -- Goal: (u : ZMod n) = (m : ZMod n)
    -- We have h2: u.val.val % n = m % n
    -- (u : ZMod n) = u.val, and u.val.val % n = m % n implies u.val = (m : ZMod n)
    -- Try using the fact that in ZMod n, equality is defined by val
    have h3 : (u.val : ZMod n).val = (m : ZMod n).val := by
      have hlt : (u.val : ZMod n).val < n := ZMod.val_lt _
      rw [Nat.mod_eq_of_lt hlt] at h2
      simp [h2]
    -- Goal: (u : ZMod n) = (m : ZMod n)
    -- h3: u.val.val = (m : ZMod n).val
    -- u : (ZMod n)ˣ, so ↑u = u.val : ZMod n
    simp at h3 ⊢
    have h4 : (m : ZMod n).val = m % n := ZMod.val_natCast n m
    have h5 : (↑u : ZMod n).val = (↑m : ZMod n).val := by rw [h3, h4]
    have h6 := @ZMod.val_injective n _ (u : ZMod n) (m : ZMod n) h5
    exact h6

variable (L) in
/-- **The cyclotomic Artin map over `ℚ`**: the isomorphism `(ZMod n)ˣ ≃* Gal(ℚ(ζₙ)/ℚ)`. -/
noncomputable def artinMap : (ZMod n)ˣ ≃* (L ≃ₐ[ℚ] L) :=
  (IsCyclotomicExtension.autEquivPow L (cyclotomic.irreducible_rat (NeZero.pos n))).symm

/-- The Artin map sends the class of `m` (coprime to `n`) to the catalog automorphism
`ζ ↦ ζ ^ m`. -/
theorem artinMap_unitOfCoprime_zeta (hζ : IsPrimitiveRoot ζ n) {m : ℕ} (hm : m.Coprime n) :
    artinMap L (ZMod.unitOfCoprime m hm) ζ = ζ ^ m := by
  -- Use autToPow_eq_autToPow from supporting code (line 274-276)
  set ζc := IsCyclotomicExtension.zeta n ℚ L with hζc_def
  have hζc : IsPrimitiveRoot ζc n := IsCyclotomicExtension.zeta_spec n ℚ L
  have h_ae_eq := autToPow_eq_autToPow hζ hζc
  -- Use autToPow_spec for hζ
  have hspec := hζ.autToPow_spec ℚ (artinMap L (ZMod.unitOfCoprime m hm))
  -- Show autToPow ℚ hζ (artinMap L u) = u
  have hu : hζ.autToPow ℚ (artinMap L (ZMod.unitOfCoprime m hm)) = ZMod.unitOfCoprime m hm := by
    rw [h_ae_eq]
    -- Now use autEquivPow_apply for canonical zeta
    have haeq := IsCyclotomicExtension.autEquivPow_apply L (cyclotomic.irreducible_rat (NeZero.pos n))
      (artinMap L (ZMod.unitOfCoprime m hm))
    -- haeq : autEquivPow L irreducible σ = autToPow ℚ hζc σ
    -- So autToPow ℚ hζc σ = autEquivPow L irreducible σ
    have haeq' : hζc.autToPow ℚ (artinMap L (ZMod.unitOfCoprime m hm)) =
        IsCyclotomicExtension.autEquivPow L (cyclotomic.irreducible_rat (NeZero.pos n))
      (artinMap L (ZMod.unitOfCoprime m hm)) := haeq.symm
    rw [haeq']
    -- Now show autEquivPow L irreducible (artinMap L u) = u
    exact (IsCyclotomicExtension.autEquivPow L (cyclotomic.irreducible_rat (NeZero.pos n))).apply_symm_apply _
  rw [hu] at hspec
  -- hspec : ζ ^ (u.val : ℕ) = (artinMap L u) ζ
  -- u = unitOfCoprime m hm, so u.val = m % n
  -- We need: (artinMap L u) ζ = ζ ^ m
  -- Since ζ^n = 1 and m % n ≡ m (mod n), we have ζ^(m % n) = ζ^m
  have hm_mod : (ZMod.unitOfCoprime m hm : ZMod n).val = m % n := by simp [ZMod.unitOfCoprime]
  rw [hm_mod] at hspec
  -- Now show ζ ^ (m % n) = ζ ^ m
  have hpow_eq : ζ ^ (m % n) = ζ ^ m := by
    rw [← Nat.mod_add_div m n, pow_add, pow_mul]
    simp [hζ.pow_eq_one]
  rw [hpow_eq] at hspec
  exact hspec.symm

/-- The Artin map is multiplicative: `σ_{uv} = σ_u ∘ σ_v`. -/
theorem artinMap_mul (u v : (ZMod n)ˣ) :
    artinMap L (u * v) = (artinMap L u : L ≃ₐ[ℚ] L) * artinMap L v :=
  map_mul _ _ _

/-- The Artin symbol of `m` preserves the order `ℤ[ζ]`. -/
theorem artinMap_zeta_mem_cycOrder (hζ : IsPrimitiveRoot ζ n) {m : ℕ} (hm : m.Coprime n) :
    artinMap L (ZMod.unitOfCoprime m hm) ζ ∈ cycOrder ζ := by
  rw [artinMap_unitOfCoprime_zeta hζ hm]
  exact pow_mem (zeta_mem_cycOrder ζ) m

end CatalogMap

section Restriction

variable {L : Type*} [Field L] {ζ : L}

/-- An automorphism sending `ζ` into `ℤ[ζ]` preserves `ℤ[ζ]`. -/
theorem mapsTo_cycOrder (σ : L →+* L) (h : σ ζ ∈ cycOrder ζ) (x : cycOrder ζ) :
    σ (x : L) ∈ cycOrder ζ := by
  have key : ∀ y : L, y ∈ Algebra.adjoin ℤ ({ζ} : Set L) → σ y ∈ cycOrder ζ := by
    intro y hy
    induction hy using Algebra.adjoin_induction with
    | algebraMap n => simp [map_intCast]
    | mem a ha => simp_all
    | add x y hx hy ihx ihy => simp only [map_add]; exact add_mem ihx ihy
    | mul x y hx hy ihx ihy => simp only [map_mul]; exact mul_mem ihx ihy
  exact key _ x.prop

/-- Restriction of a ring endomorphism of `L` preserving `ℤ[ζ]` to an endomorphism of `ℤ[ζ]`. -/
noncomputable def restrictCycOrder (σ : L →+* L) (h : σ ζ ∈ cycOrder ζ) :
    cycOrder ζ →ₐ[ℤ] cycOrder ζ :=
  AlgHom.codRestrict ((σ.toIntAlgHom).comp (cycOrder ζ).val) _ (mapsTo_cycOrder σ h)

@[simp]
theorem restrictCycOrder_apply (σ : L →+* L) (h : σ ζ ∈ cycOrder ζ) (x : cycOrder ζ) :
    ((restrictCycOrder σ h x : cycOrder ζ) : L) = σ (x : L) := rfl

theorem restrictCycOrder_zeta (σ : L →+* L) (h : σ ζ ∈ cycOrder ζ) :
    restrictCycOrder σ h ⟨ζ, zeta_mem_cycOrder ζ⟩ = ⟨σ ζ, h⟩ := rfl

end Restriction

section Reciprocity

variable {n : ℕ} [NeZero n] {L : Type*} [Field L] [Algebra ℚ L]
  [IsCyclotomicExtension {n} ℚ L] {ζ : L}

/-- **Cyclotomic reciprocity over `ℚ`.**  Let `p` be a rational prime coprime to `n` and let `Q`
be a prime of the order `ℤ[ζ]` lying over `p`.  Then the restriction to `ℤ[ζ]` of the catalog
automorphism `σ_p : ζ ↦ ζ ^ p` — i.e. the value of the Artin map at the residue class of `p` —
is an arithmetic Frobenius at `Q`. -/
theorem isArithFrobAt_restrict_artinMap (hζ : IsPrimitiveRoot ζ n) {p : ℕ} (hp : p.Prime)
    (hpn : p.Coprime n) {Q : Ideal (cycOrder ζ)}
    (hcard : Nat.card (ℤ ⧸ Q.under ℤ) = p) (hpQ : (p : cycOrder ζ) ∈ Q) :
    (restrictCycOrder (artinMap L (ZMod.unitOfCoprime p hpn) : L →+* L)
      (artinMap_zeta_mem_cycOrder hζ hpn)).IsArithFrobAt Q := by
  exact isArithFrobAt_of_map_eq (adjoin_zeta_cycOrder_eq_top ζ) hp hcard hpQ _
    (by simp [restrictCycOrder_zeta, artinMap_unitOfCoprime_zeta hζ hpn])

/-- **Uniqueness.**  The arithmetic Frobenius at a prime of `ℤ[ζ]` above `p ∤ n` is unique, so it
*is* the restricted Artin symbol of `isArithFrobAt_restrict_artinMap`. -/
theorem eq_restrict_artinMap_of_isArithFrobAt (hζ : IsPrimitiveRoot ζ n) {p : ℕ}
    (hpn : p.Coprime n) {Q : Ideal (cycOrder ζ)}
    (hcard : Nat.card (ℤ ⧸ Q.under ℤ) = p) (hn : ((n : ℕ) : cycOrder ζ) ∉ Q)
    (φ : cycOrder ζ →ₐ[ℤ] cycOrder ζ) (hφ : φ.IsArithFrobAt Q) :
    φ = restrictCycOrder (artinMap L (ZMod.unitOfCoprime p hpn) : L →+* L)
      (artinMap_zeta_mem_cycOrder hζ hpn) := by
  have htop := adjoin_zeta_cycOrder_eq_top ζ
  have hζ' : (⟨ζ, zeta_mem_cycOrder ζ⟩ : cycOrder ζ) ^ n = 1 := by
    exact Subtype.ext hζ.pow_eq_one
  have hσ : φ ⟨ζ, zeta_mem_cycOrder ζ⟩ = ⟨ζ, zeta_mem_cycOrder ζ⟩ ^ p :=
    map_eq_of_isArithFrobAt (S := cycOrder ζ) hζ' hn hcard φ hφ
  have hτ : (restrictCycOrder (artinMap L (ZMod.unitOfCoprime p hpn))
      (artinMap_zeta_mem_cycOrder hζ hpn)) ⟨ζ, zeta_mem_cycOrder ζ⟩ =
      ⟨ζ, zeta_mem_cycOrder ζ⟩ ^ p := by
    rw [restrictCycOrder_zeta]
    exact Subtype.ext (artinMap_unitOfCoprime_zeta hζ hpn)
  have h_eq : φ.toRingHom = (restrictCycOrder (artinMap L (ZMod.unitOfCoprime p hpn))
      (artinMap_zeta_mem_cycOrder hζ hpn)).toRingHom :=
    ringHom_ext_of_adjoin_eq_top htop _ _ (hσ.trans hτ.symm)
  exact AlgHom.ext (fun x => congrArg (fun f : cycOrder ζ →+* cycOrder ζ => f x) h_eq)

end Reciprocity

end Catalog.Pythagorean.CyclotomicFrobenius