import Mathlib

/-!
# Tropical Rank Growth Under Matrix Powers

This file formalizes a **tropical complexity-growth law**: bounded monotone
integer-valued complexity measures on matrix powers must eventually stabilize,
and strict rank jumps produce provably large image sets.

## Main results

* `tropicalRank_le_dim` — the number of distinct columns of an n×n matrix is ≤ n.
* `monotone_nat_eventually_stable` — any monotone sequence ℕ → ℕ bounded above
  eventually stabilizes.
* `strict_mono_Fin_le` — a strictly increasing sequence on `Fin (M+1)` bounded
  by `n` satisfies `M ≤ n`.
* `tropical_rank_eventually_stable` — the tropical-rank sequence of matrix powers
  stabilizes (assuming monotonicity).
* `exists_strict_rank_growth_of_nonstable` — a monotone non-stable rank sequence
  must witness a strict increase.
* `rank_ne_implies_matrix_ne` — matrices with different tropical ranks are distinct.
* `distinct_powers_of_rank_jumps` — `M` consecutive rank jumps produce `M + 1`
  pairwise-distinct matrix powers.
* `powerColumnSet_card_ge_of_rank_jumps` — `M` consecutive rank jumps force the
  column-image set to have cardinality at least `M + 1`.

## Notation

We work with tropical matrices over `Tropical (WithTop ℤ)`, where
- tropical addition = min
- tropical multiplication = +
- tropical zero = ⊤
- tropical one = 0

Standard matrix multiplication over this semiring gives the min-plus tropical
matrix product.
-/

open Finset

noncomputable section

/-! ## Tropical matrix type and rank -/

/-- Abbreviation for the tropical semiring over `WithTop ℤ`. -/
abbrev TropZ := Tropical (WithTop ℤ)

/-- Abbreviation for n×n tropical matrices. -/
abbrev TropMat (n : ℕ) := Matrix (Fin n) (Fin n) TropZ

/-- The **tropical rank** of a matrix: the number of distinct columns.
This measures the "column complexity" of the matrix — how many
structurally different column vectors it contains. -/
def tropicalRank {n : ℕ} (A : TropMat n) : ℕ :=
  (Finset.univ.image (fun j : Fin n => fun i : Fin n => A i j)).card

/-- The column set of a single matrix: the set of its distinct column vectors. -/
def columnSet {n : ℕ} (A : TropMat n) : Finset (Fin n → TropZ) :=
  Finset.univ.image (fun j : Fin n => fun i : Fin n => A i j)

/-- The **power column set**: the union of all column vectors appearing in
matrix powers `A^0, A^1, …, A^M`. Measures the total column diversity
generated by iterating the tropical matrix. -/
def powerColumnSet {n : ℕ} (A : TropMat n) (M : ℕ) : Finset (Fin n → TropZ) :=
  (Finset.range (M + 1)).biUnion (fun m => columnSet (A ^ m))

theorem tropicalRank_eq_columnSet_card {n : ℕ} (A : TropMat n) :
    tropicalRank A = (columnSet A).card := rfl

/-! ## Core bound: tropical rank ≤ dimension -/

/-
The tropical rank of an n×n matrix is at most n.
-/
theorem tropicalRank_le_dim {n : ℕ} (A : TropMat n) :
    tropicalRank A ≤ n := by
  exact Finset.card_image_le.trans_eq ( Finset.card_fin _ )

/-! ## Combinatorial lemmas on bounded sequences -/

/-
Any monotone (nondecreasing) sequence `ℕ → ℕ` that is bounded above
eventually stabilizes: there exists an index after which the sequence
is constant.
-/
theorem monotone_nat_eventually_stable (f : ℕ → ℕ) (n : ℕ)
    (hmono : Monotone f) (hbound : ∀ m, f m ≤ n) :
    ∃ N, ∀ m, N ≤ m → f m = f N := by
  -- Since $f$ is monotone and bounded above, it must eventually stabilize.
  have h_stabilize : Filter.Tendsto f Filter.atTop (nhds (sSup {f m | m : ℕ})) := by
    exact tendsto_atTop_isLUB hmono ( isLUB_ciSup ⟨ n, by rintro x ⟨ m, rfl ⟩ ; exact hbound m ⟩ );
  norm_num +zetaDelta at *;
  exact ⟨ h_stabilize.choose, fun m hm => by rw [ h_stabilize.choose_spec m hm, h_stabilize.choose_spec _ le_rfl ] ⟩

/-
A strictly increasing function from `Fin (M + 1)` into `{0, …, n}`
satisfies `M ≤ n`. This is the key pigeonhole principle for
bounding the number of strict rank jumps.
-/
theorem strict_mono_Fin_le (M n : ℕ)
    (f : Fin (M + 1) → ℕ) (hf : StrictMono f) (hbound : ∀ i, f i ≤ n) :
    M ≤ n := by
  -- Since $f$ is strictly monotone, we have $f i ≥ i$ for all $i$.
  have h_mono : ∀ i : Fin (M + 1), (i : ℕ) ≤ f i := by
    intro i;
    induction' i using Fin.inductionOn with i IH;
    · exact Nat.zero_le _;
    · exact Nat.succ_le_of_lt ( lt_of_le_of_lt IH ( hf ( Nat.lt_succ_self _ ) ) );
  exact le_trans ( h_mono ⟨ M, Nat.lt_succ_self M ⟩ ) ( hbound _ )

/-
A monotone sequence bounded by `n` has at most `n` strict-increase
steps: if `f(m) < f(m+1)` for `M` distinct values of `m`, then `M ≤ n`.
-/
theorem monotone_strict_increases_bounded (f : ℕ → ℕ) (n M : ℕ)
    (_hmono : Monotone f) (hbound : ∀ m, f m ≤ n)
    (hjumps : ∀ k : Fin M, f (k : ℕ) < f ((k : ℕ) + 1)) :
    M ≤ n := by
  set g : Fin (M + 1) → ℕ := fun k => f k.val;
  have hg_strict_mono : StrictMono g := by
    intro i j hij
    simp [g];
    induction' j using Fin.inductionOn with j ih;
    · contradiction;
    · grind +revert;
  exact strict_mono_Fin_le M n g hg_strict_mono fun i => hbound _

/-! ## Core theorems: rank growth and stabilization -/

/-
If the tropical-rank sequence under powering is monotone, it
eventually stabilizes.
-/
theorem tropical_rank_eventually_stable {n : ℕ} (A : TropMat n)
    (hmono : Monotone (fun m => tropicalRank (A ^ m))) :
    ∃ N, ∀ m, N ≤ m → tropicalRank (A ^ m) = tropicalRank (A ^ N) := by
  -- By definition of `tropicalRank`, we know that `tropicalRank (A ^ m) ≤ n` for all `m`.
  have hbound : ∀ m, tropicalRank (A ^ m) ≤ n := fun m => tropicalRank_le_dim _
  exact monotone_nat_eventually_stable (fun m => tropicalRank (A ^ m)) n hmono hbound

/-
If the tropical-rank sequence is monotone and non-stable (i.e., not
eventually constant from the start), then there exists a step where
rank strictly increases.
-/
theorem exists_strict_rank_growth_of_nonstable {n : ℕ} (A : TropMat n)
    (hmono : Monotone (fun m => tropicalRank (A ^ m)))
    (h_nonstable : ∃ m, tropicalRank (A ^ (m + 1)) ≠ tropicalRank (A ^ m)) :
    ∃ m, tropicalRank (A ^ m) < tropicalRank (A ^ (m + 1)) := by
  exact h_nonstable.imp fun m hm => lt_of_le_of_ne ( hmono m.le_succ ) ( Ne.symm hm )

/-
The total number of strict tropical-rank jumps under powering is at most n.
In other words, if ranks strictly increase at M consecutive steps
`0, 1, …, M−1`, then `M ≤ n`.
-/
theorem total_rank_jumps_bounded {n : ℕ} (A : TropMat n) (M : ℕ)
    (hjumps : ∀ k : Fin M,
      tropicalRank (A ^ (k : ℕ)) < tropicalRank (A ^ ((k : ℕ) + 1))) :
    M ≤ n := by
  -- Define g(k) = tropicalRank(A^k), g is strictly increasing by hjumps.
  set g : Fin (M + 1) → ℕ := fun k => tropicalRank (A ^ (k.val)) with hg
  have hg_mono : StrictMono g := by
    intros i j hij; induction' j using Fin.inductionOn with j ih ih; aesop;
    grind;
  exact strict_mono_Fin_le M n g hg_mono fun k => tropicalRank_le_dim _

/-! ## Rank jumps ⟹ distinct matrix powers -/

/-
Matrices with different tropical ranks must be different matrices.
-/
theorem rank_ne_implies_matrix_ne {n : ℕ} (A B : TropMat n)
    (h : tropicalRank A ≠ tropicalRank B) : A ≠ B := by
  contrapose! h; aesop;

/-
If the rank sequence strictly increases at each of steps `0, …, M−1`,
then the matrix powers `A^0, A^1, …, A^M` are pairwise distinct.
-/
theorem distinct_powers_of_rank_jumps {n : ℕ} (A : TropMat n) (M : ℕ)
    (hjumps : ∀ k : Fin M,
      tropicalRank (A ^ (k : ℕ)) < tropicalRank (A ^ ((k : ℕ) + 1)))
    (i j : Fin (M + 1)) (hij : i ≠ j) :
    A ^ (i : ℕ) ≠ A ^ (j : ℕ) := by
  -- By the strict increase property, if $i < j$, then the rank of $A^i$ is less than the rank of $A^j$.
  have h_rank_lt : ∀ i j : Fin (M + 1), i < j → tropicalRank (A ^ i.val) < tropicalRank (A ^ j.val) := by
    intro i j hij; induction' j using Fin.inductionOn with j ih ih; aesop;
    grind +revert;
  cases lt_or_gt_of_ne hij <;> [ exact fun h => ne_of_lt ( h_rank_lt _ _ ‹_› ) ( by aesop ) ; exact fun h => ne_of_gt ( h_rank_lt _ _ ‹_› ) ( by aesop ) ]

/-! ## Image-set growth from rank jumps -/

/-
**Main image-set growth theorem.** If the tropical rank strictly increases
at each of the first `M` powering steps, then the power column set has
at least `M + 1` elements. This translates algebraic complexity (rank growth)
into dynamical complexity (large output diversity under iteration).
-/
theorem powerColumnSet_card_ge_of_rank_jumps {n : ℕ} (hn : 0 < n) (A : TropMat n) (M : ℕ)
    (hjumps : ∀ k : Fin M,
      tropicalRank (A ^ (k : ℕ)) < tropicalRank (A ^ ((k : ℕ) + 1))) :
    M + 1 ≤ (powerColumnSet A M).card := by
  by_cases hM : M = 0 <;> simp_all +decide;
  · exact ⟨ _, Finset.mem_biUnion.mpr ⟨ 0, Finset.mem_range.mpr ( Nat.succ_pos _ ), Finset.mem_image_of_mem _ ( Finset.mem_univ ⟨ 0, hn ⟩ ) ⟩ ⟩;
  · -- Since $M \neq 0$, we have $tropicalRank (A ^ 0) < tropicalRank (A ^ 1)$.
    have h_rank_0_1 : tropicalRank (1 : TropMat n) < tropicalRank (A ^ 1) := by
      simpa using hjumps ⟨ 0, Nat.pos_of_ne_zero hM ⟩;
    -- Since $tropicalRank(1) = n$ and $tropicalRank(A^1) \leq n$, we have $n < n$, which is a contradiction.
    have h_contradiction : tropicalRank (1 : TropMat n) = n := by
      unfold tropicalRank;
      rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective ];
      simp +decide [ funext_iff, Matrix.one_apply ];
      intro i j h; specialize h i; aesop;
    linarith [ show tropicalRank ( A ^ 1 ) ≤ n from tropicalRank_le_dim _ ]

/-! ## Finite range of rank values -/

/-
The set of tropical rank values attained by powers of a matrix is finite.
This holds unconditionally (no monotonicity needed), since ranks are
bounded by the dimension.
-/
theorem finite_range_tropical_rank_powers {n : ℕ} (A : TropMat n) :
    Set.Finite (Set.range (fun m => tropicalRank (A ^ m))) := by
  exact Set.finite_iff_bddAbove.mpr ⟨ n, by rintro _ ⟨ m, rfl ⟩ ; exact tropicalRank_le_dim _ ⟩

/-! ## Rank-1 characterization -/

/-
A tropical matrix has rank ≤ 1 if and only if all its columns are
identical.
-/
theorem tropicalRank_le_one_iff {n : ℕ} (_hn : 0 < n) (A : TropMat n) :
    tropicalRank A ≤ 1 ↔
      ∀ j₁ j₂ : Fin n, (fun i => A i j₁) = (fun i => A i j₂) := by
  constructor;
  · intro h j₁ j₂; contrapose! h; simp_all +decide;
    refine' Finset.one_lt_card.mpr ⟨ _, Finset.mem_image_of_mem _ ( Finset.mem_univ j₁ ), _, Finset.mem_image_of_mem _ ( Finset.mem_univ j₂ ), _ ⟩ ; aesop;
  · exact fun h => Finset.card_le_one.mpr fun x hx y hy => by obtain ⟨ j₁, _, rfl ⟩ := Finset.mem_image.mp hx; obtain ⟨ j₂, _, rfl ⟩ := Finset.mem_image.mp hy; exact h j₁ j₂;

end