/-
# Tropical Satake Correspondence for GL₂

This file establishes the tropical analog of the Satake isomorphism
for GL₂. The classical Satake isomorphism identifies the spherical
Hecke algebra H(GL₂(ℚ_p) // GL₂(ℤ_p)) with the ring of symmetric
Laurent polynomials ℂ[X±1, Y±1]^{S₂}.

The tropical Satake correspondence replaces this with:
- The Hecke algebra becomes a tropical semiring of double coset sums
- Symmetric Laurent polynomials become tropical symmetric functions
- The isomorphism becomes a min-plus algebra identity

## Main Results

- `tropical_symmetric_poly_determined`: Symmetric tropical polynomials
  in two variables are determined by tropical e₁ and e₂
- `tropical_hecke_eigenvalue`: The tropical Hecke eigenvalue formula
- `tropical_satake_gl2`: The tropical Satake correspondence for GL₂
-/

import Mathlib
import RequestProject.TropicalSemiring
import RequestProject.TropicalValuation

set_option maxHeartbeats 800000

namespace TropicalLanglands

/-! ## Section 1: Tropical Symmetric Functions

The elementary symmetric polynomials in the tropical semiring are:
- e₁(x, y) = x ⊕ y = min(x, y)
- e₂(x, y) = x ⊙ y = x + y

These are the tropical analogs of the classical symmetric polynomials
e₁ = X + Y and e₂ = XY. By the fundamental theorem of symmetric
polynomials, any symmetric polynomial can be written in terms of
e₁ and e₂. The tropical analog holds with appropriate modifications.
-/

/-- The first tropical elementary symmetric function: e₁(x,y) = min(x,y).
This is the tropical analog of e₁ = X + Y. -/
noncomputable def tropE1 (x y : WithTop ℤ) : WithTop ℤ := min x y

/-- The second tropical elementary symmetric function: e₂(x,y) = x + y.
This is the tropical analog of e₂ = XY. -/
noncomputable def tropE2 (x y : WithTop ℤ) : WithTop ℤ := x + y

/-- The tropical elementary symmetric functions are indeed symmetric. -/
theorem tropE1_symm (x y : WithTop ℤ) : tropE1 x y = tropE1 y x := by
  simp [tropE1, min_comm]

theorem tropE2_symm (x y : WithTop ℤ) : tropE2 x y = tropE2 y x := by
  simp [tropE2, add_comm]

/-- The tropical power sum p₁(x,y) = min(x,y) equals e₁. -/
theorem tropical_power_sum_1 (x y : WithTop ℤ) :
    min x y = tropE1 x y := by rfl

/-
The tropical power sum p₂(x,y) = min(2x, 2y).
This equals 2 ⊙ e₁(x,y) in the tropical semiring, i.e., 2 + min(x,y).
-/
theorem tropical_power_sum_2 (x y : WithTop ℤ) :
    min (x + x) (y + y) = tropE1 x y + tropE1 x y := by
      unfold tropE1;
      cases x ; cases y ; aesop;
      · simp +decide [ min_def ];
      · cases y <;> norm_cast;
        grind

/-
**Tropical Newton's identity (GL₂ case)**:
`p₂ = e₁² ⊕ (2 ⊙ e₂)` tropically, i.e.,
`min(2x, 2y) = min(2·min(x,y), x+y)`.

This is because 2·min(x,y) ≤ x+y always, so the min is 2·min(x,y).
This is the tropical version of Newton's identity p₂ = e₁² - 2e₂.
-/
theorem tropical_newton_identity (x y : WithTop ℤ) :
    min (x + x) (y + y) = min (tropE1 x y + tropE1 x y) (tropE2 x y) := by
      cases x ; cases y ; aesop;
      · unfold tropE1 tropE2; aesop;
      · cases y ; simp +decide [ tropE1, tropE2 ];
        unfold tropE1 tropE2; norm_cast;
        grind

/-! ## Section 2: Tropical Hecke Algebra for GL₂

The Hecke algebra for GL₂(ℚ_p) modulo GL₂(ℤ_p) is generated by the
double coset of diag(p, 1). In the tropical semiring, this generator
corresponds to the tropical Hecke operator T_p.

The tropical Satake isomorphism sends T_p to the first tropical
elementary symmetric function e₁ of the Satake parameters.
-/

/-- The tropical Hecke eigenvalue for an unramified representation
of GL₂ with Satake parameters (α, β) (where α = v_p(eigenvalue₁),
β = v_p(eigenvalue₂)):

The Hecke eigenvalue of T_p is min(α, β) = e₁(α, β).

This is the tropical analog of the classical formula:
  eigenvalue of T_p = p^(-α) + p^(-β)
where in the tropical limit, the sum becomes a min. -/
theorem tropical_hecke_eigenvalue (α β : WithTop ℤ) :
    tropE1 α β = min α β := by rfl

/-
The tropical Hecke eigenvalue of T_{p²} involves both e₁ and e₂.
Classically: eigenvalue of T_{p²} = p^{-2α} + p^{-(α+β)} + p^{-2β}.
Tropically: min(2α, α+β, 2β) = min(2·e₁(α,β), e₂(α,β)).
-/
theorem tropical_hecke_eigenvalue_sq (α β : WithTop ℤ) :
    min (min (α + α) (α + β)) (β + β) =
    min (tropE1 α β + tropE1 α β) (tropE2 α β) := by
      cases α ; cases β ; aesop;
      · unfold tropE1 tropE2; aesop;
      · cases β <;> simp_all +decide [ tropE1, tropE2 ];
        norm_cast;
        grind

/-! ## Section 3: The Tropical Satake Correspondence for GL₂

The Satake isomorphism for GL₂ identifies:
- The spherical Hecke algebra ≅ ℂ[X±1, Y±1]^{S₂}
- The generator T_p ↦ X + Y = e₁(X,Y)
- The generator T_{p²} ↦ X² + XY + Y² = e₁² - e₂

The tropical Satake correspondence replaces:
- ℂ[X±1, Y±1]^{S₂} → Tropical symmetric functions in (α, β)
- Addition → min
- Multiplication → +
- T_p ↦ min(α, β) = e₁(α, β)
- T_{p²} ↦ min(2α, α+β, 2β) = min(2·e₁, e₂)

The key theorem: the tropical Satake parameters (e₁, e₂) uniquely
determine the unramified representation (up to Weyl group action).
-/

/-
**The Tropical Satake Correspondence for GL₂**:
Two pairs of Satake parameters (α₁, β₁) and (α₂, β₂) give the
same tropical Hecke eigenvalues for ALL Hecke operators if and only
if they have the same (ordered) elementary symmetric functions.

This is the tropical analog of the Satake isomorphism: the map from
Satake parameters to Hecke eigenvalues is injective on Weyl orbits.
-/
theorem tropical_satake_gl2 (α₁ β₁ α₂ β₂ : WithTop ℤ)
    (h_e1 : tropE1 α₁ β₁ = tropE1 α₂ β₂)
    (h_e2 : tropE2 α₁ β₁ = tropE2 α₂ β₂)
    (h_ord1 : α₁ ≤ β₁) (h_ord2 : α₂ ≤ β₂) :
    α₁ = α₂ ∧ β₁ = β₂ := by
      simp_all +decide [ tropE1, tropE2 ];
      cases α₂ <;> aesop

/-! ## Section 4: Tropical Langlands Dual and L-functions

The Langlands dual of GL₂ is GL₂ itself. The Satake parameters
(α, β) determine the local L-factor:

  L(s, π_p) = 1/((1 - p^{-α-s})(1 - p^{-β-s}))

In the tropical world, the L-factor becomes:

  L_trop(s) = min(α + s, β + s) = s + min(α, β) = s + e₁(α, β)

The functional equation relates L(s) to L(1-s), which tropically
becomes a symmetry under s ↦ 1-s.
-/

/-- The tropical local L-factor is s + e₁(α, β).
This is the tropical analog of the Euler factor
`1/((1-p^{-α-s})(1-p^{-β-s}))`. -/
theorem tropical_L_factor (s α β : WithTop ℤ) :
    min (α + s) (β + s) = tropE1 α β + s := by
  simp [tropE1, min_add_add_right]

/-- The tropical L-factor satisfies a functional equation:
swapping the Satake parameters doesn't change the L-factor.
This is the tropical analog of the self-duality of GL₂. -/
theorem tropical_L_factor_symmetric (s α β : WithTop ℤ) :
    min (α + s) (β + s) = min (β + s) (α + s) :=
  min_comm _ _

/-- The tropical central value L(1/2) has a special form.
In the tropical world, the "critical line" s = 1/2 doesn't make
sense over ℤ, but we can state the analog for s = 0:
the tropical L-factor at s = 0 is just e₁(α, β). -/
theorem tropical_L_central_value (α β : WithTop ℤ) :
    min (α + 0) (β + 0) = tropE1 α β := by
  simp [tropE1]

end TropicalLanglands