"""
Aboriginal Kinship Systems: Group-Theoretic Algorithms

Implements the core algorithms for computing kinship relations
in Aboriginal section and subsection systems modeled as finite
abelian groups (Z2)^n.
"""

from typing import Tuple, List, Set, Dict, Optional
from itertools import product
from dataclasses import dataclass


# Type aliases
Z2 = int  # Elements are 0 or 1, arithmetic mod 2
Section4 = Tuple[Z2, Z2]
Section8 = Tuple[Z2, Z2, Z2]


def z2_add(a: Tuple[Z2, ...], b: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
    """Add two elements of (Z2)^n."""
    return tuple((x + y) % 2 for x, y in zip(a, b))


def z2_neg(a: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
    """Negate an element of (Z2)^n. (Same as identity since -1 = 1 mod 2.)"""
    return a  # In Z2, every element is its own inverse


def z2_sub(a: Tuple[Z2, ...], b: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
    """Subtract two elements of (Z2)^n."""
    return z2_add(a, z2_neg(b))


def z2_zero(n: int) -> Tuple[Z2, ...]:
    """The zero element of (Z2)^n."""
    return tuple(0 for _ in range(n))


@dataclass
class KinshipSystem:
    """A kinship system on (Z2)^n with marriage and descent offsets.

    Attributes:
        n: Dimension (n=2 for 4-section, n=3 for 8-subsection)
        marriage: Marriage offset element
        descent: Descent offset element
        section_names: Optional human-readable names for sections
    """
    n: int
    marriage: Tuple[Z2, ...]
    descent: Tuple[Z2, ...]
    section_names: Optional[Dict[Tuple[Z2, ...], str]] = None

    def __post_init__(self) -> None:
        assert len(self.marriage) == self.n
        assert len(self.descent) == self.n
        assert z2_add(self.marriage, self.marriage) == z2_zero(self.n), \
            "Marriage must be an involution (2m = 0)"
        assert self.marriage != z2_zero(self.n), "Exogamy: marriage offset must be nonzero"
        assert self.descent != z2_zero(self.n), "Descent must be nontrivial"
        assert self.marriage != self.descent, "Marriage and descent must be independent"

    def marry(self, section: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
        """Compute the marriage-eligible section for a given section.

        Algorithm: O(n) addition in (Z2)^n.
        """
        return z2_add(section, self.marriage)

    def descend(self, section: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
        """Compute the child's section from the mother's section.

        Algorithm: O(n) addition in (Z2)^n.
        """
        return z2_add(section, self.descent)

    def ascend(self, section: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
        """Compute the mother's section from the child's section (inverse descent).

        Algorithm: O(n) subtraction in (Z2)^n.
        In Z2, subtraction equals addition, so this is the same as descend.
        """
        return z2_sub(section, self.descent)

    def cross_cousin(self, section: Tuple[Z2, ...]) -> Tuple[Z2, ...]:
        """Compute the section of the mother's brother's daughter.

        By the Cross-Cousin Marriage Theorem, this always equals marry(section).

        Algorithm:
            1. Ascend to mother's section: s - d
            2. Marry to get uncle's wife's section: (s - d) + m
            3. Descend to get cousin's section: (s - d) + m + d = s + m

        Time complexity: O(n)
        """
        mother = self.ascend(section)
        uncles_wife = self.marry(mother)
        cousin = self.descend(uncles_wife)
        return cousin

    def descend_n(self, section: Tuple[Z2, ...], generations: int) -> Tuple[Z2, ...]:
        """Compute the section after n generations of descent.

        Uses the formula: descendN(s, n) = s + n * descent

        Algorithm: O(n) since in Z2, n * d = (n mod 2) * d
        """
        if generations % 2 == 0:
            return section
        else:
            return self.descend(section)

    def can_marry(self, s: Tuple[Z2, ...], t: Tuple[Z2, ...]) -> bool:
        """Check if two sections can intermarry.

        Algorithm: O(n) comparison.
        """
        return z2_sub(t, s) == self.marriage

    def moiety(self, section: Tuple[Z2, ...]) -> Z2:
        """Compute the moiety (first component) of a section."""
        return section[0]

    def generation_class(self, section: Tuple[Z2, ...]) -> Z2:
        """Compute the generation class (second component) of a section."""
        return section[1] if self.n >= 2 else 0

    def all_sections(self) -> List[Tuple[Z2, ...]]:
        """List all sections of the kinship system."""
        return list(product([0, 1], repeat=self.n))

    def marriage_pairs(self) -> List[Tuple[Tuple[Z2, ...], Tuple[Z2, ...]]]:
        """List all marriage pairs."""
        pairs = []
        for s in self.all_sections():
            t = self.marry(s)
            if s <= t:  # Avoid duplicates
                pairs.append((s, t))
        return pairs

    def generated_subgroup(self) -> Set[Tuple[Z2, ...]]:
        """Compute the subgroup generated by marriage and descent offsets.

        Algorithm: Closure under addition, starting from {0, m, d}.
        Since the group is finite, this terminates in O(|G|^2) steps.
        """
        subgroup = {z2_zero(self.n), self.marriage, self.descent}
        changed = True
        while changed:
            changed = False
            new_elements = set()
            for a in subgroup:
                for b in subgroup:
                    c = z2_add(a, b)
                    if c not in subgroup:
                        new_elements.add(c)
                        changed = True
            subgroup |= new_elements
        return subgroup

    def is_full_generator(self) -> bool:
        """Check if marriage and descent generate the full group."""
        return len(self.generated_subgroup()) == 2 ** self.n

    def section_name(self, s: Tuple[Z2, ...]) -> str:
        """Get human-readable name for a section."""
        if self.section_names and s in self.section_names:
            return self.section_names[s]
        return str(s)


def kariera() -> KinshipSystem:
    """The Kariera 4-section kinship system.

    Sections: A=(0,0), B=(1,0), C=(0,1), D=(1,1)
    Marriage: A↔B, C↔D
    Descent: A→C, B→D, C→A, D→B
    """
    return KinshipSystem(
        n=2,
        marriage=(1, 0),
        descent=(0, 1),
        section_names={
            (0, 0): "A", (1, 0): "B",
            (0, 1): "C", (1, 1): "D"
        }
    )


def aranda() -> KinshipSystem:
    """The Aranda 8-subsection kinship system.

    Subsections: 8 elements of (Z2)^3
    Marriage offset: (1,0,0)
    Descent offset: (0,1,1)
    """
    names = {}
    labels = ["A₁", "B₁", "C₁", "D₁", "A₂", "B₂", "C₂", "D₂"]
    for i, s in enumerate(product([0, 1], repeat=3)):
        names[s] = labels[i]
    return KinshipSystem(
        n=3,
        marriage=(1, 0, 0),
        descent=(0, 1, 1),
        section_names=names
    )


def verify_cross_cousin_theorem(ks: KinshipSystem) -> bool:
    """Verify the cross-cousin marriage theorem for all sections.

    The theorem states: crossCousin(s) = marry(s) for all s.
    Returns True if verified for all sections.
    """
    for s in ks.all_sections():
        if ks.cross_cousin(s) != ks.marry(s):
            return False
    return True


def verify_marriage_involution(ks: KinshipSystem) -> bool:
    """Verify that marry(marry(s)) = s for all sections."""
    for s in ks.all_sections():
        if ks.marry(ks.marry(s)) != s:
            return False
    return True


def verify_grandchild_return(ks: KinshipSystem) -> bool:
    """Verify that descend(descend(s)) = s for all sections."""
    for s in ks.all_sections():
        if ks.descend(ks.descend(s)) != s:
            return False
    return True


def classify_kinship_systems(n: int) -> List[KinshipSystem]:
    """Enumerate all valid kinship systems on (Z2)^n.

    A valid system requires:
    - marriage ≠ 0, descent ≠ 0, marriage ≠ descent
    - marriage + marriage = 0 (automatic in Z2)

    Returns list of all valid systems (may contain isomorphic duplicates).
    """
    zero = z2_zero(n)
    elements = list(product([0, 1], repeat=n))
    nonzero = [e for e in elements if e != zero]

    systems = []
    for m in nonzero:
        for d in nonzero:
            if m != d:
                systems.append(KinshipSystem(n=n, marriage=m, descent=d))
    return systems


def two_generator_bound_test(n: int = 3) -> Dict[str, any]:
    """Test the two-generator bound conjecture for (Z2)^n.

    Conjecture: For n ≥ 3, no two nonzero distinct elements generate (Z2)^n.

    Returns test results including max subgroup size found.
    """
    zero = z2_zero(n)
    elements = list(product([0, 1], repeat=n))
    nonzero = [e for e in elements if e != zero]

    max_size = 0
    full_count = 0
    total_pairs = 0

    for i, m in enumerate(nonzero):
        for d in nonzero[i+1:]:
            ks = KinshipSystem(n=n, marriage=m, descent=d)
            sg = ks.generated_subgroup()
            size = len(sg)
            max_size = max(max_size, size)
            if size == 2**n:
                full_count += 1
            total_pairs += 1

    return {
        "n": n,
        "group_order": 2**n,
        "pairs_tested": total_pairs,
        "max_subgroup_size": max_size,
        "full_generators": full_count,
        "conjecture_holds": full_count == 0
    }
