#!/usr/bin/env python3
"""
Symmetric Group Generation — Algorithms

Implements key algorithms for computing and analyzing generation probability
of symmetric groups, including:

1. Subgroup generation via BFS closure
2. Schreier-Sims style generation test
3. Obstruction analysis by subgroup type
4. Monte Carlo estimation of generation probability for larger n
"""

from itertools import permutations
from math import factorial, comb
from fractions import Fraction
from collections import defaultdict
import random
from typing import List, Tuple, Set, Dict, Optional


# ─────────────────────────────────────────────────────────────────────────────
# Core Permutation Operations
# ─────────────────────────────────────────────────────────────────────────────

def identity(n: int) -> Tuple[int, ...]:
    """Return the identity permutation on n elements."""
    return tuple(range(n))


def compose(a: Tuple[int, ...], b: Tuple[int, ...]) -> Tuple[int, ...]:
    """Compose permutations: (a ∘ b)(i) = a(b(i))."""
    return tuple(a[b[i]] for i in range(len(a)))


def inverse(p: Tuple[int, ...]) -> Tuple[int, ...]:
    """Compute the inverse of a permutation."""
    n = len(p)
    inv = [0] * n
    for i in range(n):
        inv[p[i]] = i
    return tuple(inv)


def sign(p: Tuple[int, ...]) -> int:
    """Compute the sign of a permutation: +1 (even) or -1 (odd)."""
    n = len(p)
    visited = [False] * n
    cycles = 0
    for i in range(n):
        if not visited[i]:
            cycles += 1
            j = i
            while not visited[j]:
                visited[j] = True
                j = p[j]
    return (-1) ** (n - cycles)


def cycle_type(p: Tuple[int, ...]) -> Tuple[int, ...]:
    """Return the cycle type of a permutation as a sorted tuple of cycle lengths."""
    n = len(p)
    visited = [False] * n
    lengths = []
    for i in range(n):
        if not visited[i]:
            length = 0
            j = i
            while not visited[j]:
                visited[j] = True
                j = p[j]
                length += 1
            lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


# ─────────────────────────────────────────────────────────────────────────────
# Algorithm 1: BFS Subgroup Generation
# ─────────────────────────────────────────────────────────────────────────────

def generate_subgroup_bfs(generators: List[Tuple[int, ...]], n: int) -> Set[Tuple[int, ...]]:
    """
    Generate the subgroup of S_n from generators using breadth-first search.

    Time complexity: O(|H|^2) where |H| is the size of the generated subgroup.
    Space complexity: O(|H|).

    Args:
        generators: List of permutations (as tuples).
        n: Degree of the symmetric group.

    Returns:
        Set of all elements in the generated subgroup.
    """
    e = identity(n)
    subgroup = {e}
    queue = []

    for g in generators:
        if g not in subgroup:
            subgroup.add(g)
            queue.append(g)

    while queue:
        g = queue.pop(0)
        for h in list(subgroup):
            for product in [compose(g, h), compose(h, g)]:
                if product not in subgroup:
                    subgroup.add(product)
                    queue.append(product)

    return subgroup


def generates_symmetric_group(sigma: Tuple[int, ...], tau: Tuple[int, ...]) -> bool:
    """
    Test whether two permutations generate the full symmetric group S_n.

    Uses BFS subgroup generation and checks if the result has n! elements.

    Args:
        sigma, tau: Permutations of {0, ..., n-1}.

    Returns:
        True iff ⟨σ, τ⟩ = S_n.
    """
    n = len(sigma)
    sg = generate_subgroup_bfs([sigma, tau], n)
    return len(sg) == factorial(n)


# ─────────────────────────────────────────────────────────────────────────────
# Algorithm 2: Quick Generation Test via Parity + Transitivity
# ─────────────────────────────────────────────────────────────────────────────

def is_transitive(generators: List[Tuple[int, ...]], n: int) -> bool:
    """
    Test if the group generated by `generators` acts transitively on {0,...,n-1}.

    Uses orbit computation from point 0.

    Time complexity: O(n * |generators| * orbit_size).
    """
    if n == 0:
        return True

    orbit = {0}
    queue = [0]
    while queue:
        pt = queue.pop(0)
        for g in generators:
            img = g[pt]
            if img not in orbit:
                orbit.add(img)
                queue.append(img)
            # Also apply inverse
            img_inv = inverse(g)[pt]
            if img_inv not in orbit:
                orbit.add(img_inv)
                queue.append(img_inv)
    return len(orbit) == n


def quick_generation_filter(sigma: Tuple[int, ...], tau: Tuple[int, ...]) -> Optional[bool]:
    """
    Quick filter for generation testing.

    Returns:
        False if we can quickly determine the pair does NOT generate S_n.
        None if we cannot determine quickly (need full BFS).

    Checks:
        1. Parity obstruction: if both are even, return False.
        2. Transitivity: if the group is intransitive, return False.
    """
    n = len(sigma)
    if n <= 1:
        return None

    # Parity check
    if sign(sigma) == 1 and sign(tau) == 1:
        return False

    # Transitivity check
    if not is_transitive([sigma, tau], n):
        return False

    return None  # Need full test


# ─────────────────────────────────────────────────────────────────────────────
# Algorithm 3: Exact Generation Counting
# ─────────────────────────────────────────────────────────────────────────────

def exact_generation_count(n: int) -> Dict:
    """
    Compute exact generation statistics for S_n by brute force.

    Returns a dictionary with counts and probabilities.

    Warning: Time complexity is O(n!^3), so only practical for n ≤ 5.
    """
    perms = list(permutations(range(n)))
    total = len(perms) ** 2
    gen_count = 0
    parity_filtered = 0
    transitivity_filtered = 0

    for sigma in perms:
        for tau in perms:
            result = quick_generation_filter(sigma, tau)
            if result is False:
                if sign(sigma) == 1 and sign(tau) == 1:
                    parity_filtered += 1
                else:
                    transitivity_filtered += 1
                continue
            if generates_symmetric_group(sigma, tau):
                gen_count += 1

    return {
        'n': n,
        'group_size': factorial(n),
        'total_pairs': total,
        'generating_pairs': gen_count,
        'probability': Fraction(gen_count, total),
        'parity_filtered': parity_filtered,
        'transitivity_filtered': transitivity_filtered,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Algorithm 4: Monte Carlo Generation Probability Estimation
# ─────────────────────────────────────────────────────────────────────────────

def random_permutation(n: int) -> Tuple[int, ...]:
    """Generate a uniformly random permutation of {0, ..., n-1}."""
    perm = list(range(n))
    random.shuffle(perm)
    return tuple(perm)


def monte_carlo_gen_prob(n: int, samples: int = 10000) -> Dict:
    """
    Estimate P(⟨σ, τ⟩ = S_n) by Monte Carlo sampling.

    For each sample, generates two random permutations and tests
    if they generate S_n.

    Args:
        n: Degree of symmetric group.
        samples: Number of random pairs to test.

    Returns:
        Dictionary with estimated probability and confidence interval.
    """
    successes = 0
    parity_failures = 0
    transitivity_failures = 0

    for _ in range(samples):
        sigma = random_permutation(n)
        tau = random_permutation(n)

        quick = quick_generation_filter(sigma, tau)
        if quick is False:
            if sign(sigma) == 1 and sign(tau) == 1:
                parity_failures += 1
            else:
                transitivity_failures += 1
            continue

        if generates_symmetric_group(sigma, tau):
            successes += 1

    p_hat = successes / samples
    # 95% confidence interval (normal approximation)
    import math
    se = math.sqrt(p_hat * (1 - p_hat) / samples) if samples > 0 else 0
    ci = (p_hat - 1.96 * se, p_hat + 1.96 * se)

    return {
        'n': n,
        'samples': samples,
        'successes': successes,
        'estimated_probability': p_hat,
        'confidence_interval_95': ci,
        'parity_failure_rate': parity_failures / samples,
        'transitivity_failure_rate': transitivity_failures / samples,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Algorithm 5: Obstruction Analysis
# ─────────────────────────────────────────────────────────────────────────────

def analyze_obstructions(n: int) -> Dict:
    """
    Analyze the contribution of different obstructions to non-generation.

    Obstructions:
        1. Parity: both permutations are even.
        2. Point stabilizer: both fix a common point.
        3. Block system: both preserve a non-trivial partition.

    Returns contribution fractions for each obstruction type.
    """
    an_size = factorial(n) // 2 if n >= 2 else factorial(n)
    sn_size = factorial(n)

    # Parity obstruction
    parity_fraction = Fraction(an_size ** 2, sn_size ** 2)

    # Point stabilizer obstruction (both fix point i)
    # |Stab(i)| = (n-1)!, so fraction fixing point i is ((n-1)!/n!)^2 = 1/n^2
    # Union bound over n points: ≤ n * 1/n^2 = 1/n
    point_stab_each = Fraction(1, n ** 2) if n >= 1 else Fraction(0)
    point_stab_union = n * point_stab_each if n >= 1 else Fraction(0)

    # Young subgroup S_k × S_{n-k} obstruction
    # |S_k × S_{n-k}| = k! * (n-k)!, contribution = (k!(n-k)!/n!)^2
    young_contributions = {}
    for k in range(1, n):
        size = factorial(k) * factorial(n - k)
        frac = Fraction(size ** 2, sn_size ** 2)
        # Number of such subgroups = C(n, k)
        count = comb(n, k)
        young_contributions[k] = {
            'subgroup_size': size,
            'single_contribution': frac,
            'num_conjugates': count,
            'total_contribution_bound': count * frac,
        }

    return {
        'n': n,
        'parity_obstruction': parity_fraction,
        'point_stabilizer_each': point_stab_each,
        'point_stabilizer_union_bound': point_stab_union,
        'young_subgroups': young_contributions,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Main demonstration
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("=" * 70)
    print("  Symmetric Group Generation — Algorithm Demonstrations")
    print("=" * 70)

    # Exact counts for small n
    print("\n📊 Exact generation counts:")
    print(f"  {'n':>3}  {'|S_n|':>8}  {'gen pairs':>10}  {'probability':>12}  {'decimal':>10}")
    print(f"  {'─'*3}  {'─'*8}  {'─'*10}  {'─'*12}  {'─'*10}")

    for n in range(1, 6):
        stats = exact_generation_count(n)
        print(f"  {n:>3}  {stats['group_size']:>8}  "
              f"{stats['generating_pairs']:>10}  "
              f"{str(stats['probability']):>12}  "
              f"{float(stats['probability']):>10.6f}")

    # Obstruction analysis
    print("\n📐 Obstruction analysis:")
    for n in [3, 4, 5, 10, 20]:
        obs = analyze_obstructions(n)
        print(f"\n  S_{n}:")
        print(f"    Parity obstruction: {float(obs['parity_obstruction']):.6f}"
              f" (exactly {obs['parity_obstruction']})")
        print(f"    Point stabilizer union bound: {float(obs['point_stabilizer_union_bound']):.6f}"
              f" (≤ 1/{n})")

    # Monte Carlo for larger n
    print("\n🎲 Monte Carlo estimates (10000 samples each):")
    print(f"  {'n':>3}  {'est. prob':>10}  {'95% CI':>20}  {'parity fail':>12}")
    print(f"  {'─'*3}  {'─'*10}  {'─'*20}  {'─'*12}")

    random.seed(42)
    for n in [5, 10, 20, 50]:
        mc = monte_carlo_gen_prob(n, samples=10000)
        ci = mc['confidence_interval_95']
        print(f"  {n:>3}  {mc['estimated_probability']:>10.4f}  "
              f"({ci[0]:.4f}, {ci[1]:.4f})  "
              f"{mc['parity_failure_rate']:>12.4f}")

    print(f"\n{'=' * 70}")
    print("  Key insight: As n grows, p_n → 3/4 from below.")
    print("  The dominant obstruction is parity (1/4 of pairs have both even).")
    print(f"{'=' * 70}")
