#!/usr/bin/env python3
"""
Algorithms for Counterpoint Category Theory

Type-hinted implementations of the core algorithms for analyzing
consonant intervals as algebraic structures in ℤ/12ℤ.
"""

from typing import Set, Tuple, List, Dict, Optional
from math import gcd
from itertools import product


class ZMod:
    """Element of ℤ/nℤ."""
    def __init__(self, value: int, n: int = 12):
        self.n = n
        self.value = value % n

    def __add__(self, other: 'ZMod') -> 'ZMod':
        assert self.n == other.n
        return ZMod(self.value + other.value, self.n)

    def __neg__(self) -> 'ZMod':
        return ZMod(-self.value, self.n)

    def __sub__(self, other: 'ZMod') -> 'ZMod':
        return self + (-other)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, ZMod):
            return self.n == other.n and self.value == other.value
        return NotImplemented

    def __hash__(self) -> int:
        return hash((self.value, self.n))

    def __repr__(self) -> str:
        return f"{self.value}"


class ConsonanceAnalyzer:
    """Analyzes consonance structure in n-TET systems."""

    # Simple frequency ratios and their corresponding interval sizes in 12-TET
    JUST_RATIOS: Dict[str, Tuple[int, int]] = {
        "unison": (1, 1),
        "minor_third": (6, 5),
        "major_third": (5, 4),
        "perfect_fourth": (4, 3),
        "perfect_fifth": (3, 2),
        "minor_sixth": (8, 5),
        "major_sixth": (5, 3),
    }

    def __init__(self, n: int = 12, consonant_set: Optional[Set[int]] = None):
        self.n = n
        if consonant_set is None:
            self.consonant: Set[int] = {0, 3, 4, 7, 8, 9}
        else:
            self.consonant = consonant_set
        self.dissonant: Set[int] = set(range(n)) - self.consonant
        self.perfect: Set[int] = {0, 7} & self.consonant
        self.imperfect: Set[int] = self.consonant - self.perfect

    def invert(self, i: int) -> int:
        """Octave complement (inversion)."""
        return (self.n - i) % self.n

    def is_inversion_closed(self, S: Optional[Set[int]] = None) -> bool:
        """Check if a set is closed under inversion."""
        if S is None:
            S = self.consonant
        return all(self.invert(i) in S for i in S)

    def find_symmetry_defects(self) -> List[int]:
        """Find elements where inversion breaks consonance."""
        return [i for i in self.consonant if self.invert(i) not in self.consonant]

    def unique_dissonant_with_consonant_inversion(self) -> List[int]:
        """Find dissonant intervals whose inversion is consonant."""
        return [d for d in self.dissonant if self.invert(d) in self.consonant]

    def subgroup_generated_by(self, generators: Set[int]) -> Set[int]:
        """Compute the additive subgroup of ℤ/nℤ generated by a set."""
        subgroup = {0}
        frontier = set(generators)
        while frontier:
            new = set()
            for a in frontier:
                for b in subgroup | frontier:
                    for c in [(a + b) % self.n, (a - b) % self.n, (b - a) % self.n]:
                        if c not in subgroup and c not in frontier:
                            new.add(c)
            subgroup |= frontier
            frontier = new
        return subgroup

    def generates_all(self, generators: Set[int]) -> bool:
        """Check if a set generates all of ℤ/nℤ."""
        return len(self.subgroup_generated_by(generators)) == self.n

    def consonant_sum(self) -> int:
        """Sum of consonant intervals mod n."""
        return sum(self.consonant) % self.n


class VoiceLead:
    """A voice leading in ℤ/12ℤ."""
    def __init__(self, step_upper: int, step_lower: int, n: int = 12):
        self.step_upper = step_upper % n
        self.step_lower = step_lower % n
        self.n = n

    @property
    def interval_change(self) -> int:
        return (self.step_upper - self.step_lower) % self.n

    @property
    def is_parallel(self) -> bool:
        return self.step_upper == self.step_lower

    @property
    def is_stationary(self) -> bool:
        return self.step_upper == 0 and self.step_lower == 0

    def compose(self, other: 'VoiceLead') -> 'VoiceLead':
        return VoiceLead(
            (self.step_upper + other.step_upper) % self.n,
            (self.step_lower + other.step_lower) % self.n,
            self.n
        )

    def __repr__(self) -> str:
        return f"VL({self.step_upper}, {self.step_lower})"


class CounterpointCategory:
    """The category of first-species counterpoint voice leadings."""

    def __init__(self, analyzer: ConsonanceAnalyzer):
        self.analyzer = analyzer
        self.n = analyzer.n
        self.objects = sorted(analyzer.consonant)

    def is_valid_lead(self, i: int, j: int, vl: VoiceLead) -> bool:
        """Check if a voice leading is valid from interval i to j."""
        # Interval change must match
        if vl.interval_change != (j - i) % self.n:
            return False
        # No parallel motion to perfect consonances (unless stationary)
        if j in self.analyzer.perfect and vl.is_parallel and not vl.is_stationary:
            return False
        return True

    def find_valid_leads(self, i: int, j: int) -> List[VoiceLead]:
        """Find all valid voice leadings from interval i to j."""
        valid = []
        for su in range(self.n):
            for sl in range(self.n):
                vl = VoiceLead(su, sl, self.n)
                if self.is_valid_lead(i, j, vl):
                    valid.append(vl)
        return valid

    def count_morphisms(self) -> Dict[Tuple[int, int], int]:
        """Count morphisms between each pair of objects."""
        counts: Dict[Tuple[int, int], int] = {}
        for i in self.objects:
            for j in self.objects:
                counts[(i, j)] = len(self.find_valid_leads(i, j))
        return counts

    def transition_matrix(self) -> List[List[int]]:
        """Compute the transition count matrix."""
        counts = self.count_morphisms()
        matrix = []
        for i in self.objects:
            row = [counts[(i, j)] for j in self.objects]
            matrix.append(row)
        return matrix

    def is_thin(self) -> bool:
        """Check if the category is thin (at most one morphism per hom-set)."""
        counts = self.count_morphisms()
        return all(c <= 1 for c in counts.values())


class TensionPoset:
    """The tension partial order on consonant intervals."""

    RANKS: Dict[int, int] = {0: 0, 7: 1, 3: 2, 4: 2, 8: 2, 9: 2}

    def __init__(self):
        self.elements = sorted(self.RANKS.keys())

    def le(self, a: int, b: int) -> bool:
        """Tension ordering: a ≤ b iff rank(a) ≤ rank(b)."""
        return self.RANKS[a] <= self.RANKS[b]

    def fiber(self, rank: int) -> List[int]:
        """Elements at a given tension rank."""
        return [i for i in self.elements if self.RANKS[i] == rank]

    def fiber_sizes(self) -> List[int]:
        """Sizes of fibers at each rank."""
        return [len(self.fiber(r)) for r in range(3)]

    def hasse_diagram(self) -> List[Tuple[int, int]]:
        """Compute the Hasse diagram (covering relations)."""
        covers = []
        for a in self.elements:
            for b in self.elements:
                if self.RANKS[a] + 1 == self.RANKS[b]:
                    covers.append((a, b))
        return covers


def main():
    """Run all algorithms and display results."""
    print("=== Consonance Analysis ===")
    analyzer = ConsonanceAnalyzer()

    print(f"Consonant: {sorted(analyzer.consonant)}")
    print(f"Dissonant: {sorted(analyzer.dissonant)}")
    print(f"Inversion-closed (consonant): {analyzer.is_inversion_closed()}")
    print(f"Inversion-closed (imperfect): {analyzer.is_inversion_closed(analyzer.imperfect)}")
    print(f"Symmetry defects: {analyzer.find_symmetry_defects()}")
    print(f"Unique dissonant w/ consonant inversion: "
          f"{analyzer.unique_dissonant_with_consonant_inversion()}")
    print(f"{{3,4}} generates Z/12Z: {analyzer.generates_all({3, 4})}")
    print(f"Consonant sum mod 12: {analyzer.consonant_sum()}")

    print("\n=== Counterpoint Category ===")
    cat = CounterpointCategory(analyzer)
    counts = cat.count_morphisms()

    print("Morphism counts:")
    for i in cat.objects:
        for j in cat.objects:
            print(f"  Hom({i},{j}): {counts[(i,j)]} morphisms")

    print(f"\nIs thin? {cat.is_thin()}")
    print("(Expected: NO — there are many voice leadings between intervals)")

    print("\nTransition matrix (morphism counts):")
    matrix = cat.transition_matrix()
    print("     " + "  ".join(f"{j:3d}" for j in cat.objects))
    for i, row in zip(cat.objects, matrix):
        print(f"  {i}: " + "  ".join(f"{c:3d}" for c in row))

    print("\n=== Tension Poset ===")
    poset = TensionPoset()
    print(f"Fiber sizes: {poset.fiber_sizes()}")
    print(f"Hasse diagram: {poset.hasse_diagram()}")
    print("Structure: ordinal sum 1 + 1 + 4")


if __name__ == "__main__":
    main()
