#!/usr/bin/env python3
"""
Algorithms for Heegner number analysis and the Rabinowitz criterion.

Type-hinted implementations of key algorithms connecting 163, Heegner numbers,
prime-generating polynomials, and near-integer phenomena.
"""

from typing import List, Tuple, Optional
import math


# ============================================================
# Core Definitions
# ============================================================

HEEGNER_NUMBERS: List[int] = [1, 2, 3, 7, 11, 19, 43, 67, 163]
HEEGNER_MOD3: List[int] = [d for d in HEEGNER_NUMBERS if d % 4 == 3]


def is_prime(n: int) -> bool:
    """Primality test using trial division."""
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


# ============================================================
# Algorithm 1: Rabinowitz Polynomial Analysis
# ============================================================

def rabinowitz_constant(d: int) -> int:
    """
    Given a Heegner number d ≡ 3 (mod 4), compute the Rabinowitz constant p
    such that x² + x + p generates primes for x = 0, ..., p-2.

    The discriminant of x² + x + p is 1 - 4p = -d, so p = (d+1)/4.
    """
    assert d % 4 == 3, f"{d} is not ≡ 3 (mod 4)"
    return (d + 1) // 4


def euler_polynomial(x: int, p: int = 41) -> int:
    """Evaluate x² + x + p (generalized Euler polynomial)."""
    return x * x + x + p


def prime_generation_length(p: int) -> int:
    """
    Count consecutive primes generated by x² + x + p starting from x = 0.
    Returns the number of consecutive prime values.
    """
    count = 0
    for x in range(p):  # Rabinowitz boundary: f(p-1) = p²
        val = euler_polynomial(x, p)
        if is_prime(val):
            count += 1
        else:
            break
    return count


def analyze_rabinowitz_polynomials() -> List[Tuple[int, int, int]]:
    """
    Analyze all Rabinowitz polynomials corresponding to Heegner numbers.

    Returns list of (d, p, prime_count) tuples where:
    - d is the Heegner number
    - p is the Rabinowitz constant
    - prime_count is the number of consecutive primes generated
    """
    results = []
    for d in HEEGNER_MOD3:
        p = rabinowitz_constant(d)
        if p >= 2:
            count = prime_generation_length(p)
            results.append((d, p, count))
    return results


# ============================================================
# Algorithm 2: Near-Integer Quality Measurement
# ============================================================

def near_integer_quality(d: int) -> Tuple[float, float, int]:
    """
    Compute the near-integer quality of e^(π√d).

    Returns:
        (value, distance_to_nearest_int, nearest_int)
    """
    val = math.exp(math.pi * math.sqrt(d))
    nearest = round(val)
    dist = abs(val - nearest)
    return (val, dist, nearest)


def rank_near_integer_quality(max_d: int = 200) -> List[Tuple[int, float]]:
    """
    Rank all integers d from 1 to max_d by how close e^(π√d) is
    to an integer.

    Returns sorted list of (d, distance) from closest to farthest.
    """
    results = []
    for d in range(1, max_d + 1):
        try:
            _, dist, _ = near_integer_quality(d)
            results.append((d, dist))
        except OverflowError:
            break
    results.sort(key=lambda x: x[1])
    return results


# ============================================================
# Algorithm 3: Quadratic Form Class Number Estimation
# ============================================================

def reduced_forms(D: int) -> List[Tuple[int, int, int]]:
    """
    Find all reduced binary quadratic forms of discriminant D < 0.

    A form ax² + bxy + cy² with discriminant D = b² - 4ac is reduced if:
    - |b| ≤ a ≤ c
    - if |b| = a or a = c, then b ≥ 0

    The number of reduced forms equals the class number h(D).
    """
    assert D < 0, "Discriminant must be negative"
    assert D % 4 in (0, 1), f"D = {D} is not a discriminant (D mod 4 = {D % 4})"

    forms = []
    # a ranges from 1 to sqrt(-D/3)
    a_max = int(math.sqrt(-D / 3)) + 1

    for a in range(1, a_max + 1):
        for b in range(-a, a + 1):
            if (b * b - D) % (4 * a) == 0:
                c = (b * b - D) // (4 * a)
                if c >= a:
                    # Check reduced form conditions
                    if abs(b) <= a and a <= c:
                        if (abs(b) == a or a == c) and b < 0:
                            continue
                        forms.append((a, b, c))

    return forms


def class_number(d: int) -> int:
    """
    Compute the class number h(-d) for a fundamental discriminant -d.

    For d ≡ 3 (mod 4), the discriminant is D = -d.
    For d ≡ 1, 2 (mod 4), the discriminant is D = -4d.
    """
    if d % 4 == 3:
        D = -d
    else:
        D = -4 * d
    return len(reduced_forms(D))


def verify_heegner_class_numbers() -> List[Tuple[int, int]]:
    """
    Verify that all Heegner numbers have class number 1.
    Returns list of (d, h(-d)) pairs.
    """
    results = []
    for d in HEEGNER_NUMBERS:
        h = class_number(d)
        results.append((d, h))
    return results


# ============================================================
# Algorithm 4: j-Invariant Approximation
# ============================================================

def j_invariant_approximation(d: int) -> Tuple[float, float]:
    """
    For a Heegner number d, compute:
    1. The approximation e^(π√d)
    2. The theoretical value from the j-invariant

    For d ≡ 3 (mod 4), j((1+√(-d))/2) is an algebraic integer,
    and e^(π√d) ≈ -j + 744 (for large d).
    """
    # Known j-invariant values for Heegner numbers
    j_values = {
        3: 0,
        7: -3375,
        11: -32768,
        19: -884736,
        43: -884736000,
        67: -147197952000,
        163: -262537412640768000
    }

    exp_val = math.exp(math.pi * math.sqrt(d))
    j_val = j_values.get(d, None)

    if j_val is not None:
        theoretical = abs(j_val) + 744
        return (exp_val, float(theoretical))
    return (exp_val, float('nan'))


# ============================================================
# Main Demo
# ============================================================

if __name__ == "__main__":
    print("=== Rabinowitz Polynomial Analysis ===")
    for d, p, count in analyze_rabinowitz_polynomials():
        print(f"  d={d:>3}, p={p:>2}: {count} consecutive primes "
              f"(x² + x + {p}, x=0..{count-1})")

    print("\n=== Class Number Verification ===")
    for d, h in verify_heegner_class_numbers():
        status = "✓" if h == 1 else "✗"
        print(f"  {status} h(-{d}) = {h}")

    print("\n=== Near-Integer Quality (top 15) ===")
    for d, dist in rank_near_integer_quality(100)[:15]:
        marker = " ← HEEGNER" if d in HEEGNER_NUMBERS else ""
        print(f"  d={d:>3}: distance = {dist:.6e}{marker}")

    print("\n=== j-Invariant Connection ===")
    for d in HEEGNER_MOD3:
        exp_val, theory = j_invariant_approximation(d)
        print(f"  d={d:>3}: e^(π√d) ≈ {exp_val:.2f}, "
              f"|j| + 744 = {theory:.0f}")
