"""
Demo: Galois Theory of Cellular Automata

Demonstrates the key findings from the research on reversible
elementary cellular automata and their group structure.
"""

from algorithms import (
    wolfram_rule, global_map, is_bijective_on_size,
    find_reversible_rules, orbit, orbit_period,
    reversibility_index, composition_group_order,
    classify_single_input
)
from itertools import product


def demo_reversible_classification():
    """Demo 1: Identify all 6 reversible elementary CA rules."""
    print("=" * 60)
    print("DEMO 1: Reversible Elementary CA Classification")
    print("=" * 60)
    print()
    print("Testing all 256 elementary CA rules for reversibility")
    print("on periodic configurations of various sizes...\n")
    
    # Test for n = 5, 6, 7
    results = {}
    for n in [5, 6, 7]:
        rev = find_reversible_rules(n)
        results[n] = set(rev)
        print(f"  n = {n}: reversible rules = {rev}")
    
    # The intersection across all tested sizes
    common = results[5] & results[6] & results[7]
    print(f"\n  Common reversible rules: {sorted(common)}")
    print(f"  Expected: [15, 51, 85, 170, 204, 240]")
    
    print("\nClassification of reversible rules:")
    for r in sorted(common):
        info = classify_single_input(r)
        print(f"  Rule {r:3d}: {info}")
    
    print()


def demo_orbit_structure():
    """Demo 2: Orbit structure under reversible vs non-reversible rules."""
    print("=" * 60)
    print("DEMO 2: Orbit Structure")
    print("=" * 60)
    print()
    
    n = 6
    config = (True, False, True, False, True, False)
    
    print(f"Configuration: {config_to_str(config)}")
    print(f"Configuration size: {n}\n")
    
    # Reversible rule: Rule 170 (left shift)
    rule_170 = wolfram_rule(170)
    orb = orbit(rule_170, config)
    period = orbit_period(rule_170, config)
    print(f"Rule 170 (left shift):")
    print(f"  Orbit period: {period}")
    for i, c in enumerate(orb[:min(8, len(orb))]):
        print(f"    t={i}: {config_to_str(c)}")
    
    print()
    
    # Reversible rule: Rule 51 (complement)
    rule_51 = wolfram_rule(51)
    period = orbit_period(rule_51, config)
    print(f"Rule 51 (complement):")
    print(f"  Orbit period: {period}")
    orb = orbit(rule_51, config)
    for i, c in enumerate(orb[:4]):
        print(f"    t={i}: {config_to_str(c)}")
    
    print()
    
    # Non-reversible rule: Rule 30
    rule_30 = wolfram_rule(30)
    print(f"Rule 30 (non-reversible, chaotic):")
    current = config
    seen = set()
    for t in range(20):
        if current in seen:
            print(f"    t={t}: {config_to_str(current)} ← CYCLE DETECTED")
            break
        seen.add(current)
        if t < 8:
            print(f"    t={t}: {config_to_str(current)}")
        current = global_map(rule_30, current)
    
    print()


def demo_group_structure():
    """Demo 3: Group structure of reversible CA compositions."""
    print("=" * 60)
    print("DEMO 3: Reversibility Group Structure")
    print("=" * 60)
    print()
    
    # For small n, compute the group generated by the 6 reversible rules
    reversible_rules = [wolfram_rule(r) for r in [15, 51, 85, 170, 204, 240]]
    
    for n in [3, 4, 5, 6]:
        order = composition_group_order(reversible_rules, n)
        print(f"  n = {n}: |G| = {order} (expected: 2n = {2*n})")
    
    print()
    print("The group is Z/nZ × Z/2Z (cyclic shifts × complement)")
    print("  - Z/nZ generated by the left shift (Rule 170)")
    print("  - Z/2Z generated by the complement (Rule 51)")
    print("  - These commute: shift ∘ complement = complement ∘ shift")
    
    print()
    
    # Verify commutativity
    n = 5
    rule_170 = wolfram_rule(170)
    rule_51 = wolfram_rule(51)
    
    print(f"Verifying commutativity (n={n}):")
    all_configs = list(product([False, True], repeat=n))
    commutes = all(
        global_map(rule_170, global_map(rule_51, c)) ==
        global_map(rule_51, global_map(rule_170, c))
        for c in all_configs
    )
    print(f"  shift ∘ complement = complement ∘ shift: {commutes}")
    
    print()


def demo_reversibility_index():
    """Demo 4: Reversibility index as a measure of irreversibility."""
    print("=" * 60)
    print("DEMO 4: Reversibility Index")
    print("=" * 60)
    print()
    
    n = 5
    print(f"Reversibility index for configurations of size {n}:")
    print(f"  (0 = fully reversible, higher = more info loss)\n")
    
    rules_to_test = [
        (0,   "constant zero"),
        (15,  "complement right shift"),
        (30,  "chaotic (Wolfram's favorite)"),
        (51,  "complement"),
        (85,  "complement left shift"),
        (90,  "XOR rule"),
        (110, "Turing-complete"),
        (150, "XOR variant"),
        (170, "left shift"),
        (204, "identity"),
        (240, "right shift"),
    ]
    
    for rule_num, description in rules_to_test:
        idx = reversibility_index(wolfram_rule(rule_num), n)
        rev = "✓ REVERSIBLE" if idx == 0 else f"  index = {idx}"
        print(f"  Rule {rule_num:3d} ({description:30s}): {rev}")
    
    print()


def demo_conjecture_test():
    """Demo 5: Test the Universal Reversibility Classification Conjecture."""
    print("=" * 60)
    print("DEMO 5: Universal Reversibility Conjecture")
    print("=" * 60)
    print()
    
    expected_universal = {15, 51, 85, 170, 204, 240}
    
    print("Reversible rules for each configuration size:")
    all_reversible = set(range(256))
    for n in range(3, 12):
        rev = set(find_reversible_rules(n))
        all_reversible &= rev
        extra = rev - expected_universal
        suffix = f"  (extra: {sorted(extra)})" if extra else ""
        print(f"  n = {n:2d}: {len(rev):2d} reversible rules{suffix}")
    
    print(f"\n  Intersection (universally reversible): {sorted(all_reversible)}")
    print(f"  Expected (single-input rules):          {sorted(expected_universal)}")
    match = all_reversible == expected_universal
    print(f"  Match: {match}")
    
    print()
    print("KEY INSIGHT: Some rules (e.g., Rule 150 = XOR) are reversible")
    print("only for certain n (odd n for XOR). The UNIVERSALLY reversible")
    print("rules — those bijective for ALL n — are exactly the 6 single-input rules.")
    print("This is the corrected conjecture, with forward direction proved in Lean.")
    print()


def config_to_str(config: tuple) -> str:
    """Pretty-print a binary configuration."""
    return "".join("█" if b else "░" for b in config)


if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("  GALOIS THEORY OF CELLULAR AUTOMATA")
    print("  Reversible Dynamics Demo")
    print("=" * 60 + "\n")
    
    demo_reversible_classification()
    demo_orbit_structure()
    demo_group_structure()
    demo_reversibility_index()
    demo_conjecture_test()
    
    print("=" * 60)
    print("  All demos complete.")
    print("=" * 60)


"""
Visualization: Spacetime Diagrams of Reversible vs Non-Reversible CAs

Creates spacetime diagrams showing how configurations evolve under
reversible and non-reversible cellular automata rules.
"""

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
from itertools import product


def wolfram_rule(number: int):
    bits = [(number >> i) & 1 == 1 for i in range(8)]
    def rule(left: bool, center: bool, right: bool) -> bool:
        index = (int(left) << 2) | (int(center) << 1) | int(right)
        return bits[index]
    return rule


def global_map(rule, config: tuple) -> tuple:
    n = len(config)
    return tuple(
        rule(config[(i - 1) % n], config[i], config[(i + 1) % n])
        for i in range(n)
    )


def evolve_spacetime(rule, initial: tuple, steps: int) -> np.ndarray:
    n = len(initial)
    grid = np.zeros((steps, n), dtype=int)
    grid[0] = [int(b) for b in initial]
    current = initial
    for t in range(1, steps):
        current = global_map(rule, current)
        grid[t] = [int(b) for b in current]
    return grid


def main():
    n = 40
    steps = 60
    
    # Random-ish initial condition
    np.random.seed(42)
    initial = tuple(bool(x) for x in np.random.randint(0, 2, n))
    
    rules_info = [
        (204, "Rule 204 (Identity) — Reversible"),
        (170, "Rule 170 (Left Shift) — Reversible"),
        (51,  "Rule 51 (Complement) — Reversible"),
        (15,  "Rule 15 (¬Left) — Reversible"),
        (30,  "Rule 30 (Chaotic) — NOT Reversible"),
        (110, "Rule 110 (Turing-Complete) — NOT Reversible"),
    ]
    
    fig, axes = plt.subplots(2, 3, figsize=(14, 8))
    fig.suptitle("Spacetime Diagrams: Reversible vs Non-Reversible Elementary CAs",
                 fontsize=14, fontweight='bold')
    
    cmap = mcolors.ListedColormap(['#FFFFFF', '#2C3E50'])
    
    for idx, (rule_num, title) in enumerate(rules_info):
        ax = axes[idx // 3][idx % 3]
        rule = wolfram_rule(rule_num)
        grid = evolve_spacetime(rule, initial, steps)
        
        ax.imshow(grid, cmap=cmap, aspect='auto', interpolation='nearest')
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("Cell position")
        ax.set_ylabel("Time step")
        
        # Color border green for reversible, red for not
        color = '#27AE60' if rule_num in {15, 51, 85, 170, 204, 240} else '#E74C3C'
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(2.5)
    
    plt.tight_layout()
    plt.savefig("ca_spacetime_diagrams.png", dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved: ca_spacetime_diagrams.png")


if __name__ == "__main__":
    main()


"""
Visualization: Group Structure of Reversible Elementary CAs

Shows the Cayley graph and multiplication table of the reversibility
group G = Z/nZ × Z/2Z for small configuration sizes.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from itertools import product


def wolfram_rule(number: int):
    bits = [(number >> i) & 1 == 1 for i in range(8)]
    def rule(left: bool, center: bool, right: bool) -> bool:
        index = (int(left) << 2) | (int(center) << 1) | int(right)
        return bits[index]
    return rule


def global_map(rule, config: tuple) -> tuple:
    n = len(config)
    return tuple(
        rule(config[(i - 1) % n], config[i], config[(i + 1) % n])
        for i in range(n)
    )


def config_perm_key(rule, n: int) -> tuple:
    all_configs = sorted(product([False, True], repeat=n))
    return tuple(all_configs.index(global_map(rule, c)) for c in all_configs)


def compose_perms(p1: tuple, p2: tuple) -> tuple:
    return tuple(p1[p2[i]] for i in range(len(p1)))


def main():
    n = 5
    
    # Get permutations for the 6 reversible rules
    rules = {
        204: "id",
        170: "σ",
        240: "σ⁻¹",
        51:  "¬",
        85:  "σ¬",
        15:  "σ⁻¹¬",
    }
    
    rule_perms = {}
    for rule_num, name in rules.items():
        rule = wolfram_rule(rule_num)
        rule_perms[name] = config_perm_key(rule, n)
    
    # Generate the full group by composition
    identity = rule_perms["id"]
    sigma = rule_perms["σ"]
    neg = rule_perms["¬"]
    
    # Build group elements as powers of sigma and neg
    group_elements = {}
    current = identity
    for k in range(n):
        group_elements[f"σ^{k}"] = current
        group_elements[f"σ^{k}·¬"] = compose_perms(neg, current)
        # Compose with sigma
        current = compose_perms(sigma, current)
    
    # Verify group order
    print(f"Configuration size n = {n}")
    print(f"Group order: {len(group_elements)} (expected: {2*n})")
    
    # Create multiplication table for the 6 reversible rule generators
    gen_names = ["id", "σ", "σ⁻¹", "¬", "σ¬", "σ⁻¹¬"]
    gen_perms = [rule_perms[name] for name in gen_names]
    
    # Find which generator each product equals
    perm_to_name = {rule_perms[name]: name for name in gen_names}
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # Plot 1: Multiplication table
    ax1 = axes[0]
    table_data = []
    table_colors = []
    color_map = {
        "id": 0, "σ": 1, "σ⁻¹": 2, "¬": 3, "σ¬": 4, "σ⁻¹¬": 5
    }
    
    for i, name_i in enumerate(gen_names):
        row = []
        color_row = []
        for j, name_j in enumerate(gen_names):
            prod = compose_perms(gen_perms[i], gen_perms[j])
            prod_name = perm_to_name.get(prod, "?")
            row.append(prod_name)
            color_row.append(color_map.get(prod_name, -1))
        table_data.append(row)
        table_colors.append(color_row)
    
    color_array = np.array(table_colors, dtype=float)
    cmap = plt.cm.Set3
    
    ax1.imshow(color_array, cmap=cmap, vmin=0, vmax=5, aspect='equal')
    
    for i in range(len(gen_names)):
        for j in range(len(gen_names)):
            ax1.text(j, i, table_data[i][j], ha='center', va='center',
                     fontsize=9, fontweight='bold')
    
    ax1.set_xticks(range(len(gen_names)))
    ax1.set_xticklabels(gen_names, fontsize=9)
    ax1.set_yticks(range(len(gen_names)))
    ax1.set_yticklabels(gen_names, fontsize=9)
    ax1.set_xlabel("Right operand")
    ax1.set_ylabel("Left operand")
    ax1.set_title(f"Composition Table of Reversible ECAs\n(n={n}, restricted to 6 generators)")
    
    # Plot 2: Group order vs configuration size
    ax2 = axes[1]
    sizes = list(range(3, 12))
    orders = []
    
    for sz in sizes:
        all_configs = list(product([False, True], repeat=sz))
        config_to_idx = {c: i for i, c in enumerate(all_configs)}
        
        def to_perm(rule_num):
            rule = wolfram_rule(rule_num)
            return tuple(config_to_idx[global_map(rule, c)] for c in all_configs)
        
        gens = [to_perm(r) for r in [170, 51]]
        identity_p = tuple(range(len(all_configs)))
        
        seen = {identity_p}
        frontier = [identity_p]
        while frontier:
            new_frontier = []
            for p in frontier:
                for g in gens:
                    # Also use inverse of g
                    inv_g = [0] * len(g)
                    for ii, gi in enumerate(g):
                        inv_g[gi] = ii
                    inv_g = tuple(inv_g)
                    
                    for h in [g, inv_g]:
                        comp = compose_perms(h, p)
                        if comp not in seen:
                            seen.add(comp)
                            new_frontier.append(comp)
            frontier = new_frontier
        
        orders.append(len(seen))
    
    ax2.plot(sizes, orders, 'bo-', markersize=8, linewidth=2, label='|G(n)| (computed)')
    ax2.plot(sizes, [2*s for s in sizes], 'r--', linewidth=1.5, label='2n (predicted)')
    ax2.set_xlabel("Configuration size n")
    ax2.set_ylabel("Group order |G|")
    ax2.set_title("Reversibility Group Order vs Configuration Size")
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig("group_structure.png", dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved: group_structure.png")


if __name__ == "__main__":
    main()


"""
Visualization: Reversibility Landscape of All 256 Elementary CA Rules

Creates a heatmap showing the reversibility index of each rule
across different configuration sizes, revealing which rules are
reversible and how irreversibility scales.
"""

import matplotlib.pyplot as plt
import numpy as np
from itertools import product


def wolfram_rule(number: int):
    bits = [(number >> i) & 1 == 1 for i in range(8)]
    def rule(left: bool, center: bool, right: bool) -> bool:
        index = (int(left) << 2) | (int(center) << 1) | int(right)
        return bits[index]
    return rule


def global_map(rule, config: tuple) -> tuple:
    n = len(config)
    return tuple(
        rule(config[(i - 1) % n], config[i], config[(i + 1) % n])
        for i in range(n)
    )


def reversibility_index(rule, n: int) -> int:
    all_configs = list(product([False, True], repeat=n))
    image_count = {}
    for config in all_configs:
        img = global_map(rule, config)
        image_count[img] = image_count.get(img, 0) + 1
    return sum(c for c in image_count.values() if c > 1)


def main():
    sizes = [3, 4, 5, 6, 7]
    n_rules = 256
    
    # Compute reversibility index for each rule and size
    data = np.zeros((n_rules, len(sizes)))
    
    print("Computing reversibility indices...")
    for j, n in enumerate(sizes):
        print(f"  Size n={n}...")
        for r in range(n_rules):
            rule = wolfram_rule(r)
            data[r, j] = reversibility_index(rule, n)
    
    # Normalize each column for visualization
    data_norm = data.copy()
    for j in range(len(sizes)):
        mx = data_norm[:, j].max()
        if mx > 0:
            data_norm[:, j] /= mx
    
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))
    
    # Plot 1: Heatmap of raw reversibility index
    ax1 = axes[0]
    im = ax1.imshow(data.T, aspect='auto', cmap='YlOrRd', interpolation='nearest')
    ax1.set_xlabel("Rule Number (0-255)")
    ax1.set_ylabel("Configuration Size n")
    ax1.set_yticks(range(len(sizes)))
    ax1.set_yticklabels([str(s) for s in sizes])
    ax1.set_title("Reversibility Index\n(0 = reversible, higher = more info loss)")
    plt.colorbar(im, ax=ax1, label="Reversibility Index")
    
    # Mark the 6 reversible rules
    reversible_rules = [15, 51, 85, 170, 204, 240]
    for r in reversible_rules:
        ax1.axvline(x=r, color='#27AE60', alpha=0.6, linewidth=0.8, linestyle='--')
    
    # Plot 2: Bar chart of reversibility index at n=6
    ax2 = axes[1]
    n_idx = sizes.index(6)
    colors = ['#27AE60' if data[r, n_idx] == 0 else '#E74C3C' for r in range(n_rules)]
    ax2.bar(range(n_rules), data[:, n_idx], color=colors, width=1.0, edgecolor='none')
    ax2.set_xlabel("Rule Number")
    ax2.set_ylabel("Reversibility Index")
    ax2.set_title(f"Reversibility Index at n={sizes[n_idx]}\nGreen = reversible, Red = non-reversible")
    ax2.set_xlim(-1, 256)
    
    # Annotate reversible rules
    for r in reversible_rules:
        ax2.annotate(f'{r}', xy=(r, 0), xytext=(r, -3),
                     fontsize=7, ha='center', color='#27AE60', fontweight='bold')
    
    plt.tight_layout()
    plt.savefig("reversibility_landscape.png", dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved: reversibility_landscape.png")


if __name__ == "__main__":
    main()
