#!/usr/bin/env python3
"""
Counterpoint Category Theory — Numerical Demonstrations

Demonstrates the algebraic structure of first-species counterpoint:
consonance classification, complement duality, generation dichotomy,
voice-leading quiver, and multiplicative rigidity.
"""

from math import gcd
from itertools import product

# ============================================================
# Core Definitions
# ============================================================

CHROMATIC = list(range(12))
CONSONANT = {0, 3, 4, 7, 8, 9}
PERFECT = {0, 7}
IMPERFECT = {3, 4, 8, 9}
DISSONANT = {1, 2, 5, 6, 10, 11}

INTERVAL_NAMES = {
    0: "Unison", 1: "m2", 2: "M2", 3: "m3", 4: "M3",
    5: "P4", 6: "Tritone", 7: "P5", 8: "m6", 9: "M6",
    10: "m7", 11: "M7"
}

TENSION = {0: 0, 7: 1, 4: 2, 9: 2, 3: 3, 8: 3}


def complement(n: int) -> int:
    """Interval complement: n -> -n mod 12."""
    return (12 - n) % 12


def is_vl_allowed(i: int, j: int) -> bool:
    """Voice-leading transition predicate."""
    if i not in CONSONANT or j not in CONSONANT:
        return False
    if i == j:
        return i in IMPERFECT
    return True


def subgroup_generated(generators: set[int], n: int = 12) -> set[int]:
    """Compute the additive subgroup of Z/nZ generated by a set."""
    subgroup = {0}
    frontier = set(generators)
    while frontier:
        new = set()
        for g in frontier:
            for s in list(subgroup):
                elem = (s + g) % n
                if elem not in subgroup:
                    new.add(elem)
                elem = (s - g) % n
                if elem not in subgroup:
                    new.add(elem)
        subgroup |= new
        frontier = new
    return subgroup


# ============================================================
# Demo 1: Consonance Classification
# ============================================================
print("=" * 60)
print("DEMO 1: Consonance Classification")
print("=" * 60)
for n in CHROMATIC:
    status = "CONSONANT" if n in CONSONANT else "dissonant"
    kind = ""
    if n in PERFECT:
        kind = " (perfect)"
    elif n in IMPERFECT:
        kind = " (imperfect)"
    print(f"  {n:2d} semitones ({INTERVAL_NAMES[n]:>8s}): {status}{kind}")
print(f"\nConsonant count: {len(CONSONANT)}")
print(f"Perfect count:   {len(PERFECT)}")
print(f"Imperfect count: {len(IMPERFECT)}")
print(f"Dissonant count: {len(DISSONANT)}")

# ============================================================
# Demo 2: Complement Duality
# ============================================================
print("\n" + "=" * 60)
print("DEMO 2: Complement Duality")
print("=" * 60)
print("\nComplement map on consonant intervals:")
for n in sorted(CONSONANT):
    c = complement(n)
    preserved = "✓" if c in CONSONANT else "✗ BREAKS!"
    print(f"  {INTERVAL_NAMES[n]:>8s} ({n}) -> {INTERVAL_NAMES[c]:>8s} ({c})  {preserved}")

print("\nComplement map on imperfect consonances:")
for n in sorted(IMPERFECT):
    c = complement(n)
    print(f"  {INTERVAL_NAMES[n]:>8s} ({n}) -> {INTERVAL_NAMES[c]:>8s} ({c})  {'✓ imperfect' if c in IMPERFECT else '✗'}")

breakers = [n for n in CONSONANT if complement(n) not in CONSONANT]
print(f"\nUnique complement-breaking element: {breakers} = {[INTERVAL_NAMES[b] for b in breakers]}")

# ============================================================
# Demo 3: Voice-Leading Quiver
# ============================================================
print("\n" + "=" * 60)
print("DEMO 3: Voice-Leading Quiver")
print("=" * 60)

edges = [(i, j) for i in sorted(CONSONANT) for j in sorted(CONSONANT) if is_vl_allowed(i, j)]
print(f"\nTotal edges: {len(edges)} (= 6×6 - 2 forbidden self-loops)")

print("\nTransition matrix (✓ = allowed, ✗ = forbidden):")
header = "     " + "  ".join(f"{INTERVAL_NAMES[j]:>4s}" for j in sorted(CONSONANT))
print(header)
for i in sorted(CONSONANT):
    row = f"{INTERVAL_NAMES[i]:>4s} "
    for j in sorted(CONSONANT):
        row += f"{'  ✓ ' if is_vl_allowed(i, j) else '  ✗ '}"
    print(row)

self_loops = [(i, i) for i in sorted(CONSONANT) if is_vl_allowed(i, i)]
forbidden_loops = [(i, i) for i in sorted(CONSONANT) if not is_vl_allowed(i, i)]
print(f"\nAllowed self-loops (imperfect): {[INTERVAL_NAMES[i] for i, _ in self_loops]}")
print(f"Forbidden self-loops (perfect): {[INTERVAL_NAMES[i] for i, _ in forbidden_loops]}")

# ============================================================
# Demo 4: Generation Dichotomy
# ============================================================
print("\n" + "=" * 60)
print("DEMO 4: Generation Dichotomy")
print("=" * 60)

imperfect_list = sorted(IMPERFECT)
print("\nSubgroups generated by pairs of imperfect consonances:")
for i in range(len(imperfect_list)):
    for j in range(i + 1, len(imperfect_list)):
        a, b = imperfect_list[i], imperfect_list[j]
        sg = subgroup_generated({a, b})
        is_comp = (a + b) % 12 == 0
        comp_str = "COMPLEMENTARY" if is_comp else "non-complement"
        gen_str = "FULL (all 12)" if len(sg) == 12 else f"PROPER ({len(sg)} elements: {sorted(sg)})"
        print(f"  {{{INTERVAL_NAMES[a]}, {INTERVAL_NAMES[b]}}} ({comp_str}): {gen_str}")

print("\nPattern: generates Z/12Z iff NOT complementary")

# ============================================================
# Demo 5: Multiplicative Rigidity
# ============================================================
print("\n" + "=" * 60)
print("DEMO 5: Multiplicative Rigidity")
print("=" * 60)

units = [k for k in range(12) if gcd(k, 12) == 1]
print(f"\nUnits of Z/12Z: {units}")

for k in units:
    images = {(k * n) % 12 for n in CONSONANT}
    preserves = images <= CONSONANT
    print(f"  k={k:2d}: consonant set maps to {sorted(images)}")
    print(f"         {'✓ preserves consonance' if preserves else '✗ DOES NOT preserve (e.g., ' + str([(n, (k*n)%12) for n in CONSONANT if (k*n)%12 not in CONSONANT][0]) + ' maps consonant to dissonant)'}")

# ============================================================
# Demo 6: Tension Ordering
# ============================================================
print("\n" + "=" * 60)
print("DEMO 6: Tension Ordering")
print("=" * 60)

for n in sorted(CONSONANT, key=lambda x: TENSION[x]):
    t = TENSION[n]
    par = "allowed" if n in IMPERFECT else "FORBIDDEN"
    print(f"  τ({INTERVAL_NAMES[n]:>8s}) = {t}  |  parallel motion: {par}")

print("\nCorrespondence: τ ≤ 1 ⟺ parallel forbidden")

# ============================================================
# Demo 7: Dissonance Adjacency
# ============================================================
print("\n" + "=" * 60)
print("DEMO 7: Dissonance Adjacency")
print("=" * 60)

for n in sorted(DISSONANT):
    neighbors = []
    if (n + 1) % 12 in CONSONANT:
        neighbors.append(f"{INTERVAL_NAMES[(n+1)%12]} (+1)")
    if (n - 1) % 12 in CONSONANT:
        neighbors.append(f"{INTERVAL_NAMES[(n-1)%12]} (-1)")
    print(f"  {INTERVAL_NAMES[n]:>8s} ({n}): adjacent to {', '.join(neighbors)}")

print("\nEvery dissonant interval is ≤1 semitone from a consonance.")
print("\n✅ All demonstrations complete.")


#!/usr/bin/env python3
"""
Visualization: Voice-Leading Quiver of First-Species Counterpoint

Draws the directed graph of allowed voice-leading transitions between
consonant intervals, with perfect and imperfect consonances distinguished
by color and self-loops highlighted.
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# Consonant intervals and their properties
CONSONANT = [0, 3, 4, 7, 8, 9]
PERFECT = {0, 7}
IMPERFECT = {3, 4, 8, 9}

NAMES = {0: "Unison\n(0)", 3: "m3\n(3)", 4: "M3\n(4)",
         7: "P5\n(7)", 8: "m6\n(8)", 9: "M6\n(9)"}

# Layout: arrange on a circle
n = len(CONSONANT)
angles = [2 * np.pi * i / n - np.pi / 2 for i in range(n)]
positions = {CONSONANT[i]: (1.5 * np.cos(angles[i]), 1.5 * np.sin(angles[i]))
             for i in range(n)}

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# ---- Panel 1: Full Voice-Leading Quiver ----
ax = axes[0]
ax.set_title("Voice-Leading Quiver\n(34 edges: 6×6 − 2 forbidden)", fontsize=13, fontweight='bold')
ax.set_xlim(-2.5, 2.5)
ax.set_ylim(-2.5, 2.5)
ax.set_aspect('equal')
ax.axis('off')

# Draw edges (cross-transitions)
for i in CONSONANT:
    for j in CONSONANT:
        if i == j:
            continue
        x1, y1 = positions[i]
        x2, y2 = positions[j]
        dx, dy = x2 - x1, y2 - y1
        length = np.sqrt(dx**2 + dy**2)
        # Shorten arrows to not overlap with nodes
        shrink = 0.35
        ax.annotate("", xy=(x2 - shrink * dx / length, y2 - shrink * dy / length),
                     xytext=(x1 + shrink * dx / length, y1 + shrink * dy / length),
                     arrowprops=dict(arrowstyle="->", color="#888888", lw=0.5,
                                     connectionstyle="arc3,rad=0.1"))

# Draw self-loops (only imperfect)
for i in IMPERFECT:
    x, y = positions[i]
    angle = np.arctan2(y, x)
    loop_x = x + 0.4 * np.cos(angle)
    loop_y = y + 0.4 * np.sin(angle)
    circle = plt.Circle((loop_x, loop_y), 0.2, fill=False,
                         edgecolor='#2ecc71', linewidth=2, linestyle='-')
    ax.add_patch(circle)

# Draw forbidden self-loops (perfect) with X marks
for i in PERFECT:
    x, y = positions[i]
    angle = np.arctan2(y, x)
    loop_x = x + 0.4 * np.cos(angle)
    loop_y = y + 0.4 * np.sin(angle)
    circle = plt.Circle((loop_x, loop_y), 0.2, fill=False,
                         edgecolor='#e74c3c', linewidth=2, linestyle='--')
    ax.add_patch(circle)
    ax.text(loop_x, loop_y, '✗', ha='center', va='center',
            fontsize=10, color='#e74c3c', fontweight='bold')

# Draw nodes
for i in CONSONANT:
    x, y = positions[i]
    color = '#e74c3c' if i in PERFECT else '#3498db'
    circle = plt.Circle((x, y), 0.3, facecolor=color, edgecolor='white',
                         linewidth=2, zorder=5)
    ax.add_patch(circle)
    ax.text(x, y, NAMES[i], ha='center', va='center',
            fontsize=8, color='white', fontweight='bold', zorder=6)

# Legend
perfect_patch = mpatches.Patch(color='#e74c3c', label='Perfect consonance')
imperfect_patch = mpatches.Patch(color='#3498db', label='Imperfect consonance')
ax.legend(handles=[perfect_patch, imperfect_patch], loc='lower right', fontsize=9)

# ---- Panel 2: Complement Structure ----
ax2 = axes[1]
ax2.set_title("Complement Duality\n(imperfect: closed; perfect: breaks at P4)", fontsize=13, fontweight='bold')
ax2.set_xlim(-3, 3)
ax2.set_ylim(-2.5, 2.5)
ax2.set_aspect('equal')
ax2.axis('off')

# Draw all 12 intervals on a circle
all_angles = [2 * np.pi * i / 12 - np.pi / 2 for i in range(12)]
all_pos = {i: (2 * np.cos(all_angles[i]), 2 * np.sin(all_angles[i])) for i in range(12)}

interval_names_short = {
    0: "U", 1: "m2", 2: "M2", 3: "m3", 4: "M3", 5: "P4",
    6: "TT", 7: "P5", 8: "m6", 9: "M6", 10: "m7", 11: "M7"
}

# Draw complement arrows
complement_pairs = [(3, 9), (4, 8)]  # imperfect pairs
for a, b in complement_pairs:
    x1, y1 = all_pos[a]
    x2, y2 = all_pos[b]
    ax2.annotate("", xy=(x2 * 0.85, y2 * 0.85), xytext=(x1 * 0.85, y1 * 0.85),
                 arrowprops=dict(arrowstyle="<->", color='#2ecc71', lw=2.5))

# Draw the broken complement pair (5, 7)
x1, y1 = all_pos[7]
x2, y2 = all_pos[5]
ax2.annotate("", xy=(x2 * 0.85, y2 * 0.85), xytext=(x1 * 0.85, y1 * 0.85),
             arrowprops=dict(arrowstyle="<->", color='#e74c3c', lw=2.5, linestyle='--'))

# Draw nodes
for i in range(12):
    x, y = all_pos[i]
    if i in PERFECT:
        color = '#e74c3c'
    elif i in IMPERFECT:
        color = '#3498db'
    elif i == 5:
        color = '#f39c12'  # highlight the breaking point
    else:
        color = '#bdc3c7'  # dissonant
    circle = plt.Circle((x, y), 0.25, facecolor=color, edgecolor='white',
                         linewidth=1.5, zorder=5)
    ax2.add_patch(circle)
    ax2.text(x, y, interval_names_short[i], ha='center', va='center',
            fontsize=7, color='white', fontweight='bold', zorder=6)

# Legend
from matplotlib.lines import Line2D
legend_elements = [
    mpatches.Patch(color='#e74c3c', label='Perfect consonance'),
    mpatches.Patch(color='#3498db', label='Imperfect consonance'),
    mpatches.Patch(color='#f39c12', label='P4 (breaking point)'),
    mpatches.Patch(color='#bdc3c7', label='Dissonant'),
    Line2D([0], [0], color='#2ecc71', lw=2.5, label='Complement (preserved)'),
    Line2D([0], [0], color='#e74c3c', lw=2.5, linestyle='--', label='Complement (broken)'),
]
ax2.legend(handles=legend_elements, loc='lower right', fontsize=7)

plt.tight_layout()
plt.savefig('counterpoint_quiver.png', dpi=150, bbox_inches='tight')
plt.savefig('counterpoint_quiver.svg', bbox_inches='tight')
print("Saved: counterpoint_quiver.png, counterpoint_quiver.svg")
