#!/usr/bin/env python3
"""
Counterpoint as Category Theory: Demonstrations

Shows the group-theoretic structure underlying first-species counterpoint
in twelve-tone equal temperament.
"""

from math import gcd

# === Core Definitions ===

INTERVAL_NAMES = {
    0: "P1 (unison)", 1: "m2", 2: "M2", 3: "m3 (minor third)",
    4: "M3 (major third)", 5: "P4 (perfect fourth)", 6: "TT (tritone)",
    7: "P5 (perfect fifth)", 8: "m6 (minor sixth)", 9: "M6 (major sixth)",
    10: "m7", 11: "M7"
}

CONSONANT = {0, 3, 4, 7, 8, 9}
PERFECT = {0, 7}
IMPERFECT = {3, 4, 8, 9}

def additive_order(k: int, n: int = 12) -> int:
    """Additive order of k in Z/nZ: smallest positive m with m*k ≡ 0 (mod n)."""
    if k % n == 0:
        return 1
    return n // gcd(n, k % n)

def cyclic_subgroup(k: int, n: int = 12) -> set[int]:
    """The cyclic subgroup generated by k in Z/nZ."""
    return {(m * k) % n for m in range(n)}

def complement(k: int, n: int = 12) -> int:
    """Intervallic complement: -k mod n."""
    return (-k) % n

# === Demonstration 1: The Perfect Consonance Characterization ===

print("=" * 70)
print("THEOREM: Perfect Consonance ↔ Extreme Additive Order")
print("=" * 70)
print()
print(f"{'Interval':<25} {'Semitones':<10} {'Order':<8} {'Subgroup':<20} {'Type':<12}")
print("-" * 75)

for i in sorted(CONSONANT):
    order = additive_order(i)
    subgrp = sorted(cyclic_subgroup(i))
    is_perfect = i in PERFECT
    typename = "PERFECT" if is_perfect else "imperfect"
    name = INTERVAL_NAMES[i]
    print(f"{name:<25} {i:<10} {order:<8} {str(subgrp):<20} {typename:<12}")

print()
print("Key insight: Perfect consonances have order 1 (trivial) or 12 (full group).")
print("Imperfect consonances have intermediate orders (3 or 4).")

# === Demonstration 2: The Complement Involution ===

print()
print("=" * 70)
print("THEOREM: Complement Preserves Imperfect Consonances")
print("=" * 70)
print()

for i in sorted(CONSONANT):
    comp = complement(i)
    name_i = INTERVAL_NAMES[i]
    name_c = INTERVAL_NAMES[comp]
    in_consonant = comp in CONSONANT
    status = "✓ consonant" if in_consonant else "✗ DISSONANT"
    print(f"  -{i} mod 12 = {comp}: {name_i} → {name_c}  [{status}]")

print()
print("The perfect fifth (7) is the UNIQUE consonant interval whose complement")
print("is dissonant. This explains the 'problem of the fourth' in music theory.")

# === Demonstration 3: The Transition Graph ===

print()
print("=" * 70)
print("THEOREM: Valid Transition Count = 34")
print("=" * 70)
print()

valid_count = 0
cross_count = 0
self_count = 0
forbidden = []

for src in sorted(CONSONANT):
    for tgt in sorted(CONSONANT):
        if src == tgt:
            if src not in PERFECT:
                valid_count += 1
                self_count += 1
            else:
                forbidden.append((src, tgt))
        else:
            valid_count += 1
            cross_count += 1

print(f"Cross-transitions (i ≠ j): {cross_count}")
print(f"Self-loops (parallel motion on imperfect): {self_count}")
print(f"Forbidden (parallel motion on perfect): {len(forbidden)} → {forbidden}")
print(f"Total valid transitions: {valid_count}")

# === Demonstration 4: The Subgroup Diamond ===

print()
print("=" * 70)
print("THE SUBGROUP DIAMOND LATTICE")
print("=" * 70)
print()

subgroups = {}
for i in sorted(CONSONANT):
    sg = frozenset(cyclic_subgroup(i))
    name = f"⟨{i}⟩"
    if sg not in subgroups:
        subgroups[sg] = []
    subgroups[sg].append(i)

print("Distinct subgroups generated by consonant intervals:")
for sg, generators in sorted(subgroups.items(), key=lambda x: len(x[0])):
    print(f"  {sorted(sg)} (generators: {generators}, order: {len(sg)})")

print()
print("Diamond structure:")
print("        Z/12Z = ⟨7⟩")
print("       /       \\")
print("   {0,3,6,9}  {0,4,8}")
print("   = ⟨3⟩=⟨9⟩  = ⟨4⟩=⟨8⟩")
print("       \\       /")
print("        {0} = ⟨0⟩")
print()
print("This is a 4-element diamond, NOT 12 elements as conjectured.")
print("The original conjecture about a 12-element poset is REFUTED.")

# === Demonstration 5: Rigidity ===

print()
print("=" * 70)
print("THEOREM: Consonance Rigidity under Aut(Z/12Z)")
print("=" * 70)
print()

units = [u for u in range(12) if gcd(u, 12) == 1]
print(f"Units of Z/12Z: {units}")
print()

for u in units:
    image = {(u * i) % 12 for i in CONSONANT}
    preserves = image == CONSONANT
    print(f"  u = {u}: {sorted(CONSONANT)} → {sorted(image)}  "
          f"{'PRESERVES' if preserves else 'BREAKS'}")

print()
print("Only u = 1 (identity) preserves the consonance set.")
print("The consonance structure has trivial automorphism group.")

# === Summary ===

print()
print("=" * 70)
print("SUMMARY OF FORMAL RESULTS (all verified in Lean 4)")
print("=" * 70)
print("""
1. perfect_iff_extreme_order: Perfect consonances ↔ order 1 or 12 in Z/12Z
2. perfect_fifth_unique_dissonant_complement: P5 is the unique consonance
   whose complement is dissonant (explains the 'problem of the fourth')
3. consonance_rigidity: Only the identity automorphism of Z/12Z preserves
   the consonance set (the structure is 'rigid')
4. three_four_incomparable: The subgroup diamond has incomparable middle
   elements, giving the lattice its characteristic shape
5. valid_transition_count = 34: Exactly 34 valid first-species transitions
6. self_transition_iff_imperfect: Parallel motion ↔ imperfect consonance
""")


#!/usr/bin/env python3
"""
Visualization: The Subgroup Diamond of Consonant Intervals

Shows the 4-element diamond lattice formed by cyclic subgroups generated
by consonant intervals in Z/12Z.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np


def draw_subgroup_diamond():
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 7))

    # === Left panel: The Diamond Lattice ===
    positions = {
        '{0}': (0, 0),
        '{0,3,6,9}': (-1.5, 1.5),
        '{0,4,8}': (1.5, 1.5),
        'Z/12Z': (0, 3),
    }

    labels = {
        '{0}': '⟨0⟩ = {0}\norder 1\n(Unison)',
        '{0,3,6,9}': '⟨3⟩ = ⟨9⟩ = {0,3,6,9}\norder 4\n(Dim. 7th chord)',
        '{0,4,8}': '⟨4⟩ = ⟨8⟩ = {0,4,8}\norder 3\n(Aug. triad)',
        'Z/12Z': '⟨7⟩ = Z/12Z\norder 12\n(Circle of fifths)',
    }

    colors = {
        '{0}': '#2196F3',
        '{0,3,6,9}': '#4CAF50',
        '{0,4,8}': '#FF9800',
        'Z/12Z': '#F44336',
    }

    # Draw edges
    edges = [
        ('{0}', '{0,3,6,9}'),
        ('{0}', '{0,4,8}'),
        ('{0,3,6,9}', 'Z/12Z'),
        ('{0,4,8}', 'Z/12Z'),
    ]

    for s, t in edges:
        xs = [positions[s][0], positions[t][0]]
        ys = [positions[s][1], positions[t][1]]
        ax1.plot(xs, ys, 'k-', linewidth=2, zorder=1)

    # Draw nodes
    for name, (x, y) in positions.items():
        circle = plt.Circle((x, y), 0.4, color=colors[name], zorder=2)
        ax1.add_patch(circle)
        ax1.text(x, y - 0.8, labels[name], ha='center', va='top', fontsize=8,
                fontweight='bold')

    ax1.set_xlim(-3, 3)
    ax1.set_ylim(-1.5, 4.5)
    ax1.set_aspect('equal')
    ax1.set_title('Subgroup Diamond of Consonant Intervals', fontsize=13,
                  fontweight='bold')
    ax1.text(0, -1.2, 'PERFECT consonances at extremes\nIMPERFECT consonances in the middle',
             ha='center', fontsize=9, style='italic', color='#666')
    ax1.axis('off')

    # === Right panel: The Consonance Wheel ===
    angles = np.linspace(0, 2 * np.pi, 12, endpoint=False)
    # Rotate so 0 is at top
    angles = np.pi / 2 - angles

    consonant = {0, 3, 4, 7, 8, 9}
    perfect = {0, 7}
    note_names = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

    radius = 2.0
    for i in range(12):
        x = radius * np.cos(angles[i])
        y = radius * np.sin(angles[i])

        if i in perfect:
            color = '#F44336'
            size = 300
            label_color = 'white'
        elif i in consonant:
            color = '#4CAF50'
            size = 250
            label_color = 'white'
        else:
            color = '#E0E0E0'
            size = 150
            label_color = 'black'

        ax2.scatter(x, y, s=size, c=color, zorder=3, edgecolors='black', linewidth=1)
        ax2.text(x, y, note_names[i], ha='center', va='center', fontsize=8,
                fontweight='bold', color=label_color, zorder=4)

        # Interval number outside
        ox = 1.2 * radius * np.cos(angles[i])
        oy = 1.2 * radius * np.sin(angles[i])
        ax2.text(ox, oy, str(i), ha='center', va='center', fontsize=7,
                color='#999')

    # Draw the complement anomaly: 7 -> 5
    x7 = radius * np.cos(angles[7])
    y7 = radius * np.sin(angles[7])
    x5 = radius * np.cos(angles[5])
    y5 = radius * np.sin(angles[5])
    ax2.annotate('', xy=(x5, y5), xytext=(x7, y7),
                arrowprops=dict(arrowstyle='->', color='red', lw=2,
                               connectionstyle='arc3,rad=0.3'))
    ax2.text((x7 + x5) / 2 - 0.5, (y7 + y5) / 2 + 0.3,
             'complement\nanomaly!', fontsize=8, color='red',
             ha='center', fontweight='bold')

    # Legend
    legend_elements = [
        mpatches.Patch(facecolor='#F44336', edgecolor='black', label='Perfect consonance'),
        mpatches.Patch(facecolor='#4CAF50', edgecolor='black', label='Imperfect consonance'),
        mpatches.Patch(facecolor='#E0E0E0', edgecolor='black', label='Dissonant'),
    ]
    ax2.legend(handles=legend_elements, loc='lower right', fontsize=8)

    ax2.set_xlim(-3.5, 3.5)
    ax2.set_ylim(-3.5, 3.5)
    ax2.set_aspect('equal')
    ax2.set_title('Chromatic Circle: Consonance Classification', fontsize=13,
                  fontweight='bold')
    ax2.axis('off')

    plt.tight_layout()
    plt.savefig('subgroup_diamond.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved subgroup_diamond.png")


def draw_transition_graph():
    fig, ax = plt.subplots(figsize=(8, 8))

    consonant = [0, 3, 4, 7, 8, 9]
    perfect = {0, 7}
    n = len(consonant)

    # Position consonances in a hexagon
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    angles = np.pi / 2 - angles
    radius = 2.5

    positions = {}
    interval_names = {0: 'P1', 3: 'm3', 4: 'M3', 7: 'P5', 8: 'm6', 9: 'M6'}

    for i, c in enumerate(consonant):
        x = radius * np.cos(angles[i])
        y = radius * np.sin(angles[i])
        positions[c] = (x, y)

    # Draw edges (all pairs)
    for i, src in enumerate(consonant):
        for j, tgt in enumerate(consonant):
            if src != tgt:
                xs, ys = positions[src]
                xt, yt = positions[tgt]
                # Slight curve for bidirectional
                dx, dy = xt - xs, yt - ys
                ax.annotate('', xy=(xt - 0.15 * dx, yt - 0.15 * dy),
                           xytext=(xs + 0.15 * dx, ys + 0.15 * dy),
                           arrowprops=dict(arrowstyle='->', color='#888',
                                          lw=0.8, alpha=0.4))

    # Self-loops on imperfect consonances
    for c in consonant:
        if c not in perfect:
            x, y = positions[c]
            angle = np.arctan2(y, x)
            loop_r = 0.4
            loop_x = x + loop_r * np.cos(angle)
            loop_y = y + loop_r * np.sin(angle)
            circle = plt.Circle((loop_x, loop_y), loop_r, fill=False,
                               color='#4CAF50', linewidth=2)
            ax.add_patch(circle)

    # Draw nodes
    for c in consonant:
        x, y = positions[c]
        color = '#F44336' if c in perfect else '#4CAF50'
        circle = plt.Circle((x, y), 0.35, color=color, zorder=5)
        ax.add_patch(circle)
        ax.text(x, y, f'{interval_names[c]}\n({c})', ha='center', va='center',
               fontsize=9, fontweight='bold', color='white', zorder=6)

    # Forbidden self-loops (X marks)
    for c in perfect:
        x, y = positions[c]
        angle = np.arctan2(y, x)
        fx = x + 0.7 * np.cos(angle)
        fy = y + 0.7 * np.sin(angle)
        ax.text(fx, fy, '✕', ha='center', va='center', fontsize=16,
               color='red', fontweight='bold', zorder=7)
        ax.text(fx, fy - 0.3, 'no ∥', ha='center', va='top', fontsize=7,
               color='red')

    ax.set_xlim(-4, 4)
    ax.set_ylim(-4, 4)
    ax.set_aspect('equal')
    ax.set_title('Counterpoint Transition Graph\n(34 valid transitions, 2 forbidden self-loops)',
                fontsize=13, fontweight='bold')
    ax.text(0, -3.8, 'Red = perfect consonance (no parallel self-loop)\n'
                     'Green = imperfect consonance (parallel self-loop allowed)',
           ha='center', fontsize=9, color='#666')
    ax.axis('off')

    plt.tight_layout()
    plt.savefig('transition_graph.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved transition_graph.png")


if __name__ == '__main__':
    draw_subgroup_diamond()
    draw_transition_graph()
