#!/usr/bin/env python3
"""
demo.py — The Periodic Table of Finite Groups

Demonstrates the chemical classification of finite groups by computing
structural invariants (center size, derived length, nilpotency class)
for all groups of small order.

Uses GAP-like computations implemented from scratch in Python.
"""

from itertools import product as cart_product
from math import gcd, log2
from collections import defaultdict


# === Group implementations ===

def cyclic_group(n):
    """Return the multiplication table of Z/nZ."""
    return [[( i + j) % n for j in range(n)] for i in range(n)]

def dihedral_group(n):
    """Return the multiplication table of D_n (order 2n).
    Elements: rotations r^i (0..n-1) and reflections s*r^i (n..2n-1)."""
    order = 2 * n
    table = [[0]*order for _ in range(order)]
    for a in range(order):
        for b in range(order):
            a_rot, a_ref = a < n, a >= n
            b_rot, b_ref = b < n, b >= n
            ai = a if a < n else a - n
            bi = b if b < n else b - n
            if a_rot and b_rot:
                table[a][b] = (ai + bi) % n
            elif a_rot and b_ref:
                table[a][b] = n + (ai + bi) % n
            elif a_ref and b_rot:
                table[a][b] = n + (ai - bi) % n
            else:  # both reflections
                table[a][b] = (ai - bi) % n
    return table

def direct_product(table1, table2):
    """Direct product of two groups given by multiplication tables."""
    n1, n2 = len(table1), len(table2)
    order = n1 * n2
    table = [[0]*order for _ in range(order)]
    for a in range(order):
        for b in range(order):
            a1, a2 = a // n2, a % n2
            b1, b2 = b // n2, b % n2
            table[a][b] = table1[a1][b1] * n2 + table2[a2][b2]
    return table


# === Group invariant computations ===

def compute_center(table):
    """Compute the center Z(G) as a list of element indices."""
    n = len(table)
    center = []
    for g in range(n):
        if all(table[g][h] == table[h][g] for h in range(n)):
            center.append(g)
    return center

def is_abelian(table):
    """Check if the group is abelian."""
    return len(compute_center(table)) == len(table)

def compute_commutator_subgroup(table):
    """Compute [G,G] = subgroup generated by all commutators [a,b] = a*b*a^{-1}*b^{-1}."""
    n = len(table)
    # Find inverses
    inv = [0]*n
    for i in range(n):
        for j in range(n):
            if table[i][j] == 0:
                inv[i] = j
                break

    # Compute all commutators
    commutators = set()
    for a in range(n):
        for b in range(n):
            # [a,b] = a*b*a^{-1}*b^{-1}
            ab = table[a][b]
            ainv_binv = table[inv[a]][inv[b]]
            comm = table[ab][ainv_binv]
            commutators.add(comm)

    # Generate the subgroup from commutators
    return generate_subgroup(table, commutators)

def generate_subgroup(table, generators):
    """Generate subgroup from a set of generators."""
    subgroup = set(generators)
    subgroup.add(0)  # identity
    changed = True
    while changed:
        changed = False
        new_elts = set()
        for a in subgroup:
            for b in subgroup:
                prod = table[a][b]
                if prod not in subgroup:
                    new_elts.add(prod)
                    changed = True
        subgroup.update(new_elts)
    return sorted(subgroup)

def compute_derived_series(table, max_depth=20):
    """Compute the derived series G = G^(0) ⊇ G^(1) ⊇ G^(2) ⊇ ..."""
    n = len(table)
    current = list(range(n))
    series = [current]

    for _ in range(max_depth):
        # Build restricted table for current subgroup
        sub_table = restriction_table(table, current)
        if sub_table is None:
            break
        comm = compute_commutator_subgroup(sub_table)
        # Map back to original indices
        next_sub = [current[i] for i in comm]
        if len(next_sub) == len(current):
            break  # stabilized
        current = next_sub
        series.append(current)
        if len(current) == 1:
            break
    return series

def restriction_table(table, elements):
    """Restrict multiplication table to a subset (must be a subgroup)."""
    idx_map = {e: i for i, e in enumerate(elements)}
    n = len(elements)
    sub_table = [[0]*n for _ in range(n)]
    for i, a in enumerate(elements):
        for j, b in enumerate(elements):
            prod = table[a][b]
            if prod not in idx_map:
                return None  # not closed
            sub_table[i][j] = idx_map[prod]
    return sub_table

def derived_length(table):
    """Compute the derived length of a solvable group."""
    series = compute_derived_series(table)
    if len(series[-1]) > 1:
        return None  # not solvable
    return len(series) - 1

def is_nilpotent_check(table, max_depth=20):
    """Check nilpotency by computing the lower central series."""
    n = len(table)
    current = list(range(n))

    for depth in range(max_depth):
        # Compute [G, current]
        inv = [0]*n
        for i in range(n):
            for j in range(n):
                if table[i][j] == 0:
                    inv[i] = j
                    break

        commutators = set()
        for a in range(n):
            for b in current:
                ab = table[a][b]
                ainv_binv = table[inv[a]][inv[b]]
                comm = table[ab][ainv_binv]
                commutators.add(comm)

        next_sub = generate_subgroup(table, commutators)
        if len(next_sub) == 1:
            return depth + 1  # nilpotency class
        if len(next_sub) == len(current):
            return None  # not nilpotent (stabilized without reaching trivial)
        current = next_sub

    return None

def classify_group(table):
    """Classify a group into its chemical series."""
    n = len(table)
    center = compute_center(table)
    ab = is_abelian(table)
    dl = derived_length(table)
    nilp = is_nilpotent_check(table)

    if n == 1:
        return "Vacuum"
    elif ab and is_cyclic(table):
        from sympy import isprime
        if isprime(n):
            return "Prime Element"
        return "Noble Gas"
    elif ab:
        return "Alkaline Earth"
    elif nilp is not None:
        return "Alkali Metal"
    elif dl is not None:
        return "Compound"
    else:
        return "Radioactive"

def is_cyclic(table):
    """Check if a group is cyclic."""
    n = len(table)
    for g in range(n):
        # Check if g generates the group
        seen = {0}
        current = g
        for _ in range(n):
            seen.add(current)
            current = table[current][g]
        if len(seen) == n:
            return True
    return False


# === Main Demo ===

def print_separator():
    print("=" * 70)

def main():
    print_separator()
    print("THE PERIODIC TABLE OF FINITE GROUPS")
    print("Chemistry Meets Algebra")
    print_separator()

    # Demo 1: Classify small groups
    print("\n1. CLASSIFICATION OF FAMILIAR GROUPS\n")

    groups = {
        "Z/2Z (cyclic, order 2)": cyclic_group(2),
        "Z/3Z (cyclic, order 3)": cyclic_group(3),
        "Z/4Z (cyclic, order 4)": cyclic_group(4),
        "Z/2Z × Z/2Z (Klein four)": direct_product(cyclic_group(2), cyclic_group(2)),
        "Z/5Z (cyclic, order 5)": cyclic_group(5),
        "Z/6Z (cyclic, order 6)": cyclic_group(6),
        "D₃ ≅ S₃ (dihedral, order 6)": dihedral_group(3),
        "Z/7Z (cyclic, order 7)": cyclic_group(7),
        "Z/8Z (cyclic, order 8)": cyclic_group(8),
        "D₄ (dihedral, order 8)": dihedral_group(4),
        "Z/2Z × Z/2Z × Z/2Z": direct_product(direct_product(cyclic_group(2), cyclic_group(2)), cyclic_group(2)),
    }

    print(f"{'Group':<30} {'Order':>5} {'|Z(G)|':>6} {'DerLen':>6} {'NilCl':>5} {'Series':<15}")
    print("-" * 70)

    for name, table in groups.items():
        n = len(table)
        center = compute_center(table)
        dl = derived_length(table)
        nilp = is_nilpotent_check(table)
        cyc = is_cyclic(table)
        ab = is_abelian(table)

        if n == 1:
            series = "Vacuum"
        elif ab and cyc:
            series = "Noble Gas"
        elif ab:
            series = "Alkaline Earth"
        elif nilp is not None:
            series = "Alkali Metal"
        elif dl is not None:
            series = "Compound"
        else:
            series = "Radioactive"

        dl_str = str(dl) if dl is not None else "∞"
        nilp_str = str(nilp) if nilp is not None else "—"
        print(f"{name:<30} {n:>5} {len(center):>6} {dl_str:>6} {nilp_str:>5} {series:<15}")

    # Demo 2: Center-valence product law
    print("\n" + "=" * 70)
    print("\n2. CENTER-VALENCE MULTIPLICATIVITY: |Z(G×H)| = |Z(G)|·|Z(H)|\n")

    test_pairs = [
        ("Z/3Z", cyclic_group(3), "Z/4Z", cyclic_group(4)),
        ("Z/2Z", cyclic_group(2), "D₃", dihedral_group(3)),
        ("D₃", dihedral_group(3), "D₄", dihedral_group(4)),
    ]

    for n1, t1, n2, t2 in test_pairs:
        c1 = len(compute_center(t1))
        c2 = len(compute_center(t2))
        prod = direct_product(t1, t2)
        c_prod = len(compute_center(prod))
        check = "✓" if c_prod == c1 * c2 else "✗"
        print(f"  |Z({n1} × {n2})| = {c_prod} = {c1} × {c2} = {c1*c2}  {check}")

    # Demo 3: Derived series spectroscopy
    print("\n" + "=" * 70)
    print("\n3. DERIVED SERIES SPECTROSCOPY\n")

    spectral_groups = {
        "Z/6Z": cyclic_group(6),
        "D₃ ≅ S₃": dihedral_group(3),
        "D₄": dihedral_group(4),
        "D₅": dihedral_group(5),
    }

    for name, table in spectral_groups.items():
        series = compute_derived_series(table)
        sizes = [len(s) for s in series]
        print(f"  {name:<15} Derived series sizes: {' ⊇ '.join(map(str, sizes))}")
        dl = len(series) - 1 if sizes[-1] == 1 else "∞"
        print(f"  {'':15} Derived length: {dl}")
        print()

    # Demo 4: The nilpotent-solvable hierarchy
    print("=" * 70)
    print("\n4. NILPOTENT-SOLVABLE HIERARCHY\n")
    print("  Abelian ⊂ Nilpotent ⊂ Solvable ⊂ All Groups\n")

    hierarchy_groups = {
        "Z/12Z": cyclic_group(12),
        "Z/2Z × Z/6Z": direct_product(cyclic_group(2), cyclic_group(6)),
        "D₃": dihedral_group(3),
        "D₄": dihedral_group(4),
        "D₅": dihedral_group(5),
        "D₆": dihedral_group(6),
    }

    print(f"  {'Group':<20} {'Abelian':>8} {'Nilpotent':>10} {'Solvable':>9} {'Class':>6}")
    print("  " + "-" * 55)
    for name, table in hierarchy_groups.items():
        ab = is_abelian(table)
        nilp = is_nilpotent_check(table)
        dl = derived_length(table)
        solv = dl is not None
        nilp_str = str(nilp) if nilp is not None else "—"
        print(f"  {name:<20} {'Yes' if ab else 'No':>8} {'Yes' if nilp else 'No':>10} {'Yes' if solv else 'No':>9} {nilp_str:>6}")

    # Demo 5: Abelian defect
    print("\n" + "=" * 70)
    print("\n5. ABELIAN DEFECT = |G| / |Z(G)| (Electronegativity Analogue)\n")

    for name, table in groups.items():
        n = len(table)
        center_size = len(compute_center(table))
        defect = n // center_size if center_size > 0 else "∞"
        print(f"  {name:<30} |G|={n}, |Z|={center_size}, defect={defect}")

    print("\n" + "=" * 70)
    print("\nCONCLUSION: The periodic table of finite groups organizes groups by")
    print("structural invariants — center valence, derived length, nilpotency class —")
    print("analogous to how atomic number, electron configuration, and valence")
    print("organize chemical elements.")
    print_separator()

if __name__ == "__main__":
    main()


#!/usr/bin/env python3
"""
Visualization: Derived Series Spectroscopy

Shows the "spectral fingerprints" of various groups — how their derived series
decays, analogous to emission spectra of chemical elements.
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np


def cyclic_group(n):
    return [[(i + j) % n for j in range(n)] for i in range(n)]

def dihedral_group(n):
    order = 2 * n
    table = [[0]*order for _ in range(order)]
    for a in range(order):
        for b in range(order):
            ai, bi = a % n, b % n
            if a < n and b < n: table[a][b] = (ai + bi) % n
            elif a < n: table[a][b] = n + (ai + bi) % n
            elif b < n: table[a][b] = n + (ai - bi) % n
            else: table[a][b] = (ai - bi) % n
    return table

def direct_product(t1, t2):
    n1, n2 = len(t1), len(t2)
    order = n1 * n2
    table = [[0]*order for _ in range(order)]
    for a in range(order):
        for b in range(order):
            table[a][b] = t1[a//n2][b//n2] * n2 + t2[a%n2][b%n2]
    return table

def compute_inverses(table):
    n = len(table)
    inv = [0]*n
    for i in range(n):
        for j in range(n):
            if table[i][j] == 0:
                inv[i] = j; break
    return inv

def generate_subgroup(table, generators):
    subgroup = set(generators) | {0}
    changed = True
    while changed:
        changed = False
        new = set()
        for a in subgroup:
            for b in subgroup:
                p = table[a][b]
                if p not in subgroup:
                    new.add(p); changed = True
        subgroup |= new
    return sorted(subgroup)

def derived_series_sizes(table, max_depth=15):
    n = len(table)
    current = list(range(n))
    sizes = [n]
    inv = compute_inverses(table)

    for _ in range(max_depth):
        comms = set()
        for a in current:
            for b in current:
                ab = table[a][b]
                ainv_binv = table[inv[a]][inv[b]]
                comms.add(table[ab][ainv_binv])
        next_sub = generate_subgroup(table, comms)
        if len(next_sub) == len(current): break
        current = next_sub
        sizes.append(len(current))
        if len(current) == 1: break

    return sizes


def main():
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # Groups to analyze
    groups = [
        ("Noble Gases (Cyclic)", [
            ("Z/6Z", cyclic_group(6)),
            ("Z/12Z", cyclic_group(12)),
            ("Z/15Z", cyclic_group(15)),
        ], axes[0, 0]),
        ("Alkaline Earths (Abelian non-cyclic)", [
            ("V₄ = Z₂×Z₂", direct_product(cyclic_group(2), cyclic_group(2))),
            ("Z₂×Z₄", direct_product(cyclic_group(2), cyclic_group(4))),
            ("Z₃×Z₃", direct_product(cyclic_group(3), cyclic_group(3))),
        ], axes[0, 1]),
        ("Alkali Metals (Nilpotent non-abelian)", [
            ("D₄", dihedral_group(4)),
            ("D₄×Z₂", direct_product(dihedral_group(4), cyclic_group(2))),
        ], axes[1, 0]),
        ("Compounds (Solvable non-nilpotent)", [
            ("D₃ ≅ S₃", dihedral_group(3)),
            ("D₅", dihedral_group(5)),
            ("D₇", dihedral_group(7)),
        ], axes[1, 1]),
    ]

    colors = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12', '#9b59b6']

    for title, group_list, ax in groups:
        for idx, (name, table) in enumerate(group_list):
            sizes = derived_series_sizes(table)
            steps = list(range(len(sizes)))
            color = colors[idx % len(colors)]

            # Plot as spectral lines
            ax.plot(steps, sizes, 'o-', color=color, label=name,
                    linewidth=2, markersize=8)

            # Add spectral "glow"
            for i, s in enumerate(sizes):
                ax.barh(s, 0.3, left=i-0.15, height=max(sizes)*0.02,
                        color=color, alpha=0.3)

        ax.set_xlabel("Derived Series Step", fontsize=10)
        ax.set_ylabel("Subgroup Order", fontsize=10)
        ax.set_title(title, fontsize=11, fontweight='bold')
        ax.legend(fontsize=8)
        ax.set_yscale('log')
        ax.grid(True, alpha=0.3)

    fig.suptitle("Derived Series Spectroscopy: Group Fingerprints",
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig("derived_spectra.png", dpi=150, bbox_inches='tight')
    print("Saved: derived_spectra.png")


if __name__ == "__main__":
    main()


#!/usr/bin/env python3
"""
Visualization: The Periodic Table of Finite Groups

Creates a color-coded periodic table showing groups organized by order (rows)
and chemical series (columns), with center-valence shown as cell intensity.
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np


def is_prime(n):
    if n < 2: return False
    if n < 4: return True
    if n % 2 == 0 or n % 3 == 0: return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0: return False
        i += 6
    return True


def factorize(n):
    factors = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors[d] = factors.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        factors[n] = factors.get(n, 0) + 1
    return factors


def num_groups_estimate(n):
    """Rough estimate of number of groups of order n."""
    if n == 1: return 1
    factors = factorize(n)
    if len(factors) == 1:
        p, a = list(factors.items())[0]
        # p-groups
        if a == 1: return 1
        if a == 2: return 2
        if a == 3: return 5
        if a == 4: return 14 if p == 2 else 15
        return max(15, a * a)
    # Multiple primes
    count = 1
    for p, a in factors.items():
        if a == 1: count *= 1
        elif a == 2: count *= 2
        elif a == 3: count *= 5
        else: count *= max(5, a * a)
    # Account for semidirect products
    return max(count, len(factors) + 1)


def classify_order(n):
    """Classify the 'dominant' group type for order n."""
    if n == 1: return "Vacuum", 1.0
    if is_prime(n): return "Prime Element", 1.0
    factors = factorize(n)
    if len(factors) == 1:
        p, a = list(factors.items())[0]
        if a == 2:
            return "Noble Gas", 1.0  # Both groups of order p^2 are abelian
        if a == 3:
            return "Alkali Metal", 0.6  # 3 abelian, 2 non-abelian nilpotent
        return "Alkali Metal", 0.4  # Higher p-groups mostly nilpotent
    if len(factors) == 2:
        return "Compound", 0.7  # Two prime factors → solvable (Burnside)
    # Check if order is divisible by enough primes for non-solvability
    if n >= 60 and n % 60 == 0:
        return "Radioactive", 0.3  # Could contain A_5 as quotient
    if len(factors) >= 3:
        return "Compound", 0.5
    return "Noble Gas", 0.8


# Color scheme matching chemical analogy
COLORS = {
    "Vacuum": "#f0f0f0",
    "Prime Element": "#ff6b6b",
    "Noble Gas": "#4ecdc4",
    "Alkaline Earth": "#45b7d1",
    "Alkali Metal": "#f9ca24",
    "Compound": "#a29bfe",
    "Radioactive": "#fd79a8",
}

def main():
    fig, ax = plt.subplots(1, 1, figsize=(16, 10))

    # Create grid for orders 1-100
    max_order = 100
    cols = 10
    rows = (max_order + cols - 1) // cols

    for n in range(1, max_order + 1):
        row = (n - 1) // cols
        col = (n - 1) % cols

        series, intensity = classify_order(n)
        color = COLORS[series]

        # Draw cell
        rect = mpatches.FancyBboxPatch(
            (col * 1.5, (rows - 1 - row) * 1.3),
            1.3, 1.1,
            boxstyle="round,pad=0.05",
            facecolor=color,
            edgecolor='gray',
            alpha=0.5 + 0.5 * intensity,
            linewidth=0.5
        )
        ax.add_patch(rect)

        # Order number
        ax.text(col * 1.5 + 0.65, (rows - 1 - row) * 1.3 + 0.75,
                str(n), ha='center', va='center',
                fontsize=9, fontweight='bold')

        # Estimated group count
        ng = num_groups_estimate(n)
        ax.text(col * 1.5 + 0.65, (rows - 1 - row) * 1.3 + 0.35,
                f"~{ng}g" if ng > 1 else "1g",
                ha='center', va='center', fontsize=6, color='gray')

    # Legend
    legend_patches = [
        mpatches.Patch(color=COLORS["Prime Element"], label="Prime Element (p)"),
        mpatches.Patch(color=COLORS["Noble Gas"], label="Noble Gas (cyclic)"),
        mpatches.Patch(color=COLORS["Alkali Metal"], label="Alkali Metal (nilpotent)"),
        mpatches.Patch(color=COLORS["Compound"], label="Compound (solvable)"),
        mpatches.Patch(color=COLORS["Radioactive"], label="Radioactive (non-solvable)"),
    ]
    ax.legend(handles=legend_patches, loc='upper right', fontsize=9,
              title="Chemical Series", title_fontsize=10)

    ax.set_xlim(-0.5, cols * 1.5 + 0.5)
    ax.set_ylim(-0.5, rows * 1.3 + 0.5)
    ax.set_aspect('equal')
    ax.axis('off')
    ax.set_title("The Periodic Table of Finite Groups (Orders 1–100)",
                 fontsize=16, fontweight='bold', pad=20)

    plt.tight_layout()
    plt.savefig("periodic_table_groups.png", dpi=150, bbox_inches='tight')
    print("Saved: periodic_table_groups.png")

if __name__ == "__main__":
    main()
