/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Optimal equidistant codes for `n ≡ 2 (mod 4)`: a Pell obstruction to a proposed BIBD family

An optimal equidistant binary code `EC(n, (n−2)/2, m)` with `n ≡ 2 (mod 4)` is
equivalent to a **symmetric block design** (a symmetric `2-(v, k, λ)` design, i.e.
a symmetric balanced incomplete block design).  A speculative research proposal
suggested that such optimal codes exist for the two–parameter family

>  `v = 12u² + 8u + 2`,  `k = 6u² + u`,  `λ = k(k−1)/(v−1)`,   `u ∈ ℕ`,

and that this family had "not been previously characterized".  This file carries
out an adversarial analysis of that proposal.

The first observation is purely algebraic: the awkward quotient defining `λ`
collapses to a polynomial,

>  `λ = 3u² − u`,

because the denominator `v − 1 = (2u+1)(6u+1)` divides the numerator
`k(k−1) = u(6u+1)(2u+1)(3u−1)` exactly.  Consequently the design *order*
`k − λ` is `u(3u+2)`.

For a **symmetric** `2-(v, k, λ)` design with an *even* number of points, the
Bruck–Ryser–Chowla theorem forces the order `k − λ` to be a perfect square.  Here
`v ≡ 2 (mod 4)` is always even, so the family can only host a symmetric design
when `u(3u+2)` is a perfect square.  The clean identity

>  `(3u+1)² = 3·u(3u+2) + 1`

turns this into the **Pell equation** `x² − 3y² = 1` with `x = 3u+1`: the order is
a perfect square exactly when `3u+1` is the `x`–coordinate of a Pell solution.
The admissible parameters are therefore *sparse*, indexed by a Pell recurrence
`u = 0, 2, 32, 450, …` rather than dense in `ℕ`.  In particular the smallest
non-trivial member `u = 1` has order `5`, ruling out the corresponding symmetric
`2-(22, 7, 2)` design outright.

The correct characterization of the family is thus a Pell/Diophantine one, not an
existence statement for all `u`.

## References
* `MB`  — Mathon & Rosa, tables of symmetric designs and admissible parameters.
* `IS95` — surveys of equidistant codes and their equivalence with symmetric designs.
* `vanLint84` — van Lint, *Introduction to Coding Theory* (equidistant codes,
  Fisher-type bounds, and the design ↔ code dictionary).

-- !-- Lab Notes -- !--
-- HYPOTHESIS (Hypothesizer): For every `u`, the parameter triple
--   `(12u²+8u+2, 6u²+u, k(k−1)/(v−1))` is realized by an optimal equidistant code,
--   i.e. by a symmetric BIBD, and the family is genuinely new.
-- EXPERIMENT (Experimenter): Reduce `λ`. The denominator factors as
--   `(2u+1)(6u+1)` and cancels the numerator `u(6u+1)(2u+1)(3u−1)`, giving the
--   polynomial `λ = 3u²−u` and order `k−λ = u(3u+2)`. Verified numerically for
--   `u = 0..7` and encoded as ring identities below.
-- ANALYSIS (Analyst): `v ≡ 2 (mod 4)` is even, so BRC demands `k−λ = u(3u+2)` be
--   a perfect square. The identity `(3u+1)² = 3·u(3u+2)+1` converts this to the
--   Pell equation `x²−3y²=1`. The square values of `u(3u+2)` for `u ≤ 500` are
--   exactly `u ∈ {0,2,32,450}` — a Pell sequence, NOT all `u`.
-- CRITIQUE (Critic): The bold existence hypothesis is FALSE as stated: `u = 1`
--   gives order `5`, a non-square, so the symmetric `2-(22,7,2)` design cannot
--   exist. The salvageable, non-trivial content is the Pell characterization of
--   admissible parameters plus an infinite family generated by the Pell step.
-- SYNTHESIS (PI): We prove (i) the `λ` collapse, (ii) the order formula, (iii)
--   `v ≡ 2 (mod 4)`, (iv) the Pell identity and the square⇔Pell equivalence,
--   (v) the `u=1` obstruction, (vi) explicit admissible members, and (vii) a
--   Pell step yielding infinitely many admissible `u`.
-/
import Mathlib

namespace EquidistantBIBDPell

/-- Number of points of the proposed symmetric design. -/
def v (u : ℤ) : ℤ := 12 * u ^ 2 + 8 * u + 2

/-- Block size of the proposed symmetric design. -/
def k (u : ℤ) : ℤ := 6 * u ^ 2 + u

/-- The index `λ` of the proposed symmetric design, as the *polynomial* `3u² − u`. -/
def lam (u : ℤ) : ℤ := 3 * u ^ 2 - u

/-- **λ collapses to a polynomial.**  The defining relation of a symmetric
`2-(v, k, λ)` design, `λ(v−1) = k(k−1)`, holds with `λ = 3u² − u`.  Equivalently,
`v − 1` divides `k(k−1)` exactly and the quotient is `3u² − u`. -/
theorem lam_defining_relation (u : ℤ) : lam u * (v u - 1) = k u * (k u - 1) := by
  simp only [lam, v, k]; ring

/-- The denominator `v − 1` factors as `(2u+1)(6u+1)`. -/
theorem v_sub_one_factor (u : ℤ) : v u - 1 = (2 * u + 1) * (6 * u + 1) := by
  simp only [v]; ring

/-- The numerator `k(k−1)` factors as `u(6u+1)(2u+1)(3u−1)`, exhibiting the exact
cancellation that produces the polynomial `λ`. -/
theorem k_mul_pred_factor (u : ℤ) :
    k u * (k u - 1) = u * (6 * u + 1) * (2 * u + 1) * (3 * u - 1) := by
  simp only [k]; ring

/-- **Order formula.**  The order `k − λ` of the proposed design is `u(3u+2)`. -/
theorem order_formula (u : ℤ) : k u - lam u = u * (3 * u + 2) := by
  simp only [k, lam]; ring

/-- **Parity of the point count.**  `v ≡ 2 (mod 4)`; in particular `v` is even,
so the Bruck–Ryser–Chowla square condition on the order applies. -/
theorem v_mod_four (u : ℕ) : (12 * u ^ 2 + 8 * u + 2) % 4 = 2 := by
  have : 12 * u ^ 2 + 8 * u + 2 = 4 * (3 * u ^ 2 + 2 * u) + 2 := by ring
  omega

/-- **Pell identity.**  `(3u+1)² = 3·(order) + 1`, the bridge turning the
"order is a perfect square" condition into the Pell equation `x² − 3y² = 1`. -/
theorem pell_identity (u : ℤ) : (3 * u + 1) ^ 2 = 3 * (u * (3 * u + 2)) + 1 := by
  ring

/-- **Order is a square ⇔ Pell solution.**  The design order `u(3u+2)` is a
perfect square exactly when `(3u+1, m)` solves the Pell equation `x² − 3y² = 1`.
This is the correct Diophantine characterization of the admissible parameters. -/
theorem order_square_iff_pell (u : ℤ) :
    (∃ m : ℤ, u * (3 * u + 2) = m ^ 2) ↔ (∃ m : ℤ, (3 * u + 1) ^ 2 - 3 * m ^ 2 = 1) := by
  constructor
  · rintro ⟨m, hm⟩
    exact ⟨m, by rw [pell_identity, hm]; ring⟩
  · rintro ⟨m, hm⟩
    refine ⟨m, ?_⟩
    have := pell_identity u
    linarith

/-- **The `u = 1` obstruction.**  For `u = 1` the parameters are the symmetric
`2-(22, 7, 2)` design, whose order would be `5`.  Since `5` is not a perfect
square, no such symmetric design (hence no such optimal equidistant code) exists.
This refutes the bold existence hypothesis at its smallest non-trivial instance. -/
theorem u_one_order_not_square : ¬ ∃ m : ℤ, (1 : ℤ) * (3 * 1 + 2) = m ^ 2 := by
  rintro ⟨m, hm⟩
  -- `m^2 = 5` has no integer solution
  have h5 : m ^ 2 = 5 := by linarith
  have h1 : m ≤ 2 := by nlinarith [sq_nonneg (m - 3)]
  have h2 : -2 ≤ m := by nlinarith [sq_nonneg (m + 3)]
  interval_cases m <;> omega

/-- The `u = 1` parameters really are `(v, k, λ) = (22, 7, 2)`. -/
theorem u_one_parameters : v 1 = 22 ∧ k 1 = 7 ∧ lam 1 = 2 := by
  refine ⟨?_, ?_, ?_⟩ <;> simp [v, k, lam]

/-- **First non-trivial admissible member `u = 2`.**  The parameters are
`(66, 26, 10)`, the order is `16 = 4²`, and `(7, 4)` solves the Pell equation. -/
theorem u_two_admissible :
    v 2 = 66 ∧ k 2 = 26 ∧ lam 2 = 10 ∧
      (2 : ℤ) * (3 * 2 + 2) = 4 ^ 2 ∧ (3 * 2 + 1) ^ 2 - 3 * 4 ^ 2 = 1 := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> simp [v, k, lam]

/-- **Second non-trivial admissible member `u = 32`.**  The order is
`32·98 = 3136 = 56²`, and `(97, 56)` solves the Pell equation. -/
theorem u_thirtytwo_admissible :
    (32 : ℤ) * (3 * 32 + 2) = 56 ^ 2 ∧ (3 * 32 + 1) ^ 2 - 3 * 56 ^ 2 = 1 := by
  constructor <;> norm_num

/-- **Pell step.**  If `(x, y)` solves `x² − 3y² = 1`, so does `(2x+3y, x+2y)`. -/
theorem pell_step {x y : ℤ} (h : x ^ 2 - 3 * y ^ 2 = 1) :
    (2 * x + 3 * y) ^ 2 - 3 * (x + 2 * y) ^ 2 = 1 := by
  nlinarith [h]

/-- **Admissibility step.**  From an admissible parameter `u` (order a perfect
square, witnessed by `m` via the Pell equation `(3u+1)² − 3m² = 1`) the values
`u' = 7u + 4m + 2` and `m' = 12u + 7m + 4` again satisfy the Pell equation, and
`u' > u` when `u ≥ 0` and `m ≥ 1`.  Applying the Pell step twice keeps the
`x`–coordinate `≡ 1 (mod 3)`, so admissibility propagates within the family. -/
theorem admissible_step {u m : ℤ} (h : (3 * u + 1) ^ 2 - 3 * m ^ 2 = 1)
    (hu : 0 ≤ u) (hm : 1 ≤ m) :
    (3 * (7 * u + 4 * m + 2) + 1) ^ 2 - 3 * (12 * u + 7 * m + 4) ^ 2 = 1 ∧
      u < 7 * u + 4 * m + 2 := by
  refine ⟨by nlinarith [h], by nlinarith⟩

/-- **Infinitely many admissible parameters.**  For every bound `N` there is an
admissible parameter `u > N`: some `u` with `u > N` whose order `u(3u+2)` is a
perfect square (equivalently `(3u+1)` is a Pell `x`–coordinate).  The admissible
`u` form the infinite Pell-indexed sequence `0, 2, 32, 450, …`. -/
theorem infinitely_many_admissible (N : ℤ) :
    ∃ u m : ℤ, N < u ∧ 0 ≤ u ∧ 1 ≤ m ∧ (3 * u + 1) ^ 2 - 3 * m ^ 2 = 1 := by
  -- Iterate the admissibility step from the base solution `(u, m) = (2, 4)`.
  -- We show that the `u`-values are unbounded above.
  -- Package a single "state" that satisfies the invariant, and induct on a
  -- natural-number step count large enough to exceed `N`.
  -- Base: (2,4) is admissible with u ≥ 0, m ≥ 1.
  -- Since each step strictly increases u (by ≥ 1) while preserving the invariant,
  -- after enough steps u exceeds any N.
  -- Formalize via strong induction on the number of remaining steps `t : ℕ`.
  suffices H : ∀ t : ℕ, ∃ u m : ℤ, (t : ℤ) ≤ u ∧ 0 ≤ u ∧ 1 ≤ m ∧
      (3 * u + 1) ^ 2 - 3 * m ^ 2 = 1 by
    obtain ⟨u, m, ht, hu, hm, hpell⟩ := H (N.toNat + 1)
    refine ⟨u, m, ?_, hu, hm, hpell⟩
    have : (N.toNat + 1 : ℤ) ≤ u := ht
    have hN : N ≤ (N.toNat : ℤ) := Int.self_le_toNat N
    push_cast at this
    linarith
  intro t
  induction t with
  | zero => exact ⟨2, 4, by norm_num, by norm_num, by norm_num, by norm_num⟩
  | succ n ih =>
      obtain ⟨u, m, ht, hu, hm, hpell⟩ := ih
      refine ⟨7 * u + 4 * m + 2, 12 * u + 7 * m + 4, ?_, by linarith, by linarith, ?_⟩
      · have : (n : ℤ) ≤ u := ht
        push_cast
        linarith
      · nlinarith [hpell]

end EquidistantBIBDPell