import Mathlib

/-!
# A finite ER=EPR toy model

This file isolates a mathematically precise finite statement behind the ER=EPR
slogan.  A pure two-qubit state is represented by its real coefficient matrix.
Its one-qubit reduced density matrices are computed by contraction.  The Bell
state has maximally mixed marginals and nonzero determinant, hence cannot be a
product state.

The bulk toy geometry consists of one possible Einstein--Rosen throat.  Its
weight is reconstructed from boundary entanglement entropies by the two-vertex
cut formula.  For the Bell state the reconstructed throat has unit weight.
-/

noncomputable section

namespace EmergentSpacetime

abbrev Qubit := Fin 2

/-- A real pure two-qubit state, represented by its coefficient matrix in the
computational basis. -/
abbrev TwoQubitState := Matrix Qubit Qubit ℝ

/-- The Bell state `|Φ⁺⟩ = (|00⟩ + |11⟩) / √2`. -/
def bellState : TwoQubitState := fun i j =>
  if i = j then (Real.sqrt 2)⁻¹ else 0

/-- The reduced density matrix on the left qubit. -/
def leftReduced (ψ : TwoQubitState) : Matrix Qubit Qubit ℝ := fun i k =>
  ∑ j, ψ i j * ψ k j

/-- The reduced density matrix on the right qubit. -/
def rightReduced (ψ : TwoQubitState) : Matrix Qubit Qubit ℝ := fun j l =>
  ∑ i, ψ i j * ψ i l

/-- The maximally mixed one-qubit density matrix `I/2`. -/
def maximallyMixed : Matrix Qubit Qubit ℝ := fun i j =>
  if i = j then 1 / 2 else 0

/-- A two-qubit coefficient matrix is a product state when it is an outer
product of two one-qubit amplitude vectors. -/
def IsProduct (ψ : TwoQubitState) : Prop :=
  ∃ u v : Qubit → ℝ, ∀ i j, ψ i j = u i * v j

/-- The determinant invariant detecting entanglement of a pure two-qubit state. -/
def entanglementDet (ψ : TwoQubitState) : ℝ := Matrix.det ψ

/-- Concurrence of a real pure two-qubit state. -/
def concurrence (ψ : TwoQubitState) : ℝ := 2 * |entanglementDet ψ|

/-- A two-boundary toy bulk geometry with a single possible throat. -/
structure TwoBoundaryGeometry where
  /-- The cross-sectional weight of the throat. -/
  throatWeight : ℝ
  weight_nonneg : 0 ≤ throatWeight

/-- Boundary cut-entanglement data for two boundary components. -/
structure TwoBoundaryEntanglement where
  /-- Entropy of the left boundary component. -/
  leftEntropy : ℝ
  /-- Entropy of the right boundary component. -/
  rightEntropy : ℝ
  /-- Entropy of the union of both boundary components. -/
  totalEntropy : ℝ

/-- Reconstruct the unique two-boundary throat by the cut formula
`(S(L) + S(R) - S(LR))/2`. -/
def reconstructGeometry (E : TwoBoundaryEntanglement)
    (h : 0 ≤ E.leftEntropy + E.rightEntropy - E.totalEntropy) : TwoBoundaryGeometry where
  throatWeight := (E.leftEntropy + E.rightEntropy - E.totalEntropy) / 2
  weight_nonneg := div_nonneg h (by norm_num)

/-- The cut entropies generated by a single throat of weight `w`: each proper
boundary cut crosses the throat once, while the full boundary crosses it zero
times. -/
def boundaryEntanglement (G : TwoBoundaryGeometry) : TwoBoundaryEntanglement where
  leftEntropy := G.throatWeight
  rightEntropy := G.throatWeight
  totalEntropy := 0

/-- The Bell pair's boundary entropy data, measured in bits. -/
def bellEntanglement : TwoBoundaryEntanglement where
  leftEntropy := 1
  rightEntropy := 1
  totalEntropy := 0

/-- A microscopic Einstein--Rosen bridge in this toy model is a unit-weight
throat joining the two boundary components. -/
def IsMicroscopicERBridge (G : TwoBoundaryGeometry) : Prop :=
  G.throatWeight = 1

/-- Product states have zero entanglement determinant. -/
theorem product_entanglementDet_zero {ψ : TwoQubitState} (h : IsProduct ψ) :
    entanglementDet ψ = 0 := by
  obtain ⟨u, v, huv⟩ := h
  simp [entanglementDet, Matrix.det_fin_two, huv]
  ring

/-- Both one-qubit marginals of the Bell state are maximally mixed. -/
theorem bell_marginals_maximally_mixed :
    leftReduced bellState = maximallyMixed ∧
      rightReduced bellState = maximallyMixed := by
  have sqrt2_sq : (Real.sqrt 2)⁻¹ * (Real.sqrt 2)⁻¹ = 1 / 2 := by
    rw [← mul_inv, Real.mul_self_sqrt (by norm_num : (2 : ℝ) ≥ 0)]
    norm_num
  constructor
  · ext i k
    simp [leftReduced, bellState, maximallyMixed]
    fin_cases i <;> fin_cases k <;> simp_all
  · ext j l
    simp [rightReduced, bellState, maximallyMixed]
    fin_cases j <;> fin_cases l <;> simp_all

/-- The Bell state has unit concurrence. -/
theorem bell_concurrence : concurrence bellState = 1 := by
  simp [concurrence, entanglementDet]
  norm_num [Matrix.det_fin_two, bellState]
  rw [abs_of_pos (by norm_num : (0 : ℝ) < Real.sqrt 2)]
  field_simp
  norm_num [Real.sq_sqrt]

/-- The Bell state is genuinely entangled: it admits no product factorization. -/
theorem bell_not_product : ¬ IsProduct bellState := by
  intro h
  have hdet := product_entanglementDet_zero h
  have hconc := bell_concurrence
  simp [concurrence, hdet] at hconc

/-- The two-boundary cut formula exactly reconstructs every one-throat toy
geometry from its boundary entanglement data. -/
theorem reconstruct_boundaryEntanglement (G : TwoBoundaryGeometry) :
    (reconstructGeometry (boundaryEntanglement G) (by
      simp [boundaryEntanglement, G.weight_nonneg])).throatWeight = G.throatWeight := by
  simp [reconstructGeometry, boundaryEntanglement]

/-- ER=EPR in the finite model: Bell-pair entanglement reconstructs a unit
microscopic Einstein--Rosen bridge. -/
theorem bell_pair_reconstructs_microscopic_bridge :
    IsMicroscopicERBridge
      (reconstructGeometry bellEntanglement (by norm_num [bellEntanglement])) := by
  simp [IsMicroscopicERBridge, reconstructGeometry, bellEntanglement]

/-- The Bell pair simultaneously has the quantum and geometric signatures of
the toy ER=EPR correspondence. -/
theorem bell_ER_EPR_correspondence :
    (¬ IsProduct bellState) ∧
    leftReduced bellState = maximallyMixed ∧
    rightReduced bellState = maximallyMixed ∧
    IsMicroscopicERBridge
      (reconstructGeometry bellEntanglement (by norm_num [bellEntanglement])) := by
  refine ⟨bell_not_product, bell_marginals_maximally_mixed.1,
    bell_marginals_maximally_mixed.2, bell_pair_reconstructs_microscopic_bridge⟩

end EmergentSpacetime