/-
# The face lattice of the chamber complex and the rank of a decisive coalition

This file closes the last open item of the tropical / social-choice bridge: the
combinatorial ("matroid") packaging of the polyhedral complex built in
`Tropical/SocialChoice/Chambers.lean` and
`Tropical/SocialChoice/ChamberComplex.lean`.

For a min-plus aggregator `F x = min_{i ∈ S} (x i + δ i)` the cells of the
complex are labelled by the nonempty subcoalitions `T ⊆ S`, the label of a
profile being the decisive coalition `decisiveSet S δ x`.  Here we prove that
this labelling is an *order anti-isomorphism* onto the face lattice, we identify
the walls containing a cell with the edges of the complete graph on `T` (the
flat of the graphic matroid of `K_S` generated by `T`), we exhibit the star of
any `i₀ ∈ T` as a spanning set of that flat, and we compute the codimension of
the cell to be exactly `|T| - 1`, the rank of the flat.

Main results.

* `closedCell_antitone`, `closedCell_subset_iff`, `closedCell_injOn`,
  `closedCell_ssubset`: `T ↦ closedCell T` is an inclusion-reversing bijection
  from the nonempty subcoalitions of `S` onto the cells of the complex; larger
  coalitions give strictly smaller faces.
* `closedCell_union`: the face lattice is closed under intersection, the
  intersection of two cells being the cell of the union of the labels.
* `closedCell_subset_wallSet_iff`: the walls containing the cell of `T` are
  exactly the pairs `(i, j)` with `i, j ∈ T` — the flat of the graphic matroid
  of the complete graph on `S` spanned by the edges of `K_T`.
* `closedCell_eq_star_inter`: the star `{(i, i₀) | i ∈ T}` of any `i₀ ∈ T`
  already cuts the cell out of the chamber of `i₀`: it is a spanning set (indeed
  a basis) of the flat, of size `|T| - 1`.
* `cellDirection`, `sub_mem_cellDirection`, `exists_relOpen_closedCell`,
  `finrank_cellDirection`: the cell spans the affine subspace directed by
  `cellDirection T = {v | v is constant on T}`, and
  `finrank (cellDirection T) + |T| = n + 1`, i.e. the cell has codimension
  exactly `|T| - 1`.
* `exists_decisiveSet_pair`, `adjacency_single_voter_exchange`: any two
  top-dimensional cells `{i}`, `{j}` share a codimension-one face, and the
  passage from one to the other is realized by changing the score of the single
  voter `j` — the exchange law of the support matroid.
-/
import Mathlib
import Tropical.SocialChoice.ChamberComplex

namespace TropicalSupportMatroid

open Finset TropicalChambers TropicalChamberComplex

variable {ι : Type*}

/-! ## The face lattice -/

/-- Larger labels give smaller cells. -/
theorem closedCell_antitone {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T T' : Finset ι}
    (h : T ⊆ T') : closedCell S hS δ T' ⊆ closedCell S hS δ T :=
  fun _ hx => h.trans hx

/-- The face lattice is closed under intersection: the cell of a union of labels
is the intersection of the cells. -/
theorem closedCell_union [DecidableEq ι] {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ)
    (T T' : Finset ι) :
    closedCell S hS δ (T ∪ T') = closedCell S hS δ T ∩ closedCell S hS δ T' := by
  ext x
  simp only [closedCell, Set.mem_setOf_eq, Set.mem_inter_iff, Finset.union_subset_iff]

/-- **The labelling is an order anti-isomorphism.**  For nonempty labels inside
the support, one cell contains another exactly when the labels are reversely
included. -/
theorem closedCell_subset_iff {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T T' : Finset ι}
    (hTS : T ⊆ S) (hT : T.Nonempty) :
    closedCell S hS δ T ⊆ closedCell S hS δ T' ↔ T' ⊆ T := by
  constructor
  · intro h
    obtain ⟨x, hx⟩ := exists_decisiveSet_eq hS δ hTS hT
    have hxT : x ∈ closedCell S hS δ T := by
      show T ⊆ decisiveSet S hS δ x
      rw [hx]
    have := h hxT
    simpa [closedCell, hx] using this
  · intro h
    exact closedCell_antitone hS δ h

/-- Distinct nonempty subcoalitions of the support give distinct cells. -/
theorem closedCell_injOn {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T T' : Finset ι}
    (hTS : T ⊆ S) (hT : T.Nonempty) (hT'S : T' ⊆ S) (hT' : T'.Nonempty)
    (h : closedCell S hS δ T = closedCell S hS δ T') : T = T' := by
  have h1 : T' ⊆ T := (closedCell_subset_iff hS δ hTS hT).mp h.subset
  have h2 : T ⊆ T' := (closedCell_subset_iff hS δ hT'S hT').mp h.symm.subset
  exact Finset.Subset.antisymm h2 h1

/-- Strictly larger labels give strictly smaller faces. -/
theorem closedCell_ssubset {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T T' : Finset ι}
    (hTS : T ⊆ S) (hT' : T'.Nonempty) (h : T' ⊂ T) :
    closedCell S hS δ T ⊂ closedCell S hS δ T' := by
  refine ⟨closedCell_antitone hS δ h.subset, ?_⟩
  intro hcontra
  have hT'S : T' ⊆ S := h.subset.trans hTS
  have : T ⊆ T' := (closedCell_subset_iff hS δ hT'S hT').mp hcontra
  exact absurd (Finset.Subset.antisymm h.subset this) (by
    intro hEq
    exact absurd h.2 (by simp [hEq]))

/-! ## Walls: the flat of the support matroid attached to a cell -/

/-- The wall on which the tropical monomials of `i` and `j` agree. -/
def wallSet (δ : ι → ℝ) (i j : ι) : Set (ι → ℝ) := {x | x i + δ i = x j + δ j}

/-- A generic profile with decisive coalition `T` in which a prescribed voter
`m ∉ T` is strictly worse off than everybody else. -/
theorem exists_decisiveSet_eq_of_lt {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T : Finset ι}
    (hTS : T ⊆ S) (hT : T.Nonempty) {m : ι} (hm : m ∉ T) :
    ∃ x : ι → ℝ, decisiveSet S hS δ x = T ∧ x m + δ m = 2 ∧ ∀ k, k ≠ m → x k + δ k ≤ 1 := by
  classical
  set x : ι → ℝ := fun k => (if k ∈ T then (0:ℝ) else if k = m then 2 else 1) - δ k with hxdef
  have hval : ∀ k, x k + δ k = if k ∈ T then (0:ℝ) else if k = m then 2 else 1 := by
    intro k; simp [hxdef]
  obtain ⟨t, htT⟩ := hT
  have hagg : tropAgg S hS δ x = 0 := by
    refine le_antisymm ?_ ?_
    · have := Finset.inf'_le (fun k => x k + δ k) (hTS htT)
      simpa [tropAgg, hval, htT] using this
    · refine Finset.le_inf' hS _ ?_
      intro j _
      rw [hval j]
      split_ifs <;> norm_num
  refine ⟨x, ?_, ?_, ?_⟩
  · ext k
    rw [mem_decisiveSet_iff, hagg, hval k]
    constructor
    · rintro ⟨-, hk⟩
      by_contra hkT
      rw [if_neg hkT] at hk
      split_ifs at hk <;> norm_num at hk
    · intro hk
      exact ⟨hTS hk, by rw [if_pos hk]⟩
  · rw [hval m, if_neg hm, if_pos rfl]
  · intro k hk
    rw [hval k]
    split_ifs <;> norm_num

/-- **The walls containing a cell are exactly the edges inside its label.**
Thus the cell of `T` corresponds to the flat of the graphic matroid of the
complete graph on `S` spanned by the edges of `K_T`. -/
theorem closedCell_subset_wallSet_iff {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T : Finset ι}
    (hTS : T ⊆ S) (hT : T.Nonempty) {i j : ι} :
    closedCell S hS δ T ⊆ wallSet δ i j ↔ (i ∈ T ∧ j ∈ T) ∨ i = j := by
  constructor
  · intro h
    by_cases hij : i = j
    · exact Or.inr hij
    refine Or.inl ⟨?_, ?_⟩ <;> by_contra hmem
    · obtain ⟨x, hx, hxm, hxle⟩ := exists_decisiveSet_eq_of_lt hS δ hTS hT hmem
      have hxT : x ∈ closedCell S hS δ T := by
        show T ⊆ decisiveSet S hS δ x
        rw [hx]
      have hw : x i + δ i = x j + δ j := h hxT
      have := hxle j (fun hji => hij hji.symm)
      rw [hxm] at hw
      linarith
    · obtain ⟨x, hx, hxm, hxle⟩ := exists_decisiveSet_eq_of_lt hS δ hTS hT hmem
      have hxT : x ∈ closedCell S hS δ T := by
        show T ⊆ decisiveSet S hS δ x
        rw [hx]
      have hw : x i + δ i = x j + δ j := h hxT
      have := hxle i hij
      rw [hxm] at hw
      linarith
  · rintro (⟨hi, hj⟩ | rfl)
    · intro x hx
      exact eq_on_closedCell hx hi hj
    · intro x _
      rfl

/-- **A star is a spanning set of the flat.**  For any `i₀ ∈ T` the cell of `T`
is cut out of the chamber of `i₀` by the `|T| - 1` wall equations
`x i + δ i = x i₀ + δ i₀`, `i ∈ T`. -/
theorem closedCell_eq_star_inter {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T : Finset ι}
    (hTS : T ⊆ S) {i₀ : ι} (hi₀ : i₀ ∈ T) :
    closedCell S hS δ T = closedCell S hS δ {i₀} ∩ ⋂ i ∈ T, wallSet δ i i₀ := by
  ext x
  simp only [closedCell, Set.mem_setOf_eq, Set.mem_inter_iff, Set.mem_iInter,
    Finset.singleton_subset_iff, wallSet]
  constructor
  · intro h
    refine ⟨h hi₀, fun i hi => ?_⟩
    exact eq_on_closedCell (by simpa [closedCell] using h) hi hi₀
  · rintro ⟨h0, hw⟩ i hi
    have h0' := (mem_decisiveSet_iff.mp h0).2
    refine mem_decisiveSet_iff.mpr ⟨hTS hi, ?_⟩
    rw [hw i hi, h0']

/-! ## Codimension of a cell -/

/-- The direction space of the cell labelled `T`: the profiles that are constant
on `T`. -/
def cellDirection (T : Finset ι) : Submodule ℝ (ι → ℝ) where
  carrier := {v | ∀ i ∈ T, ∀ j ∈ T, v i = v j}
  zero_mem' := by intro i _ j _; rfl
  add_mem' := by
    intro u v hu hv i hi j hj
    simp only [Pi.add_apply, hu i hi j hj, hv i hi j hj]
  smul_mem' := by
    intro c v hv i hi j hj
    simp only [Pi.smul_apply, hv i hi j hj]

lemma mem_cellDirection {T : Finset ι} {v : ι → ℝ} :
    v ∈ cellDirection T ↔ ∀ i ∈ T, ∀ j ∈ T, v i = v j := Iff.rfl

/-- The cell of `T` lies in an affine subspace directed by `cellDirection T`. -/
theorem sub_mem_cellDirection {S : Finset ι} {hS : S.Nonempty} {δ : ι → ℝ} {T : Finset ι}
    {x y : ι → ℝ} (hx : x ∈ closedCell S hS δ T) (hy : y ∈ closedCell S hS δ T) :
    x - y ∈ cellDirection T := by
  intro i hi j hj
  have h1 := eq_on_closedCell hx hi hj
  have h2 := eq_on_closedCell hy hi hj
  simp only [Pi.sub_apply]
  linarith

/-- **The cell is relatively open in its affine span.**  There is a profile
whose decisive coalition is exactly `T` and which stays in the (relatively open)
cell of `T` under every small perturbation in the direction space. -/
theorem exists_relOpen_closedCell {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ) {T : Finset ι}
    (hTS : T ⊆ S) (hT : T.Nonempty) :
    ∃ x₀ : ι → ℝ, decisiveSet S hS δ x₀ = T ∧
      ∀ v ∈ cellDirection T, (∀ k, |v k| < 1/4) → decisiveSet S hS δ (x₀ + v) = T := by
  classical
  set x₀ : ι → ℝ := fun k => (if k ∈ T then (0:ℝ) else 1) - δ k with hx₀def
  have hval : ∀ (v : ι → ℝ) k, (x₀ + v) k + δ k = (if k ∈ T then (0:ℝ) else 1) + v k := by
    intro v k; simp [hx₀def]; ring
  have key : ∀ v ∈ cellDirection T, (∀ k, |v k| < 1/4) → decisiveSet S hS δ (x₀ + v) = T := by
    intro v hv hvsmall
    obtain ⟨t, htT⟩ := hT
    have hvt : ∀ i ∈ T, v i = v t := fun i hi => hv i hi t htT
    have habs : ∀ k, -(1/4 : ℝ) < v k ∧ v k < 1/4 := by
      intro k; exact abs_lt.mp (hvsmall k)
    have hagg : tropAgg S hS δ (x₀ + v) = v t := by
      refine le_antisymm ?_ ?_
      · have := Finset.inf'_le (fun k => (x₀ + v) k + δ k) (hTS htT)
        simp only [tropAgg] at this ⊢
        rw [hval v t, if_pos htT] at this
        linarith
      · refine Finset.le_inf' hS _ ?_
        intro j _
        rw [hval v j]
        by_cases hj : j ∈ T
        · rw [if_pos hj, hvt j hj]; linarith
        · rw [if_neg hj]
          have h1 := (habs j).1
          have h2 := (habs t).2
          linarith
    ext k
    rw [mem_decisiveSet_iff, hagg, hval v k]
    constructor
    · rintro ⟨-, hk⟩
      by_contra hkT
      rw [if_neg hkT] at hk
      have h1 := (habs k).1
      have h2 := (habs t).2
      linarith
    · intro hk
      exact ⟨hTS hk, by rw [if_pos hk, hvt k hk]; ring⟩
  refine ⟨x₀, ?_, key⟩
  have := key 0 (Submodule.zero_mem _) (by intro k; norm_num)
  simpa using this

/-- **The codimension of the cell labelled `T` is `|T| - 1`**, the rank of the
corresponding flat of the support matroid: the direction space of the cell has
dimension `n - |T| + 1` on an electorate of `n` voters. -/
theorem finrank_cellDirection [Fintype ι] [DecidableEq ι] {T : Finset ι} (hT : T.Nonempty) :
    Module.finrank ℝ (cellDirection (ι := ι) T) + T.card = Fintype.card ι + 1 := by
  classical
  obtain ⟨i₀, hi₀⟩ := hT
  set L : (ι → ℝ) →ₗ[ℝ] (↥(T.erase i₀) → ℝ) :=
    { toFun := fun v i => v i - v i₀
      map_add' := by intro u v; funext i; simp [Pi.add_apply]; ring
      map_smul' := by intro c v; funext i; simp [Pi.smul_apply]; ring } with hL
  have hker : LinearMap.ker L = cellDirection (ι := ι) T := by
    ext v
    simp only [LinearMap.mem_ker, hL, LinearMap.coe_mk, AddHom.coe_mk, mem_cellDirection]
    constructor
    · intro h i hi j hj
      have hfun : ∀ k : ↥(T.erase i₀), v k - v i₀ = 0 := by
        intro k; exact congrFun h k
      have haux : ∀ k ∈ T, v k = v i₀ := by
        intro k hk
        by_cases hki : k = i₀
        · rw [hki]
        · have hmem : k ∈ T.erase i₀ := Finset.mem_erase.mpr ⟨hki, hk⟩
          have := hfun ⟨k, hmem⟩
          simpa using sub_eq_zero.mp this
      rw [haux i hi, haux j hj]
    · intro h
      funext k
      have hk : (k : ι) ∈ T := (Finset.mem_erase.mp k.2).2
      simp [h (k : ι) hk i₀ hi₀]
  have hsurj : Function.Surjective L := by
    intro w
    refine ⟨fun k => if hk : k ∈ T.erase i₀ then w ⟨k, hk⟩ else 0, ?_⟩
    have hi₀not : i₀ ∉ T.erase i₀ := Finset.notMem_erase _ _
    funext k
    simp only [hL, LinearMap.coe_mk, AddHom.coe_mk]
    rw [dif_pos k.2, dif_neg hi₀not]
    simp
  have hrange : LinearMap.range L = ⊤ := LinearMap.range_eq_top.mpr hsurj
  have hcodim : Module.finrank ℝ (↥(T.erase i₀) → ℝ) = (T.erase i₀).card := by
    rw [Module.finrank_pi ℝ]
    exact Fintype.card_coe _
  have hrk := LinearMap.finrank_range_add_finrank_ker L
  rw [hrange, hker] at hrk
  have htop : Module.finrank ℝ (⊤ : Submodule ℝ (↥(T.erase i₀) → ℝ)) = (T.erase i₀).card := by
    rw [finrank_top]
    exact hcodim
  rw [htop] at hrk
  have hdom : Module.finrank ℝ (ι → ℝ) = Fintype.card ι := by
    rw [Module.finrank_pi ℝ]
  rw [hdom] at hrk
  have hcard : (T.erase i₀).card + 1 = T.card := by
    rw [Finset.card_erase_of_mem hi₀]
    have : 1 ≤ T.card := Finset.card_pos.mpr ⟨i₀, hi₀⟩
    omega
  omega

/-! ## Adjacency of top-dimensional cells -/

/-- Any two voters of the support label a common codimension-one face: there is
a profile whose decisive coalition is exactly `{i, j}`. -/
theorem exists_decisiveSet_pair [DecidableEq ι] {S : Finset ι} (hS : S.Nonempty) (δ : ι → ℝ)
    {i j : ι} (hi : i ∈ S) (hj : j ∈ S) :
    ∃ x : ι → ℝ, decisiveSet S hS δ x = {i, j} := by
  refine exists_decisiveSet_eq hS δ ?_ ⟨i, by simp⟩
  intro k hk
  rcases Finset.mem_insert.mp hk with rfl | hk
  · exact hi
  · rw [Finset.mem_singleton] at hk; subst hk; exact hj

/-- **Exchange law for adjacent top-dimensional cells.**  From any profile in the
chamber of `i`, changing the score of the single voter `j` lands first on the
common face labelled `{i, j}` and then, after any further strict decrease, in the
open cell labelled `{j}`.  Adjacent chambers of the complex are therefore related
by single-voter exchanges. -/
theorem adjacency_single_voter_exchange [DecidableEq ι] {S : Finset ι} (hS : S.Nonempty)
    (δ : ι → ℝ) {i j : ι} (hiS : i ∈ S) (hjS : j ∈ S) (hij : i ≠ j) {x : ι → ℝ}
    (hx : x ∈ chamber S δ i) :
    Function.update x j (x i + δ i - δ j) ∈ closedCell S hS δ {i, j} ∧
      ∀ ε > 0, decisiveSet S hS δ (Function.update x j (x i + δ i - δ j - ε)) = {j} := by
  refine ⟨exchange_mem_wall hS δ hiS hjS hij hx, ?_⟩
  intro ε hε
  exact single_voter_exchange hS δ hjS hx hε

end TropicalSupportMatroid