import Mathlib

/-!
# Witness complexity: principal certificates and a two-parameter bound

A capturing face `w` in an abstract simplicial complex has a canonical certificate:
its principal down-set `w.powerset`.  This file proves that this certificate is the
unique smallest subcomplex containing `w`, has exactly `2 ^ |w|` faces, and is
independent of the ambient vertex count.  For a family `W` of at most `q` witness
faces, each of size at most `m`, the union of their principal certificates has at
most `q * 2^m` faces.

The results sharpen ambient-size polynomial estimates: witness complexity is
controlled directly by two intrinsic parameters, the number `q` of requested
witnesses and their maximum support size `m`.
-/

open Finset

namespace WitnessComplexity

variable {α : Type*} [DecidableEq α]

/-- A finite family of finite sets is downward closed. -/
def IsDownClosed (K : Finset (Finset α)) : Prop :=
  ∀ ⦃s t : Finset α⦄, s ∈ K → t ⊆ s → t ∈ K

/-- The canonical simplicial certificate generated by one face. -/
def principalCertificate (w : Finset α) : Finset (Finset α) := w.powerset

/-- The certificate generated by a finite family of faces. -/
def familyCertificate (W : Finset (Finset α)) : Finset (Finset α) :=
  W.biUnion principalCertificate

/-
A principal certificate is a simplicial complex.
-/
omit [DecidableEq α] in
theorem principalCertificate_downClosed (w : Finset α) :
    IsDownClosed (principalCertificate w) := by
  exact fun s t hs ht => Finset.mem_powerset.mpr ( Finset.Subset.trans ht ( Finset.mem_powerset.mp hs ) )

/-
Its maximal generating face belongs to it.
-/
omit [DecidableEq α] in
theorem mem_principalCertificate (w : Finset α) :
    w ∈ principalCertificate w := by
  exact Finset.mem_powerset_self _

/-
**Minimality.** Every downward-closed family containing `w` contains its
entire principal certificate.
-/
omit [DecidableEq α] in
theorem principalCertificate_minimal {K : Finset (Finset α)} {w : Finset α}
    (hK : IsDownClosed K) (hw : w ∈ K) :
    principalCertificate w ⊆ K := by
  exact fun x hx => hK hw ( Finset.mem_powerset.mp hx )

/-
**Exact one-witness complexity.** The canonical certificate has `2^|w|`
faces.
-/
omit [DecidableEq α] in
theorem principalCertificate_card (w : Finset α) :
    (principalCertificate w).card = 2 ^ w.card := by
  convert Finset.card_powerset w

/-
Consequently, every simplicial certificate containing `w` needs at least
`2^|w|` faces.
-/
omit [DecidableEq α] in
theorem downClosed_card_lower_bound {K : Finset (Finset α)} {w : Finset α}
    (hK : IsDownClosed K) (hw : w ∈ K) :
    2 ^ w.card ≤ K.card := by
  exact Finset.card_le_card ( principalCertificate_minimal hK hw ) |> le_trans ( by simp +decide [ principalCertificate_card ] )

/-
A family certificate is again downward closed.
-/
theorem familyCertificate_downClosed (W : Finset (Finset α)) :
    IsDownClosed (familyCertificate W) := by
  -- Unfold familyCertificate and biUnion membership.
  unfold familyCertificate principalCertificate IsDownClosed
  intro s;
  grind

/-
Every requested witness is retained by the family certificate.
-/
theorem subset_familyCertificate (W : Finset (Finset α)) :
    W ⊆ familyCertificate W := by
  intro w hw
  exact Finset.mem_biUnion.mpr ⟨w, hw, mem_principalCertificate w⟩

/-
The generated family is the least downward-closed family containing all
requested witnesses.
-/
theorem familyCertificate_minimal {W K : Finset (Finset α)}
    (hK : IsDownClosed K) (hWK : W ⊆ K) :
    familyCertificate W ⊆ K := by
  exact Finset.biUnion_subset.mpr fun w hw => principalCertificate_minimal hK ( hWK hw )

/-
**Two-parameter witness theorem.** If at most `q` faces are requested and
each has at most `m` vertices, their generated subcomplex has at most
`q * 2^m` faces.  This has no dependence on the ambient number of vertices.
-/
theorem familyCertificate_card_le
    (W : Finset (Finset α)) (q m : ℕ)
    (hcount : W.card ≤ q) (hwidth : ∀ w ∈ W, w.card ≤ m) :
    (familyCertificate W).card ≤ q * 2 ^ m := by
  refine' le_trans _ ( Nat.mul_le_mul_right _ hcount );
  convert Finset.card_biUnion_le.trans _ using 1;
  exact le_trans ( Finset.sum_le_sum fun x hx => show # ( principalCertificate x ) ≤ 2 ^ m from by rw [ principalCertificate_card ] ; exact pow_le_pow_right₀ ( by decide ) ( hwidth x hx ) ) ( by simp +decide )

/-
Capstone: the generated family is simultaneously a valid subcomplex,
contains all witnesses, and satisfies the intrinsic two-parameter bound.
-/
theorem exists_small_witness_subcomplex
    (W : Finset (Finset α)) (q m : ℕ)
    (hcount : W.card ≤ q) (hwidth : ∀ w ∈ W, w.card ≤ m) :
    ∃ K : Finset (Finset α),
      IsDownClosed K ∧ W ⊆ K ∧ K.card ≤ q * 2 ^ m := by
  exact ⟨_, familyCertificate_downClosed W, subset_familyCertificate W,
    familyCertificate_card_le W q m hcount hwidth⟩

/-
**Ambient-relative capstone.** Inside any ambient simplicial complex `A`,
any `q` designated faces of width at most `m` admit a downward-closed
subcomplex containing them with at most `q * 2^m` faces.
-/
theorem exists_small_subcomplex_of
    (A W : Finset (Finset α)) (q m : ℕ)
    (hA : IsDownClosed A) (hWA : W ⊆ A)
    (hcount : W.card ≤ q) (hwidth : ∀ w ∈ W, w.card ≤ m) :
    ∃ K : Finset (Finset α),
      IsDownClosed K ∧ W ⊆ K ∧ K ⊆ A ∧ K.card ≤ q * 2 ^ m := by
  set K := familyCertificate W
  have hK_downClosed : IsDownClosed K := by
    exact familyCertificate_downClosed W
  have hK_subset_A : K ⊆ A := by
    exact familyCertificate_minimal hA hWA
  have hK_card : K.card ≤ q * 2 ^ m := by
    apply familyCertificate_card_le W q m hcount hwidth
  exact ⟨K, hK_downClosed, subset_familyCertificate W, hK_subset_A, hK_card⟩

/-
A concrete counterexample to the bold but false extrapolation that every
width-two complex on `n` vertices has the tree count `2n`: the complete
width-two skeleton on four vertices has eleven faces, not eight.
-/
theorem width_two_tree_count_conjecture_false :
    let base := (Finset.univ : Finset (Fin 4))
    let K := base.powerset.filter (fun s => s.card ≤ 2)
    K.card = 11 ∧ K.card ≠ 2 * base.card := by
  decide +kernel

end WitnessComplexity