/-
# Radical 2-isogeny verification on Montgomery curves

This file builds on the catalog's isogeny group-action foundations and verifies,
at the level of affine rational functions, the degree-two quotient map with
kernel generated by the rational two-torsion point `(0,0)`.

For the Montgomery equation `y² = x³ + A*x² + x`, put

* `X = x + x⁻¹`,
* `Y = y * (1 - x⁻²)`.

The image satisfies `Y² = X³ + A*X² - 4*X - 4*A`.  The formulas are invariant
under `x ↦ x⁻¹`, the nontrivial deck transformation of this quotient.  Avoiding
an affine point structure keeps the statements directly reusable with
Mathlib's several projective/Weierstrass point representations.
-/
import Cryptography.AbstractAlgebra.IsogenyFoundations

namespace Cryptography.IsogenySIDH

section Montgomery

variable {K : Type*} [Field K]

/-- The affine Montgomery equation with coefficient of `x` normalized to one. -/
def OnMontgomery (A : K) (P : K × K) : Prop :=
  P.2 ^ 2 = P.1 ^ 3 + A * P.1 ^ 2 + P.1

/-- The affine equation of the quotient by the point `(0,0)`. -/
def OnTwoQuotient (A : K) (P : K × K) : Prop :=
  P.2 ^ 2 = P.1 ^ 3 + A * P.1 ^ 2 - 4 * P.1 - 4 * A

/-- Rational evaluation formula for the radical degree-two quotient map. -/
def radicalTwoEval (P : K × K) : K × K :=
  (P.1 + P.1⁻¹, P.2 * (1 - P.1⁻¹ ^ 2))

/-- The target polynomial factors into its three visible two-torsion roots. -/
theorem twoQuotient_factor (A X : K) :
    X ^ 3 + A * X ^ 2 - 4 * X - 4 * A = (X + A) * (X - 2) * (X + 2) := by
  ring

/-- The radical degree-two formula maps every input point away from its pole to
its claimed quotient curve.  This is the principal affine correctness theorem. -/
theorem radicalTwoEval_on_curve {A x y : K} (hx : x ≠ 0)
    (hP : OnMontgomery A (x, y)) :
    OnTwoQuotient A (radicalTwoEval (x, y)) := by
  dsimp [OnMontgomery] at hP
  dsimp [OnTwoQuotient, radicalTwoEval]
  calc
    (y * (1 - x⁻¹ ^ 2)) ^ 2 = y ^ 2 * (1 - x⁻¹ ^ 2) ^ 2 := by ring
    _ = (x ^ 3 + A * x ^ 2 + x) * (1 - x⁻¹ ^ 2) ^ 2 := by rw [hP]
    _ = (x + x⁻¹) ^ 3 + A * (x + x⁻¹) ^ 2 - 4 * (x + x⁻¹) - 4 * A := by
      field_simp
      ring

/-- The `X`-coordinate of evaluation is invariant under the quotient's deck
transformation `x ↦ x⁻¹`. -/
theorem radicalTwoEval_x_inversion (x : K) :
    (radicalTwoEval (x⁻¹, (0 : K))).1 = (radicalTwoEval (x, (0 : K))).1 := by
  simp [radicalTwoEval, add_comm]

/-- Under simultaneous inversion of `x` and the corresponding rescaling of
`y`, the complete affine output is unchanged. -/
theorem radicalTwoEval_deck_invariant {x y : K} (hx : x ≠ 0) :
    radicalTwoEval (x⁻¹, -(y * x⁻¹ ^ 2)) = radicalTwoEval (x, y) := by
  apply Prod.ext
  · simp [radicalTwoEval, add_comm]
  · dsimp [radicalTwoEval]
    field_simp
    ring

/-- Equality of nonzero quotient `X`-coordinates has exactly the expected two
possibilities: equal inputs or inputs interchanged by inversion. -/
theorem quotient_fiber_classification {x z : K} (hx : x ≠ 0) (hz : z ≠ 0)
    (h : x + x⁻¹ = z + z⁻¹) : x = z ∨ x * z = 1 := by
  field_simp [hx, hz] at h
  have hfactor : (x - z) * (x * z - 1) = 0 := by
    linear_combination h
  rcases mul_eq_zero.mp hfactor with h₁ | h₂
  · left
    exact sub_eq_zero.mp h₁
  · right
    exact sub_eq_zero.mp h₂

/-- Conversely, the two alternatives in the fiber classification produce the
same quotient `X`-coordinate. -/
theorem quotient_x_eq_of_same_or_inverse {x z : K} (hx : x ≠ 0) (hz : z ≠ 0)
    (h : x = z ∨ x * z = 1) : x + x⁻¹ = z + z⁻¹ := by
  rcases h with rfl | hprod
  · rfl
  · have hzxi : z = x⁻¹ := by
      apply (mul_left_cancel₀ hx)
      rw [mul_inv_cancel₀ hx]
      exact hprod
    subst z
    simp [add_comm]

/-- Exact characterization of fibers of the evaluated `X`-coordinate. -/
theorem radicalTwoEval_x_fiber_iff {x z : K} (hx : x ≠ 0) (hz : z ≠ 0) :
    (radicalTwoEval (x, (0 : K))).1 = (radicalTwoEval (z, (0 : K))).1 ↔
      x = z ∨ x * z = 1 := by
  simp only [radicalTwoEval]
  constructor
  · exact quotient_fiber_classification hx hz
  · exact quotient_x_eq_of_same_or_inverse hx hz

/-- The target equation exposes the image of the nonzero two-torsion roots:
if `x² + A*x + 1 = 0`, then its quotient coordinate is `-A`. -/
theorem torsion_root_maps_to_neg_parameter {A x : K} (hx : x ≠ 0)
    (hroot : x ^ 2 + A * x + 1 = 0) : x + x⁻¹ = -A := by
  field_simp [hx]
  linear_combination hroot

/-- The visible target point with `X = -A` is indeed two-torsion at the level
of the affine equation (`Y = 0`). -/
theorem neg_parameter_on_twoQuotient (A : K) :
    OnTwoQuotient A (-A, 0) := by
  simp [OnTwoQuotient]
  ring

/-- Both other visible target roots give affine points with zero ordinate. -/
theorem plus_two_on_twoQuotient (A : K) :
    OnTwoQuotient A (2, 0) := by
  rw [OnTwoQuotient, twoQuotient_factor]
  ring

theorem minus_two_on_twoQuotient (A : K) :
    OnTwoQuotient A (-2, 0) := by
  rw [OnTwoQuotient, twoQuotient_factor]
  ring

/-- Scaling the ordinate by a chosen radical normalizes a quadratic twist.
This isolates precisely the radical precomputation used by radical-isogeny
algorithms. -/
def radicalNormalize (r : K) (P : K × K) : K × K :=
  (P.1, r * P.2)

/-- Correctness of radical normalization: if `r² = B`, then scaling sends
`B*y² = x³ + A*x² + x` to the normalized Montgomery equation. -/
theorem radicalNormalize_correct {A B r x y : K}
    (hrad : r ^ 2 = B)
    (hP : B * y ^ 2 = x ^ 3 + A * x ^ 2 + x) :
    OnMontgomery A (radicalNormalize r (x, y)) := by
  dsimp [OnMontgomery, radicalNormalize]
  calc
    (r * y) ^ 2 = r ^ 2 * y ^ 2 := by ring
    _ = B * y ^ 2 := by rw [hrad]
    _ = x ^ 3 + A * x ^ 2 + x := hP

/-- The chosen radical normalization is invertible away from a zero radical. -/
theorem radicalNormalize_injective {r : K} (hr : r ≠ 0) :
    Function.Injective (radicalNormalize (K := K) r) := by
  intro P Q h
  apply Prod.ext
  · have h₁ := congrArg Prod.fst h
    simpa [radicalNormalize] using h₁
  · have h₂ := congrArg Prod.snd h
    simpa [radicalNormalize] using mul_left_cancel₀ hr h₂

/-- End-to-end affine correctness of the radical-normalize-then-quotient
algorithm. -/
theorem radicalTwoAlgorithm_correct {A B r x y : K}
    (hrad : r ^ 2 = B)
    (hP : B * y ^ 2 = x ^ 3 + A * x ^ 2 + x)
    (hx : x ≠ 0) :
    OnTwoQuotient A
      (radicalTwoEval (radicalNormalize r (x, y))) := by
  apply radicalTwoEval_on_curve
  · exact hx
  · exact radicalNormalize_correct hrad hP

end Montgomery

section ActionVerification

open IsogenyFoundations

variable {G X : Type*} [CommGroup G] [Fintype G] [Fintype X]
  [DecidableEq G] [DecidableEq X]

/-- A compact verification record for a chain of radical-isogeny evaluations:
each advertised step carries its acting class-group element. -/
def VerifiesStep (T : FreeTrans G X) (source target : X) (step : G) : Prop :=
  T.act step source = target

/-- Two verified radical-isogeny evaluations compose to a verified evaluation.
This specializes the catalog action law rather than introducing a second
notion of isogeny composition. -/
theorem verifiesStep_compose (T : FreeTrans G X) {x y z : X} {a b : G}
    (ha : VerifiesStep T x y a) (hb : VerifiesStep T y z b) :
    VerifiesStep T x z (b * a) := by
  rw [VerifiesStep, T.act_mul, ha, hb]

/-- Reversing a verified evaluation uses the inverse class-group element. -/
theorem verifiesStep_reverse (T : FreeTrans G X) {x y : X} {a : G}
    (ha : VerifiesStep T x y a) : VerifiesStep T y x a⁻¹ := by
  rw [VerifiesStep, ← ha]
  exact T.act_inv_cancel a x

/-- The connector extracted from a verified radical-isogeny step is exactly
its advertised group element. -/
theorem connector_of_verified_step (T : FreeTrans G X) {x y : X} {a : G}
    (ha : VerifiesStep T x y a) : T.connector x y = a := by
  apply T.unique_connector x y
  · exact T.connector_spec x y
  · exact ha

/-- Any two advertised class-group elements verifying the same radical-isogeny
step agree.  This is the algebraic soundness property of step verification. -/
theorem verified_step_unique (T : FreeTrans G X) {x y : X} {a b : G}
    (ha : VerifiesStep T x y a) (hb : VerifiesStep T x y b) : a = b := by
  exact T.unique_connector x y a b ha hb

end ActionVerification

end Cryptography.IsogenySIDH