/-
# NET-68, third cycle: the domain axis is a ℤ-torsor, and the envelope rule needs the
# shared increment

Round 21 reports a *shift*: code sits `4` keys below prose at both contexts.  It never
reports an absolute domain coordinate, and this file shows that it cannot: at a fixed
scale the set of budget laws with a given increment carries a free and transitive action
of ℤ by base translation, so only *differences* of bases are observable.  The measured
`−4` is the whole of the domain information at this scale.

The same rigidity has a cost.  `Applications.NET68DomainJumpBudgetLaw` derives the
deployment rule "size the cache by the largest base" from `eval_sup'`, which assumes the
increment is shared.  Here we show that assumption is not decoration: as soon as two
domains have different increments *and* their bases cross, the mixed-workload envelope is
provably **not** a budget law at all (`envelope_not_a_law`).  Deployment sizing by a
single law is a privilege that the NET-68 measurement earns, not a modelling default.

## Contents

* `eval_ext_of_two_points'` — affine rigidity: agreement at any two distinct contexts
  forces equality of laws (`ext_of_two_points` is the case `0, 1`).
* `exists_unique_shift`, `shift_add`, `shift_self`, `shift_symm` — the fibre of laws with
  a fixed increment is a ℤ-torsor: a unique translation carries one domain to another, and
  translations compose additively.  `fiberEquivInt` is the induced bijection with ℤ.
* `only_base_differences_are_observable` — re-basing every domain by a common `t` leaves
  every inter-domain shift unchanged: the origin of the domain axis is pure convention.
* `le_eval_iff_base_le`, `envelope_eq_of_inc_eq` — in a fibre, the pointwise order is the
  order of bases and the envelope is the join.
* `envelope_not_a_law` — with unequal increments and crossing bases, no budget law
  computes the mixed-workload envelope.
* `net68_domain_axis` — the round-21 instance: code and prose lie in one fibre, the
  connecting translation is `4`, and it generates the domain ladder.
-/
import Mathlib
import Applications.NET68DomainJumpBudgetLaw

namespace Catalog.NET68

namespace BudgetLaw

/-! ## 1. Affine rigidity -/

/-- Two laws agreeing at **any** two distinct contexts are equal.  (The knee experiment
therefore needs two contexts, and two suffice, whichever they are.) -/
theorem eval_ext_of_two_points' {A B : BudgetLaw} {d e : ℕ} (hde : d ≠ e)
    (hd : A.eval d = B.eval d) (he : A.eval e = B.eval e) : A = B := by
  have hd' : A.base + A.inc * d = B.base + B.inc * d := hd
  have he' : A.base + A.inc * e = B.base + B.inc * e := he
  have hsub : (A.inc - B.inc) * ((d : ℤ) - e) = 0 := by ring_nf; linarith
  have hne : ((d : ℤ) - e) ≠ 0 := by
    intro h
    exact hde (by exact_mod_cast sub_eq_zero.1 h)
  have hinc : A.inc = B.inc := by
    rcases mul_eq_zero.1 hsub with h | h
    · exact sub_eq_zero.1 h
    · exact absurd h hne
  have hbase : A.base = B.base := by
    rw [hinc] at hd'
    linarith
  cases A; cases B; simp_all

/-! ## 2. The fibre of a fixed increment is a ℤ-torsor -/

/-- Translating a law's base: the action of ℤ on the domain axis. -/
def tr (t : ℤ) (L : BudgetLaw) : BudgetLaw := ⟨L.base + t, L.inc⟩

@[simp] theorem tr_inc (t : ℤ) (L : BudgetLaw) : (tr t L).inc = L.inc := rfl

@[simp] theorem tr_eval (t : ℤ) (L : BudgetLaw) (d : ℕ) :
    (tr t L).eval d = L.eval d + t := by
  simp only [tr, eval]; ring

@[simp] theorem tr_zero (L : BudgetLaw) : tr 0 L = L := by
  simp [tr]

theorem tr_tr (s t : ℤ) (L : BudgetLaw) : tr s (tr t L) = tr (s + t) L := by
  simp only [tr, add_assoc, add_comm t s]

/-- **Transitivity, freely.**  Two domains at the same scale are related by a *unique*
translation of the budget axis. -/
theorem exists_unique_shift {A B : BudgetLaw} (h : A.inc = B.inc) :
    ∃! t : ℤ, tr t A = B := by
  refine ⟨B.base - A.base, ?_, ?_⟩
  · cases A; cases B; simp_all [tr]
  · intro t ht
    have : A.base + t = B.base := congrArg BudgetLaw.base ht
    omega

/-- The connecting translation, i.e. the observable inter-domain shift. -/
def shift (A B : BudgetLaw) : ℤ := B.base - A.base

@[simp] theorem shift_self (A : BudgetLaw) : shift A A = 0 := by simp [shift]

theorem shift_symm (A B : BudgetLaw) : shift B A = -shift A B := by
  simp [shift]

/-- **Cocycle law.**  Shifts compose additively along a chain of domains — the domain
ladder is generated by its consecutive gaps. -/
theorem shift_add (A B C : BudgetLaw) : shift A B + shift B C = shift A C := by
  simp only [shift]; ring

/-- With a shared increment the shift is exactly the (context-free) budget difference. -/
theorem shift_eq_eval_sub {A B : BudgetLaw} (h : A.inc = B.inc) (d : ℕ) :
    shift A B = B.eval d - A.eval d := by
  simp only [shift, eval, h]; ring

/-- The fibre over an increment is in bijection with ℤ: a domain at a fixed scale is
exactly one integer of information. -/
def fiberEquivInt (c : ℤ) : {L : BudgetLaw // L.inc = c} ≃ ℤ where
  toFun L := L.1.base
  invFun b := ⟨⟨b, c⟩, rfl⟩
  left_inv := by rintro ⟨⟨b, i⟩, rfl⟩; rfl
  right_inv := by intro b; rfl

/-- **Only differences are observable.**  Re-basing every domain by a common translation
leaves every inter-domain shift unchanged, so the origin of the domain axis carries no
experimental content: NET-68 measures `−4`, never `12` and `16` separately. -/
theorem only_base_differences_are_observable (t : ℤ) (A B : BudgetLaw) :
    shift (tr t A) (tr t B) = shift A B := by
  simp only [shift, tr]; ring

/-- A base value on its own is not observable: some translation moves it anywhere while
fixing all shifts. -/
theorem base_not_observable (A B : BudgetLaw) (b : ℤ) :
    ∃ t : ℤ, (tr t A).base = b ∧ shift (tr t A) (tr t B) = shift A B :=
  ⟨b - A.base, by simp [tr], only_base_differences_are_observable _ _ _⟩

/-! ## 3. Order and the envelope inside a fibre -/

/-- Inside a fibre the pointwise budget order is exactly the order of bases. -/
theorem le_eval_iff_base_le {A B : BudgetLaw} (h : A.inc = B.inc) :
    (∀ d : ℕ, A.eval d ≤ B.eval d) ↔ A.base ≤ B.base := by
  constructor
  · intro hle
    have := hle 0
    simpa using this
  · intro hb d
    simp only [eval, h]
    linarith

/-- Inside a fibre the mixed-workload envelope is the join, and it is a law. -/
theorem envelope_eq_of_inc_eq {A B : BudgetLaw} (h : A.inc = B.inc) (d : ℕ) :
    max (A.eval d) (B.eval d) = (BudgetLaw.mk (max A.base B.base) A.inc).eval d :=
  max_eval h d

/-! ## 4. Without the shared increment there is no envelope law -/

/-- **The deployment rule fails outside a fibre.**  If two domains have different
increments and their bases cross, then *no* budget law computes the mixed-workload
envelope: a mixed workload of such domains cannot be sized by a single
`base + increment · doublings` formula.  This is what the measured constancy of the
NET-68 shift buys. -/
theorem envelope_not_a_law {A B : BudgetLaw} (hinc : A.inc < B.inc)
    (hbase : B.base < A.base) :
    ¬ ∃ C : BudgetLaw, ∀ d : ℕ, C.eval d = max (A.eval d) (B.eval d) := by
  rintro ⟨C, hC⟩
  obtain ⟨D, hD⟩ := crossover_of_inc_lt hinc
  have hCB : ∀ d : ℕ, D ≤ d → C.eval d = B.eval d := by
    intro d hd
    rw [hC d, max_eq_right (le_of_lt (hD d hd))]
  have h1 : C.eval D = B.eval D := hCB D le_rfl
  have h2 : C.eval (D + 1) = B.eval (D + 1) := hCB (D + 1) (by omega)
  have hCeqB : C = B := eval_ext_of_two_points' (by omega) h1 h2
  have h0 : C.eval 0 = max (A.eval 0) (B.eval 0) := hC 0
  rw [hCeqB] at h0
  simp only [eval_zero] at h0
  rw [max_eq_left (le_of_lt hbase)] at h0
  omega

/-- The hypotheses of `envelope_not_a_law` are satisfiable: the failure is real, not
vacuous. -/
theorem envelope_failure_realisable :
    ¬ ∃ C : BudgetLaw, ∀ d : ℕ,
      C.eval d = max ((BudgetLaw.mk 16 2).eval d) ((BudgetLaw.mk 12 6).eval d) :=
  envelope_not_a_law (A := ⟨16, 2⟩) (B := ⟨12, 6⟩) (by norm_num) (by norm_num)

end BudgetLaw

/-! ## 5. The round-21 instance -/

open BudgetLaw

/-- **The NET-68 domain axis.**  Code and prose lie in the same fibre (shared increment);
the unique translation carrying code to prose is `+4`, i.e. one fine grid step; shifts
compose along the ladder; and re-basing both domains changes nothing observable.  The
experiment measures a torsor element, not a pair of coordinates. -/
theorem net68_domain_axis :
    codeLaw.inc = proseLaw.inc ∧
    (∃! t : ℤ, tr t codeLaw = proseLaw) ∧
    shift codeLaw proseLaw = (fineStep : ℤ) ∧
    (∀ t : ℤ, shift (tr t codeLaw) (tr t proseLaw) = shift codeLaw proseLaw) := by
  refine ⟨net68_increment_shared, exists_unique_shift net68_increment_shared, ?_, ?_⟩
  · norm_num [shift, codeLaw, proseLaw, fineStep]
  · intro t; exact only_base_differences_are_observable t codeLaw proseLaw

/-- A third domain that were one fine step below code would extend the ladder by the same
gap: the shifts `code → prose` and `hypothetical → code` add to `8`. -/
theorem net68_ladder_composes :
    shift (BudgetLaw.mk 8 4) codeLaw + shift codeLaw proseLaw = 8 := by
  norm_num [shift, codeLaw, proseLaw]

end Catalog.NET68