import Cryptography.WeilPairingBLS

/-!
# The determinant model of the Weil pairing: construction, classification, existence

The catalog file `Cryptography.WeilPairingBLS` *axiomatises* a Weil pairing on the
`n`-torsion of a Weierstrass curve (bilinear, alternating, `n`-torsion valued,
nondegenerate).  This file removes the axiom in the only place where it can be removed
by pure algebra, and classifies all possible pairings.

Main results.

* `AltPairing` : the bare alternating bi-additive interface, extracted from a
  `WeilPairing` by `WeilPairing.toAltPairing`.
* `AltPairing.pair_zsmul_left/right`, `AltPairing.skew` : full `ℤ`-bilinearity and
  skew-symmetry from alternation alone.
* `AltPairing.pair_coords` : **classification.** On a group generated by two elements
  `e₁, e₂`, every alternating pairing is the `ζ`-th power of the determinant form,
  `e(a e₁ + b e₂, c e₁ + d e₂) = ζ ^ (ad - bc)` with `ζ = e(e₁,e₂)`.  In particular two
  alternating pairings that agree on a basis agree everywhere
  (`AltPairing.ext_of_basis`).
* `detPairing` : the explicit determinant pairing on `(ZMod n)²` with values in
  `Multiplicative (ZMod n)`, proved alternating, `n`-torsion and **nondegenerate**.
* `weilPairingOfEquiv` : **existence.** Any Weierstrass curve whose `n`-torsion is
  isomorphic to `(ZMod n)²` carries a Weil pairing in the sense of the catalog
  structure.  Together with `detPairing_nondegenerate` this shows that the axioms of
  `WeilPairing` are consistent and non-vacuous.
* `AltPairing.orderOf_root_of_nondegenerate` : conversely, a nondegenerate alternating
  pairing on `(ZMod n)²` forces its root of unity `ζ` to have exact order `n`.
-/

open scoped BigOperators

namespace Cryptography.WeilBLS

universe u v w

/-! ## The bare alternating pairing interface -/

/-- An alternating bi-additive pairing from an additive abelian group to a
commutative group.  This is the algebraic core shared by all Weil pairings. -/
structure AltPairing (A : Type u) [AddCommGroup A] (μ : Type v) [CommGroup μ] where
  /-- The underlying bi-additive map. -/
  hom : A →+ A →+ Additive μ
  /-- Alternation. -/
  alternating : ∀ P : A, hom P P = 0

namespace AltPairing

variable {A : Type u} [AddCommGroup A] {μ : Type v} [CommGroup μ] (E : AltPairing A μ)

/-- Multiplicative notation for an alternating pairing. -/
def pair (x y : A) : μ := Additive.toMul (E.hom x y)

@[simp] theorem pair_zero_left (y : A) : E.pair 0 y = 1 := by
  simp [pair]

@[simp] theorem pair_zero_right (x : A) : E.pair x 0 = 1 := by
  simp [pair]

theorem pair_add_left (x y z : A) : E.pair (x + y) z = E.pair x z * E.pair y z := by
  simp [pair, map_add]

theorem pair_add_right (x y z : A) : E.pair x (y + z) = E.pair x y * E.pair x z := by
  simp [pair, map_add]

@[simp] theorem pair_self (x : A) : E.pair x x = 1 := by
  simp [pair, E.alternating x]

theorem pair_zsmul_left (a : ℤ) (x y : A) : E.pair (a • x) y = E.pair x y ^ a := by
  simp [pair, map_zsmul]

theorem pair_zsmul_right (b : ℤ) (x y : A) : E.pair x (b • y) = E.pair x y ^ b := by
  simp [pair, map_zsmul]

theorem pair_nsmul_left (a : ℕ) (x y : A) : E.pair (a • x) y = E.pair x y ^ a := by
  simp [pair, map_nsmul]

theorem pair_nsmul_right (b : ℕ) (x y : A) : E.pair x (b • y) = E.pair x y ^ b := by
  simp [pair, map_nsmul]

theorem pair_neg_left (x y : A) : E.pair (-x) y = (E.pair x y)⁻¹ := by
  have h : E.pair (-x) y * E.pair x y = 1 := by
    rw [← E.pair_add_left, neg_add_cancel, E.pair_zero_left]
  exact eq_inv_of_mul_eq_one_left h

theorem pair_sub_left (x y z : A) :
    E.pair (x - y) z = E.pair x z * (E.pair y z)⁻¹ := by
  rw [sub_eq_add_neg, E.pair_add_left, E.pair_neg_left]

/-- Skew symmetry is a consequence of alternation. -/
theorem skew (x y : A) : E.pair y x = (E.pair x y)⁻¹ := by
  have h := E.pair_self (x + y)
  rw [E.pair_add_left, E.pair_add_right, E.pair_add_right, E.pair_self, E.pair_self,
    one_mul, mul_one] at h
  exact eq_inv_of_mul_eq_one_right h

/-- **Classification of alternating pairings.**  On the subgroup generated by two
elements, every alternating pairing is a power of the determinant form. -/
theorem pair_coords (e₁ e₂ : A) (a b c d : ℤ) :
    E.pair (a • e₁ + b • e₂) (c • e₁ + d • e₂) = E.pair e₁ e₂ ^ (a * d - b * c) := by
  rw [E.pair_add_left, E.pair_add_right, E.pair_add_right, E.pair_zsmul_left,
    E.pair_zsmul_left, E.pair_zsmul_left, E.pair_zsmul_left, E.pair_zsmul_right,
    E.pair_zsmul_right, E.pair_zsmul_right, E.pair_zsmul_right, E.pair_self, E.pair_self,
    E.skew e₁ e₂, zpow_sub]
  simp [← zpow_mul, mul_comm]

/-- Two alternating pairings that agree on a generating pair agree on the whole
subgroup generated by that pair. -/
theorem ext_of_basis (E' : AltPairing A μ) (e₁ e₂ : A)
    (h : E.pair e₁ e₂ = E'.pair e₁ e₂) (a b c d : ℤ) :
    E.pair (a • e₁ + b • e₂) (c • e₁ + d • e₂) =
      E'.pair (a • e₁ + b • e₂) (c • e₁ + d • e₂) := by
  rw [E.pair_coords, E'.pair_coords, h]

end AltPairing

variable {F : Type u} [Field F] [DecidableEq F]

/-- Every Weil pairing is in particular an alternating pairing. -/
def WeilPairing.toAltPairing {W : WeierstrassCurve F} {n : ℕ} {μ : Type v} [CommGroup μ]
    (e : WeilPairing W n μ) : AltPairing (torsionPoints W n) μ where
  hom := e.hom
  alternating := e.alternating

@[simp] theorem WeilPairing.toAltPairing_pair {W : WeierstrassCurve F} {n : ℕ}
    {μ : Type v} [CommGroup μ] (e : WeilPairing W n μ) (P Q : torsionPoints W n) :
    e.toAltPairing.pair P Q = e.pair P Q := rfl

/-! ## The explicit determinant pairing on `(ZMod n)²` -/

/-- The determinant form on `(ZMod n)²`. -/
def detForm (n : ℕ) (v w : ZMod n × ZMod n) : ZMod n := v.1 * w.2 - v.2 * w.1

/-- The determinant form, as an additive homomorphism in the second variable. -/
def detFormRight (n : ℕ) (v : ZMod n × ZMod n) : (ZMod n × ZMod n) →+ ZMod n where
  toFun w := detForm n v w
  map_zero' := by simp [detForm]
  map_add' w w' := by simp only [detForm, Prod.fst_add, Prod.snd_add]; ring

/-- The determinant form, as a bi-additive map. -/
def detBihom (n : ℕ) : (ZMod n × ZMod n) →+ ((ZMod n × ZMod n) →+ ZMod n) where
  toFun v := detFormRight n v
  map_zero' := by ext w; simp [detFormRight, detForm]
  map_add' v v' := by
    ext w
    simp only [detFormRight, detForm, AddMonoidHom.coe_mk, ZeroHom.coe_mk,
      AddMonoidHom.add_apply, Prod.fst_add, Prod.snd_add]
    ring

/-- Every element of `Multiplicative (ZMod n)` is an `n`-th root of unity: this is the
canonical model of `μₙ` used below. -/
theorem multiplicative_zmod_pow_self (n : ℕ) (z : Multiplicative (ZMod n)) : z ^ n = 1 := by
  have : z ^ n = Multiplicative.ofAdd (n • Multiplicative.toAdd z) := by
    rw [ofAdd_nsmul]; rfl
  rw [this, nsmul_eq_mul, ZMod.natCast_self, zero_mul]
  rfl

/-- The determinant pairing on `(ZMod n)²` with values in `Multiplicative (ZMod n)`,
the canonical model of the group of `n`-th roots of unity. -/
def detPairing (n : ℕ) : AltPairing (ZMod n × ZMod n) (Multiplicative (ZMod n)) where
  hom := detBihom n
  alternating := by
    intro v
    show detForm n v v = 0
    simp [detForm, mul_comm]

@[simp] theorem detPairing_apply (n : ℕ) (v w : ZMod n × ZMod n) :
    (detPairing n).pair v w = Multiplicative.ofAdd (detForm n v w) := rfl

/-- The determinant pairing takes the value `ofAdd 1` on the standard basis, i.e. its
root of unity is the canonical generator. -/
theorem detPairing_basis (n : ℕ) :
    (detPairing n).pair ((1 : ZMod n), (0 : ZMod n)) ((0 : ZMod n), (1 : ZMod n)) =
      Multiplicative.ofAdd (1 : ZMod n) := by
  simp [detForm]

/-- Coordinates: `(ZMod n)²` is generated by the standard basis, with integer scalars. -/
theorem zmod_prod_coords {n : ℕ} [NeZero n] (w : ZMod n × ZMod n) :
    ((w.1.val : ℤ) • ((1 : ZMod n), (0 : ZMod n)) +
      (w.2.val : ℤ) • ((0 : ZMod n), (1 : ZMod n))) = w := by
  ext <;> simp [zsmul_eq_mul]

/-- **Nondegeneracy of the determinant pairing.** -/
theorem detPairing_nondegenerate_left {n : ℕ} (v : ZMod n × ZMod n)
    (h : ∀ w, (detPairing n).pair v w = 1) : v = 0 := by
  have h1 := h ((0 : ZMod n), (1 : ZMod n))
  have h2 := h ((1 : ZMod n), (0 : ZMod n))
  simp only [detPairing_apply, detForm, ofAdd_eq_one] at h1 h2
  have hv1 : v.1 = 0 := by simpa using h1
  have hv2 : v.2 = 0 := by
    have : -v.2 = 0 := by simpa using h2
    simpa using neg_eq_zero.mp this
  exact Prod.ext hv1 hv2

theorem detPairing_nondegenerate_right {n : ℕ} (w : ZMod n × ZMod n)
    (h : ∀ v, (detPairing n).pair v w = 1) : w = 0 := by
  refine detPairing_nondegenerate_left w fun v => ?_
  rw [(detPairing n).skew v w, h v, inv_one]

/-! ## Transporting pairings and the existence theorem -/

/-- Pull back a bi-additive map along an additive homomorphism. -/
def bihomComp {A B M : Type*} [AddCommGroup A] [AddCommGroup B] [AddCommGroup M]
    (f : B →+ B →+ M) (g : A →+ B) : A →+ A →+ M where
  toFun a := (f (g a)).comp g
  map_zero' := by ext b; simp
  map_add' a a' := by ext b; simp

@[simp] theorem bihomComp_apply {A B M : Type*} [AddCommGroup A] [AddCommGroup B]
    [AddCommGroup M] (f : B →+ B →+ M) (g : A →+ B) (a a' : A) :
    bihomComp f g a a' = f (g a) (g a') := rfl

/-- Transport an alternating pairing along an additive homomorphism. -/
def AltPairing.comap {A B : Type*} [AddCommGroup A] [AddCommGroup B] {μ : Type v}
    [CommGroup μ] (E : AltPairing B μ) (g : A →+ B) : AltPairing A μ where
  hom := bihomComp E.hom g
  alternating P := E.alternating (g P)

@[simp] theorem AltPairing.comap_pair {A B : Type*} [AddCommGroup A] [AddCommGroup B]
    {μ : Type v} [CommGroup μ] (E : AltPairing B μ) (g : A →+ B) (x y : A) :
    (E.comap g).pair x y = E.pair (g x) (g y) := rfl

/-- **Existence of the Weil pairing in the determinant model.**  If the `n`-torsion of a
Weierstrass curve is isomorphic to `(ZMod n)²` — the classical structure theorem for
elliptic-curve torsion in characteristic prime to `n` — then the axioms of `WeilPairing`
are satisfied by an explicit pairing with values in `μₙ ≅ Multiplicative (ZMod n)`.
In particular the catalog axioms are consistent and non-vacuous. -/
def weilPairingOfEquiv {W : WeierstrassCurve F} {n : ℕ}
    (φ : torsionPoints W n ≃+ (ZMod n × ZMod n)) :
    WeilPairing W n (Multiplicative (ZMod n)) where
  hom := bihomComp (detPairing n).hom φ.toAddMonoidHom
  alternating P := (detPairing n).alternating (φ P)
  image_torsion P Q := multiplicative_zmod_pow_self n _
  nondegenerate_left := by
    intro P hP
    have hzero : φ P = 0 := by
      refine detPairing_nondegenerate_left (φ P) fun w => ?_
      have h := hP (φ.symm w)
      rw [bihomComp_apply, AddEquiv.coe_toAddMonoidHom, φ.apply_symm_apply] at h
      have hrw : (detPairing n).pair (φ P) w
          = Additive.toMul ((detPairing n).hom (φ P) w) := rfl
      rw [hrw, h]
      rfl
    simpa using (AddEquiv.map_eq_zero_iff φ).mp hzero
  nondegenerate_right := by
    intro Q hQ
    have hzero : φ Q = 0 := by
      refine detPairing_nondegenerate_right (φ Q) fun v => ?_
      have h := hQ (φ.symm v)
      rw [bihomComp_apply, AddEquiv.coe_toAddMonoidHom, φ.apply_symm_apply] at h
      have hrw : (detPairing n).pair v (φ Q)
          = Additive.toMul ((detPairing n).hom v (φ Q)) := rfl
      rw [hrw, h]
      rfl
    simpa using (AddEquiv.map_eq_zero_iff φ).mp hzero

end Cryptography.WeilBLS