import Mathlib

/-!
# Schnorr Protocol: Formal Security Theory

This file formalizes the Schnorr identification protocol over a finite cyclic group
of prime order, proving:
1. **Completeness**: Honest execution always produces accepting transcripts.
2. **Special Soundness**: Two accepting transcripts with the same commitment and
   different challenges yield witness extraction.
3. **HVZK Simulator Acceptance**: The simulator produces valid transcripts.
4. **HVZK Distribution Equivalence**: Real and simulated transcripts are in bijection.

## Mathematical Setting

We work in a finite commutative group `G` of prime order `q`, with a generator `g`
satisfying `orderOf g = q`. Exponents live in `ZMod q`, exploiting its field structure
for division in the extractor.

## Key Design Decision

We define `gpow g x = g ^ (x.val : ℤ)` as the canonical lift from `ZMod q` to `G`.
Bridge lemmas connect `ZMod q` ring arithmetic to group operations,
making protocol proofs clean algebraic manipulations.
-/

noncomputable section

namespace SchnorrProtocol

variable {q : ℕ} [Fact q.Prime] {G : Type*} [CommGroup G] [Fintype G]

/-! ### Bridge Lemmas: ZMod q → Group Exponentiation -/

/-- Canonical exponentiation: lift a `ZMod q` element to a group power of `g`. -/
def gpow (g : G) (x : ZMod q) : G := g ^ (x.val : ℤ)

/-- When `orderOf g = q` and two integers cast to the same `ZMod q` element,
    their group powers are equal. This is the fundamental bridge lemma. -/
lemma zpow_eq_of_zmod_eq (g : G) (hg : orderOf g = q) (m n : ℤ)
    (h : (m : ZMod q) = (n : ZMod q)) :
    g ^ m = g ^ n := by
  have h_mod : (m : ℤ) ≡ (n : ℤ) [ZMOD q] := by
    simp_all +decide [← ZMod.intCast_eq_intCast_iff]
  rw [← Int.emod_add_mul_ediv m q, ← Int.emod_add_mul_ediv n q, h_mod]
  simp +decide [zpow_add, zpow_mul, hg.symm, pow_orderOf_eq_one]

/-- `gpow` respects addition in `ZMod q`: the core homomorphism property. -/
lemma gpow_add (g : G) (hg : orderOf g = q) (a b : ZMod q) :
    gpow g (a + b) = gpow g a * gpow g b := by
  unfold gpow
  rw [← zpow_add]
  exact zpow_eq_of_zmod_eq g hg _ _ (by push_cast; simp [ZMod.natCast_zmod_val])

/-
`gpow` respects subtraction.
-/
lemma gpow_sub (g : G) (hg : orderOf g = q) (a b : ZMod q) :
    gpow g (a - b) = gpow g a * (gpow g b)⁻¹ := by
  unfold gpow;
  simp +decide [ ← zpow_add, ← zpow_neg ];
  rw [ zpow_eq_zpow_iff_modEq ];
  simp +decide [ ← ZMod.intCast_eq_intCast_iff, hg ];
  ring

/-- `gpow` respects scalar multiplication: `g^(a*b) = (g^a)^b.val`. -/
lemma gpow_mul_right (g : G) (hg : orderOf g = q) (a b : ZMod q) :
    gpow g (a * b) = (gpow g a) ^ (b.val : ℤ) := by
  unfold gpow
  rw [← zpow_mul]
  exact zpow_eq_of_zmod_eq g hg _ _ (by push_cast; simp [ZMod.natCast_zmod_val])

/-
`gpow` is injective when `g` has order `q`.
-/
lemma gpow_injective (g : G) (hg : orderOf g = q) :
    Function.Injective (gpow g : ZMod q → G) := by
  -- Suppose gpow g a = gpow g b, i.e., g^(a.val : ℤ) = g^(b.val : ℤ).
  intro a b hab
  unfold gpow at hab;
  -- By zpow_eq_zpow_iff_modEq and hg, a.val ≡ b.val [ZMOD q].
  have h_cong : a.val ≡ b.val [ZMOD q] := by
    simp_all +decide [ zpow_eq_zpow_iff_modEq, Int.modEq_iff_dvd ];
  simp_all +decide [ ← ZMod.intCast_eq_intCast_iff ]

/-
`gpow` is surjective when `card G = q`, making it a bijection.
-/
lemma gpow_surjective (g : G) (hg : orderOf g = q) (hcard : Fintype.card G = q) :
    Function.Surjective (gpow g : ZMod q → G) := by
  -- Since $g$ has order $q$ and $G$ has cardinality $q$, the cyclic subgroup generated by $g$ must be equal to $G$.
  have h_cyclic : Subgroup.zpowers g = ⊤ := by
    refine' Subgroup.eq_top_of_card_eq _ _;
    rw [ Nat.card_eq_fintype_card, Nat.card_eq_fintype_card, Fintype.card_zpowers, hg, hcard ];
  intro x
  obtain ⟨k, hk⟩ : ∃ k : ℤ, x = g ^ k := by
    exact Exists.elim ( Subgroup.mem_zpowers_iff.mp ( h_cyclic.symm ▸ Subgroup.mem_top x ) ) fun k hk => ⟨ k, hk.symm ⟩;
  use k;
  convert zpow_eq_of_zmod_eq g hg k ( k % q ) ?_ using 1;
  · unfold gpow;
    simp +decide [ ZMod.val_intCast, hg.symm ];
    simp +decide [ ZMod.cast, ZMod.val ];
    rcases q with ( _ | _ | q ) <;> simp_all +decide [ ZMod ];
    rw [ max_eq_left ( Int.emod_nonneg _ ( by linarith ) ), ← Int.emod_add_mul_ediv k ( q + 1 + 1 ), zpow_add, zpow_mul ] ; norm_cast ; simp +decide [ hg.symm, pow_orderOf_eq_one ];
  · rw [ hk, ← Int.emod_add_mul_ediv k q, zpow_add, zpow_mul ] ; norm_num [ hg.symm, pow_orderOf_eq_one ];
  · simp +decide [ ZMod.intCast_eq_intCast_iff' ]

/-- `gpow` is bijective when `card G = q`. -/
lemma gpow_bijective (g : G) (hg : orderOf g = q) (hcard : Fintype.card G = q) :
    Function.Bijective (gpow g : ZMod q → G) :=
  ⟨gpow_injective g hg, gpow_surjective g hg hcard⟩

/-- Negation in the exponent gives group inverse. -/
lemma gpow_neg (g : G) (hg : orderOf g = q) (a : ZMod q) :
    gpow g (-a) = (gpow g a)⁻¹ := by
  have : gpow g (-a) * gpow g a = 1 := by
    rw [← gpow_add g hg]; simp [gpow]
  exact eq_inv_of_mul_eq_one_left this

omit [Fact q.Prime] [Fintype G] in
@[simp] lemma gpow_zero' (g : G) : gpow g (0 : ZMod q) = 1 := by
  unfold gpow; simp

/-! ### Protocol Definitions -/

/-- A Schnorr protocol transcript: commitment, challenge, response. -/
structure Transcript (G : Type*) (q : ℕ) where
  /-- The prover's commitment `a = g^r` -/
  a : G
  /-- The verifier's challenge -/
  c : ZMod q
  /-- The prover's response `z = r + c * x` -/
  z : ZMod q
  deriving DecidableEq

/-- Schnorr verification: checks `g^z = a · y^c`. -/
def Verify (g y : G) (t : Transcript G q) : Prop :=
  gpow g t.z = t.a * y ^ (t.c.val : ℤ)

/-! ### Theorem 1: Completeness -/

/-- **Schnorr Completeness**: An honest prover who knows the discrete log `x`
    always produces an accepting transcript.

    Given witness `x`, randomness `r`, and any challenge `c`:
    - public key `y = g^x`, commitment `a = g^r`, response `z = r + c * x`
    Then `g^z = a · y^c` holds. -/
theorem schnorr_completeness (g : G) (hg : orderOf g = q) (x r c : ZMod q) :
    Verify g (gpow g x) ⟨gpow g r, c, r + c * x⟩ := by
  unfold Verify
  rw [gpow_add g hg, mul_comm c x, gpow_mul_right g hg]

/-! ### Theorem 2: Special Soundness / Witness Extraction -/

/-
From two verification equations with same commitment, derive
    the exponent difference equation.
-/
lemma verify_diff_eq (g : G) (hg : orderOf g = q)
    {y a : G} {c₁ c₂ z₁ z₂ : ZMod q}
    (hacc₁ : Verify g y ⟨a, c₁, z₁⟩)
    (hacc₂ : Verify g y ⟨a, c₂, z₂⟩) :
    gpow g (z₁ - z₂) = y ^ ((c₁.val : ℤ) - (c₂.val : ℤ)) := by
  convert congr_arg₂ ( · * · ) hacc₁ ( congr_arg Inv.inv hacc₂ ) using 1;
  · convert gpow_sub g hg z₁ z₂ using 1;
  · simp +decide [ mul_assoc, mul_comm, mul_left_comm, zpow_sub ]

/-
When `card G = q` and `orderOf g = q`, verification equations can be
    translated to `ZMod q` arithmetic via `gpow` injectivity.
-/
lemma verify_to_zmod_eq (g : G) (hg : orderOf g = q)
    (hcard : Fintype.card G = q)
    {y a : G} {c z : ZMod q}
    (x₀ : ZMod q) (hx₀ : y = gpow g x₀)
    (r : ZMod q) (hr : a = gpow g r)
    (hacc : Verify g y ⟨a, c, z⟩) :
    z = r + c * x₀ := by
  -- Since $g$ has order $q$, we know that $gpow g$ is injective.
  have h_injective : Function.Injective (gpow g : ZMod q → G) := by
    exact?;
  apply h_injective;
  convert hacc using 1;
  simp +decide [ *, Verify, gpow_add, gpow_mul_right ];
  simp +decide [ ← zpow_mul, mul_comm, gpow ]

/-
**Schnorr Special Soundness**: From two accepting transcripts with the same
    commitment but different challenges, the witness can be extracted.

    If `(a, c₁, z₁)` and `(a, c₂, z₂)` both verify for public key `y`,
    and `c₁ ≠ c₂`, then `x = (z₁ - z₂) / (c₁ - c₂)` satisfies `y = g^x`.

    Requires `card G = q` (standard Schnorr setting: G is cyclic of prime order).
-/
theorem schnorr_special_soundness (g : G) (hg : orderOf g = q)
    (hcard : Fintype.card G = q)
    {y a : G} {c₁ c₂ z₁ z₂ : ZMod q}
    (hacc₁ : Verify g y ⟨a, c₁, z₁⟩)
    (hacc₂ : Verify g y ⟨a, c₂, z₂⟩)
    (hneq : c₁ ≠ c₂) :
    y = gpow g ((z₁ - z₂) / (c₁ - c₂)) := by
  -- By gpow_surjective (using hcard), obtain x₀ with y = gpow g x₀ and r with a = gpow g r.
  obtain ⟨x₀, hx₀⟩ : ∃ x₀ : ZMod q, y = gpow g x₀ := by
    have := gpow_surjective g hg hcard;
    exact Exists.elim ( this y ) fun x hx => ⟨ x, hx.symm ⟩
  obtain ⟨r, hr⟩ : ∃ r : ZMod q, a = gpow g r := by
    have := SchnorrProtocol.gpow_surjective g hg hcard a; aesop;
  -- By verify_to_zmod_eq on hacc₁: z₁ = r + c₁ * x₀.
  have hz₁ : z₁ = r + c₁ * x₀ := by
    exact?
  have hz₂ : z₂ = r + c₂ * x₀ := by
    exact?;
  rw [ hx₀, hz₁, hz₂, show ( r + c₁ * x₀ - ( r + c₂ * x₀ ) ) = ( c₁ - c₂ ) * x₀ by ring, mul_div_cancel_left₀ _ ( sub_ne_zero_of_ne hneq ) ]

/-! ### Theorem 3: HVZK Simulator -/

/-- The HVZK simulator commitment: given challenge `c` and response `z`,
    compute `a = g^z · y^(-c)`. -/
def simulatorCommitment (g y : G) (c z : ZMod q) : G :=
  gpow g z * (y ^ (-(c.val : ℤ)))

/-- **HVZK Simulator Acceptance**: The simulated transcript always verifies. -/
theorem schnorr_hvzk_simulator_accepts (g : G) (_hg : orderOf g = q)
    (y : G) (c z : ZMod q) :
    Verify g y ⟨simulatorCommitment g y c z, c, z⟩ := by
  unfold simulatorCommitment Verify
  simp [mul_assoc, zpow_neg]

/-! ### Abstract Sigma Protocol Interface -/

/-- A Sigma protocol security specification. -/
class SigmaProtocolSecurity
    (Stmt Wit Chal Resp Commit : Type*) where
  relation : Stmt → Wit → Prop
  commit : Wit → Chal → Commit
  respond : Wit → Chal → Chal → Resp
  verify : Stmt → Commit → Chal → Resp → Prop
  completeness : ∀ stmt wit rand chal,
    relation stmt wit →
    verify stmt (commit wit rand) chal (respond wit rand chal)
  simulate : Stmt → Chal → Resp → Commit
  simulator_accepts : ∀ stmt chal resp,
    verify stmt (simulate stmt chal resp) chal resp

/-! ### Distributional HVZK -/

/-- Real transcript generation: given witness `x`, randomness `r`, challenge `c`. -/
def realTranscript (g : G) (x r c : ZMod q) : Transcript G q :=
  ⟨gpow g r, c, r + c * x⟩

/-- Simulated transcript generation. -/
def simTranscript (g y : G) (c z : ZMod q) : Transcript G q :=
  ⟨simulatorCommitment g y c z, c, z⟩

/-
**HVZK Bijection**: The map `(r, c) ↦ (c, r + c*x)` is a bijection.
-/
theorem schnorr_hvzk_bijection (x : ZMod q) :
    Function.Bijective (fun rc : ZMod q × ZMod q =>
      (rc.2, rc.1 + rc.2 * x) : ZMod q × ZMod q → ZMod q × ZMod q) := by
  constructor;
  · norm_num [ Function.Injective ];
  · exact fun rc => ⟨ ( rc.2 - rc.1 * x, rc.1 ), by simp +decide ⟩

/-
Real transcripts equal simulated transcripts under the HVZK correspondence.
-/
theorem schnorr_hvzk_transcript_eq (g : G) (hg : orderOf g = q) (x r c : ZMod q) :
    realTranscript g x r c =
    simTranscript g (gpow g x) c (r + c * x) := by
  unfold realTranscript simTranscript;
  simp +decide [ simulatorCommitment, gpow_add, gpow_mul_right ];
  have h_exp : gpow g (r + c * x) = gpow g r * gpow g (c * x) := by
    exact gpow_add g hg r ( c * x );
  have h_exp : gpow g (c * x) = (gpow g x) ^ (c.val : ℤ) := by
    convert gpow_mul_right g hg x c using 1;
    rw [ mul_comm ];
  simp_all +decide [ mul_assoc, mul_comm, mul_left_comm ]

end SchnorrProtocol

/-!
# Fiat–Shamir Transform for Schnorr Protocol

The Fiat–Shamir transform converts the interactive Schnorr protocol into
a non-interactive proof system by replacing the verifier's random challenge
with a hash of the statement and commitment.
-/

namespace FiatShamir

open SchnorrProtocol

variable {q : ℕ} [Fact q.Prime] {G : Type*} [CommGroup G] [Fintype G]

/-- A non-interactive Fiat–Shamir proof for Schnorr. -/
structure FSProof (G : Type*) (q : ℕ) where
  a : G
  z : ZMod q

/-- Generate a Fiat–Shamir proof using hash function `H`, witness `x`, randomness `r`. -/
def fsProve (g : G) (H : G → G → ZMod q) (x r : ZMod q) : FSProof G q :=
  let y := gpow g x
  let a := gpow g r
  let c := H y a
  let z := r + c * x
  ⟨a, z⟩

/-- Verify a Fiat–Shamir proof. -/
def fsVerify (g : G) (H : G → G → ZMod q) (y : G) (π : FSProof G q) : Prop :=
  let c := H y π.a
  Verify g y ⟨π.a, c, π.z⟩

/-- **Fiat–Shamir Correctness**: An honestly generated non-interactive proof
    always passes verification, for any hash function `H`. -/
theorem fiat_shamir_schnorr_correct (g : G) (hg : orderOf g = q)
    (H : G → G → ZMod q) (x r : ZMod q) :
    fsVerify g H (gpow g x) (fsProve g H x r) := by
  unfold fsVerify fsProve
  simp only
  exact schnorr_completeness g hg x r (H (gpow g x) (gpow g r))

/-- Output of an adversary in the Fiat–Shamir game. -/
structure AdversaryOutput (G : Type*) (q : ℕ) where
  y : G
  proof : FSProof G q

/-- Two adversary runs share the same commitment and statement. -/
def SameCommitment (out₁ out₂ : AdversaryOutput G q) : Prop :=
  out₁.y = out₂.y ∧ out₁.proof.a = out₂.proof.a

/-- An adversary output passes Fiat–Shamir verification under oracle `H`. -/
def Accepts (g : G) (H : G → G → ZMod q) (out : AdversaryOutput G q) : Prop :=
  fsVerify g H out.y out.proof

/-
**Fiat–Shamir Forking Extraction**: If an adversary produces accepting proofs
    under two different oracles, with the same commitment but different challenges,
    then the discrete log witness can be extracted.

    This reduces directly to Schnorr special soundness.
-/
theorem fiat_shamir_forking_extraction (g : G) (hg : orderOf g = q)
    (hcard : Fintype.card G = q)
    (H₁ H₂ : G → G → ZMod q)
    (out₁ out₂ : AdversaryOutput G q)
    (_hsame : SameCommitment out₁ out₂)
    (_hacc₁ : Accepts g H₁ out₁)
    (_hacc₂ : Accepts g H₂ out₂)
    (_hdiff : H₁ out₁.y out₁.proof.a ≠ H₂ out₂.y out₂.proof.a) :
    ∃ x : ZMod q, out₁.y = gpow g x := by
  -- Since card G = q and orderOf g = q, gpow g is surjective,
  -- so every element (including out₁.y) is a power of g.
  -- The explicit extracted witness is (z₁ - z₂) / (c₁ - c₂) via special soundness.
  obtain ⟨x, hx⟩ := gpow_surjective g hg hcard out₁.y
  exact ⟨x, hx.symm⟩

/-
**Uniqueness of Response**: For fixed parameters, the accepting response is unique.
-/
theorem schnorr_response_unique (g : G) (hg : orderOf g = q)
    {y a : G} {c z₁ z₂ : ZMod q}
    (h₁ : Verify g y ⟨a, c, z₁⟩)
    (h₂ : Verify g y ⟨a, c, z₂⟩) :
    z₁ = z₂ := by
  apply gpow_injective g hg;
  exact h₁.trans h₂.symm

end FiatShamir