import Mathlib
import Catalog.Shared.ProofRefinement
import Catalog.Cryptography.NoetherianCertification

/-!
# Self-Improving Cryptographic Certificates

A certificate is represented by a proof tree together with the proposition it
certifies. Its audited complexity is the sum of tree length, tree depth, and the
number of named lemmas. Refinement is not an arbitrary reassignment of a natural
number: it is generated by concrete, conclusion-preserving rewrites of the tree.

The principal result synchronizes two termination mechanisms. Proof-tree
simplification is controlled by descent in the natural-valued audited complexity,
while cryptographic key-ideal growth is controlled by the ascending-chain
condition in a Noetherian ring. Consequently, a protocol combining both processes
has a common stage after which neither audited proof complexity nor the key ideal
changes.
-/

namespace Cryptography.SelfImprovingCertificates

open Logic.Propositional
open Learning.ProofRefinement
open Learning.ProofRefinement.ProofTerm

/-- A syntactic certificate for `T`, retaining both an auditable proof tree and
an independent mathematical witness of the certified claim. -/
structure AuditedProof (T : Prop) where
  tree : ProofTerm
  cert : T

/-- The audited cost is exactly length plus depth plus named-lemma count. -/
def AuditedProof.cost {T : Prop} (p : AuditedProof T) : ℕ :=
  combinedPT p.tree

/-- A certificate refines another when one permitted tree rewrite transforms the
old certificate into the new one. Both objects certify the same proposition by
their common type. -/
def Refines {T : Prop} (new old : AuditedProof T) : Prop :=
  Reduces old.tree new.tree

/-- A concrete refinement preserves the asserted propositional conclusion. -/
theorem refines_preserves_conclusion {T : Prop} {new old : AuditedProof T}
    (h : Refines new old) : conclusion new.tree = conclusion old.tree := by
  exact (reduces_conclusion h).symm

/-- Every concrete refinement strictly lowers the audited cost. -/
theorem refines_cost_lt {T : Prop} {new old : AuditedProof T}
    (h : Refines new old) : new.cost < old.cost := by
  exact reduces_combined_lt h

/-- Concrete refinement of audited certificates is well-founded. -/
theorem refines_wellFounded {T : Prop} :
    WellFounded (Refines : AuditedProof T → AuditedProof T → Prop) := by
  exact InvImage.wf AuditedProof.tree Learning.ProofRefinement.refinement_terminates

/-- There is no infinite sequence in which every certificate is a concrete
refinement of its predecessor. -/
theorem no_infinite_concrete_refinement {T : Prop} :
    ¬ ∃ f : ℕ → AuditedProof T, ∀ n, Refines (f (n + 1)) (f n) := by
  rintro ⟨f, hf⟩
  obtain ⟨p, ⟨n, rfl⟩, hmin⟩ :=
    refines_wellFounded.has_min (Set.range f) ⟨f 0, 0, rfl⟩
  exact hmin (f (n + 1)) ⟨n + 1, rfl⟩ (hf n)

/-- Any non-increasing sequence of audited costs eventually stabilizes. This
allows protocol rounds that leave a proof unchanged as well as rounds that
strictly simplify it. -/
theorem audited_cost_eventually_constant {T : Prop} (p : ℕ → AuditedProof T)
    (hcost : Antitone fun n => (p n).cost) :
    ∃ N, ∀ n, N ≤ n → (p n).cost = (p N).cost := by
  let values : Set ℕ := Set.range fun n => (p n).cost
  obtain ⟨c, ⟨N, hN⟩, hc⟩ := Nat.lt_wfRel.wf.has_min values ⟨(p 0).cost, 0, rfl⟩
  refine ⟨N, fun n hn => ?_⟩
  have hle : (p n).cost ≤ (p N).cost := hcost hn
  have hnot : ¬(p n).cost < c := hc (p n).cost ⟨n, rfl⟩
  have hlower : c ≤ (p n).cost := Nat.le_of_not_gt hnot
  rw [← hN] at hlower
  exact Nat.le_antisymm hle hlower

/-- **Synchronized certificate and key-ideal stabilization.** In a Noetherian
cryptographic state space, an antitone sequence of audited proof costs and an
ascending key-ideal protocol admit one common stage after which both components
are constant. -/
theorem synchronized_certificate_key_stabilization
    {R : Type*} [CommRing R] [IsNoetherianRing R] {T : Prop}
    (proofs : ℕ → AuditedProof T) (hcost : Antitone fun n => (proofs n).cost)
    (keys : NoetherianCrypto.NoetherianCertProtocol R) :
    ∃ N, ∀ n, N ≤ n →
      (proofs n).cost = (proofs N).cost ∧ keys.chain n = keys.chain N := by
  obtain ⟨Np, hp⟩ := audited_cost_eventually_constant proofs hcost
  obtain ⟨Nk, hk⟩ := NoetherianCrypto.acc_protocol_termination keys
  let N := max Np Nk
  refine ⟨N, fun n hn => ?_⟩
  have hNpN : Np ≤ N := Nat.le_max_left _ _
  have hNkN : Nk ≤ N := Nat.le_max_right _ _
  have hNpn : Np ≤ n := le_trans hNpN hn
  have hNkn : Nk ≤ n := le_trans hNkN hn
  constructor
  · calc
      (proofs n).cost = (proofs Np).cost := hp n hNpn
      _ = (proofs N).cost := (hp N hNpN).symm
  · calc
      keys.chain n = keys.chain Nk := hk n hNkn
      _ = keys.chain N := (hk N hNkN).symm

/-! ## Irrationality of the square root of two: an explicit audit trail -/

/-- The mathematical claim carried by the worked certificate. -/
abbrev SqrtTwoIrrational : Prop := Irrational (Real.sqrt 2)

/-- A propositional audit label for the claim. -/
def sqrtTwoLabel : Formula := Formula.atom 2

/-- The fully expanded certificate has three redundant restatement layers. -/
def sqrtTwoExpanded : AuditedProof SqrtTwoIrrational :=
  ⟨.restate sqrtTwoLabel
    (.restate sqrtTwoLabel (.restate sqrtTwoLabel (.hyp sqrtTwoLabel))),
    irrational_sqrt_two⟩

/-- The first refinement removes one redundant layer. -/
def sqrtTwoRefined₁ : AuditedProof SqrtTwoIrrational :=
  ⟨.restate sqrtTwoLabel (.restate sqrtTwoLabel (.hyp sqrtTwoLabel)),
    irrational_sqrt_two⟩

/-- The second refinement removes another redundant layer. -/
def sqrtTwoRefined₂ : AuditedProof SqrtTwoIrrational :=
  ⟨.restate sqrtTwoLabel (.hyp sqrtTwoLabel), irrational_sqrt_two⟩

/-- The final certificate contains only the irreducible hypothesis leaf. -/
def sqrtTwoMinimal : AuditedProof SqrtTwoIrrational :=
  ⟨.hyp sqrtTwoLabel, irrational_sqrt_two⟩

/-- The displayed square-root certificates form a three-step sequence of
permitted refinements, rather than merely receiving hand-assigned costs. -/
theorem sqrtTwo_concrete_refinement_chain :
    Refines sqrtTwoRefined₁ sqrtTwoExpanded ∧
    Refines sqrtTwoRefined₂ sqrtTwoRefined₁ ∧
    Refines sqrtTwoMinimal sqrtTwoRefined₂ := by
  constructor
  · exact Reduces.rmRestate _ _ rfl
  constructor
  · exact Reduces.rmRestate _ _ rfl
  · exact Reduces.rmRestate _ _ rfl

/-- The measured costs of the explicit audit trail are `7, 5, 3, 1`; in
particular every displayed step strictly decreases the stipulated complexity. -/
theorem sqrtTwo_measured_costs :
    sqrtTwoExpanded.cost = 7 ∧ sqrtTwoRefined₁.cost = 5 ∧
    sqrtTwoRefined₂.cost = 3 ∧ sqrtTwoMinimal.cost = 1 := by
  norm_num [AuditedProof.cost, combinedPT, Learning.TreeComplexity.combined,
    sqrtTwoExpanded, sqrtTwoRefined₁, sqrtTwoRefined₂, sqrtTwoMinimal,
    length, depth, lemmaCount]

/-- No certificate of the same conclusion can refine the final leaf using the
specified rewrite system. Thus the endpoint is normal, not merely the last item
chosen for display. -/
theorem sqrtTwoMinimal_is_normal :
    ¬ ∃ q : AuditedProof SqrtTwoIrrational, Refines q sqrtTwoMinimal := by
  rintro ⟨q, hq⟩
  cases hq

-- !-- Lab Notes -- !--
-- Hypothesis (ranked by expected impact):
-- 1. [Open-problem subtask: P versus NP/proof complexity] Polynomially bounded
--    normalization lengths for broad propositional proof systems would imply
--    strong uniform proof-search bounds.
-- 2. [Open-problem subtask: P versus NP/proof complexity] A family of short
--    certificates may nevertheless require superpolynomially long local
--    refinement paths under a fixed finite rewrite basis.
-- 3. [Open-problem subtask: circuit lower bounds] Normal-form cost lower bounds
--    may transfer to lower bounds for cryptographic verification circuits.
-- 4. [Cross-domain: rewriting and commutative algebra] Natural-valued proof
--    descent and Noetherian ideal ascent can be synchronized at one finite stage.
-- 5. [Cross-domain: number theory and proof complexity] Irrationality of sqrt(2)
--    admits an explicit audited rewrite chain with costs 7, 5, 3, 1.
-- 6. [Cross-domain: cryptography and order theory] Any antitone certificate-cost
--    schedule eventually stabilizes, even when idle rounds are permitted.
-- Experiment: Conjectures 4--6 were tested as structural theorems. The sqrt(2)
-- chain uses actual tree rewrites, and each statistic was unfolded independently.
-- Numerical search is unnecessary here because all four finite trees are fully
-- enumerated by their constructors and the general claims are order-theoretic.
-- Analysis: The synchronization conjecture survives. The unrestricted claim that
-- a local process must reach a globally Kolmogorov-minimal proof does not: well-
-- foundedness gives termination, but a rewrite system can have several local
-- normal forms and need not reach the globally shortest description.
-- Critique: The mathematical certificate and its audit syntax are deliberately
-- separated. The audit tree labels the claim but does not encode a foundational
-- derivation of real-number irrationality. Accordingly, the results establish
-- termination and measured simplification, not a theorem about uncomputable
-- Kolmogorov complexity. No normal-form uniqueness is asserted.
-- Synthesis: The strongest verified bridge is synchronized stabilization. It
-- combines a genuine proof-complexity descent theorem with the Noetherian ACC,
-- and the concrete irrationality chain demonstrates strict reduction at every
-- selected step.
-- !-- End Lab Notes -- !--

end Cryptography.SelfImprovingCertificates