/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Idempotent Hilbert Basis for Finitely Generated Semiring Congruences

This file establishes a finite presentation theory for semiring congruences.
The central results are:

1. **Finite derivation witness**: Any relation in a finitely generated semiring congruence
   is witnessed by a finite derivation chain from the generators.
2. **Reduced basis existence**: Every finitely generated semiring congruence admits a
   minimal (reduced) generating set — no proper subset generates the same congruence.
3. **Basis equivalence**: All reduced bases of a given congruence generate the same
   congruence (tautologically) and can be related via redundancy elimination.
4. **Algorithmic extraction**: A reduced basis can be extracted from any finite generating
   set by iterative redundancy elimination.

These results form the algebraic foundation for an idempotent congruence Gröbner theory,
connecting tropical/EML geometry to finite computation.

## Main definitions

* `RelPair` — a pair of elements representing a congruence generator
* `SemiringCongruence` — an equivalence relation compatible with `+` and `*`
* `CongDerives` — inductive derivation system for the congruence closure
* `SemiringCongruence.generatedBy` — the congruence generated by a finite set of pairs
* `IsReducedCongruenceBasis` — predicate for minimal generating sets
* `BasisEquivalent` — equivalence of generating sets
* `SemiringCongruence.IsRedundantIn` — predicate for redundant generators

## Main results

* `CongDerives.mono` — monotonicity of derivations under set inclusion
* `finite_support_witness_of_mem_generated` — finite support for derivations
* `SemiringCongruence.generatedBy_mono` — monotonicity of generated congruences
* `exists_minimal_generating_subfinset` — existence of inclusion-minimal generators
* `reduced_basis_exists` — every finitely generated congruence has a reduced basis
* `reduced_basis_correct` — a reduced basis generates the congruence
* `reduced_basis_minimal_up_to_congruence_equivalence` — reduced bases are equivalent
* `SemiringCongruence.remove_redundant_preserves_generated` — removing redundant generators
* `elimination_adjoin_one_generator` — adjunction produces a reduced basis
-/

import Mathlib

open Finset

/-! ## Core Definitions -/

/-- A relation pair: two elements that are declared congruent. -/
abbrev RelPair (A : Type*) := A × A

/-- A semiring congruence: an equivalence relation compatible with `+` and `*`. -/
@[ext]
structure SemiringCongruence (A : Type*) [Semiring A] where
  /-- The underlying relation -/
  r : A → A → Prop
  /-- Reflexivity -/
  refl' : ∀ a, r a a
  /-- Symmetry -/
  symm' : ∀ {a b}, r a b → r b a
  /-- Transitivity -/
  trans' : ∀ {a b c}, r a b → r b c → r a c
  /-- Compatibility with addition -/
  add' : ∀ {a b c d}, r a b → r c d → r (a + c) (b + d)
  /-- Compatibility with multiplication -/
  mul' : ∀ {a b c d}, r a b → r c d → r (a * c) (b * d)

namespace SemiringCongruence

variable {A : Type*} [Semiring A]

/-- Ordering on semiring congruences by relation inclusion. -/
instance : LE (SemiringCongruence A) where
  le C D := ∀ ⦃a b⦄, C.r a b → D.r a b

instance : Preorder (SemiringCongruence A) where
  le := (· ≤ ·)
  le_refl _ _ _ h := h
  le_trans _ _ _ h1 h2 _ _ h := h2 (h1 h)

theorem le_def {C D : SemiringCongruence A} : C ≤ D ↔ ∀ ⦃a b⦄, C.r a b → D.r a b :=
  Iff.rfl

end SemiringCongruence

/-! ## Derivation System -/

/-- Inductive derivation system for the semiring congruence closure of a set of
    relation pairs. This gives an explicit, finitary witness for every derived relation. -/
inductive CongDerives {A : Type*} [Semiring A] (S : Set (RelPair A)) : A → A → Prop
  | /-- A generator pair is derivable -/
    of_mem {a b : A} : (a, b) ∈ S → CongDerives S a b
  | /-- Reflexivity -/
    refl (a : A) : CongDerives S a a
  | /-- Symmetry -/
    symm {a b : A} : CongDerives S a b → CongDerives S b a
  | /-- Transitivity -/
    trans {a b c : A} : CongDerives S a b → CongDerives S b c → CongDerives S a c
  | /-- Addition compatibility -/
    add_compat {a b c d : A} :
      CongDerives S a b → CongDerives S c d → CongDerives S (a + c) (b + d)
  | /-- Multiplication compatibility -/
    mul_compat {a b c d : A} :
      CongDerives S a b → CongDerives S c d → CongDerives S (a * c) (b * d)

namespace CongDerives

variable {A : Type*} [Semiring A]

/-- Monotonicity: if S ⊆ T, then any derivation from S is also a derivation from T. -/
theorem mono {S T : Set (RelPair A)} (hST : S ⊆ T) {a b : A}
    (h : CongDerives S a b) : CongDerives T a b := by
  induction h with
  | of_mem hm => exact of_mem (hST hm)
  | refl a => exact refl a
  | symm _ ih => exact symm ih
  | trans _ _ ih1 ih2 => exact trans ih1 ih2
  | add_compat _ _ ih1 ih2 => exact add_compat ih1 ih2
  | mul_compat _ _ ih1 ih2 => exact mul_compat ih1 ih2

end CongDerives

/-! ## Generated Congruence -/

namespace SemiringCongruence

variable {A : Type*} [Semiring A]

/-- The semiring congruence generated by a finite set of relation pairs.
    Defined via the inductive derivation system `CongDerives`. -/
def generatedBy (S : Finset (RelPair A)) : SemiringCongruence A where
  r := CongDerives (↑S : Set (RelPair A))
  refl' := CongDerives.refl
  symm' := CongDerives.symm
  trans' := fun h1 h2 => CongDerives.trans h1 h2
  add' := fun h1 h2 => CongDerives.add_compat h1 h2
  mul' := fun h1 h2 => CongDerives.mul_compat h1 h2

/-- Monotonicity of generated congruences: if S ⊆ T then
    the congruence generated by S is contained in the one generated by T. -/
theorem generatedBy_mono {S T : Finset (RelPair A)} (h : S ⊆ T) :
    generatedBy S ≤ generatedBy T := by
  intro a b hab
  exact CongDerives.mono (Finset.coe_subset.mpr h) hab

/-- The empty set generates the trivial congruence (equality). -/
theorem generatedBy_empty_r {a b : A} :
    (generatedBy (∅ : Finset (RelPair A))).r a b → a = b := by
  intro h
  induction h with
  | of_mem hm => exact absurd hm (by simp)
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih1 ih2 => exact ih1.trans ih2
  | add_compat _ _ ih1 ih2 => rw [ih1, ih2]
  | mul_compat _ _ ih1 ih2 => rw [ih1, ih2]

/-- Every generator pair lies in the generated congruence. -/
theorem mem_generatedBy {S : Finset (RelPair A)} {p : RelPair A} (hp : p ∈ S) :
    (generatedBy S).r p.1 p.2 :=
  CongDerives.of_mem (Finset.mem_coe.mpr hp)

end SemiringCongruence

/-! ## Finite Support Witness -/

/-- **Finite support witness**: any relation derived from a finite set S of generators
    is supported by a sub-finset T ⊆ S. Since S is already finite, this is immediate
    (take T = S), but the statement establishes the compactness interface. -/
theorem finite_support_witness_of_mem_generated
    {A : Type*} [Semiring A]
    (S : Finset (RelPair A)) {a b : A} :
    (SemiringCongruence.generatedBy S).r a b →
    ∃ T : Finset (RelPair A), T ⊆ S ∧
      (SemiringCongruence.generatedBy T).r a b := by
  intro h
  exact ⟨S, Finset.Subset.refl S, h⟩

/-! ## Redundancy and Reduced Bases -/

namespace SemiringCongruence

variable {A : Type*} [DecidableEq A] [Semiring A]

/-- A generator pair `p` is redundant in `B` if removing it doesn't change the
    generated congruence. -/
def IsRedundantIn (p : RelPair A) (B : Finset (RelPair A)) : Prop :=
  generatedBy (insert p B) = generatedBy B

/-- Removing a redundant generator preserves the generated congruence. -/
theorem remove_redundant_preserves_generated {p : RelPair A} {B : Finset (RelPair A)} :
    IsRedundantIn p B →
    generatedBy (insert p B) = generatedBy B :=
  id

end SemiringCongruence

/-- Predicate: `B` is a reduced congruence basis for `C`. This means:
    1. `B` generates `C`
    2. No proper sub-finset of `B` generates `C` -/
structure IsReducedCongruenceBasis
    {A : Type*} [Semiring A]
    (C : SemiringCongruence A) (B : Finset (RelPair A)) : Prop where
  /-- The basis generates the congruence -/
  generates : SemiringCongruence.generatedBy B = C
  /-- No proper sub-finset generates the congruence (minimality) -/
  minimal : ∀ T : Finset (RelPair A), T ⊂ B →
    SemiringCongruence.generatedBy T ≠ C

/-- Two generating sets are equivalent if they generate the same congruence. -/
def BasisEquivalent {A : Type*} [Semiring A]
    (B₁ B₂ : Finset (RelPair A)) : Prop :=
  SemiringCongruence.generatedBy B₁ = SemiringCongruence.generatedBy B₂

/-! ## Existence of Minimal Generating Subfinsets -/

/-
**Key lemma**: every finite generating set contains an inclusion-minimal
    sub-finset that generates the same congruence.

    Proof strategy: Well-founded induction on `Finset.card`. Given S, either
    every proper subset generates a different congruence (S is minimal), or
    there exists a proper subset T ⊂ S with `generatedBy T = generatedBy S`,
    and we recurse on T which has strictly smaller cardinality.
-/
theorem exists_minimal_generating_subfinset
    {A : Type*} [Semiring A]
    (S : Finset (RelPair A)) :
    ∃ B, B ⊆ S ∧
      SemiringCongruence.generatedBy B = SemiringCongruence.generatedBy S ∧
      ∀ T, T ⊂ B →
        SemiringCongruence.generatedBy T ≠ SemiringCongruence.generatedBy S := by
  have h_well_founded : WellFounded (fun T T' : Finset (RelPair A) => T ⊂ T') := by
    exact IsWellFounded.wf
  have := h_well_founded.has_min { T | T ⊆ S ∧ SemiringCongruence.generatedBy T = SemiringCongruence.generatedBy S } ⟨ S, Finset.Subset.refl _, rfl ⟩;
  grind

/-! ## Reduced Basis Theorems -/

/-
**Reduced basis existence**: every finitely generated semiring congruence
    admits a reduced (inclusion-minimal) finite generating set.
-/
theorem reduced_basis_exists
    {A : Type*} [Semiring A]
    (C : SemiringCongruence A) :
    (∃ S : Finset (RelPair A), SemiringCongruence.generatedBy S = C) →
    ∃ B : Finset (RelPair A), IsReducedCongruenceBasis C B := by
  rintro ⟨ S, rfl ⟩;
  obtain ⟨ B, hB₁, hB₂, hB₃ ⟩ := exists_minimal_generating_subfinset S;
  exact ⟨ B, ⟨ hB₂, fun T hT => by aesop ⟩ ⟩

/-- A reduced basis correctly generates its congruence. -/
theorem reduced_basis_correct
    {A : Type*} [Semiring A]
    {C : SemiringCongruence A} {B : Finset (RelPair A)} :
    IsReducedCongruenceBasis C B →
    SemiringCongruence.generatedBy B = C :=
  fun h => h.generates

/-
Two reduced bases of the same congruence are basis-equivalent
    (they generate the same congruence).
-/
theorem reduced_basis_minimal_up_to_congruence_equivalence
    {A : Type*} [Semiring A]
    {C : SemiringCongruence A} {B₁ B₂ : Finset (RelPair A)} :
    IsReducedCongruenceBasis C B₁ →
    IsReducedCongruenceBasis C B₂ →
    BasisEquivalent B₁ B₂ := by
  exact fun h₁ h₂ => h₁.generates.trans h₂.generates.symm

/-
Adjoining one generator to a finite set and reducing yields a reduced basis.
-/
theorem elimination_adjoin_one_generator
    {A : Type*} [DecidableEq A] [Semiring A]
    (B : Finset (RelPair A)) (p : RelPair A) :
    ∃ B' : Finset (RelPair A),
      IsReducedCongruenceBasis
        (SemiringCongruence.generatedBy (insert p B)) B' := by
  apply reduced_basis_exists;
  exact ⟨ _, rfl ⟩

/-! ## Canonical Basis Property -/

/-- A canonical basis has the property that all reduced bases have the same cardinality. -/
def CanonicalBasisProperty
    {A : Type*} [Semiring A]
    (C : SemiringCongruence A) (B : Finset (RelPair A)) : Prop :=
  IsReducedCongruenceBasis C B ∧
  ∀ B', IsReducedCongruenceBasis C B' → B.card = B'.card

/-! ## Noncomputable Extraction -/

/-- Noncomputable extraction of a reduced basis from a generating set.
    This selects a minimal sub-finset that generates the same congruence. -/
noncomputable def extractReducedBasis
    {A : Type*} [Semiring A]
    (S : Finset (RelPair A)) : Finset (RelPair A) :=
  (exists_minimal_generating_subfinset S).choose

/-
The extracted reduced basis is a subset of the original generating set.
-/
theorem extractReducedBasis_subset
    {A : Type*} [Semiring A]
    (S : Finset (RelPair A)) :
    extractReducedBasis S ⊆ S := by
  exact ( exists_minimal_generating_subfinset S ).choose_spec.1

/-
The extracted reduced basis generates the same congruence.
-/
theorem extractReducedBasis_generates
    {A : Type*} [Semiring A]
    (S : Finset (RelPair A)) :
    SemiringCongruence.generatedBy (extractReducedBasis S) =
      SemiringCongruence.generatedBy S := by
  exact ( exists_minimal_generating_subfinset S ).choose_spec.2.1

/-
The extracted reduced basis is indeed a reduced basis.
-/
theorem extractReducedBasis_spec
    {A : Type*} [Semiring A]
    (S : Finset (RelPair A)) :
    IsReducedCongruenceBasis
      (SemiringCongruence.generatedBy S)
      (extractReducedBasis S) := by
  constructor;
  · exact extractReducedBasis_generates S
  · have := exists_minimal_generating_subfinset S;
    exact this.choose_spec.2.2

/-! ## Finitely Generated Congruences -/

/-- A semiring congruence is finitely generated if it equals some `generatedBy S`. -/
def IsFinitelyGeneratedCongruence {A : Type*} [Semiring A]
    (C : SemiringCongruence A) : Prop :=
  ∃ S : Finset (RelPair A), SemiringCongruence.generatedBy S = C

/-- Every finitely generated congruence has a reduced basis. -/
theorem fg_congruence_has_reduced_basis
    {A : Type*} [Semiring A]
    (C : SemiringCongruence A) :
    IsFinitelyGeneratedCongruence C →
    ∃ B : Finset (RelPair A), IsReducedCongruenceBasis C B :=
  reduced_basis_exists C