import Mathlib

/-!
# The Space–Algebra Rosetta Stone

## Universal Translator: Geometry ↔ Algebra

This file formalizes the eight correspondences between geometry and algebra,
with special emphasis on Row 7 (connected components ↔ idempotent elements),
which bridges directly to the Master Equation of idempotent collapse theory.

## The Dictionary

| GEOMETRY              | ALGEBRA                              |
|-----------------------|--------------------------------------|
| Point                 | Prime ideal                          |
| Open set              | Ring element (basic open D(f))       |
| Continuous map        | Ring homomorphism (contravariant)    |
| Closed subspace       | Ideal (zero locus V(I))             |
| Dimension             | Krull dimension                      |
| Tangent vector        | Derivation (Leibniz rule)            |
| Connected components  | Idempotent elements (e² = e)         |
| Vector bundle         | Projective module                    |

## The Master Equation Bridge

The connected components of Spec(R) are the fixed points of the
idempotent-splitting process. An idempotent e ∈ R with e² = e splits
Spec(R) into two clopen pieces: D(e) and D(1-e) = V(e).
-/

open Set Function PrimeSpectrum TopologicalSpace

noncomputable section

variable {R : Type*} [CommRing R]

/-! ## Row 1: Points ↔ Prime Ideals -/

/-- A point of the prime spectrum is a prime ideal. -/
theorem rosetta_row1_point_is_prime_ideal :
    ∀ (x : PrimeSpectrum R), (x.asIdeal).IsPrime :=
  fun x => x.isPrime

/-! ## Row 2: Open Sets ↔ Ring Elements -/

/-- Basic open sets are generated by ring elements. -/
theorem rosetta_row2_element_gives_open (f : R) :
    IsOpen (basicOpen f : Set (PrimeSpectrum R)) :=
  (basicOpen f).isOpen

/-- The basic opens form a topological basis. -/
theorem rosetta_row2_basic_opens_are_basis :
    IsTopologicalBasis
      (Set.range (fun f : R => (basicOpen f : Set (PrimeSpectrum R)))) :=
  PrimeSpectrum.isTopologicalBasis_basic_opens

/-! ## Row 3: Continuous Maps ↔ Ring Homomorphisms (Contravariant) -/

/-- A ring homomorphism induces a continuous map on spectra (contravariantly). -/
theorem rosetta_row3_ring_hom_gives_continuous_map
    {S : Type*} [CommRing S] (φ : R →+* S) :
    Continuous (PrimeSpectrum.comap φ) :=
  PrimeSpectrum.continuous_comap φ

/-! ## Row 4: Closed Subspaces ↔ Ideals -/

/-- The zero locus of a set of ring elements is closed. -/
theorem rosetta_row4_ideal_gives_closed (s : Set R) :
    IsClosed (PrimeSpectrum.zeroLocus s) :=
  PrimeSpectrum.isClosed_zeroLocus s

/-! ## Row 5: Dimension ↔ Krull Dimension -/

/-- The Krull dimension of a ring equals the order dimension
    of its prime spectrum. -/
theorem rosetta_row5_krull_dim_eq_spec_dim :
    ringKrullDim R = Order.krullDim (PrimeSpectrum R) :=
  rfl

/-! ## Row 6: Tangent Vectors ↔ Derivations (Leibniz Rule) -/

/-- Derivations satisfy the Leibniz rule — the algebraic
    encoding of "tangent vector". -/
theorem rosetta_row6_derivation_leibniz {A M : Type*}
    [CommSemiring A] [AddCommMonoid M] [Module A M] [Module R M] [Algebra R A]
    (D : Derivation R A M) (a b : A) :
    D (a * b) = a • D b + b • D a :=
  D.leibniz a b

/-! ## Row 7: Connected Components ↔ Idempotent Elements (THE BRIDGE)

This is the crucial row that connects the Rosetta Stone to the Master Equation.
Clopen subsets of Spec(R) ↔ Idempotent elements of R. -/

/-- **THE BRIDGE**: Clopen sets in Spec(R) are order-isomorphic to idempotent elements. -/
theorem rosetta_row7_clopens_equiv_idempotents :
    Nonempty ({ e : R // IsIdempotentElem e } ≃o Clopens (PrimeSpectrum R)) :=
  ⟨PrimeSpectrum.isIdempotentElemEquivClopens⟩

/-- An idempotent element determines a clopen subset. -/
theorem rosetta_row7_idempotent_gives_clopen (e : R) (he : IsIdempotentElem e) :
    IsClopen (basicOpen e : Set (PrimeSpectrum R)) :=
  PrimeSpectrum.isClopen_iff.mpr ⟨e, he, rfl⟩

/-- A clopen subset determines an idempotent element. -/
theorem rosetta_row7_clopen_gives_idempotent (s : Set (PrimeSpectrum R))
    (hs : IsClopen s) :
    ∃ e : R, IsIdempotentElem e ∧ s = (basicOpen e : Set (PrimeSpectrum R)) :=
  PrimeSpectrum.exists_idempotent_basicOpen_eq_of_isClopen hs

/-- Idempotents split the spectrum: V(e) = D(1-e). -/
theorem rosetta_row7_idempotent_splits_spectrum (e : R) (he : IsIdempotentElem e) :
    PrimeSpectrum.zeroLocus {e} = (basicOpen (1 - e) : Set (PrimeSpectrum R)) :=
  PrimeSpectrum.zeroLocus_eq_basicOpen_of_isIdempotentElem e he

/-- Each clopen determines a UNIQUE idempotent. -/
theorem rosetta_row7_unique_idempotent (s : Set (PrimeSpectrum R))
    (hs : IsClopen s) :
    ∃! e : R, IsIdempotentElem e ∧ s = (basicOpen e : Set (PrimeSpectrum R)) :=
  PrimeSpectrum.existsUnique_idempotent_basicOpen_eq_of_isClopen hs

/-! ## Row 8: Vector Bundles ↔ Projective Modules -/

/-- Projective modules lift along surjections. -/
theorem rosetta_row8_projective_lifts {M N P : Type*}
    [AddCommMonoid M] [Module R M] [AddCommMonoid N] [Module R N]
    [AddCommMonoid P] [Module R P] [Module.Projective R P]
    (f : M →ₗ[R] N) (g : P →ₗ[R] N) (hf : Surjective f) :
    ∃ h : P →ₗ[R] M, f ∘ₗ h = g :=
  Module.projective_lifting_property f g hf

/-! ## The Master Equation Bridge

The Master Equation f ∘ f = f, translated through the Rosetta Stone:
**connected components = fixed points of the idempotent-splitting process**. -/

/-- Multiplication by an idempotent is an idempotent endomorphism. -/
theorem master_equation_algebraic (e : R) (he : IsIdempotentElem e) :
    ∀ r : R, e * (e * r) = e * r := by
  intro r; rw [← mul_assoc]; exact congr_arg (· * r) he

/-- The complement of an idempotent is idempotent. -/
theorem idempotent_complement (e : R) (he : IsIdempotentElem e) :
    IsIdempotentElem (1 - e) :=
  IsIdempotentElem.one_sub he

/-
PROBLEM
Orthogonal idempotents: if e₁e₂ = 0 then e₂e₁ = 0.

PROVIDED SOLUTION
We have e₁*e₂ = 0, he₁ : e₁*e₁ = e₁, he₂ : e₂*e₂ = e₂. We want e₂*e₁ = 0. Consider (e₂*e₁)² = e₂*e₁*e₂*e₁ = e₂*(e₁*e₂)*e₁ = e₂*0*e₁ = 0. So (e₂*e₁)² = 0. But also note that e₂*e₁ is in a commutative ring, so we can try: multiply horth on left by e₂ and right by e₁. Actually just directly: e₂*e₁ = e₂*(e₁*e₁) = (e₂*e₁)*e₁ and e₂*e₁ = (e₂*e₂)*e₁ = e₂*(e₂*e₁). So (e₂*e₁)*(e₂*e₁) = e₂*(e₁*e₂)*e₁ = 0. So x² = 0 where x = e₂*e₁. Also x = e₂*x (from he₂) = x*e₁ (from he₁). Hmm, but x² = 0 doesn't mean x = 0 in a general commutative ring. Wait—actually for commutative rings, if e₁*e₂ = 0, then since the ring is commutative, e₂*e₁ = e₁*e₂ = 0. CommRing implies commutativity of multiplication!
-/
theorem orthogonal_idempotents_commute (e₁ e₂ : R)
    (_he₁ : IsIdempotentElem e₁) (_he₂ : IsIdempotentElem e₂)
    (horth : e₁ * e₂ = 0) : e₂ * e₁ = 0 := by
  rwa [ mul_comm ]

/-- R decomposes: r = e*r + (1-e)*r for any idempotent e. -/
theorem idempotent_decomposition (e : R)
    (r : R) : r = e * r + (1 - e) * r := by ring

end