import Geometry.MissingDataCohomology

/-!
# Missing information is controlled by restriction maps

This file specializes the catalog's `MissingDataCohomology.DataComplex` to two
finite data complexes with identical cochain-space dimensions.  In the first,
all restriction maps vanish, so every overlap residual survives in `H¹`.  In
the second, the degree-zero coboundary is the identity, so every residual can
be patched and `H¹` vanishes.

Thus feature count and a scalar missing rate cannot by themselves determine
cohomological information loss.  An incidence model and its restriction maps
are indispensable.  We also test the proposed real-valued proxy
`n * r² * log (1/r)`: it is positive at `r = 1/2` (for positive `n`) but zero
at `r = 1`, so it is not increasing throughout the probability interval.
-/

open MissingDataCohomology

namespace MissingInformationCohomology

variable (𝕜 : Type*) [Field 𝕜]

/-- The cochain space with `n` scalar coordinates. -/
abbrev Coordinates (n : ℕ) := Fin n → 𝕜

/-- A data complex whose restriction maps carry no information. -/
def disconnectedComplex (n : ℕ) : DataComplex 𝕜 where
  C0 := Coordinates 𝕜 n
  C1 := Coordinates 𝕜 n
  C2 := Coordinates 𝕜 0
  d0 := 0
  d1 := 0
  d_sq := by simp

/-- A data complex on the same cochain spaces in which every overlap residual
is generated by a degree-zero correction. -/
def patchableComplex (n : ℕ) : DataComplex 𝕜 where
  C0 := Coordinates 𝕜 n
  C1 := Coordinates 𝕜 n
  C2 := Coordinates 𝕜 0
  d0 := LinearMap.id
  d1 := 0
  d_sq := by simp

/-- The two models have exactly the same dimensions in every cochain degree. -/
theorem equal_cochain_dimensions (n : ℕ) :
    Module.finrank 𝕜 (disconnectedComplex 𝕜 n).C0 =
        Module.finrank 𝕜 (patchableComplex 𝕜 n).C0 ∧
    Module.finrank 𝕜 (disconnectedComplex 𝕜 n).C1 =
        Module.finrank 𝕜 (patchableComplex 𝕜 n).C1 ∧
    Module.finrank 𝕜 (disconnectedComplex 𝕜 n).C2 =
        Module.finrank 𝕜 (patchableComplex 𝕜 n).C2 := by
  exact ⟨rfl, rfl, rfl⟩

/-- With zero restriction maps, all `n` overlap coordinates survive in `H¹`. -/
theorem disconnected_h1_finrank (n : ℕ) :
    Module.finrank 𝕜 (disconnectedComplex 𝕜 n).H1 = n := by
  rw [DataComplex.h1_full_of_zero_maps]
  · simp [disconnectedComplex, Coordinates]
  · rfl
  · rfl

/-- With identity patch generation, the first cohomology vanishes. -/
theorem patchable_h1_finrank (n : ℕ) :
    Module.finrank 𝕜 (patchableComplex 𝕜 n).H1 = 0 := by
  apply DataComplex.h1_vanishes_of_surjective_d0
  intro x
  exact ⟨x, rfl⟩

/-- Equal feature/cochain counts can support different obstruction dimensions.
This is a concrete non-identifiability result against any universal formula
using only those scalar counts. -/
theorem same_dimensions_different_h1 {n : ℕ} (hn : 0 < n) :
    Module.finrank 𝕜 (disconnectedComplex 𝕜 n).H1 ≠
      Module.finrank 𝕜 (patchableComplex 𝕜 n).H1 := by
  rw [disconnected_h1_finrank, patchable_h1_finrank]
  omega

/-- The numerical proxy proposed in the mission, with feature count represented
as a real scalar. -/
noncomputable def rateProxy (n r : ℝ) : ℝ := n * r ^ 2 * Real.log (1 / r)

/-- At complete missingness the proposed proxy is zero, not maximal. -/
theorem rateProxy_at_one (n : ℝ) : rateProxy n 1 = 0 := by
  simp [rateProxy]

/-- At missing rate `1/2`, the proxy is strictly positive for a positive feature
count. -/
theorem rateProxy_half_positive {n : ℝ} (hn : 0 < n) :
    0 < rateProxy n (1 / 2) := by
  rw [rateProxy]
  have hlog : 0 < Real.log (2 : ℝ) := Real.log_pos (by norm_num)
  norm_num
  positivity

/-- Consequently, the proposed proxy is not monotone nondecreasing on the full
probability interval `[0,1]`. -/
theorem rateProxy_not_monotone_on_unit {n : ℝ} (hn : 0 < n) :
    ¬ MonotoneOn (rateProxy n) (Set.Icc (0 : ℝ) 1) := by
  intro hmono
  have hle := hmono (by constructor <;> norm_num : (1 / 2 : ℝ) ∈ Set.Icc 0 1)
    (by constructor <;> norm_num : (1 : ℝ) ∈ Set.Icc 0 1) (by norm_num)
  rw [rateProxy_at_one] at hle
  exact (not_lt_of_ge hle) (rateProxy_half_positive hn)

end MissingInformationCohomology