#!/usr/bin/env python3
"""
Algorithms for Subgroup Lattice Möbius Inversion

Implements the core algorithms from the research paper:
1. Subgroup enumeration for S_n
2. Möbius function computation on subgroup lattices
3. Generating pair counting via Möbius inversion
4. Asymptotic approximation comparison

Complexity analysis:
- Subgroup enumeration: O(n!² · n!) pairs × closure computation
- Möbius function: O(s²) where s = number of subgroups
- Generating pair count via Möbius: O(s) after Möbius precomputation
"""

from itertools import permutations
from math import factorial
from fractions import Fraction
from typing import Dict, FrozenSet, List, Set, Tuple
from collections import defaultdict


# ============================================================
# Core permutation operations
# ============================================================

def compose(p: Tuple[int, ...], q: Tuple[int, ...]) -> Tuple[int, ...]:
    """Compose permutations: (p ∘ q)(i) = p(q(i)).

    Args:
        p: First permutation (applied second)
        q: Second permutation (applied first)

    Returns:
        The composition p ∘ q

    Example:
        >>> compose((1, 0, 2), (0, 2, 1))
        (1, 2, 0)
    """
    return tuple(p[q[i]] for i in range(len(p)))


def inverse(p: Tuple[int, ...]) -> Tuple[int, ...]:
    """Compute the inverse permutation.

    Args:
        p: A permutation

    Returns:
        p⁻¹ such that p ∘ p⁻¹ = id

    Example:
        >>> inverse((1, 2, 0))
        (2, 0, 1)
    """
    n = len(p)
    inv = [0] * n
    for i in range(n):
        inv[p[i]] = i
    return tuple(inv)


def identity(n: int) -> Tuple[int, ...]:
    """The identity permutation on {0, ..., n-1}."""
    return tuple(range(n))


# ============================================================
# Algorithm 1: Subgroup Closure
# ============================================================

def closure(generators: List[Tuple[int, ...]], n: int) -> FrozenSet[Tuple[int, ...]]:
    """Compute the subgroup generated by a set of permutations.

    Algorithm: Iterative multiplication closure.
    Start with generators and their inverses, then repeatedly
    multiply all pairs until no new elements appear.

    Complexity: O(|⟨generators⟩|² · n) per iteration,
                O(|⟨generators⟩|) iterations worst case.

    Args:
        generators: List of generating permutations
        n: Degree of the symmetric group

    Returns:
        The subgroup ⟨generators⟩ as a frozenset

    Example:
        >>> sorted(closure([(1, 0, 2)], 3))
        [(0, 1, 2), (1, 0, 2)]
    """
    elements = {identity(n)}
    for g in generators:
        elements.add(g)
        elements.add(inverse(g))

    changed = True
    while changed:
        changed = False
        new = set()
        for a in elements:
            for b in elements:
                c = compose(a, b)
                if c not in elements and c not in new:
                    new.add(c)
                    changed = True
        elements |= new
    return frozenset(elements)


# ============================================================
# Algorithm 2: Subgroup Enumeration
# ============================================================

def enumerate_subgroups(n: int) -> Set[FrozenSet[Tuple[int, ...]]]:
    """Enumerate all subgroups of S_n.

    Algorithm: Generate closures of all 1- and 2-element subsets.
    Since every subgroup of S_n can be generated by at most n-1 elements,
    and we're looking at 2-generated subgroups for our application,
    taking closures of pairs suffices for the Möbius computation.

    Note: For n ≥ 6, this may miss some subgroups that require ≥3 generators.
    For n ≤ 5, every subgroup of S_n is 2-generated, so this is complete.

    Complexity: O(n!² · closure_cost)

    Args:
        n: Degree of symmetric group

    Returns:
        Set of all subgroups (as frozensets)
    """
    all_perms = list(permutations(range(n)))
    subgroups: Set[FrozenSet[Tuple[int, ...]]] = set()

    # Trivial subgroup
    subgroups.add(frozenset([identity(n)]))

    # Cyclic subgroups
    for g in all_perms:
        subgroups.add(closure([g], n))

    # 2-generated subgroups
    for i, g in enumerate(all_perms):
        for h in all_perms[i:]:
            subgroups.add(closure([g, h], n))

    return subgroups


# ============================================================
# Algorithm 3: Möbius Function on Subgroup Lattice
# ============================================================

def compute_moebius(
    subgroups: Set[FrozenSet[Tuple[int, ...]]],
    n: int
) -> Dict[FrozenSet[Tuple[int, ...]], int]:
    """Compute the Möbius function μ(H, S_n) for all subgroups H.

    Algorithm: Top-down recursion on the subgroup lattice.
    Process subgroups in decreasing order of cardinality.
    - μ(S_n, S_n) = 1
    - μ(H, S_n) = -Σ_{K: H ⊊ K ≤ S_n} μ(K, S_n)

    This is the standard recursive Möbius function computation on
    a finite poset, specialized to the subgroup lattice.

    Complexity: O(s²) where s = |subgroups|

    Args:
        subgroups: Set of all subgroups
        n: Degree of symmetric group

    Returns:
        Dictionary mapping each subgroup H to μ(H, S_n)

    Example:
        >>> subs = enumerate_subgroups(2)
        >>> mu = compute_moebius(subs, 2)
        >>> sn = frozenset(permutations(range(2)))
        >>> mu[sn]
        1
    """
    sn = frozenset(permutations(range(n)))
    sorted_subs = sorted(subgroups, key=lambda s: -len(s))

    mu: Dict[FrozenSet[Tuple[int, ...]], int] = {}
    for H in sorted_subs:
        if H == sn:
            mu[H] = 1
        else:
            mu[H] = -sum(
                mu[K] for K in sorted_subs
                if H < K and H.issubset(K)
            )
    return mu


# ============================================================
# Algorithm 4: Generating Pair Count via Möbius Inversion
# ============================================================

def generating_pair_count_moebius(
    subgroups: Set[FrozenSet[Tuple[int, ...]]],
    mu: Dict[FrozenSet[Tuple[int, ...]], int],
    n: int
) -> int:
    """Count generating pairs using the Möbius inversion formula.

    Formula: #{(σ,τ) : ⟨σ,τ⟩ = S_n} = Σ_{H ≤ S_n} μ(H, S_n) · |H|²

    This avoids enumerating all n!² pairs and instead sums over
    the (much smaller) subgroup lattice.

    Complexity: O(s) where s = |subgroups|

    Args:
        subgroups: Set of all subgroups
        mu: Möbius function values
        n: Degree of symmetric group

    Returns:
        Number of generating pairs

    Example:
        >>> subs = enumerate_subgroups(3)
        >>> mu = compute_moebius(subs, 3)
        >>> generating_pair_count_moebius(subs, mu, 3)
        18
    """
    return sum(mu[H] * len(H)**2 for H in subgroups)


# ============================================================
# Algorithm 5: Direct Generating Pair Count
# ============================================================

def generating_pair_count_direct(n: int) -> int:
    """Count generating pairs by direct enumeration.

    Complexity: O(n!² · closure_cost)

    Args:
        n: Degree of symmetric group

    Returns:
        Number of ordered pairs (σ,τ) with ⟨σ,τ⟩ = S_n
    """
    all_perms = list(permutations(range(n)))
    sn = frozenset(all_perms)
    count = 0
    for sigma in all_perms:
        for tau in all_perms:
            if closure([sigma, tau], n) == sn:
                count += 1
    return count


# ============================================================
# Algorithm 6: Asymptotic Analysis
# ============================================================

def asymptotic_analysis(
    n: int,
    exact_prob: Fraction
) -> Dict[str, Fraction]:
    """Compare exact probability with asymptotic approximations.

    Computes:
    - First-order: 1 - 1/n
    - Second-order: 1 - 1/n - 1/n²
    - Third-order: 1 - 1/n - 1/n² - 4/n³  (conjectural for general n)

    Args:
        n: Degree of symmetric group
        exact_prob: Exact probability P_n

    Returns:
        Dictionary with approximations and errors
    """
    first = 1 - Fraction(1, n)
    second = first - Fraction(1, n**2)
    third = second - Fraction(4, n**3)

    return {
        'exact': exact_prob,
        'first_order': first,
        'first_error': abs(exact_prob - first),
        'second_order': second,
        'second_error': abs(exact_prob - second),
        'third_order': third,
        'third_error': abs(exact_prob - third),
    }


# ============================================================
# Algorithm 7: Subgroup Family Classification
# ============================================================

def classify_subgroup_families(
    subgroups: Set[FrozenSet[Tuple[int, ...]]],
    mu: Dict[FrozenSet[Tuple[int, ...]], int],
    n: int
) -> Dict[str, List]:
    """Classify subgroups by type and compute family contributions.

    Categories:
    - "full": S_n itself
    - "point_stabilizer": conjugates of S_{n-1} (fix one point)
    - "alternating": the alternating group A_n
    - "other": all remaining subgroups

    Args:
        subgroups: All subgroups
        mu: Möbius function values
        n: Degree of symmetric group

    Returns:
        Dictionary mapping family name to list of (H, μ(H), |H|, contribution)
    """
    sn = frozenset(permutations(range(n)))
    total = factorial(n) ** 2
    families: Dict[str, List] = defaultdict(list)

    for H in subgroups:
        order = len(H)
        contrib = Fraction(mu[H] * order**2, total)

        if H == sn:
            families["full"].append((order, mu[H], contrib))
        elif order == factorial(n - 1) and n > 1:
            # Check if it's a point stabilizer
            # A point stabilizer of i fixes i for all elements
            is_stab = False
            for i in range(n):
                if all(p[i] == i for p in H):
                    is_stab = True
                    break
            if is_stab:
                families["point_stabilizer"].append((order, mu[H], contrib))
            else:
                families["other"].append((order, mu[H], contrib))
        elif order == factorial(n) // 2 and n >= 2:
            families["alternating"].append((order, mu[H], contrib))
        else:
            families["other"].append((order, mu[H], contrib))

    return dict(families)


# ============================================================
# Main demonstration
# ============================================================

def main():
    """Run all algorithms and display results."""
    print("=" * 70)
    print("  Algorithms for Subgroup Lattice Möbius Inversion")
    print("=" * 70)

    for n in range(2, 6):
        print(f"\n{'─' * 70}")
        print(f"  S_{n}  (order {factorial(n)})")
        print(f"{'─' * 70}")

        # Algorithm 1-2: Enumerate subgroups
        subgroups = enumerate_subgroups(n)
        print(f"  Subgroups found: {len(subgroups)}")

        # Algorithm 3: Compute Möbius function
        mu = compute_moebius(subgroups, n)

        # Algorithm 4: Count via Möbius
        moebius_count = generating_pair_count_moebius(subgroups, mu, n)

        # Algorithm 5: Count directly
        direct_count = generating_pair_count_direct(n)

        total = factorial(n) ** 2
        prob = Fraction(direct_count, total)

        print(f"  Generating pairs (Möbius): {moebius_count}")
        print(f"  Generating pairs (direct): {direct_count}")
        print(f"  Consistency check: {'✓' if moebius_count == direct_count else '✗'}")
        print(f"  P(generate S_{n}) = {prob} ≈ {float(prob):.6f}")

        # Algorithm 6: Asymptotic analysis
        analysis = asymptotic_analysis(n, prob)
        print(f"\n  Asymptotic comparison:")
        print(f"    1 - 1/n     = {float(analysis['first_order']):.6f}  "
              f"(error = {float(analysis['first_error']):.6f})")
        print(f"    1 - 1/n - 1/n² = {float(analysis['second_order']):.6f}  "
              f"(error = {float(analysis['second_error']):.6f})")

        # Algorithm 7: Family classification
        if n <= 5:
            families = classify_subgroup_families(subgroups, mu, n)
            print(f"\n  Subgroup family contributions:")
            for family, entries in sorted(families.items()):
                total_contrib = sum(e[2] for e in entries)
                print(f"    {family:20s}: {len(entries):3d} subgroups, "
                      f"total contribution = {float(total_contrib):+.6f}")

    # Möbius function distribution
    print(f"\n\n{'=' * 70}")
    print("  Möbius Function Value Distribution")
    print(f"{'=' * 70}")
    for n in range(2, 6):
        subgroups = enumerate_subgroups(n)
        mu = compute_moebius(subgroups, n)
        values = defaultdict(int)
        for v in mu.values():
            values[v] += 1
        print(f"\n  S_{n}: {dict(sorted(values.items()))}")


if __name__ == "__main__":
    main()
