#!/usr/bin/env python3
"""
Visualization 3: Eigenvalue Spectrum Comparison

Compares the full eigenvalue spectrum of Cayley graphs generated by
different generator pairs for S_5. Shows that:
1. The top eigenvalue is always 1 (connected graph).
2. There is a visible spectral gap.
3. Random generators tend to produce 'better' gaps than the standard pair.

Output: Eigenvalue spectrum heatmap and individual spectrum plots.
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from itertools import permutations
from math import factorial


def compose(p, q):
    return tuple(p[q[i]] for i in range(len(p)))

def inverse(p):
    n = len(p)
    inv = [0] * n
    for i in range(n):
        inv[p[i]] = i
    return tuple(inv)

def identity(n):
    return tuple(range(n))

def random_perm(n):
    p = list(range(n))
    np.random.shuffle(p)
    return tuple(p)

def closure(generators, n):
    e = identity(n)
    all_gens = list(generators) + [inverse(s) for s in generators]
    visited = {e}
    frontier = [e]
    while frontier:
        nf = []
        for g in frontier:
            for s in all_gens:
                h = compose(s, g)
                if h not in visited:
                    visited.add(h)
                    nf.append(h)
        frontier = nf
    return visited

def build_matrix_and_spectrum(sigma, tau, n):
    gens = list(set([sigma, inverse(sigma), tau, inverse(tau)]))
    d = len(gens)
    elements = sorted(permutations(range(n)))
    idx = {p: i for i, p in enumerate(elements)}
    N = len(elements)
    A = np.zeros((N, N))
    for i, g in enumerate(elements):
        for s in gens:
            j = idx[compose(s, g)]
            A[i, j] += 1.0 / d
    eigs = np.sort(np.linalg.eigvalsh(A))[::-1]
    return eigs


np.random.seed(2025)
n = 5
N = factorial(n)

# Collect spectra
spectra = []
gaps = []
labels = []

# Standard generators
tau = tuple((i + 1) % n for i in range(n))
sl = list(range(n)); sl[0], sl[1] = sl[1], sl[0]
sigma = tuple(sl)
eigs = build_matrix_and_spectrum(sigma, tau, n)
spectra.append(eigs)
gaps.append(1.0 - eigs[1])
labels.append('Standard (swap+cycle)')

# Random generators
num_random = 25
while len(spectra) - 1 < num_random:
    s = random_perm(n)
    t = random_perm(n)
    if len(closure([s, t], n)) == N:
        eigs = build_matrix_and_spectrum(s, t, n)
        spectra.append(eigs)
        gaps.append(1.0 - eigs[1])
        labels.append(f'Random #{len(spectra)-1}')

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Top left: Heatmap of all spectra
ax = axes[0, 0]
spectrum_matrix = np.array(spectra)
im = ax.imshow(spectrum_matrix, aspect='auto', cmap='RdYlBu_r',
               vmin=-1, vmax=1, interpolation='nearest')
ax.set_xlabel('Eigenvalue Index', fontsize=12)
ax.set_ylabel('Generator Pair', fontsize=12)
ax.set_title('Eigenvalue Spectra (all pairs)', fontsize=13, fontweight='bold')
fig.colorbar(im, ax=ax, label='Eigenvalue')
ax.axhline(y=0.5, color='yellow', linewidth=2, linestyle='--', alpha=0.7)
ax.set_yticks([0])
ax.set_yticklabels(['Standard'])

# Top right: Overlay of spectra
ax = axes[0, 1]
for i in range(min(8, len(spectra))):
    alpha = 1.0 if i == 0 else 0.3
    lw = 2.5 if i == 0 else 1
    color = 'red' if i == 0 else 'steelblue'
    ax.plot(spectra[i], 'o-', markersize=2, alpha=alpha, linewidth=lw,
           color=color, label=labels[i] if i <= 1 else None)

ax.axhline(y=1, color='gray', linestyle=':', alpha=0.5)
ax.axhline(y=0, color='gray', linestyle=':', alpha=0.5)
ax.set_xlabel('Eigenvalue Index', fontsize=12)
ax.set_ylabel('Eigenvalue', fontsize=12)
ax.set_title('Eigenvalue Spectra Overlay', fontsize=13, fontweight='bold')
ax.legend(fontsize=10)
ax.grid(True, alpha=0.2)

# Bottom left: Gap distribution
ax = axes[1, 0]
ax.hist(gaps[1:], bins=12, edgecolor='white', color='#4CAF50', alpha=0.8)
ax.axvline(x=gaps[0], color='red', linewidth=2, linestyle='--',
          label=f'Standard: {gaps[0]:.4f}')
ax.axvline(x=0.01, color='orange', linewidth=2, linestyle=':',
          label='Threshold 0.01')
ax.set_xlabel('Spectral Gap', fontsize=12)
ax.set_ylabel('Count', fontsize=12)
ax.set_title('Gap Distribution', fontsize=13, fontweight='bold')
ax.legend(fontsize=10)

# Bottom right: Eigenvalue density (histogram of all eigenvalues)
ax = axes[1, 1]
all_eigs = np.concatenate(spectra[1:])  # Exclude standard
ax.hist(all_eigs, bins=50, edgecolor='white', color='#9C27B0', alpha=0.7,
       density=True, label='Random generators')
ax.hist(spectra[0], bins=30, edgecolor='white', color='red', alpha=0.5,
       density=True, label='Standard generators')
ax.set_xlabel('Eigenvalue', fontsize=12)
ax.set_ylabel('Density', fontsize=12)
ax.set_title('Eigenvalue Density Distribution', fontsize=13, fontweight='bold')
ax.legend(fontsize=10)
ax.axvline(x=1, color='gray', linestyle=':', alpha=0.5)

fig.suptitle(f'Spectral Analysis of Cayley Graphs of S_{n} ({N} vertices)',
             fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig('viz_eigenvalue_spectrum.png', dpi=150, bbox_inches='tight')
print("Saved viz_eigenvalue_spectrum.png")
