"""
Visualization: Hasse Diagram of Boolean Lattice B_3 with 𝔽₁-Points Highlighted

This script draws the Hasse diagram of the Boolean lattice of subsets of {1,2,3},
highlighting the sup-irreducible elements (singletons = 𝔽₁-points) in red.
Non-extreme elements are shown in blue. The bottom element ⊥ = ∅ is shown in gray.

This visualizes Theorem 3 (finset_supIrred_iff_singleton): the 𝔽₁-points
of the powerset lattice are exactly the singletons.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from itertools import combinations


def powerset(ground):
    elems = sorted(ground)
    result = []
    for r in range(len(elems) + 1):
        for combo in combinations(elems, r):
            result.append(frozenset(combo))
    return result


def hasse_edges(elements):
    """Compute Hasse diagram edges (covers)."""
    edges = []
    for a in elements:
        for b in elements:
            if a < b and len(b) == len(a) + 1:
                edges.append((a, b))
    return edges


def label(s):
    if not s:
        return "∅"
    return "{" + ",".join(str(x) for x in sorted(s)) + "}"


def main():
    ground = {1, 2, 3}
    elements = powerset(ground)
    edges = hasse_edges(elements)

    # Position elements by rank (cardinality)
    positions = {}
    for rank in range(4):
        rank_elems = [s for s in elements if len(s) == rank]
        n = len(rank_elems)
        for i, s in enumerate(rank_elems):
            x = (i - (n - 1) / 2) * 2.0
            y = rank * 2.0
            positions[s] = (x, y)

    fig, ax = plt.subplots(1, 1, figsize=(10, 8))

    # Draw edges
    for a, b in edges:
        xa, ya = positions[a]
        xb, yb = positions[b]
        ax.plot([xa, xb], [ya, yb], 'k-', linewidth=1.0, alpha=0.4)

    # Classify and draw nodes
    for s in elements:
        x, y = positions[s]
        if len(s) == 1:
            # Sup-irreducible = 𝔽₁-point
            color = '#e74c3c'
            size = 800
            edgecolor = '#c0392b'
            zorder = 10
        elif len(s) == 0:
            # Bottom
            color = '#95a5a6'
            size = 600
            edgecolor = '#7f8c8d'
            zorder = 5
        else:
            # Composite element
            color = '#3498db'
            size = 600
            edgecolor = '#2980b9'
            zorder = 5

        ax.scatter(x, y, s=size, c=color, edgecolors=edgecolor,
                   linewidths=2, zorder=zorder)
        ax.annotate(label(s), (x, y), fontsize=11, ha='center', va='center',
                    fontweight='bold', color='white' if len(s) == 1 else 'white',
                    zorder=zorder + 1)

    # Labels
    ax.set_title("Hasse Diagram of B₃ = P({1,2,3})\n"
                 "𝔽₁-Points (Sup-Irreducibles) Highlighted in Red",
                 fontsize=14, fontweight='bold')

    # Legend
    legend_elements = [
        mpatches.Patch(facecolor='#e74c3c', edgecolor='#c0392b',
                       label='𝔽₁-point (singleton = sup-irreducible)'),
        mpatches.Patch(facecolor='#3498db', edgecolor='#2980b9',
                       label='Composite element (generated by 𝔽₁-points)'),
        mpatches.Patch(facecolor='#95a5a6', edgecolor='#7f8c8d',
                       label='Bottom element ⊥ = ∅'),
    ]
    ax.legend(handles=legend_elements, loc='upper left', fontsize=10,
              framealpha=0.9)

    # Annotations
    ax.annotate("F1Card(B₃) = 3 = |{1,2,3}|",
                xy=(0.98, 0.02), xycoords='axes fraction',
                fontsize=12, ha='right', va='bottom',
                bbox=dict(boxstyle='round,pad=0.5', facecolor='lightyellow',
                          edgecolor='orange', alpha=0.9))

    ax.set_xlim(-4, 4)
    ax.set_ylim(-1, 7.5)
    ax.axis('off')
    plt.tight_layout()
    plt.savefig('viz_lattice_hasse.png', dpi=150, bbox_inches='tight')
    print("Saved viz_lattice_hasse.png")


if __name__ == "__main__":
    main()
