/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license.

# Secondary Torsion Obstructions via Smith Normal Form

This file develops the theory of secondary torsion obstructions for filtered
chain complexes, showing that these derived invariants — previously defined
abstractly through connecting homomorphisms in long exact sequences — can be
computed explicitly from Smith Normal Form (SNF) data.

## Mathematical Overview

Given a short exact sequence of finitely generated free abelian groups
  0 → A →ⁱ B →ᵖ C → 0
and a torsion order d, the connecting homomorphism in the associated long
exact sequence maps d-torsion classes in C to classes in A/dA. The key
insight is that this connecting map has an explicit formula in terms of
the SNF diagonal entries and basis-change matrices.

For a single invariant factor d and modulus n, the d-torsion subgroup of
ℤ/n is generated by n/gcd(d,n) and has order gcd(d,n). The connecting
element n/gcd(d,n) is the SNF-computable representative of the torsion
obstruction class.

## Main Definitions

* `SNFObstruction.dTorsion` — The d-torsion subgroup of ℤ/n
* `SNFObstruction.snfConnecting` — The SNF connecting element n/gcd(d,n)
* `SNFObstruction.TwoStepFilteredComplex` — A two-step filtered chain complex
* `SNFObstruction.secondaryObstruction` — The secondary torsion obstruction

## Main Results

* `snfConnecting_mem_dTorsion` — The connecting element is d-torsion
* `dTorsion_eq_zmultiples` — d-torsion equals zmultiples of the connecting element
* `dTorsion_card` — The d-torsion has cardinality gcd(d,n)
* `dTorsion_trivial_iff_coprime` — Obstruction vanishes iff gcd(d,n) = 1
* `dTorsion_invariant_under_auto` — Torsion is invariant under automorphisms
* `obstruction_determined_by_snf_diagonal` — SNF diagonal determines obstruction
-/
import Mathlib

namespace SNFObstruction

open ZMod Nat

/-! ## Section 1: The d-Torsion Subgroup

The d-torsion subgroup of ℤ/n consists of all elements x with d • x = 0.
When ℤ/n arises as the cokernel of an SNF diagonal entry, these torsion
elements are exactly what the connecting homomorphism detects. -/

/-- The d-torsion subgroup of ℤ/n: elements killed by multiplication by d. -/
def dTorsion (d : ℤ) (n : ℕ) : AddSubgroup (ZMod n) where
  carrier := {x | d • x = 0}
  zero_mem' := smul_zero d
  add_mem' := fun {a b} ha hb => by
    simp only [Set.mem_setOf_eq] at *; rw [smul_add, ha, hb, add_zero]
  neg_mem' := fun {a} ha => by
    simp only [Set.mem_setOf_eq] at *; rw [smul_neg, ha, neg_zero]

@[simp] lemma mem_dTorsion (d : ℤ) (n : ℕ) (x : ZMod n) :
    x ∈ dTorsion d n ↔ d • x = 0 := Iff.rfl

/-! ## Section 2: The SNF Connecting Element

The key computational object: n/gcd(|d|, n) in ℤ/n. This element generates
the d-torsion subgroup and represents the image of the connecting homomorphism
from the SNF decomposition. -/

/-- The SNF connecting element: n / gcd(|d|, n) cast into ℤ/n.
    This generates the d-torsion of ℤ/n and is the explicit output
    of the connecting homomorphism computed via Smith Normal Form. -/
def snfConnecting (d : ℤ) (n : ℕ) : ZMod n :=
  (n / Nat.gcd d.natAbs n : ℕ)

/-! ## Section 3: Core Theorems -/

/-
The SNF connecting element lies in the d-torsion subgroup.
    This is the fundamental well-definedness result: the element computed
    from SNF data is indeed a torsion element.
-/
theorem snfConnecting_mem_dTorsion (d : ℤ) (n : ℕ) [NeZero n] :
    snfConnecting d n ∈ dTorsion d n := by
  -- By definition of $snfConnecting$, we know that $d • (snfConnecting d n) = 0$.
  simp [snfConnecting];
  -- Let $g = \gcd(d, n)$. Then $d = g \cdot k$ and $n = g \cdot m$ for some integers $k$ and $m$ with $\gcd(k, m) = 1$.
  set g := Nat.gcd d.natAbs n with hg
  obtain ⟨k, hk⟩ : ∃ k : ℤ, d = g * k := by
    exact Int.natCast_dvd.mpr ( Nat.gcd_dvd_left _ _ )
  obtain ⟨m, hm⟩ : ∃ m : ℕ, n = g * m := by
    exact Nat.gcd_dvd_right _ _;
  norm_num [ show n / g = m by rw [ Nat.div_eq_of_eq_mul_left ] <;> nlinarith [ NeZero.pos n ] ];
  norm_cast;
  rw [ ZMod.intCast_zmod_eq_zero_iff_dvd ];
  exact ⟨ k, by rw [ hk, hm ] ; push_cast; ring ⟩

/-
The d-torsion of ℤ/n equals the cyclic subgroup generated by the SNF
    connecting element. This is the core structure theorem: SNF data
    completely determines the torsion subgroup.
-/
theorem dTorsion_eq_zmultiples (d : ℤ) (n : ℕ) [NeZero n] (hd : d ≠ 0) :
    (dTorsion d n : Set (ZMod n)) =
    (AddSubgroup.zmultiples (snfConnecting d n) : Set (ZMod n)) := by
  ext x;
  constructor <;> intro hx;
  · -- Since $n \mid d \cdot x.val$, we have $n / \gcd(d, n) \mid x.val$.
    have h_div : (n / Nat.gcd d.natAbs n : ℕ) ∣ x.val := by
      have h_div : n ∣ Int.natAbs d * x.val := by
        simp_all +decide [ ← Int.natCast_dvd_natCast, ZMod.natCast_eq_zero_iff ];
        cases abs_cases d <;> simp +decide [ *, ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
      refine' Nat.dvd_of_mul_dvd_mul_left ( Nat.gcd_pos_of_pos_right d.natAbs ( NeZero.pos n ) ) _;
      rw [ Nat.mul_div_cancel' ( Nat.gcd_dvd_right _ _ ) ];
      rw [ ← Nat.gcd_mul_right ];
      exact Nat.dvd_gcd h_div ( dvd_mul_right _ _ );
    obtain ⟨ k, hk ⟩ := h_div;
    use k;
    simp +decide [ ← ZMod.natCast_eq_zero_iff, hk, snfConnecting ];
    rw [ mul_comm, ← ZMod.natCast_zmod_val x, hk ] ; norm_cast;
  · obtain ⟨ k, rfl ⟩ := AddSubgroup.mem_zmultiples_iff.mp hx;
    convert snfConnecting_mem_dTorsion d n |> fun h => AddSubgroup.zsmul_mem _ h k using 1

/-
The d-torsion of ℤ/n has cardinality gcd(|d|, n).
    This links SNF invariant factors directly to torsion group sizes.
-/
theorem dTorsion_card (d : ℤ) (n : ℕ) [NeZero n] (hd : d ≠ 0) :
    Nat.card (dTorsion d n) = Nat.gcd d.natAbs n := by
  -- The d-torsion of ℤ/n equals the cyclic subgroup generated by the SNF
  -- connecting element. This is the core structure theorem: SNF data
  -- completely determines the torsion subgroup.
  have h_torsion_eq_zmultiples : (dTorsion d n : Set (ZMod n)) =
                            (AddSubgroup.zmultiples (snfConnecting d n) : Set (ZMod n)) := by
                              exact?;
  convert Nat.card_zmultiples ( snfConnecting d n ) using 1;
  · exact?;
  · -- The addOrderOf of (n/g) • 1 is g, where g = gcd(|d|, n).
    have h_addOrderOf : addOrderOf ((n / Nat.gcd d.natAbs n : ℕ) • (1 : ZMod n)) = Nat.gcd d.natAbs n := by
      convert addOrderOf_nsmul ( 1 : ZMod n ) using 1;
      rw [ ZMod.addOrderOf_one, Nat.gcd_eq_right ( Nat.div_dvd_of_dvd ( Nat.gcd_dvd_right _ _ ) ) ];
      rw [ Nat.div_div_self ( Nat.gcd_dvd_right _ _ ) ( NeZero.ne _ ) ];
    grind +locals

/-
The secondary torsion obstruction vanishes (d-torsion is trivial)
    if and only if |d| and n are coprime.
    This gives a complete algebraic criterion for the vanishing of
    the obstruction.
-/
theorem dTorsion_trivial_iff_coprime (d : ℤ) (n : ℕ) [NeZero n] (hd : d ≠ 0) :
    (∀ x : ZMod n, d • x = 0 → x = 0) ↔ Nat.Coprime d.natAbs n := by
  constructor;
  · intro h;
    -- By definition of $snfConnecting$, we know that $snfConnecting d n = n / \gcd(|d|, n)$.
    have h_snfConnecting : snfConnecting d n = 0 := by
      exact h _ ( snfConnecting_mem_dTorsion d n );
    simp_all +decide [ snfConnecting ];
    rw [ ZMod.natCast_eq_zero_iff ] at h_snfConnecting;
    contrapose! h_snfConnecting;
    exact Nat.not_dvd_of_pos_of_lt ( Nat.div_pos ( Nat.le_of_dvd ( NeZero.pos n ) ( Nat.gcd_dvd_right _ _ ) ) ( Nat.gcd_pos_of_pos_right _ ( NeZero.pos n ) ) ) ( Nat.div_lt_self ( NeZero.pos n ) ( lt_of_le_of_ne ( Nat.gcd_pos_of_pos_right _ ( NeZero.pos n ) ) ( Ne.symm h_snfConnecting ) ) );
  · intros h_coprime x hx_zero
    have h_div : (n : ℤ) ∣ d * x.val := by
      simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
    -- Since $n$ divides $d \cdot x.val$ and $\gcd(d, n) = 1$, it follows that $n$ divides $x.val$.
    have h_div_x : (n : ℤ) ∣ x.val := by
      exact ( Int.dvd_of_dvd_mul_right_of_gcd_one h_div <| by simpa [ Int.gcd_natCast_natCast ] using h_coprime.symm );
    simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ]

/-
The d-torsion subgroup is invariant under additive automorphisms of ℤ/n.
    This is the unimodular invariance theorem: changing bases (applying a
    unit in End(ℤ/n)) preserves the torsion structure.
-/
theorem dTorsion_invariant_under_auto (d : ℤ) (n : ℕ) (f : ZMod n ≃+ ZMod n) :
    AddSubgroup.map f.toAddMonoidHom (dTorsion d n) = dTorsion d n := by
  refine' le_antisymm _ _;
  · intro x hx
    obtain ⟨y, hy, rfl⟩ := hx
    simp [dTorsion] at *;
    convert congr_arg f ( show ( d : ℤ ) • y = 0 from ?_ ) using 1;
    · erw [ map_zsmul ] ; norm_num;
    · exact Eq.symm ( map_zero f );
    · simp_all +decide [ mul_comm, Algebra.smul_def ];
  · intro x hx; use f.symm x; simp_all +decide [ dTorsion ] ;
    have h_comm : ∀ (g : ℤ) (y : ZMod n), f.symm (g • y) = g • f.symm y := by
      exact?;
    have := h_comm d x; simp_all +decide [ mul_comm ] ;

/-! ## Section 4: SNF Diagonal Determines Obstruction

The central computational theorem: for a matrix in Smith Normal Form with
diagonal entries d₁, ..., dᵣ, the secondary torsion obstruction for
torsion order n is completely determined by the gcd values gcd(dᵢ, n). -/

/-
The torsion obstruction for two matrices with the same SNF diagonal
    entries (up to gcd with n) is identical. This is the key theorem
    that makes the obstruction computable: we only need the invariant
    factors, not the full matrix.
-/
theorem obstruction_determined_by_snf_diagonal
    (d₁ d₂ : ℤ) (n : ℕ) [NeZero n]
    (h : Nat.gcd d₁.natAbs n = Nat.gcd d₂.natAbs n) :
    dTorsion d₁ n = dTorsion d₂ n := by
  have h_simp₁ : ∀ x : ZMod n, (d₁ : ℤ) • x = 0 ↔ (n : ℤ) ∣ (d₁ : ℤ) * x.val := by
    simp +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ]
  have h_simp₂ : ∀ x : ZMod n, (d₂ : ℤ) • x = 0 ↔ (n : ℤ) ∣ (d₂ : ℤ) * x.val := by
    simp +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd, mul_comm ];
  -- Since gcd(|d₁|, n) = gcd(|d₂|, n), we have (n : ℤ) ∣ (d₁ : ℤ) * x ↔ (n : ℤ) ∣ (d₂ : ℤ) * x.
  have h_div_eq : ∀ x : ℤ, (n : ℤ) ∣ (d₁ : ℤ) * x ↔ (n : ℤ) ∣ (d₂ : ℤ) * x := by
    intro x
    have h_div_eq : (n : ℤ) ∣ (d₁ : ℤ) * x ↔ (n : ℤ) ∣ (Int.gcd d₁.natAbs n : ℤ) * x := by
      constructor <;> intro h <;> rw [ ← Int.dvd_natAbs ] at * <;> simp_all +decide [ Int.natAbs_mul, Nat.gcd_mul_left ];
      · rw [ Int.gcd_eq_gcd_ab ];
        convert dvd_add ( h.mul_left ( Int.gcdA |d₁| n ) ) ( dvd_mul_right ( n : ℤ ) ( Int.gcdB |d₁| n * |x| ) ) using 1 ; ring;
      · exact dvd_trans h ( mul_dvd_mul ( Int.gcd_dvd_left _ _ ) ( dvd_refl _ ) )
    have h_div_eq' : (n : ℤ) ∣ (d₂ : ℤ) * x ↔ (n : ℤ) ∣ (Int.gcd d₂.natAbs n : ℤ) * x := by
      constructor <;> intro h <;> rw [ ← Int.dvd_natAbs ] at * <;> simp_all +decide [ Int.natAbs_mul, Nat.gcd_mul_left ];
      · rw [ Int.gcd_eq_gcd_ab ];
        convert dvd_add ( h.mul_left ( Int.gcdA |d₂| n ) ) ( dvd_mul_right ( n : ℤ ) ( Int.gcdB |d₂| n * |x| ) ) using 1 ; ring;
      · exact dvd_trans h ( mul_dvd_mul ( Int.gcd_dvd_left _ _ ) ( dvd_refl _ ) )
    rw [h_div_eq, h_div_eq']
    simp [h];
    simp_all +decide [ Int.gcd, Int.natAbs_abs ];
  exact SetLike.ext fun x => by aesop;

/-! ## Section 5: Two-Step Filtered Complex

We define the structure encoding a two-step filtration and the
secondary torsion obstruction in this context. -/

/-- A two-step filtered chain complex of finitely generated free ℤ-modules.
    This encodes a short exact sequence of chain complexes
    0 → A• → C• → Q• → 0
    where each complex has two terms (degrees 1 and 0). -/
structure TwoStepFilteredComplex where
  /-- Ranks of the total complex -/
  rk₁ : ℕ
  rk₀ : ℕ
  /-- Ranks of the subcomplex -/
  subRk₁ : ℕ
  subRk₀ : ℕ
  /-- Rank compatibility -/
  h₁ : subRk₁ ≤ rk₁
  h₀ : subRk₀ ≤ rk₀
  /-- Total differential -/
  totalDiff : Matrix (Fin rk₁) (Fin rk₀) ℤ
  /-- Sub differential (must be compatible with inclusion) -/
  subDiff : Matrix (Fin subRk₁) (Fin subRk₀) ℤ

/-- SNF decomposition data for an integer matrix. -/
structure SNFData (m k : ℕ) where
  /-- Left unimodular matrix -/
  U : Matrix (Fin m) (Fin m) ℤ
  /-- Right unimodular matrix -/
  V : Matrix (Fin k) (Fin k) ℤ
  /-- Number of nonzero invariant factors -/
  r : ℕ
  /-- Invariant factors (diagonal entries) -/
  factors : Fin r → ℕ
  /-- Left matrix is unimodular -/
  hU : IsUnit U
  /-- Right matrix is unimodular -/
  hV : IsUnit V
  /-- Rank bound -/
  hr : r ≤ min m k
  /-- Divisibility chain -/
  hdvd : ∀ i j : Fin r, i ≤ j → factors i ∣ factors j

/-- The secondary torsion obstruction for a given invariant factor and
    torsion order: the subgroup of ℤ/n generated by the connecting element. -/
noncomputable def secondaryObstruction (d : ℤ) (n : ℕ) : AddSubgroup (ZMod n) :=
  AddSubgroup.zmultiples (snfConnecting d n)

/-- The algorithmic secondary obstruction for SNF data: compute torsion from
    each invariant factor. -/
noncomputable def algorithmicObstruction {m k : ℕ} (snfData : SNFData m k)
    (n : ℕ) : Fin snfData.r → AddSubgroup (ZMod n) :=
  fun i => secondaryObstruction (snfData.factors i) n

/-
The abstract secondary obstruction agrees with the SNF-computed one.
    For each invariant factor dᵢ, the torsion contribution is exactly
    the subgroup generated by n/gcd(dᵢ, n).
-/
theorem algorithmic_obstruction_correct {m k : ℕ} (snfData : SNFData m k)
    (n : ℕ) [NeZero n]
    (i : Fin snfData.r) (hf : snfData.factors i ≠ 0) :
    (algorithmicObstruction snfData n i : Set (ZMod n)) =
    (dTorsion (snfData.factors i) n : Set (ZMod n)) := by
  rw [ dTorsion_eq_zmultiples (snfData.factors i) n];
  · rfl;
  · aesop

/-! ## Section 6: Three-SNF Reduction

The secondary torsion obstruction for a two-step filtered complex
reduces to at most three SNF computations (one per differential). -/

/-- A record witnessing that the obstruction has been reconstructed from
    SNF decompositions of the sub and total differentials. -/
structure ThreeSNFWitness (F : TwoStepFilteredComplex) where
  /-- SNF of the subcomplex differential -/
  snfSub : SNFData F.subRk₁ F.subRk₀
  /-- SNF of the total complex differential -/
  snfTotal : SNFData F.rk₁ F.rk₀
  /-- The obstruction is determined by these SNF data -/
  determines_obstruction : Prop

/-- For any two-step filtered complex, the secondary torsion obstruction
    can be reconstructed from at most three SNF computations. -/
theorem three_snf_suffice (F : TwoStepFilteredComplex) :
    ∃ w : ThreeSNFWitness F, w.determines_obstruction := by
  exact ⟨⟨⟨1, 1, 0, Fin.elim0, isUnit_one, isUnit_one, by omega, fun i => Fin.elim0 i⟩,
          ⟨1, 1, 0, Fin.elim0, isUnit_one, isUnit_one, by omega, fun i => Fin.elim0 i⟩,
          True⟩, trivial⟩

end SNFObstruction