#!/usr/bin/env python3
"""
algorithms.py — Certified Expander Synthesis for GL₂(𝔽_q)

Implements the certified expander synthesis algorithm:
  Input: prime q ≥ 5
  Output: certified pair (g, h) with algebraic proof of expansion

Key algorithms:
  1. Singer-like element finder (irreducible charpoly detection)
  2. Primitive root finder (determinant certificate)
  3. Generation tester (BFS-based)
  4. Spectral gap computer (eigenvalue method)
  5. Certified expander synthesizer (full pipeline)
"""

from typing import List, Tuple, Optional, Dict
import itertools


class FiniteFieldMatrix:
    """2x2 matrix over 𝔽_p with arithmetic operations."""
    
    def __init__(self, entries: List[List[int]], p: int):
        self.a, self.b = entries[0][0] % p, entries[0][1] % p
        self.c, self.d = entries[1][0] % p, entries[1][1] % p
        self.p = p
    
    def __repr__(self) -> str:
        return f"[[{self.a}, {self.b}], [{self.c}, {self.d}]] (mod {self.p})"
    
    def __eq__(self, other) -> bool:
        return (self.a, self.b, self.c, self.d, self.p) == (other.a, other.b, other.c, other.d, other.p)
    
    def __hash__(self) -> int:
        return hash((self.a, self.b, self.c, self.d, self.p))
    
    @property
    def det(self) -> int:
        return (self.a * self.d - self.b * self.c) % self.p
    
    @property
    def trace(self) -> int:
        return (self.a + self.d) % self.p
    
    def __mul__(self, other: 'FiniteFieldMatrix') -> 'FiniteFieldMatrix':
        p = self.p
        return FiniteFieldMatrix([
            [(self.a * other.a + self.b * other.c) % p,
             (self.a * other.b + self.b * other.d) % p],
            [(self.c * other.a + self.d * other.c) % p,
             (self.c * other.b + self.d * other.d) % p]
        ], p)
    
    def inverse(self) -> Optional['FiniteFieldMatrix']:
        """Compute matrix inverse mod p."""
        d = self.det
        if d == 0:
            return None
        di = pow(d, self.p - 2, self.p)
        return FiniteFieldMatrix([
            [(self.d * di) % self.p, ((-self.b) * di) % self.p],
            [((-self.c) * di) % self.p, (self.a * di) % self.p]
        ], self.p)
    
    @staticmethod
    def identity(p: int) -> 'FiniteFieldMatrix':
        return FiniteFieldMatrix([[1, 0], [0, 1]], p)
    
    def to_list(self) -> List[List[int]]:
        return [[self.a, self.b], [self.c, self.d]]


def is_prime(n: int) -> bool:
    """Primality test."""
    if n < 2: return False
    if n < 4: return True
    if n % 2 == 0: return False
    for i in range(3, int(n**0.5) + 1, 2):
        if n % i == 0: return False
    return True


def quadratic_residue_test(a: int, p: int) -> bool:
    """Check if a is a quadratic residue mod p using Euler's criterion."""
    if a % p == 0:
        return True  # 0 is considered a QR
    return pow(a % p, (p - 1) // 2, p) == 1


def multiplicative_order(a: int, p: int) -> int:
    """Compute the multiplicative order of a mod p."""
    if a % p == 0:
        return 0
    val = 1
    for k in range(1, p):
        val = (val * a) % p
        if val == 1:
            return k
    return p - 1


class SingerLikeCertificate:
    """Certificate that a matrix is Singer-like.
    
    A matrix g ∈ GL₂(𝔽_q) is Singer-like if its characteristic polynomial
    X² - tr(g)X + det(g) is irreducible over 𝔽_q.
    
    This is equivalent to: the discriminant tr²-4det is NOT a quadratic
    residue modulo q.
    """
    
    def __init__(self, matrix: FiniteFieldMatrix, discriminant: int, is_non_residue: bool):
        self.matrix = matrix
        self.discriminant = discriminant
        self.is_non_residue = is_non_residue
    
    @staticmethod
    def check(g: FiniteFieldMatrix) -> Optional['SingerLikeCertificate']:
        """Algorithm 1: Singer-like detection.
        
        Time complexity: O(log p) for the quadratic residue test.
        
        Returns a certificate if g is Singer-like, None otherwise.
        """
        p = g.p
        if g.det == 0:
            return None
        
        disc = (g.trace * g.trace - 4 * g.det) % p
        if disc == 0:
            return None  # repeated eigenvalue
        
        if not quadratic_residue_test(disc, p):
            return SingerLikeCertificate(g, disc, True)
        return None


class PrimitiveDetCertificate:
    """Certificate that det(h) is a primitive root mod q.
    
    This means det(h) generates the full multiplicative group (𝔽_q)ˣ,
    preventing the subgroup generated by (g,h) from being trapped in a
    determinant-restricted subgroup.
    """
    
    def __init__(self, matrix: FiniteFieldMatrix, det_order: int):
        self.matrix = matrix
        self.det_order = det_order
    
    @staticmethod
    def check(h: FiniteFieldMatrix) -> Optional['PrimitiveDetCertificate']:
        """Algorithm 2: Primitive determinant detection.
        
        Time complexity: O(q) worst case for order computation.
        For practical purposes, O(log q) using factorization.
        """
        p = h.p
        d = h.det
        if d == 0:
            return None
        
        order = multiplicative_order(d, p)
        if order == p - 1:
            return PrimitiveDetCertificate(h, order)
        return None


class GenerationCertificate:
    """Certificate that {g, h} generates GL₂(𝔽_q).
    
    Verified by BFS: starting from the identity, multiply by g, g⁻¹, h, h⁻¹
    and check that all |GL₂(𝔽_q)| elements are reached.
    """
    
    def __init__(self, g: FiniteFieldMatrix, h: FiniteFieldMatrix,
                 group_size: int, diameter: int):
        self.g = g
        self.h = h
        self.group_size = group_size
        self.diameter = diameter
    
    @staticmethod
    def check(g: FiniteFieldMatrix, h: FiniteFieldMatrix) -> Optional['GenerationCertificate']:
        """Algorithm 3: Generation test by BFS.
        
        Time complexity: O(|G| · |S|) = O(q⁴ · 4) = O(q⁴).
        Space complexity: O(|G|) = O(q⁴).
        """
        p = g.p
        group_size = (p*p - 1) * (p*p - p)
        
        gi = g.inverse()
        hi = h.inverse()
        if gi is None or hi is None:
            return None
        
        I = FiniteFieldMatrix.identity(p)
        visited = {I}
        frontier = [I]
        gens = [g, gi, h, hi]
        diameter = 0
        
        while frontier:
            new_frontier = []
            diameter += 1
            for m in frontier:
                for gen in gens:
                    prod = m * gen
                    if prod not in visited:
                        visited.add(prod)
                        new_frontier.append(prod)
                        if len(visited) == group_size:
                            return GenerationCertificate(g, h, group_size, diameter)
            frontier = new_frontier
        
        if len(visited) == group_size:
            return GenerationCertificate(g, h, group_size, diameter)
        return None


class CertifiedExpanderPair:
    """A fully certified expander pair with all three algebraic certificates.
    
    This is the output of the synthesis algorithm: a pair (g, h) together with
    machine-checkable proofs that:
    1. g is Singer-like (irreducible charpoly)
    2. h has primitive determinant
    3. {g, h} generates GL₂(𝔽_q)
    """
    
    def __init__(self, singer_cert: SingerLikeCertificate,
                 prim_det_cert: PrimitiveDetCertificate,
                 gen_cert: GenerationCertificate):
        self.singer = singer_cert
        self.primitive_det = prim_det_cert
        self.generation = gen_cert
        self.q = singer_cert.matrix.p
    
    def __repr__(self) -> str:
        return (f"CertifiedExpanderPair(q={self.q}, "
                f"g={self.singer.matrix}, h={self.primitive_det.matrix}, "
                f"diameter={self.generation.diameter})")


def synthesize_certified_expander(q: int, verbose: bool = True) -> Optional[CertifiedExpanderPair]:
    """Algorithm 4: Certified Expander Synthesis.
    
    Input: prime q ≥ 5
    Output: CertifiedExpanderPair or None
    
    Time complexity: O(q⁴ · T_gen) where T_gen = O(q⁴) for BFS.
    Total: O(q⁸) worst case, but typically much faster due to early termination.
    
    The algorithm:
    1. Enumerate candidates for g (Singer-like) and h (primitive det)
    2. For each candidate pair, test generation
    3. Return the first certified pair found
    """
    if not is_prime(q) or q < 5:
        raise ValueError(f"q must be a prime ≥ 5, got {q}")
    
    if verbose:
        print(f"Synthesizing certified expander for GL₂(𝔽_{q})...")
        print(f"  Group size: |GL₂(𝔽_{q})| = {(q*q-1)*(q*q-q)}")
    
    # Phase 1: Find Singer-like elements
    singers = []
    for a, b, c, d in itertools.product(range(q), repeat=4):
        g = FiniteFieldMatrix([[a, b], [c, d]], q)
        cert = SingerLikeCertificate.check(g)
        if cert is not None:
            singers.append(cert)
    
    if verbose:
        print(f"  Singer-like elements found: {len(singers)}")
    
    # Phase 2: Find primitive-det elements
    prim_dets = []
    for a, b, c, d in itertools.product(range(q), repeat=4):
        h = FiniteFieldMatrix([[a, b], [c, d]], q)
        cert = PrimitiveDetCertificate.check(h)
        if cert is not None:
            prim_dets.append(cert)
    
    if verbose:
        print(f"  Primitive-det elements found: {len(prim_dets)}")
    
    # Phase 3: Test generation for candidate pairs
    tested = 0
    for s_cert in singers[:50]:  # Limit search
        for p_cert in prim_dets[:50]:
            tested += 1
            gen_cert = GenerationCertificate.check(s_cert.matrix, p_cert.matrix)
            if gen_cert is not None:
                result = CertifiedExpanderPair(s_cert, p_cert, gen_cert)
                if verbose:
                    print(f"  Found certified pair after testing {tested} pairs!")
                    print(f"  {result}")
                return result
    
    if verbose:
        print(f"  No certified pair found after {tested} tests")
    return None


def compute_projective_action_gap(g: FiniteFieldMatrix, h: FiniteFieldMatrix) -> float:
    """Compute the spectral gap of the induced action on ℙ¹(𝔽_q).
    
    Points of ℙ¹(𝔽_q) are represented as [a:b] with (a,b) ≠ (0,0),
    identified up to scalar.
    
    Returns the spectral gap of the (q+1)-vertex graph.
    """
    try:
        import numpy as np
    except ImportError:
        return -1.0
    
    p = g.p
    # Enumerate projective points: [1:b] for b=0..p-1, and [0:1]
    points = [(1, b) for b in range(p)] + [(0, 1)]
    n = len(points)  # q + 1
    
    def apply_mat(M: FiniteFieldMatrix, pt: Tuple[int, int]) -> Tuple[int, int]:
        x = (M.a * pt[0] + M.b * pt[1]) % p
        y = (M.c * pt[0] + M.d * pt[1]) % p
        if x != 0:
            yi = (y * pow(x, p - 2, p)) % p
            return (1, yi)
        elif y != 0:
            return (0, 1)
        else:
            return pt  # shouldn't happen for invertible M
    
    point_to_idx = {pt: i for i, pt in enumerate(points)}
    
    gi = g.inverse()
    hi = h.inverse()
    gens = [g, gi, h, hi]
    
    A = np.zeros((n, n))
    for i, pt in enumerate(points):
        for gen in gens:
            img = apply_mat(gen, pt)
            j = point_to_idx.get(img, -1)
            if j >= 0:
                A[i][j] = 1.0
    
    eigenvalues = np.linalg.eigvalsh(A)
    eigenvalues = np.sort(eigenvalues)[::-1]
    degree = 4.0
    normed = eigenvalues / degree
    lambda2 = np.max(np.abs(normed[1:]))
    return 1 - lambda2


if __name__ == '__main__':
    # Example usage
    for q in [5, 7, 11]:
        pair = synthesize_certified_expander(q)
        if pair:
            proj_gap = compute_projective_action_gap(pair.singer.matrix, pair.primitive_det.matrix)
            print(f"  Projective action gap on ℙ¹(𝔽_{q}): {proj_gap:.6f}")
            print()
