#!/usr/bin/env python3
"""
algorithms.py — Algorithms for Harmonic-Sector Factorization

Implements verified methods for computing:
- Weighted graph Laplacians (for theta graphs and general graphs)
- Reduced Laplacian determinants
- Harmonic lattice covolumes
- Pinned, harmonic, and periodic partition functions
- Subdivision operations preserving the underlying metric graph

All algorithms are documented with complexity analysis.

References:
    Baker & Norine, "Riemann-Roch and Abel-Jacobi theory on a finite graph" (2007)
    An, Baker, Kuperberg, Shokrieh, "Canonical representatives for divisor
    classes on tropical curves and the matrix-tree theorem" (2014)
"""

import numpy as np
from typing import Tuple, List


def build_theta_graph_laplacian(a: float, b: float, c: float) -> np.ndarray:
    """
    Build the weighted Laplacian for the theta graph Θ(a, b, c).

    The theta graph has 2 vertices connected by 3 parallel edges of lengths
    a, b, c. Edge weights (conductances) are 1/length.

    Args:
        a, b, c: Edge lengths (positive reals).

    Returns:
        2x2 weighted Laplacian matrix.

    Time complexity: O(1)
    Space complexity: O(1)

    Example:
        >>> L = build_theta_graph_laplacian(1.0, 2.0, 3.0)
        >>> L
        array([[ 1.833, -1.833],
               [-1.833,  1.833]])
    """
    assert a > 0 and b > 0 and c > 0, "Edge lengths must be positive"
    w = 1.0 / a + 1.0 / b + 1.0 / c  # total conductance
    return np.array([[w, -w], [-w, w]])


def build_general_graph_laplacian(
    n: int, edges: List[Tuple[int, int, float]]
) -> np.ndarray:
    """
    Build the weighted Laplacian for a general weighted graph.

    Args:
        n: Number of vertices.
        edges: List of (i, j, weight) tuples. Weight = conductance = 1/length.

    Returns:
        n×n weighted Laplacian matrix.

    Time complexity: O(n² + |E|)
    Space complexity: O(n²)
    """
    L = np.zeros((n, n))
    for i, j, w in edges:
        assert 0 <= i < n and 0 <= j < n, f"Invalid vertex index: {i}, {j}"
        assert w > 0, f"Weight must be positive: {w}"
        L[i, j] -= w
        L[j, i] -= w
        L[i, i] += w
        L[j, j] += w
    return L


def compute_reduced_laplacian_det(L: np.ndarray) -> float:
    """
    Compute the determinant of the reduced Laplacian.

    The reduced Laplacian is obtained by deleting the last row and column.
    By the matrix-tree theorem, det(L_red) equals the weighted number of
    spanning trees.

    Args:
        L: n×n weighted Laplacian matrix.

    Returns:
        Determinant of the (n-1)×(n-1) reduced Laplacian.

    Time complexity: O(n³) — LU decomposition
    Space complexity: O(n²)

    Example:
        >>> L = build_theta_graph_laplacian(1.0, 2.0, 3.0)
        >>> compute_reduced_laplacian_det(L)
        1.8333...
    """
    n = L.shape[0]
    if n == 1:
        return 1.0
    L_red = L[:n - 1, :n - 1]
    return float(np.linalg.det(L_red))


def compute_kernel_lattice_covolume(a: float, b: float, c: float) -> float:
    """
    Compute the covolume of the harmonic kernel lattice for Θ(a, b, c).

    For the theta graph with edge lengths a, b, c, the first Betti number
    is g = 2 (three edges, two vertices: g = |E| - |V| + 1 = 3 - 2 + 1 = 2).

    The harmonic kernel lattice Λ_Γ ⊂ ℝ^g is generated by the cycle vectors
    projected onto the harmonic subspace. For Θ(a, b, c):
    - Cycle 1 uses edges a, b (going around a-b loop)
    - Cycle 2 uses edges a, c (going around a-c loop)

    The Gram matrix of the cycle inner products (using the edge-length metric)
    is:
        G = [[a + b, a], [a, a + c]]

    The covolume is sqrt(det(G)).

    Args:
        a, b, c: Edge lengths.

    Returns:
        Covolume of the harmonic kernel lattice.

    Time complexity: O(1)
    Space complexity: O(1)
    """
    # Gram matrix of cycle space inner products
    det_G = (a + b) * (a + c) - a * a
    # = a*c + b*a + b*c = a*b + b*c + c*a
    return float(np.sqrt(abs(det_G)))


def compute_zpin(n: int, det_Lred: float) -> float:
    """
    Compute the pinned partition factor.

    Z_pin = (2π)^((n-1)/2) / √(det L_red)

    Args:
        n: Number of vertices.
        det_Lred: Determinant of the reduced Laplacian (must be positive).

    Returns:
        The pinned partition factor.

    Time complexity: O(1)
    Space complexity: O(1)
    """
    assert det_Lred > 0, "Reduced Laplacian determinant must be positive"
    return (2 * np.pi) ** ((n - 1) / 2) / np.sqrt(det_Lred)


def compute_zharm(covolume: float) -> float:
    """
    Compute the harmonic partition factor.

    Z_harm = covol(Λ_Γ) = volume of the tropical Jacobian torus.

    Args:
        covolume: Covolume of the kernel lattice (positive).

    Returns:
        The harmonic partition factor.

    Time complexity: O(1)
    Space complexity: O(1)
    """
    assert covolume > 0, "Covolume must be positive"
    return covolume


def compute_zperiodic(n: int, det_Lred: float, covolume: float) -> float:
    """
    Compute the periodic partition function.

    Z_periodic = Z_pin * Z_harm

    Args:
        n: Number of vertices.
        det_Lred: Determinant of the reduced Laplacian.
        covolume: Covolume of the kernel lattice.

    Returns:
        The periodic partition function.

    Time complexity: O(1)
    Space complexity: O(1)
    """
    return compute_zpin(n, det_Lred) * compute_zharm(covolume)


def subdivide_theta_edge(
    a: float, b: float, c: float,
    edge_idx: int = 0, num_parts: int = 2
) -> np.ndarray:
    """
    Subdivide one edge of Θ(a, b, c) into num_parts equal segments.

    The resulting graph has (num_parts - 1) new interior vertices on the
    subdivided edge, yielding a graph with (2 + num_parts - 1) vertices
    that represents the same metric graph.

    Args:
        a, b, c: Original edge lengths.
        edge_idx: Which edge to subdivide (0=a, 1=b, 2=c).
        num_parts: Number of equal parts to divide the edge into.

    Returns:
        Weighted Laplacian of the subdivided graph.

    Time complexity: O(n²) where n = num_parts + 1
    Space complexity: O(n²)
    """
    lengths = [a, b, c]
    sub_len = lengths[edge_idx]
    seg_len = sub_len / num_parts

    # Vertices: 0 and 1 are the original endpoints.
    # Vertices 2, 3, ..., num_parts are interior vertices on the subdivided edge.
    n = 2 + (num_parts - 1)
    edges = []

    # Non-subdivided edges: connect vertex 0 to vertex 1
    for idx in range(3):
        if idx != edge_idx:
            edges.append((0, 1, 1.0 / lengths[idx]))

    # Subdivided edge: 0 -- 2 -- 3 -- ... -- (num_parts) -- 1
    chain = [0] + list(range(2, num_parts + 1)) + [1]
    for i in range(len(chain) - 1):
        edges.append((chain[i], chain[i + 1], 1.0 / seg_len))

    return build_general_graph_laplacian(n, edges)


def compute_free_energy_decomposition(
    n: int, det_Lred: float, covolume: float
) -> Tuple[float, float, float]:
    """
    Compute the free energy decomposition.

    F_total = F_pin + F_harm
    where F_pin = -log(Z_pin), F_harm = -log(Z_harm).

    Args:
        n: Number of vertices.
        det_Lred: Determinant of the reduced Laplacian.
        covolume: Covolume of the kernel lattice.

    Returns:
        Tuple (F_total, F_pin, F_harm).

    Time complexity: O(1)
    Space complexity: O(1)
    """
    zpin = compute_zpin(n, det_Lred)
    zharm = compute_zharm(covolume)
    F_pin = -np.log(zpin)
    F_harm = -np.log(zharm)
    F_total = F_pin + F_harm
    return F_total, F_pin, F_harm


def verify_gauge_invariance(L: np.ndarray, x: np.ndarray, c: float) -> bool:
    """
    Numerically verify gauge invariance: E(x + c) = E(x).

    Args:
        L: Weighted Laplacian matrix.
        x: Field configuration.
        c: Constant shift.

    Returns:
        True if gauge invariance holds (up to floating-point tolerance).

    Time complexity: O(n²)
    Space complexity: O(n)
    """
    def energy(phi):
        return phi @ L @ phi

    E_x = energy(x)
    E_shifted = energy(x + c * np.ones_like(x))
    return abs(E_x - E_shifted) < 1e-10 * (abs(E_x) + 1)


if __name__ == "__main__":
    # Quick self-test
    print("Running algorithm self-tests...")

    # Test theta graph
    L = build_theta_graph_laplacian(1, 2, 3)
    assert abs(L.sum(axis=1)).max() < 1e-14, "Row-sum-zero failed"
    assert abs(L - L.T).max() < 1e-14, "Symmetry failed"

    # Test determinant
    det = compute_reduced_laplacian_det(L)
    assert det > 0, "Determinant should be positive for connected graph"
    expected = 1/1 + 1/2 + 1/3  # = 11/6
    assert abs(det - expected) < 1e-10, f"Expected {expected}, got {det}"

    # Test covolume
    covol = compute_kernel_lattice_covolume(1, 2, 3)
    expected_covol = np.sqrt(1*2 + 2*3 + 3*1)  # = sqrt(11)
    assert abs(covol - expected_covol) < 1e-10

    # Test gauge invariance
    x = np.array([1.0, -0.5])
    assert verify_gauge_invariance(L, x, 3.7), "Gauge invariance failed"

    # Test subdivision
    L_sub = subdivide_theta_edge(1, 2, 3, edge_idx=0, num_parts=3)
    assert abs(L_sub.sum(axis=1)).max() < 1e-14, "Subdivision row-sum failed"

    print("All self-tests passed!")
