import Geometry.FlagComplex

/-!
# Argumentation semantics and downward-closed topology

This study separates two constructions that are easily conflated. Preferred
extensions form an antichain of maximal admissible sets, whereas a simplicial
complex must be closed under taking subsets. The downward closure generated by
preferred extensions is a genuine complex, but the preferred family itself is
usually not one.
-/

open Finset

namespace ArgumentationTopology

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- An attack relation is conflict-free on `S` when no two members attack. -/
def ConflictFree (R : α → α → Prop) (S : Finset α) : Prop :=
  ∀ ⦃a⦄, a ∈ S → ∀ ⦃b⦄, b ∈ S → ¬ R a b

/-- `S` defends `a` when every attacker of `a` is attacked from `S`. -/
def Defends (R : α → α → Prop) (S : Finset α) (a : α) : Prop :=
  ∀ b, R b a → ∃ c ∈ S, R c b

/-- Dung admissibility: conflict freedom together with self-defence. -/
def Admissible (R : α → α → Prop) (S : Finset α) : Prop :=
  ConflictFree R S ∧ ∀ a ∈ S, Defends R S a

/-- A preferred extension is an inclusion-maximal admissible set. -/
def Preferred (R : α → α → Prop) (S : Finset α) : Prop :=
  Admissible R S ∧ ∀ T, Admissible R T → S ⊆ T → T ⊆ S

/-- A complete extension contains exactly the arguments it defends and is conflict-free. -/
def Complete (R : α → α → Prop) (S : Finset α) : Prop :=
  ConflictFree R S ∧ ∀ a, a ∈ S ↔ Defends R S a

/-- A grounded extension is a least complete extension. -/
def Grounded (R : α → α → Prop) (G : Finset α) : Prop :=
  Complete R G ∧ ∀ S, Complete R S → G ⊆ S

omit [Fintype α] [DecidableEq α] in
/-- The preferred extensions form an antichain under inclusion. -/
theorem preferred_antichain {R : α → α → Prop} {S T : Finset α}
    (hS : Preferred R S) (hT : Preferred R T) (hST : S ⊆ T) : S = T := by
  apply Finset.Subset.antisymm hST
  exact hS.2 T hT.1 hST

omit [Fintype α] [DecidableEq α] in
/-- If a nonempty admissible set exists, the empty set is not preferred. -/
theorem empty_not_preferred_of_nonempty_admissible {R : α → α → Prop}
    {S : Finset α} (hS : Admissible R S) (hne : S.Nonempty) :
    ¬ Preferred R ∅ := by
  intro h
  have hsub : S ⊆ (∅ : Finset α) := h.2 S hS (by simp)
  rcases hne with ⟨a, ha⟩
  have := hsub ha
  simp at this

/-- Faces generated by preferred extensions are their finite subsets. -/
def preferredFaces (R : α → α → Prop) : Set (Finset α) :=
  {S | ∃ P, Preferred R P ∧ S ⊆ P}

/-- The generated preferred complex. Its faces are all subsets of preferred extensions. -/
def preferredComplex (R : α → α → Prop) : ASC α where
  faces := preferredFaces R
  down_closed := by
    intro s hs t hts
    rcases hs with ⟨P, hP, hsP⟩
    exact ⟨P, hP, hts.trans hsP⟩
  singletons_mem := by
    intro a ha
    rcases ha with ⟨s, ⟨P, hP, hsP⟩, has⟩
    exact ⟨P, hP, by simpa using hsP has⟩

omit [Fintype α] [DecidableEq α] in
/-- Every preferred extension is a face of the generated complex. -/
theorem preferred_mem_generated {R : α → α → Prop} {S : Finset α}
    (hS : Preferred R S) : S ∈ (preferredComplex R).faces := by
  exact ⟨S, hS, Subset.rfl⟩

section MutualAttack

/-- The two-argument framework in which each distinct argument attacks the other. -/
def mutualAttack (a b : Fin 2) : Prop := a ≠ b

instance : DecidableRel mutualAttack := fun a b =>
  inferInstanceAs (Decidable (a ≠ b))

/-- In the mutual-attack framework, each singleton is admissible. -/
theorem mutual_singleton_admissible (a : Fin 2) :
    Admissible mutualAttack {a} := by
  constructor
  · intro x hx y hy hxy
    simp only [mem_singleton] at hx hy
    subst x; subst y
    exact hxy rfl
  · intro x hx b hba
    simp only [mem_singleton] at hx
    subst x
    exact ⟨a, by simp, hba.symm⟩

/-- In the mutual-attack framework, preferred extensions are exactly the singletons. -/
theorem mutual_preferred_iff (S : Finset (Fin 2)) :
    Preferred mutualAttack S ↔ S.card = 1 := by
  constructor
  · intro h
    have hne : S.Nonempty := by
      by_contra hempty
      rw [not_nonempty_iff_eq_empty.mp hempty] at h
      exact empty_not_preferred_of_nonempty_admissible
        (mutual_singleton_admissible 0) (by simp) h
    have hle : S.card ≤ 1 := by
      by_contra hcard
      have htwo : S.card = 2 := by
        have hu : S.card ≤ Fintype.card (Fin 2) := card_le_univ S
        norm_num at hu ⊢
        omega
      have hS : S = Finset.univ := by
        apply Finset.eq_univ_of_card
        simpa using htwo
      have hcf : ConflictFree mutualAttack S := h.1.1
      have h01 := hcf (a := (0 : Fin 2)) (by simp [hS])
        (b := (1 : Fin 2)) (by simp [hS])
      exact h01 (by decide)
    have hpos : 0 < S.card := Finset.card_pos.mpr hne
    omega
  · intro hcard
    rcases Finset.card_eq_one.mp hcard with ⟨a, rfl⟩
    refine ⟨mutual_singleton_admissible a, ?_⟩
    intro T hT haT x hx
    by_contra hxa
    have ha_mem : a ∈ T := haT (by simp)
    have hax : mutualAttack a x := by
      intro hEq
      subst x
      exact hxa (by simp)
    exact hT.1 ha_mem hx hax

/-- Concrete example required by the structural analysis. -/
example : Preferred mutualAttack ({0} : Finset (Fin 2)) := by
  rw [mutual_preferred_iff]
  simp

/-- Preferred extensions themselves are not downward closed, even for two arguments. -/
theorem preferred_family_not_downward_closed :
    ¬ (∀ (S T : Finset (Fin 2)), Preferred mutualAttack S → T ⊆ S →
      Preferred mutualAttack T) := by
  intro h
  have hp : Preferred mutualAttack ({0} : Finset (Fin 2)) :=
    (mutual_preferred_iff _).2 (by simp)
  have he := h {0} ∅ hp (by simp)
  have := (mutual_preferred_iff ∅).1 he
  simp at this

end MutualAttack

section NoAttack

/-- The attack-free framework. -/
def noAttack (_ _ : α) : Prop := False

omit [Fintype α] [DecidableEq α] in
/-- Every set is admissible in an attack-free framework. -/
theorem noAttack_admissible (S : Finset α) : Admissible noAttack S := by
  constructor
  · intro a ha b hb hab
    exact hab
  · intro a ha b hba
    exact False.elim hba

omit [DecidableEq α] in
/-- The unique preferred extension in an attack-free finite framework is the full vertex set. -/
theorem noAttack_preferred_iff (S : Finset α) :
    Preferred noAttack S ↔ S = Finset.univ := by
  constructor
  · intro h
    apply Finset.eq_univ_of_forall
    intro a
    exact h.2 Finset.univ (noAttack_admissible Finset.univ) (by simp) (by simp)
  · rintro rfl
    refine ⟨noAttack_admissible Finset.univ, ?_⟩
    intro T hT hsub
    simp

omit [DecidableEq α] in
/-- The grounded extension of an attack-free framework is the full vertex set. -/
theorem noAttack_grounded_iff (G : Finset α) :
    Grounded noAttack G ↔ G = Finset.univ := by
  constructor
  · intro h
    apply Finset.eq_univ_of_forall
    intro a
    exact (h.1.2 a).2 (by intro b hb; exact False.elim hb)
  · rintro rfl
    constructor
    · constructor
      · intro a ha b hb hab
        exact hab
      · intro a
        constructor
        · intro ha b hb
          exact False.elim hb
        · intro h
          simp
    · intro S hS a ha
      exact (hS.2 a).2 (by intro b hb; exact False.elim hb)

/-- The proposed Euler/semantics identity already gives `2 = -1` on two
isolated arguments: two vertices, no attacks, one preferred extension, and a
grounded extension of size two. -/
theorem two_isolated_numerical_obstruction :
    ((2 : ℤ) - 0 + 0) ≠ ((1 : ℤ) - 2) := by
  omega

/-- The semantic counts used by the numerical obstruction are forced by the
attack-free semantics, rather than chosen independently. -/
theorem two_isolated_semantics {P G : Finset (Fin 2)}
    (hP : Preferred (noAttack : Fin 2 → Fin 2 → Prop) P)
    (hG : Grounded (noAttack : Fin 2 → Fin 2 → Prop) G) :
    P.card = 2 ∧ G.card = 2 := by
  have hPu : P = Finset.univ := (noAttack_preferred_iff P).1 hP
  have hGu : G = Finset.univ := (noAttack_grounded_iff G).1 hG
  constructor <;> simp [hPu, hGu]

end NoAttack

-- !-- Lab Notes -- !--
-- Hypotheses, ranked by expected impact:
-- (1) semantic Euler characteristics are recoverable from generated complexes;
-- (2) homology of the generated complex detects attack cycles;
-- (3) semantic equivalence induces simple-homotopy equivalence;
-- (4) grounded extensions are topologically detectable as canonical cores;
-- (5) preferred extensions themselves form a simplicial complex;
-- (6) the proposed numerical Euler/semantics identity holds universally.
-- The first four are bold cross-domain conjectures linking argumentation,
-- combinatorial topology, and semantic invariance; the final two are the
-- foundational claims tested here.
-- Experiment: the mutual-attack pair and the attack-free pair were analyzed
-- exactly. The former has two singleton preferred extensions; the latter has
-- one full preferred extension and a two-element grounded extension.
-- Analysis: maximality makes preferred extensions an antichain, fundamentally
-- opposing downward closure. Passing to `preferredFaces` repairs the topology
-- but changes the object. The numerical identity fails on two isolated vertices.
-- Critique: the counterexamples include no homology computation and therefore
-- do not claim that cycles in an attack graph model homological cycles. They
-- isolate earlier boundary failures: the family is not a complex, and even the
-- dimension-zero arithmetic is incompatible with semantics.
-- Synthesis: the robust bridge is the generated downward closure. Future work
-- should study which semantic information survives this closure and should use
-- the face-number Euler characteristic of that complex.
-- Generalization: `preferred_antichain` holds for every finite argument type and
-- arbitrary attack relation; the generated-complex construction is equally broad.
-- Boundary case: if no nonempty admissible set exists, the empty set can be
-- preferred, so `empty_not_preferred_of_nonempty_admissible` states the exact guard.
-- External signals: no arXiv, OEIS, or LMFDB signal was supplied; target selection
-- was therefore driven by the conjecture's smallest finite boundary cases.
-- !-- End Lab Notes -- !--

end ArgumentationTopology