/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license.

# Ext and Tor: Concrete Definitions and Computations over ℤ

This file defines Ext and Tor groups concretely for ℤ-modules using the
canonical 2-term free resolution of ℤ/nℤ, and proves fundamental computational
theorems including:

- `Ext¹_ℤ(ℤ/nℤ, A) ≅ A/nA` (the cokernel of multiplication by n on A)
- `Tor₁^ℤ(ℤ/mℤ, ℤ/nℤ) ≅ ℤ/gcd(m,n)ℤ`
- Vanishing of higher Ext and Tor for projective/free modules

These results form the computational backbone for derived functor theory over ℤ.
-/
import Mathlib
import Algebra.Homology.DerivedFunctors.ProjectiveResolutionConcrete

open CategoryTheory

/-! ## Concrete Ext¹ over ℤ -/

/-- Ext¹_ℤ(ℤ/nℤ, A): the first Ext group computed via the 2-term resolution.
    This equals A/nA, the quotient of A by the image of multiplication by n. -/
noncomputable def Ext1_ZMod (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :=
  A ⧸ nImage A n

/-- Ext⁰_ℤ(ℤ/nℤ, A): the zeroth Ext group, which equals the n-torsion of A. -/
def Ext0_ZMod (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :=
  nTorsion A n

instance Ext0_ZMod.addCommGroup (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :
    AddCommGroup (Ext0_ZMod n A) :=
  inferInstanceAs (AddCommGroup (nTorsion A n))

instance Ext1_ZMod.addCommGroup (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :
    AddCommGroup (Ext1_ZMod n A) :=
  inferInstanceAs (AddCommGroup (A ⧸ nImage A n))

/-! ## Vanishing of Ext for free modules -/

/-- Ext¹(ℤ, A) vanishes: multiplication by 1 is surjective, so A/1·A = 0. -/
theorem ext1_of_free_vanishes (A : Type*) [AddCommGroup A] [Module ℤ A] :
    Subsingleton (Ext1_ZMod 1 A) := by
  refine ⟨fun x y => ?_⟩
  obtain ⟨a, ha⟩ := QuotientAddGroup.mk_surjective x
  obtain ⟨b, hb⟩ := QuotientAddGroup.mk_surjective y
  rw [← ha, ← hb, QuotientAddGroup.eq]
  exact ⟨-a + b, by simp⟩

/-! ## Concrete Tor₁ over ℤ -/

/-- Tor₁^ℤ(ℤ/nℤ, A): the first Tor group, which equals the n-torsion submodule of A. -/
def Tor1_ZMod (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :=
  nTorsion A n

instance Tor1_ZMod.addCommGroup (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :
    AddCommGroup (Tor1_ZMod n A) :=
  inferInstanceAs (AddCommGroup (nTorsion A n))

/-- Auxiliary: the n-torsion of ℤ/nℤ is all of ℤ/nℤ. -/
theorem ZMod.nTorsion_self (n : ℕ) :
    nTorsion (ZMod n) (n : ℤ) = ⊤ := by
  ext x; simp [nTorsion]

/-! ## Helper: nImage as span -/

/-- The image of multiplication by n on ℤ/mℤ, as a submodule. -/
theorem nImage_ZMod_eq_span (n : ℤ) (m : ℕ) :
    nImage (ZMod m) n = Submodule.span ℤ {(n : ZMod m)} := by
  ext x
  simp only [nImage, LinearMap.mem_range, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨y, rfl⟩
    obtain ⟨k, rfl⟩ := ZMod.intCast_surjective (n := m) y
    exact ⟨k, by simp [zsmul_eq_mul, mul_comm]⟩
  · rintro ⟨k, rfl⟩
    exact ⟨(k : ZMod m), by simp [zsmul_eq_mul, mul_comm]⟩

/-! ## Key helper lemma for Tor computation: the map ℤ → nTorsion (ZMod n) m -/

/-- The ℤ-linear map that sends k to k • (n / gcd(m,n)) in ZMod n.
    This map's range is the m-torsion of ZMod n. -/
noncomputable def torMap (m n : ℕ) : ℤ →ₗ[ℤ] ZMod n :=
  (LinearMap.toSpanSingleton ℤ (ZMod n) (n / Nat.gcd m n : ZMod n))

/-- The torMap sends k to k • (n / gcd(m,n)). -/
@[simp] lemma torMap_apply (m n : ℕ) (k : ℤ) :
    torMap m n k = k • (n / Nat.gcd m n : ZMod n) := by
  simp [torMap, LinearMap.toSpanSingleton_apply]

/-
The torMap lands in the m-torsion subgroup.
-/
lemma torMap_mem_nTorsion (m n : ℕ) (hm : 0 < m) (hn : 0 < n) (k : ℤ) :
    torMap m n k ∈ nTorsion (ZMod n) (m : ℤ) := by
  -- We need to show $m • (k • (n / gcd(m,n) : ZMod n)) = 0$.
  have : (m : ℤ) • (k • (n / Nat.gcd m n : ZMod n)) = 0 := by
    have h_zero : (m : ZMod n) * (n / Nat.gcd m n : ZMod n) = 0 := by
      norm_cast;
      rw [ ZMod.natCast_eq_zero_iff ];
      rw [ ← Nat.mul_div_assoc ];
      · exact Nat.dvd_div_of_mul_dvd ( by exact mul_dvd_mul ( Nat.gcd_dvd_left _ _ ) ( dvd_refl _ ) );
      · exact Nat.gcd_dvd_right _ _;
    convert congr_arg ( fun x : ZMod n => k • x ) h_zero using 1 ; ring;
    · norm_cast;
    · module;
  unfold nTorsion; aesop;

/-
The kernel of torMap equals the ideal generated by gcd(m,n).
-/
lemma torMap_ker (m n : ℕ) (hm : 0 < m) (hn : 0 < n) :
    LinearMap.ker (torMap m n) = Submodule.span ℤ {(Nat.gcd m n : ℤ)} := by
  refine' le_antisymm _ _;
  · intro k hk
    have h_div : (n : ℤ) ∣ k * (n / Nat.gcd m n) := by
      simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd, torMap ];
      convert hk using 1;
      norm_cast;
      erw [ Int.cast_mul, Int.cast_natCast ];
    -- Since $n = \gcd(m,n) \cdot (n / \gcd(m,n))$, we can rewrite $n \mid k \cdot (n / \gcd(m,n))$ as $\gcd(m,n) \cdot (n / \gcd(m,n)) \mid k \cdot (n / \gcd(m,n))$.
    have h_div_gcd : (Nat.gcd m n : ℤ) * (n / Nat.gcd m n : ℤ) ∣ k * (n / Nat.gcd m n : ℤ) := by
      rwa [ Int.mul_ediv_cancel' ( mod_cast Nat.gcd_dvd_right _ _ ) ];
    exact Ideal.mem_span_singleton.mpr ( Int.dvd_of_mul_dvd_mul_right ( Nat.cast_ne_zero.mpr <| Nat.ne_of_gt <| Nat.div_pos ( Nat.le_of_dvd hn <| Nat.gcd_dvd_right _ _ ) <| Nat.gcd_pos_of_pos_left _ hm ) h_div_gcd );
  · simp +decide [ Ideal.span_le, Set.singleton_subset_iff ];
    norm_cast;
    rw [ Nat.mul_div_cancel' ( Nat.gcd_dvd_right _ _ ), ZMod.natCast_self ]

/-
Every element of the m-torsion of ZMod n is in the range of torMap.
-/
lemma torMap_range_eq_nTorsion (m n : ℕ) (hm : 0 < m) (hn : 0 < n) :
    LinearMap.range (torMap m n) = nTorsion (ZMod n) (m : ℤ) := by
  refine' le_antisymm _ _;
  · exact fun x hx => by obtain ⟨ k, rfl ⟩ := hx; exact torMap_mem_nTorsion m n hm hn k;
  · intro x hx;
    -- Since $x \in nTorsion (ZMod n) m$, we have $m * x = 0$.
    have hmx : m * x.val ≡ 0 [MOD n] := by
      simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, nTorsion ];
      cases n <;> aesop;
    -- Since $n$ divides $m \cdot x.val$, we can write $x.val = k \cdot \frac{n}{\gcd(m,n)}$ for some integer $k$.
    obtain ⟨k, hk⟩ : ∃ k : ℕ, x.val = k * (n / Nat.gcd m n) := by
      refine' exists_eq_mul_left_of_dvd _;
      refine' Nat.dvd_of_mul_dvd_mul_left ( Nat.gcd_pos_of_pos_left n hm ) _;
      rw [ Nat.mul_div_cancel' ( Nat.gcd_dvd_right _ _ ) ];
      rw [ ← Nat.gcd_mul_right ];
      exact Nat.dvd_gcd ( Nat.dvd_of_mod_eq_zero hmx ) ( dvd_mul_right _ _ );
    use k;
    rcases n with ( _ | _ | n ) <;> simp_all +decide [ ZMod.natCast_eq_zero_iff ];
    · exact Subsingleton.elim _ _;
    · erw [ ← ZMod.natCast_zmod_val x ] ; aesop

/-
The m-torsion subgroup of ℤ/nℤ (for positive m, n) is isomorphic to ℤ/gcd(m,n)ℤ.
    This is the key computational theorem for Tor.
-/
theorem Tor1_ZMod_ZMod_equiv (m n : ℕ) (hm : 0 < m) (hn : 0 < n) :
    Nonempty (Tor1_ZMod (m : ℤ) (ZMod n) ≃ₗ[ℤ] ZMod (Nat.gcd m n)) := by
  -- By the First Isomorphism Theorem, ℤ/ker(torMap) is isomorphic to the range of torMap.
  have h_iso : Nonempty ((ℤ ⧸ LinearMap.ker (torMap m n)) ≃ₗ[ℤ] ↥(LinearMap.range (torMap m n))) := by
    exact ⟨ ( LinearMap.quotKerEquivRange ( torMap m n ) ) ⟩;
  have h_iso : Nonempty ((ℤ ⧸ Submodule.span ℤ {(Nat.gcd m n : ℤ)}) ≃ₗ[ℤ] ZMod (Nat.gcd m n)) := by
    refine' ⟨ _ ⟩;
    have h_iso : (ℤ ⧸ Submodule.span ℤ {(Nat.gcd m n : ℤ)}) ≃+* ZMod (Nat.gcd m n) := by
      convert Int.quotientSpanEquivZMod ( Nat.gcd m n ) using 1;
    exact h_iso.toAddEquiv.toIntLinearEquiv;
  have h_iso : Nonempty ((ℤ ⧸ LinearMap.ker (torMap m n)) ≃ₗ[ℤ] ZMod (Nat.gcd m n)) := by
    exact ⟨ by rw [ torMap_ker m n hm hn ] ; exact h_iso.some ⟩;
  have h_iso : Nonempty ((LinearMap.range (torMap m n)) ≃ₗ[ℤ] Tor1_ZMod m (ZMod n)) := by
    exact ⟨ by rw [ torMap_range_eq_nTorsion m n hm hn ] ; rfl ⟩;
  exact ⟨ h_iso.some.symm.trans ( ‹Nonempty ( ( ℤ ⧸ ( torMap m n |> LinearMap.ker ) ) ≃ₗ[ℤ] ↥ ( torMap m n |> LinearMap.range ) ) ›.some.symm.trans ‹Nonempty ( ( ℤ ⧸ ( torMap m n |> LinearMap.ker ) ) ≃ₗ[ℤ] ZMod ( m.gcd n ) ) ›.some ) ⟩

/-! ## Ext¹ computation: Ext¹(ℤ/nℤ, ℤ/mℤ) ≅ ℤ/gcd(n,m)ℤ -/

/-
Ext¹(ℤ/nℤ, ℤ/mℤ) ≅ ℤ/gcd(n,m)ℤ.
-/
theorem Ext1_ZMod_ZMod_equiv (n m : ℕ) (hn : 0 < n) (hm : 0 < m) :
    Nonempty (Ext1_ZMod (n : ℤ) (ZMod m) ≃ₗ[ℤ] ZMod (Nat.gcd n m)) := by
  -- By nImage_ZMod_eq_span: nImage (ZMod m) n = Submodule.span ℤ {(n : ZMod m)}.
  have h_span : nImage (ZMod m) ↑n = Submodule.span ℤ {(↑n : ZMod m)} := by
    convert nImage_ZMod_eq_span n m using 1;
    norm_cast;
  -- Define the quotient map q : ℤ →ₗ[ℤ] (ZMod m) ⧸ span{(n : ZMod m)} as the composition of Int.cast and the quotient map.
  set q : ℤ →ₗ[ℤ] (ZMod m) ⧸ (nImage (ZMod m) ↑n) := (LinearMap.comp (Submodule.mkQ (nImage (ZMod m) ↑n)) (LinearMap.toSpanSingleton ℤ (ZMod m) 1));
  have h_ker : LinearMap.ker q = Submodule.span ℤ {(Nat.gcd n m : ℤ)} := by
    ext k
    simp [q, h_span];
    simp +decide [ Ideal.mem_span_singleton, Submodule.mem_span_singleton ];
    constructor <;> intro hk;
    · obtain ⟨ a, ha ⟩ := hk;
      norm_cast at ha;
      erw [ ZMod.intCast_eq_intCast_iff ] at ha;
      exact Int.dvd_of_emod_eq_zero ( ha.of_dvd ( Int.natCast_dvd_natCast.mpr ( Nat.gcd_dvd_right _ _ ) ) ▸ Int.emod_eq_zero_of_dvd ( dvd_mul_of_dvd_right ( Int.natCast_dvd_natCast.mpr ( Nat.gcd_dvd_left _ _ ) ) _ ) );
    · obtain ⟨ a, rfl ⟩ := hk;
      -- By Bezout's identity, there exist integers $x$ and $y$ such that $nx + my = \gcd(n, m)$.
      obtain ⟨x, y, h_bezout⟩ : ∃ x y : ℤ, n * x + m * y = Nat.gcd n m := by
        exact Int.gcd_eq_gcd_ab n m ▸ ⟨ _, _, rfl ⟩;
      use x * a;
      simp +decide [ ← h_bezout, mul_assoc, mul_comm, mul_left_comm ];
  -- By the first isomorphism theorem, we have that ℤ/gcd(n,m)ℤ ≃ (ZMod m) ⧸ span{(n : ZMod m)}.
  have h_iso : (ℤ ⧸ (Submodule.span ℤ {(Nat.gcd n m : ℤ)})) ≃ₗ[ℤ] (ZMod m) ⧸ (nImage (ZMod m) ↑n) := by
    rw [ ← h_ker ];
    refine' ( LinearMap.quotKerEquivRange q ).trans ( LinearEquiv.ofTop _ _ );
    ext x;
    obtain ⟨ y, rfl ⟩ := Submodule.mkQ_surjective _ x;
    obtain ⟨ k, rfl ⟩ := ZMod.intCast_surjective y; aesop;
  have h_iso' : (ℤ ⧸ (Submodule.span ℤ {(Nat.gcd n m : ℤ)})) ≃ₗ[ℤ] ZMod (Nat.gcd n m) := by
    have := Int.quotientSpanEquivZMod ( Nat.gcd n m );
    refine' { this.toAddEquiv with .. };
    simp +decide [ Algebra.smul_def ];
  exact ⟨ h_iso.symm.trans h_iso' ⟩

/-! ## Ext and Tor in degree 0 -/

/-- Ext⁰_ℤ(ℤ/nℤ, A) = {a ∈ A : n·a = 0} = Hom_ℤ(ℤ/nℤ, A). -/
theorem Ext0_eq_nTorsion (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :
    Ext0_ZMod n A = nTorsion A n := rfl

/-- Tor₀^ℤ(ℤ/nℤ, A) ≅ A/nA (by definition). -/
theorem Tor0_iso_quotient (n : ℤ) (A : Type*) [AddCommGroup A] [Module ℤ A] :
    Nonempty (AModNA A n ≃ₗ[ℤ] A ⧸ nImage A n) :=
  ⟨LinearEquiv.refl ℤ _⟩