/-
  # Gröbner Derandomization — Algebraic Verification for Circuit Identity Testing

  Bridge: connects Algebra (ideal theory, Noetherian rings, derivations) to
  Computation (derandomization of PIT) and Cryptography (polynomial commitment verification).

  Key results:
  - Jacobian ideal characterization
  - Evaluation-based PIT soundness
  - Monomial circuit constructions
  - Variable usage analysis
  - Certified circuit complexity certificates
-/

import Mathlib
import Algebra.CircuitComplexity.AlgebraicCircuitComplexity
import Algebra.CircuitComplexity.NullstellensatzPIT

namespace AlgebraicCircuitComplexity

open MvPolynomial Finset

variable {R : Type*} {n : ℕ}

/-! ## Partial Derivative Framework for PIT

Bridge: connects Algebra (derivations) to Machine Learning (backpropagation). -/

/-- The Jacobian ideal of a polynomial f is generated by all partial derivatives.

    Bridge: connects Algebra (Jacobian ideal) to Computation (gradient structure). -/
noncomputable def jacobianIdeal [CommSemiring R] (f : MvPolynomial (Fin n) R) :
    Ideal (MvPolynomial (Fin n) R) :=
  Ideal.span (Set.range (fun i : Fin n => (MvPolynomial.pderiv i) f))

/-- All partial derivatives of the zero polynomial are zero. -/
theorem pderiv_zero_eq [CommSemiring R] (i : Fin n) :
    (MvPolynomial.pderiv i) (0 : MvPolynomial (Fin n) R) = 0 :=
  map_zero _

/-- All partial derivatives of a constant polynomial are zero. -/
theorem pderiv_C_eq [CommSemiring R] (r : R) (i : Fin n) :
    (MvPolynomial.pderiv i) (MvPolynomial.C r : MvPolynomial (Fin n) R) = 0 :=
  MvPolynomial.pderiv_C

/-- Partial derivative is additive: ∂(f+g)/∂xᵢ = ∂f/∂xᵢ + ∂g/∂xᵢ. -/
theorem pderiv_add_eq [CommSemiring R] (i : Fin n)
    (f g : MvPolynomial (Fin n) R) :
    (MvPolynomial.pderiv i) (f + g) =
    (MvPolynomial.pderiv i) f + (MvPolynomial.pderiv i) g :=
  map_add _ f g

/-- Partial derivative satisfies the Leibniz rule using smul notation. -/
theorem pderiv_mul_leibniz [CommSemiring R] (i : Fin n)
    (f g : MvPolynomial (Fin n) R) :
    (MvPolynomial.pderiv i) (f * g) =
    f • (MvPolynomial.pderiv i) g + g • (MvPolynomial.pderiv i) f :=
  Derivation.leibniz _ f g

/-! ## Evaluation-Based PIT

Bridge: connects Computation (deterministic PIT) to Cryptography (polynomial commitment verification). -/

/-- An evaluation-based PIT test for circuits using a list of evaluation points.

    Bridge: connects Computation (evaluation-based testing) to Cryptography
    (polynomial evaluation proofs). -/
def evaluationPITTest [CommSemiring R] [DecidableEq R]
    (C : AlgCircuit R n) (points : List (Fin n → R)) : Bool :=
  points.all (fun v => decide (C.eval v = 0))

/-- If the evaluation test passes, the circuit is zero on those points.

    Bridge: connects Computation (test soundness) to Cryptography (proof system soundness). -/
theorem evaluationPITTest_sound [CommSemiring R] [DecidableEq R]
    (C : AlgCircuit R n) (points : List (Fin n → R))
    (h : evaluationPITTest C points = true)
    (v : Fin n → R) (hv : v ∈ points) :
    C.eval v = 0 := by
  simp only [evaluationPITTest, List.all_eq_true] at h
  have := h v hv
  simpa using this

/-- A circuit that is zero on all points in S has its polynomial in every evaluation kernel.

    Bridge: connects Computation (circuit testing) to Algebra (evaluation kernel). -/
theorem zero_on_eval_set_implies_poly_zero [CommRing R]
    (C : AlgCircuit R n) (S : Set (Fin n → R))
    (h : ∀ v ∈ S, C.eval v = 0) :
    ∀ v ∈ S, MvPolynomial.eval v C.toMvPolynomial = 0 := by
  intro v hv
  rw [← eval_eq_mvpolynomial_eval]
  exact h v hv

/-! ## Monomial Circuit Constructions

Bridge: connects Computation (circuit normal forms) to Algebra (polynomial representations). -/

/-- A monomial circuit computes a product of variables. -/
def monomialCircuit [CommSemiring R] (vars : List (Fin n)) : AlgCircuit R n :=
  match vars with
  | [] => .const 1
  | [i] => .var i
  | i :: rest => .mul (.var i) (monomialCircuit rest)

/-- The monomial circuit evaluates to the product of the specified variables. -/
theorem monomialCircuit_eval [CommSemiring R] (vars : List (Fin n)) (v : Fin n → R) :
    (monomialCircuit vars).eval v = (vars.map v).prod := by
  induction vars with
  | nil => simp [monomialCircuit, AlgCircuit.eval]
  | cons i rest ih =>
    match rest, ih with
    | [], _ => simp [monomialCircuit, AlgCircuit.eval]
    | j :: rest', ih =>
      simp only [monomialCircuit, AlgCircuit.eval, List.map_cons, List.prod_cons]
      rw [ih]
      simp [List.map_cons, List.prod_cons]

/-- The monomial circuit has degree bound at most the length of the variable list. -/
theorem monomialCircuit_degreeBound [CommSemiring R] (vars : List (Fin n)) :
    (monomialCircuit vars : AlgCircuit R n).degreeBound ≤ vars.length := by
  induction vars with
  | nil => simp [monomialCircuit, AlgCircuit.degreeBound]
  | cons i rest ih =>
    match rest with
    | [] => simp [monomialCircuit, AlgCircuit.degreeBound]
    | j :: rest' =>
      simp only [monomialCircuit, AlgCircuit.degreeBound, List.length_cons]
      have : (monomialCircuit (j :: rest') : AlgCircuit R n).degreeBound ≤ (j :: rest').length := ih
      simp [List.length_cons] at this
      omega

/-! ## Variable Usage Analysis

Bridge: connects Computation (variable reduction) to Cryptography (dimension reduction). -/

/-- Set of distinct variables used in a circuit's computation. -/
def usedVars [CommSemiring R] : AlgCircuit R n → Finset (Fin n)
  | .const _ => ∅
  | .var i => {i}
  | .add C₁ C₂ => usedVars C₁ ∪ usedVars C₂
  | .mul C₁ C₂ => usedVars C₁ ∪ usedVars C₂

/-- The number of used variables is at most n. -/
theorem usedVars_card_le [CommSemiring R] (C : AlgCircuit R n) :
    (usedVars C).card ≤ n :=
  (Finset.card_le_card (Finset.subset_univ _)).trans (Finset.card_fin n).le

/-- A circuit with no used variables computes a constant function. -/
theorem empty_usedVars_constant [CommSemiring R] (C : AlgCircuit R n)
    (h : usedVars C = ∅) :
    ∀ v₁ v₂ : Fin n → R, C.eval v₁ = C.eval v₂ := by
  induction C with
  | const _ => intros; rfl
  | var i => simp [usedVars] at h
  | add C₁ C₂ ih₁ ih₂ =>
    simp [usedVars, Finset.union_eq_empty] at h
    intro v₁ v₂
    simp only [AlgCircuit.eval, ih₁ h.1 v₁ v₂, ih₂ h.2 v₁ v₂]
  | mul C₁ C₂ ih₁ ih₂ =>
    simp [usedVars, Finset.union_eq_empty] at h
    intro v₁ v₂
    simp only [AlgCircuit.eval, ih₁ h.1 v₁ v₂, ih₂ h.2 v₁ v₂]

/-- Used variables of a sum circuit is the union of used variables. -/
@[simp] theorem usedVars_add [CommSemiring R] (C₁ C₂ : AlgCircuit R n) :
    usedVars (.add C₁ C₂ : AlgCircuit R n) = usedVars C₁ ∪ usedVars C₂ := rfl

/-- Used variables of a product circuit is the union of used variables. -/
@[simp] theorem usedVars_mul [CommSemiring R] (C₁ C₂ : AlgCircuit R n) :
    usedVars (.mul C₁ C₂ : AlgCircuit R n) = usedVars C₁ ∪ usedVars C₂ := rfl

/-! ## Certified Circuit Complexity Certificates

Bridge: connects Computation (resource-bounded computation) to Cryptography
(certified_bounds) and Machine Learning (certified_robustness). -/

/-- A certified circuit bundles a circuit with machine-verified proofs
    of depth, degree, and size bounds.

    Bridge: connects Computation (resource certification) to Machine Learning
    (lipschitz_certified neural network bounds). -/
structure CertifiedCircuit (R : Type*) [CommSemiring R] (n : ℕ) where
  circuit : AlgCircuit R n
  maxDepth : ℕ
  maxDegree : ℕ
  maxSize : ℕ
  depth_cert : circuit.depth ≤ maxDepth
  degree_cert : circuit.degreeBound ≤ maxDegree
  size_cert : circuit.size ≤ maxSize

/-- Construct a certified circuit from a depth bound alone.

    Bridge: connects Computation (automatic bound derivation) to Cryptography
    (post_quantum parameter derivation). -/
noncomputable def CertifiedCircuit.fromDepthBound [CommSemiring R] (C : AlgCircuit R n)
    (d : ℕ) (hd : C.depth ≤ d) : CertifiedCircuit R n where
  circuit := C
  maxDepth := d
  maxDegree := 2 ^ d
  maxSize := C.size
  depth_cert := hd
  degree_cert := (degreeBound_le_two_pow_depth C).trans
    (Nat.pow_le_pow_right (by omega) hd)
  size_cert := le_refl _

/-- The depth certificate implies a size lower bound. -/
theorem CertifiedCircuit.size_ge_depth [CommSemiring R]
    (cc : CertifiedCircuit R n) :
    cc.circuit.depth + 1 ≤ cc.maxSize :=
  (size_ge_depth_succ cc.circuit).trans cc.size_cert

/-- Two certified circuits can be composed (added) with derived certificates. -/
noncomputable def CertifiedCircuit.addCircuits [CommSemiring R]
    (cc₁ cc₂ : CertifiedCircuit R n) : CertifiedCircuit R n where
  circuit := .add cc₁.circuit cc₂.circuit
  maxDepth := 1 + max cc₁.maxDepth cc₂.maxDepth
  maxDegree := max cc₁.maxDegree cc₂.maxDegree
  maxSize := 1 + cc₁.maxSize + cc₂.maxSize
  depth_cert := by
    simp only [AlgCircuit.depth]
    have := cc₁.depth_cert; have := cc₂.depth_cert; omega
  degree_cert := by
    simp only [AlgCircuit.degreeBound]
    exact max_le_max cc₁.degree_cert cc₂.degree_cert
  size_cert := by
    simp only [AlgCircuit.size]
    have := cc₁.size_cert; have := cc₂.size_cert; omega

/-- Two certified circuits can be composed (multiplied) with derived certificates. -/
noncomputable def CertifiedCircuit.mulCircuits [CommSemiring R]
    (cc₁ cc₂ : CertifiedCircuit R n) : CertifiedCircuit R n where
  circuit := .mul cc₁.circuit cc₂.circuit
  maxDepth := 1 + max cc₁.maxDepth cc₂.maxDepth
  maxDegree := cc₁.maxDegree + cc₂.maxDegree
  maxSize := 1 + cc₁.maxSize + cc₂.maxSize
  depth_cert := by
    simp only [AlgCircuit.depth]
    have := cc₁.depth_cert; have := cc₂.depth_cert; omega
  degree_cert := by
    simp only [AlgCircuit.degreeBound]
    exact Nat.add_le_add cc₁.degree_cert cc₂.degree_cert
  size_cert := by
    simp only [AlgCircuit.size]
    have := cc₁.size_cert; have := cc₂.size_cert; omega

/-- The evaluation of an added certified circuit is the sum of evaluations. -/
theorem CertifiedCircuit.addCircuits_eval [CommSemiring R]
    (cc₁ cc₂ : CertifiedCircuit R n) (v : Fin n → R) :
    (cc₁.addCircuits cc₂).circuit.eval v =
    cc₁.circuit.eval v + cc₂.circuit.eval v := rfl

/-- The evaluation of a multiplied certified circuit is the product. -/
theorem CertifiedCircuit.mulCircuits_eval [CommSemiring R]
    (cc₁ cc₂ : CertifiedCircuit R n) (v : Fin n → R) :
    (cc₁.mulCircuits cc₂).circuit.eval v =
    cc₁.circuit.eval v * cc₂.circuit.eval v := rfl

/-! ## PIT Summary Theorems

Bridge: connects the full chain from Algebra through Computation to Cryptography. -/

/-- A circuit computing zero polynomial is functionally zero on all inputs.

    Bridge: connects Algebra (polynomial = 0) to Computation (circuit = 0). -/
theorem pit_forward [CommSemiring R] (C : AlgCircuit R n)
    (h : C.toMvPolynomial = 0) :
    C.isZeroFunction :=
  zero_poly_implies_zero_function C h

/-- A circuit that is NOT the zero function must have a witness point.

    Bridge: connects Computation (witness search) to Cryptography
    (finding non-trivial evaluations for soundness proofs). -/
theorem pit_witness_exists [CommSemiring R] (C : AlgCircuit R n)
    (h : ¬C.isZeroFunction) :
    ∃ v : Fin n → R, C.eval v ≠ 0 := by
  by_contra h'
  push_neg at h'
  exact h h'

/-- PIT is equivalent to the non-existence of a nonzero evaluation witness.

    Bridge: connects Computation (PIT) to Algebra (polynomial nonvanishing). -/
theorem pit_iff_no_witness [CommSemiring R] (C : AlgCircuit R n) :
    C.isZeroFunction ↔ ¬∃ v : Fin n → R, C.eval v ≠ 0 := by
  constructor
  · intro h ⟨v, hv⟩; exact hv (h v)
  · intro h v; by_contra hv; exact h ⟨v, hv⟩

end AlgebraicCircuitComplexity