/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Newton's Method for Idempotent Lifting

## Overview

An element `e` of a ring `R` is **idempotent** if `e * e = e`. The **idempotent lifting
problem** asks: given a ring `R`, an ideal `I`, and an idempotent `ē ∈ R/I`, can we find
an idempotent `e ∈ R` that maps to `ē`?

This file solves the lifting problem using an algebraic analogue of **Newton's method**.
The polynomial `f(t) = 3t² - 2t³` acts as a correction map: if `e` is an "approximate
idempotent" (meaning `e² - e` is small in a nilpotency sense), then `f(e)` is a better
approximation. The key identity

  `f(e)² - f(e) = (e² - e)² · (4e² - 4e - 3)`

shows that the "defect" `f(e)² - f(e)` is controlled by the **square** of the original
defect `e² - e`. This quadratic convergence — the hallmark of Newton's method — means
that after `k` iterations, the defect becomes `(e² - e)^(2^k)`, which vanishes if the
original defect is nilpotent.

## Main Results

* `newtonMap_defect_sq` — The key squaring identity for the Newton map.
* `newtonMap_isIdempotentElem` — If `(e² - e)² = 0`, the Newton map yields an idempotent.
* `iterNewtonMap_isIdempotentElem` — General lifting: if `(e² - e)^(2^k) = 0`,
  then `k` iterations produce a true idempotent.
* `iterNewtonMap_sub_mem_ideal` — The lifted idempotent is congruent to `e`
  modulo the ideal generated by `e² - e`.
* `geom_series_nilpotent_inv` — Geometric series gives an explicit inverse for `1 - x`
  when `x` is nilpotent.

## Mathematical Significance

The idempotent lifting theorem is a cornerstone of commutative algebra:
- It implies **Hensel's Lemma** for splitting polynomials over complete local rings.
- It is essential for the **Krull–Schmidt theorem** on decomposition of modules.
- In **algebraic K-theory**, idempotent lifting ensures that K₀ is well-behaved
  under nilpotent extensions.
- The polynomial `3t² - 2t³` is the unique cubic Hermite interpolant satisfying
  `f(0) = 0`, `f(1) = 1`, `f'(0) = 0`, `f'(1) = 0` — connecting to the theory
  of **smoothstep functions** used in computer graphics.

## References

* Lam, T.Y., *A First Course in Noncommutative Rings*, Chapter 21.
* Atiyah, M.F. and Macdonald, I.G., *Introduction to Commutative Algebra*, Chapter 1.
-/

namespace NewtonIdempotent

/-! ### The Newton Map -/

section NewtonMap

variable {R : Type*} [CommRing R]

/-- The **Newton map** for idempotent iteration: `f(e) = 3e² - 2e³`.

This is the algebraic analogue of one step of Newton's method applied to the
equation `t² - t = 0`. It is the unique cubic polynomial satisfying:
- `f(0) = 0` and `f(1) = 1` (it fixes the "target" idempotents)
- `f'(0) = 0` and `f'(1) = 0` (double roots ensure quadratic convergence) -/
def newtonMap (e : R) : R := 3 * e ^ 2 - 2 * e ^ 3

/-- **The Fundamental Squaring Identity.** The Newton map squares the idempotent defect:
`f(e)² - f(e) = (e² - e)² · (4e² - 4e - 3)`.

This is the key engine of the lifting theorem. It shows that one application of the
Newton map replaces the defect `δ = e² - e` with `δ² · g(e)`, so the defect's
nilpotency order is (at least) doubled at each step. -/
theorem newtonMap_defect_sq (e : R) :
    (newtonMap e) ^ 2 - newtonMap e =
      (e ^ 2 - e) ^ 2 * (4 * e ^ 2 - 4 * e - 3) := by
  unfold newtonMap; ring

/-- The Newton map moves `e` by a multiple of the defect `e² - e`. In particular,
`f(e) ≡ e (mod (e² - e))`, so the lifted idempotent lies in the same residue class. -/
theorem newtonMap_sub_self (e : R) :
    newtonMap e - e = (e ^ 2 - e) * (1 - 2 * e) := by
  unfold newtonMap; ring

/-
Idempotent elements are fixed points of the Newton map.
-/
theorem newtonMap_of_isIdempotentElem {e : R} (he : IsIdempotentElem e) :
    newtonMap e = e := by
  unfold newtonMap; rw [ show e ^ 3 = e ^ 2 * e by ring, show e ^ 2 = e * e by ring, he ] ; ring;
  rw [ sq, he ] ; ring

/-
**Base Case Lifting Theorem.** If the squared defect vanishes — i.e.,
`(e² - e)² = 0` — then one application of the Newton map produces a true idempotent.

This is the foundational step. The general theorem follows by iterating this.
-/
theorem newtonMap_isIdempotentElem {e : R}
    (h : (e ^ 2 - e) ^ 2 = 0) : IsIdempotentElem (newtonMap e) := by
  unfold IsIdempotentElem; have := newtonMap_defect_sq e; simp_all +decide [ sq, sub_eq_iff_eq_add ] ;

end NewtonMap

/-! ### Iterated Newton Map and the General Lifting Theorem -/

section Iteration

variable {R : Type*} [CommRing R]

/-- Iterated application of the Newton map. `iterNewtonMap e k` applies `newtonMap`
to `e` a total of `k` times. -/
def iterNewtonMap (e : R) : ℕ → R
  | 0 => e
  | n + 1 => newtonMap (iterNewtonMap e n)

@[simp] theorem iterNewtonMap_zero (e : R) : iterNewtonMap e 0 = e := rfl
@[simp] theorem iterNewtonMap_succ (e : R) (n : ℕ) :
    iterNewtonMap e (n + 1) = newtonMap (iterNewtonMap e n) := rfl

/-
**Key Inductive Lemma.** If `(e² - e)^(2^k) = 0`, then `(f(e)² - f(e))^(2^(k-1)) = 0`
where `f = newtonMap`. This drives the induction in the main theorem.
-/
theorem defect_pow_of_newtonMap {e : R} {k : ℕ}
    (h : (e ^ 2 - e) ^ (2 ^ (k + 1)) = 0) :
    ((newtonMap e) ^ 2 - newtonMap e) ^ (2 ^ k) = 0 := by
  rw [ newtonMap_defect_sq ];
  convert congr_arg ( · * ( 4 * e ^ 2 - 4 * e - 3 ) ^ 2 ^ k ) h using 1 <;> ring;
  rw [ pow_mul' ] ; rw [ ← mul_pow ] ; ring;

/-
**The General Idempotent Lifting Theorem.** If the defect `e² - e` is nilpotent
with `(e² - e)^(2^k) = 0`, then `k` iterations of the Newton map produce a true
idempotent.

This is one of the most important results in the structure theory of rings.
Combined with the fact that iterating preserves the residue class modulo `(e² - e)`,
it gives a complete solution to the idempotent lifting problem for nilpotent ideals.
-/
theorem iterNewtonMap_isIdempotentElem {e : R} {k : ℕ}
    (h : (e ^ 2 - e) ^ (2 ^ k) = 0) :
    IsIdempotentElem (iterNewtonMap e k) := by
  induction' k with k ih generalizing e;
  · simp_all +decide [ IsIdempotentElem, sub_eq_zero ];
    rwa [ sq ] at h;
  · convert ih ( defect_pow_of_newtonMap h ) using 1;
    exact Nat.recOn k rfl fun n ih => by rw [ show iterNewtonMap e ( n + 2 ) = newtonMap ( iterNewtonMap e ( n + 1 ) ) by rfl, show iterNewtonMap ( newtonMap e ) ( n + 1 ) = newtonMap ( iterNewtonMap ( newtonMap e ) n ) by rfl, ih ] ;

/-
The lifted idempotent lies in the same residue class as `e` modulo the ideal
generated by the defect `e² - e`.
-/
theorem iterNewtonMap_sub_mem_ideal (e : R) (k : ℕ) :
    iterNewtonMap e k - e ∈ Ideal.span {e ^ 2 - e} := by
  -- By induction on $k$, we can show that $(iterNewtonMap e k)^2 - iterNewtonMap e k$ is in the ideal generated by $e^2 - e$.
  have h_ind : ∀ k, (iterNewtonMap e k)^2 - iterNewtonMap e k ∈ Ideal.span {e ^ 2 - e} := by
    intro k;
    induction' k with k ih;
    · exact Ideal.mem_span_singleton_self _;
    · rw [ show iterNewtonMap e ( k + 1 ) = newtonMap ( iterNewtonMap e k ) by rfl ];
      rw [ Ideal.mem_span_singleton ] at *;
      exact dvd_trans ih ( by rw [ newtonMap_defect_sq ] ; exact dvd_mul_of_dvd_left ( dvd_pow_self _ two_ne_zero ) _ );
  induction' k with k ih <;> simp_all +decide [ Ideal.mem_span_singleton, iterNewtonMap ];
  convert dvd_add ( dvd_mul_of_dvd_right ( h_ind k ) ( 1 - 2 * iterNewtonMap e k ) ) ih using 1 ; ring;
  unfold newtonMap; ring;

end Iteration

/-! ### Geometric Series and Nilpotent Inverses -/

section GeometricSeries

variable {R : Type*} [CommRing R]

/-
**Geometric Series Inverse.** If `x` is nilpotent with `x^n = 0`, then `1 - x` is
a unit with explicit inverse `1 + x + x² + ⋯ + x^(n-1)`.

This is the algebraic analogue of the geometric series `1/(1-x) = 1 + x + x² + ⋯`
from analysis, but here it terminates after finitely many terms because `x` is nilpotent.
-/
theorem geom_series_nilpotent_inv (x : R) (n : ℕ) (hx : x ^ n = 0) :
    (1 - x) * (∑ k ∈ Finset.range n, x ^ k) = 1 := by
  rw [ mul_comm, geom_sum_mul_neg, hx, sub_zero ]

/-
The geometric series also works on the right side, giving a two-sided inverse.
-/
theorem geom_series_nilpotent_inv' (x : R) (n : ℕ) (hx : x ^ n = 0) :
    (∑ k ∈ Finset.range n, x ^ k) * (1 - x) = 1 := by
  rw [ geom_sum_mul_neg, hx, sub_zero ]

/-
**Unit Construction.** If `x` is nilpotent, then `1 - x` is a unit. This provides
an explicit unit, unlike the existential statement in Mathlib.
-/
theorem isUnit_one_sub_of_nilpotent (x : R) (n : ℕ) (hx : x ^ n = 0) :
    IsUnit (1 - x) := by
  exact isUnit_iff_exists_inv.2 ⟨ ∑ k ∈ Finset.range n, x ^ k, geom_series_nilpotent_inv x n hx ⟩

/-
If `u` is a unit and `n` is nilpotent, then `u + n` is a unit.

This is the **stability of units under nilpotent perturbation**, a fundamental
result in ring theory with applications to perturbation theory in linear algebra
and numerical analysis.
-/
theorem isUnit_add_nilpotent {u n : R} (hu : IsUnit u) {m : ℕ} (hn : n ^ m = 0) :
    IsUnit (u + n) := by
  -- Write $u + n = u \cdot (1 + u^{-1} \cdot n)$.
  obtain ⟨v, hv⟩ : ∃ v : R, u * v = 1 := by
    exact hu.exists_right_inv;
  have h_nilpotent : IsNilpotent (v * n) := by
    exact ⟨ m, by rw [ mul_pow, hn, MulZeroClass.mul_zero ] ⟩;
  -- Since $v * n$ is nilpotent, $1 + v * n$ is a unit.
  have h_unit : IsUnit (1 + v * n) := by
    exact IsNilpotent.isUnit_one_add h_nilpotent;
  convert h_unit.mul hu using 1 ; linear_combination' -hv * n

end GeometricSeries

/-! ### Concrete Computations in ℤ/n -/

section Concrete

/-
In ℤ/12, the element 4 satisfies 4² - 4 = 12 ≡ 0, so 4 is idempotent.
-/
theorem zmod12_four_idempotent : IsIdempotentElem (4 : ZMod 12) := by
  -- In the ring $\mathbb{Z}/12\mathbb{Z}$, we have $4^2 = 16 \equiv 4 \pmod{12}$, so $4$ is idempotent.
  norm_cast

/-
In ℤ/12, the element 9 satisfies 9² - 9 = 72 ≡ 0, so 9 is idempotent.
-/
theorem zmod12_nine_idempotent : IsIdempotentElem (9 : ZMod 12) := by
  simp +decide only [IsIdempotentElem]

/-
The idempotents 4 and 9 in ℤ/12 are complementary: they sum to 1.
-/
theorem zmod12_complementary : (4 : ZMod 12) + (9 : ZMod 12) = 1 := by
  native_decide +revert

end Concrete

end NewtonIdempotent