import Mathlib

/-!
# Symmetry groups of periodic rhythms (the 1-dimensional theory)

A (monophonic) *rhythm* is a Boolean onset function on the integer time-line,
`f : ℤ → Bool`, where `f n = true` means "there is an onset at time `n`".

Musically, the most basic symmetry of a rhythm is a **time translation**: a shift
`t` that maps the rhythm onto itself.  The set of all such shifts is the
`symGroup` of the rhythm.  This file develops its structure theory:

* `symGroup f` is an additive subgroup of `ℤ` (`symGroup`).
* Membership is exactly periodicity: `p ∈ symGroup f ↔ Function.Periodic f p`.
* Every symmetry group is cyclic — generated by a single shift
  (`exists_generator`).  This is the algebraic reason a rhythm has a
  *fundamental period* that all other periods are multiples of.
* `exists_fundamental` / `fundamental_period`: a periodic rhythm has a smallest
  positive period `d`, and a shift `q` is a period **iff** `d ∣ q`.  This is the
  classical "the fundamental period divides every period" theorem.

These are the genuine mathematical facts underlying the informal slogan that the
symmetry group of a period-`p` rhythm is a subgroup of `ℤ/pℤ`.
-/

namespace WallpaperRhythm

open AddSubgroup Function

/-- A rhythm: a Boolean onset function on the integer time-line. -/
abbrev Rhythm := ℤ → Bool

/-- The translation symmetries of a rhythm form an additive subgroup of `ℤ`.
The carrier is the set of shifts `t` with `f (n + t) = f n` for all `n`. -/
def symGroup (f : Rhythm) : AddSubgroup ℤ where
  carrier := {t | ∀ n, f (n + t) = f n}
  zero_mem' := by intro n; simp
  add_mem' := by
    intro a b ha hb n
    have h : n + (a + b) = (n + b) + a := by ring
    rw [h, ha (n + b), hb n]
  neg_mem' := by
    intro a ha n
    have key := ha (n - a)
    have h2 : (n - a) + a = n := by ring
    rw [h2] at key
    rw [show n + -a = n - a from by ring]
    exact key.symm

@[simp] lemma mem_symGroup {f : Rhythm} {t : ℤ} :
    t ∈ symGroup f ↔ ∀ n, f (n + t) = f n := Iff.rfl

/-- A shift is a symmetry exactly when it is a period of the rhythm. -/
lemma periodic_iff_mem {f : Rhythm} {p : ℤ} :
    Function.Periodic f p ↔ p ∈ symGroup f := Iff.rfl

/-- **Every symmetry group is cyclic**: it is generated by a single shift `d`.
Consequently the period structure of a rhythm is completely governed by one
number, its fundamental period. -/
theorem exists_generator (f : Rhythm) :
    ∃ d : ℤ, symGroup f = zmultiples d := by
  obtain ⟨d, hd⟩ := Int.subgroup_cyclic (symGroup f)
  exact ⟨d, by rw [hd, zmultiples_eq_closure]⟩

/-- **The periods of a rhythm are exactly the multiples of a fixed integer `d`.**
This is the abstract form of the fundamental-period theorem. -/
theorem exists_fundamental (f : Rhythm) :
    ∃ d : ℤ, ∀ q : ℤ, Function.Periodic f q ↔ d ∣ q := by
  obtain ⟨d, hd⟩ := exists_generator f
  refine ⟨d, fun q => ?_⟩
  rw [periodic_iff_mem, hd, Int.mem_zmultiples_iff]

/-- **The fundamental period.**  If a rhythm has any positive period, then it has
a smallest positive period `d`, and a shift `q` is a period *iff* `d ∣ q`; in
particular `d` is `≤` every positive period. -/
theorem fundamental_period {f : Rhythm} {p : ℤ} (hp : 0 < p)
    (hper : Function.Periodic f p) :
    ∃ d : ℤ, 0 < d ∧ (∀ q : ℤ, Function.Periodic f q ↔ d ∣ q) ∧
      (∀ q : ℤ, 0 < q → Function.Periodic f q → d ≤ q) := by
  obtain ⟨d, hd⟩ := exists_fundamental f
  -- `d ≠ 0` because `p` is a nonzero period.
  have hdp : d ∣ p := (hd p).mp hper
  have hd0 : d ≠ 0 := by
    rintro rfl
    simp only [zero_dvd_iff] at hdp
    omega
  refine ⟨|d|, abs_pos.mpr hd0, fun q => ?_, ?_⟩
  · rw [hd q, abs_dvd]
  · intro q hq hqper
    have : |d| ∣ q := by rw [abs_dvd]; exact (hd q).mp hqper
    exact Int.le_of_dvd hq this

/-- A rhythm is **aperiodic** (has trivial symmetry group `{0}`) iff its only
period is `0`. This is the `p1` case: "free rhythm". -/
lemma symGroup_eq_bot_iff {f : Rhythm} :
    symGroup f = ⊥ ↔ ∀ q : ℤ, Function.Periodic f q → q = 0 := by
  rw [eq_bot_iff]
  constructor
  · intro h q hq
    have : q ∈ (⊥ : AddSubgroup ℤ) := h (periodic_iff_mem.mp hq)
    simpa using this
  · intro h x hx
    have := h x hx
    simp [this]

/-! ## Classification of the symmetry types of a period-`p` rhythm

The possible translation-symmetry groups of a rhythm are exactly the subgroups
`zmultiples d` of `ℤ`.  For a rhythm of period `p`, these are precisely the
divisor lattices `zmultiples d` with `d ∣ p`.  Moreover **every** such lattice is
realised by an actual rhythm, so the symmetry types of period-`p` rhythms are in
bijection with the positive divisors of `p` (the honest 1-D analogue of the
wallpaper-group classification: `τ(p)` types, not a fixed `17`). -/

/-- The canonical "metronome on the `d`-grid" rhythm: an onset exactly at the
multiples of `d`. -/
def divRhythm (d : ℤ) : Rhythm := fun n => decide (d ∣ n)

/-- **Realisability.**  The `d`-grid rhythm has symmetry group *exactly*
`zmultiples d`. -/
theorem symGroup_divRhythm (d : ℤ) : symGroup (divRhythm d) = zmultiples d := by
  ext t
  rw [mem_symGroup, Int.mem_zmultiples_iff]
  constructor
  · intro h
    have h0 := h 0
    simpa [divRhythm] using h0
  · intro hdt n
    have hiff : (d ∣ n + t) ↔ (d ∣ n) := by
      constructor
      · intro hh
        have : d ∣ (n + t) - t := Int.dvd_sub hh hdt
        simpa using this
      · intro hh; exact hh.add hdt
    simp [divRhythm, hiff]

/-- Every symmetry group of a period-`p` rhythm is a **divisor lattice**
`zmultiples d` with `0 < d` and `d ∣ p`. -/
theorem symGroup_eq_divisor_lattice {f : Rhythm} {p : ℤ} (hp : 0 < p)
    (hper : Function.Periodic f p) :
    ∃ d : ℤ, 0 < d ∧ d ∣ p ∧ symGroup f = zmultiples d := by
  obtain ⟨d, hd0, hdiff, _⟩ := fundamental_period hp hper
  refine ⟨d, hd0, (hdiff p).mp hper, ?_⟩
  ext t
  rw [mem_symGroup, Int.mem_zmultiples_iff]
  exact (hdiff t)

/-- The `d`-grid rhythm indeed has period `p` whenever `d ∣ p`; combined with
`symGroup_divRhythm` this shows every divisor lattice of `p` is the symmetry
group of some genuine period-`p` rhythm. -/
theorem divRhythm_periodic {d p : ℤ} (h : d ∣ p) : Function.Periodic (divRhythm d) p := by
  rw [periodic_iff_mem, symGroup_divRhythm, Int.mem_zmultiples_iff]
  exact h

end WallpaperRhythm