import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Tactic

/-!
# EML programs and a finite-template obstruction to exponentials

This file models the *intensional* notion of a finite EML program: an abstract
syntax tree generated by real constants, variables, addition, multiplication,
`exp`, and `log`. Substitution is composition, and tuples give product maps.

The connector theorem `no_universal_finite_template` links a programming-
language invariant (abstract-syntax-tree size) with a categorical obstruction:
a fixed finite EML evaluator cannot represent every EML program merely by
sharing leaf parameters. Thus the proposed “currying via EML parameter
sharing” does not construct exponential objects for this natural intensional
category.

This is deliberately not a claim about an extensional quotient identifying
programs that happen to compute equal real functions. Such a quotient needs a
separate semantic non-universality theorem.
-/

namespace EMLCategory

/-- Finite EML expression trees with `n` input variables. -/
inductive Expr (n : ℕ) where
  | const : ℝ → Expr n
  | var : Fin n → Expr n
  | add : Expr n → Expr n → Expr n
  | mul : Expr n → Expr n → Expr n
  | exp : Expr n → Expr n
  | log : Expr n → Expr n

namespace Expr

/-- The real function denoted by an EML expression. Mathlib's totalized
`Real.log` supplies semantics at nonpositive inputs as well. -/
noncomputable def eval {n : ℕ} : Expr n → (Fin n → ℝ) → ℝ
  | const c, _ => c
  | var i, x => x i
  | add a b, x => eval a x + eval b x
  | mul a b, x => eval a x * eval b x
  | exp a, x => Real.exp (eval a x)
  | log a, x => Real.log (eval a x)

/-- Simultaneous substitution, the syntactic form of composition. -/
def subst {m n : ℕ} (σ : Fin m → Expr n) : Expr m → Expr n
  | const c => const c
  | var i => σ i
  | add a b => add (subst σ a) (subst σ b)
  | mul a b => mul (subst σ a) (subst σ b)
  | exp a => exp (subst σ a)
  | log a => log (subst σ a)

/-- Number of nodes in the abstract syntax tree. -/
def size {n : ℕ} : Expr n → ℕ
  | const _ => 1
  | var _ => 1
  | add a b => 1 + size a + size b
  | mul a b => 1 + size a + size b
  | exp a => 1 + size a
  | log a => 1 + size a

/-- Substitution has the expected denotational semantics. -/
theorem eval_subst {m n : ℕ} (σ : Fin m → Expr n) (e : Expr m)
    (x : Fin n → ℝ) :
    eval (subst σ e) x = eval e (fun i => eval (σ i) x) := by
  induction e with
  | const c => rfl
  | var i => rfl
  | add a b ha hb => simp only [subst, eval, ha, hb]
  | mul a b ha hb => simp only [subst, eval, ha, hb]
  | exp a ha => simp only [subst, eval, ha]
  | log a ha => simp only [subst, eval, ha]

/-- Substitution by variables is the identity. -/
theorem subst_var {n : ℕ} (e : Expr n) : subst var e = e := by
  induction e with
  | const c => rfl
  | var i => rfl
  | add a b ha hb => simp only [subst, ha, hb]
  | mul a b ha hb => simp only [subst, ha, hb]
  | exp a ha => simp only [subst, ha]
  | log a ha => simp only [subst, ha]

/-- Associativity of simultaneous substitution. -/
theorem subst_subst {k m n : ℕ} (τ : Fin m → Expr n)
    (σ : Fin k → Expr m) (e : Expr k) :
    subst τ (subst σ e) = subst (fun i => subst τ (σ i)) e := by
  induction e with
  | const c => rfl
  | var i => rfl
  | add a b ha hb => simp [subst, ha, hb]
  | mul a b ha hb => simp [subst, ha, hb]
  | exp a ha => simp [subst, ha]
  | log a ha => simp [subst, ha]

/-- A tower of `k` exponential nodes above the constant zero. -/
def expTower {n : ℕ} : ℕ → Expr n
  | 0 => const 0
  | k + 1 => exp (expTower k)

/-- The exponential tower has one leaf in addition to its `k` unary nodes. -/
theorem size_expTower {n : ℕ} (k : ℕ) : size (expTower (n := n) k) = k + 1 := by
  induction k with
  | zero => rfl
  | succ k hk => simp only [expTower, size, hk]; omega

/-- A leaf substitution replaces variables only by expressions of size one. -/
def IsLeafSubst {m n : ℕ} (σ : Fin m → Expr n) : Prop :=
  ∀ i, size (σ i) = 1

/-- AST size is invariant under parameter sharing by leaves. -/
theorem size_subst_of_leaf {m n : ℕ} (σ : Fin m → Expr n)
    (hσ : IsLeafSubst σ) (e : Expr m) :
    size (subst σ e) = size e := by
  induction e with
  | const c => rfl
  | var i => exact hσ i
  | add a b ha hb => simp only [subst, size, ha, hb]
  | mul a b ha hb => simp only [subst, size, ha, hb]
  | exp a ha => simp only [subst, size, ha]
  | log a ha => simp only [subst, size, ha]

end Expr

/-- An `m`-output finite EML program on `ℝⁿ`. -/
abbrev Program (n m : ℕ) := Fin m → Expr n

namespace Program

/-- Identity EML program. -/
def id (n : ℕ) : Program n n := Expr.var

/-- Composition of finite EML programs. -/
def comp {n m k : ℕ} (g : Program m k) (f : Program n m) : Program n k :=
  fun j => Expr.subst f (g j)

/-- Product pairing of EML programs. -/
def pair {n m k : ℕ} (f : Program n m) (g : Program n k) :
    Program n (m + k) :=
  Fin.addCases f g

/-- Composition preserves the denoted functions. -/
theorem eval_comp {n m k : ℕ} (g : Program m k) (f : Program n m)
    (x : Fin n → ℝ) (j : Fin k) :
    Expr.eval ((comp g f) j) x =
      Expr.eval (g j) (fun i => Expr.eval (f i) x) := by
  exact Expr.eval_subst f (g j) x

/-- Left identity law for syntactic EML composition. -/
theorem id_comp {n m : ℕ} (f : Program n m) : comp (id m) f = f := by
  rfl

/-- Right identity law for syntactic EML composition. -/
theorem comp_id {n m : ℕ} (f : Program n m) : comp f (id n) = f := by
  funext j
  simp [comp, id, Expr.subst_var]

/-- Associativity law for syntactic EML composition. -/
theorem comp_assoc {a b c d : ℕ} (h : Program c d)
    (g : Program b c) (f : Program a b) :
    comp (comp h g) f = comp h (comp g f) := by
  funext j
  exact Expr.subst_subst f g (h j)

/-- Pairing is closed under precomposition, the key finite-product equation. -/
theorem pair_comp {a b c d : ℕ} (f : Program b c) (g : Program b d)
    (h : Program a b) :
    comp (pair f g) h = pair (comp f h) (comp g h) := by
  funext j
  simp [comp, pair, Fin.addCases]
  split_ifs <;> rfl

end Program

/-- A fixed expression template is universal by parameter sharing if every
expression can be obtained by replacing its variable leaves with leaves.
This isolates the exact mechanism proposed for EML currying. -/
def UniversalByParameterSharing {m n : ℕ} (template : Expr m) : Prop :=
  ∀ target : Expr n, ∃ σ : Fin m → Expr n,
    Expr.IsLeafSubst σ ∧ Expr.subst σ template = target

/-- **Connector theorem (syntax complexity ↔ categorical exponentials).**
No finite EML evaluator template is universal under parameter sharing. The
proof uses the invariant `Expr.size`: specializing leaves preserves template
size, while adding one `exp` node produces a legitimate EML target of strictly
larger size.

Consequently, currying cannot be justified merely by claiming that a single
finite EML expression shares finitely many parameters; any genuine exponential
construction must change the representation of morphisms or establish a much
stronger extensional universal-evaluator theorem. -/
theorem no_universal_finite_template {m n : ℕ} (template : Expr m) :
    ¬ UniversalByParameterSharing (n := n) template := by
  intro h
  obtain ⟨σ, hσ, heq⟩ := h (Expr.expTower (n := n) (Expr.size template))
  have hs := Expr.size_subst_of_leaf σ hσ template
  have ht := Expr.size_expTower (n := n) (Expr.size template)
  have heqsize := congrArg Expr.size heq
  omega

end EMLCategory