import Mathlib

/-!
# Berggren Tree, Lifted to Euclid Parameters

The classical Berggren ternary tree organises every *primitive* Pythagorean triple
into a tree rooted at `(3, 4, 5)`, with three forward matrices `A, B, C` producing the
children of each node (see `Pythagorean/BerggrenCompleteness.lean`, which works entirely
at the level of triples `(a, b, c)`).

Independently, `Pythagorean/GaussianPythagorean.lean` records the Euclid parametrisation
`(m² - n², 2mn, m² + n²)`.

This file **bridges the two viewpoints**: it shows the Berggren tree is, underneath,
nothing more than a tree on the *Euclid generator pairs* `(m, n)` (coprime, opposite
parity, `m > n > 0`), generated by three strikingly simple **linear** maps

* `A : (m, n) ↦ (2m - n, m)`
* `B : (m, n) ↦ (2m + n, m)`
* `C : (m, n) ↦ (m + 2n, n)`

rooted at `(2, 1)` (which parametrises `(3, 4, 5)`).

The main results are:

* `berggren_euclid_lift` — the three Berggren forward transforms commute with the Euclid
  parametrisation: applying a Berggren matrix to the Euclid triple of `(m, n)` gives the
  Euclid triple of the linearly-transformed parameters.  (The geometric heart of the file.)
* `forward_preserves_good` — each parameter map sends a valid Euclid generator pair to a
  valid one (coprimality, opposite parity and the ordering `m > n > 0` are all preserved).
* `forward_hyp_increases` — each map strictly increases the hypotenuse `m² + n²`.
* `parent_exists` — every non-root valid pair has a strictly-smaller valid parent under a
  unique branch (parameter-level descent step).
* `completeness` — every valid Euclid generator pair is reachable from the root `(2, 1)`
  by forward parameter maps; equivalently, the lifted Berggren tree is exhaustive.

-- !-- Lab Notes -- !--
HYPOTHESIS.  The three Berggren integer matrices, conjugated through the (non-linear)
Euclid parametrisation `q : (m,n) ↦ (m²-n², 2mn, m²+n²)`, should become *linear* maps on
`(m,n)`.  Reason: the parametrisation is essentially `z ↦ z²` on `ℤ[i]` with `z = m + ni`,
and the Berggren matrices are the images of the three generators of a finite-index
subgroup acting on the modular side; squaring intertwines these actions linearly.

EXPERIMENT.  Compute children of the root `(3,4,5)` [params `(2,1)`]:
  A: (3,4,5) ↦ (5,12,13)  with params (3,2)   vs. (2·2-1, 2) = (3,2)   ✓
  B: (3,4,5) ↦ (21,20,29) with params (5,2)   vs. (2·2+1, 2) = (5,2)   ✓
  C: (3,4,5) ↦ (15,8,17)  with params (4,1)   vs. (2+2·1, 1) = (4,1)   ✓
So the candidate linear maps above are exactly right; promoted to `berggren_euclid_lift`.

INSIGHT.  At the parameter level the parent map is a clean three-way split on the size of
`M` relative to `2N` and `3N`:  `N < M < 2N` ⇒ branch A, `2N < M < 3N` ⇒ branch B,
`M > 3N` ⇒ branch C.  The boundary `M = 2N` happens only at the root, and `M = 3N` never
happens for a valid pair (it would force same parity).  This makes the descent totally
explicit and uniqueness transparent — a noticeable simplification over the triple-level
σ-invariant bookkeeping in `BerggrenCompleteness.lean`.

FAILURE ANALYSIS.  A first attempt phrased opposite parity as `Odd (m + n)`; coprimality
preservation then fought with `Odd`/`Even` rewriting.  Switching to `IsCoprime` (ℤ) for
coprimality and the bare `m % 2 ≠ n % 2` (so `omega` discharges parity) removed the
friction entirely.
-/

namespace BerggrenEuclidLift

open scoped Classical

/-! ## Section 1: Definitions -/

/-- The three branches of the ternary Berggren tree. -/
inductive Branch : Type where
  | A : Branch
  | B : Branch
  | C : Branch
  deriving DecidableEq, Repr

/-- The Berggren forward transforms on a triple `(a, b, c)`, indexed by branch.
These are the same three integer matrices used in `BerggrenCompleteness.lean`
(repeated here so this file is self-contained, since that module is not importable
under the current build layout). -/
def berggrenFwd : Branch → ℤ → ℤ → ℤ → ℤ × ℤ × ℤ
  | .A, a, b, c => (a - 2*b + 2*c, 2*a - b + 2*c, 2*a - 2*b + 3*c)
  | .B, a, b, c => (a + 2*b + 2*c, 2*a + b + 2*c, 2*a + 2*b + 3*c)
  | .C, a, b, c => (-a + 2*b + 2*c, -2*a + b + 2*c, -2*a + 2*b + 3*c)

/-- The lifted maps on Euclid generator pairs `(m, n)`. -/
def paramMap : Branch → ℤ → ℤ → ℤ × ℤ
  | .A, m, n => (2*m - n, m)
  | .B, m, n => (2*m + n, m)
  | .C, m, n => (m + 2*n, n)

/-- The Euclid parametrisation `(m, n) ↦ (m² - n², 2mn, m² + n²)`. -/
def euclidTriple (m n : ℤ) : ℤ × ℤ × ℤ := (m^2 - n^2, 2*m*n, m^2 + n^2)

/-- A pair `(m, n)` is a *valid Euclid generator pair* when `m > n > 0`, the entries are
coprime, and they have opposite parity.  These are exactly the pairs producing primitive
Pythagorean triples (with positive legs). -/
def GoodParams (m n : ℤ) : Prop :=
  0 < n ∧ n < m ∧ IsCoprime m n ∧ m % 2 ≠ n % 2

/-! ## Section 2: The parametrisation and the lift -/

/-- The Euclid triple is Pythagorean. -/
theorem euclid_pythagorean (m n : ℤ) :
    (euclidTriple m n).1 ^ 2 + (euclidTriple m n).2.1 ^ 2 = (euclidTriple m n).2.2 ^ 2 := by
  simp only [euclidTriple]; ring

/-- The root parameters `(2, 1)` parametrise the root triple `(3, 4, 5)`. -/
theorem euclid_root : euclidTriple 2 1 = (3, 4, 5) := by
  decide

/-- **The lift.** Each Berggren forward transform, applied to the Euclid triple of `(m, n)`,
yields the Euclid triple of the linearly-transformed parameters `paramMap br m n`. -/
theorem berggren_euclid_lift (br : Branch) (m n : ℤ) :
    berggrenFwd br (m^2 - n^2) (2*m*n) (m^2 + n^2)
      = euclidTriple (paramMap br m n).1 (paramMap br m n).2 := by
  cases br <;> simp only [berggrenFwd, euclidTriple, paramMap, Prod.mk.injEq] <;>
    refine ⟨by ring, by ring, by ring⟩

/-! ## Section 3: Forward maps preserve valid pairs and grow the hypotenuse -/

/-- Each parameter map preserves validity of the generator pair. -/
theorem forward_preserves_good (br : Branch) (m n : ℤ) (h : GoodParams m n) :
    GoodParams (paramMap br m n).1 (paramMap br m n).2 := by
  cases br <;> simp_all +decide [ GoodParams, paramMap ];
  · refine' ⟨ by linarith, by linarith, _, _ ⟩;
    · convert h.2.2.1.symm.neg_left.add_mul_left_left 2 using 1 ; ring;
    · tauto;
  · exact ⟨ by linarith, by linarith, by convert h.2.2.1.symm.add_mul_left_left 2 using 1; ring, by tauto ⟩;
  · exact ⟨ by linarith, by convert h.2.2.1.add_mul_left_left 2 using 1; ring ⟩

/-- Each parameter map strictly increases the hypotenuse `m² + n²`. -/
theorem forward_hyp_increases (br : Branch) (m n : ℤ) (h : GoodParams m n) :
    (euclidTriple m n).2.2 < (euclidTriple (paramMap br m n).1 (paramMap br m n).2).2.2 := by
  rcases br with ( _ | _ | _ ) <;> simp_all +decide [ euclidTriple, paramMap ]; all_goals nlinarith [ h.1, h.2.1 ]

/-! ## Section 4: Descent and completeness -/

/-- The only valid generator pair with `m = 2` is the root `(2, 1)`. -/
theorem good_m_eq_two (n : ℤ) (h : GoodParams 2 n) : n = 1 := by
  cases h ; omega

/-- **Parameter-level descent.** Every non-root valid pair has a strictly smaller valid
parent under exactly one branch. -/
theorem parent_exists (m n : ℤ) (h : GoodParams m n) (hne : (m, n) ≠ (2, 1)) :
    ∃ (br : Branch) (m' n' : ℤ),
      GoodParams m' n' ∧ paramMap br m' n' = (m, n) ∧ m' < m := by
  rcases h with ⟨ hn, hm, hcop, hpar ⟩;
  by_cases hmn : m = 2 * n ∨ m = 3 * n;
  · rcases hmn with ( rfl | rfl ) <;> simp_all +decide [ Int.isCoprime_iff_nat_coprime ];
    · simp_all +decide [ Int.natAbs_mul, Nat.coprime_mul_iff_left ];
      grind;
    · grind;
  · by_cases hmn : m < 2 * n;
    · refine' ⟨ Branch.A, n, 2 * n - m, _, _, _ ⟩ <;> simp_all +decide [ GoodParams ];
      · exact ⟨ by linarith, by obtain ⟨ a, b, H ⟩ := hcop; exact ⟨ b + 2 * a, -a, by linarith ⟩, by omega ⟩;
      · grind +locals;
    · by_cases hmn : m < 3 * n;
      · refine' ⟨ .B, n, m - 2 * n, _, _, _ ⟩ <;> norm_num [ paramMap ];
        · constructor <;> try omega;
          exact ⟨ by linarith, by convert hcop.symm.add_mul_right_right ( -2 ) using 1; ring, by omega ⟩;
        · grind +qlia;
      · refine' ⟨ .C, m - 2 * n, n, _, _, _ ⟩ <;> simp_all +decide [ GoodParams ];
        · exact ⟨ by omega, by convert hcop.add_mul_left_left ( -2 ) using 1; ring ⟩;
        · exact Prod.mk_inj.mpr ⟨ by ring, rfl ⟩

/-- Reachability from the root `(2, 1)` by forward parameter maps. -/
inductive Reachable : ℤ → ℤ → Prop where
  | root : Reachable 2 1
  | step (br : Branch) (m n : ℤ) :
      Reachable m n → Reachable (paramMap br m n).1 (paramMap br m n).2

/-- **Completeness of the lifted Berggren tree.** Every valid Euclid generator pair is
reachable from the root `(2, 1)` by forward parameter maps. -/
theorem completeness (m n : ℤ) (h : GoodParams m n) : Reachable m n := by
  induction' k : m.toNat using Nat.strong_induction_on with k ih generalizing m n;
  by_cases hne : ( m, n ) = ( 2, 1 );
  · cases hne ; exact Reachable.root;
  · obtain ⟨ br, m', n', hgood', heq, hlt ⟩ := parent_exists m n h hne;
    convert Reachable.step br m' n' ( ih _ _ _ _ hgood' rfl ) using 1;
    · exact heq.symm ▸ rfl;
    · grind;
    · linarith [ Int.toNat_of_nonneg ( by linarith [ hgood'.1, hgood'.2.1 ] : 0 ≤ m' ), Int.toNat_of_nonneg ( by linarith [ h.1, h.2.1 ] : 0 ≤ m ) ]

end BerggrenEuclidLift