/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license.

# Quantum Channel Mixing via Cayley Moment Bounds

This file establishes the bridge between classical random walks on finite groups
and quantum channel mixing theory. The central discovery: the Hilbert–Schmidt
purity of the quantum channel induced by a symmetric group walk equals the
classical return probability — turning every spectral moment bound into a
certified quantum mixing theorem.

## Cross-Domain Significance

The identity `walkPurity(k) = momentKernel(2k)` means every theorem about
return probabilities of Cayley walks becomes, for free, a theorem about
decoherence rates of quantum channels generated by permutation unitaries.
This connects:
- **Expander / Cayley graph theory** — spectral moments and return probabilities
- **Quantum channel mixing** — purity decay and Hilbert-Schmidt contraction
- **Random circuit design** — certified bounds on unitary mixing
- **Representation-theoretic spectral analysis** — character sum bounds

## Catalog References

Builds on results from `Pythagorean.CayleyExpander.MomentMethod`:
- `spectral_moment_eq_return_prob` — the spectral moment / return probability bridge
- `momentKernel_le_one` — moment kernel is a probability
- `free_group_moment_two_lower` — free group baseline return probability
-/
import Mathlib

open Finset BigOperators Matrix

namespace QuantumMixing

/-! ## Alphabet and Word Evaluation (from catalog)

We reproduce the essential definitions from the Cayley expander catalog
to make this file self-contained. -/

/-- The four-letter alphabet for a symmetric 2-generator Cayley graph. -/
inductive QGenLetter
  | sigma | sigmaInv | tau | tauInv
  deriving DecidableEq, Repr, Fintype

namespace QGenLetter

/-- Formal inverse on the alphabet. -/
def inv : QGenLetter → QGenLetter
  | sigma    => sigmaInv
  | sigmaInv => sigma
  | tau      => tauInv
  | tauInv   => tau

@[simp] theorem inv_inv (a : QGenLetter) : a.inv.inv = a := by cases a <;> rfl
@[simp] theorem card_qGenLetter : Fintype.card QGenLetter = 4 := by decide

end QGenLetter

/-- Two-generator Cayley data. -/
structure QTwoGenData (G : Type*) [Group G] where
  sigma : G
  tau   : G

namespace QTwoGenData
variable {G : Type*} [Group G]

def evalLetter (d : QTwoGenData G) : QGenLetter → G
  | .sigma    => d.sigma
  | .sigmaInv => d.sigma⁻¹
  | .tau      => d.tau
  | .tauInv   => d.tau⁻¹

@[simp]
theorem evalLetter_inv (d : QTwoGenData G) (a : QGenLetter) :
    d.evalLetter a.inv = (d.evalLetter a)⁻¹ := by
  cases a <;> simp [evalLetter, QGenLetter.inv]

end QTwoGenData

/-- Evaluate a word in a group. -/
def qEvalWord {G : Type*} [Group G] (σ τ : G) : List QGenLetter → G
  | []     => 1
  | a :: w => (QTwoGenData.mk σ τ).evalLetter a * qEvalWord σ τ w

@[simp] theorem qEvalWord_nil {G : Type*} [Group G] (σ τ : G) :
    qEvalWord σ τ [] = 1 := rfl

theorem qEvalWord_append {G : Type*} [Group G] (σ τ : G) (w₁ w₂ : List QGenLetter) :
    qEvalWord σ τ (w₁ ++ w₂) = qEvalWord σ τ w₁ * qEvalWord σ τ w₂ := by
  induction w₁ with
  | nil => simp [qEvalWord]
  | cons a w₁ ih => simp [qEvalWord, ih, mul_assoc]

/-- Reverse-and-invert a word. -/
def qReverseInvert : List QGenLetter → List QGenLetter :=
  fun w => (w.reverse.map QGenLetter.inv)

theorem qEvalWord_reverseInvert {G : Type*} [Group G] (σ τ : G)
    (w : List QGenLetter) :
    qEvalWord σ τ (qReverseInvert w) = (qEvalWord σ τ w)⁻¹ := by
  induction w with
  | nil => simp [qReverseInvert, qEvalWord]
  | cons a w ih =>
    simp only [qReverseInvert, List.reverse_cons, List.map_append, List.map_cons, List.map_nil]
    rw [qEvalWord_append]
    simp only [qEvalWord, _root_.mul_inv_rev, List.map_nil]
    congr 1
    simp

/-! ## Core Definitions -/

variable {G : Type*} [Fintype G] [DecidableEq G] [Group G]

section Definitions

/-- Conjugation of a matrix by the permutation for left-multiplication by g.
    Implements ρ ↦ U_g ρ U_g† where U_g is the left-regular permutation unitary. -/
noncomputable def conjugateByPerm (G : Type*) [Fintype G] [DecidableEq G] [Group G]
    (g : G) : Matrix G G ℂ →ₗ[ℂ] Matrix G G ℂ where
  toFun ρ := Matrix.of fun i j => ρ (g⁻¹ * i) (g⁻¹ * j)
  map_add' u v := by ext i j; simp [Matrix.add_apply]
  map_smul' c ρ := by ext i j; simp [Matrix.smul_apply, smul_eq_mul]

/-- The quantum channel induced by a finite group walk:
    Φ_μ(ρ) = ∑_{g ∈ G} μ(g) · U_g ρ U_g†
    This is a bistochastic quantum channel whenever μ is a probability distribution. -/
noncomputable def groupWalkChannel (G : Type*) [Fintype G] [DecidableEq G] [Group G]
    (μ : G → ℝ) : Matrix G G ℂ →ₗ[ℂ] Matrix G G ℂ :=
  ∑ g : G, ((μ g : ℝ) : ℂ) • conjugateByPerm G g

/-- Purity of a real-valued function (L² mass / collision probability). -/
noncomputable def purityFn (f : G → ℝ) : ℝ := ∑ x : G, f x ^ 2

/-- Point mass distribution δ_{g₀}. -/
noncomputable def pointMassFn (g₀ : G) : G → ℝ :=
  fun g => if g = g₀ then 1 else 0

/-- Uniform distribution on G. -/
noncomputable def uniformDist (G : Type*) [Fintype G] : G → ℝ :=
  fun _ => (1 : ℝ) / (Fintype.card G : ℝ)

/-- Number of length-k words evaluating to x. -/
noncomputable def wordCount (σ τ : G) (k : ℕ) (x : G) : ℕ :=
  (Finset.univ.filter fun w : Fin k → QGenLetter =>
    qEvalWord σ τ (List.ofFn w) = x).card

/-- Closed word count: words evaluating to the identity. -/
noncomputable def qClosedWordCount (σ τ : G) (k : ℕ) : ℕ :=
  (Finset.univ.filter fun w : Fin k → QGenLetter =>
    qEvalWord σ τ (List.ofFn w) = 1).card

/-- The moment kernel: return probability after k steps. -/
noncomputable def qMomentKernel (σ τ : G) (k : ℕ) : ℚ :=
  (qClosedWordCount σ τ k : ℚ) / (4 : ℚ) ^ k

/-- Walk distribution after k steps from identity. -/
noncomputable def walkDistrib (σ τ : G) (k : ℕ) (x : G) : ℚ :=
  (wordCount σ τ k x : ℚ) / (4 : ℚ) ^ k

/-- Purity (L² mass) of the k-step walk distribution. -/
noncomputable def walkPurity (σ τ : G) (k : ℕ) : ℚ :=
  ∑ x : G, (walkDistrib σ τ k x) ^ 2

/-- Centered purity: L² distance from the uniform distribution. -/
noncomputable def centeredPurityFn (f : G → ℝ) : ℝ :=
  ∑ x : G, (f x - (1 : ℝ) / (Fintype.card G : ℝ)) ^ 2

/-- Walk convolution operator: (T_μ f)(x) = ∑_g μ(g) f(g⁻¹ x). -/
noncomputable def walkConvOp (μ : G → ℝ) (f : G → ℝ) : G → ℝ :=
  fun x => ∑ g : G, μ g * f (g⁻¹ * x)

/-- Spectral gap: the walk operator contracts mean-zero functions. -/
def spectralGapBound (μ : G → ℝ) (gap : ℝ) : Prop :=
  ∀ f : G → ℝ, (∑ x : G, f x = 0) →
    purityFn (walkConvOp μ f) ≤ (1 - gap) ^ 2 * purityFn f

/-- Diagonal density matrix from a real distribution. -/
noncomputable def diagState (p : G → ℝ) : Matrix G G ℂ :=
  Matrix.diagonal (fun g => (p g : ℂ))

/-- Matrix purity: Re(tr(ρ²)). -/
noncomputable def matrixPurity (ρ : Matrix G G ℂ) : ℝ :=
  Complex.re (Matrix.trace (ρ * ρ))

end Definitions

/-! ## Basic Properties of Purity -/

/-- Purity is nonnegative. -/
theorem purity_nonneg (f : G → ℝ) : 0 ≤ purityFn f :=
  Finset.sum_nonneg fun x _ => sq_nonneg _

/-
Purity of a point mass is 1.
-/
theorem purity_pointMass_eq_one (g₀ : G) :
    purityFn (pointMassFn g₀ : G → ℝ) = 1 := by
  unfold purityFn pointMassFn;
  aesop

/-
Purity of the uniform distribution is 1/|G|.
-/
theorem purity_uniform :
    purityFn (uniformDist G) = 1 / (Fintype.card G : ℝ) := by
  unfold purityFn uniformDist;
  by_cases h : Fintype.card G = 0 <;> simp_all +decide [ sq, mul_assoc ]

/-! ## Walk Distribution Properties -/

/-
Word count at identity = closed word count.
-/
theorem wordCount_identity (σ τ : G) (k : ℕ) :
    wordCount σ τ k 1 = qClosedWordCount σ τ k := by
  convert rfl

/-
Sum of word counts = 4^k.
-/
theorem sum_wordCount_eq_total (σ τ : G) (k : ℕ) :
    ∑ x : G, (wordCount σ τ k x : ℚ) = (4 : ℚ) ^ k := by
  unfold wordCount;
  rw_mod_cast [ ← Finset.card_biUnion ];
  · convert Finset.card_univ ( α := Fin k → QGenLetter ) using 2 ; aesop;
    simp +decide [ Fintype.card_pi ];
  · exact fun x _ y _ hxy => Finset.disjoint_left.mpr fun w hw₁ hw₂ => hxy <| by aesop;

/-
Walk distribution sums to 1.
-/
theorem walkDistrib_sum (σ τ : G) (k : ℕ) :
    ∑ x : G, walkDistrib σ τ k x = 1 := by
  convert congr_arg ( · / ( 4 : ℚ ) ^ k ) ( sum_wordCount_eq_total σ τ k ) using 1;
  · simp +decide only [walkDistrib, sum_div];
  · rw [ div_self ( by positivity ) ]

omit [Fintype G] in
/-- Walk distribution is nonneg. -/
theorem walkDistrib_nonneg (σ τ : G) (k : ℕ) (x : G) :
    0 ≤ walkDistrib σ τ k x :=
  div_nonneg (Nat.cast_nonneg _) (pow_nonneg (by norm_num) _)

/-! ## The Purity–Return Probability Bridge -/

/-
**Collision Count Identity**: ∑_x (wordCount x)² = closedWordCount(2k).
    The sum of squared word counts equals closed walks at double length,
    via the bijection (w₁, w₂) ↦ w₁ ++ reverseInvert(w₂).
-/
theorem collision_count_eq_closedWordCount (σ τ : G) (k : ℕ) :
    ∑ x : G, (wordCount σ τ k x : ℚ) ^ 2 =
      (qClosedWordCount σ τ (2 * k) : ℚ) := by
  -- The sum of squared word counts is equal to the number of pairs of words of length k whose concatenation evaluates to the identity.
  have h_sum_pairs : ∑ x : G, (wordCount σ τ k x : ℚ) ^ 2 = ∑ w₁ : Fin k → QGenLetter, ∑ w₂ : Fin k → QGenLetter, if qEvalWord σ τ (List.ofFn w₁ ++ List.map QGenLetter.inv (List.reverse (List.ofFn w₂))) = 1 then 1 else 0 := by
    have h_sum_pairs : ∑ x : G, (wordCount σ τ k x : ℚ) ^ 2 = ∑ w₁ : Fin k → QGenLetter, ∑ w₂ : Fin k → QGenLetter, if qEvalWord σ τ (List.ofFn w₁) = qEvalWord σ τ (List.ofFn w₂) then 1 else 0 := by
      simp +decide only [wordCount, card_eq_sum_ones, sum_filter, pow_two];
      push_cast [ Finset.sum_mul _ _ _ ];
      rw [ Finset.sum_comm ];
      simp +decide [ Finset.sum_ite ];
      simp +decide only [eq_comm];
    convert h_sum_pairs using 3;
    simp +decide [ qEvalWord_append, qEvalWord_reverseInvert ];
    simp +decide [ ← mul_inv_eq_one, qEvalWord_reverseInvert ];
    rw [ show qEvalWord σ τ ( List.ofFn ( QGenLetter.inv ∘ _ ) ).reverse = ( qEvalWord σ τ ( List.ofFn _ ) ) ⁻¹ from ?_ ];
    convert qEvalWord_reverseInvert σ τ _ using 2;
    unfold qReverseInvert; simp +decide [ List.ofFn_eq_map ] ;
  -- By definition of $qClosedWordCount$, we know that
  have h_closed_word_count : qClosedWordCount σ τ (2 * k) = ∑ w : Fin (2 * k) → QGenLetter, if qEvalWord σ τ (List.ofFn w) = 1 then 1 else 0 := by
    simp +decide [ qClosedWordCount ];
  -- By definition of $qEvalWord$, we can split the sum into two parts: one over the first $k$ letters and one over the last $k$ letters.
  have h_split_sum : ∑ w : Fin (2 * k) → QGenLetter, (if qEvalWord σ τ (List.ofFn w) = 1 then 1 else 0) = ∑ w₁ : Fin k → QGenLetter, ∑ w₂ : Fin k → QGenLetter, (if qEvalWord σ τ (List.ofFn w₁ ++ List.ofFn w₂) = 1 then 1 else 0) := by
    rw [ ← Finset.sum_product' ];
    refine' Finset.sum_bij ( fun w _ => ( fun i => w ⟨ i, by linarith [ Fin.is_lt i ] ⟩, fun i => w ⟨ i + k, by linarith [ Fin.is_lt i ] ⟩ ) ) _ _ _ _ <;> simp +decide;
    · intro a₁ a₂ h₁ h₂; ext i; by_cases hi : i.val < k <;> simp_all +decide [ funext_iff, Fin.ext_iff ] ;
      · convert h₁ ⟨ i, hi ⟩;
      · convert h₂ ⟨ i - k, by rw [ tsub_lt_iff_left ] <;> linarith [ Fin.is_lt i ] ⟩ using 1 <;> congr <;> simp +decide [ Nat.sub_add_cancel hi ];
    · intro a b; use fun i => if h : i.val < k then a ⟨ i.val, h ⟩ else b ⟨ i.val - k, by rw [ tsub_lt_iff_left ] <;> linarith [ Fin.is_lt i ] ⟩ ; aesop;
    · intro a; congr! 2; simp +decide [ two_mul, List.ofFn_add ] ;
      congr! 3;
  rw [ h_sum_pairs, h_closed_word_count, h_split_sum ];
  push_cast [ Finset.sum_filter ];
  refine' Finset.sum_congr rfl fun w₁ _ => _;
  refine' Finset.sum_bij ( fun w₂ _ => fun i => QGenLetter.inv ( w₂ ( Fin.rev i ) ) ) _ _ _ _ <;> simp +decide;
  · simp +decide [ funext_iff ];
    exact fun a₁ a₂ h x => by simpa using congr_arg QGenLetter.inv ( h ( Fin.rev x ) ) ;
  · exact fun b => ⟨ fun i => QGenLetter.inv ( b ( Fin.rev i ) ), by ext i; simp +decide ⟩;
  · intro w₂; congr! 2;
    congr! 2;
    refine' List.ext_get _ _ <;> simp +decide [ List.get ];
    grind

/-
**Main Bridge Theorem (Theorem 1)**: walkPurity(k) = momentKernel(2k).
    Identifies quantum channel purity with classical return probability.
-/
theorem walkPurity_eq_momentKernel (σ τ : G) (k : ℕ) :
    walkPurity σ τ k = qMomentKernel σ τ (2 * k) := by
  convert congr_arg ( fun x : ℚ => x / ( 4 ^ k ) ^ 2 ) ( collision_count_eq_closedWordCount σ τ k ) using 1;
  · unfold walkPurity walkDistrib; norm_num [ Finset.sum_div _ _ _ ] ; ring;
    ac_rfl;
  · unfold qMomentKernel; ring;

/-! ## Consequences -/

/-
Moment kernel is at most 1.
-/
theorem qMomentKernel_le_one (σ τ : G) (k : ℕ) :
    qMomentKernel σ τ k ≤ 1 := by
  refine' div_le_one_of_le₀ _ ( by positivity );
  convert Nat.cast_le.mpr ( Finset.card_filter_le _ _ ) using 1 ; norm_num [ Fintype.card_pi ]; all_goals infer_instance

/-
Walk purity ≤ 1.
-/
theorem walkPurity_le_one (σ τ : G) (k : ℕ) :
    walkPurity σ τ k ≤ 1 := by
  convert qMomentKernel_le_one σ τ ( 2 * k ) using 1;
  exact?

/-
Free group moment lower bound: at length 2, at least 1/4.
-/
theorem qMomentKernel_two_ge (σ τ : G) :
    (1 : ℚ) / 4 ≤ qMomentKernel σ τ 2 := by
  -- By definition of $qMomentKernel$, we know that
  have h_momentKernel_def : qMomentKernel σ τ 2 = (qClosedWordCount σ τ 2 : ℚ) / (4 : ℚ) ^ 2 := by
    rfl
  rw [h_momentKernel_def] at *; norm_num at *; (
  -- Consider the following 4 words of length 2 that evaluate to 1:
  have h_words : Finset.card (Finset.filter (fun w : Fin 2 → QGenLetter => qEvalWord σ τ (List.ofFn w) = 1) Finset.univ) ≥ Finset.card ({![.sigma, .sigmaInv], ![.sigmaInv, .sigma], ![.tau, .tauInv], ![.tauInv, .tau]} : Finset (Fin 2 → QGenLetter)) := by
    refine Finset.card_le_card ?_ ; simp +decide [ Finset.subset_iff ] ; (
    simp +decide [ qEvalWord ] ;
    simp +decide [ QTwoGenData.evalLetter ]); -- We will prove this lower bound later.;
  rw [ div_le_div_iff₀ ] <;> norm_cast ; simp_all +decide [ qClosedWordCount ] ;
  linarith [ show Finset.card ( Finset.filter ( fun w : Fin 2 → QGenLetter => qEvalWord σ τ [ w 0, w 1 ] = 1 ) Finset.univ ) ≤ 16 by exact le_trans ( Finset.card_filter_le _ _ ) ( by decide ) ] ;);

/-
We will prove this lower bound later.

Walk purity after one step ≥ 1/4.
-/
theorem walkPurity_one_step_ge (σ τ : G) :
    (1 : ℚ) / 4 ≤ walkPurity σ τ 1 := by
  have h_walkPurity_one : walkPurity σ τ 1 = qMomentKernel σ τ 2 := by
    convert walkPurity_eq_momentKernel σ τ 1 using 1;
  exact h_walkPurity_one.symm ▸ qMomentKernel_two_ge σ τ

/-! ## Quantum-Classical Bridge -/

/-
**Cross-Domain: Purity of diagonal state = L² mass**.
    tr(diag(p)²) = ∑ p(g)². Bridges quantum purity with collision probability.
-/
theorem purity_diagState_eq_l2mass (p : G → ℝ) :
    matrixPurity (diagState p) = purityFn p := by
  unfold matrixPurity purityFn diagState;
  simp +decide [ Matrix.trace, sq ]

/-! ## Spectral Gap and Exponential Decay -/

/-
Walk convolution preserves total mass.
-/
theorem walkConvOp_preserves_sum (μ : G → ℝ) (f : G → ℝ)
    (hprob : ∑ g : G, μ g = 1) :
    ∑ x : G, walkConvOp μ f x = ∑ x : G, f x := by
  -- We can interchange the order of summation because the sum is over a finite set.
  have h_swap : ∑ x, ∑ g : G, μ g * f (g⁻¹ * x) = ∑ g : G, ∑ x : G, μ g * f (g⁻¹ * x) := by
    exact Finset.sum_comm;
  simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul ];
  exact h_swap.trans ( by rw [ Finset.sum_congr rfl fun g hg => by rw [ show ∑ i, f ( g⁻¹ * i ) = ∑ i, f i from Equiv.sum_comp ( Equiv.mulLeft g⁻¹ ) f ] ] ; simp +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, hprob ] )

/-
The walk convolution operator preserves constant functions.
-/
theorem walkConvOp_const (μ : G → ℝ) (c : ℝ)
    (hprob : ∑ g : G, μ g = 1) :
    walkConvOp μ (fun _ => c) = fun _ => c := by
  ext x; simp +decide [ walkConvOp ] ;
  rw [ ← Finset.sum_mul, hprob, one_mul ]

/-
Walk convolution is "linear" in the function argument: it commutes with subtraction of constants.
-/
theorem walkConvOp_sub_const (μ : G → ℝ) (f : G → ℝ) (c : ℝ)
    (hprob : ∑ g : G, μ g = 1) :
    walkConvOp μ (fun x => f x - c) = fun x => walkConvOp μ f x - c := by
  unfold walkConvOp; ext x; simp +decide [ mul_sub, ← Finset.sum_mul, hprob ] ;

/-
Iterating the walk preserves the sum of a function.
-/
theorem iterate_walkConvOp_preserves_sum (μ : G → ℝ) (f : G → ℝ)
    (hprob : ∑ g : G, μ g = 1) (k : ℕ) :
    ∑ x : G, (walkConvOp μ)^[k] f x = ∑ x : G, f x := by
  induction' k with k ih;
  · rfl;
  · rw [ Function.iterate_succ_apply', ← ih, walkConvOp_preserves_sum μ _ hprob ]

/-
**Theorem 2: Exponential Purity Decay from Spectral Gap**.
    For a probability distribution f (summing to 1), the centered purity
    decays exponentially under the walk.
-/
theorem centeredPurity_iter_le_gap_decay
    (μ : G → ℝ) (gap : ℝ)
    (hprob : ∑ g : G, μ g = 1)
    (_hsym : ∀ g, μ g = μ (g⁻¹))
    (_hnonneg : ∀ g, 0 ≤ μ g)
    (hgap : spectralGapBound μ gap)
    (f : G → ℝ)
    (hf : ∑ x : G, f x = 1)
    (k : ℕ) :
    centeredPurityFn ((walkConvOp μ)^[k] f) ≤
      (1 - gap) ^ (2 * k) * centeredPurityFn f := by
  induction' k with k ih generalizing f;
  · norm_num;
  · -- Let $h := (walkConvOp μ)^[k] f - 1/|G|$.
    set h : G → ℝ := fun x => ((walkConvOp μ)^[k] f) x - 1 / (Fintype.card G : ℝ);
    -- By the properties of the walk convolution operator, we have:
    have h_walkConvOp_h : walkConvOp μ h = (walkConvOp μ)^[k + 1] f - fun _ => 1 / (Fintype.card G : ℝ) := by
      convert walkConvOp_sub_const μ ( ( walkConvOp μ )^[k] f ) ( 1 / ( Fintype.card G : ℝ ) ) hprob using 1;
      exact funext fun x => by rw [ Function.iterate_succ_apply' ] ; rfl;
    -- By the properties of the walk convolution operator, we have $\sum h(x) = 0$.
    have h_sum_h : ∑ x, h x = 0 := by
      have h_sum_h : ∑ x, ((walkConvOp μ)^[k] f) x = 1 := by
        convert iterate_walkConvOp_preserves_sum μ f hprob k using 1;
        exact hf.symm;
      simp +zetaDelta at *;
      linarith;
    -- By the properties of the walk convolution operator, we have $\text{purityFn}(walkConvOp μ h) \leq (1 - gap)^2 \text{purityFn}(h)$.
    have h_purity_h : purityFn (walkConvOp μ h) ≤ (1 - gap) ^ 2 * purityFn h := by
      exact hgap h h_sum_h;
    convert h_purity_h.trans _ using 1;
    · exact h_walkConvOp_h.symm ▸ rfl;
    · convert mul_le_mul_of_nonneg_left ( ih f hf ) ( sq_nonneg ( 1 - gap ) ) using 1 ; ring!

end QuantumMixing