"""
EML Stone–Weierstrass Theorem: Demonstration on Compact Hausdorff Spaces

This demo illustrates the EML universal approximation theorem by showing that
EML networks (built from exponential and logistic generators composed with
continuous point-separating features) can approximate arbitrary continuous
functions on compact spaces.

We demonstrate on:
  1. The circle S¹ (a compact manifold, not a subset of ℝ)
  2. The 2-sphere S² (a compact surface)
  3. A torus T² (product of circles)

In each case, we choose a continuous point-separating family Φ and show that
the EML subalgebra generated by {exp(w·Φ+b), σ(w·Φ+b)} approximates target
functions to arbitrary precision.
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# --- EML building blocks ---

def logistic(x):
    """Logistic activation σ(x) = 1/(1+exp(-x))."""
    return 1.0 / (1.0 + np.exp(-np.clip(x, -500, 500)))

def eml_exp_gen(Phi, w, b):
    """Exponential generator: exp(∑ wᵢ Φᵢ(x) + b)."""
    return np.exp(np.clip(Phi @ w + b, -500, 500))

def eml_logistic_gen(Phi, w, b):
    """Logistic generator: σ(∑ wᵢ Φᵢ(x) + b)."""
    return logistic(Phi @ w + b)


def fit_eml_network(Phi, target, n_exp=8, n_log=8, lr=0.01, steps=2000):
    """
    Fit an EML network to a target function by gradient descent.
    Uses a simple architecture: sum of weighted exp and logistic generators.
    """
    n_features = Phi.shape[1]
    np.random.seed(42)

    # Initialize parameters
    w_exp = np.random.randn(n_exp, n_features) * 0.3
    b_exp = np.random.randn(n_exp) * 0.3
    c_exp = np.random.randn(n_exp) * 0.1

    w_log = np.random.randn(n_log, n_features) * 1.0
    b_log = np.random.randn(n_log) * 0.5
    c_log = np.random.randn(n_log) * 0.1

    bias = 0.0

    for step in range(steps):
        # Forward pass
        pred = np.zeros(len(target)) + bias
        exp_gens = []
        log_gens = []
        for k in range(n_exp):
            g = eml_exp_gen(Phi, w_exp[k], b_exp[k])
            exp_gens.append(g)
            pred += c_exp[k] * g
        for k in range(n_log):
            g = eml_logistic_gen(Phi, w_log[k], b_log[k])
            log_gens.append(g)
            pred += c_log[k] * g

        residual = pred - target
        loss = np.mean(residual**2)

        # Gradient descent
        n = len(target)
        grad_bias = 2 * np.mean(residual)
        bias -= lr * grad_bias

        for k in range(n_exp):
            g = exp_gens[k]
            dc = 2 * np.mean(residual * g)
            c_exp[k] -= lr * dc
            dg = residual * c_exp[k] * g
            dw = 2 * np.mean(dg[:, None] * Phi, axis=0)
            db = 2 * np.mean(dg)
            w_exp[k] -= lr * 0.1 * dw
            b_exp[k] -= lr * 0.1 * db

        for k in range(n_log):
            g = log_gens[k]
            sig_deriv = g * (1 - g)
            dc = 2 * np.mean(residual * g)
            c_log[k] -= lr * dc
            dg = residual * c_log[k] * sig_deriv
            dw = 2 * np.mean(dg[:, None] * Phi, axis=0)
            db = 2 * np.mean(dg)
            w_log[k] -= lr * dw
            b_log[k] -= lr * db

        if step % 500 == 0:
            print(f"  Step {step:4d}: loss = {loss:.6f}")

    # Final prediction
    pred = np.zeros(len(target)) + bias
    for k in range(n_exp):
        pred += c_exp[k] * eml_exp_gen(Phi, w_exp[k], b_exp[k])
    for k in range(n_log):
        pred += c_log[k] * eml_logistic_gen(Phi, w_log[k], b_log[k])

    return pred, loss


# ============================================================
# Demo 1: Approximation on the circle S¹
# ============================================================
print("=" * 60)
print("Demo 1: EML approximation on the circle S¹")
print("=" * 60)

N = 500
theta = np.linspace(0, 2*np.pi, N, endpoint=False)

# Point-separating features: Φ = (cos θ, sin θ)
Phi_circle = np.column_stack([np.cos(theta), np.sin(theta)])

# Target: a non-trivial continuous function on S¹
target_circle = np.cos(3*theta) + 0.5 * np.sin(5*theta) + np.cos(theta)**2

print("Fitting EML network to f(θ) = cos(3θ) + 0.5·sin(5θ) + cos²(θ) on S¹...")
pred_circle, loss_circle = fit_eml_network(
    Phi_circle, target_circle, n_exp=12, n_log=12, lr=0.005, steps=3000
)
print(f"  Final L² error: {np.sqrt(np.mean((pred_circle - target_circle)**2)):.6f}")
print(f"  Max error: {np.max(np.abs(pred_circle - target_circle)):.6f}")

# ============================================================
# Demo 2: Approximation on the 2-sphere S²
# ============================================================
print("\n" + "=" * 60)
print("Demo 2: EML approximation on the 2-sphere S²")
print("=" * 60)

N_sphere = 800
indices = np.arange(0, N_sphere) + 0.5
phi_s = np.arccos(1 - 2 * indices / N_sphere)
theta_s = np.pi * (1 + 5**0.5) * indices

x_s = np.sin(phi_s) * np.cos(theta_s)
y_s = np.sin(phi_s) * np.sin(theta_s)
z_s = np.cos(phi_s)

# Point-separating features: Φ = (x, y, z)
Phi_sphere = np.column_stack([x_s, y_s, z_s])

# Target: spherical harmonic Y₂₀ ∝ 3z² - 1
target_sphere = 3 * z_s**2 - 1

print("Fitting EML network to Y₂₀(x,y,z) = 3z² - 1 on S²...")
pred_sphere, loss_sphere = fit_eml_network(
    Phi_sphere, target_sphere, n_exp=15, n_log=15, lr=0.003, steps=3000
)
print(f"  Final L² error: {np.sqrt(np.mean((pred_sphere - target_sphere)**2)):.6f}")
print(f"  Max error: {np.max(np.abs(pred_sphere - target_sphere)):.6f}")

# ============================================================
# Demo 3: Approximation on the torus T²
# ============================================================
print("\n" + "=" * 60)
print("Demo 3: EML approximation on the torus T² = S¹ × S¹")
print("=" * 60)

N_torus = 40
u_grid = np.linspace(0, 2*np.pi, N_torus, endpoint=False)
v_grid = np.linspace(0, 2*np.pi, N_torus, endpoint=False)
U, V = np.meshgrid(u_grid, v_grid)
u_flat = U.flatten()
v_flat = V.flatten()

Phi_torus = np.column_stack([
    np.cos(u_flat), np.sin(u_flat),
    np.cos(v_flat), np.sin(v_flat)
])

target_torus = np.cos(u_flat) * np.sin(v_flat) + np.cos(2*u_flat - v_flat)

print("Fitting EML network to f(u,v) = cos(u)sin(v) + cos(2u-v) on T²...")
pred_torus, loss_torus = fit_eml_network(
    Phi_torus, target_torus, n_exp=15, n_log=15, lr=0.003, steps=3000
)
print(f"  Final L² error: {np.sqrt(np.mean((pred_torus - target_torus)**2)):.6f}")
print(f"  Max error: {np.max(np.abs(pred_torus - target_torus)):.6f}")

# ============================================================
# Point Separation Demonstration
# ============================================================
print("\n" + "=" * 60)
print("Demo 4: Point separation by EML generators")
print("=" * 60)

print("\nShowing exp generators separate points on S¹:")
pairs = [(0.3, 1.7), (np.pi/4, 3*np.pi/4), (0.0, np.pi)]
for t1, t2 in pairs:
    phi1 = np.array([np.cos(t1), np.sin(t1)])
    phi2 = np.array([np.cos(t2), np.sin(t2)])
    w = np.array([1.0, 0.0])
    val1 = np.exp(w @ phi1)
    val2 = np.exp(w @ phi2)
    print(f"  θ₁={t1:.2f}, θ₂={t2:.2f}: exp(cos θ₁)={val1:.6f}, exp(cos θ₂)={val2:.6f}, "
          f"separated={'Yes' if abs(val1-val2) > 1e-10 else 'No'}")

# ============================================================
# Visualization
# ============================================================
fig = plt.figure(figsize=(18, 12))
gs = GridSpec(2, 3, figure=fig, hspace=0.35, wspace=0.3)

ax1 = fig.add_subplot(gs[0, 0])
ax1.plot(theta, target_circle, 'b-', linewidth=2, label='Target', alpha=0.8)
ax1.plot(theta, pred_circle, 'r--', linewidth=2, label='EML approx', alpha=0.8)
ax1.set_xlabel('θ', fontsize=12)
ax1.set_ylabel('f(θ)', fontsize=12)
ax1.set_title('EML Approximation on S¹', fontsize=13, fontweight='bold')
ax1.legend(fontsize=10)
ax1.grid(True, alpha=0.3)

ax2 = fig.add_subplot(gs[0, 1])
ax2.plot(theta, np.abs(pred_circle - target_circle), 'g-', linewidth=1.5)
ax2.set_xlabel('θ', fontsize=12)
ax2.set_ylabel('|error|', fontsize=12)
ax2.set_title('Approximation Error on S¹', fontsize=13, fontweight='bold')
ax2.grid(True, alpha=0.3)

ax3 = fig.add_subplot(gs[0, 2], projection='3d')
sc = ax3.scatter(x_s, y_s, z_s, c=pred_sphere, cmap='RdBu_r', s=5, alpha=0.8)
ax3.set_title('EML on S² (approx)', fontsize=13, fontweight='bold')
ax3.set_xlabel('x'); ax3.set_ylabel('y'); ax3.set_zlabel('z')
plt.colorbar(sc, ax=ax3, shrink=0.6, label='value')

ax4 = fig.add_subplot(gs[1, 0])
im4 = ax4.imshow(target_torus.reshape(N_torus, N_torus),
                  extent=[0, 2*np.pi, 0, 2*np.pi], origin='lower',
                  cmap='viridis', aspect='equal')
ax4.set_xlabel('u', fontsize=12)
ax4.set_ylabel('v', fontsize=12)
ax4.set_title('Target on T²', fontsize=13, fontweight='bold')
plt.colorbar(im4, ax=ax4, shrink=0.8)

ax5 = fig.add_subplot(gs[1, 1])
im5 = ax5.imshow(pred_torus.reshape(N_torus, N_torus),
                  extent=[0, 2*np.pi, 0, 2*np.pi], origin='lower',
                  cmap='viridis', aspect='equal')
ax5.set_xlabel('u', fontsize=12)
ax5.set_ylabel('v', fontsize=12)
ax5.set_title('EML Approximation on T²', fontsize=13, fontweight='bold')
plt.colorbar(im5, ax=ax5, shrink=0.8)

ax6 = fig.add_subplot(gs[1, 2])
im6 = ax6.imshow(np.abs(pred_torus - target_torus).reshape(N_torus, N_torus),
                  extent=[0, 2*np.pi, 0, 2*np.pi], origin='lower',
                  cmap='hot', aspect='equal')
ax6.set_xlabel('u', fontsize=12)
ax6.set_ylabel('v', fontsize=12)
ax6.set_title('Error on T²', fontsize=13, fontweight='bold')
plt.colorbar(im6, ax=ax6, shrink=0.8)

plt.suptitle('EML Universal Approximation on Non-Euclidean Compact Spaces',
             fontsize=15, fontweight='bold', y=1.01)
plt.savefig('demos/eml_hausdorff_demo.png', dpi=150, bbox_inches='tight')
print("\nFigure saved to demos/eml_hausdorff_demo.png")
plt.close()

# ============================================================
# Convergence study
# ============================================================
print("\n" + "=" * 60)
print("Demo 5: Convergence as network size increases")
print("=" * 60)

sizes = [2, 4, 8, 16, 32]
errors = []
for size in sizes:
    pred, _ = fit_eml_network(
        Phi_circle, target_circle, n_exp=size, n_log=size, lr=0.005, steps=2000
    )
    err = np.max(np.abs(pred - target_circle))
    errors.append(err)
    print(f"  {size:2d} exp + {size:2d} log generators: max error = {err:.6f}")

fig2, ax = plt.subplots(figsize=(8, 5))
ax.semilogy(sizes, errors, 'bo-', linewidth=2, markersize=8)
ax.set_xlabel('Number of generators (each type)', fontsize=12)
ax.set_ylabel('Max approximation error', fontsize=12)
ax.set_title('EML Convergence on S¹: Error vs. Network Size', fontsize=13, fontweight='bold')
ax.grid(True, alpha=0.3)
plt.savefig('demos/eml_convergence.png', dpi=150, bbox_inches='tight')
print("\nConvergence plot saved to demos/eml_convergence.png")
plt.close()

print("\n" + "=" * 60)
print("All demos completed successfully!")
print("=" * 60)
