import Mathlib
-- The module `MachineLearning.TropicalNTKDynamics` is referenced by the original
-- catalog export but is absent from this repository.  The two predicates and the
-- one lemma that this file used from it are reconstructed below, so that the file
-- is self-contained and compiles.

/-!
# Neural Tangent Kernel Convergence

This chapter isolates the architecture-independent dynamical core of lazy training.
On a finite training set, a frozen neural tangent kernel determines a linear residual
recursion. A strict contraction hypothesis gives convergence to the interpolating NTK
solution, while equality of frozen kernels gives universality of the entire training
trajectory across architectures.
-/

open Filter

noncomputable section

namespace NTKConvergence

/-- Residual dynamics generated by a fixed update operator. -/
def residualIterate {E : Type*} (step : E → E) (r₀ : E) : ℕ → E
  | 0 => r₀
  | n + 1 => step (residualIterate step r₀ n)

/-- Predictions associated with a target and a residual trajectory. -/
def predictionIterate {E : Type*} [AddGroup E]
    (target : E) (step : E → E) (r₀ : E) (n : ℕ) : E :=
  target + residualIterate step r₀ n

/-- The frozen-kernel gradient step on residuals: `r ↦ r - ηKr`. -/
def frozenKernelStep {E : Type*} [AddCommGroup E] [Module ℝ E]
    (K : E →ₗ[ℝ] E) (η : ℝ) : E → E :=
  fun r => r - η • K r

/-- Iterating a pointwise contraction yields a geometric norm estimate. -/
theorem residualIterate_norm_bound
    {E : Type*} [NormedAddCommGroup E]
    (step : E → E) (r₀ : E) (q : ℝ)
    (hq : 0 ≤ q)
    (hcontract : ∀ r, ‖step r‖ ≤ q * ‖r‖) :
    ∀ n : ℕ, ‖residualIterate step r₀ n‖ ≤ q ^ n * ‖r₀‖ := by
  intro n
  induction n with
  | zero => simp [residualIterate]
  | succ n ih =>
      rw [residualIterate]
      calc
        ‖step (residualIterate step r₀ n)‖ ≤
            q * ‖residualIterate step r₀ n‖ := hcontract _
        _ ≤ q * (q ^ n * ‖r₀‖) := mul_le_mul_of_nonneg_left ih hq
        _ = q ^ (n + 1) * ‖r₀‖ := by ring

/-- A strict frozen-kernel contraction drives every residual to zero. -/
theorem residualIterate_tendsto_zero
    {E : Type*} [NormedAddCommGroup E]
    (step : E → E) (r₀ : E) (q : ℝ)
    (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hcontract : ∀ r, ‖step r‖ ≤ q * ‖r‖) :
    Tendsto (residualIterate step r₀) atTop (nhds 0) := by
  apply squeeze_zero_norm (residualIterate_norm_bound step r₀ q hq0 hcontract)
  have hpow := tendsto_pow_atTop_nhds_zero_of_lt_one hq0 hq1
  simpa using hpow.mul_const ‖r₀‖

/-- **Frozen NTK convergence.** If `I - ηK` is a strict contraction, lazy
training converges to the interpolating NTK solution (the target vector). -/
theorem frozen_ntk_converges_to_target
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (K : E →L[ℝ] E) (η : ℝ) (target initial : E) (q : ℝ)
    (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hcontract : ∀ r : E, ‖r - η • K r‖ ≤ q * ‖r‖) :
    Tendsto
      (predictionIterate target (fun r => r - η • K r) (initial - target))
      atTop (nhds target) := by
  have hres : Tendsto
      (residualIterate (fun r : E => r - η • K r) (initial - target))
      atTop (nhds 0) :=
    residualIterate_tendsto_zero _ _ q hq0 hq1 hcontract
  simpa [predictionIterate] using hres.const_add target

/-- On a kernel eigendirection, lazy training has the exact spectral decay factor
`(1 - ηλ)ⁿ`. This identifies the step-size condition behind contraction. -/
theorem frozenKernelStep_iterate_of_eigenvector
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (K : E →L[ℝ] E) (eta eigenvalue : ℝ) (r : E)
    (heigen : K r = eigenvalue • r) :
    ∀ n : ℕ,
      residualIterate (fun x => x - eta • K x) r n =
        (1 - eta * eigenvalue) ^ n • r := by
  intro n
  induction n with
  | zero => simp [residualIterate]
  | succ n ih =>
      rw [residualIterate, ih, K.map_smul, heigen]
      rw [smul_smul, smul_smul, ← sub_smul]
      congr 1
      ring

/-- Frozen kernels determine the whole training path: two architectures with the
same kernel, learning rate, target, and initial predictions have identical iterates. -/
theorem architecture_universality_of_equal_frozen_kernel
    {E : Type*} [AddCommGroup E] [Module ℝ E]
    (K₁ K₂ : E →ₗ[ℝ] E) (η : ℝ) (target initial : E)
    (hK : K₁ = K₂) :
    ∀ n : ℕ,
      predictionIterate target (frozenKernelStep K₁ η) (initial - target) n =
      predictionIterate target (frozenKernelStep K₂ η) (initial - target) n := by
  subst K₂
  intro n
  rfl

/-- Equality of kernel actions along two residual paths is enough for trajectory
universality; global equality of the operators is not required. -/
theorem architecture_universality_on_trajectory
    {E : Type*} [AddCommGroup E] [Module ℝ E]
    (K₁ K₂ : E →ₗ[ℝ] E) (η : ℝ) (r₀ : E)
    (hagrees : ∀ n,
      K₁ (residualIterate (frozenKernelStep K₁ η) r₀ n) =
      K₂ (residualIterate (frozenKernelStep K₂ η) r₀ n)) :
    ∀ n,
      residualIterate (frozenKernelStep K₁ η) r₀ n =
      residualIterate (frozenKernelStep K₂ η) r₀ n := by
  intro n
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [residualIterate, residualIterate]
      unfold frozenKernelStep
      calc
        residualIterate (frozenKernelStep K₁ η) r₀ n -
            η • K₁ (residualIterate (frozenKernelStep K₁ η) r₀ n) =
          residualIterate (frozenKernelStep K₂ η) r₀ n -
            η • K₁ (residualIterate (frozenKernelStep K₁ η) r₀ n) := by rw [ih]
        _ = residualIterate (frozenKernelStep K₂ η) r₀ n -
            η • K₂ (residualIterate (frozenKernelStep K₂ η) r₀ n) := by
              rw [hagrees n]

namespace TropicalKernelDynamics

/-- Two parameter vectors lie in the same tropical cell when the cell-labelling
map does not separate them. -/
def SameTropicalCell {P : ℕ} {C : Type*} (cellOf : (Fin P → ℝ) → C)
    (x y : Fin P → ℝ) : Prop := cellOf x = cellOf y

/-- A kernel map is cell-wise constant when it factors through the cell
labelling. -/
def IsCellwiseConstant {P N : ℕ} {C : Type*} (cellOf : (Fin P → ℝ) → C)
    (K : (Fin P → ℝ) → Matrix (Fin N) (Fin N) ℝ) : Prop :=
  ∀ x y, cellOf x = cellOf y → K x = K y

/-- **Cell invariance freezes the kernel.**  A trajectory that stays inside one
tropical cell up to time `T` sees a constant cell-wise constant kernel. -/
theorem tropical_lazy_training_of_cell_invariance {P N : ℕ} {C : Type*}
    (cellOf : (Fin P → ℝ) → C) (traj : ℝ → (Fin P → ℝ))
    (K : (Fin P → ℝ) → Matrix (Fin N) (Fin N) ℝ) (T : ℝ) (_hT : 0 < T)
    (hcell : ∀ t, 0 ≤ t → t < T → SameTropicalCell cellOf (traj t) (traj 0))
    (hK : IsCellwiseConstant cellOf K) :
    ∀ t, 0 ≤ t → t < T → K (traj t) = K (traj 0) :=
  fun t ht0 htT => hK _ _ (hcell t ht0 htT)

end TropicalKernelDynamics

/-- The tropical cell criterion supplies a concrete source of frozen kernels:
a trajectory confined to one cell has a constant NTK matrix. -/
theorem tropical_cell_gives_frozen_ntk
    {P N : ℕ} {C : Type*}
    (cellOf : (Fin P → ℝ) → C)
    (K : (Fin P → ℝ) → Matrix (Fin N) (Fin N) ℝ)
    (traj : ℝ → (Fin P → ℝ)) (T : ℝ) (hT : 0 < T)
    (hcell : ∀ t, 0 ≤ t → t < T →
      TropicalKernelDynamics.SameTropicalCell cellOf (traj t) (traj 0))
    (hK : TropicalKernelDynamics.IsCellwiseConstant cellOf K) :
    ∀ t, 0 ≤ t → t < T → K (traj t) = K (traj 0) := by
  exact TropicalKernelDynamics.tropical_lazy_training_of_cell_invariance
    cellOf traj K T hT hcell hK

-- !-- Lab Notes -- !--
-- Hypothesis: (1) every frozen strict-contraction NTK converges geometrically;
-- (2) its rate is exactly spectral on eigendirections; (3) equal limiting kernels make
-- different architectures dynamically indistinguishable; (4) equality merely along
-- the realized paths already suffices; (5) tropical cell confinement supplies exact
-- lazy behavior; (6, bold) approximate kernel equality should imply quantitative
-- finite-horizon trajectory stability.
-- Experiment: the residual recursion was separated from neural parameter space. Claims
-- (1)--(5) survived; claim (6) was retained as a testable perturbation conjecture because
-- its sharp bound requires an additional Lipschitz/discrepancy framework.
-- Analysis: strict contraction is the analytic ingredient for interpolation, while
-- cell invariance is a geometric ingredient that freezes the kernel. The eigendirection
-- formula exposes the spectral factor `1 - ηλ` joining these two levels.
-- Critique: positive semidefiniteness alone does not imply strict contraction because
-- a kernel may have a nontrivial nullspace. Consequently the convergence theorem states
-- spectral contraction explicitly, concerns predictions rather than parameters, and
-- makes no unsupported infinite-width or probabilistic limit claim.
-- Synthesis: geometric decay, exact spectral dynamics, pathwise universality, and the
-- existing tropical cell criterion form an architecture-independent lazy-training
-- convergence principle for finite training sets.
-- !-- End Lab Notes -- !--

end NTKConvergence