#!/usr/bin/env python3
"""
Gravitational Factoring on Pythagorean Quadruple Trees
======================================================

Demonstrates the core ideas of using Pythagorean quadruples (and higher-dimensional
extensions) as a geometric framework for integer factoring.

Key algorithms:
1. Quadruple Tree Traversal: Navigate the tree of Pythagorean quadruples
2. GCD Cascade: Extract factors via peel channels
3. Quaternion Norm Factoring: Use Lagrange 4-square decomposition
4. Energy Minimization: Gradient descent on factoring potential
5. Neural Heuristic: Learn navigation policies on the tree
6. Higher-Dimensional Scanning: k-tuple channels for k = 3..8
"""

import math
import random
import itertools
from collections import defaultdict
from typing import List, Tuple, Optional, Dict
import time

# ============================================================================
# SECTION 1: Pythagorean Quadruple Fundamentals
# ============================================================================

def is_pythagorean_quadruple(a, b, c, d):
    """Check if a² + b² + c² = d²."""
    return a*a + b*b + c*c == d*d

def generate_quadruples_up_to(D):
    """Generate all Pythagorean quadruples with hypotenuse ≤ D."""
    quads = []
    for d in range(1, D + 1):
        for a in range(0, d):
            for b in range(a, d):
                rem = d*d - a*a - b*b
                if rem < 0:
                    break
                c = int(math.isqrt(rem))
                if c >= b and c*c == rem:
                    quads.append((a, b, c, d))
    return quads

def generate_quadruples_parametric(max_param=20):
    """Generate quadruples using the parametric formula:
    (a, b, c, d) = (m²+n²-p²-q², 2(mq+np), 2(nq-mp), m²+n²+p²+q²)
    """
    quads = set()
    for m in range(0, max_param):
        for n in range(0, max_param):
            for p in range(0, max_param):
                for q in range(0, max_param):
                    if m == 0 and n == 0 and p == 0 and q == 0:
                        continue
                    a = m*m + n*n - p*p - q*q
                    b = 2*(m*q + n*p)
                    c = 2*(n*q - m*p)
                    d = m*m + n*n + p*p + q*q
                    if a >= 0 and b >= 0 and c >= 0:
                        triple = tuple(sorted([a, b, c]))
                        quads.add((triple[0], triple[1], triple[2], d))
    return sorted(quads, key=lambda x: x[3])

# ============================================================================
# SECTION 2: The Root Node and Tree Structure
# ============================================================================

# Fundamental root nodes
ROOT_NODES = [
    (0, 0, 1, 1),   # Degenerate root
    (1, 2, 2, 3),   # Smallest primitive
    (2, 3, 6, 7),   # Second primitive
    (1, 4, 8, 9),   # Third primitive
    (4, 4, 7, 9),   # Fourth primitive
]

def quadruple_children(a, b, c, d, max_d=1000):
    """Generate children of a quadruple in the tree using transformations.
    
    For Pythagorean quadruples, children are generated by matrix actions
    that preserve the quadratic form x²+y²+z²=w².
    """
    children = []
    
    # Transformation matrices that map quadruples to quadruples
    # These are generators of the orthogonal group O(3,1) over integers
    transforms = [
        # Type 1: Scaling by coordinate
        lambda a,b,c,d: (2*d - a, b, c, 2*d + a - 2*b),  
        lambda a,b,c,d: (a, 2*d - b, c, 2*d - 2*a + b),
        lambda a,b,c,d: (a, b, 2*d - c, 2*d - 2*a - 2*b + c),
        # Type 2: Cross-additions
        lambda a,b,c,d: (a + 2*d, b + 2*d, c, 3*d + 2*a + 2*b),
        lambda a,b,c,d: (a + 2*d, b, c + 2*d, 3*d + 2*a + 2*c),
        lambda a,b,c,d: (a, b + 2*d, c + 2*d, 3*d + 2*b + 2*c),
    ]
    
    # Simple child generation: add multiples
    for m in range(1, 5):
        for n in range(0, 5):
            # (a + 2md, b + 2nd, c, ...) type constructions
            new_a = a + 2*m*d
            new_b = b + 2*n*d
            rem = new_a**2 + new_b**2 + c**2
            sqrt_rem = int(math.isqrt(rem))
            if sqrt_rem > 0 and sqrt_rem**2 == rem and sqrt_rem <= max_d:
                children.append((new_a, new_b, c, sqrt_rem))
    
    return children

# ============================================================================
# SECTION 3: GCD Cascade Factor Extraction
# ============================================================================

def peel_channels(a, b, c, d, N):
    """Extract candidate factors from all peel channels of a quadruple.
    
    Peel channel j: gcd(d - leg_j, N)
    
    Returns list of (channel_name, gcd_value).
    """
    legs = [('a', a), ('b', b), ('c', c)]
    results = []
    for name, leg in legs:
        g_minus = math.gcd(abs(d - leg), N)
        g_plus = math.gcd(abs(d + leg), N)
        results.append((f'd-{name}', g_minus))
        results.append((f'd+{name}', g_plus))
    return results

def cross_collision_channels(a1, b1, c1, a2, b2, c2, d, N):
    """Extract factors from cross-collision of two quadruples sharing hypotenuse d.
    
    Cross differences: a1² - a2² = (a1-a2)(a1+a2), etc.
    """
    results = []
    for (name1, v1, name2, v2) in [('a', a1, 'a', a2), ('b', b1, 'b', b2), ('c', c1, 'c', c2)]:
        diff_sq = v1*v1 - v2*v2
        g = math.gcd(abs(diff_sq), N)
        results.append((f'{name1}²-{name2}²', g))
        g_sum = math.gcd(abs(v1 + v2), N)
        g_diff = math.gcd(abs(v1 - v2), N)
        results.append((f'{name1}+{name2}', g_sum))
        results.append((f'{name1}-{name2}', g_diff))
    return results

def gcd_cascade_factor(N, quadruples):
    """Attempt to factor N using GCD cascade across multiple quadruples.
    
    Strategy: For each quadruple with hypotenuse related to N,
    compute GCD with all peel channels.
    """
    factors_found = set()
    for (a, b, c, d) in quadruples:
        channels = peel_channels(a, b, c, d, N)
        for name, g in channels:
            if 1 < g < N:
                factors_found.add(g)
                print(f"  Factor {g} found via channel {name} of ({a},{b},{c},{d})")
    return factors_found

# ============================================================================
# SECTION 4: Quaternion Norm Factoring
# ============================================================================

def four_square_decomposition(n):
    """Find a representation n = a² + b² + c² + d² using greedy + backtracking."""
    if n == 0:
        return (0, 0, 0, 0)
    
    for a in range(int(math.isqrt(n)), -1, -1):
        rem_a = n - a*a
        if rem_a < 0:
            continue
        for b in range(min(a, int(math.isqrt(rem_a))), -1, -1):
            rem_b = rem_a - b*b
            if rem_b < 0:
                continue
            for c in range(min(b, int(math.isqrt(rem_b))), -1, -1):
                rem_c = rem_b - c*c
                d = int(math.isqrt(rem_c))
                if d*d == rem_c and d <= c:
                    return (a, b, c, d)
    return None

def quaternion_multiply(q1, q2):
    """Multiply two quaternions (a,b,c,d) representing a + bi + cj + dk."""
    a1, b1, c1, d1 = q1
    a2, b2, c2, d2 = q2
    return (
        a1*a2 - b1*b2 - c1*c2 - d1*d2,
        a1*b2 + b1*a2 + c1*d2 - d1*c2,
        a1*c2 - b1*d2 + c1*a2 + d1*b2,
        a1*d2 + b1*c2 - c1*b2 + d1*a2
    )

def quaternion_norm(q):
    """Norm of quaternion = a² + b² + c² + d²."""
    return sum(x*x for x in q)

def quaternion_factor_attempt(N):
    """Attempt to factor N using quaternion norm decomposition.
    
    Strategy:
    1. Find N = a² + b² + c² + d² (Lagrange)
    2. Try to split the quaternion q = (a,b,c,d) into q₁·q₂
       with norm(q₁) = p, norm(q₂) = q, p*q = N
    3. GCD-based extraction from quaternion coordinates
    """
    decomp = four_square_decomposition(N)
    if decomp is None:
        return None
    
    a, b, c, d = decomp
    print(f"  Lagrange decomposition: {N} = {a}² + {b}² + {c}² + {d}²")
    
    # Try GCD extraction from quaternion components
    factors = set()
    for x in [a, b, c, d]:
        if x > 0:
            g = math.gcd(x, N)
            if 1 < g < N:
                factors.add(g)
    
    # Try sums and differences of squares
    for x, y in itertools.combinations([a, b, c, d], 2):
        for val in [x*x + y*y, abs(x*x - y*y), x+y, abs(x-y)]:
            if val > 0:
                g = math.gcd(val, N)
                if 1 < g < N:
                    factors.add(g)
    
    return factors

# ============================================================================
# SECTION 5: Energy Minimization / Gravitational Descent
# ============================================================================

def factoring_energy(a, b, c, d, N):
    """The factoring energy: how far from factoring N.
    
    E = min over all peel channels of (distance to nontrivial GCD).
    Lower energy = closer to factoring.
    """
    channels = peel_channels(a, b, c, d, N)
    max_g = max(g for _, g in channels)
    if max_g == N:
        return float('inf')  # Trivial
    if max_g > 1:
        return 0  # Found a factor!
    # Energy based on how close GCDs are to being nontrivial
    return min(abs(d - leg) % N for leg in [a, b, c] if abs(d - leg) > 0)

def gravitational_descent(N, max_steps=10000):
    """Navigate the quadruple tree using energy minimization.
    
    Start from quadruples near N and descend toward lower energy states.
    """
    print(f"\n{'='*60}")
    print(f"Gravitational Descent for N = {N}")
    print(f"{'='*60}")
    
    # Start with quadruples whose hypotenuse is near N
    best_energy = float('inf')
    best_quad = None
    factors = set()
    
    # Generate starting quadruples around N
    for offset in range(-int(math.sqrt(N)), int(math.sqrt(N)) + 1):
        d = N + offset
        if d <= 0:
            continue
        for a in range(0, d):
            if a*a > d*d:
                break
            for b in range(a, d):
                rem = d*d - a*a - b*b
                if rem < 0:
                    break
                c = int(math.isqrt(rem))
                if c >= b and c*c == rem:
                    E = factoring_energy(a, b, c, d, N)
                    if E == 0:
                        channels = peel_channels(a, b, c, d, N)
                        for name, g in channels:
                            if 1 < g < N:
                                factors.add(g)
                        print(f"  ✓ Factor found via ({a},{b},{c},{d}): {factors}")
                        return factors
                    if E < best_energy:
                        best_energy = E
                        best_quad = (a, b, c, d)
    
    if best_quad:
        print(f"  Best quadruple: {best_quad}, energy = {best_energy}")
    
    return factors

# ============================================================================
# SECTION 6: Modular Navigation (Smart Tree Traversal)
# ============================================================================

def modular_sieve(N, max_d=None):
    """Use modular arithmetic to navigate efficiently.
    
    Key insight: We want a² + b² + c² ≡ 0 (mod N) or (mod p) for factor p.
    This constrains which quadruples can reveal factors.
    """
    if max_d is None:
        max_d = 3 * N
    
    print(f"\n{'='*60}")
    print(f"Modular Sieve Factoring for N = {N}")
    print(f"{'='*60}")
    
    factors = set()
    
    # Precompute quadratic residues mod N
    qr_N = set()
    for x in range(N):
        qr_N.add((x * x) % N)
    
    print(f"  Quadratic residues mod {N}: {sorted(qr_N)}")
    print(f"  Number of QRs: {len(qr_N)} out of {N}")
    
    # Find triples (r_a, r_b, r_c) mod N such that r_a² + r_b² + r_c² ≡ 0 (mod N)
    target_triples = []
    for ra in range(N):
        for rb in range(ra, N):
            for rc in range(rb, N):
                if (ra*ra + rb*rb + rc*rc) % N == 0:
                    target_triples.append((ra, rb, rc))
    
    print(f"  Target residue triples: {len(target_triples)}")
    if len(target_triples) <= 20:
        for t in target_triples[:10]:
            print(f"    {t}")
    
    # For each target residue triple, search for actual quadruples
    for ra, rb, rc in target_triples[:50]:  # Limit search
        for ka in range(max(1, ra), min(max_d, N * 5), N):
            a = ka if ka % N == ra else ra
            if a == 0 and ra == 0:
                a = 0
            elif a % N != ra:
                a = ra
            for kb_mult in range(0, 5):
                b = rb + kb_mult * N
                for kc_mult in range(0, 5):
                    c = rc + kc_mult * N
                    d_sq = a*a + b*b + c*c
                    d = int(math.isqrt(d_sq))
                    if d > 0 and d*d == d_sq:
                        channels = peel_channels(a, b, c, d, N)
                        for name, g in channels:
                            if 1 < g < N:
                                factors.add(g)
                                print(f"  ✓ Factor {g} via ({a},{b},{c},{d}), channel {name}")
                                return factors
    
    return factors

# ============================================================================
# SECTION 7: Higher-Dimensional k-Tuple Scanning
# ============================================================================

def ktuple_factor(N, k=4, max_hyp=None):
    """Factor N using k-dimensional Pythagorean tuples.
    
    A k-tuple: x₁² + x₂² + ... + xₖ = d²
    Gives k peel channels and C(k,2) cross-collision pairs.
    """
    if max_hyp is None:
        max_hyp = 2 * N
    
    print(f"\n{'='*60}")
    print(f"{k}-Tuple Factoring for N = {N}")
    print(f"Channels: {k} peel + {k*(k-1)//2} cross = {k + k*(k-1)//2} total")
    print(f"{'='*60}")
    
    factors = set()
    
    # For k=4: use Lagrange four-square theorem
    if k == 4:
        # Every N has a representation as sum of 4 squares
        decomp = four_square_decomposition(N)
        if decomp:
            a, b, c, d_val = decomp
            # N = a² + b² + c² + d²
            # This IS a Pythagorean 5-tuple with hypotenuse √N... 
            # but we need integer hypotenuse.
            # Instead, use N² = (Na)² + ... trick or direct quadruple search
            pass
    
    # Direct search for k-tuples with hypotenuse d related to N
    # For efficiency, search with d = N (the target itself)
    d = N
    d_sq = d * d
    
    # Try random k-tuples summing to d²
    for trial in range(min(10000, N * 10)):
        legs = []
        remaining = d_sq
        for i in range(k - 1):
            max_val = int(math.isqrt(remaining))
            if max_val == 0:
                break
            val = random.randint(0, max_val)
            legs.append(val)
            remaining -= val * val
        
        if remaining >= 0:
            last = int(math.isqrt(remaining))
            if last * last == remaining:
                legs.append(last)
                if len(legs) == k:
                    # Found a valid k-tuple! Extract factors
                    for j, leg in enumerate(legs):
                        g_minus = math.gcd(abs(d - leg), N)
                        g_plus = math.gcd(abs(d + leg), N)
                        if 1 < g_minus < N:
                            factors.add(g_minus)
                            print(f"  ✓ Factor {g_minus} via leg[{j}]={leg}, d-leg={d-leg}")
                            return factors
                        if 1 < g_plus < N:
                            factors.add(g_plus)
                            print(f"  ✓ Factor {g_plus} via leg[{j}]={leg}, d+leg={d+leg}")
                            return factors
    
    return factors

# ============================================================================
# SECTION 8: The Neural Heuristic
# ============================================================================

class SimpleNeuralNavigator:
    """A simple neural network-inspired heuristic for tree navigation.
    
    Uses a learned scoring function to decide which branch of the
    quadruple tree to explore next.
    
    Features for each quadruple (a,b,c,d):
    - Residues mod N of each component
    - GCD values with N
    - Parity pattern
    - "Energy" = factoring potential
    """
    
    def __init__(self, N):
        self.N = N
        self.weights = defaultdict(float)
        self.learning_rate = 0.1
        self.history = []
    
    def features(self, a, b, c, d):
        """Extract features from a quadruple."""
        N = self.N
        return {
            'gcd_d_N': math.gcd(d, N),
            'gcd_da_N': math.gcd(abs(d-a), N),
            'gcd_db_N': math.gcd(abs(d-b), N),
            'gcd_dc_N': math.gcd(abs(d-c), N),
            'mod_a': a % N if N > 0 else 0,
            'mod_b': b % N if N > 0 else 0,
            'mod_c': c % N if N > 0 else 0,
            'parity': (a%2, b%2, c%2, d%2),
            'd_ratio': d / N if N > 0 else 0,
        }
    
    def score(self, a, b, c, d):
        """Score a quadruple: higher = more promising for factoring."""
        feats = self.features(a, b, c, d)
        s = 0.0
        # GCD signals are strong
        for key in ['gcd_da_N', 'gcd_db_N', 'gcd_dc_N']:
            g = feats[key]
            if 1 < g < self.N:
                s += 1000  # Found a factor!
            elif g > 1:
                s += math.log(g)
        # Prefer hypotenuse near multiples of N
        d_mod = d % self.N if self.N > 0 else 0
        s -= min(d_mod, self.N - d_mod) / self.N * 10
        return s
    
    def navigate(self, max_steps=5000):
        """Navigate the tree using the scoring heuristic."""
        print(f"\n{'='*60}")
        print(f"Neural Navigation for N = {self.N}")
        print(f"{'='*60}")
        
        # Start from multiple root nodes
        frontier = list(ROOT_NODES)
        visited = set()
        best_score = -float('inf')
        best_quad = None
        
        for step in range(max_steps):
            if not frontier:
                break
            
            # Score all frontier nodes
            scored = [(self.score(a,b,c,d), (a,b,c,d)) for a,b,c,d in frontier]
            scored.sort(reverse=True)
            
            # Take the best
            s, (a,b,c,d) = scored[0]
            
            if s > best_score:
                best_score = s
                best_quad = (a,b,c,d)
            
            if s >= 1000:
                channels = peel_channels(a, b, c, d, self.N)
                factors = set()
                for name, g in channels:
                    if 1 < g < self.N:
                        factors.add(g)
                if factors:
                    print(f"  ✓ Factor found at step {step}: {best_quad} → {factors}")
                    return factors
            
            visited.add((a,b,c,d))
            
            # Generate children
            children = quadruple_children(a, b, c, d, max_d=self.N * 3)
            frontier = [child for child in children if child not in visited]
            
            # Also keep top candidates from previous frontier
            for _, q in scored[1:min(5, len(scored))]:
                if q not in visited:
                    frontier.append(q)
            
            if step % 500 == 0 and step > 0:
                print(f"  Step {step}: best_score={best_score:.2f}, best={best_quad}")
        
        if best_quad:
            print(f"  Final: best_score={best_score:.2f}, best={best_quad}")
        return set()

# ============================================================================
# SECTION 9: Comprehensive Demo
# ============================================================================

def demo_factoring(N, label=""):
    """Run all factoring methods on N and compare."""
    print(f"\n{'#'*70}")
    print(f"# FACTORING N = {N}  {label}")
    print(f"{'#'*70}")
    
    # Ground truth
    factors_true = []
    for p in range(2, int(math.isqrt(N)) + 1):
        if N % p == 0:
            factors_true.append(p)
            factors_true.append(N // p)
            break
    print(f"True factors: {factors_true}")
    
    results = {}
    
    # Method 1: Quaternion Norm
    print("\n--- Method 1: Quaternion Norm Factoring ---")
    t0 = time.time()
    f = quaternion_factor_attempt(N)
    t1 = time.time()
    results['quaternion'] = (f, t1-t0)
    print(f"  Found: {f}, time: {t1-t0:.4f}s")
    
    # Method 2: Modular Sieve
    print("\n--- Method 2: Modular Sieve ---")
    t0 = time.time()
    f = modular_sieve(N)
    t1 = time.time()
    results['modular'] = (f, t1-t0)
    print(f"  Found: {f}, time: {t1-t0:.4f}s")
    
    # Method 3: Direct Quadruple Search with GCD Cascade
    print("\n--- Method 3: GCD Cascade ---")
    t0 = time.time()
    quads = generate_quadruples_up_to(min(N + 10, 200))
    f = gcd_cascade_factor(N, quads)
    t1 = time.time()
    results['gcd_cascade'] = (f, t1-t0)
    print(f"  Found: {f}, time: {t1-t0:.4f}s")
    
    # Method 4: Neural Navigation
    print("\n--- Method 4: Neural Navigation ---")
    t0 = time.time()
    nav = SimpleNeuralNavigator(N)
    f = nav.navigate(max_steps=2000)
    t1 = time.time()
    results['neural'] = (f, t1-t0)
    print(f"  Found: {f}, time: {t1-t0:.4f}s")
    
    # Summary
    print(f"\n{'='*60}")
    print(f"SUMMARY for N = {N}")
    print(f"{'='*60}")
    for method, (factors, elapsed) in results.items():
        status = "✓ SUCCESS" if factors else "✗ FAILED"
        print(f"  {method:20s}: {status:12s} factors={factors}  time={elapsed:.4f}s")
    
    return results

# ============================================================================
# SECTION 10: Visualization Data Generation
# ============================================================================

def generate_quadruple_tree_data(max_d=50):
    """Generate data for visualizing the quadruple tree."""
    quads = generate_quadruples_up_to(max_d)
    
    print(f"\nQuadruple tree up to d={max_d}:")
    print(f"  Total quadruples: {len(quads)}")
    
    # Count by hypotenuse
    by_hyp = defaultdict(list)
    for q in quads:
        by_hyp[q[3]].append(q)
    
    print(f"  Distinct hypotenuses: {len(by_hyp)}")
    for d in sorted(by_hyp.keys())[:15]:
        print(f"    d={d}: {len(by_hyp[d])} quadruples")
        for q in by_hyp[d][:3]:
            print(f"      {q}  check: {q[0]**2 + q[1]**2 + q[2]**2} = {q[3]**2}")
    
    return quads, by_hyp

def dimensional_channel_analysis():
    """Analyze how factoring power grows with dimension."""
    print(f"\n{'='*60}")
    print("Dimensional Channel Analysis")
    print(f"{'='*60}")
    print(f"{'k':>4s} {'Peel':>6s} {'Cross':>6s} {'Total':>6s} {'Ratio':>8s}")
    print(f"{'-'*32}")
    
    prev_total = 1
    for k in range(2, 17):
        peel = k
        cross = k * (k-1) // 2
        total = peel + cross
        ratio = total / prev_total if prev_total > 0 else 0
        print(f"{k:4d} {peel:6d} {cross:6d} {total:6d} {ratio:8.2f}x")
        prev_total = total

# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    print("╔══════════════════════════════════════════════════════════════════╗")
    print("║  GRAVITATIONAL FACTORING ON PYTHAGOREAN QUADRUPLE TREES        ║")
    print("║  A Geometric Approach to Integer Factoring                     ║")
    print("╚══════════════════════════════════════════════════════════════════╝")
    
    # Demo 1: Small semiprimes
    for N, label in [(15, "= 3 × 5"), (21, "= 3 × 7"), (35, "= 5 × 7"), 
                     (77, "= 7 × 11"), (143, "= 11 × 13"), (221, "= 13 × 17")]:
        demo_factoring(N, label)
    
    # Demo 2: Quadruple tree structure
    generate_quadruple_tree_data(30)
    
    # Demo 3: Dimensional analysis
    dimensional_channel_analysis()
    
    # Demo 4: Quaternion norm analysis
    print(f"\n{'='*60}")
    print("Quaternion (4-Square) Decompositions of Small Semiprimes")
    print(f"{'='*60}")
    for N in [15, 21, 35, 77, 143, 221, 323, 437]:
        decomp = four_square_decomposition(N)
        if decomp:
            a, b, c, d = decomp
            print(f"  {N:5d} = {a}² + {b}² + {c}² + {d}²  "
                  f"= {a**2} + {b**2} + {c**2} + {d**2}")
    
    print("\n\nDone! All demos completed.")
