import Mathlib

/-!
# Dimensional Euler signs as the two Fourier characters of parity

This file gives a self-contained bridge from negative-dimensional Euler
characteristics to character theory and finite Fourier analysis.  A virtual
cellular space is a finitely supported integer function on integer dimensions.
Every unit-valued character of the dimension group `ℤ` is either trivial or the
Euler sign character.  Consequently its two character evaluations are exactly
total cell mass and Euler characteristic.  Character-table orthogonality then
recovers the even- and odd-dimensional masses.
-/

namespace NegativeDimensionCharacterBridge

/-- Virtual cellular data, allowing cells in arbitrary positive or negative
integer dimensions. -/
abbrev VSpace := AddMonoidAlgebra ℤ ℤ

/-- A character of the additive dimension group with values in the units of `ℤ`. -/
abbrev DimensionCharacter := Multiplicative ℤ →* ℤˣ

/-- The trivial dimension character. -/
def trivialCharacter : DimensionCharacter := 1

/-- The parity/Euler character, generated by the unit `-1`. -/
def eulerCharacter : DimensionCharacter := zpowersHom ℤˣ (-1 : ℤˣ)

/-
The Euler character takes dimension `d` to `(-1)^d`.
-/
lemma eulerCharacter_apply (d : ℤ) :
    eulerCharacter (Multiplicative.ofAdd d) = (-1 : ℤˣ) ^ d := by
      simp +decide [ eulerCharacter, zpowersHom ]

/-
**Character classification.**  The character group of integer dimensions
with values in `ℤˣ` has only two elements: the trivial character and parity.
This is the number-theoretic rigidity behind the dimensional Euler sign.
-/
theorem dimensionCharacter_classification (ψ : DimensionCharacter) :
    ψ = trivialCharacter ∨ ψ = eulerCharacter := by
      -- By definition of $ψ$, we know that $ψ(Multiplicative.ofAdd 1) = 1$ or $ψ(Multiplicative.ofAdd 1) = -1$.
      have h_unit : ψ (Multiplicative.ofAdd 1) = 1 ∨ ψ (Multiplicative.ofAdd 1) = -1 := by
        exact Int.units_eq_one_or _;
      aesop

/-
Parity is the unique character taking the one-dimensional generator to `-1`.
-/
theorem eulerCharacter_unique_nontrivial (ψ : DimensionCharacter)
    (hψ : ψ (Multiplicative.ofAdd 1) = (-1 : ℤˣ)) :
    ψ = eulerCharacter := by
      convert dimensionCharacter_classification ψ;
      simp_all +decide [DimensionCharacter]
      rintro rfl
      simp_all +decide

/-- Evaluation of virtual cellular data against a dimension character. -/
def characterEval (ψ : DimensionCharacter) (x : VSpace) : ℤ :=
  ∑ d ∈ x.support, (ψ (Multiplicative.ofAdd d) : ℤ) * x d

/-
Character evaluation on a pure cell in dimension `d`.
-/
theorem characterEval_single (ψ : DimensionCharacter) (d c : ℤ) :
    characterEval ψ (AddMonoidAlgebra.single d c) =
      (ψ (Multiplicative.ofAdd d) : ℤ) * c := by
        by_cases hc : c = 0 <;> simp +decide [ hc, characterEval ];
        rw [ Finset.sum_eq_single d ] <;> simp +decide;
        · convert Finsupp.single_eq_same;
          convert Finsupp.ext fun x => ?_ ; aesop;
        · intro b hb hb'; erw [ AddMonoidAlgebra.single_mul_apply ] at hb; aesop;

/-- Total signed cell mass, evaluation at the trivial character. -/
def totalMass (x : VSpace) : ℤ := ∑ d ∈ x.support, x d

/-- The dimensional Euler characteristic, evaluation at parity. -/
def eulerChi (x : VSpace) : ℤ := characterEval eulerCharacter x

/-
Total mass is precisely trivial-character evaluation.
-/
theorem characterEval_trivial (x : VSpace) :
    characterEval trivialCharacter x = totalMass x := by
      unfold characterEval totalMass trivialCharacter;
      norm_num

/-
Every integral dimension character yields either total mass or Euler
characteristic; there are no other unit-valued character evaluations.
-/
theorem characterEval_classification (ψ : DimensionCharacter) (x : VSpace) :
    characterEval ψ x = totalMass x ∨ characterEval ψ x = eulerChi x := by
      -- Apply the classification theorem to ψ.
      have hψ : ψ = trivialCharacter ∨ ψ = eulerCharacter := dimensionCharacter_classification ψ;
      cases hψ <;> simp +decide [ * ];
      · exact Or.inl ( characterEval_trivial x );
      · exact Or.inr rfl

/-- The mass in even dimensions, including negative even dimensions. -/
def evenMass (x : VSpace) : ℤ :=
  ∑ d ∈ x.support.filter Even, x d

/-- The mass in odd dimensions, including negative odd dimensions. -/
def oddMass (x : VSpace) : ℤ :=
  ∑ d ∈ x.support.filter (fun d => ¬ Even d), x d

/-
The trivial character is the sum of the two parity sectors.
-/
theorem totalMass_eq_even_add_odd (x : VSpace) :
    totalMass x = evenMass x + oddMass x := by
      unfold totalMass evenMass oddMass;
      rw [ Finset.sum_filter_add_sum_filter_not ]

/-
The Euler character is the difference of the two parity sectors.
-/
theorem eulerChi_eq_even_sub_odd (x : VSpace) :
    eulerChi x = evenMass x - oddMass x := by
      unfold eulerChi evenMass oddMass characterEval;
      rw [ Finset.sum_filter, Finset.sum_filter ];
      rw [ ← Finset.sum_sub_distrib ] ; congr ; ext d ; split_ifs <;> simp_all +decide [ eulerCharacter_apply ] ;
      · rw [ Even.neg_zpow ] <;> aesop;
      · obtain ⟨ k, rfl ⟩ := ‹Odd d›; norm_num [ zpow_add, zpow_mul ] ;
        norm_num [ zpow_two ]

/-
**Character-table/Fourier bridge.**  The two topological measurements,
total cell mass and negative-dimensional Euler characteristic, are the two
characters of `ℤ/2`; their character-table transform recovers both parity
sectors.  This is the integral (denominator-free) Fourier inversion formula.
-/
theorem parity_fourier_reconstruction (x : VSpace) :
    totalMass x + eulerChi x = 2 * evenMass x ∧
    totalMass x - eulerChi x = 2 * oddMass x := by
      constructor <;> rw [ totalMass_eq_even_add_odd, eulerChi_eq_even_sub_odd ] <;> ring

/-- Euler characteristic is invariant under reflection of every dimension,
expressing the self-duality `d ↦ -d` at the character level. -/
noncomputable def reflect (x : VSpace) : VSpace :=
  AddMonoidAlgebra.mapDomain (negAddMonoidHom : ℤ →+ ℤ) x

/-
Reflection preserves the Euler character evaluation.
-/
theorem eulerChi_reflect (x : VSpace) : eulerChi (reflect x) = eulerChi x := by
  unfold eulerChi reflect;
  convert Finset.sum_bij ( fun y hy => -y ) _ _ _ _ using 1;
  · simp +contextual [ Finsupp.mapDomain ];
    intro a ha; contrapose! ha; simp_all +decide [ Finsupp.sum ] ;
    convert Finset.sum_eq_zero _ ; intros ; simp_all +decide;
    erw [ AddMonoidAlgebra.single_mul_apply ] ; aesop;
  · aesop;
  · intro b hb; use -b; simp_all +decide [ AddMonoidAlgebra.mapDomain ] ;
    rw [ Finsupp.mapDomain_apply ] ; aesop;
    exact neg_injective;
  · -- By definition of mapDomain, we have that (mapDomain neg x) a = x (-a).
    have h_mapDomain : ∀ a, (AddMonoidAlgebra.mapDomain (⇑negAddMonoidHom) x) a = x (-a) := by
      intro a; exact (by
      convert Finsupp.mapDomain_apply _ _ _;
      · exact Eq.symm ( neg_neg a );
      · exact neg_injective);
    simp_all +decide [ eulerCharacter_apply ]

/-! ## A machine-checked mixed-dimensional example -/

/-- A sample with coefficients `3,5,7,11` in dimensions `-2,-1,0,3`. -/
noncomputable def sampleSpace : VSpace :=
  AddMonoidAlgebra.single (-2) 3 + AddMonoidAlgebra.single (-1) 5 +
  AddMonoidAlgebra.single 0 7 + AddMonoidAlgebra.single 3 11

/-
The sample has even mass `10`, odd mass `16`, total mass `26`, and Euler
characteristic `-6`, so its Fourier reconstruction is `(20,32)`.
-/
theorem sampleSpace_calculation :
    evenMass sampleSpace = 10 ∧ oddMass sampleSpace = 16 ∧
    totalMass sampleSpace = 26 ∧ eulerChi sampleSpace = -6 ∧
    totalMass sampleSpace + eulerChi sampleSpace = 20 ∧
    totalMass sampleSpace - eulerChi sampleSpace = 32 := by
      unfold evenMass oddMass totalMass eulerChi;
      unfold characterEval sampleSpace; simp +decide [ Finset.sum_filter, Finset.sum_add_distrib ] ;
      -- The support of the polynomial is {-2, -1, 0, 3}.
      have h_support : (3 * LaurentPolynomial.T (-2) + 5 * LaurentPolynomial.T (-1) + 7 + 11 * LaurentPolynomial.T 3 : LaurentPolynomial ℤ).support = {-2, -1, 0, 3} := by
        -- The support of a sum of singletons is the union of their supports.
        have h_support_union : ∀ (s : Finset ℤ) (f : ℤ → ℤ), (∀ d ∈ s, f d ≠ 0) → (Finset.sum s (fun d => AddMonoidAlgebra.single d (f d))).support = s := by
          intro s f hf; ext d; simp +decide;
          -- The coefficient of $T^d$ in the sum is the sum of $f(x)$ for all $x \in s$ such that $x = d$.
          have h_coeff : (∑ x ∈ s, (f x : ℤ) • LaurentPolynomial.T x) d = ∑ x ∈ s, if x = d then f x else 0 := by
            rw [ Finset.sum_apply' ];
            refine' Finset.sum_congr rfl fun x hx => _;
            erw [ Finsupp.smul_apply ] ; aesop;
          by_cases hd : d ∈ s <;> simp_all +decide;
        convert h_support_union { -2, -1, 0, 3 } ( fun d => if d = -2 then 3 else if d = -1 then 5 else if d = 0 then 7 else 11 ) _ using 1 <;> simp +decide;
        abel_nf;
      simp +decide [ h_support, eulerCharacter_apply ];
      erw [ AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply ] ; norm_num;
      erw [ AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply ] ; norm_num;
      erw [ AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply, AddMonoidAlgebra.single_mul_apply ] ; norm_num;
      erw [ AddMonoidAlgebra.single_apply, AddMonoidAlgebra.single_apply, AddMonoidAlgebra.single_apply, AddMonoidAlgebra.single_apply ] ; norm_num;
      decide +revert

end NegativeDimensionCharacterBridge