/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Core Definitions for GL₂(𝔽_q) Certified Expander Theory

This file introduces the core algebraic definitions for the certified
expander framework:

* `SingerLike`: matrices with irreducible characteristic polynomial
* `PrimitiveDet`: matrices whose determinant generates 𝔽_qˣ
* Helper definitions for Cayley graph spectral analysis on abstract groups

These definitions are the foundation of the certificate-driven expander
synthesis paradigm.
-/

import Mathlib

open Finset BigOperators Matrix Polynomial Submodule

/-! ## Singer-Like Matrices -/

/-- A matrix `g ∈ GL₂(𝔽_q)` is **Singer-like** if it is invertible and its
characteristic polynomial is irreducible over 𝔽_q. Such elements act as
"field extensions in disguise": they have eigenvalues in 𝔽_{q²} \ 𝔽_q.

The Singer-like property is the geometric engine of certified expansion:
it prevents the averaging operator from concentrating on any
low-dimensional invariant subspace of the representation. -/
def SingerLike {q : ℕ} [Fact q.Prime]
    (g : Matrix (Fin 2) (Fin 2) (ZMod q)) : Prop :=
  IsUnit g.det ∧ Irreducible g.charpoly

/-- A matrix `h` has **primitive determinant** if `det(h)` has multiplicative
order `q - 1` in 𝔽_qˣ, i.e., it generates the full multiplicative group.
This ensures the subgroup generated by `h` maps surjectively onto the
determinant quotient GL₂/SL₂ ≅ 𝔽_qˣ. -/
def PrimitiveDet {q : ℕ} [Fact q.Prime]
    (h : Matrix (Fin 2) (Fin 2) (ZMod q)) : Prop :=
  ∃ (hu : IsUnit h.det), orderOf hu.unit = q - 1

/-! ## Projective Line Concepts -/

/-- A 1-dimensional subspace (line) in 𝔽_q². These are the points of the
projective line ℙ¹(𝔽_q). -/
def IsProjectiveLine {q : ℕ} [Fact q.Prime]
    (W : Submodule (ZMod q) (Fin 2 → ZMod q)) : Prop :=
  Module.finrank (ZMod q) W = 1

/-- A matrix preserves a subspace if its linear action maps the subspace to itself. -/
def PreservesSubspace {q : ℕ} [Fact q.Prime]
    (g : Matrix (Fin 2) (Fin 2) (ZMod q))
    (W : Submodule (ZMod q) (Fin 2 → ZMod q)) : Prop :=
  ∀ w ∈ W, g.mulVecLin w ∈ W

/-! ## Cayley Graph and Spectral Definitions -/

/-- The symmetric generator set from a pair in a group: `{g, g⁻¹, h, h⁻¹}`. -/
def symGensOf {G : Type*} [Group G] [DecidableEq G] (g h : G) : Finset G :=
  {g, g⁻¹, h, h⁻¹}

/-- The inner product on `G → ℝ` for a finite group `G`. -/
noncomputable def groupInner' {G : Type*} [Fintype G] (f g : G → ℝ) : ℝ :=
  ∑ x : G, f x * g x

/-- The averaging (Markov) operator associated to a generator set `S`.
Maps `f : G → ℝ` to the function `x ↦ (1/|S|) ∑_{s ∈ S} f(x * s)`. -/
noncomputable def avgOp {G : Type*} [Group G] [Fintype G]
    (S : Finset G) (f : G → ℝ) (x : G) : ℝ :=
  (↑S.card : ℝ)⁻¹ * ∑ s ∈ S, f (x * s)

/-- A function is **harmonic** (a fixed point of the averaging operator). -/
def IsHarmonicOn {G : Type*} [Group G] [Fintype G]
    (S : Finset G) (f : G → ℝ) : Prop :=
  ∀ x : G, f x = avgOp S f x

/-- A function is mean-zero over the group. -/
def IsMeanZeroOn {G : Type*} [Fintype G] (f : G → ℝ) : Prop :=
  ∑ x : G, f x = 0

/-- The `L²` norm squared of a function over a finite group. -/
noncomputable def l2NormSq' {G : Type*} [Fintype G]
    (f : G → ℝ) : ℝ :=
  ∑ x : G, f x ^ 2

/-- The **Dirichlet energy** of a function `f : G → ℝ` with respect to a
generator set `S`. Measures the total variation across Cayley graph edges:
  E(f) = (1/|S|) ∑_x ∑_{s ∈ S} (f(x) - f(xs))² -/
noncomputable def DirichletEnergy {G : Type*} [Group G] [Fintype G]
    (S : Finset G) (f : G → ℝ) : ℝ :=
  (↑S.card : ℝ)⁻¹ * ∑ x : G, ∑ s ∈ S, (f x - f (x * s)) ^ 2

/-- The spectral gap: infimum of `E(f)/‖f‖²` over nonzero mean-zero functions.
For finite groups, this equals `1 - λ₂` where `λ₂` is the second-largest
eigenvalue of the averaging operator.

Defined as `sInf` of the image set to avoid issues with ℝ's
`ConditionallyCompleteLattice` and conditional `iInf`. -/
noncomputable def spectralGap' {G : Type*} [Group G] [Fintype G] [DecidableEq G]
    (S : Finset G) : ℝ :=
  sInf (DirichletEnergy S '' {f : G → ℝ | IsMeanZeroOn f ∧ l2NormSq' f = 1})