import Pythagorean.FiberStructure

/-!
# The exact size of the identity fibre of the unlabeled product

`Pythagorean.uprod_fiber_one_ncard` computes the fibre of `uprod` over the identity triple
for families of length two: it has exactly four elements.  Here we compute it in *every*
length: the fibre over `1` of the length-`n+1` unlabeled product has exactly `4 ^ n`
elements.

The proof is a chain of identifications.  A family with product `1` consists of units
(`mem_fiber_one_pow_rotI`), the units form the cyclic group of order four generated by the
quarter turn `rotI`, so such a family is the same thing as a vector `v : Fin (n+1) → ZMod 4`
of rotation exponents, and the product condition says exactly `∑ v = 0`.  Finally, the
sum-zero hyperplane in `(ZMod 4)^{n+1}` has `4 ^ n` points.

## Main results

* `Pythagorean.rotPow_bijective_on_fiber` : the exponent parametrisation of the fibre.
* `Pythagorean.card_sum_zero_vectors` : `#{v : Fin (n+1) → ZMod 4 | ∑ v = 0} = 4 ^ n`.
* `Pythagorean.uprod_fiber_one_ncard_general` :
  `Set.ncard {f : Fin (n+1) → PTriple | uprod f = 1} = 4 ^ n`.
-/

namespace Pythagorean

open PTriple

/-! ## Powers of the quarter turn -/

lemma rotI_pow_mod (m : ℕ) : rotI ^ m = rotI ^ (m % 4) := by
  conv_lhs => rw [← Nat.div_add_mod m 4]
  rw [pow_add, pow_mul, rotI_pow_four, one_pow, one_mul]

lemma rotI_pow_eq_one_iff (m : ℕ) : rotI ^ m = 1 ↔ 4 ∣ m := by
  constructor
  · intro h
    rw [rotI_pow_mod] at h
    have hlt : m % 4 < 4 := Nat.mod_lt _ (by norm_num)
    have h1 : rotI ^ 1 ≠ 1 := by
      rw [pow_one]
      intro he
      have : (0 : ℤ) = 1 := by simpa [rotI] using congrArg PTriple.a he
      norm_num at this
    have h3 : rotI ^ 3 ≠ 1 := by
      rw [rotI_cube]
      intro he
      have : (0 : ℤ) = 1 := by simpa [rotNegI] using congrArg PTriple.a he
      norm_num at this
    interval_cases hm : (m % 4)
    · exact Nat.dvd_of_mod_eq_zero hm
    · exact absurd h h1
    · exact absurd h rotI_sq_ne_one
    · exact absurd h h3
  · rintro ⟨k, rfl⟩
    rw [pow_mul, rotI_pow_four, one_pow]

/-- The rotation attached to an exponent in `ZMod 4`. -/
def rotPow (k : ZMod 4) : PTriple := rotI ^ k.val

@[simp] lemma rotPow_zero : rotPow 0 = 1 := by simp [rotPow]

lemma rotPow_natCast (m : ℕ) : rotPow (m : ZMod 4) = rotI ^ m := by
  rw [rotPow, ZMod.val_natCast, ← rotI_pow_mod]

lemma rotPow_eq_one_iff (k : ZMod 4) : rotPow k = 1 ↔ k = 0 := by
  constructor
  · intro h
    have h4 : 4 ∣ k.val := (rotI_pow_eq_one_iff k.val).mp h
    have hlt : k.val < 4 := ZMod.val_lt k
    have : k.val = 0 := by omega
    rw [← ZMod.natCast_zmod_val k, this]
    simp
  · rintro rfl; simp

lemma rotPow_injective : Function.Injective rotPow := by
  intro k l h
  have hk : k.val < 4 := ZMod.val_lt k
  have hl : l.val < 4 := ZMod.val_lt l
  have hmod : rotI ^ k.val = rotI ^ l.val := h
  -- compare the four possible values directly
  have : k.val = l.val := by
    interval_cases hk' : k.val <;> interval_cases hl' : l.val <;>
      first
        | rfl
        | (exfalso
           revert hmod
           simp [rotI_sq, rotI_cube, pow_succ, rotI, rotNegOne, rotNegI, PTriple.ext_iff])
  rw [← ZMod.natCast_zmod_val k, ← ZMod.natCast_zmod_val l, this]

/-! ## The exponent parametrisation of the fibre -/

lemma uprod_rotPow {n : ℕ} (v : Fin n → ZMod 4) :
    uprod (fun i => rotPow (v i)) = rotPow (∑ i, v i) := by
  have h1 : uprod (fun i => rotPow (v i)) = rotI ^ (∑ i, (v i).val) := by
    unfold uprod rotPow
    exact Finset.prod_pow_eq_pow_sum _ _ _
  have h2 : ((∑ i, (v i).val : ℕ) : ZMod 4) = ∑ i, v i := by
    push_cast
    exact Finset.sum_congr rfl fun i _ => ZMod.natCast_zmod_val (v i)
  rw [h1, ← rotPow_natCast, h2]

/-- **The fibre over the identity is parametrised by sum-zero exponent vectors.** -/
theorem rotPow_bijective_on_fiber {n : ℕ} :
    Function.Bijective
      (fun v : {v : Fin n → ZMod 4 // ∑ i, v i = 0} =>
        (⟨fun i => rotPow (v.1 i), by rw [uprod_rotPow, v.2, rotPow_zero]⟩ :
          {f : Fin n → PTriple // uprod f = 1})) := by
  constructor
  · rintro ⟨v, hv⟩ ⟨w, hw⟩ h
    have hfun := congrArg Subtype.val h
    refine Subtype.ext (funext fun i => rotPow_injective ?_)
    exact congrFun hfun i
  · rintro ⟨f, hf⟩
    choose k hk using fun i => mem_fiber_one_pow_rotI f hf i
    refine ⟨⟨fun i => ((k i : ℕ) : ZMod 4), ?_⟩, ?_⟩
    · -- the exponents sum to zero because the product is the identity
      have hfeq : f = fun i => rotPow ((k i : ℕ) : ZMod 4) := by
        funext i; rw [rotPow_natCast, hk i]
      have : rotPow (∑ i, ((k i : ℕ) : ZMod 4)) = 1 := by
        rw [← uprod_rotPow, ← hfeq, hf]
      exact (rotPow_eq_one_iff _).mp this
    · refine Subtype.ext (funext fun i => ?_)
      dsimp only
      rw [rotPow_natCast, hk i]

/-! ## Counting sum-zero vectors -/

/-- Deleting the last coordinate identifies the sum-zero hyperplane of `(ZMod 4)^{n+1}` with
`(ZMod 4)^n`. -/
def sumZeroEquiv (n : ℕ) :
    {v : Fin (n + 1) → ZMod 4 // ∑ i, v i = 0} ≃ (Fin n → ZMod 4) where
  toFun v := fun i => v.1 i.castSucc
  invFun w := ⟨Fin.snoc w (-(∑ i, w i)), by
    rw [Fin.sum_univ_castSucc]
    simp [Fin.snoc_castSucc, Fin.snoc_last]⟩
  left_inv := by
    rintro ⟨v, hv⟩
    refine Subtype.ext (funext fun i => ?_)
    refine Fin.lastCases ?_ ?_ i
    · dsimp only
      rw [Fin.snoc_last]
      rw [Fin.sum_univ_castSucc] at hv
      linear_combination (norm := ring_nf) -hv
    · intro j
      dsimp only
      rw [Fin.snoc_castSucc]
  right_inv := by
    intro w
    funext i
    simp [Fin.snoc_castSucc]

theorem card_sum_zero_vectors (n : ℕ) :
    Nat.card {v : Fin (n + 1) → ZMod 4 // ∑ i, v i = 0} = 4 ^ n := by
  rw [Nat.card_congr (sumZeroEquiv n)]
  simp

/-! ## The count -/

/-- **The identity fibre of the unlabeled product has exactly `4 ^ n` elements** in length
`n + 1`.  The redundancy of the product is therefore exactly the order of the Gaussian
rotation group raised to the number of free slots. -/
theorem uprod_fiber_one_ncard_general (n : ℕ) :
    Set.ncard {f : Fin (n + 1) → PTriple | uprod f = 1} = 4 ^ n := by
  have h1 : Nat.card {f : Fin (n + 1) → PTriple // uprod f = 1} = 4 ^ n := by
    rw [Nat.card_congr (Equiv.ofBijective _ rotPow_bijective_on_fiber).symm,
      card_sum_zero_vectors]
  rw [← Nat.card_coe_set_eq]
  exact h1

end Pythagorean