/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Cubical Semantics: the cubical circle and torus

This file gives a set-level ("0-truncated") surrogate for two basic higher inductive
types — the circle `S¹` and the torus `T²` — built by *quotient operations* on the
unit interval, following the cubical philosophy in which spaces are generated by
*interval maps* (paths) and the gluing data is recorded by their *endpoints*.

The constructions are purely algorithmic: every map out of a generated space is
produced by a `Quot.lift` recursor, and the gluing relations are exactly the
endpoint identifications of the interval.  The build is *acyclic*: the cubical
interval is defined first, the circle is the quotient of the interval by gluing its
two endpoints, and the torus is the quotient of the square by gluing opposite edges.
No definition depends on a later one.

## Main definitions

- `CubicalSemantics.I0`, `CubicalSemantics.I1` — the two endpoints of the cubical
  interval (Mathlib's `unitInterval`).
- `CubicalSemantics.Circle` — the cubical circle, `unitInterval` quotiented by the
  relation gluing `0` to `1`.
- `CubicalSemantics.Circle.loop` — the canonical interval map (loop) into the circle.
- `CubicalSemantics.Circle.rec'` — the recursion principle: an interval map whose two
  endpoints agree induces a map out of the circle.
- `CubicalSemantics.Torus` — the cubical torus, the square `unitInterval × unitInterval`
  quotiented by gluing opposite edges.
- `CubicalSemantics.Torus.rec'` — the recursion principle for the torus.
- `CubicalSemantics.torusEquivCircles` — the torus is `Circle × Circle`.

## Main results

- `Circle.loop_zero`, `Circle.loop_one` — the loop sends both endpoints to the base
  point (endpoint behaviour).
- `Circle.rec_base`, `Circle.rec_loop`, `Circle.rec_unique` — computation and
  uniqueness rules for the circle recursor.
- `Torus.rec_mk`, `Torus.rec_unique` — computation and uniqueness rules for the torus
  recursor.
- `torusEquivCircles` — `Torus ≃ Circle × Circle`.
-/

open unitInterval

namespace CubicalSemantics

/-! ## The cubical interval

We use Mathlib's `unitInterval` as the cubical interval.  Its two endpoints are the
points `0` and `1`; everything below is generated from these. -/

/-- The `0` endpoint of the cubical interval. -/
def I0 : unitInterval := 0

/-- The `1` endpoint of the cubical interval. -/
def I1 : unitInterval := 1

/-- The two endpoints of the cubical interval are distinct. -/
theorem endpoints_ne : I0 ≠ I1 := by
  simp [I0, I1, unitInterval]

/-! ## The cubical circle

The circle is the quotient of the interval that glues its two endpoints together. -/

/-- The gluing relation for the circle: identify the two endpoints `0` and `1`. -/
inductive CircleRel : unitInterval → unitInterval → Prop where
  | glue : CircleRel 0 1

/-- The cubical circle: the unit interval with its endpoints glued. -/
def Circle : Type := Quot CircleRel

namespace Circle

/-- The base point of the circle, the common image of the two endpoints. -/
def base : Circle := Quot.mk _ 0

/-- The canonical interval map (loop) into the circle. -/
def loop (t : unitInterval) : Circle := Quot.mk _ t

/-- Endpoint behaviour: the loop sends the `0` endpoint to the base point. -/
theorem loop_zero : loop 0 = base := rfl

/-- Endpoint behaviour: the loop sends the `1` endpoint to the base point. -/
theorem loop_one : loop 1 = base := (Quot.sound CircleRel.glue).symm

/-- The loop is constant on the endpoints: both map to the base point. -/
theorem loop_endpoints : loop 0 = loop 1 := by
  rw [loop_zero, loop_one]

/-- **Recursion principle for the circle.** An interval map `f` whose two endpoints
agree (`f 0 = f 1`) induces a map out of the circle. -/
def rec' {X : Type v} (f : unitInterval → X) (h : f 0 = f 1) : Circle → X :=
  Quot.lift f (fun a b r => by cases r; exact h)

/-- Computation rule at the base point. -/
@[simp]
theorem rec_base {X : Type v} (f : unitInterval → X) (h : f 0 = f 1) :
    rec' f h base = f 0 := rfl

/-- Computation rule along the loop. -/
@[simp]
theorem rec_loop {X : Type v} (f : unitInterval → X) (h : f 0 = f 1) (t : unitInterval) :
    rec' f h (loop t) = f t := rfl

/-- Uniqueness of the recursor: any map agreeing with `f` along the loop equals the
recursor. -/
theorem rec_unique {X : Type v} (f : unitInterval → X) (h : f 0 = f 1)
    (g : Circle → X) (hg : ∀ t, g (loop t) = f t) : g = rec' f h := by
  funext x
  induction x using Quot.ind with
  | mk t => exact hg t

/-- Every point of the circle is the loop at some interval point. -/
theorem loop_surjective : Function.Surjective loop := by
  intro x
  induction x using Quot.ind with
  | mk t => exact ⟨t, rfl⟩

end Circle

/-! ## The cubical torus

The torus is the quotient of the square that glues opposite edges: the bottom edge to
the top edge, and the left edge to the right edge. -/

/-- The gluing relation for the torus: identify opposite edges of the square. -/
inductive TorusRel : (unitInterval × unitInterval) → (unitInterval × unitInterval) → Prop where
  | horiz (x : unitInterval) : TorusRel (x, 0) (x, 1)
  | vert  (y : unitInterval) : TorusRel (0, y) (1, y)

/-- The cubical torus: the square with opposite edges glued. -/
def Torus : Type := Quot TorusRel

namespace Torus

/-- The canonical square map into the torus. -/
def mk (p : unitInterval × unitInterval) : Torus := Quot.mk _ p

/-- Endpoint behaviour on the horizontal edges: the bottom and top edges are glued. -/
theorem mk_horiz (x : unitInterval) : mk (x, 0) = mk (x, 1) :=
  Quot.sound (TorusRel.horiz x)

/-- Endpoint behaviour on the vertical edges: the left and right edges are glued. -/
theorem mk_vert (y : unitInterval) : mk (0, y) = mk (1, y) :=
  Quot.sound (TorusRel.vert y)

/-- **Recursion principle for the torus.** A square map `f` that agrees on opposite
edges induces a map out of the torus. -/
def rec' {X : Type v} (f : unitInterval × unitInterval → X)
    (hh : ∀ x, f (x, 0) = f (x, 1)) (hv : ∀ y, f (0, y) = f (1, y)) : Torus → X :=
  Quot.lift f (fun a b r => by
    cases r with
    | horiz x => exact hh x
    | vert y => exact hv y)

/-- Computation rule for the torus recursor. -/
@[simp]
theorem rec_mk {X : Type v} (f : unitInterval × unitInterval → X)
    (hh : ∀ x, f (x, 0) = f (x, 1)) (hv : ∀ y, f (0, y) = f (1, y)) (p : unitInterval × unitInterval) :
    rec' f hh hv (mk p) = f p := rfl

/-- Uniqueness of the torus recursor. -/
theorem rec_unique {X : Type v} (f : unitInterval × unitInterval → X)
    (hh : ∀ x, f (x, 0) = f (x, 1)) (hv : ∀ y, f (0, y) = f (1, y))
    (g : Torus → X) (hg : ∀ p, g (mk p) = f p) : g = rec' f hh hv := by
  funext x
  induction x using Quot.ind with
  | mk p => exact hg p

/-- The square map is surjective onto the torus. -/
theorem mk_surjective : Function.Surjective mk := by
  intro x
  induction x using Quot.ind with
  | mk p => exact ⟨p, rfl⟩

/-- The torus, as the product of two circles, by sending a square point to the pair of
its circle coordinates. -/
noncomputable def toCircles : Torus → Circle × Circle :=
  rec' (fun p => (Circle.loop p.1, Circle.loop p.2))
    (fun x => by simp [Circle.loop_zero, Circle.loop_one])
    (fun y => by simp [Circle.loop_zero, Circle.loop_one])

/-- The inverse map from `Circle × Circle` to the torus. -/
def ofCircles : Circle × Circle → Torus := fun p =>
  Circle.rec'
    (fun x => Circle.rec' (fun y => mk (x, y)) (mk_horiz x))
    (by
      funext c
      induction c using Quot.ind with
      | mk y => exact mk_vert y)
    p.1 p.2

theorem left_inv (t : Torus) : ofCircles (toCircles t) = t := by
  induction t using Quot.ind with
  | mk p => rfl

theorem right_inv (p : Circle × Circle) : toCircles (ofCircles p) = p := by
  obtain ⟨c1, c2⟩ := p
  induction c1 using Quot.ind with
  | mk x =>
    induction c2 using Quot.ind with
    | mk y => rfl

end Torus

/-- **The cubical torus is the product of two cubical circles.** -/
noncomputable def torusEquivCircles : Torus ≃ Circle × Circle where
  toFun := Torus.toCircles
  invFun := Torus.ofCircles
  left_inv := Torus.left_inv
  right_inv := Torus.right_inv

end CubicalSemantics