import numpy as np
import matplotlib.pyplot as plt
from math import gcd

def fib(n: int) -> int:
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

def entry_point(m: int) -> int:
    if m == 1:
        return 1
    a, b, k = 0, 1, 0
    while True:
        k += 1
        a, b = b, (a + b) % m
        if a == 0:
            return k

MAX_M, MAX_N = 24, 60
grid = np.zeros((MAX_M, MAX_N), dtype=float)
for mi, m in enumerate(range(1, MAX_M + 1)):
    for ni, n in enumerate(range(1, MAX_N + 1)):
        grid[mi, ni] = 1.0 if fib(n) % m == 0 else 0.0

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
ax1.imshow(grid, aspect="auto", origin="lower", cmap="viridis",
           extent=[1, MAX_N, 1, MAX_M])
ax1.set_xlabel("index n")
ax1.set_ylabel("modulus m")
ax1.set_title("m | F(n):  periodic stripes generated by entry(m)")

ms = list(range(1, MAX_M + 1))
ax2.bar(ms, [entry_point(m) for m in ms], color="#3b6")
ax2.set_xlabel("modulus m")
ax2.set_ylabel("entry(m)  (rank of apparition)")
ax2.set_title("Rank of apparition profile")
plt.tight_layout()
plt.savefig("fibonacci_lattice.png", dpi=150)
print("Saved fibonacci_lattice.png")
