/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Tropical AC Canonical Forms: A Certified Decision Procedure

This file implements a certified canonical-form normalizer for the
commutative-associative (AC) fragment of tropical (min-plus) expressions.

## Main results

- `normalize_ca_sound`: normalization preserves evaluation semantics
- `normalize_ca_idempotent`: normalization is idempotent
- `normalize_ca_complete`: AC-equivalent expressions normalize to the same form

Together these constitute a **certified decision procedure** for AC equivalence
of tropical expressions: two expressions are AC-equivalent if and only if they
have the same normal form.

## Why completeness is only for the AC fragment

The full tropical semiring satisfies additional identities:
- Distributivity: `a + min b c = min (a+b) (a+c)`
- Idempotence of min: `min a a = a`

These identities create semantic equalities not generated by AC alone. Our normalizer
is complete for the AC congruence, which captures exactly the equalities arising from
commutativity and associativity of `min` and `+`, with congruence closure.
-/

import Mathlib

open Classical

namespace TropicalACCanonical

/-! ## Expression Language -/

/-- A tropical expression over ℝ with constants, variables, min, and addition. -/
inductive TropExpr where
  | const : ℝ → TropExpr
  | var   : ℕ → TropExpr
  | tmin  : TropExpr → TropExpr → TropExpr
  | add   : TropExpr → TropExpr → TropExpr

open TropExpr

noncomputable instance : DecidableEq TropExpr := fun a b => Classical.dec (a = b)

/-! ## Semantic Evaluation -/

/-- Evaluate a tropical expression in environment `σ`. -/
noncomputable def eval (σ : ℕ → ℝ) : TropExpr → ℝ
  | .const r   => r
  | .var n     => σ n
  | .tmin a b  => min (eval σ a) (eval σ b)
  | .add a b   => eval σ a + eval σ b

/-! ## AC Equivalence Relation -/

/-- The AC congruence on tropical expressions: the smallest congruence
    containing commutativity and associativity of both `tmin` and `add`. -/
inductive ACEquiv : TropExpr → TropExpr → Prop
  | refl  : ∀ e, ACEquiv e e
  | symm  : ∀ {e₁ e₂}, ACEquiv e₁ e₂ → ACEquiv e₂ e₁
  | trans : ∀ {e₁ e₂ e₃}, ACEquiv e₁ e₂ → ACEquiv e₂ e₃ → ACEquiv e₁ e₃
  | tmin_comm  : ∀ e₁ e₂, ACEquiv (.tmin e₁ e₂) (.tmin e₂ e₁)
  | tmin_assoc : ∀ e₁ e₂ e₃,
      ACEquiv (.tmin (.tmin e₁ e₂) e₃) (.tmin e₁ (.tmin e₂ e₃))
  | add_comm  : ∀ e₁ e₂, ACEquiv (.add e₁ e₂) (.add e₂ e₁)
  | add_assoc : ∀ e₁ e₂ e₃,
      ACEquiv (.add (.add e₁ e₂) e₃) (.add e₁ (.add e₂ e₃))
  | cong_tmin : ∀ {a a' b b'}, ACEquiv a a' → ACEquiv b b' →
      ACEquiv (.tmin a b) (.tmin a' b')
  | cong_add  : ∀ {a a' b b'}, ACEquiv a a' → ACEquiv b b' →
      ACEquiv (.add a b) (.add a' b')

/-! ## Comparison / Total Order on TropExpr -/

/-- A well-founded comparison function on TropExpr. -/
noncomputable def TropExpr.cmp : TropExpr → TropExpr → Ordering
  | .const r₁, .const r₂ => if r₁ < r₂ then .lt else if r₁ = r₂ then .eq else .gt
  | .var n₁, .var n₂ => compare n₁ n₂
  | .tmin a₁ b₁, .tmin a₂ b₂ =>
      match a₁.cmp a₂ with
      | .eq => b₁.cmp b₂
      | o => o
  | .add a₁ b₁, .add a₂ b₂ =>
      match a₁.cmp a₂ with
      | .eq => b₁.cmp b₂
      | o => o
  | .const _, _ => .lt
  | .var _, .const _ => .gt
  | .var _, .tmin _ _ => .lt
  | .var _, .add _ _ => .lt
  | .tmin _ _, .const _ => .gt
  | .tmin _ _, .var _ => .gt
  | .tmin _ _, .add _ _ => .lt
  | .add _ _, .const _ => .gt
  | .add _ _, .var _ => .gt
  | .add _ _, .tmin _ _ => .gt

/-- Boolean ≤ based on cmp. -/
noncomputable def TropExpr.ble (e₁ e₂ : TropExpr) : Bool :=
  match e₁.cmp e₂ with
  | .gt => false
  | _ => true

/-! ## Flattening -/

/-- Flatten a tmin-tree into a list of non-tmin children. -/
def flattenMin : TropExpr → List TropExpr
  | .tmin a b => flattenMin a ++ flattenMin b
  | e => [e]

/-- Flatten an add-tree into a list of non-add children. -/
def flattenAdd : TropExpr → List TropExpr
  | .add a b => flattenAdd a ++ flattenAdd b
  | e => [e]

/-! ## Rebuilding from sorted lists -/

/-- Build a right-associated tmin chain from a nonempty list. -/
def buildMin : List TropExpr → TropExpr
  | [] => .const 0
  | [e] => e
  | e :: es => .tmin e (buildMin es)

/-- Build a right-associated add chain from a nonempty list. -/
def buildAdd : List TropExpr → TropExpr
  | [] => .const 0
  | [e] => e
  | e :: es => .add e (buildAdd es)

/-! ## Normalization -/

/-- Normalize a tropical expression for AC equivalence.
    Strategy: recursively normalize children, flatten same-head operators,
    sort children by the total order, and rebuild. -/
noncomputable def normalize_ca : TropExpr → TropExpr
  | .const r => .const r
  | .var n   => .var n
  | .tmin a b =>
      let a' := normalize_ca a
      let b' := normalize_ca b
      let children := flattenMin (.tmin a' b')
      let sorted := children.mergeSort TropExpr.ble
      buildMin sorted
  | .add a b =>
      let a' := normalize_ca a
      let b' := normalize_ca b
      let children := flattenAdd (.add a' b')
      let sorted := children.mergeSort TropExpr.ble
      buildAdd sorted

/-! ## List evaluation helpers -/

/-- Evaluate a list of expressions under min, folding from right. -/
noncomputable def evalMinList (σ : ℕ → ℝ) : List TropExpr → ℝ
  | [] => 0
  | [e] => eval σ e
  | e :: es => min (eval σ e) (evalMinList σ es)

/-- Evaluate a list of expressions under addition, folding from right. -/
noncomputable def evalAddList (σ : ℕ → ℝ) : List TropExpr → ℝ
  | [] => 0
  | [e] => eval σ e
  | e :: es => eval σ e + evalAddList σ es

/-! ## Nonemptiness of flatten results -/

theorem flattenMin_ne (e : TropExpr) : flattenMin e ≠ [] := by
  induction e with
  | tmin a _ iha _ =>
    simp only [flattenMin]; exact List.append_ne_nil_of_left_ne_nil iha _
  | const _ => simp [flattenMin]
  | var _ => simp [flattenMin]
  | add _ _ => simp [flattenMin]

theorem flattenAdd_ne (e : TropExpr) : flattenAdd e ≠ [] := by
  induction e with
  | add a _ iha _ =>
    simp only [flattenAdd]; exact List.append_ne_nil_of_left_ne_nil iha _
  | const _ => simp [flattenAdd]
  | var _ => simp [flattenAdd]
  | tmin _ _ => simp [flattenAdd]

/-! ## evalMinList / evalAddList cons lemmas -/

@[simp] theorem evalMinList_singleton (σ : ℕ → ℝ) (e : TropExpr) :
    evalMinList σ [e] = eval σ e := by simp [evalMinList]

@[simp] theorem evalAddList_singleton (σ : ℕ → ℝ) (e : TropExpr) :
    evalAddList σ [e] = eval σ e := by simp [evalAddList]

theorem evalMinList_cons_cons (σ : ℕ → ℝ) (e f : TropExpr) (es : List TropExpr) :
    evalMinList σ (e :: f :: es) = min (eval σ e) (evalMinList σ (f :: es)) := by
  simp [evalMinList]

theorem evalAddList_cons_cons (σ : ℕ → ℝ) (e f : TropExpr) (es : List TropExpr) :
    evalAddList σ (e :: f :: es) = eval σ e + evalAddList σ (f :: es) := by
  simp [evalAddList]

/-! ## Append lemmas -/

theorem evalMinList_append (σ : ℕ → ℝ) (l₁ l₂ : List TropExpr)
    (h₁ : l₁ ≠ []) (h₂ : l₂ ≠ []) :
    evalMinList σ (l₁ ++ l₂) = min (evalMinList σ l₁) (evalMinList σ l₂) := by
      rcases l₁ with ( _ | ⟨ e₁, _ | ⟨ e₂, l₁ ⟩ ⟩ ) <;> rcases l₂ with ( _ | ⟨ e₃, _ | ⟨ e₄, l₂ ⟩ ⟩ ) <;> simp_all +arith +decide;
      · exact?;
      · rfl;
      · induction' l₁ with l₁ ih generalizing e₁ e₂ <;> simp_all +decide [ evalMinList_cons_cons ];
        · grind;
        · grind;
      · induction' l₁ with e₅ l₁ ih generalizing e₁ e₂ e₃ e₄ l₂ <;> simp_all +arith +decide [ evalMinList_cons_cons ];
        · grind;
        · grind +qlia

theorem evalAddList_append (σ : ℕ → ℝ) (l₁ l₂ : List TropExpr)
    (h₁ : l₁ ≠ []) (h₂ : l₂ ≠ []) :
    evalAddList σ (l₁ ++ l₂) = evalAddList σ l₁ + evalAddList σ l₂ := by
      induction l₁ <;> simp_all +decide [ evalAddList ];
      induction ‹List TropExpr› <;> simp_all +decide [ evalAddList ];
      ring

/-! ## Flattening preserves semantics -/

theorem eval_flattenMin (σ : ℕ → ℝ) (e : TropExpr) :
    evalMinList σ (flattenMin e) = eval σ e := by
  induction e with
  | const r => simp [flattenMin, evalMinList, eval]
  | var n => simp [flattenMin, evalMinList, eval]
  | tmin a b iha ihb =>
    simp only [flattenMin, eval]
    rw [evalMinList_append σ _ _ (flattenMin_ne a) (flattenMin_ne b), iha, ihb]
  | add a b => simp [flattenMin, evalMinList, eval]

theorem eval_flattenAdd (σ : ℕ → ℝ) (e : TropExpr) :
    evalAddList σ (flattenAdd e) = eval σ e := by
  induction e with
  | const r => simp [flattenAdd, evalAddList, eval]
  | var n => simp [flattenAdd, evalAddList, eval]
  | add a b iha ihb =>
    simp only [flattenAdd, eval]
    rw [evalAddList_append σ _ _ (flattenAdd_ne a) (flattenAdd_ne b), iha, ihb]
  | tmin a b => simp [flattenAdd, evalAddList, eval]

/-! ## Permutation invariance -/

theorem evalMinList_perm (σ : ℕ → ℝ) {l₁ l₂ : List TropExpr}
    (hp : l₁.Perm l₂) (hne : l₁ ≠ []) :
    evalMinList σ l₁ = evalMinList σ l₂ := by
      induction' hp with l₁ l₂ hp ih;
      · -- The base case is impossible because the empty list cannot be equal to itself.
        exfalso; exact hne rfl;
      · cases l₂ <;> cases hp <;> simp_all +decide [ evalMinList_cons_cons ];
      · induction' ‹List TropExpr› with z l ih generalizing σ <;> simp_all +decide [ evalMinList ];
        · exact min_comm _ _;
        · rw [ min_left_comm ];
      · aesop

theorem evalAddList_perm (σ : ℕ → ℝ) {l₁ l₂ : List TropExpr}
    (hp : l₁.Perm l₂) (hne : l₁ ≠ []) :
    evalAddList σ l₁ = evalAddList σ l₂ := by
      have h_fold_eq_sum : ∀ l : List TropExpr, List.sum (List.map (fun e => eval σ e) l) = evalAddList σ l := by
        intro l;
        induction l <;> simp_all +decide [ evalAddList ];
        cases ‹List TropExpr› <;> simp_all +decide [ evalAddList ];
      rw [ ← h_fold_eq_sum l₁, ← h_fold_eq_sum l₂, hp.map _ |> List.Perm.sum_eq ]

/-! ## buildMin / buildAdd evaluation -/

theorem eval_buildMin_eq (σ : ℕ → ℝ) (l : List TropExpr) (hne : l ≠ []) :
    eval σ (buildMin l) = evalMinList σ l := by
      induction' l with e l ih;
      · grind;
      · cases l <;> simp_all +decide [ buildMin ];
        convert congr_arg₂ ( fun x y => min x y ) rfl ih using 1

theorem eval_buildAdd_eq (σ : ℕ → ℝ) (l : List TropExpr) (hne : l ≠ []) :
    eval σ (buildAdd l) = evalAddList σ l := by
      rcases l with ( _ | ⟨ e, _ | ⟨ f, l ⟩ ⟩ ) <;> simp_all +decide [ evalAddList ];
      · rfl;
      · induction' l with l ih generalizing e f <;> simp_all +decide [ evalAddList ];
        · exact show eval σ ( e.add f ) = eval σ e + eval σ f from rfl;
        · convert congr_arg₂ ( · + · ) rfl ( ‹∀ e f : TropExpr, eval σ ( buildAdd ( e :: f :: ih ) ) = eval σ e + evalAddList σ ( f :: ih ) › f l ) using 1

/-! ## mergeSort helpers -/

theorem mergeSort_perm_self (l : List TropExpr) :
    (l.mergeSort TropExpr.ble).Perm l :=
  List.mergeSort_perm l _

theorem mergeSort_ne (l : List TropExpr) (hne : l ≠ []) :
    l.mergeSort TropExpr.ble ≠ [] := by
  intro h
  have hlen := (mergeSort_perm_self l).length_eq
  rw [h] at hlen
  simp at hlen
  exact hne (List.eq_nil_of_length_eq_zero hlen.symm)

/-! ## Main Theorems -/

/-
**Soundness**: normalization preserves evaluation semantics.
-/
theorem normalize_ca_sound (σ : ℕ → ℝ) (e : TropExpr) :
    eval σ (normalize_ca e) = eval σ e := by
      induction' e using TropExpr.recOn;
      · rfl;
      · rfl;
      · unfold normalize_ca;
        rename_i a b ha hb;
        convert eval_buildMin_eq σ _ _ using 1;
        · convert eval_flattenMin σ ( .tmin ( normalize_ca a ) ( normalize_ca b ) ) |> Eq.symm using 1;
          · rw [ show eval σ ( a.tmin b ) = min ( eval σ a ) ( eval σ b ) by rfl, show eval σ ( ( normalize_ca a ).tmin ( normalize_ca b ) ) = min ( eval σ ( normalize_ca a ) ) ( eval σ ( normalize_ca b ) ) by rfl, ha, hb ];
          · apply evalMinList_perm;
            · exact?;
            · exact mergeSort_ne _ ( flattenMin_ne _ );
        · exact mergeSort_ne _ ( flattenMin_ne _ );
      · unfold normalize_ca;
        rw [ eval_buildAdd_eq ];
        · rename_i a b ha hb;
          convert evalAddList_perm σ ( mergeSort_perm_self _ ) _ using 1;
          · rw [ eval_flattenAdd ];
            exact show eval σ a + eval σ b = eval σ ( normalize_ca a ) + eval σ ( normalize_ca b ) from by rw [ ha, hb ] ;
          · grind +suggestions;
        · exact mergeSort_ne _ ( flattenAdd_ne _ )

/-
**ACEquiv is sound for eval**: AC-equivalent expressions have the same semantics.
-/
theorem ACEquiv_sound (σ : ℕ → ℝ) {e₁ e₂ : TropExpr}
    (h : ACEquiv e₁ e₂) : eval σ e₁ = eval σ e₂ := by
      induction h;
      all_goals try linarith;
      all_goals try { exact min_comm _ _ };
      · exact min_assoc _ _ _;
      · exact add_comm _ _;
      · exact add_assoc _ _ _;
      · rename_i a b c d ha hb ih₁ ih₂;
        exact congr_arg₂ ( · ⊓ · ) ih₁ ih₂;
      · exact congr_arg₂ ( · + · ) ‹_› ‹_›

/-! ## Flatten-of-normalized helpers for completeness -/

/-
No element of flattenMin is a tmin node.
-/
theorem flattenMin_no_tmin (e : TropExpr) :
    ∀ x ∈ flattenMin e, ∀ a b, x ≠ .tmin a b := by
      intro x hx a b ih;
      induction' e with e₁ e₂ ih₁ ih₂ generalizing a b;
      · cases hx;
        · cases ih;
        · contradiction;
      · grind +locals;
      · unfold flattenMin at hx; aesop;
      · unfold flattenMin at hx; aesop;

/-
No element of flattenAdd is an add node.
-/
theorem flattenAdd_no_add (e : TropExpr) :
    ∀ x ∈ flattenAdd e, ∀ a b, x ≠ .add a b := by
      intro x hx a b;
      induction' e with e₁ e₂ ih₁ ih₂ generalizing x <;> simp_all +decide [ flattenAdd ];
      grind

/-
flattenMin of buildMin on a list with no tmin elements returns that list.
-/
theorem flattenMin_buildMin (l : List TropExpr) (hne : l ≠ [])
    (hno : ∀ x ∈ l, ∀ a b, x ≠ .tmin a b) :
    flattenMin (buildMin l) = l := by
      rcases l with ( _ | ⟨ x, _ | ⟨ y, l ⟩ ⟩ ) <;> simp_all +decide;
      · cases x <;> tauto;
      · induction' l with z l ih generalizing x y <;> simp_all +decide [ buildMin ];
        · -- By definition of `flattenMin`, we have `flattenMin (x.tmin y) = flattenMin x ++ flattenMin y`.
          have h_flattenMin : flattenMin (x.tmin y) = flattenMin x ++ flattenMin y := by
            exact?;
          -- By definition of `flattenMin`, we have `flattenMin x = [x]` and `flattenMin y = [y]`.
          have h_flattenMin_x : flattenMin x = [x] := by
            cases x <;> aesop
          have h_flattenMin_y : flattenMin y = [y] := by
            cases y <;> aesop;
          aesop;
        · convert congr_arg₂ ( · ++ · ) ( show flattenMin x = [ x ] from ?_ ) ( ih y z hno.2.1 hno.2.2.1 ) using 1;
          cases x <;> tauto

/-
flattenAdd of buildAdd on a list with no add elements returns that list.
-/
theorem flattenAdd_buildAdd (l : List TropExpr) (hne : l ≠ [])
    (hno : ∀ x ∈ l, ∀ a b, x ≠ .add a b) :
    flattenAdd (buildAdd l) = l := by
      -- By definition of `buildAdd`, we can split into cases based on the length of `l`.
      cases' l with e l';
      · contradiction;
      · induction l' <;> simp_all +decide [ buildAdd, flattenAdd ];
        rename_i k hk; induction k <;> simp_all +decide [ buildAdd, flattenAdd ] ;

/-! ## No tmin/add in normalized children -/

theorem normalize_ca_flattenMin_no_tmin (e : TropExpr) :
    ∀ x ∈ flattenMin (normalize_ca e), ∀ a b, x ≠ .tmin a b := by
      convert flattenMin_no_tmin _ using 1

theorem normalize_ca_flattenAdd_no_add (e : TropExpr) :
    ∀ x ∈ flattenAdd (normalize_ca e), ∀ a b, x ≠ .add a b := by
      convert flattenAdd_no_add _

/-! ## mergeSort determinism -/

/-
cmp is reflexive: cmp e e = .eq
-/
theorem cmp_refl (e : TropExpr) : e.cmp e = .eq := by
  induction e <;> simp_all +decide [ TropExpr.cmp ]

/-
cmp is antisymmetric: if cmp returns .eq, the expressions are equal
-/
theorem cmp_eq_iff (e₁ e₂ : TropExpr) : e₁.cmp e₂ = .eq ↔ e₁ = e₂ := by
  constructor;
  · induction' e₁ with a b ih_a ih_b generalizing e₂ <;> induction' e₂ with c d ih_c ih_d <;> simp_all +decide [ TropExpr.cmp ];
    · cases h : ih_a.cmp ih_c <;> simp_all +decide;
      aesop;
    · rename_i a b c d ha hb hc hd;
      cases h : a.cmp ha <;> simp_all +decide;
      exact fun h' => ⟨ c _ h, d _ h' ⟩;
  · rintro rfl; exact?

/-
cmp is the flip of its reverse
-/
theorem cmp_symm (e₁ e₂ : TropExpr) :
    e₁.cmp e₂ = .lt ↔ e₂.cmp e₁ = .gt := by
      revert e₁ e₂;
      -- We can prove this by induction on the structure of the expressions.
      have h_ind : ∀ e₁ e₂ : TropExpr, (e₁.cmp e₂ = .lt ↔ e₂.cmp e₁ = .gt) ∧ (e₁.cmp e₂ = .gt ↔ e₂.cmp e₁ = .lt) ∧ (e₁.cmp e₂ = .eq ↔ e₂.cmp e₁ = .eq) := by
        intros e₁ e₂
        induction' e₁ with e₁₁ e₁₂ ih generalizing e₂;
        · induction' e₂ with e₂₁ e₂₂ ih;
          · unfold TropExpr.cmp; simp +decide [ lt_asymm ] ;
            grind;
          · exact ⟨ by tauto, by tauto, by tauto ⟩;
          · unfold TropExpr.cmp; aesop;
          · exact ⟨ by tauto, by tauto, by tauto ⟩;
        · induction' e₂ with e₂₁ e₂₂ ih;
          · exact ⟨ by tauto, by tauto, by tauto ⟩;
          · unfold TropExpr.cmp; simp +decide [ compare ] ;
            unfold compareOfLessAndEq; simp +decide [ lt_asymm ] ;
            grind;
          · grind +locals;
          · grind +locals;
        · cases e₂ <;> simp_all +decide [ TropExpr.cmp ];
          rename_i k hk;
          cases h : ih.cmp k <;> cases h' : k.cmp ih <;> simp_all +decide;
        · unfold TropExpr.cmp; aesop;
      exact fun e₁ e₂ => h_ind e₁ e₂ |>.1

/-
ble is total
-/
theorem ble_total (e₁ e₂ : TropExpr) :
    e₁.ble e₂ = true ∨ e₂.ble e₁ = true := by
      simp only [TropExpr.ble]
      cases h : e₁.cmp e₂ <;> simp
      · have := (cmp_symm e₂ e₁).mpr h
        simp [this]

/-
ble is antisymmetric
-/
theorem ble_antisymm {e₁ e₂ : TropExpr}
    (h₁ : e₁.ble e₂ = true) (h₂ : e₂.ble e₁ = true) : e₁ = e₂ := by
      apply (cmp_eq_iff e₁ e₂).mp;
      -- By definition of cmp, if e₁.cmp e₂ is not gt, then it must be either lt or eq.
      have h_cases : e₁.cmp e₂ = .lt ∨ e₁.cmp e₂ = .eq := by
        cases h : e₁.cmp e₂ <;> simp_all +decide;
        unfold TropExpr.ble at * ; aesop;
      cases h_cases <;> simp_all +decide [ TropExpr.ble ];
      rw [ cmp_symm ] at * ; aesop ( simp_config := { decide := true } ) ;

/-- The tag of each constructor determines cross-constructor ordering -/
def TropExpr.tag : TropExpr → ℕ
  | .const _ => 0
  | .var _ => 1
  | .tmin _ _ => 2
  | .add _ _ => 3

/-
cmp agrees with tag ordering for different constructors
-/
theorem cmp_of_tag_lt {e₁ e₂ : TropExpr}
    (h : e₁.tag < e₂.tag) : e₁.cmp e₂ = .lt := by
      rcases e₁ with ( _ | _ | _ | _ ) <;> rcases e₂ with ( _ | _ | _ | _ ) <;> norm_cast

theorem cmp_of_tag_gt {e₁ e₂ : TropExpr}
    (h : e₁.tag > e₂.tag) : e₁.cmp e₂ = .gt := by
      rcases e₁ with ( _ | _ | _ | _ ) <;> rcases e₂ with ( _ | _ | _ | _ ) <;> norm_cast

/-
If cmp ≠ .gt then tag ≤
-/
theorem tag_le_of_cmp_ne_gt {e₁ e₂ : TropExpr}
    (h : e₁.cmp e₂ ≠ .gt) : e₁.tag ≤ e₂.tag := by
      cases lt_or_ge ( e₁.tag ) ( e₂.tag ) <;> simp_all +decide;
      · linarith;
      · cases lt_or_eq_of_le ‹_› <;> simp_all +decide [ cmp_of_tag_lt, cmp_of_tag_gt ]

/-
cmp transitivity for const
-/
theorem cmp_trans_const (r₁ r₂ r₃ : ℝ)
    (h₁ : (TropExpr.const r₁).cmp (.const r₂) ≠ .gt)
    (h₂ : (TropExpr.const r₂).cmp (.const r₃) ≠ .gt) :
    (TropExpr.const r₁).cmp (.const r₃) ≠ .gt := by
      unfold TropExpr.cmp at *;
      grind

/-
cmp transitivity for var
-/
theorem cmp_trans_var (n₁ n₂ n₃ : ℕ)
    (h₁ : (TropExpr.var n₁).cmp (.var n₂) ≠ .gt)
    (h₂ : (TropExpr.var n₂).cmp (.var n₃) ≠ .gt) :
    (TropExpr.var n₁).cmp (.var n₃) ≠ .gt := by
      simp_all +decide [ TropExpr.cmp ];
      grind +suggestions

/-
cmp transitivity for lexicographic (tmin or add)
-/
theorem cmp_trans_lex {a₁ b₁ a₂ b₂ a₃ b₃ : TropExpr}
    (iha : a₁.cmp a₂ ≠ .gt → a₂.cmp a₃ ≠ .gt → a₁.cmp a₃ ≠ .gt)
    (ihb : b₁.cmp b₂ ≠ .gt → b₂.cmp b₃ ≠ .gt → b₁.cmp b₃ ≠ .gt)
    (h₁ : (match a₁.cmp a₂ with | .eq => b₁.cmp b₂ | o => o) ≠ .gt)
    (h₂ : (match a₂.cmp a₃ with | .eq => b₂.cmp b₃ | o => o) ≠ .gt) :
    (match a₁.cmp a₃ with | .eq => b₁.cmp b₃ | o => o) ≠ .gt := by
      cases h : a₁.cmp a₂ <;> cases h' : a₂.cmp a₃ <;> simp +decide [ h, h' ] at h₁ h₂ ⊢
      -- (.lt, .lt)
      · have hne := iha (by simp [h]) (by simp [h'])
        cases h'' : a₁.cmp a₃ <;> simp +decide [h'']
        · -- a₁.cmp a₃ = .eq, so a₁ = a₃
          have := (cmp_eq_iff a₁ a₃).mp h''
          subst this
          -- then a₂.cmp a₃ = a₂.cmp a₁ and cmp_symm gives .gt, contradiction
          have := (cmp_symm a₁ a₂).mp h
          simp_all
        · exact absurd h'' hne
      -- (.lt, .eq)
      · have := (cmp_eq_iff a₂ a₃).mp h'
        subst this; simp [h]
      -- (.eq, .lt)
      · have := (cmp_eq_iff a₁ a₂).mp h
        subst this; simp [h']
      -- (.eq, .eq)
      · have ha₁ := (cmp_eq_iff a₁ a₂).mp h
        have ha₂ := (cmp_eq_iff a₂ a₃).mp h'
        subst ha₁; subst ha₂
        simp [cmp_refl]
        exact ihb h₁ h₂

/-- Expression size for well-founded induction -/
def TropExpr.sz : TropExpr → ℕ
  | .const _ => 1
  | .var _   => 1
  | .tmin a b => a.sz + b.sz + 1
  | .add a b  => a.sz + b.sz + 1

/-- cmp is transitive -/
theorem cmp_trans {e₁ e₂ e₃ : TropExpr}
    (h₁ : e₁.cmp e₂ ≠ .gt) (h₂ : e₂.cmp e₃ ≠ .gt) : e₁.cmp e₃ ≠ .gt := by
  have ht₁ := tag_le_of_cmp_ne_gt h₁
  have ht₂ := tag_le_of_cmp_ne_gt h₂
  by_cases heq₁ : e₁.tag = e₂.tag
  · by_cases heq₂ : e₂.tag = e₃.tag
    · -- same tag: case split on the 4 tags
      rcases e₁ with (r₁ | n₁ | ⟨a₁, b₁⟩ | ⟨a₁, b₁⟩) <;>
      rcases e₂ with (r₂ | n₂ | ⟨a₂, b₂⟩ | ⟨a₂, b₂⟩) <;>
      rcases e₃ with (r₃ | n₃ | ⟨a₃, b₃⟩ | ⟨a₃, b₃⟩) <;>
      simp [TropExpr.tag] at heq₁ heq₂ ⊢ <;>
      first
      | exact cmp_trans_const _ _ _ h₁ h₂
      | exact cmp_trans_var _ _ _ h₁ h₂
      | (simp only [TropExpr.cmp] at h₁ h₂ ⊢;
         exact cmp_trans_lex
           (fun ha₁ ha₂ => cmp_trans ha₁ ha₂)
           (fun hb₁ hb₂ => cmp_trans hb₁ hb₂) h₁ h₂)
    · have hlt : e₁.tag < e₃.tag := by omega
      intro habs; have := cmp_of_tag_lt hlt; simp_all
  · have hlt : e₁.tag < e₃.tag := by omega
    intro habs; have := cmp_of_tag_lt hlt; simp_all

/-
ble is transitive
-/
theorem ble_trans {e₁ e₂ e₃ : TropExpr}
    (h₁ : e₁.ble e₂ = true) (h₂ : e₂.ble e₃ = true) : e₁.ble e₃ = true := by
      unfold TropExpr.ble at *;
      have h₃ := cmp_trans ( show e₁.cmp e₂ ≠ Ordering.gt from by
                              grind ) ( show e₂.cmp e₃ ≠ Ordering.gt from by
                                                                              grind +splitImp );
      cases h : e₁.cmp e₃ <;> tauto

/-
ble is total in the Bool disjunction sense
-/
theorem ble_total_bool (e₁ e₂ : TropExpr) :
    (e₁.ble e₂ || e₂.ble e₁) = true := by
      grind +suggestions

/-- mergeSort with ble produces a sorted list (pairwise ble) -/
theorem mergeSort_pairwise (l : List TropExpr) :
    List.Pairwise (fun a b => a.ble b = true) (l.mergeSort TropExpr.ble) :=
  @List.pairwise_mergeSort TropExpr TropExpr.ble
    (fun _ _ _ h₁ h₂ => ble_trans h₁ h₂) ble_total_bool l

/-
Two permutations sort to the same result.
-/
theorem mergeSort_perm_eq {l₁ l₂ : List TropExpr}
    (hp : l₁.Perm l₂) :
    l₁.mergeSort TropExpr.ble = l₂.mergeSort TropExpr.ble := by
      apply Classical.byContradiction
      intro h_neq;
      have h_perm : List.Perm (l₁.mergeSort TropExpr.ble) (l₂.mergeSort TropExpr.ble) := by
        exact List.Perm.trans ( mergeSort_perm_self _ ) ( hp.trans ( mergeSort_perm_self _ |> List.Perm.symm ) );
      have h_sorted : List.Pairwise (fun a b => TropExpr.ble a b = true) (l₁.mergeSort TropExpr.ble) ∧ List.Pairwise (fun a b => TropExpr.ble a b = true) (l₂.mergeSort TropExpr.ble) := by
        exact ⟨ mergeSort_pairwise l₁, mergeSort_pairwise l₂ ⟩;
      have h_eq : ∀ {l₁ l₂ : List TropExpr}, List.Pairwise (fun a b => TropExpr.ble a b = true) l₁ → List.Pairwise (fun a b => TropExpr.ble a b = true) l₂ → List.Perm l₁ l₂ → l₁ = l₂ := by
        intros l₁ l₂ hl₁ hl₂ hperm;
        apply_rules [ List.Perm.eq_of_pairwise ];
        exact fun a b ha hb hab hba => ble_antisymm hab hba;
      exact ‹¬l₁.mergeSort ble = l₂.mergeSort ble› ( h_eq h_sorted.1 h_sorted.2 h_perm )

/-! ## Completeness -/

/-
**Completeness for AC congruence**: AC-equivalent expressions normalize
    to the same canonical form.
-/
theorem normalize_ca_complete {e₁ e₂ : TropExpr}
    (h : ACEquiv e₁ e₂) : normalize_ca e₁ = normalize_ca e₂ := by
      -- By definition of ACEquiv, we know that ACEquiv e₁ e₂ implies that e₁ and e₂ are equivalent under the AC congruence.
      induction' h with e₁ e₂ h_eq h_trans h_symm h_refl h_add h_add_comm h_add_assoc h_tmin h_tmin_comm h_tmin_assoc;
      all_goals try tauto;
      exact h_tmin_comm.trans h_tmin_assoc;
      -- Since the mergeSort function is deterministic and the input lists are permutations of each other, the mergeSort results will be the same.
      have h_mergeSort_perm : ∀ (l₁ l₂ : List TropExpr), l₁.Perm l₂ → List.mergeSort l₁ TropExpr.ble = List.mergeSort l₂ TropExpr.ble := by
        intros l₁ l₂ h_perm
        apply mergeSort_perm_eq h_perm;
      grind +locals;
      · unfold normalize_ca;
        simp +decide [ flattenMin ];
        nontriviality;
        rename_i e₁ e₂ e₃;
        rename_i e₄;
        rw [ show normalize_ca ( e₄.tmin e₁ ) = buildMin ( ( flattenMin ( normalize_ca e₄ ) ++ flattenMin ( normalize_ca e₁ ) ).mergeSort ble ) from ?_, show normalize_ca ( e₁.tmin e₂ ) = buildMin ( ( flattenMin ( normalize_ca e₁ ) ++ flattenMin ( normalize_ca e₂ ) ).mergeSort ble ) from ?_ ];
        · rw [ flattenMin_buildMin, flattenMin_buildMin ];
          · rw [ mergeSort_perm_eq ];
            rw [ List.perm_iff_count ];
            intro a; rw [ List.count_append, List.count_append ] ;
            rw [ List.Perm.count_eq ( mergeSort_perm_self _ ), List.Perm.count_eq ( mergeSort_perm_self _ ) ] ; ring;
            rw [ List.count_append, List.count_append ] ; ring;
          · exact mergeSort_ne _ ( by simp +decide [ flattenMin_ne ] );
          · intro x hx a b; contrapose! hx; simp_all +decide [ List.mem_mergeSort ] ;
            exact ⟨ fun h => by have := normalize_ca_flattenMin_no_tmin e₁ _ h _ _ rfl; contradiction, fun h => by have := normalize_ca_flattenMin_no_tmin e₂ _ h _ _ rfl; contradiction ⟩;
          · exact mergeSort_ne _ ( by simp +decide [ flattenMin_ne ] );
          · intro x hx a b; have := normalize_ca_flattenMin_no_tmin e₄; have := normalize_ca_flattenMin_no_tmin e₁; simp_all +decide [ List.mem_mergeSort ] ;
            grind;
        · cases e₁ <;> cases e₂ <;> tauto;
        · rw [ normalize_ca ];
          simp +decide [ flattenMin ];
      · unfold normalize_ca;
        simp +decide [ flattenAdd ];
        rw [ mergeSort_perm_eq ];
        grind +revert;
      · -- By definition of `normalize_ca`, we know that `normalize_ca (a.add b)` is the sorted list of `a` and `b`.
        have h_normalize_add : ∀ a b : TropExpr, normalize_ca (a.add b) = buildAdd ((flattenAdd (normalize_ca a) ++ flattenAdd (normalize_ca b)).mergeSort TropExpr.ble) := by
          intros a b
          rw [normalize_ca];
          congr;
        rw [ h_normalize_add, h_normalize_add ];
        rw [ h_normalize_add, h_normalize_add ];
        rw [ flattenAdd_buildAdd, flattenAdd_buildAdd ];
        · rw [ mergeSort_perm_eq ];
          rw [ List.perm_iff_count ];
          intro x; rw [ List.count_append, List.count_append ] ;
          rw [ List.Perm.count_eq ( mergeSort_perm_self _ ), List.Perm.count_eq ( mergeSort_perm_self _ ) ] ; ring;
          rw [ List.count_append, List.count_append ] ; ring;
        · exact mergeSort_ne _ ( by simp +decide [ flattenAdd_ne ] );
        · grind +suggestions;
        · exact mergeSort_ne _ ( by simp +decide [ flattenAdd_ne ] );
        · grind +suggestions;
      · unfold normalize_ca;
        grind;
      · unfold normalize_ca;
        grind

/-
buildMin of a permutation is ACEquiv to buildMin of the original (for nonempty lists without tmin)
-/
theorem buildMin_perm_ACEquiv {l₁ l₂ : List TropExpr}
    (hp : l₁.Perm l₂) (h₁ : l₁ ≠ []) (h₂ : l₂ ≠ []) :
    ACEquiv (buildMin l₁) (buildMin l₂) := by
      induction' hp with l₁ l₂ hp ih;
      · contradiction;
      · cases l₂ <;> cases hp <;> simp_all +decide [ buildMin ];
        · constructor;
        · exact ACEquiv.cong_tmin ( ACEquiv.refl _ ) ‹_›;
      · rename_i x y l;
        rcases l with ( _ | ⟨ z, l ⟩ ) <;> simp_all +decide [ buildMin ];
        · exact ACEquiv.tmin_comm _ _;
        · have h_assoc_comm : ACEquiv (y.tmin (x.tmin (buildMin (z :: l)))) ((y.tmin x).tmin (buildMin (z :: l))) ∧ ACEquiv ((y.tmin x).tmin (buildMin (z :: l))) (x.tmin (y.tmin (buildMin (z :: l)))) := by
            constructor;
            · exact ACEquiv.symm ( ACEquiv.tmin_assoc _ _ _ );
            · have h_assoc_comm : ACEquiv ((y.tmin x).tmin (buildMin (z :: l))) ((x.tmin y).tmin (buildMin (z :: l))) := by
                exact ACEquiv.cong_tmin ( ACEquiv.tmin_comm _ _ ) ( ACEquiv.refl _ );
              exact h_assoc_comm.trans ( ACEquiv.tmin_assoc _ _ _ );
          exact ACEquiv.trans h_assoc_comm.1 h_assoc_comm.2;
      · rename_i l₁ l₂ l₃ hp₁ hp₂ ih₁ ih₂;
        exact ACEquiv.trans ( ih₁ h₁ ( by aesop ) ) ( ih₂ ( by aesop ) h₂ )

/-
buildAdd of a permutation is ACEquiv to buildAdd of the original
-/
theorem buildAdd_perm_ACEquiv {l₁ l₂ : List TropExpr}
    (hp : l₁.Perm l₂) (h₁ : l₁ ≠ []) (h₂ : l₂ ≠ []) :
    ACEquiv (buildAdd l₁) (buildAdd l₂) := by
      induction' hp with l₁ l₂ hp ih;
      · contradiction;
      · rcases l₂ with ( _ | ⟨ a, _ | ⟨ b, l₂ ⟩ ⟩ ) <;> rcases hp with ( _ | ⟨ c, _ | ⟨ d, hp ⟩ ⟩ ) <;> simp_all +decide [ buildAdd ];
        · constructor;
        · exact ACEquiv.refl _;
        · apply ACEquiv.cong_add; exact ACEquiv.refl _; assumption;
      · unfold buildAdd;
        unfold buildAdd at *;
        cases ‹List TropExpr› <;> simp_all +decide [ ACEquiv.add_comm ];
        rename_i a b c d;
        -- By the associativity of addition, we can rearrange the terms.
        have h_assoc : ACEquiv (b.add (a.add (buildAdd (c :: d)))) ((b.add a).add (buildAdd (c :: d))) := by
          exact ACEquiv.add_assoc _ _ _ |> ACEquiv.symm;
        have h_assoc : ACEquiv ((b.add a).add (buildAdd (c :: d))) (a.add (b.add (buildAdd (c :: d)))) := by
          have h_assoc : ACEquiv ((b.add a).add (buildAdd (c :: d))) ((a.add b).add (buildAdd (c :: d))) := by
            apply ACEquiv.cong_add;
            · exact ACEquiv.add_comm _ _;
            · constructor;
          exact h_assoc.trans ( ACEquiv.add_assoc _ _ _ );
        exact ACEquiv.trans ‹_› ‹_›;
      · rename_i l₁ l₂ l₃ hp₁ hp₂ ih₁ ih₂;
        exact ACEquiv.trans ( ih₁ h₁ ( by aesop ) ) ( ih₂ ( by aesop ) h₂ )

/-
buildMin of flattenMin is ACEquiv to the original expression
-/
theorem buildMin_flattenMin_ACEquiv (e : TropExpr) :
    ACEquiv (buildMin (flattenMin e)) e := by
      revert e;
      intro e
      induction' n : TropExpr.sz e using Nat.strong_induction_on with n ih generalizing e;
      rcases e with ( _ | _ | _ | _ ) <;> simp +arith +decide [ * ] at *;
      · exact ACEquiv.refl _;
      · exact ACEquiv.refl _;
      · -- By definition of `flattenMin`, we have `flattenMin (.tmin a b) = flattenMin a ++ flattenMin b`.
        have h_flattenMin_tmin : ∀ a b : TropExpr, flattenMin (.tmin a b) = flattenMin a ++ flattenMin b := by
          grind +locals
        generalize_proofs at *;
        -- By definition of `buildMin`, we have `buildMin (flattenMin a ++ flattenMin b) = .tmin (buildMin (flattenMin a)) (buildMin (flattenMin b))`.
        have h_buildMin_append : ∀ l₁ l₂ : List TropExpr, l₁ ≠ [] → l₂ ≠ [] → ACEquiv (buildMin (l₁ ++ l₂)) (.tmin (buildMin l₁) (buildMin l₂)) := by
          intros l₁ l₂ hl₁ hl₂; induction' l₁ with a l₁ ih generalizing l₂ <;> simp_all +decide [ List.append_assoc ] ;
          rcases l₁ with ( _ | ⟨ b, l₁ ⟩ ) <;> simp_all +decide [ List.append_assoc ];
          · cases l₂ <;> simp_all +decide [ List.append_assoc ];
            exact ACEquiv.refl _;
          · -- By the induction hypothesis, we know that buildMin (b :: (l₁ ++ l₂)) is ACEquiv to (buildMin (b :: l₁)).tmin (buildMin l₂).
            have h_ind : ACEquiv (buildMin (b :: (l₁ ++ l₂))) ((buildMin (b :: l₁)).tmin (buildMin l₂)) := by
              exact ih l₂ hl₂
            generalize_proofs at *; (
            exact ACEquiv.cong_tmin ( ACEquiv.refl _ ) h_ind |> ACEquiv.trans <| ACEquiv.tmin_assoc _ _ _ |> ACEquiv.symm |> ACEquiv.trans <| ACEquiv.refl _;)
        generalize_proofs at *; (
        rename_i a b; specialize h_buildMin_append ( flattenMin a ) ( flattenMin b ) ; simp_all +decide [ flattenMin_ne ] ;
        exact h_buildMin_append.trans ( ACEquiv.cong_tmin ( ih _ ( by { unfold TropExpr.sz at n; linarith } ) _ rfl ) ( ih _ ( by { unfold TropExpr.sz at n; linarith } ) _ rfl ) ));
      · exact?

/-
buildAdd of flattenAdd is ACEquiv to the original expression
-/
theorem buildAdd_flattenAdd_ACEquiv (e : TropExpr) :
    ACEquiv (buildAdd (flattenAdd e)) e := by
      induction' n : TropExpr.sz e using Nat.strong_induction_on with n ih generalizing e;
      rcases e with ( _ | _ | _ | _ ) <;> simp +arith +decide [ * ] at *;
      · exact ACEquiv.refl _;
      · exact ACEquiv.refl _;
      · exact?;
      · rename_i a b;
        -- By the induction hypothesis, we know that buildAdd (flattenAdd a) is ACEquiv to a and buildAdd (flattenAdd b) is ACEquiv to b.
        have h_ind_a : ACEquiv (buildAdd (flattenAdd a)) a := by
          grind +locals
        have h_ind_b : ACEquiv (buildAdd (flattenAdd b)) b := by
          exact ih _ ( by { unfold TropExpr.sz at n; linarith } ) _ rfl;
        -- By the properties of ACEquiv, we can combine the induction hypotheses to show that buildAdd (flattenAdd a ++ flattenAdd b) is ACEquiv to a.add b.
        have h_combined : ACEquiv (buildAdd (flattenAdd a ++ flattenAdd b)) (buildAdd (flattenAdd a) |> fun x => buildAdd (flattenAdd b) |> fun y => x.add y) := by
          have h_combined : ∀ (l₁ l₂ : List TropExpr), l₁ ≠ [] → l₂ ≠ [] → ACEquiv (buildAdd (l₁ ++ l₂)) (buildAdd l₁ |> fun x => buildAdd l₂ |> fun y => x.add y) := by
            intros l₁ l₂ hl₁ hl₂;
            induction' l₁ with x l₁ ih generalizing l₂ <;> simp_all +decide [ List.append_assoc ];
            rcases l₁ with ( _ | ⟨ y, l₁ ⟩ ) <;> simp_all +decide [ buildAdd ];
            · constructor;
            · have h_combined : ACEquiv (x.add (y.add (buildAdd (l₁ ++ l₂)))) (x.add ((buildAdd (y :: l₁)).add (buildAdd l₂))) := by
                exact ACEquiv.cong_add ( ACEquiv.refl _ ) ( ih _ hl₂ );
              have h_combined : ACEquiv (x.add ((buildAdd (y :: l₁)).add (buildAdd l₂))) ((x.add (buildAdd (y :: l₁))).add (buildAdd l₂)) := by
                exact ACEquiv.trans ( ACEquiv.refl _ ) ( ACEquiv.symm ( ACEquiv.add_assoc _ _ _ ) );
              exact ACEquiv.trans ‹_› ‹_›;
          exact h_combined _ _ ( flattenAdd_ne a ) ( flattenAdd_ne b );
        convert h_combined.trans ( ACEquiv.cong_add h_ind_a h_ind_b ) using 1

/-
normalize_ca produces an ACEquiv expression
-/
theorem normalize_ca_ACEquiv (e : TropExpr) :
    ACEquiv (normalize_ca e) e := by
      induction' e using TropExpr.recOn with e ih₂ ih₁ ih₂;
      · exact ACEquiv.refl _;
      · exact ACEquiv.refl _;
      · -- By definition of `buildMin`, we know that `buildMin (List.mergeSort (flattenMin (.tmin (normalize_ca ih₁) (normalize_ca ih₂))) TropExpr.ble)` is ACEquiv to `buildMin (flattenMin (.tmin (normalize_ca ih₁) (normalize_ca ih₂)))`.
        have h_buildMin_mergeSort : ACEquiv (buildMin (List.mergeSort (flattenMin (.tmin (normalize_ca ih₁) (normalize_ca ih₂))) TropExpr.ble)) (buildMin (flattenMin (.tmin (normalize_ca ih₁) (normalize_ca ih₂)))) := by
          apply buildMin_perm_ACEquiv
          generalize_proofs at *; (
          grind +suggestions);
          · exact mergeSort_ne _ ( flattenMin_ne _ );
          · exact flattenMin_ne _
        generalize_proofs at *; (
        convert h_buildMin_mergeSort.trans ( buildMin_flattenMin_ACEquiv _ ) |> ACEquiv.trans <| ACEquiv.cong_tmin ‹ACEquiv ( normalize_ca ih₁ ) ih₁› ‹ACEquiv ( normalize_ca ih₂ ) ih₂› using 1);
      · rename_i a b ha hb;
        convert ACEquiv.trans ( ACEquiv.trans ( buildAdd_perm_ACEquiv ( mergeSort_perm_self ( flattenAdd ( .add ( normalize_ca a ) ( normalize_ca b ) ) ) ) ( mergeSort_ne _ _ ) ( flattenAdd_ne _ ) ) ( buildAdd_flattenAdd_ACEquiv _ ) ) ( ACEquiv.cong_add ha hb ) using 1;
        exact flattenAdd_ne _

/-- **Idempotence**: normalizing twice equals normalizing once. -/
theorem normalize_ca_idempotent (e : TropExpr) :
    normalize_ca (normalize_ca e) = normalize_ca e :=
  normalize_ca_complete (normalize_ca_ACEquiv e)

end TropicalACCanonical