/-
# Phantom Possibility: The Dual (Union) Topology of Two Observers

This file is the **modal dual** of `Catalog.Novelty.PhantomTopology`.

Recall the phantom-topology setup.  A **phantom topology** on `X` with observer
set `ι` is a family `T : ι → TopologicalSpace X`.  In Mathlib's lattice of
topologies (`t ≤ s` means `t` is *finer*), the **consensus** (necessity) topology
of `PhantomTopology` is the supremum `⨆ i, T i`, whose opens are exactly the sets
open in **every** observer (`isOpen_iSup_iff`).  Consensus is the *necessity*
modality: `U` is consensus-open iff it is open for *all* observers.

Here we build the **possibility** (dual) modality.  The *possibility topology* is
the infimum

  `possibility T = ⨅ i, T i`,

the finest topology generated by the sets that are open for **some** observer.
Where consensus intersects the observers' open families, possibility takes their
(generated) union: it is the dual "◇" to the consensus "□".  Dually to
`observer_le_consensus` (each observer is *finer* than the consensus), each
observer is *coarser* than the possibility topology (`possibility_le_observer`):
possibility can only *add* resolution.

The headline result is the **possibility collapse** for the real line.  Taking the
same two observers as `PhantomTopology` — the **lower-limit** observer (basic opens
`[x, b)`) and the **upper-limit** observer (basic opens `(a, x]`) — their
possibility topology is the **discrete** topology on `ℝ`:

  `possibilityTop = lowerTop ⊓ upperTop = ⊥`   (`possibility_eq_discrete`).

The construction is completely explicit and **non-circular** — it never invokes the
consensus theorem `consensus_eq_standard` or any Euclidean property.  For each point
`x` we build its basic possibility-open neighbourhood directly as the *intersection*
of a right half-open and a left half-open interval,

  `[x, b) ∩ (a, x] = {x}`   (`inter_Ico_Ioc_singleton`),

so every singleton is possibility-open (`isOpen_singleton_possibility`), and every
set is the *union* of such singletons (`possibilityTop_isOpen`), forcing the discrete
topology.  Thus where consensus of the two observers is the Euclidean line, their
possibility is the fully-resolved discrete line: the dual modality maximally
sharpens reality instead of coarsening it.

-- !-- Lab Notes -- !--

Hypothesis (Hypothesizer):
  H1. The possibility (dual) topology of the two Sorgenfrey observers is the discrete
      topology, witnessed pointwise by `[x,b) ∩ (a,x] = {x}`.
  H2. Dually to consensus (each observer finer than consensus), each observer is
      *coarser* than the possibility topology.

Analysis (Analyst):
  - H1 survives as `possibility_eq_discrete`, built explicitly from
    `inter_Ico_Ioc_singleton` with no reference to the Euclidean/consensus theorem.
  - H2 survives as `possibility_le_observer` (= `iInf_le`).
-/
import Mathlib
import Catalog.Novelty.PhantomTopology

open Set

namespace Phantom

variable {X : Type*} {ι : Type*}

/-! ## The possibility (dual) modality -/

/-- The **possibility** (dual) topology of a phantom topology: the finest topology
generated by the sets open for *some* observer.  In Mathlib's lattice this is the
infimum `⨅ i, T i`, the order-theoretic dual of `consensus T = ⨆ i, T i`. -/
def possibility (T : PhantomTopology ι X) : TopologicalSpace X := ⨅ i, T i

/-- **Possibility sharpens.** Dually to `observer_le_consensus`, each observer is
*coarser* than the possibility topology: the possibility topology resolves at least
everything every observer resolves. -/
theorem possibility_le_observer (T : PhantomTopology ι X) (i : ι) :
    possibility T ≤ T i :=
  iInf_le T i

/-! ## Explicit basis elements on `ℝ`: singletons as interval intersections -/

/-- **Basic possibility-open set of a point.** The intersection of the right
half-open interval `[x, b)` (a lower-limit basic open) with the left half-open
interval `(a, x]` (an upper-limit basic open) is exactly the singleton `{x}`,
whenever `a < x < b`.
-/
theorem inter_Ico_Ioc_singleton (a x b : ℝ) (ha : a < x) (hb : x < b) :
    Ico x b ∩ Ioc a x = {x} := by
      grind +locals

/-- `[x, b)` is open for the lower-limit observer (a right half-open interval is a
lower-limit basic open). -/
theorem lowerOpen_Ico_self (x b : ℝ) : lowerOpen (Ico x b) := by
  exact fun y hy => ⟨ b, hy.2, fun z hz => ⟨ by linarith [ hz.1, hy.1 ], by linarith [ hz.2, hy.2 ] ⟩ ⟩

/-- `(a, x]` is open for the upper-limit observer (a left half-open interval is an
upper-limit basic open). -/
theorem upperOpen_Ioc_self (a x : ℝ) : upperOpen (Ioc a x) := by
  exact fun y hy => ⟨ a, hy.1, fun z hz => ⟨ hz.1, hz.2.trans hy.2 ⟩ ⟩

/-! ## The possibility topology of the two `ℝ`-observers is discrete -/

/-- The possibility topology of the lower-limit and upper-limit observers on `ℝ`. -/
def possibilityTop : TopologicalSpace ℝ := lowerTop ⊓ upperTop

/-- Anything open for the lower-limit observer is open in the possibility topology
(the infimum is finer than each factor). -/
theorem isOpen_possibility_of_lower {U : Set ℝ} (h : lowerOpen U) :
    possibilityTop.IsOpen U :=
  (inf_le_left : possibilityTop ≤ lowerTop) _ h

/-- Anything open for the upper-limit observer is open in the possibility topology. -/
theorem isOpen_possibility_of_upper {U : Set ℝ} (h : upperOpen U) :
    possibilityTop.IsOpen U :=
  (inf_le_right : possibilityTop ≤ upperTop) _ h

/-- **Every singleton is possibility-open**, via the explicit basis element
`[x, x+1) ∩ (x-1, x] = {x}`.
-/
theorem isOpen_singleton_possibility (x : ℝ) : possibilityTop.IsOpen ({x} : Set ℝ) := by
  have h_singleton : possibilityTop.IsOpen {x} := by
    have h_singleton : {x} = (Ico x (x + 1)) ∩ (Ioc (x - 1) x) := by
      grind
    convert possibilityTop.isOpen_inter _ _ ( isOpen_possibility_of_lower ( lowerOpen_Ico_self x ( x + 1 ) ) ) ( isOpen_possibility_of_upper ( upperOpen_Ioc_self ( x - 1 ) x ) ) using 1;
  grind

/-- **Discreteness.** Every subset of `ℝ` is open in the possibility topology,
because it is the union of its (possibility-open) singletons.
-/
theorem possibilityTop_isOpen (U : Set ℝ) : possibilityTop.IsOpen U := by
  rw [ show U = ⋃ x ∈ U, { x } by ext; simp +decide ];
  -- Since each singleton is open in the possibility topology, the union of any collection of open sets is also open.
  have h_union_open : ∀ (s : Set ℝ), (∀ x ∈ s, possibilityTop.IsOpen {x}) → possibilityTop.IsOpen (⋃ x ∈ s, {x}) := by
    -- The union of open sets is open.
    intros s hs
    apply TopologicalSpace.GenerateOpen.sUnion;
    rintro _ ⟨ x, rfl ⟩ ; by_cases hx : x ∈ s <;> simp +decide [ hx ] ;
    · convert hs x hx;
    · exact TopologicalSpace.GenerateOpen.basic _ ( Or.inl <| by tauto );
  exact h_union_open U fun x hx => isOpen_singleton_possibility x

/-- **Possibility collapse.** The possibility topology of the lower-limit and
upper-limit observers on `ℝ` is the discrete topology.  Contrast with
`consensus_eq_standard`: the *consensus* of the same two observers is the Euclidean
topology, while their *possibility* is the fully-resolved discrete topology.
-/
theorem possibility_eq_discrete : possibilityTop = ⊥ := by
  -- Apply the fact that if every set is open, then the topology is discrete.
  apply le_antisymm;
  · exact fun U hU => possibilityTop_isOpen U;
  · exact bot_le

/-! ## Packaged as a two-observer possibility -/

/-- The possibility topology of the `Bool`-indexed observer family `observersℝ`
(from `PhantomTopology`) is the discrete topology on `ℝ`. -/
theorem possibility_pair_eq_discrete :
    possibility observersℝ = (⊥ : TopologicalSpace ℝ) := by
      convert possibility_eq_discrete using 1;
      unfold possibility observersℝ possibilityTop;
      refine' le_antisymm _ _;
      · exact le_inf ( iInf_le _ true ) ( iInf_le _ false );
      · exact le_iInf fun i => by cases i <;> simp +decide ;

/-- The possibility topology strictly refines each observer: it is the discrete
topology, which is strictly finer than the lower-limit observer (`[0,1)` is
lower-open, but in the discrete topology also `{0}` is open while it is not
lower-open).
-/
theorem possibilityTop_ne_lowerTop : possibilityTop ≠ lowerTop := by
  intro h; have := Phantom.isOpen_singleton_possibility 0; simp_all +decide [ Phantom.lowerTop ] ;
  obtain ⟨ b, hb, hb' ⟩ := this 0 ( by norm_num ) ; have := hb' ( show ( b / 2 : ℝ ) ∈ Ico 0 b from ⟨ by linarith, by linarith ⟩ ) ; norm_num at this ; linarith;

end Phantom