/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Coalgebraic Temporal Adjunction: Definitions

This file lifts the finite-trace adjunction ⟨a⟩ ⊣ (ext_a)^* ⊣ [a] from
`TemporalAdjunction` to infinite traces (streams), and connects this lift
to standard temporal operators (EX, AX) on finite Kripke structures.

## Main Definitions

* `StreamPred` — Predicates on infinite streams of actions
* `prefixPull` — Pullback along stream prefix-cons
* `diamondStream` — Existential one-step modality on streams (left adjoint)
* `boxStream` — Universal one-step modality on streams (right adjoint)
* `cylinderPred` — Cylinder predicates: stream predicates determined by finite prefixes
* `Kripke` — Finite Kripke structures with transition relation
* `EX` / `AX` — Standard temporal operators on Kripke structures
* `stepPull` — Relational pullback along Kripke transitions
* `streamCoalg` — Coalgebra structure on streams (head, tail destructors)
* `CylinderGenerated` — Predicates generated by finite-prefix cylinders

## Mathematical Context

The finite-trace adjunctions from `TemporalAdjunction` show that diamond ⟨a⟩
and box [a] are left/right adjoints to pullback along trace extension. Here
we extend this to infinite traces, showing that the same adjoint geometry
governs temporal modalities on streams. The cylinder compatibility theorem
demonstrates that the infinite-trace operators restrict to the finite-trace
ones on prefix-generated predicates, realizing the principle that ω-regular
temporal reasoning can be reconstructed from a single coalgebraic adjunction.
-/

import Mathlib

namespace CoalgebraicTemporalAdjunction

/-! ## Stream Predicates and Modal Operators -/

/-- A stream predicate: a proposition on infinite streams of actions.
    These are the "observables" on infinite behaviors. -/
def StreamPred (Act : Type*) := Stream' Act → Prop

/-- Pullback along prefix-cons by action `a`:
    `prefixPull a P s = P (Stream'.cons a s)`.
    This is the inverse image functor along the one-step extension. -/
def prefixPull {Act : Type*} (a : Act) (P : StreamPred Act) : StreamPred Act :=
  fun s => P (Stream'.cons a s)

/-- **Diamond modality on streams** (left adjoint to prefixPull):
    `◇_a P t ≡ ∃ s, t = cons a s ∧ P s`.
    Existentially: "t starts with action a and the tail satisfies P." -/
def diamondStream {Act : Type*} (a : Act) (P : StreamPred Act) : StreamPred Act :=
  fun t => ∃ s, t = Stream'.cons a s ∧ P s

/-- **Box modality on streams** (right adjoint to prefixPull):
    `□_a P t ≡ ∀ s, t = cons a s → P s`.
    Universally: "if t starts with action a, the tail must satisfy P." -/
def boxStream {Act : Type*} (a : Act) (P : StreamPred Act) : StreamPred Act :=
  fun t => ∀ s, t = Stream'.cons a s → P s

/-! ## Cylinder Predicates

Cylinder predicates are stream predicates determined by a finite prefix.
They form the bridge between finite-trace and infinite-trace modalities. -/

/-- Test whether stream `s` starts with the finite prefix `w`.
    `matchesPrefix [a₀, a₁, ..., aₙ] s` holds iff
    `s 0 = a₀, s 1 = a₁, ..., s n = aₙ`. -/
def matchesPrefix {Act : Type*} : List Act → Stream' Act → Prop
  | [], _ => True
  | a :: w, s => s.head = a ∧ matchesPrefix w s.tail

/-- Drop the first `n` elements of a stream. -/
def streamDrop {Act : Type*} (n : Nat) (s : Stream' Act) : Stream' Act :=
  fun i => s (n + i)

/-- **Cylinder predicate**: the stream predicate that holds when the stream
    starts with prefix `w` and the tail after `|w|` steps satisfies `U`.
    `Cyl(w, U)(s) ≡ matchesPrefix w s ∧ U(drop |w| s)`. -/
def cylinderPred {Act : Type*} (w : List Act) (U : StreamPred Act) : StreamPred Act :=
  fun s => matchesPrefix w s ∧ U (streamDrop w.length s)

/-! ## Kripke Structures and Temporal Operators -/

/-- A Kripke structure with state type `σ`: a transition relation on states. -/
structure Kripke (σ : Type*) where
  /-- The transition relation: `step s t` means state `s` can reach `t` -/
  step : σ → σ → Prop

/-- **EX (Existential neXt)**: `EX P s` iff there exists a successor `t`
    of `s` with `P t`. This is the standard temporal operator from CTL. -/
def EX {σ : Type*} (K : Kripke σ) (P : σ → Prop) : σ → Prop :=
  fun s => ∃ t, K.step s t ∧ P t

/-- **AX (Universal neXt)**: `AX P s` iff all successors `t` of `s`
    satisfy `P t`. This is the standard temporal operator from CTL. -/
def AX {σ : Type*} (K : Kripke σ) (P : σ → Prop) : σ → Prop :=
  fun s => ∀ t, K.step s t → P t

/-- Relational pullback along the Kripke step relation.
    `stepPull K P s` iff all successors of `s` satisfy `P`. -/
def stepPull {σ : Type*} (K : Kripke σ) (P : σ → Prop) : σ → Prop :=
  fun s => ∀ t, K.step s t → P t

/-! ## Stream Coalgebra Structure -/

/-- The coalgebra structure map on streams: decomposes a stream into
    its head (current action) and tail (remaining stream).
    This exhibits `Stream' Act` as a coalgebra for the functor `F(X) = Act × X`. -/
def streamCoalg {Act : Type*} (s : Stream' Act) : Act × Stream' Act :=
  (s.head, s.tail)

/-! ## Cylinder-Generated Predicates

A stream predicate is cylinder-generated if it is determined by some
finite prefix — i.e., it can be written as a cylinder predicate.
These predicates form the ω-regular fragment of stream properties. -/

/-- A stream predicate is **cylinder-generated** if there exists a finite
    prefix `w` and a tail predicate `U` such that `P = Cyl(w, U)`.
    This captures the idea that `P` is determined by a finite observation. -/
def CylinderGenerated {Act : Type*} (P : StreamPred Act) : Prop :=
  ∃ (w : List Act) (U : StreamPred Act), ∀ s, P s ↔ cylinderPred w U s

end CoalgebraicTemporalAdjunction