#!/usr/bin/env python3
"""
Demo 14: Grand Synthesis — Six Landscapes in One View
======================================================

The unifying visualization: all six mathematical landscapes discovered
through N-dimensional inverse stereographic projection, arranged as
a hexagonal "atlas" showing how one formula connects geometry, topology,
number theory, physics, fractals, and conformal field theory.

Oracle Council's final synthesis.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
from matplotlib.colors import Normalize

def inv_stereo_1d(t):
    D = 1 + t**2
    return 2*t/D, (t**2 - 1)/D

def inv_stereo_2d(u, v):
    D = 1 + u**2 + v**2
    return 2*u/D, 2*v/D, (u**2 + v**2 - 1)/D

def conformal_factor(u, v):
    return 2.0 / (1 + u**2 + v**2)

def hopf_fiber(theta, phi, num_points=300):
    t = np.linspace(0, 2*np.pi, num_points)
    half_theta = theta / 2
    z1r = np.cos(half_theta) * np.cos(t)
    z1i = np.cos(half_theta) * np.sin(t)
    z2r = np.sin(half_theta) * np.cos(t + phi)
    z2i = np.sin(half_theta) * np.sin(t + phi)
    return z1r, z1i, z2r, z2i

def stereo_4to3(x1, x2, x3, x4):
    denom = 1 - x4
    denom = np.where(np.abs(denom) < 1e-10, np.nan, denom)
    return x1/denom, x2/denom, x3/denom

def sphere_inversion(x, y, cx, cy, r):
    dx, dy = x - cx, y - cy
    d2 = dx**2 + dy**2
    d2 = np.where(d2 < 1e-15, np.nan, d2)
    f = r**2 / d2
    return cx + f*dx, cy + f*dy

# ─── Grand Figure ───

fig = plt.figure(figsize=(24, 18))
gs = gridspec.GridSpec(3, 3, hspace=0.4, wspace=0.35)

# ═══ LANDSCAPE 1: Conformal Geometry (top-left) ═══
ax1 = fig.add_subplot(gs[0, 0])

u_g = np.linspace(-3, 3, 300)
v_g = np.linspace(-3, 3, 300)
U, V = np.meshgrid(u_g, v_g)

# Draw a conformal grid on the sphere, projected back
for k in np.linspace(-3, 3, 15):
    # Vertical lines u=k
    v_line = np.linspace(-3, 3, 200)
    x, y, z = inv_stereo_2d(np.full_like(v_line, k), v_line)
    ax1.plot(x, y, 'b-', linewidth=0.5, alpha=0.5)
    # Horizontal lines v=k
    u_line = np.linspace(-3, 3, 200)
    x, y, z = inv_stereo_2d(u_line, np.full_like(u_line, k))
    ax1.plot(x, y, 'r-', linewidth=0.5, alpha=0.5)

theta_c = np.linspace(0, 2*np.pi, 200)
ax1.plot(np.cos(theta_c), np.sin(theta_c), 'k-', linewidth=2, alpha=0.5)
ax1.set_xlim(-1.1, 1.1)
ax1.set_ylim(-1.1, 1.1)
ax1.set_aspect('equal')
ax1.set_title('🌐 L1: Conformal Geometry\nGrid on S² (x,y projection)', fontsize=11, fontweight='bold')
ax1.set_facecolor('#f0f8ff')

# ═══ LANDSCAPE 2: Harmonic Analysis (top-center) ═══
ax2 = fig.add_subplot(gs[0, 1])

# Spherical harmonic Y_2^1 in stereographic coordinates
# Y_2^1 ∝ sin(θ)cos(θ)e^{iφ} → in stereo: (2u/D)(D-2)/(2D) × u/√(u²+v²)
u_h = np.linspace(-3, 3, 300)
v_h = np.linspace(-3, 3, 300)
UH, VH = np.meshgrid(u_h, v_h)
DH = 1 + UH**2 + VH**2

# Y_2^0 ∝ 3cos²θ - 1 = 3((D-2)/D)² - 1
harmonic = 3 * ((DH - 2)/DH)**2 - 1

im2 = ax2.pcolormesh(UH, VH, harmonic, cmap='RdBu_r', shading='auto', vmin=-2, vmax=2)
plt.colorbar(im2, ax=ax2, label='Y₂⁰', shrink=0.8)
ax2.contour(UH, VH, harmonic, levels=[0], colors='black', linewidths=1.5)
ax2.set_aspect('equal')
ax2.set_title('🎵 L2: Harmonic Transport\nSpherical harmonic Y₂⁰ in stereo coords', fontsize=11, fontweight='bold')
ax2.set_facecolor('#fff8f0')

# ═══ LANDSCAPE 3: Number Theory (top-right) ═══
ax3 = fig.add_subplot(gs[0, 2])

# Pythagorean triples colored by generation method
max_d = 25
for d in range(1, max_d):
    for a in range(1, d):
        if np.gcd(a, d) == 1:
            x_pt = 2*a*d
            y_pt = d**2 - a**2
            c_pt = d**2 + a**2
            if x_pt > 0 and y_pt > 0 and c_pt < 600:
                ax3.scatter(x_pt, y_pt, c=[c_pt], cmap='turbo',
                          vmin=0, vmax=600, s=10, alpha=0.6)

ax3.set_xlabel('2ad', fontsize=10)
ax3.set_ylabel('d²−a²', fontsize=10)
ax3.set_title('🔢 L3: N-dim Pythagorean Tuples\nGenerated by stereographic parametrization', fontsize=11, fontweight='bold')
ax3.grid(True, alpha=0.2)
ax3.set_facecolor('#f8fff0')

# ═══ LANDSCAPE 4: Hopf Fibration (middle-left) ═══
ax4 = fig.add_subplot(gs[1, 0], projection='3d')

theta_fixed = np.pi / 3
n_fibers = 30
for j, phi in enumerate(np.linspace(0, 2*np.pi, n_fibers, endpoint=False)):
    x1, x2, x3, x4 = hopf_fiber(theta_fixed, phi)
    u, v, w = stereo_4to3(x1, x2, x3, x4)
    mask = np.isfinite(u) & (np.abs(u) < 5) & (np.abs(v) < 5) & (np.abs(w) < 5)
    if np.sum(mask) > 10:
        ax4.plot(u[mask], v[mask], w[mask],
                color=plt.cm.hsv(j/n_fibers), linewidth=1.0, alpha=0.7)

ax4.set_xlim(-3, 3); ax4.set_ylim(-3, 3); ax4.set_zlim(-3, 3)
ax4.set_title('🔗 L4: Hopf Fibration\nLinked circles filling ℝ³', fontsize=11, fontweight='bold')
ax4.view_init(elev=20, azim=45)

# ═══ CENTER: The Formula (middle-center) ═══
ax_center = fig.add_subplot(gs[1, 1])
ax_center.set_xlim(0, 10)
ax_center.set_ylim(0, 10)
ax_center.axis('off')

# The central formula
ax_center.text(5, 7.5, r'$\sigma_N^{-1}(y) = \left(\frac{2y_i}{1+\|y\|^2},\ \frac{\|y\|^2-1}{\|y\|^2+1}\right)$',
              fontsize=16, ha='center', va='center',
              bbox=dict(boxstyle='round,pad=0.5', facecolor='gold', alpha=0.3))

ax_center.text(5, 5.5, 'ONE FORMULA\nSIX WORLDS',
              fontsize=22, ha='center', va='center', fontweight='bold',
              color='darkblue')

ax_center.text(5, 3.5, 'The N-dimensional inverse\nstereographic projection\nunifies:',
              fontsize=12, ha='center', va='center', style='italic')

connections = [
    'Geometry ↔ Algebra',
    'Analysis ↔ Number Theory',
    'Topology ↔ Physics',
]
for i, conn in enumerate(connections):
    ax_center.text(5, 2.0 - i*0.6, conn, fontsize=11, ha='center', va='center',
                  color='darkred', fontweight='bold')

ax_center.set_facecolor('#fffff0')

# ═══ LANDSCAPE 5: Lorentzian / Physics (middle-right) ═══
ax5 = fig.add_subplot(gs[1, 2])

# Light cone: x² + y² - t² = 0 visualized as contours
x_lc = np.linspace(-3, 3, 300)
t_lc = np.linspace(-3, 3, 300)
X_LC, T_LC = np.meshgrid(x_lc, t_lc)

# Light cone: |x| = |t|
cone = X_LC**2 - T_LC**2

im5 = ax5.pcolormesh(X_LC, T_LC, cone, cmap='seismic', shading='auto', vmin=-5, vmax=5)
ax5.contour(X_LC, T_LC, cone, levels=[0], colors='yellow', linewidths=3)

# Stereographic points on the cone
t_pts = np.linspace(-3, 3, 50)
sx, sy = inv_stereo_1d(t_pts)
# Points on S¹ satisfy x²+y²=1, so x²+y²-1=0 (lightlike)
ax5.plot(sx, sy, 'wo', markersize=3, alpha=0.8)

ax5.set_xlabel('x (space)', fontsize=10)
ax5.set_ylabel('t (time)', fontsize=10)
ax5.set_title('⚡ L5: Lorentzian Structure\nStereo image is lightlike: x²+y²−1=0', fontsize=11, fontweight='bold')
ax5.set_aspect('equal')

# ═══ LANDSCAPE 6: Fractals / Apollonian (bottom-left) ═══
ax6 = fig.add_subplot(gs[2, 0])

# Simple Apollonian gasket via circle inversions
def apollonian_step(circles, parent_inversions):
    """One step of Apollonian gasket generation."""
    new_circles = []
    for cx, cy, r in parent_inversions:
        for c_cx, c_cy, c_r in circles:
            ix, iy = sphere_inversion(np.array([c_cx]), np.array([c_cy]), cx, cy, r)
            if np.isfinite(ix[0]):
                new_r = c_r * (r/np.sqrt((c_cx-cx)**2 + (c_cy-cy)**2 + 1e-10))**2
                new_circles.append((ix[0], iy[0], abs(new_r)))
    return new_circles

# Draw Apollonian-style fractal using Ford circles approach
for q in range(1, 60):
    for p in range(0, q+1):
        if np.gcd(p, q) == 1:
            cx = p / q
            r = 1 / (2 * q**2)
            circle = plt.Circle((cx, r), r, fill=True,
                              color=plt.cm.viridis(q/60), alpha=0.5,
                              linewidth=0.2, edgecolor='k')
            ax6.add_patch(circle)

ax6.set_xlim(-0.05, 1.05)
ax6.set_ylim(-0.01, 0.3)
ax6.set_aspect('equal')
ax6.set_title('🌀 L6: Apollonian Packings\nFord circles (stereographic shadow)', fontsize=11, fontweight='bold')
ax6.set_facecolor('#f0f0f8')

# ═══ SYNTHESIS MAP (bottom-center) ═══
ax_syn = fig.add_subplot(gs[2, 1])

# Draw the connection diagram
labels = ['Conformal\nGeometry', 'Harmonic\nAnalysis', 'Number\nTheory',
          'Hopf\nFibration', 'Lorentzian\nPhysics', 'Fractal\nPackings']
angles = np.linspace(0, 2*np.pi, 7)[:-1]
R_hex = 3
positions = [(R_hex*np.cos(a), R_hex*np.sin(a)) for a in angles]

# Draw connections (all-to-all)
for i in range(6):
    for j in range(i+1, 6):
        ax_syn.plot([positions[i][0], positions[j][0]],
                   [positions[i][1], positions[j][1]],
                   'gray', linewidth=0.5, alpha=0.3)

# Draw nodes
for i, (pos, label) in enumerate(zip(positions, labels)):
    color = plt.cm.Set2(i/6)
    circle = plt.Circle(pos, 0.9, color=color, alpha=0.8, zorder=5)
    ax_syn.add_patch(circle)
    ax_syn.text(pos[0], pos[1], label, ha='center', va='center',
               fontsize=8, fontweight='bold', zorder=6)

# Center node
center_circle = plt.Circle((0, 0), 1.2, color='gold', alpha=0.8, zorder=5)
ax_syn.add_patch(center_circle)
ax_syn.text(0, 0, 'σ⁻¹_N\nMöb(N)\n≅SO(N+1,1)', ha='center', va='center',
           fontsize=9, fontweight='bold', zorder=6)

# Spokes
for pos in positions:
    ax_syn.plot([0, pos[0]*0.65], [0, pos[1]*0.65], 'k-', linewidth=2, alpha=0.5)

ax_syn.set_xlim(-5, 5)
ax_syn.set_ylim(-5, 5)
ax_syn.set_aspect('equal')
ax_syn.axis('off')
ax_syn.set_title('Connection Map\nAll roads through stereographic projection', fontsize=11, fontweight='bold')

# ═══ LANDSCAPE 7: Dimensional Cascade (bottom-right) ═══
ax7 = fig.add_subplot(gs[2, 2])

# Show the stereographic tower: how dimensions connect
# S¹ → ℝ → S⁰, S² → ℝ² → S¹ → ℝ, etc.

# Conformal factor at different dimensions
r = np.linspace(0.01, 5, 500)
for N in [1, 2, 3, 4, 5, 8]:
    # In N dimensions, conformal factor is 2/(1+r²), but area element is (2/(1+r²))^N
    factor = (2/(1+r**2))**N
    ax7.semilogy(r, factor, linewidth=2, label=f'N={N}', alpha=0.8)

ax7.axvline(x=1, color='gray', linestyle='--', alpha=0.5)
ax7.annotate('Equator\n(r=1)', xy=(1, 0.01), fontsize=9)

ax7.set_xlabel('Distance from origin r', fontsize=10)
ax7.set_ylabel('Volume element λᴺ', fontsize=10)
ax7.set_title('📐 Volume Distortion by Dimension\nHigher N = more extreme compression', fontsize=11, fontweight='bold')
ax7.legend(fontsize=9, loc='upper right')
ax7.grid(True, alpha=0.3)

fig.suptitle('THE GRAND SYNTHESIS: Six Mathematical Landscapes\n'
            'United by N-Dimensional Inverse Stereographic Projection',
            fontsize=20, fontweight='bold', y=0.98,
            color='darkblue')

plt.savefig('/workspace/request-project/Stereographic/NDimensional/Demos/demo14_grand_synthesis.png',
           dpi=150, bbox_inches='tight')
plt.close()
print("✓ Demo 14 saved: demo14_grand_synthesis.png")
