/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Tropical geometry as the geometry of the field with one element

This file develops a precise, computable bridge between three worlds:

* the **min-plus (tropical) semiring** `(ℤ, min, +)`, whose defining feature is the
  *idempotency* of its addition — the algebraic fingerprint of a structure "with
  one element", where addition can never be inverted;
* the **combinatorics of lattice polytopes**, whose vertices play the role of the
  `F₁`-points of a tropical variety;
* the **topology of toric varieties** obtained by base change to `ℤ`, whose
  Euler characteristic we compute from the (Künneth-)Betti numbers of the fan.

The central correspondence proved here is:

> For every toric variety built from projective spaces by products, the
> Euler characteristic equals the number of vertices of the associated polytope
> (its `F₁`-points).

Concretely we model the class of toric varieties generated by projective spaces
`ℙ^d` (dual to the standard `d`-simplex `Δ_d`) under Cartesian product.  For such
a variety the odd Betti numbers vanish and the total Betti number is multiplicative
(Künneth), so the alternating sum defining the Euler characteristic collapses to a
plain vertex count.  The theorem `eulerChar_eq_vertices` makes this exact.

This realises, in a fully computable form, the slogan that *the field with one
element is tropical*: the `F₁`-cardinality of a tropical variety (its vertices)
is exactly the Euler characteristic of its base change to a toric variety.

-- !-- Lab Notes -- !--
Hypothesis (Hypothesizer): The tropical/`F₁` "cardinality" of a variety — the
  number of vertices of its Newton polytope — should be a topological invariant of
  the base-changed toric variety, namely its Euler characteristic.
Experiment (Experimenter): Model the projective toric class inductively
  (`ToricPoly`), define Betti numbers via the simplex spectrum and the Künneth
  antidiagonal convolution, and compute the Euler characteristic as the true
  alternating sum. Numerics: χ(ℙ²×ℙ³)=12=3·4, χ(ℙ⁵)=6, χ((ℙ¹)³)=8 — all equal to
  the vertex counts.
Analysis (Analyst): The identity survives because (a) odd Betti numbers vanish, so
  the signs in χ never contribute cancellation, and (b) total Betti number is
  multiplicative under products (Cauchy product of supported sequences), matching
  the multiplicativity of vertex counts of product polytopes.
Critique (Critic): The Euler characteristic is defined honestly as a signed sum,
  not as the vertex count; equality is a theorem, not a definition. The min-plus
  axioms establish genuine idempotency, distinguishing `F₁`/tropical addition from
  ring addition (no additive inverses).
Synthesis (PI): `eulerChar_eq_vertices` is the quantitative shadow of the
  conjectural equivalence "tropical schemes ≃ `F₁`-schemes".
-- !-- End Lab Notes -- !--
-/

namespace Tropical.FieldOneElement

open Finset

/-! ## Part 1 — The min-plus (tropical / `F₁`) semiring

Tropical addition is `min` and tropical multiplication is ordinary `+`.  The
algebraic signature of the field with one element is that this addition is
*idempotent* and admits *no additive inverses*: one can never solve `min a x = ∞`.
We record the semiring axioms and the two `F₁`-fingerprint properties. -/

/-- Tropical addition (`min`) is idempotent: the `F₁` fingerprint. -/
theorem trop_add_idem (a : ℤ) : min a a = a := by simp

/-- Tropical addition is commutative. -/
theorem trop_add_comm (a b : ℤ) : min a b = min b a := min_comm a b

/-- Tropical addition is associative. -/
theorem trop_add_assoc (a b c : ℤ) : min (min a b) c = min a (min b c) :=
  (min_assoc a b c)

/-- Tropical multiplication (`+`) distributes over tropical addition (`min`):
    this is the semiring distributive law in min-plus form. -/
theorem trop_mul_distrib (a b c : ℤ) : a + min b c = min (a + b) (a + c) := by
  omega

/-- Tropical multiplication is commutative and associative (it is `+` on `ℤ`),
    and `0` is its unit. -/
theorem trop_mul_unit (a : ℤ) : a + 0 = a := by ring

/-- The `F₁` fingerprint, negative form: min-plus addition has **no inverses**.
    There is no `x` with `min a x` strictly below both `a` and any target `t < a`;
    equivalently `min a x ≥ min a x` can never drop below `a` unless `x` already
    witnesses it.  Concretely: if `min a x = c` then `c = a` or `c = x`, so one
    cannot "cancel" `a` to reach an arbitrary value.  This is what forbids
    subtraction and marks the structure as living over `F₁` rather than a ring. -/
theorem trop_no_cancellation (a x c : ℤ) (h : min a x = c) : c = a ∨ c = x := by
  rcases le_total a x with hax | hax
  · left; rw [← h, min_eq_left hax]
  · right; rw [← h, min_eq_right hax]

/-! ## Part 2 — Toric varieties from projective spaces, and their polytopes

We model the class of toric varieties generated by the projective spaces `ℙ^d`
(dual to the standard `d`-simplex) under Cartesian product.  This is exactly the
class of *products of projective spaces*; the corresponding polytopes are products
of simplices. -/

/-- A toric variety built from projective spaces `ℙ^d` under products.
    `simplex d` denotes `ℙ^d` (dual to the standard `d`-simplex `Δ_d`). -/
inductive ToricPoly where
  | simplex (d : ℕ) : ToricPoly
  | prod : ToricPoly → ToricPoly → ToricPoly
  deriving Repr

/-- The (complex) dimension of the toric variety / the dimension of the polytope. -/
def dim : ToricPoly → ℕ
  | .simplex d => d
  | .prod P Q => dim P + dim Q

/-- The number of vertices of the associated polytope — the `F₁`-points.
    `Δ_d` has `d+1` vertices; a product polytope's vertices multiply. -/
def vertices : ToricPoly → ℕ
  | .simplex d => d + 1
  | .prod P Q => vertices P * vertices Q

/-- The `k`-th Betti number of the toric variety.  For `ℙ^d` the cohomology is
    `ℤ` in each even degree `0, 2, …, 2d` and `0` otherwise.  Products obey the
    Künneth formula, i.e. the antidiagonal (Cauchy) convolution of Betti
    sequences. -/
def betti : ToricPoly → ℕ → ℕ
  | .simplex d, k => if k % 2 = 0 ∧ k ≤ 2 * d then 1 else 0
  | .prod P Q, k => ∑ ij ∈ antidiagonal k, betti P ij.1 * betti Q ij.2

/-- The Euler characteristic, defined honestly as the alternating sum of Betti
    numbers over the (nonzero) degree range `0 … 2·dim`. -/
def eulerChar (P : ToricPoly) : ℤ :=
  ∑ k ∈ range (2 * dim P + 1), (-1) ^ k * (betti P k : ℤ)

/-! ### Structural lemmas on Betti numbers -/

/-- Toric varieties in this class have **no odd cohomology**: all odd Betti
    numbers vanish. -/
theorem betti_odd (P : ToricPoly) (k : ℕ) (h : k % 2 = 1) : betti P k = 0 := by
  induction P generalizing k <;> simp_all +decide [ betti ];
  grind

/-- Betti numbers vanish above the top degree `2·dim`. -/
theorem betti_eq_zero_of_gt (P : ToricPoly) {k : ℕ} (h : 2 * dim P < k) :
    betti P k = 0 := by
  induction' P with P Q hP hQ generalizing k;
  · exact if_neg ( by aesop );
  · refine' Finset.sum_eq_zero fun x hx => _;
    simp_all +decide [ Finset.mem_antidiagonal, dim ];
    grind

/-- The total Betti number equals the number of vertices of the polytope.
    (Künneth multiplicativity of total Betti numbers matched with the
    multiplicativity of vertex counts of product polytopes.) -/
theorem sumBetti_eq_vertices (P : ToricPoly) :
    ∑ k ∈ range (2 * dim P + 1), betti P k = vertices P := by
  induction' P using ToricPoly.recOn with d P Q ihP ihQ;
  · simp +arith +decide [ dim, betti, vertices ];
    rw [ show Finset.filter ( fun x => x % 2 = 0 ∧ x ≤ 2 * d ) ( Finset.range ( 2 * d + 1 ) ) = Finset.image ( fun x => 2 * x ) ( Finset.range ( d + 1 ) ) from ?_, Finset.card_image_of_injective ] <;> norm_num [ Function.Injective ];
    ext x; simp [Finset.mem_image];
    exact ⟨ fun h => ⟨ x / 2, by omega, by omega ⟩, fun ⟨ a, ha, ha' ⟩ => ⟨ by omega, by omega, by omega ⟩ ⟩;
  · -- By the properties of the Betti numbers and the Künneth formula, we can expand the sum.
    have h_expand : ∑ k ∈ Finset.range (2 * (dim P + dim Q) + 1), (∑ ij ∈ Finset.antidiagonal k, betti P ij.1 * betti Q ij.2) = (∑ i ∈ Finset.range (2 * dim P + 1), betti P i) * (∑ j ∈ Finset.range (2 * dim Q + 1), betti Q j) := by
      have h_cauchy : ∀ (a b : ℕ → ℕ) (m n : ℕ), (∀ i > m, a i = 0) → (∀ j > n, b j = 0) → ∑ k ∈ Finset.range (m + n + 1), ∑ ij ∈ Finset.antidiagonal k, a ij.1 * b ij.2 = (∑ i ∈ Finset.range (m + 1), a i) * (∑ j ∈ Finset.range (n + 1), b j) := by
        intros a b m n ha hb;
        rw [ Finset.sum_mul_sum ];
        rw [ Finset.sum_sigma' ];
        rw [ ← Finset.sum_subset ( show Finset.image ( fun x : ℕ × ℕ => ⟨ x.1 + x.2, x ⟩ ) ( Finset.product ( Finset.range ( m + 1 ) ) ( Finset.range ( n + 1 ) ) ) ⊆ Finset.sigma ( Finset.range ( m + n + 1 ) ) antidiagonal from ?_ ) ];
        · rw [ Finset.sum_image ] <;> norm_num [ Finset.sum_product ];
        · simp +zetaDelta at *;
          grind;
        · simp +decide [ Finset.subset_iff ];
          grind;
      rw [show 2 * (dim P + dim Q) + 1 = 2 * dim P + 2 * dim Q + 1 from by ring]
      exact h_cauchy _ _ (2 * dim P) (2 * dim Q)
        (fun i hi => betti_eq_zero_of_gt P (by linarith))
        (fun j hj => betti_eq_zero_of_gt Q (by linarith))
    aesop

/-! ### The main correspondence -/

/-- **Tropical–`F₁` Euler correspondence.**  For every toric variety obtained
    from projective spaces by products, the Euler characteristic of the base
    change to `ℤ` equals the number of `F₁`-points (vertices of the polytope). -/
theorem eulerChar_eq_vertices (P : ToricPoly) : eulerChar P = vertices P := by
  -- Since each term in the sum equals `(betti P k : ℤ)`, the sum simplifies to `vertices P`.
  have h_sum : eulerChar P = ∑ k ∈ Finset.range (2 * dim P + 1), (betti P k : ℤ) := by
    refine' Finset.sum_congr rfl _;
    intro k hk; by_cases h : Even k <;> simp_all +decide ;
    exact betti_odd P k ( Nat.odd_iff.mp h );
  exact h_sum.trans ( mod_cast sumBetti_eq_vertices P )

/-- Explicit instances of the correspondence: `χ(ℙ⁵)=6`, `χ(ℙ²×ℙ³)=12`,
    `χ((ℙ¹)³)=8`, each matching the vertex count of the polytope. -/
example : eulerChar (.simplex 5) = 6 := by rw [eulerChar_eq_vertices]; decide
example : eulerChar (.prod (.simplex 2) (.simplex 3)) = 12 := by
  rw [eulerChar_eq_vertices]; decide
example : eulerChar (.prod (.prod (.simplex 1) (.simplex 1)) (.simplex 1)) = 8 := by
  rw [eulerChar_eq_vertices]; decide

end Tropical.FieldOneElement