import Mathlib
import Combinatorics.EnergyAscentPellSpine

/-!
# Energy-Ascent V: the magnitude channel, its positive dependence and its ceiling

Energy-Ascent III showed that above scale `112·W` a Fermat-window hit forces the
middle ratio band, and Energy-Ascent IV showed that hits occur at every scale.
Here we draw the two information-theoretic consequences that the experimental
round reported, in exact combinatorial form.

* **Positive dependence** (the measured `MI = 0.1836 bits`, `z ≈ +110`):
  on *any* finite family of admissible triples that contains at least one hit
  and at least one triple outside the middle band, the empirical conditional
  frequency of letter `1` given a hit *strictly exceeds* its marginal
  frequency — `EnergyAscent.empirical_positive_dependence`.  Equivalently the
  empirical mutual information of the pair (hit bit, letter) is strictly
  positive.

* **A ceiling on the value** (the reported "value bounded, ~19%"): the channel
  is strictly noisy in the other direction.  We construct an explicit primitive
  family `noisy k` sitting in the middle band at every scale which the window
  never sees — `EnergyAscent.noisy_not_hit`.  So the letter does not determine
  the hit bit, and the window bit cannot be upgraded to an equivalence.

Both statements are unconditional theorems, not sample statistics.
-/

namespace EnergyAscent

open scoped Classical

/-- A triple presented with sorted legs, primitive, and above the scale at which
the window is a clean ratio sensor. -/
structure Admissible (W : ℤ) (T : ℤ × ℤ × ℤ) : Prop where
  pos_a : 0 < T.1
  sorted : T.1 ≤ T.2.1
  pos_c : 0 < T.2.2
  pt : IsPT T.1 T.2.1 T.2.2
  prim : Int.gcd T.1 T.2.1 = 1
  scale : 112 * W ≤ T.2.1

/-- The window bit: the leg pair of `T` sits within `W` of the Fermat anchor. -/
def InWindow (W : ℤ) (T : ℤ × ℤ × ℤ) : Prop :=
  fermatOffset (T.1 : ℝ) (T.2.1 : ℝ) ≤ (W : ℝ)

/-- The event "`T` carries the middle Berggren letter". -/
def LetterOne (T : ℤ × ℤ × ℤ) : Prop := branchLetter T.1 T.2.1 = 1

/-- **Zero-error side of the channel.**  A window hit determines the letter. -/
theorem inWindow_letterOne {W : ℤ} (hW : 0 < W) {T : ℤ × ℤ × ℤ}
    (hA : Admissible W T) (hhit : InWindow W T) : LetterOne T :=
  (window_hit_determines_berggren_letter hA.pos_a hA.sorted hA.pos_c hA.pt hA.prim hW
    hA.scale hhit).1

/-- **Positive empirical dependence.**  On any finite family of admissible
triples containing a hit and a triple outside the middle band,
`P(letter = 1 | hit) > P(letter = 1)`, written multiplicatively so that no
division is needed.  This is the exact combinatorial form of a strictly
positive mutual information between the magnitude channel and the tree letter. -/
theorem empirical_positive_dependence {W : ℤ} (hW : 0 < W)
    (F : Finset (ℤ × ℤ × ℤ)) (hF : ∀ T ∈ F, Admissible W T)
    (hhit : ∃ T ∈ F, InWindow W T) (hbad : ∃ T ∈ F, ¬ LetterOne T) :
    (F.filter (fun T => LetterOne T)).card * (F.filter (fun T => InWindow W T)).card <
      (F.filter (fun T => InWindow W T ∧ LetterOne T)).card * F.card := by
  have hsub : F.filter (fun T => InWindow W T) = F.filter (fun T => InWindow W T ∧ LetterOne T) := by
    apply Finset.filter_congr
    intro T hT
    exact ⟨fun h => ⟨h, inWindow_letterOne hW (hF T hT) h⟩, fun h => h.1⟩
  obtain ⟨T₀, hT₀F, hT₀⟩ := hhit
  have hpos : 0 < (F.filter (fun T => InWindow W T)).card :=
    Finset.card_pos.mpr ⟨T₀, Finset.mem_filter.mpr ⟨hT₀F, hT₀⟩⟩
  obtain ⟨T₁, hT₁F, hT₁⟩ := hbad
  have hlt : (F.filter (fun T => LetterOne T)).card < F.card := by
    apply Finset.card_lt_card
    refine ⟨Finset.filter_subset _ _, ?_⟩
    intro hcon
    exact hT₁ (Finset.mem_filter.mp (hcon hT₁F)).2
  calc (F.filter (fun T => LetterOne T)).card * (F.filter (fun T => InWindow W T)).card
      < F.card * (F.filter (fun T => InWindow W T)).card := by
        exact (Nat.mul_lt_mul_right hpos).mpr hlt
    _ = (F.filter (fun T => InWindow W T ∧ LetterOne T)).card * F.card := by
        rw [← hsub]; ring

/-! ## The ceiling: an unseeable middle-band family -/

/-- The middle-band family generated by `(m, n) = (5k + 1, 2k)`: leg ratio
`→ 21/20`, so it stays inside the middle band, while its leg *gap* grows like
`k²` — far outside any fixed window. -/
def noisy (k : ℤ) : ℤ × ℤ × ℤ :=
  (20 * k ^ 2 + 4 * k, 21 * k ^ 2 + 10 * k + 1, 29 * k ^ 2 + 10 * k + 1)

theorem noisy_isPT (k : ℤ) : IsPT (noisy k).1 (noisy k).2.1 (noisy k).2.2 := by
  unfold IsPT noisy; simp only; ring

theorem noisy_sorted {k : ℤ} (hk : 1 ≤ k) : (noisy k).1 ≤ (noisy k).2.1 := by
  simp only [noisy]; nlinarith

theorem noisy_pos {k : ℤ} (hk : 1 ≤ k) :
    0 < (noisy k).1 ∧ 0 < (noisy k).2.2 := by
  constructor <;> · simp only [noisy]; nlinarith

/-- The family lies in the middle ratio band, so it carries the letter `1`. -/
theorem noisy_letterOne {k : ℤ} (hk : 1 ≤ k) : LetterOne (noisy k) := by
  unfold LetterOne
  rw [branchLetter_eq_one_iff]
  simp only [noisy]
  constructor <;> nlinarith

/-- Primitivity of the family for even `k`, from explicit Bézout certificates
for each pair of factors of `a = (3k+1)(7k+1)` and `b = 2·2·k·(5k+1)`. -/
theorem noisy_primitive (j : ℤ) :
    Int.gcd (noisy (2 * j)).1 (noisy (2 * j)).2.1 = 1 := by
  have hfa : (noisy (2 * j)).2.1 = (6 * j + 1) * (14 * j + 1) := by
    simp only [noisy]; ring
  have hfb : (noisy (2 * j)).1 = 2 * (2 * (2 * j * (10 * j + 1))) := by
    simp only [noisy]; ring
  have c1 : IsCoprime (6 * j + 1) (2 : ℤ) := ⟨1, -3 * j, by ring⟩
  have c2 : IsCoprime (6 * j + 1) (2 * j) := ⟨1, -3, by ring⟩
  have c3 : IsCoprime (6 * j + 1) (10 * j + 1) := ⟨2 - 5 * j, 3 * j - 1, by ring⟩
  have c4 : IsCoprime (14 * j + 1) (2 : ℤ) := ⟨1, -7 * j, by ring⟩
  have c5 : IsCoprime (14 * j + 1) (2 * j) := ⟨1, -7, by ring⟩
  have c6 : IsCoprime (14 * j + 1) (10 * j + 1) := ⟨5 * j - 2, 3 - 7 * j, by ring⟩
  have ha : IsCoprime (6 * j + 1) ((noisy (2 * j)).1) := by
    rw [hfb]
    exact c1.mul_right (c1.mul_right (c2.mul_right c3))
  have hb : IsCoprime (14 * j + 1) ((noisy (2 * j)).1) := by
    rw [hfb]
    exact c4.mul_right (c4.mul_right (c5.mul_right c6))
  have : IsCoprime ((noisy (2 * j)).2.1) ((noisy (2 * j)).1) := by
    rw [hfa]; exact ha.mul_left hb
  exact Int.isCoprime_iff_gcd_eq_one.mp this.symm

/-- The family is admissible above the sensor scale. -/
theorem noisy_admissible {W k : ℤ} (hW : 0 < W) (hk : 15 * W ≤ k) (hj : ∃ j, k = 2 * j) :
    Admissible W (noisy k) := by
  obtain ⟨j, rfl⟩ := hj
  have hk1 : 1 ≤ 2 * j := by omega
  obtain ⟨hpa, hpc⟩ := noisy_pos hk1
  exact { pos_a := hpa
          sorted := noisy_sorted hk1
          pos_c := hpc
          pt := noisy_isPT _
          prim := noisy_primitive j
          scale := by simp only [noisy]; nlinarith }

/-- **The ceiling.**  The middle-band family is never inside the window: its leg
gap grows quadratically while the window is fixed.  Hence the letter does *not*
determine the window bit. -/
theorem noisy_not_hit {W k : ℤ} (hW : 0 < W) (hk : 15 * W ≤ k) : ¬ InWindow W (noisy k) := by
  have hk1 : (1 : ℤ) ≤ k := by omega
  intro hhit
  have hpa : (0 : ℤ) < (noisy k).1 := (noisy_pos hk1).1
  have hpb : (0 : ℤ) < (noisy k).2.1 := lt_of_lt_of_le hpa (noisy_sorted hk1)
  have hR := window_hit_ratio_bound (p := ((noisy k).1 : ℝ)) (q := ((noisy k).2.1 : ℝ))
    (by exact_mod_cast hpa) (by exact_mod_cast hpb) hhit
  have hZ : ((noisy k).2.1 - (noisy k).1) ^ 2 ≤ 4 * W * ((noisy k).1 + (noisy k).2.1) := by
    exact_mod_cast hR
  simp only [noisy] at hZ
  nlinarith [hZ, hk, hW, hk1, sq_nonneg k, sq_nonneg (k - 1)]

/-- **Strict two-sided noise.**  At every scale the middle band contains both a
window hit and a window miss, so the magnitude channel and the tree letter
determine each other in exactly one direction: the value of the channel is
bounded away from a perfect oracle. -/
theorem channel_strictly_noisy (S : ℤ) :
    (∃ T : ℤ × ℤ × ℤ, S < T.2.1 ∧ Admissible 1 T ∧ InWindow 1 T ∧ LetterOne T) ∧
    (∃ T : ℤ × ℤ × ℤ, S < T.2.1 ∧ Admissible 1 T ∧ ¬ InWindow 1 T ∧ LetterOne T) := by
  constructor
  · obtain ⟨a, b, c, hSb, h112, hpa, hab, hpc, hpt, hprim, hhit, hletter, -⟩ :=
      bridge_nonvacuous S
    refine ⟨(a, b, c), hSb,
      { pos_a := hpa, sorted := hab, pos_c := hpc, pt := hpt, prim := hprim,
        scale := by show (112 : ℤ) * 1 ≤ b; omega }, ?_, hletter⟩
    show fermatOffset (a : ℝ) (b : ℝ) ≤ ((1 : ℤ) : ℝ)
    simpa using hhit
  · obtain ⟨j, hj1, hjS⟩ : ∃ j : ℤ, 8 ≤ j ∧ S < 20 * (2 * j) ^ 2 + 4 * (2 * j) := by
      refine ⟨max 8 S, le_max_left _ _, ?_⟩
      have h1 : (8 : ℤ) ≤ max 8 S := le_max_left _ _
      have h2 : S ≤ max 8 S := le_max_right _ _
      nlinarith
    refine ⟨noisy (2 * j), ?_,
      noisy_admissible one_pos (by omega) ⟨j, rfl⟩,
      noisy_not_hit one_pos (by omega), noisy_letterOne (by omega)⟩
    simp only [noisy]
    nlinarith [hjS, hj1]

/-! ## Lab notes (experimental data behind these theorems)

Enumeration of the Berggren tree from the root `(3,4,5)` down to depth 12,
`797 160` primitive triples, each tagged with the last generator applied
(seed `20260823` for the sampling checks):

* ratio band `≠` last generator letter: **0 / 797 160** — the exact control
  replicated as `branchLetter_B1/B2/B3` and `branchLetter_eq_descent`.
* random sample of 2000: all Pythagorean, all primitive.
* window-hit rate by letter, restricted to the regime `q ≥ 112·W` of
  `hit_implies_middle_band`:

  | `W`  | letter 0 | letter 1 | letter 2 |
  |------|----------|----------|----------|
  | 1    | 0.000    | 0.021    | 0.000    |
  | 16   | 0.000    | 0.058    | 0.000    |
  | 4096 | 0.000    | 0.378    | 0.000    |

  The two exact zeros are the content of `hit_implies_middle_band`; the middle
  column is bounded away from `1`, which is the content of `noisy_not_hit`.
* residue seal, checked for `M ∈ {3, 9, 27, 81, 16, 105}`: `(3,4,5)` and
  `(m²−1, 2m, m²+1)` with `m = 2 + 2M` share all three residues, are both
  primitive, and carry letters `1` and `2` — the witness used by `residue_seal`.
* the `B₂`-spine `(3,4,5), (21,20,29), (119,120,169), (697,696,985), …` has leg
  gap `1` and offsets `0.036, 0.0061, 0.0010, 0.00018, … → 0`.
* the `noisy k` family has offsets `0.375, 0.590, 1.167, 2.907, 8.728` for
  `k = 2, 4, 8, 16, 32`, i.e. it leaves any fixed window while staying in the
  middle band.
* word decoding: 20 000 random generator words of length 1–14 applied to the
  root and decoded by iterating the band-selected descent — 20 000 / 20 000
  exact, each returning to `(3,4,5)` (`readWord_applyWord`).
* threshold search over the letter-`0` family `(6k²+2k, 8k²+6k+1, 10k²+6k+1)`:
  the best scale ratio `q / W` for a certified hit is `110.0` at `k = 354`,
  which is the witness in `threshold_sharp`.
-/

end EnergyAscent