import Physics.AdjacencyDegree.EdgeStatistics
import Physics.AdjacencyDegree.OrbitEquality
import Physics.AdjacencyDegree.Equitable
import Physics.AdjacencyDegree.RegularFailure
import Physics.AdjacencyDegree.SixVertexWitness

/-!
# Synthesis: what the adjacency-degree moments do and do not see

This file collects the two ends of the picture.

* `AdjDeg.moment_mul_J_mul` : the ideal `𝒜(G) J 𝒜(G)` (with `J = 𝟏𝟏ᵀ`) contributes nothing
  new at the level of scalar moments — its moments factor as products of word moments.
  Hence "principal" moment data is exactly the word data.
* `AdjDeg.starGraph_determined_by_moments` : within the family of stars (an infinite family of
  trees) the moments determine the graph up to isomorphism — a verified instance of the
  McKay-type determination statement.
* `AdjDeg.moment_dichotomy` : trees can be separated by moments in the star family while
  `2`-regular graphs of the same order never are; the two statements together delimit the
  determination theorem.
-/

namespace AdjDeg

open Matrix Finset

variable {V : Type*} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

/-- The all-ones matrix `J = 𝟏𝟏ᵀ`. -/
def onesMatrix : Matrix V V ℝ := Matrix.of fun _ _ => (1 : ℝ)

omit [DecidableEq V] in
/-- **Moments of the ideal `𝒜 J 𝒜` factor.** For any two matrices,
`𝟏ᵀ X J Y 𝟏 = (𝟏ᵀ X 𝟏)(𝟏ᵀ Y 𝟏)`; in particular the ideal generated by `J` produces no scalar
information beyond the word moments. -/
theorem moment_mul_J_mul (X Y : Matrix V V ℝ) :
    moment (X * (onesMatrix : Matrix V V ℝ) * Y) = moment X * moment Y := by
  have hentry : ∀ u v : V, (X * (onesMatrix : Matrix V V ℝ) * Y) u v
      = (∑ s, X u s) * ∑ t, Y t v := by
    intro u v
    simp only [Matrix.mul_apply, onesMatrix, Matrix.of_apply, mul_one]
    rw [Finset.mul_sum]
  rw [moment_eq_sum' (X * (onesMatrix : Matrix V V ℝ) * Y)]
  simp only [hentry]
  rw [moment_eq_sum' X, moment_eq_sum Y, Finset.sum_mul]
  exact Finset.sum_congr rfl fun u _ => (Finset.mul_sum _ _ _).symm

/-! ## Determination inside the star family -/

/-- The number of vertices of a star. -/
@[simp] lemma card_starGraph_vertices (n : ℕ) : Fintype.card (Fin (n + 1)) = n + 1 := by
  simp

/-- **Moments determine a star.** -/
theorem starGraph_determined_by_moments {n m : ℕ}
    (h : ∀ w : List Letter, wordMoment (starGraph n) w = wordMoment (starGraph m) w) :
    n = m := by
  have := card_eq_of_wordMoment_eq (starGraph n) (starGraph m) h
  simpa using this

/-- Moment equality inside the star family implies isomorphism. -/
theorem starGraph_iso_of_moments {n m : ℕ}
    (h : ∀ w : List Letter, wordMoment (starGraph n) w = wordMoment (starGraph m) w) :
    Nonempty (starGraph n ≃g starGraph m) := by
  obtain rfl := starGraph_determined_by_moments h
  exact ⟨SimpleGraph.Iso.refl⟩

/-- **The dichotomy.** Inside the star family the moments determine the graph, while for
`2`-regular graphs of the same order they never do: `C₆` and two triangles are moment-equal
but non-isomorphic. -/
theorem moment_dichotomy :
    (∀ n m : ℕ, (∀ w : List Letter,
        wordMoment (starGraph n) w = wordMoment (starGraph m) w) →
        Nonempty (starGraph n ≃g starGraph m)) ∧
    ((∀ w : List Letter, wordMoment cyc6 w = wordMoment twoK3 w) ∧
      IsEmpty (cyc6 ≃g twoK3)) :=
  ⟨fun _ _ h => starGraph_iso_of_moments h, moments_do_not_determine_graphs⟩

/-- **Full summary of the moment-rigidity boundary.**  Moments determine a star; they do not
separate two-regular graphs of the same order; and they do not even separate connected,
non-regular graphs, already at six vertices. -/
theorem moment_rigidity_boundary :
    (∀ n m : ℕ, (∀ w : List Letter,
        wordMoment (starGraph n) w = wordMoment (starGraph m) w) →
        Nonempty (starGraph n ≃g starGraph m)) ∧
    ((∀ w : List Letter, wordMoment cyc6 w = wordMoment twoK3 w) ∧ IsEmpty (cyc6 ≃g twoK3)) ∧
    ((∀ w : List Letter, wordMoment hex1 w = wordMoment hex2 w) ∧ IsEmpty (hex1 ≃g hex2) ∧
      hex1.Connected ∧ hex2.Connected) :=
  ⟨fun _ _ h => starGraph_iso_of_moments h, moments_do_not_determine_graphs,
    hex_wordMoment_eq, hex_not_iso, hex1_connected, hex2_connected⟩

end AdjDeg