#!/usr/bin/env python3
"""Demo: Full AETHER pipeline with Pi-Agent + PromptEngine + Aristotle artifacts."""

import asyncio
import textwrap
from pathlib import Path

from pi_agent_client import PiAgentClient, ResearchConcept
from prompt_engine import PromptEngine, ArtifactRequests
from aristotle_sdk_client import AristotleSDKClient


async def main():
    print("=" * 70)
    print("AETHER FULL PIPELINE DEMO")
    print("=" * 70)

    # 1. Pi-Agent generates concept
    print("\n[1] Pi-Agent generating breakthrough concept...")
    pi = PiAgentClient()
    concept = pi.generate_breakthrough_concept(
        domain="factoring",
        seed_concepts=["Berggren tree", "tropical matrix rank", "p-adic Newton polygon"],
        target="theorem",
    )
    print(f"    Title: {concept.title}")
    print(f"    Novelty: {concept.novelty_estimate:.2f}")
    print(f"    Breakthrough: {concept.breakthrough_potential:.2f}")

    # 2. PromptEngine optimizes for Aristotle
    print("\n[2] Optimizing Aristotle prompt with artifact requests...")
    engine = PromptEngine()
    prompt = engine.build_prompt(
        title=concept.title,
        domain="factoring",
        concept_description=concept.concept_description,
        mathematical_framing=concept.mathematical_framing,
        lean_guess=concept.lean_guess,
        difficulty="phd",
        artifacts=ArtifactRequests(
            lean_proof=True,
            research_report=True,
            python_demo=True,
            svg_demo=True,
            sciam_discussion=True,
        ),
    )
    print(f"    Prompt length: {len(prompt.prompt_text)} chars")
    print(f"    Expected artifacts: {prompt.expected_artifacts}")

    # 3. Generate Lean source
    print("\n[3] Generating Lean 4 source...")
    lean_source = textwrap.dedent(f"""\
        import Mathlib

        /-! # AETHER.AutoResearch.{concept.title}
        Auto-generated by AETHER Daemon.
        Domain: factoring
        Arc: Gravitational Factoring
        Novelty: {concept.novelty_estimate:.2f}
        -/

        /-- {concept.concept_description}

        Mathematical Concept: {concept.mathematical_framing}
        -/
        theorem {concept.title.lower().replace(' ', '_')}_breakthrough
            {{p : ℕ}} [Fact p.Prime] (n : ℕ) (hn : n > 1) :
            ∃ a b : ℕ, a * b = n ∧ a > 1 ∧ b > 1 := by
          sorry
    """)
    print(f"    Lean source: {len(lean_source)} chars")

    # 4. Dispatch to Aristotle
    print("\n[4] Dispatching to Aristotle...")
    aristotle = AristotleSDKClient({})

    project_dir = Path("./demo_pipeline_job")
    catalog_root = Path("/home/raver1975/lean/Catalog")

    result = await aristotle.submit_with_catalog_context(
        lean_source=lean_source,
        catalog_root=catalog_root,
        project_dir=project_dir,
        prompt=prompt.prompt_text,
    )

    print(f"    Project ID: {result.project_id}")
    print(f"    Status: {result.status}")
    print(f"    Latency: {result.latency_seconds:.1f}s")

    if result.lean_source:
        print(f"    Proof returned: {len(result.lean_source)} chars")
        # Save proof
        proof_file = project_dir / "PROOF.lean"
        proof_file.write_text(result.lean_source, encoding="utf-8")
        print(f"    Proof saved to: {proof_file}")
    else:
        print("    No proof returned (may still be processing or failed)")

    print("\n" + "=" * 70)
    print("DEMO COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    asyncio.run(main())
