import Mathlib

/-!
# Bergman fans and matroidal tropical linear spaces

This file uses Mathlib's `Matroid` and `Matroid.IsCircuit`.  A circuit tropical
polynomial has all coefficients zero, so its corner locus consists of weights
whose minimum on the circuit is attained at least twice.  The Bergman fan is
defined by imposing this condition on every circuit.
-/

open Set
open scoped Topology

namespace TropicalMatroid

variable {α : Type*}

/-- The minimum of `w` on `C` is attained at two distinct elements. -/
def MinAttainedTwice (C : Set α) (w : α → ℝ) : Prop :=
  ∃ e ∈ C, ∃ f ∈ C, e ≠ f ∧
    (∀ x ∈ C, w e ≤ w x) ∧ w f = w e

/-- The circuit ideal, represented by the supports of its circuit generators. -/
def CircuitIdeal (M : Matroid α) : Set (Set α) :=
  {C | M.IsCircuit C}

/-- The tropical zero set cut out by a family of supports. -/
def TropicalLinearSpace (I : Set (Set α)) : Set (α → ℝ) :=
  {w | ∀ C ∈ I, MinAttainedTwice C w}

/-- The Bergman fan of a matroid: every circuit minimum occurs at least twice. -/
def BergmanFan (M : Matroid α) : Set (α → ℝ) :=
  {w | ∀ C, M.IsCircuit C → MinAttainedTwice C w}

/-- The Bergman fan is exactly the tropical linear space of the circuit ideal. -/
theorem bergmanFan_eq_tropicalLinearSpace_circuitIdeal (M : Matroid α) :
    BergmanFan M = TropicalLinearSpace (CircuitIdeal M) := by
  ext w
  constructor <;> intro hw C hC <;> exact hw C hC

/-- Adding a scalar to every coordinate preserves a repeated circuit minimum. -/
theorem minAttainedTwice_add_const {C : Set α} {w : α → ℝ}
    (h : MinAttainedTwice C w) (c : ℝ) :
    MinAttainedTwice C (fun e => w e + c) := by
  obtain ⟨e, he, f, hf, hef, hmin, heq⟩ := h
  exact ⟨e, he, f, hf, hef, fun x hx => by simp [hmin x hx], by simp [heq]⟩

/-- Multiplication by a nonnegative scalar preserves a repeated circuit minimum. -/
theorem minAttainedTwice_nonneg_smul {C : Set α} {w : α → ℝ}
    (h : MinAttainedTwice C w) {a : ℝ} (ha : 0 ≤ a) :
    MinAttainedTwice C (fun e => a * w e) := by
  obtain ⟨e, he, f, hf, hef, hmin, heq⟩ := h
  exact ⟨e, he, f, hf, hef, fun x hx => mul_le_mul_of_nonneg_left (hmin x hx) ha, by simp [heq]⟩

/-- Bergman fans are invariant under tropical scalar multiplication (constant translation). -/
theorem bergmanFan_add_const_iff (M : Matroid α) (w : α → ℝ) (c : ℝ) :
    (fun e => w e + c) ∈ BergmanFan M ↔ w ∈ BergmanFan M := by
  constructor
  · intro hw C hC
    have h' := minAttainedTwice_add_const (hw C hC) (-c)
    simp at h'
    exact h'
  · intro hw C hC
    exact minAttainedTwice_add_const (hw C hC) c

/-- Bergman fans are closed under ordinary nonnegative dilation. -/
theorem bergmanFan_nonneg_smul (M : Matroid α) {w : α → ℝ}
    (hw : w ∈ BergmanFan M) {a : ℝ} (ha : 0 ≤ a) :
    (fun e => a * w e) ∈ BergmanFan M := by
  intro C hC
  apply minAttainedTwice_nonneg_smul (hw C hC) ha

/-- A set of weights is a tropical linear cone when it is invariant under
constant translation and closed under nonnegative dilation. -/
def IsTropicalLinearCone (S : Set (α → ℝ)) : Prop :=
  (∀ w c, (fun e => w e + c) ∈ S ↔ w ∈ S) ∧
  ∀ w ∈ S, ∀ a : ℝ, 0 ≤ a → (fun e => a * w e) ∈ S

/-- Every Bergman fan has the two fundamental tropical linear-cone symmetries. -/
theorem bergmanFan_isTropicalLinearCone (M : Matroid α) :
    IsTropicalLinearCone (BergmanFan M) := by
  exact ⟨bergmanFan_add_const_iff M,
    fun w hw a ha => bergmanFan_nonneg_smul M hw ha⟩

/-- A set is cyclic when each of its elements belongs to a circuit contained in it. -/
def IsCyclicSet (M : Matroid α) (X : Set α) : Prop :=
  ∀ e ∈ X, ∃ C, M.IsCircuit C ∧ e ∈ C ∧ C ⊆ X

/-- A cyclic flat is simultaneously a flat and a union of circuits. -/
def IsCyclicFlat (M : Matroid α) (X : Set α) : Prop :=
  M.IsFlat X ∧ IsCyclicSet M X

/-- A nested matroid is one whose cyclic flats form a chain under inclusion. -/
def IsNested (M : Matroid α) : Prop :=
  ∀ ⦃F G⦄, IsCyclicFlat M F → IsCyclicFlat M G → F ⊆ G ∨ G ⊆ F

/-- Nested matroids in particular have Bergman fans that are tropical linear cones. -/
theorem IsNested.bergmanFan_isTropicalLinearCone {M : Matroid α}
    (hM : IsNested M) : IsTropicalLinearCone (BergmanFan M) := by
  have _ := hM
  exact TropicalMatroid.bergmanFan_isTropicalLinearCone M

/-- Two elements are circuit-adjacent when one circuit contains both. -/
def CircuitAdjacent (M : Matroid α) (e f : α) : Prop :=
  ∃ C, M.IsCircuit C ∧ e ∈ C ∧ f ∈ C

/-- Matroid component relation, generated by common-circuit adjacency. -/
def InSameComponent (M : Matroid α) : α → α → Prop :=
  Relation.ReflTransGen (CircuitAdjacent M)

/-- Connectivity formulated through the circuit components of the ground set. -/
def IsCircuitConnected (M : Matroid α) : Prop :=
  M.E.Nonempty ∧ ∀ ⦃e⦄, e ∈ M.E → ∀ ⦃f⦄, f ∈ M.E → InSameComponent M e f

/-- The lineality space consists of weights constant on every circuit. -/
def BergmanLineality (M : Matroid α) : Set (α → ℝ) :=
  {v | ∀ C, M.IsCircuit C → ∀ e ∈ C, ∀ f ∈ C, v e = v f}

/-- Circuitwise constancy is equivalent to constancy on circuit components. -/
theorem mem_bergmanLineality_iff_component_constant (M : Matroid α) (v : α → ℝ) :
    v ∈ BergmanLineality M ↔
      ∀ ⦃e f⦄, InSameComponent M e f → v e = v f := by
  constructor
  · intro hv hf f hf'
    induction hf' with
    | refl => rfl
    | tail _ ih ih' =>
      obtain ⟨C, hC, he, hf⟩ := ih
      rw [ih', hv C hC _ he _ hf]
  · intro hv C hC e he f hf
    exact hv (Relation.ReflTransGen.single ⟨C, hC, he, hf⟩)

/-- For a connected matroid, every lineality weight is constant on its ground set. -/
theorem IsCircuitConnected.lineality_constant_on_ground {M : Matroid α}
    (hM : IsCircuitConnected M) {v : α → ℝ} (hv : v ∈ BergmanLineality M)
    ⦃e⦄ (he : e ∈ M.E) ⦃f⦄ (hf : f ∈ M.E) : v e = v f := by
  rw [mem_bergmanLineality_iff_component_constant] at hv
  exact hv (hM.2 he hf)

/-- Constant translation is lineality for every matroid. -/
theorem constant_mem_bergmanLineality (M : Matroid α) (c : ℝ) :
    (fun _ => c) ∈ BergmanLineality M := by
  intro C _ e _ f _
  rfl

/-- The constant-translation orbit through a weight. -/
def TranslationOrbit (w : α → ℝ) : Set (α → ℝ) :=
  {v | ∃ c : ℝ, v = fun e => w e + c}

/-- A translation orbit is convex in the ambient real vector space. -/
theorem translationOrbit_convex (w : α → ℝ) : Convex ℝ (TranslationOrbit w) := by
  intro v1 hv1 v2 hv2 a b ha hb hab
  obtain ⟨c1, rfl⟩ := hv1
  obtain ⟨c2, rfl⟩ := hv2
  refine ⟨a * c1 + b * c2, ?_⟩
  ext e
  simp
  ring_nf
  linear_combination hab * w e

/-- Translation orbits are path connected. -/
theorem translationOrbit_isPathConnected (w : α → ℝ) :
    IsPathConnected (TranslationOrbit w) := by
  exact Convex.isPathConnected (translationOrbit_convex w) ⟨w, ⟨0, by simp⟩⟩

/-- The path-connected translation orbit of a Bergman weight stays in the Bergman fan. -/
theorem translationOrbit_subset_bergmanFan (M : Matroid α) {w : α → ℝ}
    (hw : w ∈ BergmanFan M) : TranslationOrbit w ⊆ BergmanFan M := by
  intro v hv
  obtain ⟨c, rfl⟩ := hv
  exact fun C hC => minAttainedTwice_add_const (hw C hC) c

end TropicalMatroid