-- This file was a path pointer to `../../Shared/NeuralHodge/Defs.lean` in the catalogue snapshot.
-- The target module is not present in this snapshot, so the pointer is kept as a
-- comment; the module is intentionally empty.