/-
# The Euler Brick Tree, VIII: how far a congruence certificate can reach

`Tropical.EulerBrickTree.Branch` produces an infinite *branch* of the brick tree
on which the space-diagonal condition provably fails, certified by a mod-`7`
nonresidue.  The obvious question is whether the same certificate can cover a
*thicker* part of the tree — a binary subtree, say, which would obstruct
exponentially many nodes at once.

This file proves that it cannot, and in a sharp, quantitative form.

* `mod7_sound` — the certificate really refutes the perfect-cuboid condition.
* `mod7_escape_two_steps` — for **every** integer triple, at least one of the
  four words `ε, A, AA, AB` in the first two Berggren generators leads to a node
  at which the mod-`7` certificate no longer applies.  (The underlying fact is a
  finite computation on the `343` residue states modulo `7`.)
* `mod7_no_binary_subtree` — consequently there is no node from which the whole
  binary subtree generated by `bergA` and `bergB` is mod-`7` certified: the
  branch of `Branch.lean` is *sharp*, the certificate is a one-dimensional, not
  a two-dimensional, phenomenon.
* `mod7_branch_sharp_at_15_8_17` — the concrete picture at the branch node
  `(15,8,17)`: the `bergB` child stays certified for ever, while the `bergA` and
  `bergC` children already escape the certificate.

The moral for the obstruction program: a single congruence obstructs a set of
nodes of *zero density* in the tree, which is exactly why local conditions
alone cannot settle the perfect-cuboid question on the tree.
-/
import Mathlib
import Tropical.EulerBrickTree.Core
import Tropical.EulerBrickTree.Descent
import Tropical.EulerBrickTree.Obstruction
import Tropical.EulerBrickTree.Branch

namespace EulerBrickTree

/-! ## The certificate -/

/-- The mod-`7` certificate of `Obstruction.lean` and `Branch.lean`, stated
directly as a property of a tree node: the quartic `c⁴ + 16a²b²`, whose
squareness is equivalent to the perfect-cuboid condition, is a quadratic
nonresidue modulo `7`. -/
def Mod7Refutes (a b c : ℤ) : Prop :=
  ∀ S : ZMod 7, ((c : ZMod 7)) ^ 4 + 16 * ((a : ZMod 7)) ^ 2 * ((b : ZMod 7)) ^ 2 ≠ S ^ 2

/-- **Soundness.**  A certified node of the tree carries no perfect cuboid. -/
theorem mod7_sound {a b c : ℤ} (h : TreeReach a b c) (hr : Mod7Refutes a b c) :
    ¬ IsPerfectCuboid (brick a b c).1 (brick a b c).2.1 (brick a b c).2.2 := by
  rw [treeBrick_perfect_iff h]
  rintro ⟨s, hs⟩
  refine hr ((s : ℤ) : ZMod 7) ?_
  have hc := congrArg (fun t : ℤ => (t : ZMod 7)) hs
  push_cast at hc
  exact hc

/-- The quartic is a nonresidue modulo `7` on the diagonal `u ≡ v`. -/
private theorem mod7_nonresidue : ∀ U W S : ZMod 7, U ≠ 0 → U ^ 2 + U ^ 2 = W ^ 2 →
    W ^ 4 + 16 * U ^ 2 * U ^ 2 ≠ S ^ 2 := by decide

/-- The mod-`7` congruence hypothesis used in `Branch.lean` does imply the
certificate. -/
theorem mod7Refutes_of_congr {u v w : ℤ} (h : IsPT u v w) (huv : (7 : ℤ) ∣ (u - v))
    (hu : ¬ (7 : ℤ) ∣ u) : Mod7Refutes u v w := by
  intro S hS
  have hUV : ((u : ℤ) : ZMod 7) = ((v : ℤ) : ZMod 7) := by
    have hz := (ZMod.intCast_zmod_eq_zero_iff_dvd (u - v) 7).mpr huv
    push_cast at hz
    linear_combination hz
  have hU : ((u : ℤ) : ZMod 7) ≠ 0 := fun hh =>
    hu ((ZMod.intCast_zmod_eq_zero_iff_dvd u 7).mp hh)
  have hpt7 : ((u : ℤ) : ZMod 7) ^ 2 + ((u : ℤ) : ZMod 7) ^ 2 = ((w : ℤ) : ZMod 7) ^ 2 := by
    have hc := congrArg (fun t : ℤ => (t : ZMod 7)) h
    push_cast at hc
    rw [← hUV] at hc
    exact hc
  have hq : ((w : ℤ) : ZMod 7) ^ 4 + 16 * ((u : ℤ) : ZMod 7) ^ 2 * ((u : ℤ) : ZMod 7) ^ 2
      = S ^ 2 := by rw [← hUV] at hS; exact hS
  exact mod7_nonresidue _ _ _ hU hpt7 hq

/-! ## The residue dynamics modulo `7` -/

/-- The first Berggren generator on residue states. -/
private def zA (s : ZMod 7 × ZMod 7 × ZMod 7) : ZMod 7 × ZMod 7 × ZMod 7 :=
  (s.1 - 2 * s.2.1 + 2 * s.2.2, 2 * s.1 - s.2.1 + 2 * s.2.2, 2 * s.1 - 2 * s.2.1 + 3 * s.2.2)

/-- The second Berggren generator on residue states. -/
private def zB (s : ZMod 7 × ZMod 7 × ZMod 7) : ZMod 7 × ZMod 7 × ZMod 7 :=
  (s.1 + 2 * s.2.1 + 2 * s.2.2, 2 * s.1 + s.2.1 + 2 * s.2.2, 2 * s.1 + 2 * s.2.1 + 3 * s.2.2)

/-- A residue state at which the certificate fails: the quartic *is* a square
modulo `7`. -/
private def zSquare (s : ZMod 7 × ZMod 7 × ZMod 7) : Prop :=
  ∃ S : ZMod 7, s.2.2 ^ 4 + 16 * s.1 ^ 2 * s.2.1 ^ 2 = S ^ 2

instance : DecidablePred zSquare := fun _ => inferInstanceAs (Decidable (∃ _, _))

set_option maxRecDepth 20000 in
/-- **The escape computation.**  Whatever the residue state, one of the four
words `ε, A, AA, AB` in the first two generators reaches a state at which the
quartic is a square modulo `7`.  Checked over all `343` states. -/
private theorem z_escape (s : ZMod 7 × ZMod 7 × ZMod 7) :
    zSquare s ∨ zSquare (zA s) ∨ zSquare (zA (zA s)) ∨ zSquare (zB (zA s)) := by
  revert s
  decide

/-- Reduction of an integer node to its residue state. -/
private def red (t : ℤ × ℤ × ℤ) : ZMod 7 × ZMod 7 × ZMod 7 :=
  ((t.1 : ZMod 7), (t.2.1 : ZMod 7), (t.2.2 : ZMod 7))

private theorem red_bergA (t : ℤ × ℤ × ℤ) :
    red (bergA t.1 t.2.1 t.2.2) = zA (red t) := by
  simp only [red, zA, bergA, Prod.mk.injEq]
  refine ⟨?_, ?_, ?_⟩ <;> push_cast <;> ring

private theorem red_bergB (t : ℤ × ℤ × ℤ) :
    red (bergB t.1 t.2.1 t.2.2) = zB (red t) := by
  simp only [red, zB, bergB, Prod.mk.injEq]
  refine ⟨?_, ?_, ?_⟩ <;> push_cast <;> ring

private theorem not_mod7Refutes_iff (t : ℤ × ℤ × ℤ) :
    ¬ Mod7Refutes t.1 t.2.1 t.2.2 ↔ zSquare (red t) := by
  unfold Mod7Refutes zSquare red
  simp only [not_forall, not_not, ne_eq]

/-! ## Words in the two generators -/

/-- Follow a word in the two generators `bergA` (`false`) and `bergB` (`true`). -/
def walkAB : List Bool → ℤ × ℤ × ℤ → ℤ × ℤ × ℤ
  | [], t => t
  | (x :: w), t => walkAB w (if x then bergB t.1 t.2.1 t.2.2 else bergA t.1 t.2.1 t.2.2)

@[simp] theorem walkAB_nil (t : ℤ × ℤ × ℤ) : walkAB [] t = t := rfl

@[simp] theorem walkAB_cons (x : Bool) (w : List Bool) (t : ℤ × ℤ × ℤ) :
    walkAB (x :: w) t =
      walkAB w (if x then bergB t.1 t.2.1 t.2.2 else bergA t.1 t.2.1 t.2.2) := rfl

/-- Every word keeps us inside the tree. -/
theorem walkAB_treeReach : ∀ (w : List Bool) {t : ℤ × ℤ × ℤ},
    TreeReach t.1 t.2.1 t.2.2 → TreeReach (walkAB w t).1 (walkAB w t).2.1 (walkAB w t).2.2
  | [], _, h => h
  | (x :: w), t, h => by
      cases x
      · exact walkAB_treeReach w (t := bergA t.1 t.2.1 t.2.2) (TreeReach.stepA h)
      · exact walkAB_treeReach w (t := bergB t.1 t.2.1 t.2.2) (TreeReach.stepB h)

/-! ## Sharpness -/

/-- **The certificate escapes within two steps.**  From any node of the tree,
one of the four words `ε`, `A`, `AA`, `AB` in the first two Berggren generators
reaches a node at which the mod-`7` certificate no longer refutes the
perfect-cuboid condition. -/
theorem mod7_escape_two_steps (t : ℤ × ℤ × ℤ) :
    ∃ w : List Bool, w.length ≤ 2 ∧
      ¬ Mod7Refutes (walkAB w t).1 (walkAB w t).2.1 (walkAB w t).2.2 := by
  rcases z_escape (red t) with h | h | h | h
  · exact ⟨[], by simp, (not_mod7Refutes_iff _).mpr (by simpa using h)⟩
  · exact ⟨[false], by simp,
      (not_mod7Refutes_iff _).mpr (by simpa [red_bergA] using h)⟩
  · exact ⟨[false, false], by simp,
      (not_mod7Refutes_iff _).mpr (by simpa [red_bergA] using h)⟩
  · exact ⟨[false, true], by simp,
      (not_mod7Refutes_iff _).mpr (by simpa [red_bergA, red_bergB] using h)⟩

/-- **No mod-`7`-certified binary subtree.**  There is no node of the brick tree
from which every node of the binary subtree generated by the first two Berggren
generators is certified by the mod-`7` obstruction.  The infinite obstructed
branch of `Branch.lean` is therefore sharp: a single congruence can certify a
path, never a subtree of positive growth rate. -/
theorem mod7_no_binary_subtree :
    ¬ ∃ t : ℤ × ℤ × ℤ, ∀ w : List Bool,
        Mod7Refutes (walkAB w t).1 (walkAB w t).2.1 (walkAB w t).2.2 := by
  rintro ⟨t, ht⟩
  obtain ⟨w, -, hw⟩ := mod7_escape_two_steps t
  exact hw (ht w)

/-! ## The picture at the branch node `(15,8,17)` -/

/-- The `bergA` child `(33,56,65)` of `(15,8,17)` escapes the certificate. -/
theorem mod7_fails_at_33_56_65 : ¬ Mod7Refutes 33 56 65 := by
  rw [not_mod7Refutes_iff (33, 56, 65)]
  exact ⟨3, by decide⟩

/-- The `bergC` child `(35,12,37)` of `(15,8,17)` escapes the certificate. -/
theorem mod7_fails_at_35_12_37 : ¬ Mod7Refutes 35 12 37 := by
  rw [not_mod7Refutes_iff (35, 12, 37)]
  exact ⟨3, by decide⟩

/-- The `bergB` child `(65,72,97)` of `(15,8,17)` is still certified. -/
theorem mod7_holds_at_65_72_97 : Mod7Refutes 65 72 97 := by
  have h : ¬ zSquare (red (65, 72, 97)) := by decide
  intro S hS
  exact h ⟨S, hS⟩

/-- **The local architecture of the obstruction.**  At the node `(15,8,17)` the
three children behave in three different ways: the `bergB` child is certified
(and, by `Branch.lean`, so is its whole `bergB` branch), while the `bergA` and
`bergC` children are not.  The obstructed part of the tree that this congruence
sees is exactly a branch. -/
theorem mod7_branch_sharp_at_15_8_17 :
    Mod7Refutes (bergB 15 8 17).1 (bergB 15 8 17).2.1 (bergB 15 8 17).2.2 ∧
      ¬ Mod7Refutes (bergA 15 8 17).1 (bergA 15 8 17).2.1 (bergA 15 8 17).2.2 ∧
      ¬ Mod7Refutes (bergC 15 8 17).1 (bergC 15 8 17).2.1 (bergC 15 8 17).2.2 := by
  refine ⟨?_, ?_, ?_⟩
  · have h : bergB 15 8 17 = (65, 72, 97) := by norm_num [bergB]
    rw [h]
    exact mod7_holds_at_65_72_97
  · have h : bergA 15 8 17 = (33, 56, 65) := by norm_num [bergA]
    rw [h]
    exact mod7_fails_at_33_56_65
  · have h : bergC 15 8 17 = (35, 12, 37) := by norm_num [bergC]
    rw [h]
    exact mod7_fails_at_35_12_37

end EulerBrickTree