

# This file was *autogenerated* from the file hardN.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p1 = RealNumber('0.1'); _sage_const_0p15 = RealNumber('0.15'); _sage_const_400 = Integer(400); _sage_const_600 = Integer(600); _sage_const_800 = Integer(800); _sage_const_0p7 = RealNumber('0.7'); _sage_const_31337 = Integer(31337); _sage_const_10 = Integer(10); _sage_const_60 = Integer(60)
import time
exec(compile(open('/home/raver1975/lean/factor-scratch/r112/verify_gifp/vcore.sage').read(),'vcore.sage','exec'))
LOG=open('/home/raver1975/lean/factor-scratch/r112/verify_gifp/hardN.log','a')
def P(*a): LOG.write(' '.join(str(x) for x in a)+'\n'); LOG.flush()
b1,b2=RR(_sage_const_0p1 ),RR(_sage_const_0p15 )
for N in [_sage_const_400 ,_sage_const_600 ,_sage_const_800 ]:
    r=generate_gifp_instance(N,RR(_sage_const_0p1 ),RR(_sage_const_0p7 ),b1,b2,_sage_const_31337 ,max_attempts=_sage_const_10 )
    if r is None: P("n=%d GEN-NONE"%N); continue
    (p1,q1,N1),(p2t,q2t,N2),sh,ds=r
    P("n=%d |q2|=%d bits |p2|=%d bits"%(N,q2t.nbits(),p2t.nbits()))
    t0=time.time()
    try:
        g=pari(N2).factor(timeout=_sage_const_60 )
        P("   factor(N2) via PARI in %.2fs -> %s"%(time.time()-t0,"COMPLETE" if str(g)!='[1, ...]' else "GAVE UP (timeout)"))
    except Exception as e:
        P("   factor(N2) -> %.2fs EXC %s"%(time.time()-t0,e))

