

# This file was *autogenerated* from the file leak3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_200 = Integer(200); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p15 = RealNumber('0.15'); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_8000000 = Integer(8000000); _sage_const_104729 = Integer(104729); _sage_const_0p7 = RealNumber('0.7'); _sage_const_1 = Integer(1); _sage_const_999 = Integer(999); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_40 = Integer(40); _sage_const_3 = Integer(3); _sage_const_7000000 = Integer(7000000)# NEGATIVE CONTROL: shuffle the Groebner basis elements / random polynomials.
# If "recovery" is real, only the TRUE lattice polys give p2.
import time,sys
LOGF='/home/raver1975/lean/factor-scratch/r112/verify_gifp/leak3.log'
import builtins
_bp=builtins.print
def print(*a,**k):
    _bp(*a,**k)
    fh=open(LOGF,'a'); fh.write(' '.join(str(x) for x in a)+'\n'); fh.close()
builtins.print=print
exec(compile(open('/home/raver1975/lean/factor-scratch/r112/verify_gifp/vcore.sage').read(),'vcore.sage','exec'))
n=_sage_const_200 ; a=RR(_sage_const_0p1 ); b1,b2=RR(_sage_const_0p1 ),RR(_sage_const_0p15 ); m=_sage_const_4 
import random
ok_true=_sage_const_0 ; ok_scram=_sage_const_0 ; T=_sage_const_8 
for k in range(T):
    seed=_sage_const_8000000 +_sage_const_104729 *k
    B=build(n,a,RR(_sage_const_0p7 ),b1,b2,m,seed)
    R=scan_gb(B["polys"],B["N2"],B["p2t"],B["q2t"],n)
    if R.get("best"): ok_true+=_sage_const_1 
    # SCRAMBLE: replace the lattice polys with random degree-5 polys of the same shape
    pr=ZZ["x","y","z","w"]; x,y,z,w=pr.gens()
    set_random_seed(seed+_sage_const_999 )
    fake=[]
    for d in range(_sage_const_5 ):
        g=_sage_const_0 
        for i in range(_sage_const_6 ):
            g+= randint(-_sage_const_2 **_sage_const_40 ,_sage_const_2 **_sage_const_40 )*x**randint(_sage_const_0 ,_sage_const_3 )*y**randint(_sage_const_0 ,_sage_const_3 )*z**randint(_sage_const_0 ,_sage_const_1 )*w**randint(_sage_const_0 ,_sage_const_3 )
        fake.append(g)
    R2=scan_gb(fake,B["N2"],B["p2t"],B["q2t"],n)
    if R2.get("best"): ok_scram+=_sage_const_1 
print("NEGATIVE CONTROL: true lattice polys recover p2 : %d/%d"%(ok_true,T))
print("NEGATIVE CONTROL: RANDOM polys recover p2     : %d/%d"%(ok_scram,T))
print("(random polys must give 0 -- if >0 the 'recovery' is a harness artifact)")

# DEGENERATE-PATH TEST: is `a` ever N2 itself, or 1?
print()
print("=== degenerate-path check: distribution of recovered divisor size ===")
for k in range(_sage_const_6 ):
    B=build(n,a,RR(_sage_const_0p7 ),b1,b2,m,_sage_const_7000000 +_sage_const_104729 *k)
    R=scan_gb(B["polys"],B["N2"],B["p2t"],B["q2t"],n)
    if R.get("best"):
        h=R["best"]; c=ZZ(h["coef"])
        print("  seed: |a|=%d bits, N2=%d bits, a==N2? %s a==1? %s divides? %s ==p2? %s"%(
            abs(c).nbits(), B["N2"].nbits(), abs(c)==B["N2"], abs(c)==_sage_const_1 , B["N2"]%c==_sage_const_0 , h["equals_p2"]))

