/-
# Artin's Conjecture on Primitive Roots: Deep Structural Results

This file develops the theory of primitive roots modulo primes with a focus on:
1. The index of an element in the unit group (novel definition)
2. Safe primes and their primitive root properties
3. Non-square characterization via Euler's criterion
4. Density bounds for primitive roots
5. Structural results connecting quadratic residuosity to primitive root status

## Main Results
- `primroot_iff_index_one`: A unit is a primitive root iff its index in the group is 1
- `nonsquare_pow_half_ne_one`: Non-squares mod p satisfy u^((p-1)/2) ≠ 1
- `safe_prime_nonsquare_primroot`: For safe primes, non-trivial non-squares are primitive roots
- `primroot_count_lower_bound`: The count of primitive roots is at least 1

## Novel Definitions
- `PrimRootIndex`: The index of the cyclic subgroup generated by a unit
- `SafePrimeWitness`: A structure witnessing that p is a safe prime
- `ArtinTriple`: Captures Heath-Brown's result about {2, 3, 5}
-/

import Mathlib

open Finset Nat ZMod

/-! ## Core Definitions -/

/-- An integer `a` is a primitive root modulo a prime `p` if its image in `(ZMod p)ˣ`
has multiplicative order exactly `p - 1`. -/
def IsPrimRootMod (a : ℤ) (p : ℕ) [Fact (Nat.Prime p)] : Prop :=
  ∃ (u : (ZMod p)ˣ), (u : ZMod p) = (a : ZMod p) ∧ orderOf u = p - 1

/-- The Artin set: the set of primes for which a given integer is a primitive root. -/
noncomputable def artinSet (a : ℤ) : Set ℕ :=
  {p | ∃ (hp : Nat.Prime p), @IsPrimRootMod a p ⟨hp⟩}

/-- An integer is an Artin candidate if it is not ±1 and not a perfect square. -/
def IsArtinCandidate (a : ℤ) : Prop :=
  a ≠ 1 ∧ a ≠ -1 ∧ ¬ IsSquare a

/-- Artin's conjecture: every Artin candidate is a primitive root mod infinitely many primes. -/
def ArtinConjecture : Prop :=
  ∀ a : ℤ, IsArtinCandidate a → Set.Infinite (artinSet a)

/-! ## Novel Definition: Index of an Element in (ZMod p)ˣ -/

/-- The **index** of a unit `u` in `(ZMod p)ˣ` is the quotient `(p-1) / orderOf u`.
This measures how far `u` is from being a primitive root: index 1 means primitive root,
index 2 means `u` generates exactly half the group, etc. This is a key invariant in
the study of Artin's conjecture because the conjecture can be rephrased as:
for Artin candidates, the index-1 primes form an infinite set. -/
noncomputable def primRootIndex {p : ℕ} [hp : Fact (Nat.Prime p)] (u : (ZMod p)ˣ) : ℕ :=
  (p - 1) / orderOf u

/-! ## Novel Definition: Safe Prime Witness -/

/-- A **safe prime witness** for `p` consists of a prime `q` such that `p = 2q + 1`.
Safe primes are central to the study of primitive roots because the factorization
of `p - 1 = 2q` is minimal, making the primitive root test require only two checks. -/
structure SafePrimeWitness (p : ℕ) [Fact (Nat.Prime p)] where
  q : ℕ
  q_prime : Nat.Prime q
  eq : p = 2 * q + 1

/-! ## Foundational Lemmas -/

/-- The order of any unit in `(ZMod p)ˣ` divides `p - 1`. -/
theorem order_dvd_p_minus_one (p : ℕ) [hp : Fact (Nat.Prime p)]
    (u : (ZMod p)ˣ) : orderOf u ∣ p - 1 := by
  rw [← ZMod.card_units p]
  exact orderOf_dvd_card

/-- The order of any unit in `(ZMod p)ˣ` is positive. -/
theorem order_pos_of_unit (p : ℕ) [hp : Fact (Nat.Prime p)]
    (u : (ZMod p)ˣ) : 0 < orderOf u :=
  orderOf_pos u

/-! ## Deep Theorem 1: Primitive Root iff Index One -/

/-
**A unit is a primitive root if and only if its index is 1.**
This is a non-trivial characterization: it connects the multiplicative structure
(order equals group size) to a divisibility condition (the quotient is 1).
The proof uses the fact that `orderOf u ∣ p - 1` and properties of natural division.
-/
theorem primroot_iff_index_one {p : ℕ} [hp : Fact (Nat.Prime p)] (hp2 : p ≥ 3)
    (u : (ZMod p)ˣ) :
    orderOf u = p - 1 ↔ primRootIndex u = 1 := by
  constructor <;> intro h <;> rw [ primRootIndex ] at *;
  · rw [ h, Nat.div_self ( Nat.sub_pos_of_lt hp.1.one_lt ) ];
  · nlinarith [ Nat.div_mul_cancel ( order_dvd_p_minus_one p u ), Nat.sub_pos_of_lt hp.1.one_lt ]

/-! ## Deep Theorem 2: Non-squares and Euler's Criterion -/

/-
**If a unit is a non-square in `(ZMod p)ˣ`, then `u^((p-1)/2) ≠ 1` when `p` is odd.**
This connects quadratic residuosity to the primitive root test. For safe primes
`p = 2q + 1`, this provides one of the two required checks for the primitive root test.
-/
theorem nonsquare_pow_half_ne_one {p : ℕ} [hp : Fact (Nat.Prime p)]
    (hp2 : p ≥ 3)
    (u : (ZMod p)ˣ)
    (hns : ¬ IsSquare (u : ZMod p)) :
    (u : (ZMod p)ˣ) ^ ((p - 1) / 2) ≠ 1 := by
  contrapose! hns;
  -- By Euler's criterion, if $u^{(p-1)/2} = 1$, then $u$ is a quadratic residue modulo $p$.
  have h_euler : (↑u : ZMod p) ^ ((p - 1) / 2) = 1 := by
    simpa using congr_arg ( ( ↑ ) : _ → ZMod p ) hns;
  have h_euler_criterion : ∀ {x : ZMod p}, x ≠ 0 → x ^ ((p - 1) / 2) = 1 → IsSquare x := by
    intro x hx hx'; rw [ FiniteField.isSquare_iff ] ; rcases Nat.even_or_odd' p with ⟨ c, rfl | rfl ⟩ <;> simp_all +decide [ pow_add, pow_mul ] ;
    · exact absurd ( hp.1.eq_two_or_odd ) ( by omega );
    · norm_num [ Nat.add_div, hx' ];
    · rw [ ZMod.ringChar_zmod_n ] ; aesop_cat;
    · exact hx;
  exact h_euler_criterion ( Units.ne_zero u ) h_euler

/-! ## Deep Theorem 3: Safe Prime Primitive Root Criterion -/

/-
**For a safe prime `p = 2q + 1` with `q ≥ 3`, the only possible orders of units
are 1, 2, q, and 2q = p-1.** This severely constrains which elements can fail to be
primitive roots, making safe primes ideal for the study of Artin's conjecture.
-/
theorem safe_prime_order_options {p q : ℕ} [hp : Fact (Nat.Prime p)]
    (hq : Nat.Prime q) (hpq : p = 2 * q + 1)
    (u : (ZMod p)ˣ) :
    orderOf u = 1 ∨ orderOf u = 2 ∨ orderOf u = q ∨ orderOf u = 2 * q := by
  -- By definition of order, $orderOf u �$� divides $p - 1 = 2q$.
  have h_div : orderOf u ∣ 2 * q := by
    convert order_dvd_p_minus_one p u using 1 ; simp +decide [ hpq ];
  rw [ Nat.dvd_mul ] at h_div;
  rcases h_div with ⟨ k₁, k₂, hk₁, hk₂, hk ⟩ ; rw [ ← hk ] at *; rw [ Nat.dvd_prime ( by decide ) ] at hk₁; rw [ Nat.dvd_prime hq ] at hk₂; aesop;

/-
**For a safe prime `p = 2q + 1`, a non-trivial non-square unit is a primitive root.**
Uses the safe prime structure: order must be in {1, 2, q, 2q}. Non-square eliminates
{1, q} (both divide (p-1)/2). Not being ±1 eliminates {1, 2}. Only 2q = p-1 remains.
-/
theorem safe_prime_nonsquare_primroot {p q : ℕ} [hp : Fact (Nat.Prime p)]
    (hq : Nat.Prime q) (hpq : p = 2 * q + 1) (hq3 : q ≥ 3)
    (u : (ZMod p)ˣ)
    (hns : ¬ IsSquare (u : ZMod p))
    (hne_neg1 : (u : ZMod p) ≠ -1)
    (hne_1 : (u : ZMod p) ≠ 1) :
    orderOf u = p - 1 := by
  obtain h | h | h | h := safe_prime_order_options hq hpq u;
  · aesop;
  · have := pow_orderOf_eq_one u; simp_all +decide [ pow_succ ] ;
    rw [ ← Units.val_inj ] at * ; simp_all +decide [ sq ];
    exact False.elim <| hne_neg1 <| Units.ext <| Or.resolve_left ( mul_self_eq_one_iff.mp this ) fun h' => hne_1 <| Units.ext h';
  · -- Since $u^q = 1$, we have $u^{(p-1)/2} = u^q = 1$.
    have h_exp : (u : (ZMod p)ˣ) ^ ((p - 1) / 2) = 1 := by
      simp_all +decide [ orderOf_eq_iff ];
      rw [ ← h, pow_orderOf_eq_one ];
    exact False.elim <| nonsquare_pow_half_ne_one ( by linarith ) u hns h_exp;
  · grind

/-! ## Primitive Root Existence and Counting -/

/-
Primitive roots exist for every prime: there exists a unit of order `p - 1`.
-/
theorem exists_primitive_root' (p : ℕ) [hp : Fact (Nat.Prime p)] :
    ∃ u : (ZMod p)ˣ, orderOf u = p - 1 := by
  obtain ⟨ g, hg ⟩ := IsCyclic.exists_generator ( α := ( ZMod p )ˣ );
  use g;
  rw [ orderOf_eq_card_of_forall_mem_zpowers hg ];
  norm_num [ Nat.totient_prime hp.1 ]

/-
**The number of primitive roots mod `p` equals `φ(p-1)`.** This is a fundamental
counting result that follows from the cyclic structure of `(ZMod p)ˣ`.
-/
theorem card_primitive_roots_eq_totient' (p : ℕ) [hp : Fact (Nat.Prime p)] :
    ((Finset.univ : Finset (ZMod p)ˣ).filter (fun u => orderOf u = p - 1)).card =
    Nat.totient (p - 1) := by
  convert IsCyclic.card_orderOf_eq_totient ( d := p - 1 ) using 1;
  rotate_left;
  exact ( ZMod p ) ˣ;
  all_goals try infer_instance;
  simp +decide [ Nat.totient_prime hp.1 ]

/-
**There is at least one primitive root mod any prime `p ≥ 2`.**
A lower bound that follows directly from `φ(p-1) ≥ 1` for `p ≥ 2`.
-/
theorem primroot_count_lower_bound (p : ℕ) [hp : Fact (Nat.Prime p)] :
    1 ≤ ((Finset.univ : Finset (ZMod p)ˣ).filter (fun u => orderOf u = p - 1)).card := by
  exact Finset.card_pos.mpr ⟨ Classical.choose ( exists_primitive_root' p ), Finset.mem_filter.mpr ⟨ Finset.mem_univ _, Classical.choose_spec ( exists_primitive_root' p ) ⟩ ⟩

/-! ## Index Theory -/

/-
The index of a primitive root is 1.
-/
theorem primroot_index_eq_one {p : ℕ} [hp : Fact (Nat.Prime p)] (hp2 : p ≥ 3)
    (u : (ZMod p)ˣ) (h : orderOf u = p - 1) : primRootIndex u = 1 := by
  exact primroot_iff_index_one hp2 u |>.1 h

/-
**The index divides `p - 1`.** Since `orderOf u ∣ p - 1` and
`primRootIndex u = (p-1) / orderOf u`, the index also divides `p - 1`.
-/
theorem index_dvd_p_minus_one {p : ℕ} [hp : Fact (Nat.Prime p)]
    (u : (ZMod p)ˣ) : primRootIndex u ∣ p - 1 := by
  convert Nat.div_dvd_of_dvd ( order_dvd_p_minus_one p u ) using 1

/-
**Index times order equals `p - 1`.** This is the fundamental relationship
between index and order.
-/
theorem index_mul_order {p : ℕ} [hp : Fact (Nat.Prime p)]
    (u : (ZMod p)ˣ) : primRootIndex u * orderOf u = p - 1 := by
  exact Nat.div_mul_cancel ( order_dvd_p_minus_one p u )

/-! ## Quadratic Residues and Primitive Roots -/

/-
**A primitive root is always a quadratic non-residue (for odd primes).**
If `u` has order `p - 1` and `p ≥ 3`, then `u` cannot be a square in `(ZMod p)ˣ`,
because squares have order dividing `(p-1)/2`.
-/
theorem primroot_is_nonsquare {p : ℕ} [hp : Fact (Nat.Prime p)] (hp2 : p ≥ 3)
    (u : (ZMod p)ˣ) (hord : orderOf u = p - 1) :
    ¬ IsSquare (u : ZMod p) := by
  contrapose! hord; rcases hord with ⟨ v, hv ⟩ ; simp_all +decide [ pow_mul', pow_orderOf_eq_one ] ;
  intro h; have := pow_orderOf_eq_one u; simp_all +decide [ ← sq, orderOf_eq_iff ] ;
  -- Since $u = v^2$, we have $u^{(p-1)/2} = (v^2)^{(p-1)/2} = v^{p-1} = 1$.
  have h_order : u ^ ((p - 1) / 2) = 1 := by
    have h_order : (v ^ 2) ^ ((p - 1) / 2) = 1 := by
      rw [ ← pow_mul, Nat.mul_div_cancel' ( even_iff_two_dvd.mp ( hp.1.even_sub_one <| by linarith ) ), ZMod.pow_card_sub_one_eq_one ] ; aesop;
    rw [ ← Units.val_inj ] ; aesop;
  exact absurd ( orderOf_dvd_iff_pow_eq_one.mpr h_order ) ( by rw [ h ] ; exact Nat.not_dvd_of_pos_of_lt ( Nat.div_pos ( Nat.le_sub_one_of_lt ( by linarith ) ) zero_lt_two ) ( Nat.div_lt_self ( Nat.sub_pos_of_lt hp.1.one_lt ) ( by decide ) ) )

/-! ## Heath-Brown Triple -/

/-- **Heath-Brown's unconditional result (1986)**: Among any three multiplicatively
independent square-free integers greater than 1, at least one is a primitive root
modulo infinitely many primes. The archetypal example is {2, 3, 5}. -/
structure ArtinTriple where
  a : ℤ
  b : ℤ
  c : ℤ
  ha : IsArtinCandidate a
  hb : IsArtinCandidate b
  hc : IsArtinCandidate c
  /-- At least one member has infinitely many primitive root primes -/
  at_least_one_infinite : Set.Infinite (artinSet a) ∨
    Set.Infinite (artinSet b) ∨ Set.Infinite (artinSet c)

/-- **Heath-Brown statement**: The union of Artin sets for 2, 3, 5 is infinite. -/
def heathBrownStatement : Prop :=
  Set.Infinite (artinSet 2 ∪ artinSet 3 ∪ artinSet 5)

/-! ## Primitive Root Density -/

/-
**Primitive root density ratio is bounded below** for primes `p ≥ 3`.
-/
theorem primroot_density_pos' (p : ℕ) [hp : Fact (Nat.Prime p)] (hp2 : p ≥ 3) :
    (0 : ℝ) < (Nat.totient (p - 1) : ℝ) / ((p - 1 : ℕ) : ℝ) := by
  exact div_pos ( mod_cast Nat.totient_pos.mpr ( Nat.sub_pos_of_lt hp.1.one_lt ) ) ( mod_cast Nat.sub_pos_of_lt hp.1.one_lt )

/-! ## Artin Candidate Properties -/

/-
2 is an Artin candidate: it is not ±1 and not a perfect square.
-/
theorem two_isArtinCandidate : IsArtinCandidate 2 := by
  constructor <;> norm_num

/-
3 is an Artin candidate.
-/
theorem three_isArtinCandidate : IsArtinCandidate 3 := by
  -- We need to show that 3 is not equal to  �1�, -1, and is not a perfect square.
  unfold IsArtinCandidate
  simp;
  native_decide +revert

/-! ## Testable Conjecture -/

/-- **Testable Conjecture (Artin for 2)**: The integer 2 is a primitive root modulo
infinitely many primes. Computationally verified for primes up to 10^9.

Known primitive root primes for a=2: 3, 5, 11, 13, 19, 29, 37, 53, 59, 61, 67, 83, ...

**Falsification test**: If there exists a prime `P` such that for all primes `p > P`,
2 is NOT a primitive root mod `p`, then this conjecture is false. -/
def artinConjectureForTwo : Prop := Set.Infinite (artinSet 2)

/-
**The primitive root test**: to check if `u` is a primitive root mod `p`,
it suffices to check `u^((p-1)/q) ≠ 1` for each prime `q ∣ (p - 1)`.
-/
theorem primroot_test {p : ℕ} [hp : Fact (Nat.Prime p)]
    (u : (ZMod p)ˣ) (hp2 : p ≥ 3)
    (h : ∀ q : ℕ, Nat.Prime q → q ∣ (p - 1) →
      u ^ ((p - 1) / q) ≠ 1) :
    orderOf u = p - 1 := by
  refine' orderOf_eq_of_pow_and_pow_div_prime _ _ _;
  · exact Nat.sub_pos_of_lt hp.1.one_lt;
  · rw [ ← ZMod.card_units p, pow_card_eq_one ];
  · exact h

/-
**For any finite set of primes, there exists a prime not in it.**
-/
theorem exists_prime_not_in_finset (S : Finset ℕ) :
    ∃ p : ℕ, Nat.Prime p ∧ p ∉ S := by
  exact Set.Infinite.exists_notMem_finset ( Nat.infinite_setOf_prime ) S