/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Escher Height, part I: the polynomial staircase in infinitely many variables

This file extends `Algebra.EscherStaircase` (the definition `Escher.EscherStaircase`
and the characterisation `Escher.escherStaircase_iff_not_isNoetherianRing`) with the
concrete polynomial realisation of the "Escher height = number of variables" picture.

For a field `k`, the ring `k[x₀, x₁, x₂, …]` of polynomials in **countably many**
variables carries the explicit ascending chain
  `V 0 ⊆ V 1 ⊆ V 2 ⊆ ⋯`,   `V n = ⟨x₀, …, x_{n-1}⟩`,
which is *strictly* ascending (`X n` lies in `V (n+1)` but not in `V n`) and hence is
an Escher staircase.  As with the `ℕ → ℤ` example in the sibling file, the chain
"loops back": its infimum is `V 0 = ⊥ = {0}`, the very bottom rung the ascent starts
from.

## Main results

* `Escher.X_not_mem_span_image` : the load-bearing non-membership fact — `X j` is not
  in the ideal generated by `{X i : i ∈ s}` whenever `j ∉ s`.  Proved by evaluating
  the offending combination under the algebra map that kills exactly the variables in
  `s`.
* `Escher.escherStaircase_mvPolynomial_nat` : `k[x₀, x₁, …]` has an Escher staircase.
* `Escher.varIdeal_iInf_eq_bot` : the staircase loops back to `⊥`.
* `Escher.not_isNoetherianRing_mvPolynomial_nat` : consequently the ring is not
  Noetherian (its "Escher height" is infinite).

-- !-- Lab Notes -- !--
### Hypothesis (Hypothesizer)
Building on the ACC characterisation `escherStaircase_iff_not_isNoetherianRing`:
  H1. `k[x₀,x₁,…]` (infinitely many variables) has an *explicit* Escher staircase,
      the variable-ideal chain `V n = ⟨x₀,…,x_{n-1}⟩`.                        [kept]
  H2. That chain loops back: `⨅ n, V n = ⊥ = V 0`, matching the impossible-
      architecture picture.                                                   [kept]
  H3. The strictness `X n ∉ V n` is the only non-formal input, and it is a genuine
      statement about polynomial rings (not order theory).                    [kept]
  H4. (surprising) The naive informal chain `I_n = {f : f(ℤ) ⊆ 2ⁿℤ}` for `Int(ℤ)`
      is *descending*, so it is NOT an Escher staircase; the honest infinite-height
      witness is the variable chain above, whose rungs strictly grow.         [kept]

### Experiment (Experimenter)
Small cases: `V 0 = ⟨∅⟩ = ⊥`; `V 1 = ⟨x₀⟩`; `V 2 = ⟨x₀,x₁⟩`.  Strictness test:
`X 1 ∈ V 2` but `X 1 ∉ V 1`.  Checked the separating homomorphism `φ_s` that sends
`x_i ↦ 0` for `i ∈ s` and fixes the rest: it kills every generator of `⟨{x_i:i∈s}⟩`
but sends `x_j` (for `j ∉ s`) to the nonzero element `x_j`.

### Analysis (Analyst)
The key lemma `X_not_mem_span_image` is proved via `Ideal.span_le` into the kernel of
`φ_s = aeval (fun i => if i ∈ s then 0 else X i)`; membership of `X j` would force
`x_j = φ_s (x_j) = 0`, contradicting `MvPolynomial.X_ne_zero`.  This is the same
"evaluate to detect a missing generator" trick that underlies Noetherian counter-
examples for infinite variable counts.

### Critique (Critic)
* Non-triviality: strictness uses a real ring homomorphism argument, not `simp`.
* Vacuity: `k` is a field (nontrivial), so `X_ne_zero` applies and the staircase is a
  genuine strictly ascending chain — not a constant sequence.
* Loop-back honesty: `⨅ n, V n = ⊥` because `V 0 = ⊥`; the infimum truly returns to
  the starting rung.

### Synthesis (PI)
`k[x₀,x₁,…]` is the polynomial embodiment of an *infinite-height* Escher staircase,
the natural stand-in for the mission's `Int(ℤ)` example, and it dovetails with the
finite-variable Hilbert-basis result (no staircase) in the sibling file to justify
"Escher height = number of variables".
-- !-- Lab Notes -- !--
-/
import Mathlib
import Algebra.EscherStaircase

open MvPolynomial

open scoped Classical

namespace Escher

variable {k : Type*} [Field k]

/-- **Key non-membership lemma.** In `k[x₀, x₁, …]`, the variable `X j` does not lie
in the ideal generated by `{X i : i ∈ s}` as soon as `j ∉ s`.  The witness is the
algebra endomorphism that sends every variable indexed by `s` to `0` and fixes the
rest: it annihilates the whole ideal but sends `X j` to the nonzero element `X j`. -/
theorem X_not_mem_span_image {s : Set ℕ} {j : ℕ} (hj : j ∉ s) :
    (X j : MvPolynomial ℕ k) ∉ Ideal.span ((fun i => (X i : MvPolynomial ℕ k)) '' s) := by
  classical
  intro hmem
  set f : MvPolynomial ℕ k →ₐ[k] MvPolynomial ℕ k :=
    aeval (fun i => if i ∈ s then (0 : MvPolynomial ℕ k) else X i) with hf
  have hspan_le :
      Ideal.span ((fun i => (X i : MvPolynomial ℕ k)) '' s) ≤ RingHom.ker f.toRingHom := by
    rw [Ideal.span_le]
    rintro _ ⟨i, hi, rfl⟩
    simp [RingHom.mem_ker, hf, hi]
  have h0 : f.toRingHom (X j) = 0 := hspan_le hmem
  have hj' : f.toRingHom (X j) = X j := by simp [hf, hj]
  rw [hj'] at h0
  exact (X_ne_zero j) h0

/-- The `n`-th rung of the polynomial staircase: the ideal `⟨x₀, …, x_{n-1}⟩`
generated by the first `n` variables. -/
noncomputable def varIdeal (n : ℕ) : Ideal (MvPolynomial ℕ k) :=
  Ideal.span ((fun i => (X i : MvPolynomial ℕ k)) '' Set.Iio n)

/-- Each rung is strictly contained in the next: `X n` is a new generator. -/
theorem varIdeal_lt_succ (n : ℕ) :
    (varIdeal n : Ideal (MvPolynomial ℕ k)) < varIdeal (n + 1) := by
  rw [SetLike.lt_iff_le_and_exists]
  refine ⟨Ideal.span_mono (Set.image_mono (Set.Iio_subset_Iio (Nat.le_succ n))), X n, ?_, ?_⟩
  · exact Ideal.subset_span ⟨n, by simp, rfl⟩
  · exact X_not_mem_span_image (by simp)

/-- The rungs form a strictly ascending chain — an explicit Escher staircase. -/
theorem varIdeal_strictMono : StrictMono (varIdeal (k := k)) :=
  strictMono_nat_of_lt_succ varIdeal_lt_succ

/-- The bottom rung is `{0}`: no variables generate the zero ideal. -/
theorem varIdeal_zero : (varIdeal 0 : Ideal (MvPolynomial ℕ k)) = ⊥ := by
  simp [varIdeal]

/-- **The polynomial staircase loops back.** The infimum of the whole ascending chain
is the zero ideal `{0}` — the same bottom rung `V 0` the ascent started from. -/
theorem varIdeal_iInf_eq_bot : (⨅ n, varIdeal (k := k) n) = ⊥ := by
  refine le_antisymm ?_ bot_le
  calc (⨅ n, varIdeal (k := k) n) ≤ varIdeal 0 := iInf_le _ 0
    _ = ⊥ := varIdeal_zero

/-- **Main theorem (infinite Escher height).** The ring `k[x₀, x₁, x₂, …]` of
polynomials in countably many variables admits an Escher staircase. -/
theorem escherStaircase_mvPolynomial_nat : EscherStaircase (MvPolynomial ℕ k) :=
  ⟨varIdeal, varIdeal_strictMono⟩

/-- Consequently `k[x₀, x₁, …]` is not Noetherian. -/
theorem not_isNoetherianRing_mvPolynomial_nat :
    ¬ IsNoetherianRing (MvPolynomial ℕ k) :=
  escherStaircase_iff_not_isNoetherianRing.mp escherStaircase_mvPolynomial_nat

end Escher