/-
# Surreal topology: non-Archimedean order forces total disconnectedness

This file corrects the proposed connectedness claim. The topology generated by open
intervals is precisely the order topology. In Mathlib's universe-relative model of
surreal numbers, every set-sized family of surreals has an upper bound. This produces,
below every positive surreal `d`, a positive `ε` such that `n * ε < d` for every natural
number `n`.

The additive finite ray generated by such an `ε` is clopen. These rays separate every
pair of distinct surreals, proving that the order-topological surreal line is totally
separated, hence totally disconnected. Consequently every path is constant. The
fundamental group at every basepoint is nevertheless trivial: this is not a consequence
of contractibility (which is false), but of the stronger absence of nonconstant paths.
-/

import Mathlib

open Set
open scoped Topology

namespace SurrealTopologyConnector

namespace Surreal

noncomputable instance instTopologicalSpace : TopologicalSpace Surreal.{0} :=
  Preorder.topology Surreal.{0}

instance instOrderTopology : OrderTopology Surreal.{0} := ⟨rfl⟩

/-
A surreal strictly above every natural number.
-/
theorem exists_gt_natCast : ∃ M : Surreal.{0}, ∀ n : ℕ, (n : Surreal.{0}) < M := by
  by_contra! h_contra;
  obtain ⟨ M, hM ⟩ := Surreal.bddAbove_range_of_small ( fun n : ℕ => ( n : Surreal ) );
  -- Apply h_contra to M to get an n where M ≤ n.
  obtain ⟨ n, hn ⟩ := h_contra M;
  exact absurd ( hM ( Set.mem_range_self ( n + 1 ) ) ) ( by simpa using hn.trans_lt ( Nat.cast_lt.mpr ( Nat.lt_succ_self _ ) ) )

/-
There is a positive surreal smaller than every positive dyadic `2⁻ⁿ`.
It is represented by the Conway cut `{0 | 1, 1/2, 1/4, ...}`.
-/
theorem exists_positive_below_powHalf :
    ∃ δ : Surreal.{0}, 0 < δ ∧ ∀ k : ℕ, δ < Surreal.powHalf k := by
  refine' ⟨ _, _, _ ⟩;
  exact Surreal.mk ( SetTheory.PGame.mk ( PUnit ) ℕ ( fun _ => 0 ) fun n => SetTheory.PGame.powHalf n ) ( by
    constructor;
    · exact fun _ _ => SetTheory.PGame.powHalf_pos _;
    · exact ⟨fun _ => SetTheory.PGame.numeric_zero,
        fun n => SetTheory.PGame.numeric_powHalf n⟩ );
  · convert Surreal.mk_moveLeft_lt_mk _ _;
    convert rfl;
    exact PUnit.unit;
  · intro k;
    refine' Surreal.mk_lt_mk_moveRight _ _

/-
The Conway cut construction can be scaled: below `d, d/2, d/4, ...`
there remains a positive surreal.
-/
theorem exists_positive_below_scaled_powHalf {d : Surreal.{0}} (hd : 0 < d) :
    ∃ ε : Surreal.{0}, 0 < ε ∧ ∀ k : ℕ, ε < d * Surreal.powHalf k := by
  obtain ⟨ δ, hδ_pos, hδ ⟩ := Surreal.exists_positive_below_powHalf;
  refine' ⟨ δ * d, mul_pos hδ_pos hd, fun k => _ ⟩;
  rw [ mul_comm ] ; gcongr;
  exact hδ k

/-
Every positive surreal scale contains a positive quantity smaller than all of its
natural-number fractions. This is the non-Archimedean input to the topology.
-/
theorem exists_infinitesimal_below {d : Surreal.{0}} (hd : 0 < d) :
    ∃ ε : Surreal.{0}, 0 < ε ∧ ∀ n : ℕ, (n : Surreal.{0}) * ε < d := by
  obtain ⟨ ε, hε₁, hε₂ ⟩ := exists_positive_below_scaled_powHalf hd;
  -- For each n, choose k with n < 2^k (Nat.exists_lt_pow with base 2, or choose k=n+1 and prove n < 2^(n+1)). Then ε < d*powHalf k.
  have h_choose_k : ∀ n : ℕ, ∃ k : ℕ, n < 2^k := by
    exact fun n => pow_unbounded_of_one_lt n one_lt_two;
  refine ⟨ ε, hε₁, fun n => ?_ ⟩
  obtain ⟨ k, hk ⟩ := h_choose_k n
  have h_ineq : (n : Surreal) * ε < d := by
    have h_ineq : (n : Surreal) * ε < (2^k : Surreal) * ε := by
      exact mul_lt_mul_of_pos_right ( mod_cast hk ) hε₁;
    have h_ineq : (2^k : Surreal) * ε < (2^k : Surreal) * (d * Surreal.powHalf k) := by
      exact mul_lt_mul_of_pos_left ( hε₂ k ) ( by positivity );
    convert lt_trans ‹_› h_ineq using 1;
    rw [ mul_left_comm, Surreal.nsmul_pow_two_powHalf ] ; norm_num
  exact h_ineq

/-- The ray reached from `a` by finitely many positive `ε`-steps. -/
def FiniteStepRay (a ε : Surreal.{0}) : Set Surreal.{0} :=
  {x | ∃ n : ℕ, x < a + (n : Surreal.{0}) * ε}

/-
A finite-step ray is open in the interval/order topology.
-/
theorem finiteStepRay_isOpen (a ε : Surreal.{0}) : IsOpen (FiniteStepRay a ε) := by
  rw [ FiniteStepRay ];
  rw [ show { x | ∃ n : ℕ, x < a + ↑n * ε } = ⋃ n : ℕ, Set.Iio ( a + ↑n * ε ) by ext; aesop ] ; exact isOpen_iUnion fun n => isOpen_Iio;

/-
For positive step size, a finite-step ray is also closed.
-/
theorem finiteStepRay_isClosed (a ε : Surreal.{0}) (hε : 0 < ε) :
    IsClosed (FiniteStepRay a ε) := by
  refine' isClosed_of_closure_subset _;
  intro x hx; by_contra h; simp_all +decide [ mem_closure_iff ] ;
  contrapose! hx; simp_all +decide ;
  refine' ⟨ Set.Ioi ( x - ε ), isOpen_Ioi, _, _ ⟩ <;> simp_all +decide [ Set.ext_iff ];
  intro y hy hy'; obtain ⟨ n, hn ⟩ := hy'; exact h ⟨ n + 1, by simpa [ add_mul, sub_lt_iff_lt_add' ] using by linarith ⟩ ;

/-
Any two distinct surreals can be separated by a clopen set.
-/
theorem exists_clopen_separator {x y : Surreal.{0}} (hxy : x ≠ y) :
    ∃ U : Set Surreal.{0}, IsClopen U ∧ x ∈ U ∧ y ∈ Uᶜ := by
  cases' lt_or_gt_of_ne hxy with hxy hxy;
  · obtain ⟨ ε, hε_pos, hε ⟩ := Surreal.exists_infinitesimal_below ( sub_pos.mpr hxy );
    refine' ⟨ FiniteStepRay x ε, _, _, _ ⟩;
    · exact ⟨ finiteStepRay_isClosed x ε hε_pos, finiteStepRay_isOpen x ε ⟩;
    · exact ⟨ 1, by simpa using hε_pos ⟩;
    · exact fun ⟨ n, hn ⟩ => by have := hε n; rw [ lt_sub_iff_add_lt ] at this; exact hn.not_ge ( by simpa [ add_comm ] using this.le ) ;
  · obtain ⟨ ε, hε_pos, hε ⟩ := Surreal.exists_infinitesimal_below ( sub_pos.mpr hxy );
    refine' ⟨ ( FiniteStepRay y ε ) ᶜ, _, _, _ ⟩ <;> simp_all +decide [ IsClopen ];
    · exact ⟨ finiteStepRay_isOpen _ _, finiteStepRay_isClosed _ _ hε_pos ⟩;
    · exact fun ⟨ n, hn ⟩ => by linarith [ hε n ] ;
    · exact ⟨ 1, by simpa using hε_pos ⟩

/-
**Main connector theorem.** The game-theoretic/set-theoretic boundedness property of
surreals forces their interval topology to be totally separated.
-/
instance instTotallySeparatedSpace : TotallySeparatedSpace Surreal.{0} := by
  refine' ⟨ fun x y hxy => _ ⟩;
  intro _ hxy';
  obtain ⟨ U, hU₁, hU₂, hU₃ ⟩ := exists_clopen_separator hxy';
  exact ⟨ U, Uᶜ, hU₁.2, hU₁.1.isOpen_compl, hU₂, hU₃, by simp +decide, disjoint_compl_right ⟩

/-- Hence the interval-topological surreal line is totally disconnected. -/
instance instTotallyDisconnectedSpace : TotallyDisconnectedSpace Surreal.{0} :=
  inferInstance

/-
In particular, the interval-topological surreal line is not preconnected.
-/
theorem not_preconnectedSpace : ¬ PreconnectedSpace Surreal.{0} := by
  rintro ⟨ h ⟩;
  convert h.subsingleton;
  simp +decide [ Set.Subsingleton ];
  exact ⟨ 0, 1, by norm_num ⟩

/-
Hence it is not a connected space.
-/
theorem not_connectedSpace : ¬ ConnectedSpace Surreal.{0} := by
  intro h;
  convert not_preconnectedSpace _;
  infer_instance

/-
Every path in the interval topology on the surreals is constant.
-/
theorem path_eq_endpoints {x y : Surreal.{0}} (p : Path x y) : x = y := by
  -- Apply the fact that the image of a connected set under a continuous map is connected.
  have h_connected : IsConnected (Set.range p) := by
    exact isConnected_range p.continuous;
  have h_singleton : ∀ s : Set Surreal.{0}, IsConnected s → ∃ x, s = {x} := by
    intro s hs; have := hs.isPreconnected.subsingleton;
    exact ⟨ hs.nonempty.some, Set.eq_singleton_iff_nonempty_unique_mem.mpr ⟨ hs.nonempty, fun x hx => this hx hs.nonempty.some_mem ⟩ ⟩;
  obtain ⟨ z, hz ⟩ := h_singleton _ h_connected; have := p.source; have := p.target; aesop;

/-
There is no path between two distinct surreal numbers.
-/
theorem no_path_between {x y : Surreal.{0}} (hxy : x ≠ y) : IsEmpty (Path x y) := by
  exact ⟨ fun p => hxy <| path_eq_endpoints p ⟩

/-
The interval-topological surreal line is not path connected.
-/
theorem not_pathConnectedSpace : ¬ PathConnectedSpace Surreal.{0} := by
  intro h;
  exact no_path_between ( show 0 ≠ 1 by simp ) |>.elim ( PathConnectedSpace.somePath 0 1 )

/-
Therefore it cannot be contractible.
-/
theorem not_contractibleSpace : ¬ ContractibleSpace Surreal.{0} := by
  intro h;
  exact no_path_between ( show 0 ≠ 1 by simp ) |>.elim ( PathConnectedSpace.somePath 0 1 )

/-
Despite non-contractibility, every based fundamental group is trivial, because every
loop is a constant path. This is the algebraic-topology side of the connector.
-/
theorem fundamentalGroup_subsingleton (x : Surreal.{0}) :
    Subsingleton (FundamentalGroup Surreal.{0} x) := by
  constructor;
  intro a b
  obtain ⟨p, hp⟩ := a
  obtain ⟨q, hq⟩ := b
  have h_eq : p = q := by
    have h_eq : ∀ t : unitInterval, p t = x ∧ q t = x := by
      intro t; exact ⟨ by
        have h_const : IsConnected (Set.range p) := by
          exact isConnected_range p.continuous;
        have := h_const.isPreconnected.subsingleton ( Set.mem_range_self t ) ( Set.mem_range_self 0 ) ; aesop;, by
        have h_const : IsPreconnected (Set.range q) := by
          exact isPreconnected_range q.continuous;
        have := h_const.subsingleton ( Set.mem_range_self t ) ( Set.mem_range_self 0 ) ; aesop; ⟩ ;
    exact ContinuousMap.ext fun t => by simp +decide [ h_eq t ] ;
  exact (by
  aesop)

/-
Explicit group-theoretic form of `π₁(No,x)=0`.
-/
theorem fundamentalGroup_eq_one (x : Surreal.{0})
    (γ : FundamentalGroup Surreal.{0} x) : γ = 1 := by
  convert ( fundamentalGroup_subsingleton x ).allEq γ 1

end Surreal

end SurrealTopologyConnector