/-
# CM-ECM-GENERAL: the `j = 0` curve `y² = x³ + 1` over `𝔽_p` (CM by `ℤ[ω]`)

This file is the arithmetic core of the CM-ECM-GENERAL experiment (round 17 #2):
a stress test of the ECM "order shadow" on the second CM field `ℚ(√-3)`, whose
canonical curve is the `j = 0` curve

  `E_{j0} : y² = x³ + 1`,   `End = ℤ[ω]`,   bad primes `2, 3`.

Two structural facts drive the whole experiment, and both are proved here from
scratch (no elliptic-curve group law is imported; everything is explicit
counting plus explicit rational maps).

* **Rational-torsion degeneracy (§3).**  `E_{j0}` carries the rational
  `3`-torsion point `T = (0,1)`.  Translation by `T` is realised here as an
  explicit fixed-point-free self-map of order `3` of the point set, giving

    `3 ∣ #E_{j0}(𝔽_p)`  for every prime `p > 3`   (`three_dvd_curveCard_j0`).

  The divisibility is therefore *unconditional*: as a random variable indexed by
  `p`, the event `3 ∣ #E_{j0}(𝔽_p)` is **constant**, so it can carry no
  information about anything (the information-theoretic half of this statement
  is `Probability.CMECMGeneralInformation`).

* **Inert collapse (§4).**  For `p ≡ 2 (mod 3)` the cubing map is a bijection of
  `𝔽_p`, whence

    `#E_{j0}(𝔽_p) = p + 1` exactly  (`inert_curveCard`), i.e. `a_p = 0`
    (`inert_trace_zero`).

  So on the inert half ECM on the `j = 0` curve *is* the `p+1` method (Williams,
  1982), and the residue dial
    `9 ∣ #E_{j0}(𝔽_p) ↔ p ≡ 8 (mod 9)`  (`inert_nine_dvd_iff`)
  is exactly the visible `ℓ = 9` channel measured in the experiment.

* **3-adic Hecke visibility (§5).**  Combining the two, the trace of Frobenius
  satisfies `a_p ≡ p + 1 (mod 3)` for every prime `p > 3`
  (`trace_congr_three`): the trace is residue-visible modulo the *ramified*
  prime `3` of `ℤ[ω]`, and is pinned to `0` on the whole inert half.

Point counts are the ones from the catalogue file `Algebra.ECMParityCore`
(`ECMParity.curveCard A B = 1 + #{(x,y) : y² = x³ + A x + B}`), specialised to
`A = 0`, `B = 1`.
-/
import Mathlib
import Algebra.ECMParityCore

namespace CMECMGeneral

open Finset Function MulAction

/-! ## 0. A counting lemma: a free self-map of order three forces `3 ∣ #α` -/

/-- If a finite type carries a self-map `f` with `f³ = id` and no fixed point,
then its cardinality is divisible by `3`.  (This is the counting shadow of a
free `ℤ/3`-action; we get it from the `p`-group fixed-point congruence applied
to the cyclic subgroup of `Perm α` generated by `f`.) -/
theorem three_dvd_card_of_free_order_three {α : Type*} [Fintype α]
    (f : α → α) (h3 : ∀ x, f (f (f x)) = x) (hfree : ∀ x, f x ≠ x) :
    3 ∣ Fintype.card α := by
  classical
  let g : Equiv.Perm α := ⟨f, fun x => f (f x), fun x => h3 x, fun x => h3 x⟩
  have hgapp : ∀ x, g x = f x := fun _ => rfl
  have hg3 : g ^ 3 = 1 := by
    ext x
    simp [pow_succ, Equiv.Perm.mul_apply, hgapp, h3]
  by_cases hα : IsEmpty α
  · simp [Fintype.card_eq_zero]
  · rw [not_isEmpty_iff] at hα
    obtain ⟨x0⟩ := hα
    have hgne : g ≠ 1 := fun h => hfree x0 (by
      have := congrArg (fun e : Equiv.Perm α => e x0) h; simpa [hgapp] using this)
    have horder : orderOf g = 3 := by
      have hdvd : orderOf g ∣ 3 := orderOf_dvd_of_pow_eq_one hg3
      rcases Nat.prime_three.eq_one_or_self_of_dvd _ hdvd with h | h
      · exact absurd (orderOf_eq_one_iff.mp h) hgne
      · exact h
    set G := Subgroup.zpowers g with hG
    have hcard : Nat.card G = 3 ^ 1 := by rw [Nat.card_zpowers, horder]; norm_num
    have hp : IsPGroup 3 G := IsPGroup.of_card hcard
    have hempty : IsEmpty (fixedPoints G α) := by
      constructor
      rintro ⟨x, hx⟩
      have hxx : (⟨g, Subgroup.mem_zpowers g⟩ : G) • x = x := hx _
      exact hfree x (by simpa [hgapp] using hxx)
    have hmod := hp.card_modEq_card_fixedPoints (α := α)
    rw [Nat.card_eq_fintype_card (α := fixedPoints G α)] at hmod
    simp [Fintype.card_eq_zero] at hmod
    exact Nat.modEq_zero_iff_dvd.mp hmod

/-! ## 1. Translation by the 3-torsion point `(0,1)`: the rational maps

Over any field, adding the point `T = (0,1)` to an affine point `(x,y)` of
`y² = x³ + 1` with `x ≠ 0` gives the point `(trX x y, trY y)` below; the chord
through `(x,y)` and `T` has slope `(y-1)/x`, and the curve relation collapses
the second coordinate to the Möbius transformation `y ↦ (y-3)/(y+1)`. -/

section FieldAlgebra

variable {F : Type*} [Field F]

/-- The `x`-coordinate of `(x,y) + (0,1)` on `y² = x³ + 1`. -/
def trX (x y : F) : F := 2 * (1 - y) / x ^ 2

/-- The `y`-coordinate of `(x,y) + (0,1)` on `y² = x³ + 1`: a Möbius map of
order three. -/
def trY (y : F) : F := (y - 3) / (y + 1)

/-- Translation by `(0,1)` on the locus `x ≠ 0`. -/
def tr (P : F × F) : F × F := (trX P.1 P.2, trY P.2)

variable {x y : F}

/-- On `y² = x³ + 1` an affine point with `x ≠ 0` has `y ≠ ±1`. -/
theorem y_sub_one_ne_zero (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) : y - 1 ≠ 0 := by
  intro hc
  apply hx
  have hx3 : x ^ 3 = 0 := by linear_combination -h + (y + 1) * hc
  exact pow_eq_zero_iff (by norm_num) |>.mp hx3

theorem y_add_one_ne_zero (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) : y + 1 ≠ 0 := by
  intro hc
  apply hx
  have hx3 : x ^ 3 = 0 := by linear_combination -h + (y - 1) * hc
  exact pow_eq_zero_iff (by norm_num) |>.mp hx3

/-- Translation by `(0,1)` lands on the curve again. -/
theorem tr_curve (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    (trY y) ^ 2 = (trX x y) ^ 3 + 1 := by
  have hy1 : y + 1 ≠ 0 := y_add_one_ne_zero h hx
  unfold trX trY
  field_simp
  linear_combination (-8 * (1 - y) * (x ^ 3 - 1 + y ^ 2)) * h

/-- The translated point again has nonzero `x`-coordinate: the locus `x ≠ 0` is
stable, i.e. translation by `(0,1)` never hits `±(0,1)` from there. -/
theorem trX_ne_zero (h2 : (2 : F) ≠ 0) (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    trX x y ≠ 0 := by
  have hy1 : y - 1 ≠ 0 := y_sub_one_ne_zero h hx
  unfold trX
  refine div_ne_zero (mul_ne_zero h2 fun hc => hy1 ?_) (pow_ne_zero _ hx)
  linear_combination -hc

/-- Second iterate, `y`-coordinate: `y ↦ -(y+3)/(y-1)`. -/
theorem trY_trY (h2 : (2 : F) ≠ 0) (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    trY (trY y) = -(y + 3) / (y - 1) := by
  have hy1 : y - 1 ≠ 0 := y_sub_one_ne_zero h hx
  have hyp1 : y + 1 ≠ 0 := y_add_one_ne_zero h hx
  unfold trY
  have hd : (y - 3) / (y + 1) + 1 ≠ 0 := by
    rw [div_add' _ _ _ hyp1]
    refine div_ne_zero (fun hc => hy1 ?_) hyp1
    have h2y : (2 : F) * (y - 1) = 0 := by linear_combination hc
    rcases mul_eq_zero.mp h2y with h' | h'
    · exact absurd h' h2
    · exact h'
  rw [div_eq_div_iff hd hy1]
  field_simp
  ring

/-- Second iterate, `x`-coordinate: `x ↦ 2x/(y-1)` (uses the curve relation). -/
theorem trX_trX (h2 : (2 : F) ≠ 0) (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    trX (trX x y) (trY y) = 2 * x / (y - 1) := by
  have hy1 : y - 1 ≠ 0 := y_sub_one_ne_zero h hx
  have hyp1 : y + 1 ≠ 0 := y_add_one_ne_zero h hx
  have hne : (trX x y) ^ 2 ≠ 0 := pow_ne_zero _ (trX_ne_zero h2 h hx)
  unfold trX trY at *
  rw [div_eq_div_iff hne hy1]
  field_simp
  linear_combination (-4 * (y - 1)) * h

/-- Third iterate, `y`-coordinate: back to `y`. -/
theorem trY_third (h2 : (2 : F) ≠ 0) (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    trY (-(y + 3) / (y - 1)) = y := by
  have hy1 : y - 1 ≠ 0 := y_sub_one_ne_zero h hx
  unfold trY
  have hd : -(y + 3) / (y - 1) + 1 ≠ 0 := by
    rw [div_add' _ _ _ hy1]
    refine div_ne_zero (fun hc => h2 ?_) hy1
    have h4 : (2 : F) * 2 = 0 := by linear_combination -hc
    rcases mul_eq_zero.mp h4 with h' | h' <;> exact h'
  rw [div_eq_iff hd]
  field_simp
  ring

/-- Third iterate, `x`-coordinate: back to `x` (uses the curve relation). -/
theorem trX_third (h2 : (2 : F) ≠ 0) (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    trX (2 * x / (y - 1)) (-(y + 3) / (y - 1)) = x := by
  have hy1 : y - 1 ≠ 0 := y_sub_one_ne_zero h hx
  have hne : (2 * x / (y - 1)) ^ 2 ≠ 0 :=
    pow_ne_zero _ (div_ne_zero (mul_ne_zero h2 hx) hy1)
  unfold trX
  rw [div_eq_iff hne]
  field_simp
  linear_combination (2 : F) * h

/-- **Translation by `(0,1)` has order three** on the locus `x ≠ 0`. -/
theorem tr_tr_tr (h2 : (2 : F) ≠ 0) (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) :
    tr (tr (tr (x, y))) = (x, y) := by
  have h1 : tr (x, y) = (trX x y, trY y) := rfl
  have hx1 : trX x y ≠ 0 := trX_ne_zero h2 h hx
  have hc1 : (trY y) ^ 2 = (trX x y) ^ 3 + 1 := tr_curve h hx
  have h2' : tr (trX x y, trY y) = (2 * x / (y - 1), -(y + 3) / (y - 1)) := by
    have hA : trX (trX x y) (trY y) = 2 * x / (y - 1) := trX_trX h2 h hx
    have hB : trY (trY y) = -(y + 3) / (y - 1) := trY_trY h2 h hx
    exact Prod.ext hA hB
  rw [h1, h2']
  exact Prod.ext (trX_third h2 h hx) (trY_third h2 h hx)

/-- **Translation by `(0,1)` is fixed-point free** on the locus `x ≠ 0`, as soon
as `2 ≠ 0` and `3 ≠ 0`: a fixed point would force `y = -3` and `y² = -3`,
i.e. `12 = 0`. -/
theorem tr_ne_self (h2 : (2 : F) ≠ 0) (h3 : (3 : F) ≠ 0)
    (h : y ^ 2 = x ^ 3 + 1) (hx : x ≠ 0) : tr (x, y) ≠ (x, y) := by
  intro hfix
  have hy1 : y - 1 ≠ 0 := y_sub_one_ne_zero h hx
  have hyp1 : y + 1 ≠ 0 := y_add_one_ne_zero h hx
  have hX : trX x y = x := congrArg Prod.fst hfix
  have hY : trY y = y := congrArg Prod.snd hfix
  -- the `x`-equation forces `y = -3`
  have hxe : 2 * (1 - y) = x ^ 3 := by
    unfold trX at hX
    rw [div_eq_iff (pow_ne_zero 2 hx)] at hX
    linear_combination hX
  have hy3 : (y + 3) * (y - 1) = 0 := by linear_combination h - hxe
  have hy3' : y = -3 := by
    rcases mul_eq_zero.mp hy3 with h' | h'
    · linear_combination h'
    · exact absurd h' hy1
  -- the `y`-equation forces `y² = -3`
  have hye : y ^ 2 = -3 := by
    unfold trY at hY
    rw [div_eq_iff hyp1] at hY
    linear_combination -hY
  -- together: `12 = 0`
  rw [hy3'] at hye
  have h12 : (2 : F) * 2 * 3 = 0 := by linear_combination hye
  rcases mul_eq_zero.mp h12 with h' | h'
  · rcases mul_eq_zero.mp h' with h'' | h'' <;> exact h2 h''
  · exact h3 h'

end FieldAlgebra

/-! ## 2. The point set of the `j = 0` curve over `𝔽_p` -/

variable {p : ℕ} [Fact p.Prime]

/-- Affine points of `E_{j0} : y² = x³ + 1` over `𝔽_p`. -/
abbrev J0Aff (p : ℕ) [Fact p.Prime] := {P : ZMod p × ZMod p // P.2 ^ 2 = P.1 ^ 3 + 1}

/-- All points of `E_{j0}` over `𝔽_p`: the affine ones plus the point at infinity. -/
abbrev J0 (p : ℕ) [Fact p.Prime] := Option (J0Aff p)

/-- The point set has exactly `curveCard 0 1` elements. -/
theorem card_J0 : Fintype.card (J0 p) = ECMParity.curveCard (0 : ZMod p) 1 := by
  classical
  have hset : (univ.filter fun P : ZMod p × ZMod p => P.2 ^ 2 = ECMParity.cubic 0 1 P.1)
      = (univ.filter fun P : ZMod p × ZMod p => P.2 ^ 2 = P.1 ^ 3 + 1) := by
    apply filter_congr
    intro P _
    simp [ECMParity.cubic]
  rw [Fintype.card_option, Fintype.card_subtype, ECMParity.curveCard,
    ECMParity.affinePoints, hset]
  omega

/-- `3 ≠ 0` in `𝔽_p` for `p ≠ 3`. -/
theorem three_ne_zero_of_ne_three (hp : p ≠ 3) : (3 : ZMod p) ≠ 0 := by
  intro h
  have h3 : ((3 : ℕ) : ZMod p) = 0 := by exact_mod_cast h
  rw [ZMod.natCast_eq_zero_iff] at h3
  exact hp ((Nat.prime_dvd_prime_iff_eq (Fact.out : p.Prime) Nat.prime_three).1 h3)

/-! ## 3. Rational-torsion degeneracy: `3 ∣ #E_{j0}(𝔽_p)` for all `p > 3` -/

/-- Translation by the rational `3`-torsion point `T = (0,1)`, as a self-map of
the full point set: `∞ ↦ T ↦ -T ↦ ∞`, and `P ↦ P + T` on the locus `x ≠ 0`. -/
def step (hp2 : p ≠ 2) : J0 p → J0 p
  | none => some ⟨(0, 1), by norm_num⟩
  | some ⟨(x, y), h⟩ =>
      if hx : x = 0 then
        (if y = 1 then some ⟨(0, -1), by norm_num⟩ else none)
      else some ⟨tr (x, y), by
        have := ECMParity.two_ne_zero_of_odd (p := p) hp2
        exact tr_curve h hx⟩

/-- On the `x = 0` locus the only points are `(0, ±1)`. -/
theorem y_eq_neg_one_of_x_eq_zero {x y : ZMod p}
    (h : y ^ 2 = x ^ 3 + 1) (hx : x = 0) (hy : y ≠ 1) : y = -1 := by
  subst hx
  have hfac : (y - 1) * (y + 1) = 0 := by linear_combination h
  rcases mul_eq_zero.mp hfac with h' | h'
  · exact absurd (by linear_combination h') hy
  · linear_combination h'

theorem step_none (hp2 : p ≠ 2) : step hp2 (none : J0 p) = some ⟨(0, 1), by norm_num⟩ := rfl

theorem step_T (hp2 : p ≠ 2) :
    step hp2 (some ⟨(0, 1), by norm_num⟩ : J0 p) = some ⟨(0, -1), by norm_num⟩ := by
  simp [step]

theorem step_negT (hp2 : p ≠ 2) :
    step hp2 (some ⟨(0, -1), by norm_num⟩ : J0 p) = (none : J0 p) := by
  have h1 : (-1 : ZMod p) ≠ 1 := by
    intro hc
    have h2 : (2 : ZMod p) = 0 := by linear_combination -hc
    exact ECMParity.two_ne_zero_of_odd hp2 h2
  simp [step, h1]

/-- The translation map has order three on the whole point set. -/
theorem step_cube (hp2 : p ≠ 2) (P : J0 p) : step hp2 (step hp2 (step hp2 P)) = P := by
  have h2F := ECMParity.two_ne_zero_of_odd (p := p) hp2
  match P with
  | none => rw [step_none, step_T, step_negT]
  | some ⟨(x, y), h⟩ =>
      by_cases hx : x = 0
      · subst hx
        by_cases hy : y = 1
        · subst hy
          rw [show (some ⟨((0 : ZMod p), (1 : ZMod p)), h⟩ : J0 p)
              = some ⟨(0, 1), by norm_num⟩ from rfl, step_T, step_negT, step_none]
        · have hy' : y = -1 := y_eq_neg_one_of_x_eq_zero h rfl hy
          subst hy'
          rw [show (some ⟨((0 : ZMod p), (-1 : ZMod p)), h⟩ : J0 p)
              = some ⟨(0, -1), by norm_num⟩ from rfl, step_negT, step_none, step_T]
      · have hx1 : (tr (x, y)).1 ≠ 0 := trX_ne_zero h2F h hx
        have hc1 : (tr (x, y)).2 ^ 2 = (tr (x, y)).1 ^ 3 + 1 := tr_curve h hx
        have hx2 : (tr (tr (x, y))).1 ≠ 0 := trX_ne_zero h2F hc1 hx1
        have hc2 : (tr (tr (x, y))).2 ^ 2 = (tr (tr (x, y))).1 ^ 3 + 1 := tr_curve hc1 hx1
        have e1 : step hp2 (some ⟨(x, y), h⟩ : J0 p) = some ⟨tr (x, y), hc1⟩ := by
          simp only [step, dif_neg hx]
        have e2 : step hp2 (some ⟨tr (x, y), hc1⟩ : J0 p) = some ⟨tr (tr (x, y)), hc2⟩ := by
          rw [show (some ⟨tr (x, y), hc1⟩ : J0 p)
            = some ⟨((tr (x, y)).1, (tr (x, y)).2), hc1⟩ from rfl]
          simp only [step, dif_neg hx1]
        have hc3 : (tr (tr (tr (x, y)))).2 ^ 2 = (tr (tr (tr (x, y)))).1 ^ 3 + 1 :=
          tr_curve hc2 hx2
        have e3 : step hp2 (some ⟨tr (tr (x, y)), hc2⟩ : J0 p)
            = some ⟨tr (tr (tr (x, y))), hc3⟩ := by
          rw [show (some ⟨tr (tr (x, y)), hc2⟩ : J0 p)
            = some ⟨((tr (tr (x, y))).1, (tr (tr (x, y))).2), hc2⟩ from rfl]
          simp only [step, dif_neg hx2]
        rw [e1, e2, e3]
        simp only [Option.some.injEq]
        exact Subtype.ext (tr_tr_tr h2F h hx)

/-- The translation map is fixed-point free (`p > 3`). -/
theorem step_ne_self (hp2 : p ≠ 2) (hp3 : p ≠ 3) (P : J0 p) : step hp2 P ≠ P := by
  have h2F := ECMParity.two_ne_zero_of_odd (p := p) hp2
  have h3F := three_ne_zero_of_ne_three (p := p) hp3
  match P with
  | none => rw [step_none]; exact Option.some_ne_none _
  | some ⟨(x, y), h⟩ =>
      by_cases hx : x = 0
      · subst hx
        by_cases hy : y = 1
        · subst hy
          rw [show (some ⟨((0 : ZMod p), (1 : ZMod p)), h⟩ : J0 p)
              = some ⟨(0, 1), by norm_num⟩ from rfl, step_T]
          intro hc
          have h1 : ((0 : ZMod p), (-1 : ZMod p)) = ((0 : ZMod p), (1 : ZMod p)) :=
            congrArg Subtype.val (Option.some.inj hc)
          have h2 := congrArg Prod.snd h1
          simp only at h2
          exact h2F (by linear_combination -h2)
        · have hy' : y = -1 := y_eq_neg_one_of_x_eq_zero h rfl hy
          subst hy'
          rw [show (some ⟨((0 : ZMod p), (-1 : ZMod p)), h⟩ : J0 p)
              = some ⟨(0, -1), by norm_num⟩ from rfl, step_negT]
          exact (Option.some_ne_none _).symm
      · have hc1 : (tr (x, y)).2 ^ 2 = (tr (x, y)).1 ^ 3 + 1 := tr_curve h hx
        have e1 : step hp2 (some ⟨(x, y), h⟩ : J0 p) = some ⟨tr (x, y), hc1⟩ := by
          simp only [step, dif_neg hx]
        rw [e1]
        intro hc
        have := Subtype.ext_iff.mp (Option.some.inj hc)
        exact tr_ne_self h2F h3F h hx this

/-- **Rational-torsion degeneracy.**  For every prime `p > 3`,
`3 ∣ #E_{j0}(𝔽_p)`: the `j = 0` curve has a rational `3`-torsion point, so the
`ℓ = 3` ECM order event is a *constant*, not a random variable. -/
theorem three_dvd_curveCard_j0 (hp2 : p ≠ 2) (hp3 : p ≠ 3) :
    3 ∣ ECMParity.curveCard (0 : ZMod p) 1 := by
  rw [← card_J0]
  exact three_dvd_card_of_free_order_three (step hp2) (step_cube hp2) (step_ne_self hp2 hp3)

/-! ## 4. The inert half: exact collapse `#E = p + 1` -/

/-- The exponent inverting cubing when `p ≡ 2 (mod 3)`: `3 · cbrtExp p = 2(p-1)+1`. -/
def cbrtExp (p : ℕ) : ℕ := (2 * p - 1) / 3

theorem cube_pow_eq (hp : p % 3 = 2) (u : ZMod p) : u ^ (3 * cbrtExp p) = u := by
  have h2 : 2 ≤ p := (Fact.out : p.Prime).two_le
  have hk : 3 * cbrtExp p = (p - 1) * 2 + 1 := by unfold cbrtExp; omega
  rw [hk]
  by_cases hu : u = 0
  · subst hu; simp
  · rw [pow_succ, pow_mul, ZMod.pow_card_sub_one_eq_one hu, one_pow, one_mul]

/-- Cubing is surjective on `𝔽_p` when `p ≡ 2 (mod 3)`. -/
theorem cube_root (hp : p % 3 = 2) (u : ZMod p) : (u ^ cbrtExp p) ^ 3 = u := by
  rw [← pow_mul, mul_comm]; exact cube_pow_eq hp u

/-- Cubing is injective on `𝔽_p` when `p ≡ 2 (mod 3)`. -/
theorem cube_root' (hp : p % 3 = 2) (u : ZMod p) : (u ^ 3) ^ cbrtExp p = u := by
  rw [← pow_mul, mul_comm 3, mul_comm]; exact cube_pow_eq hp u

/-- **Inert collapse, affine count.**  For `p ≡ 2 (mod 3)` the `y`-coordinate is
a bijection from the affine points of `y² = x³+1` onto `𝔽_p`. -/
theorem inert_affine_card (hp : p % 3 = 2) :
    (ECMParity.affinePoints (0 : ZMod p) 1).card = p := by
  classical
  have hset : ECMParity.affinePoints (0 : ZMod p) 1
      = (univ.filter fun P : ZMod p × ZMod p => P.2 ^ 2 = P.1 ^ 3 + 1) := by
    apply filter_congr
    intro P _
    simp [ECMParity.cubic]
  rw [hset]
  have hcard := Finset.card_bij'
      (s := univ.filter fun P : ZMod p × ZMod p => P.2 ^ 2 = P.1 ^ 3 + 1)
      (t := (univ : Finset (ZMod p)))
      (fun P _ => P.2) (fun y _ => ((y ^ 2 - 1) ^ cbrtExp p, y))
      (by intro a _; exact mem_univ _)
      (by
        intro y _
        simp only [mem_filter, mem_univ, true_and]
        rw [cube_root hp]; ring)
      (by
        intro P hP
        simp only [mem_filter, mem_univ, true_and] at hP
        have h1 : P.2 ^ 2 - 1 = P.1 ^ 3 := by linear_combination hP
        refine Prod.ext ?_ rfl
        show (P.2 ^ 2 - 1) ^ cbrtExp p = P.1
        rw [h1, cube_root' hp])
      (by intro y _; rfl)
  rw [hcard]
  simp [ZMod.card]

/-- **Inert collapse.**  For `p ≡ 2 (mod 3)`, `#E_{j0}(𝔽_p) = p + 1` exactly:
ECM on the `j = 0` curve *is* the `p+1` method on the inert half. -/
theorem inert_curveCard (hp : p % 3 = 2) : ECMParity.curveCard (0 : ZMod p) 1 = p + 1 := by
  rw [ECMParity.curveCard, inert_affine_card hp]; omega

/-- The trace of Frobenius `a_p = p + 1 - #E`. -/
def traceJ0 (p : ℕ) [Fact p.Prime] : ℤ := (p : ℤ) + 1 - (ECMParity.curveCard (0 : ZMod p) 1 : ℤ)

/-- **Exact inert collapse of the trace**: `a_p = 0` for every `p ≡ 2 (mod 3)`. -/
theorem inert_trace_zero (hp : p % 3 = 2) : traceJ0 p = 0 := by
  rw [traceJ0, inert_curveCard hp]; push_cast; ring

/-- On the inert half the `ℓ = 3` channel is again unconditional. -/
theorem inert_three_dvd (hp : p % 3 = 2) : 3 ∣ ECMParity.curveCard (0 : ZMod p) 1 := by
  rw [inert_curveCard hp]; omega

/-- **The `ℓ = 9` residue dial.**  On the inert half, `9 ∣ #E_{j0}(𝔽_p)` happens
exactly on the residue class `p ≡ 8 (mod 9)` — the visible channel of the
experiment. -/
theorem inert_nine_dvd_iff (hp : p % 3 = 2) :
    9 ∣ ECMParity.curveCard (0 : ZMod p) 1 ↔ p % 9 = 8 := by
  rw [inert_curveCard hp]
  omega

/-! ## 5. 3-adic Hecke visibility -/

/-- **Visibility at the ramified prime.**  For every prime `p > 3` the trace of
Frobenius of the `j = 0` curve is pinned modulo `3` by the residue of `p`:
`a_p ≡ p + 1 (mod 3)`. -/
theorem trace_congr_three (hp2 : p ≠ 2) (hp3 : p ≠ 3) :
    traceJ0 p ≡ (p : ℤ) + 1 [ZMOD 3] := by
  obtain ⟨k, hk⟩ := three_dvd_curveCard_j0 (p := p) hp2 hp3
  have : traceJ0 p - ((p : ℤ) + 1) = -3 * (k : ℤ) := by
    rw [traceJ0, hk]; push_cast; ring
  exact Int.ModEq.symm (Int.modEq_iff_dvd.mpr ⟨-(k : ℤ), by linarith [this]⟩)

/-- Consequence of the two halves: on the inert half the trace is *exactly* `0`,
so the mod-3 datum `a_p ≡ p+1 ≡ 0 (mod 3)` is realised with no slack. -/
theorem inert_trace_congr (hp : p % 3 = 2) : traceJ0 p = 0 ∧ (p : ℤ) + 1 ≡ 0 [ZMOD 3] := by
  refine ⟨inert_trace_zero hp, ?_⟩
  have : ((p : ℤ) + 1) % 3 = 0 := by omega
  simpa [Int.ModEq] using this

end CMECMGeneral