/-
# Cycle 7: The general aperiodicity criterion for soundness spectra

Cycle 6 (`Probability.MarkovFrobeniusSpectrum`) showed that the Cycle-2 soundness
spectrum of a world is the **cycle monoid** `cycleMonoid F w`, an additive submonoid of
`ℕ`, and computed its cofiniteness threshold in the *two-generator* case via Mathlib's
Chicken–McNugget theorem (`iterR_of_gt_frobenius`).  What was left open — and recorded
as Future Direction 1 — is the **general** case: an arbitrary set of return lengths,
with no coprime pair singled out.

This file closes that gap.  The criterion is purely arithmetic:

> an additive submonoid `S ≤ ℕ` is cofinite **iff** no integer `d ≥ 2` divides all of
> `S`.

The proof does not go through generators at all.  The **difference subgroup**
`diffSubgroup S ≤ ℤ` is cyclic (`Int.subgroup_cyclic`); its generator `d` divides every
element of `S`, so the aperiodicity hypothesis forces `d = 1`, hence `S` contains two
*consecutive* numbers `y, y+1`, and then the classical box argument
`n = (q - r)·y + r·(y+1)` puts every `n ≥ y²` in `S`.

Transported along `cycleMonoid`, this yields the sharp form of Perron–Frobenius
primitivity:

* `iterR_cofinite_iff_aperiodic` — the return lengths at a world are cofinite iff the
  world is aperiodic (no `d ≥ 2` divides all its cycle lengths);
* `iterSound_cofinite_iff_aperiodic` — the same statement for the Cycle-2 soundness
  spectrum `IterSoundAt`;
* `exists_uniform_primitive_of_aperiodic` and `stepPow_pos_of_aperiodic` — an
  irreducible finite chain with **one** aperiodic state is primitive with a uniform
  exponent, with **no** self-loop and **no** coprime-pair hypothesis;
* `stepPow_primitive_iff_aperiodic` — for a finite irreducible chain, primitivity is
  *equivalent* to aperiodicity of any single state.

The two hypotheses used in Cycle 6 (a self-loop; two coprime cycles) are recovered as
`cycleAperiodic_of_selfLoop` and `cycleAperiodic_of_coprime_cycles`, and the two running
examples are classified: the `n`-cycle (`n ≥ 2`) is *not* aperiodic, while the loopless
chain `apChain` is, so it is primitive.
-/

import Mathlib
import Probability.MarkovFrobeniusSpectrum

namespace MarkovModal

open GLPLogic TangledSoundness FrameDefinability

variable {S : Type} {α : Type}

/-! ## Part A — Cofiniteness of additive submonoids of `ℕ` -/

/-- An additive submonoid of `ℕ` is **aperiodic** when no `d ≥ 2` divides all of its
elements.  (For a cycle monoid this is exactly aperiodicity of a Markov state: the gcd of
the return times is `1`.) -/
def NatAperiodic (S : AddSubmonoid ℕ) : Prop := ∀ d : ℕ, 2 ≤ d → ∃ n ∈ S, ¬ d ∣ n

/-- **The box argument.**  A submonoid of `ℕ` containing two consecutive numbers `y` and
`y + 1` contains every `n ≥ y²`: write `n = q·y + r` with `r < y ≤ q` and split it as
`(q - r)·y + r·(y+1)`. -/
theorem mem_of_consecutive (S : AddSubmonoid ℕ) {x y : ℕ}
    (hx : x ∈ S) (hy : y ∈ S) (hxy : x = y + 1) {n : ℕ} (hn : y * y ≤ n) : n ∈ S := by
  rcases Nat.eq_zero_or_pos y with rfl | hy0
  · subst hxy
    simpa using AddSubmonoid.nsmul_mem S hx n
  · set q := n / y with hq
    set r := n % y with hr
    have hrq : r < y := Nat.mod_lt _ hy0
    have hqy : y ≤ q := (Nat.le_div_iff_mul_le hy0).mpr hn
    obtain ⟨c, hc⟩ : ∃ c, q = c + r := ⟨q - r, by omega⟩
    have hmem : c • y + r • x ∈ S :=
      add_mem (AddSubmonoid.nsmul_mem S hy c) (AddSubmonoid.nsmul_mem S hx r)
    have hval : c • y + r • x = n := by
      have hdm : y * q + r = n := Nat.div_add_mod n y
      subst hxy
      simp only [smul_eq_mul]
      rw [hc] at hdm
      nlinarith [hdm]
    rwa [hval] at hmem

/-- The **difference subgroup** of `ℤ` attached to an additive submonoid of `ℕ`: the
set of differences of two elements.  It is the subgroup of `ℤ` generated by `S`. -/
def diffSubgroup (S : AddSubmonoid ℕ) : AddSubgroup ℤ where
  carrier := {n : ℤ | ∃ x ∈ S, ∃ y ∈ S, n = (x : ℤ) - (y : ℤ)}
  zero_mem' := ⟨0, zero_mem S, 0, zero_mem S, by simp⟩
  add_mem' := by
    rintro a b ⟨x1, hx1, y1, hy1, rfl⟩ ⟨x2, hx2, y2, hy2, rfl⟩
    exact ⟨x1 + x2, add_mem hx1 hx2, y1 + y2, add_mem hy1 hy2, by push_cast; ring⟩
  neg_mem' := by
    rintro a ⟨x, hx, y, hy, rfl⟩
    exact ⟨y, hy, x, hx, by ring⟩

/-- **Aperiodicity produces consecutive elements.**  The difference subgroup of `S` is
cyclic; its generator divides every element of `S`, so aperiodicity forces the generator
to be `±1`, i.e. `1 = x - y` for some `x, y ∈ S`. -/
theorem exists_consecutive_of_aperiodic (S : AddSubmonoid ℕ) (hap : NatAperiodic S) :
    ∃ x ∈ S, ∃ y ∈ S, x = y + 1 := by
  obtain ⟨a, ha⟩ := Int.subgroup_cyclic (diffSubgroup S)
  have hdvd : ∀ s ∈ S, a.natAbs ∣ s := by
    intro s hs
    have hmem : (s : ℤ) ∈ diffSubgroup S := ⟨s, hs, 0, zero_mem S, by simp⟩
    rw [ha, AddSubgroup.mem_closure_singleton] at hmem
    obtain ⟨k, hk⟩ := hmem
    have hint : (a : ℤ) ∣ (s : ℤ) := ⟨k, by rw [← hk]; simp [mul_comm]⟩
    exact Int.ofNat_dvd.mp (by simpa using (Int.natAbs_dvd.mpr hint))
  have hone : a.natAbs = 1 := by
    rcases Nat.lt_or_ge a.natAbs 2 with h | h
    · interval_cases h' : a.natAbs
      · exfalso
        obtain ⟨n, hn, hnd⟩ := hap 2 le_rfl
        exact hnd (by simp [Nat.zero_dvd.mp (hdvd n hn)])
      · rfl
    · exfalso
      obtain ⟨n, hn, hnd⟩ := hap a.natAbs h
      exact hnd (hdvd n hn)
  have h1 : (1 : ℤ) ∈ diffSubgroup S := by
    rw [ha, AddSubgroup.mem_closure_singleton]
    rcases Int.natAbs_eq a with h | h
    · exact ⟨1, by rw [h, hone]; simp⟩
    · exact ⟨-1, by rw [h, hone]; simp⟩
  obtain ⟨x, hx, y, hy, hxy⟩ := h1
  exact ⟨x, hx, y, hy, by omega⟩

/-- **The numerical-semigroup criterion.**  An additive submonoid of `ℕ` is cofinite
exactly when it is aperiodic.  This is the general statement left open by Cycle 6, where
only the two-generator (Chicken–McNugget) case was available. -/
theorem cofinite_iff_natAperiodic (S : AddSubmonoid ℕ) :
    (∃ N : ℕ, ∀ n : ℕ, N ≤ n → n ∈ S) ↔ NatAperiodic S := by
  constructor
  · rintro ⟨N, hN⟩ d hd
    -- `N * d + 1` lies in `S` and is not divisible by `d`
    refine ⟨N * d + 1, hN _ (by nlinarith), fun hdvd => ?_⟩
    have hmul : d ∣ N * d := dvd_mul_left d N
    have hone : d ∣ 1 := (Nat.dvd_add_right hmul).mp hdvd
    have := Nat.le_of_dvd one_pos hone
    omega
  · intro hap
    obtain ⟨x, hx, y, hy, hxy⟩ := exists_consecutive_of_aperiodic S hap
    exact ⟨y * y, fun n hn => mem_of_consecutive S hx hy hxy hn⟩

/-! ## Part B — Aperiodic worlds of a frame -/

/-- A world is **aperiodic** when no `d ≥ 2` divides all the lengths of its closed
paths: the modal form of aperiodicity of a Markov state. -/
def CycleAperiodic (F : KFrame) (w : F.W) : Prop :=
  ∀ d : ℕ, 2 ≤ d → ∃ k : ℕ, iterR F k w w ∧ ¬ d ∣ k

theorem cycleAperiodic_iff_natAperiodic (F : KFrame) (w : F.W) :
    CycleAperiodic F w ↔ NatAperiodic (cycleMonoid F w) := by
  constructor
  · intro h d hd
    obtain ⟨k, hk, hkd⟩ := h d hd
    exact ⟨k, hk, hkd⟩
  · intro h d hd
    obtain ⟨k, hk, hkd⟩ := h d hd
    exact ⟨k, hk, hkd⟩

/-- **The sharp cofiniteness theorem for return lengths.**  A world has closed paths of
every sufficiently large length exactly when it is aperiodic. -/
theorem iterR_cofinite_iff_aperiodic (F : KFrame) (w : F.W) :
    (∃ N : ℕ, ∀ n : ℕ, N ≤ n → iterR F n w w) ↔ CycleAperiodic F w := by
  rw [cycleAperiodic_iff_natAperiodic]
  exact cofinite_iff_natAperiodic (cycleMonoid F w)

/-- **The sharp cofiniteness theorem for the soundness spectrum.**  The Cycle-2 spectrum
`{k | IterSoundAt F α k w}` is cofinite iff `w` is aperiodic. -/
theorem iterSound_cofinite_iff_aperiodic (F : KFrame) (p : α) (w : F.W) :
    (∃ N : ℕ, ∀ n : ℕ, N ≤ n → IterSoundAt F α n w) ↔ CycleAperiodic F w := by
  rw [← iterR_cofinite_iff_aperiodic]
  constructor
  · rintro ⟨N, hN⟩
    exact ⟨N, fun n hn => (iterSound_iff_cycle F p n w).mp (hN n hn)⟩
  · rintro ⟨N, hN⟩
    exact ⟨N, fun n hn => (iterSound_iff_cycle F p n w).mpr (hN n hn)⟩

/-- A self-loop makes a world aperiodic (`1` is a return length). -/
theorem cycleAperiodic_of_selfLoop (F : KFrame) {w : F.W} (h : F.R w w) :
    CycleAperiodic F w := by
  intro d hd
  refine ⟨1, iterR_selfLoop F h 1, fun hdvd => ?_⟩
  have := Nat.le_of_dvd one_pos hdvd
  omega

/-- Two coprime return lengths make a world aperiodic: this is the hypothesis of Cycle
6's Frobenius theorem, now seen as a special case. -/
theorem cycleAperiodic_of_coprime_cycles (F : KFrame) {w : F.W} {a b : ℕ}
    (hab : Nat.Coprime a b) (hca : iterR F a w w) (hcb : iterR F b w w) :
    CycleAperiodic F w := by
  intro d hd
  by_contra hcon
  push_neg at hcon
  have hda : d ∣ a := by
    by_contra h
    exact h (by simpa using (hcon a hca))
  have hdb : d ∣ b := by
    by_contra h
    exact h (by simpa using (hcon b hcb))
  have : d ∣ Nat.gcd a b := Nat.dvd_gcd hda hdb
  rw [hab] at this
  have := Nat.le_of_dvd one_pos this
  omega

/-! ## Part C — Primitivity from a single aperiodic world -/

/-- **Padding through an aperiodic world.**  Once the return lengths at `w` are cofinite,
any approach to `w` and exit from `w` inflate to paths of every sufficiently large
length. -/
theorem iterR_of_aperiodic_pad (F : KFrame) {u v w : F.W} (hap : CycleAperiodic F w)
    {c d : ℕ} (hc : iterR F c u w) (hd : iterR F d w v) :
    ∃ N : ℕ, ∀ n : ℕ, N ≤ n → iterR F n u v := by
  obtain ⟨M, hM⟩ := (iterR_cofinite_iff_aperiodic F w).mpr hap
  refine ⟨c + d + M, fun n hn => ?_⟩
  have hloop : iterR F (n - c - d) w w := hM _ (by omega)
  have hsplit : n = c + ((n - c - d) + d) := by omega
  rw [hsplit]
  refine (iterR_add F ((n - c - d) + d) c u v).mpr ⟨w, hc, ?_⟩
  exact (iterR_add F d (n - c - d) w v).mpr ⟨w, hloop, hd⟩

/-- **Perron–Frobenius primitivity, sharp form (frames).**  An irreducible finite frame
with a single aperiodic world has paths of every sufficiently large length between every
ordered pair of worlds — with no self-loop and no coprime-pair hypothesis. -/
theorem exists_uniform_primitive_of_aperiodic (F : KFrame) [Fintype F.W] [DecidableEq F.W]
    (hirr : FrameIrreducible F) {w : F.W} (hap : CycleAperiodic F w) :
    ∃ N : ℕ, ∀ n : ℕ, N ≤ n → ∀ u v : F.W, iterR F n u v := by
  have hpair : ∀ q : F.W × F.W, ∃ N : ℕ, ∀ n : ℕ, N ≤ n → iterR F n q.1 q.2 := by
    rintro ⟨u, v⟩
    obtain ⟨c, hc⟩ := hirr u w
    obtain ⟨d, hd⟩ := hirr w v
    exact iterR_of_aperiodic_pad F hap hc hd
  choose Npair hNpair using hpair
  refine ⟨Finset.univ.sup Npair, fun n hn u v => ?_⟩
  exact hNpair (u, v) n (le_trans (Finset.le_sup (Finset.mem_univ (u, v))) hn)

/-- A state of a chain is aperiodic when its support world is. -/
def ChainAperiodic (P : S → S → ℝ) (w : S) : Prop := CycleAperiodic (suppFrame P) w

/-- **Perron–Frobenius primitivity, sharp form (chains).**  A finite irreducible chain
with one aperiodic state is primitive with a uniform exponent. -/
theorem stepPow_pos_of_aperiodic [Fintype S] [DecidableEq S] {P : S → S → ℝ}
    (hP : ∀ u v, 0 ≤ P u v) (hirr : ChainIrreducible P) {w : S} (hap : ChainAperiodic P w) :
    ∃ N : ℕ, ∀ n : ℕ, N ≤ n → ∀ u v : S, 0 < stepPow P n u v := by
  obtain ⟨N, hN⟩ :=
    @exists_uniform_primitive_of_aperiodic (suppFrame P) ‹Fintype S› ‹DecidableEq S›
      ((chainIrreducible_iff_frameIrreducible hP).mp hirr) w hap
  exact ⟨N, fun n hn u v => (stepPow_pos_iff hP n u v).mpr (hN n hn u v)⟩

/-- **Primitivity is aperiodicity.**  For a finite irreducible chain with nonnegative
entries, primitivity of the matrix is *equivalent* to aperiodicity of one — equivalently,
of every — state.  The forward direction is the sharp padding theorem; the converse
observes that a primitive chain has cofinite return times, hence an aperiodic state. -/
theorem stepPow_primitive_iff_aperiodic [Fintype S] [DecidableEq S] {P : S → S → ℝ}
    (hP : ∀ u v, 0 ≤ P u v) (hirr : ChainIrreducible P) (w : S) :
    (∃ N : ℕ, ∀ n : ℕ, N ≤ n → ∀ u v : S, 0 < stepPow P n u v) ↔ ChainAperiodic P w := by
  constructor
  · rintro ⟨N, hN⟩
    refine (iterR_cofinite_iff_aperiodic (suppFrame P) w).mp ⟨N, fun n hn => ?_⟩
    exact (stepPow_pos_iff hP n w w).mp (hN n hn w w)
  · exact fun hap => stepPow_pos_of_aperiodic hP hirr hap

/-- **Aperiodicity is a class property.**  In a finite irreducible frame, if one world is
aperiodic then every world is: periodicity cannot be localised. -/
theorem cycleAperiodic_of_cycleAperiodic (F : KFrame) [Fintype F.W] [DecidableEq F.W]
    (hirr : FrameIrreducible F) {w : F.W} (hw : CycleAperiodic F w) (u : F.W) :
    CycleAperiodic F u := by
  obtain ⟨N, hN⟩ := exists_uniform_primitive_of_aperiodic F hirr hw
  exact (iterR_cofinite_iff_aperiodic F u).mp ⟨N, fun n hn => hN n hn u u⟩

/-- The probabilistic form: aperiodicity of a finite irreducible chain does not depend on
the chosen state. -/
theorem chainAperiodic_of_chainAperiodic [Fintype S] [DecidableEq S] {P : S → S → ℝ}
    (hP : ∀ u v, 0 ≤ P u v) (hirr : ChainIrreducible P) {w : S}
    (hw : ChainAperiodic P w) (u : S) : ChainAperiodic P u :=
  (stepPow_primitive_iff_aperiodic hP hirr u).mp
    ((stepPow_primitive_iff_aperiodic hP hirr w).mpr hw)

/-! ## Part D — The two running examples, classified -/

/-- The `n`-cycle with `n ≥ 2` is **not** aperiodic: `n` divides every return length. -/
theorem cycleChain_not_aperiodic (n : ℕ) [NeZero n] (hn : 2 ≤ n) (w : ZMod n) :
    ¬ CycleAperiodic (suppFrame (cycleChain n)) w := by
  intro hap
  obtain ⟨k, hk, hkd⟩ := hap n hn
  have h := (iterR_cycleChain n k w w).mp hk
  rw [left_eq_add] at h
  exact hkd ((ZMod.natCast_eq_zero_iff k n).mp h)

/-- The loopless chain `apChain` of Cycle 6 is aperiodic at state `0` (cycles of lengths
`2` and `3`), hence — being irreducible — **primitive**, even though it has no self-loop
anywhere. -/
theorem apChain_aperiodic : ChainAperiodic apChain (0 : Fin 3) :=
  cycleAperiodic_of_coprime_cycles (suppFrame apChain) (by decide) apChain_cycle2
    apChain_cycle3

theorem apChain_frameIrreducible : FrameIrreducible (suppFrame apChain) := by
  have key : ∀ u v : Fin 3, ∃ k : ℕ, iterR (suppFrame apChain) k u v := by
    intro u v
    fin_cases u <;> fin_cases v <;>
      first
        | exact ⟨0, rfl⟩
        | exact ⟨1, _, apChain_R01, rfl⟩
        | exact ⟨1, _, apChain_R10, rfl⟩
        | exact ⟨1, _, apChain_R12, rfl⟩
        | exact ⟨1, _, apChain_R20, rfl⟩
        | exact ⟨2, _, apChain_R01, _, apChain_R12, rfl⟩
        | exact ⟨2, _, apChain_R20, _, apChain_R01, rfl⟩
  exact key

theorem apChain_irreducible : ChainIrreducible apChain :=
  (chainIrreducible_iff_frameIrreducible apChain_nonneg).mpr apChain_frameIrreducible

/-- **Capstone.**  `apChain` is primitive: every entry of every sufficiently high power
is strictly positive, although no state has positive holding probability.  This is
exactly the case that the self-loop route of Cycle 6 (`exists_uniform_primitive`) cannot
reach, and here it follows from the general aperiodicity criterion. -/
theorem apChain_primitive :
    ∃ N : ℕ, ∀ n : ℕ, N ≤ n → ∀ u v : Fin 3, 0 < stepPow apChain n u v :=
  stepPow_pos_of_aperiodic apChain_nonneg apChain_irreducible apChain_aperiodic

/-- **Trichotomy, sharpened.**  For a finite irreducible chain the three regimes of
Cycle 6's `spectrum_trichotomy` are now decided by a single arithmetic invariant: the
soundness spectrum at a state is cofinite iff the state is aperiodic, and the `n`-cycle
falls on the periodic side for every `n ≥ 2`. -/
theorem spectrum_dichotomy [Fintype S] [DecidableEq S] (p : α) {P : S → S → ℝ}
    (hP : ∀ u v, 0 ≤ P u v) (hirr : ChainIrreducible P) (w : S)
    (n : ℕ) [NeZero n] (hn : 2 ≤ n) (wn : ZMod n) :
    ((∃ N : ℕ, ∀ k : ℕ, N ≤ k → IterSoundAt (suppFrame P) α k w) ↔ ChainAperiodic P w) ∧
    ((∃ N : ℕ, ∀ k : ℕ, N ≤ k → ∀ u v : S, 0 < stepPow P k u v) ↔ ChainAperiodic P w) ∧
    ¬ CycleAperiodic (suppFrame (cycleChain n)) wn :=
  ⟨iterSound_cofinite_iff_aperiodic (suppFrame P) p w,
    stepPow_primitive_iff_aperiodic hP hirr w,
    cycleChain_not_aperiodic n hn wn⟩


end MarkovModal

-- !-- Lab Notes -- !--
--
-- Hypothesis (Hypothesizer):
--   H31. (Bold) Cycle 6's two-generator Frobenius bound is not the real theorem.  The
--        real theorem is that the *cycle monoid* of a world is cofinite exactly when no
--        `d ≥ 2` divides all return lengths — no generating set, no coprime pair, no
--        Frobenius number needed for the qualitative statement.
--   H32. If H31 holds, Perron–Frobenius primitivity of a finite irreducible chain is
--        *equivalent* to aperiodicity of a single state, and the self-loop hypothesis of
--        Cycle 6 Part III disappears entirely.
--
-- Experiment (Experimenter):
--   H31: confirmed (`cofinite_iff_natAperiodic`).  The route that worked avoids
--        generators altogether: `Int.subgroup_cyclic` applied to the difference subgroup
--        `diffSubgroup S ≤ ℤ` gives a generator `a` with `a.natAbs ∣ s` for every
--        `s ∈ S`; aperiodicity kills `a.natAbs = 0` (via `d = 2`) and `a.natAbs ≥ 2`
--        (via `d = a.natAbs`), leaving `a.natAbs = 1`, hence `1 = x - y` with
--        `x, y ∈ S`.  The box argument `n = (q - r)·y + r·(y+1)` then gives every
--        `n ≥ y²`, with `y = 0` (i.e. `1 ∈ S`) handled separately by `nsmul_mem`.
--        An earlier attempt that tried to reduce to a coprime *pair of generators*
--        failed: a generating set can have gcd `1` while no two of its members are
--        coprime, e.g. `⟨6, 10, 15⟩`, so `frobeniusNumber_pair` cannot be applied to the
--        generators and the general case needs the subgroup argument.  This is the
--        "needs a different definition" failure mode: the right invariant is the common
--        divisor of the whole monoid, not a chosen pair of generators.
--   H32: confirmed (`stepPow_primitive_iff_aperiodic`).  The forward direction is
--        padding through the aperiodic world (`iterR_of_aperiodic_pad`) plus a finite
--        `Finset.sup` of thresholds; the converse is immediate because a primitive chain
--        has all return times beyond `N`, and `iterR_cofinite_iff_aperiodic` turns
--        cofiniteness back into aperiodicity.
--
-- Analysis (Analyst):
--   Three previously separate hypotheses collapse into one.  A self-loop is the case
--   `1 ∈ cycleMonoid` (`cycleAperiodic_of_selfLoop`); two coprime cycles is the case
--   `gcd a b = 1` (`cycleAperiodic_of_coprime_cycles`); the `n`-cycle is the pure
--   counterexample `n ∣ everything` (`cycleChain_not_aperiodic`).  What survives from
--   Cycle 6 is the *quantitative* content: the Frobenius number still supplies an
--   explicit threshold in the two-generator case, whereas the general criterion gives
--   the threshold `y²` for the least pair of consecutive return lengths.
--
-- Critique (Critic):
--   * `cofinite_iff_natAperiodic` is a genuine biconditional; the easy direction is not
--     vacuous (it produces the explicit witness `N·d + 1`).
--   * No theorem here is closed by `decide` on the mathematics; the single `decide`
--     discharges `Nat.Coprime 2 3` in `apChain_aperiodic`.
--   * `stepPow_primitive_iff_aperiodic` is stated for an arbitrary state `w`; its truth
--     for *one* state therefore forces it for all, which is the standard fact that
--     aperiodicity is a class property of an irreducible chain, obtained here as a
--     corollary rather than assumed.
--   * Corner case checked: `NatAperiodic` fails for the trivial monoid `{0}` (every
--     `d` divides `0`), so Löb frames stay on the periodic side and no statement here
--     is vacuously satisfied by the empty spectrum.