import Mathlib

/-!
# Validity of the exp-580 decision rules, and why the control arm fired spuriously

Experiment 580 rested on three inferential devices.  This file proves the two
that are sound and proves the exact failure mode of the third.

1. **Permutation (randomization) p-values.**  `permPValue_valid`: for the
   randomization distribution generated by a finite group of relabellings, the
   p-value is super-uniform — the test rejects at level `α` with probability at
   most `α`, in finite samples and with no distributional assumption.  This
   licences the reported permutation p-values (family B: p = 0.34).

2. **Bonferroni multiplicity control.**  `bonferroni`: if each of `m`
   p-values is super-uniform, then the probability that *any* of them falls
   below `α / m` is at most `α`.  This is exactly the correction that killed the
   pooled rich-vs-poor KS result (raw p = 0.0038 across the tested family).

3. **The occupancy logistic regression (design B).**  The ledger flagged that
   design B fired on dense size-matched controls with quasi-separation and odds
   ratios clipped at `e^{±30}`.  `logistic_no_mle` proves this is not a
   numerical accident but a theorem: if some direction `w` separates the
   labelled scores, the log-likelihood has **no maximiser at all** — it is
   strictly increasing along the ray `t ↦ t·w`, stays strictly negative, and has
   supremum `0`.  Every fitted coefficient is then an artefact of the optimiser's
   stopping rule, so a "significant" odds ratio from such a fit carries no
   inferential content.  Design B is therefore unreliable exactly where the
   ledger flag says it is.
-/

open Finset Filter Topology MeasureTheory
open scoped ENNReal

namespace PositionalRateLink

/-! ## 1. Permutation p-values are super-uniform -/

/-- The permutation p-value of the relabelling `g`: the fraction of relabellings
whose test statistic is at least as extreme. -/
noncomputable def permPValue {G : Type*} [Fintype G] (t : G → ℝ) (g : G) : ℝ :=
  ((Finset.univ.filter (fun h => t g ≤ t h)).card : ℝ) / (Fintype.card G)

/-- Counting form of permutation validity: at most a fraction `α` of the
relabellings produce a p-value below `α`. -/
theorem permPValue_card_le {G : Type*} [Fintype G] [Nonempty G] (t : G → ℝ)
    {α : ℝ} (hα : 0 ≤ α) :
    ((Finset.univ.filter (fun g => permPValue t g ≤ α)).card : ℝ) ≤ α * Fintype.card G := by
  classical
  have hM : (0:ℝ) < Fintype.card G := by exact_mod_cast Fintype.card_pos
  set S := Finset.univ.filter (fun g => permPValue t g ≤ α) with hS
  rcases S.eq_empty_or_nonempty with h | h
  · rw [h]
    simp
    positivity
  · obtain ⟨g0, hg0S, hg0min⟩ := S.exists_min_image t h
    have hsub : S ⊆ Finset.univ.filter (fun h => t g0 ≤ t h) := by
      intro g hg
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact hg0min g hg
    have hcard := Finset.card_le_card hsub
    have hp : permPValue t g0 ≤ α := (Finset.mem_filter.1 hg0S).2
    rw [permPValue, div_le_iff₀ hM] at hp
    calc ((S.card : ℝ)) ≤ ((Finset.univ.filter (fun h => t g0 ≤ t h)).card : ℝ) := by
          exact_mod_cast hcard
      _ ≤ α * Fintype.card G := hp

/-- **Finite-sample validity of the randomization test.**  Under the null of
exchangeability the uniformly random relabelling produces a p-value below `α`
with probability at most `α`. -/
theorem permPValue_valid {G : Type*} [Fintype G] [Nonempty G] (t : G → ℝ)
    {α : ℝ} (hα : 0 ≤ α) :
    ((Finset.univ.filter (fun g => permPValue t g ≤ α)).card : ℝ) / (Fintype.card G) ≤ α := by
  have hM : (0:ℝ) < Fintype.card G := by exact_mod_cast Fintype.card_pos
  rw [div_le_iff₀ hM]
  exact permPValue_card_le t hα

/-- The permutation p-value is always strictly positive: the observed
relabelling counts itself. -/
theorem permPValue_pos {G : Type*} [Fintype G] [Nonempty G] (t : G → ℝ) (g : G) :
    0 < permPValue t g := by
  have hM : (0:ℝ) < Fintype.card G := by exact_mod_cast Fintype.card_pos
  have hmem : g ∈ Finset.univ.filter (fun h => t g ≤ t h) := by
    simp
  have hcard : 0 < (Finset.univ.filter (fun h => t g ≤ t h)).card :=
    Finset.card_pos.2 ⟨g, hmem⟩
  have : (0:ℝ) < ((Finset.univ.filter (fun h => t g ≤ t h)).card : ℝ) := by
    exact_mod_cast hcard
  exact div_pos this hM

/-! ## 2. Bonferroni family-wise error control -/

/-- **Bonferroni.**  If each of `m` p-values is super-uniform at the level
`α / m`, then the probability that the family fires is at most `α`. -/
theorem bonferroni {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ]
    {m : ℕ} (hm : 0 < m) (p : Fin m → Ω → ℝ) {α : ℝ}
    (hsuper : ∀ i, μ {ω | p i ω ≤ α / m} ≤ ENNReal.ofReal (α / m)) :
    μ {ω | ∃ i, p i ω ≤ α / m} ≤ ENNReal.ofReal α := by
  have hset : {ω | ∃ i, p i ω ≤ α / m} = ⋃ i, {ω | p i ω ≤ α / m} := by
    ext ω; simp
  rw [hset]
  refine (measure_iUnion_fintype_le μ _).trans ?_
  refine (Finset.sum_le_sum (fun i _ => hsuper i)).trans ?_
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
  have hmR : (0:ℝ) < (m:ℝ) := by exact_mod_cast hm
  have key : ENNReal.ofReal α = (m : ℝ≥0∞) * ENNReal.ofReal (α / m) := by
    rw [show ((m : ℝ≥0∞)) = ENNReal.ofReal (m : ℝ) by simp [ENNReal.ofReal_natCast],
      ← ENNReal.ofReal_mul (by positivity)]
    congr 1
    field_simp
  rw [key]

/-! ## 3. Quasi-separation destroys the occupancy logistic regression -/

/-- Log-likelihood contribution of a single observation with label `y` and
linear score `z` (logistic link). -/
noncomputable def logisticTerm (y : Bool) (z : ℝ) : ℝ :=
  if y then -Real.log (1 + Real.exp (-z)) else -Real.log (1 + Real.exp z)

lemma logisticTerm_neg (y : Bool) (z : ℝ) : logisticTerm y z < 0 := by
  have h : ∀ s : ℝ, 0 < Real.log (1 + Real.exp s) := by
    intro s
    have h1 : (1:ℝ) < 1 + Real.exp s := by have := Real.exp_pos s; linarith
    exact Real.log_pos h1
  cases y
  · simp only [logisticTerm, Bool.false_eq_true, if_false]; linarith [h z]
  · simp only [logisticTerm, if_true]; linarith [h (-z)]

lemma logisticTerm_ray_strictMono {s : ℝ} (hs : 0 < s) :
    StrictMono (fun t : ℝ => -Real.log (1 + Real.exp (-(t * s)))) := by
  intro a b hab
  have hexp : Real.exp (-(b * s)) < Real.exp (-(a * s)) := by
    apply Real.exp_lt_exp.2
    nlinarith
  have hpos : (0:ℝ) < 1 + Real.exp (-(b * s)) := by have := Real.exp_pos (-(b*s)); linarith
  have hlog := Real.log_lt_log hpos (by linarith : 1 + Real.exp (-(b*s)) < 1 + Real.exp (-(a*s)))
  simpa using by linarith [hlog]

lemma logisticTerm_tendsto {s : ℝ} (hs : 0 < s) :
    Filter.Tendsto (fun t : ℝ => -Real.log (1 + Real.exp (-(t * s)))) Filter.atTop (nhds 0) := by
  have h1 : Filter.Tendsto (fun t : ℝ => -(t * s)) Filter.atTop Filter.atBot := by
    have h0 : Filter.Tendsto (fun t : ℝ => t * s) Filter.atTop Filter.atTop :=
      Filter.tendsto_id.atTop_mul_const hs
    exact Filter.tendsto_neg_atTop_atBot.comp h0
  have h2 : Filter.Tendsto (fun t : ℝ => Real.exp (-(t * s))) Filter.atTop (nhds 0) :=
    Real.tendsto_exp_atBot.comp h1
  have hc : Filter.Tendsto (fun u : ℝ => -Real.log (1 + u)) (nhds 0) (nhds 0) := by
    have hca : ContinuousAt (fun u : ℝ => -Real.log (1 + u)) 0 :=
      ContinuousAt.neg (ContinuousAt.log (continuousAt_const.add continuousAt_id) (by norm_num))
    simpa using hca.tendsto
  simpa using hc.comp h2

/-- Logistic log-likelihood of a design `x` with binary labels `y` at the
coefficient vector `β`. -/
noncomputable def logLik {n d : ℕ} (x : Fin n → Fin d → ℝ) (y : Fin n → Bool)
    (β : Fin d → ℝ) : ℝ := ∑ i, logisticTerm (y i) (∑ j, β j * x i j)

/-- `w` separates the data: positives get a strictly positive score and
negatives a strictly negative one.  This is the quasi-separation configuration
that dense size-matched control designs fall into. -/
def Separates {n d : ℕ} (x : Fin n → Fin d → ℝ) (y : Fin n → Bool) (w : Fin d → ℝ) : Prop :=
  ∀ i, (y i = true → 0 < ∑ j, w j * x i j) ∧ (y i = false → (∑ j, w j * x i j) < 0)

lemma score_smul {n d : ℕ} (x : Fin n → Fin d → ℝ) (w : Fin d → ℝ) (t : ℝ) (i : Fin n) :
    (∑ j, (t * w j) * x i j) = t * ∑ j, w j * x i j := by
  rw [Finset.mul_sum]
  exact Finset.sum_congr rfl fun j _ => by ring

/-- The logistic log-likelihood is strictly negative whenever there is data. -/
lemma logLik_lt_zero {n d : ℕ} (hn : 0 < n) (x : Fin n → Fin d → ℝ) (y : Fin n → Bool)
    (β : Fin d → ℝ) : logLik x y β < 0 := by
  have hne : (Finset.univ : Finset (Fin n)).Nonempty := by
    simpa [Finset.univ_nonempty_iff, ← Fin.pos_iff_nonempty] using hn
  exact Finset.sum_neg (fun i _ => logisticTerm_neg _ _) hne

/-- Along a separating ray the log-likelihood increases strictly: the fit runs
off to infinity, which is what produces odds ratios clipped at the optimiser's
bound. -/
theorem logLik_ray_strictMono {n d : ℕ} (hn : 0 < n) {x : Fin n → Fin d → ℝ} {y : Fin n → Bool}
    {w : Fin d → ℝ} (hsep : Separates x y w) :
    StrictMono (fun t : ℝ => logLik x y (fun j => t * w j)) := by
  intro a b hab
  have hne : (Finset.univ : Finset (Fin n)).Nonempty := by
    simpa [Finset.univ_nonempty_iff, ← Fin.pos_iff_nonempty] using hn
  refine Finset.sum_lt_sum_of_nonempty hne ?_
  intro i _
  have hs := hsep i
  cases hy : y i
  · have hneg : (∑ j, w j * x i j) < 0 := hs.2 hy
    have hmono := logisticTerm_ray_strictMono (s := -(∑ j, w j * x i j)) (by linarith) hab
    simp only [logisticTerm, score_smul, Bool.false_eq_true, if_false]
    have hrw : ∀ t : ℝ, -(t * -(∑ j, w j * x i j)) = t * ∑ j, w j * x i j := fun t => by ring
    simp only [hrw] at hmono
    exact hmono
  · have hpos : 0 < (∑ j, w j * x i j) := hs.1 hy
    have hmono := logisticTerm_ray_strictMono (s := (∑ j, w j * x i j)) hpos hab
    simp only [logisticTerm, score_smul, if_true]
    exact hmono

lemma logLik_ray_tendsto {n d : ℕ} {x : Fin n → Fin d → ℝ} {y : Fin n → Bool} {w : Fin d → ℝ}
    (hsep : Separates x y w) :
    Filter.Tendsto (fun t : ℝ => logLik x y (fun j => t * w j)) Filter.atTop (nhds 0) := by
  have hterm : ∀ i : Fin n,
      Filter.Tendsto (fun t : ℝ => logisticTerm (y i) (∑ j, (t * w j) * x i j))
        Filter.atTop (nhds 0) := by
    intro i
    have hs := hsep i
    cases hy : y i
    · have hneg : (∑ j, w j * x i j) < 0 := hs.2 hy
      refine (logisticTerm_tendsto (s := -(∑ j, w j * x i j)) (by linarith)).congr ?_
      intro t
      simp only [logisticTerm, score_smul, Bool.false_eq_true, if_false]
      ring_nf
    · have hpos : 0 < (∑ j, w j * x i j) := hs.1 hy
      refine (logisticTerm_tendsto (s := (∑ j, w j * x i j)) hpos).congr ?_
      intro t
      simp only [logisticTerm, score_smul, if_true]
  have hsum := tendsto_finset_sum (Finset.univ : Finset (Fin n)) (fun i _ => hterm i)
  simpa [logLik] using hsum

/-- **Quasi-separation destroys the maximum-likelihood estimate.**  If some
direction separates the labelled scores, then no coefficient vector maximises the
logistic log-likelihood: for every `β` there is a point further out along the
separating ray with strictly larger likelihood.  The supremum `0` is never
attained, so the reported odds ratios of such a fit are determined by the
optimiser's clipping bound rather than by the data. -/
theorem logistic_no_mle {n d : ℕ} (hn : 0 < n) {x : Fin n → Fin d → ℝ} {y : Fin n → Bool}
    {w : Fin d → ℝ} (hsep : Separates x y w) (β : Fin d → ℝ) :
    ∃ t : ℝ, logLik x y β < logLik x y (fun j => t * w j) := by
  have hlim := logLik_ray_tendsto hsep
  have hβ : logLik x y β < 0 := logLik_lt_zero hn x y β
  exact (hlim.eventually (eventually_gt_nhds hβ)).exists

/-- Restated: the set of maximisers of the logistic log-likelihood is empty
under separation. -/
theorem logistic_no_maximizer {n d : ℕ} (hn : 0 < n) {x : Fin n → Fin d → ℝ} {y : Fin n → Bool}
    {w : Fin d → ℝ} (hsep : Separates x y w) :
    ¬ ∃ β : Fin d → ℝ, ∀ γ : Fin d → ℝ, logLik x y γ ≤ logLik x y β := by
  rintro ⟨β, hβ⟩
  obtain ⟨t, ht⟩ := logistic_no_mle hn hsep β
  exact absurd (hβ (fun j => t * w j)) (not_le.2 ht)

end PositionalRateLink