import Probability.PRNGLFSRDetection

/-!
# Tap uniqueness (Hankel nondegeneracy) and high linear complexity files

Two refinements of the LFSR analysis.

**1. Why seed recovery is well posed.**  Berlekamp–Massey returns *a* tap
vector; is it *the* tap vector?  `lfsr_taps_unique` gives the exact linear
algebra criterion: if the `L × L` Hankel matrix `H_{t,j} = y(t+j)` of the
observed window is nonsingular, then two tap vectors explaining the same stream
coincide.  The bridge is that the difference of two explanations lies in the
kernel of the Hankel matrix.

**2. How rare seed-compressible files are, over *all* orders at once.**
`card_lowComplexityWords_le` bounds the number of length-`n` files of linear
complexity `≤ M` by `q^{2M+1}` where `q = |K|`, by summing the per-order bound
`q^{2L}` geometrically.  Hence `exists_high_linear_complexity`: as soon as
`2M + 1 < n`, some file is generated by *no* LFSR of order `≤ M`.  Quantitatively,
the fraction of `n`-symbol files that any LFSR-based seed compressor can handle
at order `≤ M` is at most `q^{2M+1-n}`.
-/

namespace Catalog.Probability.SeedRec

variable {K : Type*} [CommRing K] {L : ℕ}

/-- The `L × L` Hankel matrix of the observed window: `H t j = y (t + j)`. -/
def hankel (y : ℕ → K) (L : ℕ) : Matrix (Fin L) (Fin L) K :=
  Matrix.of fun t j : Fin L => y ((t : ℕ) + (j : ℕ))

/-- **Tap uniqueness.** If the Hankel matrix of the observed window is
nonsingular, a stream determines the taps of any order-`L` LFSR explaining it:
seed recovery has a unique answer, not merely a consistent one. -/
theorem lfsr_taps_unique [IsDomain K] (y : ℕ → K) (c c' : Fin L → K)
    (hdet : (hankel y L).det ≠ 0)
    (h : SatisfiesLFSR c y) (h' : SatisfiesLFSR c' y) : c = c' := by
  have key : Matrix.mulVec (hankel y L) (c - c') = 0 := by
    funext t
    have ht : ∑ j : Fin L, y ((t : ℕ) + (j : ℕ)) * c j
        = ∑ j : Fin L, y ((t : ℕ) + (j : ℕ)) * c' j := by
      have h2 := (h (t : ℕ)).symm.trans (h' (t : ℕ))
      simpa [mul_comm] using h2
    simp only [Matrix.mulVec, hankel, Matrix.of_apply, dotProduct, Pi.sub_apply, Pi.zero_apply,
      mul_sub, Finset.sum_sub_distrib, ht, sub_self]
  exact sub_eq_zero.mp (Matrix.eq_zero_of_mulVec_eq_zero hdet key)

section Complexity

variable (K) [Fintype K] [DecidableEq K]

/-- The length-`n` files of **linear complexity at most `M`**: those produced by
an LFSR of some order `1 ≤ L ≤ M`. -/
def lowComplexityWords (M n : ℕ) : Finset (Fin n → K) :=
  (Finset.range M).biUnion fun m => lfsrWords K (m + 1) n

theorem mem_lowComplexityWords {M n : ℕ} {x : Fin n → K} :
    x ∈ lowComplexityWords K M n ↔ ∃ m < M, x ∈ lfsrWords K (m + 1) n := by
  simp [lowComplexityWords]

/-- Geometric summation of the per-order bounds. -/
theorem sum_pow_two_mul_lt (q M : ℕ) (hq : 2 ≤ q) :
    ∑ m ∈ Finset.range M, q ^ (2 * (m + 1)) < q ^ (2 * M + 1) := by
  induction M with
  | zero =>
      simp only [Finset.range_zero, Finset.sum_empty]
      exact pow_pos (by omega) _
  | succ M ih =>
      rw [Finset.sum_range_succ]
      have h1 : q ^ (2 * M + 1) + q ^ (2 * (M + 1)) ≤ 2 * q ^ (2 * (M + 1)) := by
        have : q ^ (2 * M + 1) ≤ q ^ (2 * (M + 1)) :=
          Nat.pow_le_pow_right (by omega) (by omega)
        omega
      have h2 : 2 * q ^ (2 * (M + 1)) ≤ q ^ (2 * (M + 1) + 1) := by
        rw [pow_succ, mul_comm (q ^ (2 * (M + 1))) q]
        exact Nat.mul_le_mul_right _ hq
      have h3 : (2 : ℕ) * (M + 1) + 1 = 2 * (M + 1) + 1 := rfl
      omega

/-- **Rarity of low linear complexity, uniformly in the order.** At most
`|K|^{2M+1}` files of length `n` have linear complexity `≤ M`. -/
theorem card_lowComplexityWords_le (M n : ℕ) (hK : 2 ≤ Fintype.card K) :
    (lowComplexityWords K M n).card < Fintype.card K ^ (2 * M + 1) := by
  refine lt_of_le_of_lt (Finset.card_biUnion_le) ?_
  refine lt_of_le_of_lt (Finset.sum_le_sum ?_) (sum_pow_two_mul_lt (Fintype.card K) M hK)
  intro m _
  exact card_lfsrWords_le K (m + 1) n

/-- **High linear complexity exists.** Once the file is longer than `2M + 1`
symbols, some file of that length is produced by no LFSR of order `≤ M`
whatsoever: LFSR-based seed compression is not universal at any bounded order. -/
theorem exists_high_linear_complexity (M n : ℕ) (hK : 2 ≤ Fintype.card K)
    (hn : 2 * M + 1 < n) :
    ∃ x : Fin n → K, x ∉ lowComplexityWords K M n := by
  have hlt : Fintype.card K ^ (2 * M + 1) < Fintype.card K ^ n :=
    Nat.pow_lt_pow_right (by omega) hn
  by_contra hc
  push_neg at hc
  have hsub : (Finset.univ : Finset (Fin n → K)) ⊆ lowComplexityWords K M n := fun x _ => hc x
  have hcard := Finset.card_le_card hsub
  rw [Finset.card_univ, Fintype.card_fun, Fintype.card_fin] at hcard
  have := card_lowComplexityWords_le K M n hK
  omega

/-- Density form: an LFSR seed compressor working at orders `≤ M` succeeds on at
most a `q^{2M+1-n}` fraction of the length-`n` files, an exponentially small
false-positive rate for the detector on uniformly random data. -/
theorem lowComplexityWords_density_le (M n : ℕ) (hK : 2 ≤ Fintype.card K) :
    ((lowComplexityWords K M n).card : ℚ) / (Fintype.card K : ℚ) ^ n
      ≤ (Fintype.card K : ℚ) ^ (2 * M + 1) / (Fintype.card K : ℚ) ^ n := by
  have hcard : (0 : ℚ) < (Fintype.card K : ℚ) := by
    have : (0 : ℕ) < Fintype.card K := by omega
    exact_mod_cast this
  have hpos : (0 : ℚ) < (Fintype.card K : ℚ) ^ n := by positivity
  gcongr
  exact_mod_cast (card_lowComplexityWords_le K M n hK).le

end Complexity

end Catalog.Probability.SeedRec