import Mathlib

/-!
# Dreamtime Algebra: Aboriginal Kinship Systems as Group Theory

This file builds a bridge between **social anthropology** (the section and
subsection kinship systems of Australian Aboriginal societies) and **finite
group theory**.

A *section system* (as in the classical Kariera example) partitions a society
into four named classes ("sections").  Three fundamental kinship relations act
on the sections:

* `mother`  — the section of a person's child, given the mother's section;
* `spouse`  — the section a person marries into;
* `father`  — the section of a person's child, given the father's section.

Each relation is a **permutation of the four sections**, and in the four‑section
system each is an *involution*.  The group generated by these permutations turns
out to be the **Klein four‑group** `ℤ/2 × ℤ/2`.  The eight‑*subsection* system
(as in the Warlpiri) is the analogous refinement whose transformation group is
`(ℤ/2)³`.

## Main results

* `kinGroupIso` : the four‑section kinship transformation group (a subgroup of
  the symmetric group on the 4 sections) is isomorphic to `ℤ/2 × ℤ/2`.  This is
  the **cross‑domain connector**: an anthropological classification system is
  literally a permutation representation of the Klein four‑group (Cayley's
  theorem in action).
* `section4_not_addCyclic` : the section group is genuinely `ℤ/2 × ℤ/2` and **not**
  the cyclic group `ℤ/4`; it has exponent `2`.
* `marriage_iff_sameMatriMoiety` : the marriage rule is exactly a **coset
  restriction** — two distinct sections may intermarry iff they lie in the same
  coset of the matrimoiety subgroup.
* `kinGroupIso8` : the eight‑subsection transformation group is isomorphic to
  `(ℤ/2)³`.
* `subsectionQuotIso` / `kerIso` : the subsection system is a `ℤ/2`‑extension of
  the section system — the forgetful map `Subsection8 → Section4` is surjective
  with kernel `ℤ/2`, exhibiting the eight subsections as a double cover of the
  four sections.

Everything is proved from first principles over `ℤ/2 × ℤ/2` and `(ℤ/2)³`.
-/

open Equiv

namespace DreamtimeAlgebra

/-! ## The four sections and the eight subsections -/

/-- The four **sections** of a Kariera‑type kinship system, modelled as the
underlying set of the Klein four‑group `ℤ/2 × ℤ/2`. -/
abbrev Section4 := ZMod 2 × ZMod 2

/-- The eight **subsections** of a Warlpiri‑type kinship system, modelled as
`(ℤ/2)³`. -/
abbrev Subsection8 := ZMod 2 × ZMod 2 × ZMod 2

theorem card_section4 : Fintype.card Section4 = 4 := by decide

theorem card_subsection8 : Fintype.card Subsection8 = 8 := by decide

/-- Every element of `ℤ/2` is its own additive inverse. -/
theorem zmod2_add_self (a : ZMod 2) : a + a = 0 := by revert a; decide

/-- Every section is its own additive inverse: the section group has exponent `2`. -/
theorem section4_add_self (g : Section4) : g + g = 0 := by revert g; decide

/-- Every subsection is its own additive inverse: exponent `2`. -/
theorem subsection8_add_self (g : Subsection8) : g + g = 0 := by revert g; decide

/-! ## Kinship steps as permutations of the sections

Each "kinship step" is realised as translation by a fixed section.  Because the
group has exponent `2`, every such translation is an involution. -/

/-- Translation of the section‑set by a fixed section `v`; this is the
permutation realising a kinship step. -/
def transl (v : Section4) : Perm Section4 :=
  ⟨fun x => x + v, fun x => x + v,
    fun x => by
      have : v + v = 0 := Prod.ext (zmod2_add_self v.1) (zmod2_add_self v.2)
      simp [add_assoc, this],
    fun x => by
      have : v + v = 0 := Prod.ext (zmod2_add_self v.1) (zmod2_add_self v.2)
      simp [add_assoc, this]⟩

@[simp] theorem transl_apply (v x : Section4) : transl v x = x + v := rfl

theorem transl_zero : transl 0 = 1 := by ext x <;> simp

/-- The kinship steps compose additively: performing step `v` then step `w`
is the step `v + w`. -/
theorem transl_add (v w : Section4) : transl (v + w) = transl v * transl w := by
  ext x <;> simp only [transl_apply, Perm.mul_apply, transl_apply] <;> abel_nf

/-- Every kinship translation is an involution (fundamental to a 4‑section
system: applying the same kinship step twice returns you to the start). -/
theorem transl_involutive (v : Section4) : transl v * transl v = 1 := by
  rw [← transl_add, section4_add_self, transl_zero]

/-! ### The three named kinship relations -/

/-- The **mother→child** section map. -/
def mother : Perm Section4 := transl (0, 1)

/-- The **marriage** (spouse) section map. -/
def spouse : Perm Section4 := transl (1, 0)

/-- The **father→child** section map. -/
def father : Perm Section4 := transl (1, 1)

theorem mother_involution : mother * mother = 1 := transl_involutive _
theorem spouse_involution : spouse * spouse = 1 := transl_involutive _
theorem father_involution : father * father = 1 := transl_involutive _

/-- The kinship relations commute (the system is abelian). -/
theorem mother_spouse_comm : mother * spouse = spouse * mother := by
  rw [mother, spouse, ← transl_add, ← transl_add, add_comm]

/-- **Consistency of the descent rules**: the father‑map is the composite of the
marriage‑map and the mother‑map.  A father's child‑section equals the
mother's child‑section, since parents are spouses. -/
theorem father_eq_spouse_mother : father = spouse * mother := by
  rw [father, spouse, mother, ← transl_add]; congr 1

/-! ## The connector: the kinship transformation group is the Klein four‑group -/

/-- The **kinship transformation homomorphism** — the Cayley (regular)
representation of the section group inside the symmetric group on the sections. -/
def kinHom : Multiplicative Section4 →* Perm Section4 where
  toFun v := transl (Multiplicative.toAdd v)
  map_one' := transl_zero
  map_mul' _ _ := transl_add _ _

theorem kinHom_injective : Function.Injective kinHom := by
  intro a b h
  have := congrArg (fun p : Perm Section4 => p 0) h
  simpa only [kinHom, MonoidHom.coe_mk, OneHom.coe_mk, transl_apply, zero_add] using this

/-- **CROSS‑DOMAIN CONNECTOR (4 sections).**
The kinship transformation group — the subgroup of the symmetric group on the
four sections generated by the mother/father/spouse permutations — is isomorphic
to the Klein four‑group `ℤ/2 × ℤ/2`.  A purely anthropological classification is
thus a concrete permutation representation of a finite abelian group. -/
noncomputable def kinGroupIso : Multiplicative Section4 ≃* kinHom.range :=
  MonoidHom.ofInjective kinHom_injective

/-- The kinship transformation group has exactly four elements. -/
theorem kinGroup_card : Nat.card kinHom.range = 4 := by
  rw [← Nat.card_congr kinGroupIso.toEquiv]
  simp [Nat.card_eq_fintype_card]

/-- The section group is **not** cyclic: it is the Klein four‑group `ℤ/2 × ℤ/2`,
not `ℤ/4`.  Every non‑identity element has order `2`. -/
theorem section4_not_addCyclic : ¬ IsAddCyclic Section4 := by
  intro _
  obtain ⟨g, hg⟩ := IsAddCyclic.exists_ofOrder_eq_natCard (α := Section4)
  have hcard : Nat.card Section4 = 4 := by simp [Nat.card_eq_fintype_card]
  rw [hcard] at hg
  have hdvd : addOrderOf g ∣ 2 :=
    addOrderOf_dvd_of_nsmul_eq_zero (by rw [two_nsmul]; exact section4_add_self g)
  rw [hg] at hdvd
  omega

/-- The section group acts **simply transitively** on itself: kinship relations
determine every section uniquely from any starting section. -/
theorem section4_simplyTransitive (x y : Section4) : ∃! v : Section4, x + v = y := by
  refine ⟨y - x, by abel_nf, ?_⟩
  intro w hw; rw [← hw]; abel_nf

/-! ## Marriage rules as coset restrictions -/

/-- The **matrimoiety** subgroup: the kernel of the second‑coordinate map.  Its
two cosets are the two matrimoieties, and marriage is confined to a single
coset. -/
def matriMoiety : AddSubgroup Section4 := (AddMonoidHom.snd (ZMod 2) (ZMod 2)).ker

/-- **Marriage as a coset restriction.**  A person of section `x` marries a
person of section `y` (i.e. `y = x + (1,0)`) **iff** `x` and `y` are distinct and
lie in the same coset of the matrimoiety subgroup.  Marriage is exactly a
coset‑restricted pairing. -/
theorem marriage_iff_sameMatriMoiety (x y : Section4) :
    y = x + (1, 0) ↔ (y - x ∈ matriMoiety ∧ y ≠ x) := by
  rw [matriMoiety, AddMonoidHom.mem_ker]
  revert x y; decide

theorem snd_surjective : Function.Surjective (AddMonoidHom.snd (ZMod 2) (ZMod 2)) :=
  fun b => ⟨(0, b), rfl⟩

/-- There are exactly **two** matrimoieties (cosets of `matriMoiety`). -/
noncomputable def matriQuotIso : (Section4 ⧸ matriMoiety) ≃+ ZMod 2 :=
  QuotientAddGroup.quotientKerEquivOfSurjective _ snd_surjective

theorem matriMoiety_index : Nat.card (Section4 ⧸ matriMoiety) = 2 := by
  rw [Nat.card_congr matriQuotIso.toEquiv]
  simp [Nat.card_eq_fintype_card]

/-! ## The eight‑subsection system as a `ℤ/2`‑extension -/

/-- Translation permutation for the subsection system. -/
def transl8 (v : Subsection8) : Perm Subsection8 :=
  ⟨fun x => x + v, fun x => x + v,
    fun x => by
      have : v + v = 0 := subsection8_add_self v
      simp [add_assoc, this],
    fun x => by
      have : v + v = 0 := subsection8_add_self v
      simp [add_assoc, this]⟩

@[simp] theorem transl8_apply (v x : Subsection8) : transl8 v x = x + v := rfl

theorem transl8_zero : transl8 0 = 1 := by ext x <;> simp

theorem transl8_add (v w : Subsection8) : transl8 (v + w) = transl8 v * transl8 w := by
  ext x <;> simp only [transl8_apply, Perm.mul_apply, transl8_apply] <;> abel_nf

/-- The subsection transformation homomorphism (Cayley representation). -/
def kinHom8 : Multiplicative Subsection8 →* Perm Subsection8 where
  toFun v := transl8 (Multiplicative.toAdd v)
  map_one' := transl8_zero
  map_mul' _ _ := transl8_add _ _

theorem kinHom8_injective : Function.Injective kinHom8 := by
  intro a b h
  have := congrArg (fun p : Perm Subsection8 => p 0) h
  simpa only [kinHom8, MonoidHom.coe_mk, OneHom.coe_mk, transl8_apply, zero_add] using this

/-- **CROSS‑DOMAIN CONNECTOR (8 subsections).**  The subsection transformation
group is isomorphic to `(ℤ/2)³`. -/
noncomputable def kinGroupIso8 : Multiplicative Subsection8 ≃* kinHom8.range :=
  MonoidHom.ofInjective kinHom8_injective

theorem kinGroup8_card : Nat.card kinHom8.range = 8 := by
  rw [← Nat.card_congr kinGroupIso8.toEquiv]
  simp [Nat.card_eq_fintype_card]

theorem subsection8_not_addCyclic : ¬ IsAddCyclic Subsection8 := by
  intro _
  obtain ⟨g, hg⟩ := IsAddCyclic.exists_ofOrder_eq_natCard (α := Subsection8)
  have hcard : Nat.card Subsection8 = 8 := by simp [Nat.card_eq_fintype_card]
  rw [hcard] at hg
  have hdvd : addOrderOf g ∣ 2 :=
    addOrderOf_dvd_of_nsmul_eq_zero (by rw [two_nsmul]; exact subsection8_add_self g)
  rw [hg] at hdvd
  omega

theorem subsection8_simplyTransitive (x y : Subsection8) : ∃! v : Subsection8, x + v = y := by
  refine ⟨y - x, by abel_nf, ?_⟩
  intro w hw; rw [← hw]; abel_nf

/-- The **forgetful map** collapsing a subsection to its underlying section (a
subsection refines a section). -/
def forget : Subsection8 →+ Section4 :=
  AddMonoidHom.mk' (fun p => (p.1, p.2.1)) (by intro a b; rfl)

theorem forget_surjective : Function.Surjective forget :=
  fun ⟨a, b⟩ => ⟨(a, b, 0), rfl⟩

/-- **The subsection system is a `ℤ/2`‑extension of the section system.**  The
quotient of the eight subsections by the forgetful kernel recovers exactly the
four sections. -/
noncomputable def subsectionQuotIso : (Subsection8 ⧸ forget.ker) ≃+ Section4 :=
  QuotientAddGroup.quotientKerEquivOfSurjective _ forget_surjective

/-- The kernel of the forgetful map is `ℤ/2`: passing from four sections to eight
subsections is a **double cover** (a `ℤ/2`‑extension). -/
def kerIso : forget.ker ≃+ ZMod 2 where
  toFun p := p.1.2.2
  invFun c := ⟨(0, 0, c), by simp [forget, AddMonoidHom.mem_ker]⟩
  left_inv := by
    rintro ⟨⟨a, b, c⟩, hp⟩
    rw [AddMonoidHom.mem_ker] at hp
    simp only [forget, AddMonoidHom.mk'_apply] at hp
    have ha : a = 0 := (Prod.mk.injEq .. ▸ hp).1
    have hb : b = 0 := (Prod.mk.injEq .. ▸ hp).2
    subst ha; subst hb; rfl
  right_inv _ := rfl
  map_add' _ _ := rfl

theorem forget_ker_card : Nat.card forget.ker = 2 := by
  rw [Nat.card_congr kerIso.toEquiv]
  simp [Nat.card_eq_fintype_card]

end DreamtimeAlgebra