import Mathlib

/-! # EML interpolation: analysis, topology, and network complexity

This file gives a precise bridge from exp--log expressions to Stone--Weierstrass
approximation.  It also records explicit finite-width realizations of the square
function.  The quantitative Jackson conjecture is deliberately separated from the
proved density result: Stone--Weierstrass alone does not supply a width rate.
-/

noncomputable section

open Real Set

namespace EMLInterpolationTheory

/-- A one-neuron exp--log feature with affine input. -/
def logFeature (a b c t : ℝ) : ℝ := Real.exp a * Real.log (b * t + c)

/-- The proposed exp--log feature really separates any two real points, with a
positive slope and with both logarithm arguments in their natural positive domain. -/
theorem logFeature_separates {x y : ℝ} (hxy : x ≠ y) :
    ∃ a b c : ℝ,
      0 < b ∧ 0 < b * x + c ∧ 0 < b * y + c ∧
        logFeature a b c x ≠ logFeature a b c y := by
  use 0, 1, |x| + |y| + 1
  refine ⟨by norm_num, ?_, ?_, ?_⟩
  · cases abs_cases x <;> cases abs_cases y <;> linarith
  · cases abs_cases x <;> cases abs_cases y <;> linarith
  · simp [logFeature]
    show ¬(log (x + (|x| + |y| + 1)) = log (y + (|x| + |y| + 1)))
    have posx : x + (|x| + |y| + 1) > 0 := by cases abs_cases x <;> cases abs_cases y <;> linarith
    have posy : y + (|x| + |y| + 1) > 0 := by cases abs_cases x <;> cases abs_cases y <;> linarith
    exact fun h => hxy (by linarith [Real.log_injOn_pos (x₁ := x + (|x| + |y| + 1)) (x₂ := y + (|x| + |y| + 1)) posx posy h])

/-- Coordinatewise version: one exp--log neuron separates two vectors.  This is the
finite-dimensional geometric input to Stone--Weierstrass. -/
theorem logFeature_separates_vectors {n : ℕ} {x y : Fin n → ℝ} (hxy : x ≠ y) :
    ∃ i : Fin n, ∃ a b c : ℝ,
      0 < b ∧ 0 < b * x i + c ∧ 0 < b * y i + c ∧
        logFeature a b c (x i) ≠ logFeature a b c (y i) := by
  have ⟨i, hi⟩ := Function.ne_iff.mp hxy
  obtain ⟨a, b, c, hb, hx, hy, hne⟩ := logFeature_separates hi
  exact ⟨i, a, b, c, hb, hx, hy, hne⟩

section StoneWeierstrass

variable {n : ℕ} (K : Set (Fin n → ℝ)) [CompactSpace K]

/-- Exponentiating a coordinate gives a continuous EML feature on a compact set. -/
def coordinateExp (i : Fin n) : C(K, ℝ) where
  toFun x := Real.exp (x.1 i)
  continuous_toFun :=
    Real.continuous_exp.comp ((continuous_apply i).comp continuous_subtype_val)

omit [CompactSpace K] in
/-- The algebra generated by coordinate exponential features separates points. -/
theorem coordinateExp_adjoin_separates :
    (Algebra.adjoin ℝ (Set.range (coordinateExp K))).SeparatesPoints := by
  intro x y hxy
  have hne : x.1 ≠ y.1 := Subtype.coe_ne_coe.mpr hxy
  obtain ⟨i, hi⟩ : ∃ i : Fin n, x.1 i ≠ y.1 i := Function.ne_iff.mp hne
  refine ⟨coordinateExp K i, ?_, ?_⟩
  · exact Set.mem_image_of_mem _ (Algebra.subset_adjoin (Set.mem_range_self i))
  · intro heq
    exact hi (Real.exp_injective heq)

/-- **EML--Stone--Weierstrass connector.**  Finite algebraic combinations of
coordinate exponentials are dense in all real continuous functions on every compact
subset of finite-dimensional Euclidean space. -/
theorem coordinateExp_adjoin_dense :
    (Algebra.adjoin ℝ (Set.range (coordinateExp K))).topologicalClosure = ⊤ := by
  exact ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints _
    (coordinateExp_adjoin_separates K)

end StoneWeierstrass

/-! ## A concrete expression language and explicit square networks -/

/-- Finite EML expression trees. -/
inductive Expr where
  | const (c : ℝ)
  | var
  | exp (e : Expr)
  | log (e : Expr)
  | add (e₁ e₂ : Expr)
  | mul (e₁ e₂ : Expr)
  deriving Inhabited

namespace Expr

/-- Evaluation of an EML expression. -/
noncomputable def eval : Expr → ℝ → ℝ
  | .const c, _ => c
  | .var, x => x
  | .exp e, x => Real.exp (eval e x)
  | .log e, x => Real.log (eval e x)
  | .add e₁ e₂, x => eval e₁ x + eval e₂ x
  | .mul e₁ e₂, x => eval e₁ x * eval e₂ x

/-- Width is the number of leaves of the expression tree. -/
def width : Expr → ℕ
  | .const _ => 1
  | .var => 1
  | .exp e => width e
  | .log e => width e
  | .add e₁ e₂ => width e₁ + width e₂
  | .mul e₁ e₂ => width e₁ + width e₂

/-- Add `m` harmless zero leaves to an expression. -/
def padZero : ℕ → Expr → Expr
  | 0, e => e
  | m + 1, e => .add (.const 0) (padZero m e)

@[simp] theorem eval_padZero (m : ℕ) (e : Expr) (x : ℝ) :
    (padZero m e).eval x = e.eval x := by
  induction m with
  | zero => rfl
  | succ m ih =>
    show (padZero (m + 1) e).eval x = e.eval x
    simp only [padZero, Expr.eval]
    rw [ih]
    simp

@[simp] theorem width_padZero (m : ℕ) (e : Expr) :
    (padZero m e).width = e.width + m := by
  induction m with
  | zero => simp [padZero]
  | succ m ih => rw [padZero, width, width, ih]; ring

/-- The direct multiplication realization of the square. -/
def square : Expr := .mul .var .var

/-- For every requested width `n ≥ 2`, there is an EML expression of exactly that
width which computes `x²` on `[0,1]` (indeed, on all of `ℝ`), so its uniform error is
zero. -/
theorem square_exact_at_width {n : ℕ} (hn : 2 ≤ n) :
    ∃ e : Expr, e.width = n ∧
      ∀ x ∈ Set.Icc (0 : ℝ) 1, |e.eval x - x ^ 2| = 0 := by
  refine ⟨padZero (n - 2) square, ?_, ?_⟩
  · simp [square, width, Nat.add_sub_of_le hn]
  · intro x _
    simp [square, eval, pow_two]

/-- A genuinely exp--log realization, shifted so that `log` is only evaluated at
positive arguments on `[0,1]`. -/
def shiftedExpLogSquare (δ : ℝ) : Expr :=
  .exp (.mul (.const 2) (.log (.add .var (.const δ))))

/-- Explicit error bound for the shifted exp--log square network.  Its output is
`(x+δ)²`, hence the error on `[0,1]` is at most `2δ+δ²`. -/
theorem shiftedExpLogSquare_error {δ : ℝ} (hδ : 0 < δ) :
    ∀ x ∈ Set.Icc (0 : ℝ) 1,
      |(shiftedExpLogSquare δ).eval x - x ^ 2| ≤ 2 * δ + δ ^ 2 := by
  intro x hx
  -- unfold the definition and simplify
  simp [shiftedExpLogSquare, Expr.eval]
  -- now we need: |exp(2 * log(x + δ)) - x²| ≤ 2δ + δ²
  -- since x + δ > 0, exp(2 * log(x + δ)) = (x + δ)²
  have hxδ : x + δ > 0 := by linarith [hx.1]
  have hexp : Real.exp (2 * Real.log (x + δ)) = (x + δ) ^ 2 := by
    rw [two_mul, Real.exp_add, Real.exp_log hxδ]
    ring
  rw [hexp]
  -- now: |(x + δ)² - x²| ≤ 2δ + δ²
  have h1 : (x + δ) ^ 2 - x ^ 2 = 2 * x * δ + δ ^ 2 := by ring
  rw [h1]
  rw [abs_of_nonneg]
  · -- 2 * x * δ + δ² ≤ 2δ + δ² iff x ≤ 1 (since δ > 0)
    have hx1 : x ≤ 1 := hx.2
    nlinarith
  · -- 2 * x * δ + δ² ≥ 0 since x ≥ 0, δ > 0
    nlinarith [hx.1]

/-- Choosing `δ ≤ ε/3` (and `δ ≤ 1`) turns the explicit estimate into an
`ε`-approximation. -/
theorem shiftedExpLogSquare_epsilon {ε δ : ℝ}
    (hδ : 0 < δ) (hδone : δ ≤ 1) (hδε : 3 * δ ≤ ε) :
    ∀ x ∈ Set.Icc (0 : ℝ) 1,
      |(shiftedExpLogSquare δ).eval x - x ^ 2| ≤ ε := by
  intro x hx
  calc
    |(shiftedExpLogSquare δ).eval x - x ^ 2| ≤ 2 * δ + δ ^ 2 :=
      shiftedExpLogSquare_error hδ x hx
    _ ≤ 3 * δ := by nlinarith [hδ.le]
    _ ≤ ε := hδε

end Expr

end EMLInterpolationTheory