import Mathlib

/-!
# Modular Scattering Duality via Idempotent Closure-Scattering Systems

This module establishes a finite duality and realization theory for **closure-scattering systems**,
creating a certified bridge between closure dynamics, finite idempotent semimodule duality,
and scattering/resonance reconstruction from boundary data.

## Mathematical Overview

A closure-scattering system consists of:
- A state space `X` with a closure operator `cl : Set X → Set X`
- A transfer (evolution) map `T : X → X` propagating states forward in time
- Boundary observation functionals `boundary : X → C → R` measuring states through channels

The **resonance congruence** identifies states that are observationally indistinguishable:
two states are equivalent when all sequences of boundary observations under iterated transfer
coincide. This is the idempotent analogue of Nerode/Myhill equivalence in automata theory.

The **spectral boundary semimodule** is the shift-closed set of response profiles,
representing the "dual" or "spectral" side of a closure-scattering system.

## Main Results

- `resonanceEquiv_is_equivalence`: resonance equivalence is an equivalence relation
- `resonanceEquiv_coarsest`: it is the coarsest observation-compatible equivalence (minimality)
- `transfer_preserves_resonanceEquiv`: transfer respects resonance equivalence
- `separated_systems_isomorphic_of_same_profiles`: separated systems with identical
  response profile ranges are isomorphic (**main duality/uniqueness theorem**)
- `minimalRealization_separated`: the minimal realization is separated
- `minimal_resonance_realization_unique`: any separated realization of the same boundary
  data is isomorphic to the minimal realization (**certified reconstruction**)

## Physical Interpretation

- **Closure defect = resonance**: failure of transfer to preserve closure ↔ resonant modes
- **Boundary response = scattering data**: channel functionals ↔ scattering amplitudes
- **Minimal reduced quotient = minimal resonance realization**
- **Separation by observables = distinguishability of scattering channels**

## Cross-Domain Connections

This framework provides an idempotent analogue of:
- Hankel minimal realization in systems theory
- Nerode/Myhill equivalence in automata theory
- S-matrix reconstruction in scattering theory
- Tropical spectral duality in idempotent geometry
-/

namespace ModularScatteringDuality

/-! ## Core Definitions -/

/-- A closure-scattering system: a closure operator on subsets of a state space,
together with a transfer (evolution) map and boundary observation functionals.

This models a discrete scattering system where `cl` captures reachable/generated states,
`transfer` propagates states forward in time, and `boundary` observes states through
output channels. The interaction between closure and transfer gives rise to resonance. -/
structure ClosureScatteringSystem (R : Type*) (X : Type*) (C : Type*) where
  /-- Closure operator on subsets of the state space -/
  cl : Set X → Set X
  /-- Closure is extensive: every set is contained in its closure -/
  cl_extensive : ∀ A, A ⊆ cl A
  /-- Closure is monotone: larger sets have larger closures -/
  cl_monotone : Monotone cl
  /-- Closure is idempotent: closing a closed set has no effect -/
  cl_idem : ∀ A, cl (cl A) = cl A
  /-- Transfer map: one-step evolution of states -/
  transfer : X → X
  /-- Boundary observation: measures a state through a channel -/
  boundary : X → C → R

variable {R : Type*} {X : Type*} {C : Type*}

/-- The response profile of a state records boundary observations of all iterates
under transfer. This is the complete observable behavior — the idempotent
analogue of an impulse response in systems theory. -/
def ClosureScatteringSystem.responseProfile (S : ClosureScatteringSystem R X C)
    (x : X) : ℕ → C → R :=
  fun n c => S.boundary (S.transfer^[n] x) c

/-- Resonance equivalence: two states are equivalent when they produce identical
response profiles, i.e., they are indistinguishable by any sequence of boundary
observations under transfer evolution. This is the idempotent Nerode equivalence. -/
def ClosureScatteringSystem.resonanceEquiv (S : ClosureScatteringSystem R X C)
    (x y : X) : Prop :=
  S.responseProfile x = S.responseProfile y

/-- A closure-scattering system is **separated** when distinct states have distinct
response profiles. This is the "reduced" or "fully observable" condition: every
state is uniquely determined by its boundary behavior. -/
def ClosureScatteringSystem.Separated (S : ClosureScatteringSystem R X C) : Prop :=
  Function.Injective S.responseProfile

/-- The closure defect of a set measures how much `transfer` fails to commute
with `cl`: it consists of states in `T(cl(A))` that lie outside `cl(T(A))`.
These are the "resonant" states — generated by closure then transferred,
but not reachable by transferring then closing. -/
def ClosureScatteringSystem.closureDefect (S : ClosureScatteringSystem R X C)
    (A : Set X) : Set X :=
  S.transfer '' (S.cl A) \ S.cl (S.transfer '' A)

/-- Transfer is closure-compatible when `T(cl(A)) ⊆ cl(T(A))` for all `A`.
When this holds, there are no resonance defects — transfer and closure commute. -/
def ClosureScatteringSystem.TransferClosureCompatible
    (S : ClosureScatteringSystem R X C) : Prop :=
  ∀ A, S.transfer '' (S.cl A) ⊆ S.cl (S.transfer '' A)

/-- A spectral boundary semimodule is a shift-closed set of response profiles.
This represents the "dual" or "spectral" side of a closure-scattering system:
the observable boundary data organized into an algebraic structure.

The shift-closure property captures the fact that if a response profile is observable,
then so is its time-shifted version (one step of transfer evolution). -/
structure SpectralBoundarySemimodule (R : Type*) (C : Type*) where
  /-- The set of response profiles -/
  profiles : Set (ℕ → C → R)
  /-- Profiles are closed under the time-shift operation -/
  shift_closed : ∀ f ∈ profiles, (fun n c => f (n + 1) c) ∈ profiles

/-- A morphism between closure-scattering systems preserves transfer dynamics
and boundary observations. -/
structure CSSMorphism {R : Type*} {X₁ X₂ : Type*} {C : Type*}
    (S₁ : ClosureScatteringSystem R X₁ C)
    (S₂ : ClosureScatteringSystem R X₂ C) where
  /-- The underlying map on state spaces -/
  toFun : X₁ → X₂
  /-- The map commutes with transfer -/
  transfer_comm : ∀ x, toFun (S₁.transfer x) = S₂.transfer (toFun x)
  /-- The map preserves boundary observations -/
  boundary_comm : ∀ x c, S₁.boundary x c = S₂.boundary (toFun x) c

/-- An isomorphism of closure-scattering systems: a bijective morphism.
This is the correct notion of equivalence for scattering systems — it preserves
all dynamical and observational structure. -/
structure CSSIsomorphism {R : Type*} {X₁ X₂ : Type*} {C : Type*}
    (S₁ : ClosureScatteringSystem R X₁ C)
    (S₂ : ClosureScatteringSystem R X₂ C) extends CSSMorphism S₁ S₂ where
  /-- The underlying map is bijective -/
  toFun_bijective : Function.Bijective toFun

/-! ## Resonance Congruence Properties -/

section ResonanceCongruence

variable (S : ClosureScatteringSystem R X C)

/-- Resonance equivalence is an equivalence relation.
This is immediate since it is defined as equality of response profiles. -/
theorem resonanceEquiv_is_equivalence : Equivalence S.resonanceEquiv :=
  ⟨fun _ => rfl, fun h => h.symm, fun h₁ h₂ => h₁.trans h₂⟩

/-- The resonance setoid on the state space, packaging `resonanceEquiv` as a `Setoid`. -/
def ClosureScatteringSystem.resonanceSetoid : Setoid X :=
  ⟨S.resonanceEquiv, resonanceEquiv_is_equivalence S⟩

/-
The response profile of `T(x)` is the tail-shift of the response profile of `x`.
This identity links transfer dynamics to the shift operation on spectral boundary
semimodules: applying transfer corresponds to dropping the first observation.
-/
theorem responseProfile_transfer (x : X) :
    S.responseProfile (S.transfer x) = fun n c => S.responseProfile x (n + 1) c := by
  exact List.map_inj.mp rfl

/-
Transfer preserves resonance equivalence: if two states have identical response
profiles, so do their images under transfer.
-/
theorem transfer_preserves_resonanceEquiv {x y : X}
    (h : S.resonanceEquiv x y) :
    S.resonanceEquiv (S.transfer x) (S.transfer y) := by
  -- Since the response profiles of x and y are equal, their tails are also equal.
  have h_tail : ∀ n c, S.responseProfile (S.transfer x) n c = S.responseProfile (S.transfer y) n c := by
    exact fun n c => congr_fun ( congr_fun h ( n + 1 ) ) c;
  exact funext fun n => funext fun c => h_tail n c

/-
**Minimality of resonance congruence.**
Resonance equivalence is the coarsest equivalence relation compatible with both
boundary observations and transfer dynamics. If `≈` is any equivalence such that
equivalent states have equal boundary values and transfer preserves the equivalence,
then `x ≈ y` implies `resonanceEquiv x y`.

This means resonance equivalence makes the maximum identifications while preserving
observable behavior — it yields the minimal realization.
-/
theorem resonanceEquiv_coarsest
    (equiv : X → X → Prop)
    (_ : Equivalence equiv)
    (h_boundary : ∀ x y, equiv x y → ∀ c, S.boundary x c = S.boundary y c)
    (h_transfer : ∀ x y, equiv x y → equiv (S.transfer x) (S.transfer y))
    {x y : X} (hxy : equiv x y) :
    S.resonanceEquiv x y := by
  have h_ind : ∀ n, equiv (S.transfer^[n] x) (S.transfer^[n] y) := by
    exact fun n => Nat.recOn n hxy fun n ih => by simpa only [Function.iterate_succ_apply'] using h_transfer _ _ ih
  exact funext fun n => funext fun c => h_boundary _ _ (h_ind n) c

/-
When transfer is closure-compatible, the closure defect is empty.
-/
theorem closureDefect_empty_of_compatible
    (hcompat : S.TransferClosureCompatible) (A : Set X) :
    S.closureDefect A = ∅ := by
  exact Set.diff_eq_empty.mpr ( hcompat A )

end ResonanceCongruence

/-! ## Morphism Properties -/

section MorphismProperties

variable {R : Type*} {X₁ X₂ : Type*} {C : Type*}
variable {S₁ : ClosureScatteringSystem R X₁ C}
variable {S₂ : ClosureScatteringSystem R X₂ C}

/-
A CSS morphism commutes with iterated transfer: `φ(T₁ⁿ(x)) = T₂ⁿ(φ(x))`.
-/
theorem morphism_iterate_transfer_comm (φ : CSSMorphism S₁ S₂)
    (x : X₁) (n : ℕ) :
    φ.toFun (S₁.transfer^[n] x) = S₂.transfer^[n] (φ.toFun x) := by
  induction' n with n ih generalizing x <;> simp_all +decide [ Function.iterate_succ_apply' ];
  rw [ ← ih, φ.transfer_comm ]

/-
A CSS morphism preserves response profiles: the response profile of `φ(x)` in `S₂`
equals the response profile of `x` in `S₁`. This is the fundamental compatibility
between morphisms and the spectral boundary.
-/
theorem morphism_preserves_responseProfile (φ : CSSMorphism S₁ S₂)
    (x : X₁) :
    S₂.responseProfile (φ.toFun x) = S₁.responseProfile x := by
  ext n c; simp +decide [ *, ClosureScatteringSystem.responseProfile ] ;
  induction' n with n ih generalizing x c <;> simp_all +decide [ Function.iterate_succ_apply' ];
  · exact φ.boundary_comm x c ▸ rfl;
  · have := φ.transfer_comm ( S₁.transfer^[n] x ) ; have := φ.boundary_comm ( S₁.transfer^[n] x ) c; simp_all +decide [ ← Function.iterate_succ_apply' ] ;
    convert ih ( S₁.transfer x ) c using 1;
    rw [ φ.transfer_comm ]

end MorphismProperties

/-! ## Spectral Boundary Construction -/

section SpectralBoundary

variable {R : Type*} {X : Type*} {C : Type*}

/-
Shift of a response profile remains in the range of response profiles.
This is because shifting corresponds to applying one step of transfer.
-/
theorem responseProfile_shift_mem_range (S : ClosureScatteringSystem R X C)
    {f : ℕ → C → R} (hf : f ∈ Set.range S.responseProfile) :
    (fun n c => f (n + 1) c) ∈ Set.range S.responseProfile := by
  -- Let's obtain the state `x` such that `f = S.responseProfile x`.
  obtain ⟨x, hx⟩ := hf;
  exact ⟨ S.transfer x, by aesop ⟩

/-- Construct the spectral boundary semimodule from a closure-scattering system.
This maps a system to its "dual" representation as a shift-closed set of
response profiles, capturing all observable boundary behavior. -/
noncomputable def ClosureScatteringSystem.toSpectralBoundary
    (S : ClosureScatteringSystem R X C) :
    SpectralBoundarySemimodule R C where
  profiles := Set.range S.responseProfile
  shift_closed _ hf := responseProfile_shift_mem_range S hf

/-
A surjective CSS morphism induces inclusion of spectral boundary profiles:
if `φ : S₁ → S₂` is surjective, then every response profile of `S₂` is also
a response profile of `S₁`.
-/
theorem surjective_morphism_spectral_inclusion
    {X₁ X₂ : Type*}
    {S₁ : ClosureScatteringSystem R X₁ C}
    {S₂ : ClosureScatteringSystem R X₂ C}
    (φ : CSSMorphism S₁ S₂)
    (hφ_surj : Function.Surjective φ.toFun) :
    S₂.toSpectralBoundary.profiles ⊆ S₁.toSpectralBoundary.profiles := by
  -- Take any profile p in S₂.toSpectralBoundary.profiles = range(S₂.responseProfile). So p = S₂.responseProfile y for some y.
  intro p hp
  obtain ⟨y, rfl⟩ : ∃ y, p = S₂.responseProfile y := by
    exact hp.imp fun x hx => hx.symm;
  obtain ⟨x, rfl⟩ := hφ_surj y
  exact ⟨x, Eq.symm (morphism_preserves_responseProfile φ x)⟩

end SpectralBoundary

/-! ## Main Duality / Uniqueness Theorem -/

section MainDuality

variable {R : Type*} {C : Type*}

/-
**Main Duality Theorem: Separated systems with identical response profile ranges
are isomorphic.**

If two closure-scattering systems are both separated (reduced/observable) and have
the same set of response profiles, then there exists a canonical isomorphism between
them. The isomorphism is constructed by matching states with identical response profiles.

This is the idempotent analogue of the uniqueness of minimal realization in systems
theory, and of the Myhill-Nerode theorem for automata. It establishes that the
observable boundary behavior completely determines the reduced system up to isomorphism.

**Proof idea:** Define `f : X₁ → X₂` by sending each state to the unique state with
the same response profile (exists by equal ranges, unique by separation). Then:
- `f` is injective because `S₁` is separated
- `f` is surjective because the ranges match
- `f` commutes with transfer because shifting response profiles commutes with `f`
- `f` preserves boundary because boundary values are read from response profiles at `n = 0`
-/
theorem separated_systems_isomorphic_of_same_profiles
    {X₁ X₂ : Type*}
    (S₁ : ClosureScatteringSystem R X₁ C)
    (S₂ : ClosureScatteringSystem R X₂ C)
    (hsep₁ : S₁.Separated)
    (hsep₂ : S₂.Separated)
    (hrange : Set.range S₁.responseProfile = Set.range S₂.responseProfile) :
    Nonempty (CSSIsomorphism S₁ S₂) := by
  -- Define the map $f : X₁ → X₂$ by $f(x) = y$ where $S₂.responseProfile y = S₁.responseProfile x$.
  have hf : ∀ x : X₁, ∃! y : X₂, S₂.responseProfile y = S₁.responseProfile x := by
    intro x
    obtain ⟨y, hy⟩ : ∃ y : X₂, S₂.responseProfile y = S₁.responseProfile x := by
      exact hrange.subset ( Set.mem_range_self x )
    use y
    aesop;
  choose f hf₁ hf₂ using hf;
  -- Show that $f$ is a morphism of closure-scattering systems.
  have hf_morphism : ∀ x : X₁, S₂.transfer (f x) = f (S₁.transfer x) ∧ ∀ c : C, S₁.boundary x c = S₂.boundary (f x) c := by
    intro x;
    refine' ⟨ hf₂ _ _ _, _ ⟩;
    · convert congr_arg ( fun f => fun n c => f ( n + 1 ) c ) ( hf₁ x ) using 1;
    · exact fun c => by simpa using congr_fun ( congr_fun ( hf₁ x ) 0 ) c |> Eq.symm;
  -- Show that $f$ is bijective.
  have hf_bijective : Function.Bijective f := by
    constructor;
    · intro x y hxy;
      exact hsep₁ ( by have := hf₁ x; have := hf₁ y; aesop );
    · intro y;
      obtain ⟨ x, hx ⟩ := hrange.symm.subset ( Set.mem_range_self y );
      exact ⟨ x, hf₂ x y hx.symm ▸ rfl ⟩;
  exact ⟨ ⟨ ⟨ f, fun x => hf_morphism x |>.1.symm, fun x c => hf_morphism x |>.2 c ⟩, hf_bijective ⟩ ⟩

end MainDuality

/-! ## Minimal Realization -/

section MinimalRealization

variable {R : Type*} {X : Type*} {C : Type*}

/-- The minimal realization of a closure-scattering system.
States are response profiles (elements of `Set.range S.responseProfile`),
transfer is the shift map, and boundary observation is evaluation at `n = 0`.
The closure is taken to be the identity (trivial closure).

This construction is the idempotent analogue of the observable canonical form
in linear systems theory. It produces the smallest separated system with the
same observable boundary behavior. -/
noncomputable def ClosureScatteringSystem.minimalRealization
    (S : ClosureScatteringSystem R X C) :
    ClosureScatteringSystem R ↥(Set.range S.responseProfile) C where
  cl := fun A => A
  cl_extensive := fun A => le_refl A
  cl_monotone := monotone_id
  cl_idem := fun _ => rfl
  transfer := fun ⟨f, hf⟩ =>
    ⟨fun n c => f (n + 1) c, responseProfile_shift_mem_range S hf⟩
  boundary := fun ⟨f, _⟩ c => f 0 c

/-
The `n`-fold iterate of transfer in the minimal realization shifts
a response profile by `n` steps.
-/
theorem minimalRealization_iterate_transfer (S : ClosureScatteringSystem R X C)
    (f : ↥(Set.range S.responseProfile)) (n : ℕ) :
    (S.minimalRealization.transfer^[n] f).val = fun m c => f.val (m + n) c := by
  induction' n with n ih generalizing f;
  · -- The zeroth iterate of any function is the identity function.
    simp [Function.iterate_zero];
  · convert congr_arg ( fun g : ℕ → C → R => fun m c => g ( m + 1 ) c ) ( ih f ) using 1;
    · exact congr_arg Subtype.val ( Function.iterate_succ_apply' _ _ _ );
    · grind

/-
The response profile in the minimal realization equals the underlying
function value. This is the key identity showing that the minimal realization
is a faithful representation of response profiles.
-/
theorem minimalRealization_responseProfile_eq_val (S : ClosureScatteringSystem R X C)
    (f : ↥(Set.range S.responseProfile)) :
    S.minimalRealization.responseProfile f = f.val := by
  apply funext;
  intro n;
  convert minimalRealization_iterate_transfer S f n;
  constructor <;> intro h <;> ext m c <;> simp_all +decide [ funext_iff ];
  · exact minimalRealization_iterate_transfer S f n ▸ rfl;
  · convert h 0 m using 1;
    rw [ zero_add ]

/-
The minimal realization is separated: distinct response profiles remain
distinct in the minimal realization.
-/
theorem minimalRealization_separated (S : ClosureScatteringSystem R X C) :
    S.minimalRealization.Separated := by
  intro f g hfg;
  exact Subtype.ext ( by simpa [ minimalRealization_responseProfile_eq_val ] using hfg )

/-
The minimal realization has the same spectral boundary as the original system:
the sets of response profiles coincide.
-/
theorem minimalRealization_same_spectral_boundary (S : ClosureScatteringSystem R X C) :
    Set.range S.minimalRealization.responseProfile = Set.range S.responseProfile := by
  ext f;
  constructor;
  · grind +suggestions;
  · rintro ⟨ x, rfl ⟩;
    exact ⟨ ⟨ S.responseProfile x, Set.mem_range_self x ⟩, by simp +decide [ minimalRealization_responseProfile_eq_val ] ⟩

/-
**Certified Minimal Resonance Reconstruction.**
Any separated system with the same response profiles as `S` is isomorphic to
the minimal realization of `S`. This establishes:
1. **Existence**: the minimal realization always exists
2. **Uniqueness**: it is the unique separated system with that boundary data
3. **Reconstruction**: boundary response data certifiably determines the model
-/
theorem minimal_resonance_realization_unique (S : ClosureScatteringSystem R X C)
    {Y : Type*} (S' : ClosureScatteringSystem R Y C)
    (hsep : S'.Separated)
    (hprofiles : Set.range S'.responseProfile = Set.range S.responseProfile) :
    Nonempty (CSSIsomorphism S' S.minimalRealization) := by
  apply separated_systems_isomorphic_of_same_profiles;
  · assumption;
  · exact minimalRealization_separated S
  · rw [ hprofiles, minimalRealization_same_spectral_boundary ]

/-
**Finite Closure-Scattering Duality.**
For a system with finite state space, there exists a spectral boundary semimodule
such that the minimal realization is separated, has the same spectral boundary,
and the resonance congruence is the coarsest observation-compatible equivalence.
-/
theorem finite_closure_scattering_duality
    [Fintype X]
    (S : ClosureScatteringSystem R X C) :
    ∃ M : SpectralBoundarySemimodule R C,
      M.profiles = Set.range S.responseProfile ∧
      S.minimalRealization.Separated ∧
      Set.range S.minimalRealization.responseProfile = M.profiles ∧
      ∀ (equiv : X → X → Prop) (_ : Equivalence equiv)
        (_ : ∀ x y, equiv x y → ∀ c, S.boundary x c = S.boundary y c)
        (_ : ∀ x y, equiv x y → equiv (S.transfer x) (S.transfer y)),
        ∀ x y, equiv x y → S.resonanceEquiv x y := by
  exact ⟨S.toSpectralBoundary, rfl, minimalRealization_separated S,
    minimalRealization_same_spectral_boundary S,
    fun equiv he hb ht x y hxy => resonanceEquiv_coarsest S equiv he hb ht hxy⟩

end MinimalRealization

end ModularScatteringDuality