/-
# Stone Duality for Ultrametric Proof Semirings via Prime Congruence Spectra

This file establishes a non-Archimedean geometric representation theory for proof
semirings. The central construction turns a semiring equipped with observer
congruences into a topological space (its **prime congruence spectrum**), endows
that spectrum with an **ultrametric** derived from observer agreement depth, and
proves a **reconstruction theorem**: the canonical evaluation map from the semiring
into functions on the spectrum is injective under a separation hypothesis.

## Mathematical Architecture

1. **Spectrum**: `ProofSpectrum S` = nontrivial ring congruences (prime-like observers)
2. **Topology**: Generated by basic opens `D(a,b) = {x | ¬ x.toCon a b}`
3. **Ultrametric**: Tree/prefix metric from finite probe families
4. **Reconstruction**: Evaluation map is injective modulo CodeEq
5. **Functoriality**: Ring homomorphisms induce continuous maps on spectra

## Cross-Domain Connections

- **Stone/Priestley duality**: basic opens form a clopen basis
- **Algebraic geometry**: D(a,b) analogous to D(f) in Spec(R)
- **p-adic analysis**: observer agreement depth gives non-Archimedean valuation
- **Proof compression**: diagonal avoidance becomes topological separation
- **Machine learning**: observers are features, spectrum is latent space
-/

import Mathlib

set_option maxHeartbeats 800000

namespace Bridges.Speculative

universe u

open Set Function Classical

noncomputable section

/-! ## §1: Core Algebraic Structures -/

/-- A finite indexed family of ring congruences on a semiring. -/
structure FiniteProofObserverFamily (S : Type u) [Semiring S] where
  n : ℕ
  cong : Fin n → RingCon S

/-- Two elements are `CodeEq` when every observer identifies them. -/
def CodeEq {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (a b : S) : Prop :=
  ∀ i : Fin F.n, (F.cong i) a b

/-- A prime-like observer: a ring congruence with nontrivial separation power. -/
structure PrimeLikeObserver (S : Type u) [Semiring S] where
  toCon : RingCon S
  nontrivial : ∃ a b : S, ¬ toCon a b

/-- The prime observer spectrum of a proof semiring. -/
abbrev ProofSpectrum (S : Type u) [Semiring S] := PrimeLikeObserver S

@[ext]
theorem PrimeLikeObserver.ext {S : Type u} [Semiring S]
    {x y : PrimeLikeObserver S} (h : x.toCon = y.toCon) : x = y := by
  cases x; cases y; congr

/-- A compression operator wrapping a self-map with complexity measure. -/
structure ProofCompressionOperator (S : Type u) where
  toFun : S → S
  nameComplexity : ℕ

/-- An ultrametric distance predicate. -/
def UltrametricDistPred {α : Type*} (d : α → α → ℝ) : Prop :=
  (∀ x y, 0 ≤ d x y) ∧
  (∀ x y, d x y = 0 ↔ x = y) ∧
  (∀ x y, d x y = d y x) ∧
  (∀ x y z, d x z ≤ max (d x y) (d y z))

/-- Contraction structure for proof state dynamics. -/
structure ProofStateContraction (S : Type u) where
  d : S → S → ℝ
  isUltra : UltrametricDistPred d
  F : S → S
  q : ℝ
  hq_nonneg : 0 ≤ q
  hq_lt_one : q < 1
  contractive : ∀ x y, d (F x) (F y) ≤ q * d x y

/-- Diagonal stability for iterative proof systems. -/
structure DiagStableProofSystem (S : Type u) where
  d : S → S → ℝ
  isUltra : UltrametricDistPred d
  F : S → S
  diagonalStable :
    ∀ x n, d (F^[n+2] x) (F^[n+1] x) ≤ d (F^[n+1] x) (F^[n] x)

/-! ## §2: Evaluation and Basic Opens -/

/-- Evaluate whether observer `x` identifies elements `a` and `b`. -/
def evalEq {S : Type u} [Semiring S] (x : ProofSpectrum S) (a b : S) : Prop :=
  x.toCon a b

/-- Basic open set: observers that distinguish `a` from `b`. -/
def basicOpenPair {S : Type u} [Semiring S] (a b : S) : Set (ProofSpectrum S) :=
  {x | ¬ x.toCon a b}

/-- Basic open for zero-separation. -/
def basicOpenOf {S : Type u} [Semiring S] (a : S) : Set (ProofSpectrum S) :=
  {x | ¬ x.toCon a 0}

/-- Diagonal avoidance open. -/
def diagonalAvoidOpen {S : Type u} [Semiring S]
    (T : Finset S) : Set (ProofSpectrum S) :=
  {x | ∀ a ∈ T, ∀ b ∈ T, a ≠ b → ¬ x.toCon a b}

/-! ## §3: CodeEq Properties -/

theorem codeEq_refl {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (a : S) :
    CodeEq F a a :=
  fun i => (F.cong i).refl a

theorem codeEq_symm {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a b : S}
    (h : CodeEq F a b) : CodeEq F b a :=
  fun i => (F.cong i).symm (h i)

theorem codeEq_trans {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a b c : S}
    (hab : CodeEq F a b) (hbc : CodeEq F b c) : CodeEq F a c :=
  fun i => (F.cong i).trans (hab i) (hbc i)

/-- CodeEq defines a setoid on S. -/
def codeEqSetoid {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) : Setoid S where
  r := CodeEq F
  iseqv := ⟨codeEq_refl F, fun h => codeEq_symm F h,
            fun h1 h2 => codeEq_trans F h1 h2⟩

/-- CodeEq respects addition. -/
theorem codeEq_add {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a₁ a₂ b₁ b₂ : S}
    (ha : CodeEq F a₁ a₂) (hb : CodeEq F b₁ b₂) :
    CodeEq F (a₁ + b₁) (a₂ + b₂) :=
  fun i => (F.cong i).add (ha i) (hb i)

/-- CodeEq respects multiplication. -/
theorem codeEq_mul {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a₁ a₂ b₁ b₂ : S}
    (ha : CodeEq F a₁ a₂) (hb : CodeEq F b₁ b₂) :
    CodeEq F (a₁ * b₁) (a₂ * b₂) :=
  fun i => (F.cong i).mul (ha i) (hb i)

/-- CodeEq as a RingCon. -/
def codeEqRingCon {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) : RingCon S where
  r := CodeEq F
  iseqv := (codeEqSetoid F).iseqv
  add' := fun ha hb => codeEq_add F ha hb
  mul' := fun ha hb => codeEq_mul F ha hb

/-! ## §4: Separation Theorems -/

/-- Separation hypothesis: non-CodeEq elements are distinguished by
some prime-like observer. -/
class SpectralSeparation (S : Type u) [Semiring S]
    (F : FiniteProofObserverFamily S) : Prop where
  separates : ∀ a b : S, ¬ CodeEq F a b →
    ∃ x : ProofSpectrum S, ¬ x.toCon a b

/-- Diagonal avoidance on a finite set. -/
def DiagonalAvoidsOn {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (T : Finset S) : Prop :=
  ∀ ⦃x y : S⦄, x ∈ T → y ∈ T → x ≠ y → ∃ i : Fin F.n, ¬ (F.cong i) x y

/-- Diagonal avoidance ↔ pairwise non-CodeEq. -/
theorem diagonalAvoidsOn_iff_pairwise_not_codeEq {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (T : Finset S) :
    DiagonalAvoidsOn F T ↔
      ∀ ⦃x y : S⦄, x ∈ T → y ∈ T → x ≠ y → ¬ CodeEq F x y := by
  constructor
  · intro hsep x y hx hy hne hceq
    obtain ⟨i, hi⟩ := hsep hx hy hne
    exact hi (hceq i)
  · intro h x y hx hy hne
    by_contra hall
    push_neg at hall
    exact h hx hy hne hall

/-- Under spectral separation, distinct elements (mod CodeEq) are separated. -/
theorem exists_prime_observer_separating {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) [sep : SpectralSeparation S F]
    {a b : S} (h : ¬ CodeEq F a b) :
    ∃ x : ProofSpectrum S, ¬ x.toCon a b :=
  sep.separates a b h

/-- Each nontrivial congruence in the family yields a spectral point. -/
def familyObserver {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (i : Fin F.n)
    (h : ∃ a b : S, ¬ (F.cong i) a b) : ProofSpectrum S :=
  ⟨F.cong i, h⟩

/-- Diagonal avoidance gives spectral separation on the support. -/
theorem diagonalAvoids_gives_spectral_separation {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (T : Finset S)
    (hsep : DiagonalAvoidsOn F T)
    {a b : S} (ha : a ∈ T) (hb : b ∈ T) (hne : a ≠ b) :
    ∃ x : ProofSpectrum S, ¬ x.toCon a b := by
  obtain ⟨i, hi⟩ := hsep ha hb hne
  exact ⟨⟨F.cong i, ⟨a, b, hi⟩⟩, hi⟩

/-- evalEq respects CodeEq at family observers. -/
theorem evalEq_of_codeEq {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a b : S} (h : CodeEq F a b)
    (i : Fin F.n) (hnt : ∃ c d : S, ¬ (F.cong i) c d) :
    evalEq (familyObserver F i hnt) a b := h i

/-! ## §5: Spectral Topology -/

/-- The spectral topology on ProofSpectrum S. -/
instance spectralTopology (S : Type u) [Semiring S] :
    TopologicalSpace (ProofSpectrum S) :=
  TopologicalSpace.generateFrom {U | ∃ a b : S, U = basicOpenPair a b}

/-- Basic pair-opens are open. -/
theorem basicOpenPair_isOpen {S : Type u} [Semiring S] (a b : S) :
    IsOpen (basicOpenPair (S := S) a b) :=
  TopologicalSpace.GenerateOpen.basic _ ⟨a, b, rfl⟩

/-- Complement characterization. -/
theorem basicOpenPair_compl {S : Type u} [Semiring S] (a b : S) :
    (basicOpenPair (S := S) a b)ᶜ = {x | x.toCon a b} := by
  ext x; simp [basicOpenPair]

/-- basicOpenOf a = basicOpenPair a 0. -/
theorem basicOpenOf_eq_pair {S : Type u} [Semiring S] (a : S) :
    basicOpenOf (S := S) a = basicOpenPair a 0 := rfl

/-- Self-pairing gives empty set. -/
theorem basicOpenPair_self_eq_empty {S : Type u} [Semiring S] (a : S) :
    basicOpenPair (S := S) a a = ∅ := by
  ext x; simp [basicOpenPair, (x.toCon).refl]

/-- basicOpenPair is symmetric. -/
theorem basicOpenPair_symm {S : Type u} [Semiring S] (a b : S) :
    basicOpenPair (S := S) a b = basicOpenPair b a := by
  ext x; simp [basicOpenPair]
  exact ⟨fun h hba => h (x.toCon.symm hba),
         fun h hab => h (x.toCon.symm hab)⟩

/-
**T₀ Separation**: topologically indistinguishable spectral points are equal.
-/
theorem spectralTopology_t0 (S : Type u) [Semiring S] :
    @T0Space (ProofSpectrum S) (spectralTopology S) := by
  refine' ⟨ _ ⟩;
  rintro ⟨ x, hx ⟩ ⟨ y, hy ⟩ hxy;
  rw [ inseparable_iff_forall_isOpen ] at hxy;
  ext a b; specialize hxy ( { z : ProofSpectrum S | ¬z.toCon a b } ) ; simp_all +decide [ basicOpenPair ] ;
  contrapose! hxy;
  exact ⟨ TopologicalSpace.GenerateOpen.basic _ ⟨ a, b, rfl ⟩, hxy.symm ⟩

/-! ## §6: Ultrametric Structure on the Spectrum -/

/-- A finite probe family: test pairs for measuring observer agreement. -/
structure FiniteProbeFamily (S : Type u) [Semiring S] where
  size : ℕ
  probes : Fin size → S × S

/-- Whether two observers agree on all probes up to index k. -/
def agreesUpTo {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) (k : ℕ) : Prop :=
  ∀ i : Fin P.size, i.val < k →
    (x.toCon (P.probes i).1 (P.probes i).2 ↔ y.toCon (P.probes i).1 (P.probes i).2)

theorem agreesUpTo_refl {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x : ProofSpectrum S) (k : ℕ) :
    agreesUpTo P x x k :=
  fun _ _ => Iff.rfl

theorem agreesUpTo_symm {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) {x y : ProofSpectrum S} {k : ℕ}
    (h : agreesUpTo P x y k) : agreesUpTo P y x k :=
  fun i hi => (h i hi).symm

theorem agreesUpTo_mono {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) {x y : ProofSpectrum S} {j k : ℕ}
    (hjk : j ≤ k) (h : agreesUpTo P x y k) : agreesUpTo P x y j :=
  fun i hi => h i (lt_of_lt_of_le hi hjk)

theorem agreesUpTo_trans {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) {x y z : ProofSpectrum S} {k : ℕ}
    (hxy : agreesUpTo P x y k) (hyz : agreesUpTo P y z k) :
    agreesUpTo P x z k :=
  fun i hi => (hxy i hi).trans (hyz i hi)

/-- The agreement depth: first index where observers disagree, or P.size if
they agree on everything. -/
noncomputable def agreementDepth {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) : ℕ :=
  if h : ∃ i : Fin P.size,
      ¬(x.toCon (P.probes i).1 (P.probes i).2 ↔ y.toCon (P.probes i).1 (P.probes i).2)
  then (Finset.filter
      (fun i : Fin P.size =>
        ¬(x.toCon (P.probes i).1 (P.probes i).2 ↔ y.toCon (P.probes i).1 (P.probes i).2))
      Finset.univ).min' (by
        rw [Finset.filter_nonempty_iff]
        exact ⟨h.choose, Finset.mem_univ _, h.choose_spec⟩)
  else P.size

/-
Agreement depth is at most P.size.
-/
theorem agreementDepth_le_size {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) :
    agreementDepth P x y ≤ P.size := by
  by_cases h : ∃ i : Fin P.size, ¬ ( x.toCon ( P.probes i ).1 ( P.probes i ).2 ↔ y.toCon ( P.probes i ).1 ( P.probes i ).2 ) <;> simp +decide [ h, agreementDepth ]

/-
Agreement depth of a point with itself is P.size.
-/
theorem agreementDepth_self {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x : ProofSpectrum S) :
    agreementDepth P x x = P.size := by
  unfold agreementDepth; aesop;

/-
Agreement depth is symmetric.
-/
theorem agreementDepth_symm {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) :
    agreementDepth P x y = agreementDepth P y x := by
  unfold agreementDepth; simp +decide [ iff_comm ] ;

/-
**Key ultrametric property**: agreement depth min-stability.
-/
theorem agreementDepth_min_triangle {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y z : ProofSpectrum S) :
    min (agreementDepth P x y) (agreementDepth P y z) ≤ agreementDepth P x z := by
  unfold agreementDepth;
  split_ifs <;> simp_all +decide [ Finset.min' ];
  · grind;
  · grind

/-- The ultrametric observer distance on the spectrum. -/
noncomputable def observerDist {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) : ℝ :=
  if agreementDepth P x y = P.size then 0
  else (1/2 : ℝ) ^ agreementDepth P x y

/-
Observer distance is nonneg.
-/
theorem observerDist_nonneg {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) :
    0 ≤ observerDist P x y := by
  unfold observerDist; split_ifs <;> positivity;

/-
Observer distance: d(x,x) = 0.
-/
theorem observerDist_self {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x : ProofSpectrum S) :
    observerDist P x x = 0 := by
  unfold observerDist; simp +decide [ agreementDepth_self ] ;

/-
Observer distance is symmetric.
-/
theorem observerDist_symm {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y : ProofSpectrum S) :
    observerDist P x y = observerDist P y x := by
  unfold observerDist;
  rw [ agreementDepth_symm ]

/-
**Ultrametric inequality**: d(x,z) ≤ max(d(x,y), d(y,z)).
-/
theorem observerDist_ultrametric {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S) (x y z : ProofSpectrum S) :
    observerDist P x z ≤ max (observerDist P x y) (observerDist P y z) := by
  by_cases h : agreementDepth P x z = P.size <;> simp_all +decide [ observerDist ];
  · exact Or.inl ( by positivity );
  · -- By the min-triangle inequality, we have min(agreementDepth P x y, agreementDepth P y z) ≤ agreementDepth P x z.
    have h_min_triangle : min (agreementDepth P x y) (agreementDepth P y z) ≤ agreementDepth P x z := by
      -- Apply the min-triangle inequality to conclude the proof.
      apply agreementDepth_min_triangle;
    split_ifs <;> simp_all +decide [ min_le_iff ];
    · exact False.elim ( h ( le_antisymm ( agreementDepth_le_size P x z ) h_min_triangle ) );
    · exact Or.inr ( inv_anti₀ ( by positivity ) ( pow_le_pow_right₀ ( by norm_num ) ( h_min_triangle.resolve_left ( by linarith [ agreementDepth_le_size P x z, Nat.lt_of_le_of_ne ( agreementDepth_le_size P x z ) h ] ) ) ) );
    · exact Or.inl ( inv_anti₀ ( by positivity ) ( pow_le_pow_right₀ ( by norm_num ) ( h_min_triangle.resolve_right ( by linarith [ agreementDepth_le_size P x z, Nat.lt_of_le_of_ne ( agreementDepth_le_size P x z ) h ] ) ) ) );
    · exact Or.imp ( fun h => inv_anti₀ ( by positivity ) ( pow_le_pow_right₀ ( by norm_num ) h ) ) ( fun h => inv_anti₀ ( by positivity ) ( pow_le_pow_right₀ ( by norm_num ) h ) ) h_min_triangle

/-
The observer distance is a full ultrametric when probes separate points.
-/
theorem observerDist_isUltrametric {S : Type u} [Semiring S]
    (P : FiniteProbeFamily S)
    (hP : ∀ x y : ProofSpectrum S,
      (∀ i : Fin P.size,
        (x.toCon (P.probes i).1 (P.probes i).2 ↔
         y.toCon (P.probes i).1 (P.probes i).2)) → x = y) :
    UltrametricDistPred (observerDist P) := by
  refine' ⟨ _, _, _, _ ⟩;
  · exact fun x y => observerDist_nonneg P x y
  · intro x y;
    constructor;
    · intro hxy
      have h_agree : agreementDepth P x y = P.size := by
        unfold observerDist at hxy; aesop;
      apply hP x y
      intro i
      simp [agreementDepth] at h_agree
      generalize_proofs at *;
      grind +revert;
    · exact fun h => h ▸ observerDist_self P x;
  · exact fun x y => observerDist_symm P x y
  · exact fun x y z => observerDist_ultrametric P x y z

/-! ## §7: Clopen Basis -/

theorem basicOpen_isOpen {S : Type u} [Semiring S] (a b : S) :
    IsOpen (basicOpenPair (S := S) a b) :=
  basicOpenPair_isOpen a b

/-- The **constructible (patch) topology** on the spectrum, generated by both
basic opens D(a,b) and their complements V(a,b). In algebraic geometry,
this is the topology that makes Spec into a Stone space. -/
def constructibleTopology (S : Type u) [Semiring S] :
    TopologicalSpace (ProofSpectrum S) :=
  TopologicalSpace.generateFrom
    ({U | ∃ a b : S, U = basicOpenPair a b} ∪
     {U | ∃ a b : S, U = (basicOpenPair a b)ᶜ})

/-
Basic opens are clopen in the constructible topology. This is the
topology under which the spectrum becomes a Stone space.
-/
theorem basicOpenPair_isClopen_constructible {S : Type u} [Semiring S] (a b : S) :
    @IsClopen (ProofSpectrum S) (constructibleTopology S) (basicOpenPair a b) := by
  constructor <;> simp_all +decide [ IsClopen, basicOpenPair ];
  · apply_rules [ isClosed_compl_iff.mpr, TopologicalSpace.GenerateOpen.basic ];
    unfold basicOpenPair; aesop;
  · exact TopologicalSpace.GenerateOpen.basic _ ( Or.inl ⟨ a, b, rfl ⟩ )

/-- Diagonal avoidance is antitone. -/
theorem diagonalAvoidOpen_antitone {S : Type u} [Semiring S]
    {T₁ T₂ : Finset S} (h : T₁ ⊆ T₂) :
    diagonalAvoidOpen (S := S) T₂ ⊆ diagonalAvoidOpen T₁ := by
  intro x hx a ha b hb hab
  exact hx a (h ha) b (h hb) hab

/-- Empty diagonal avoidance is the whole spectrum. -/
theorem diagonalAvoidOpen_empty {S : Type u} [Semiring S] :
    diagonalAvoidOpen (S := S) ∅ = univ := by
  ext x; simp [diagonalAvoidOpen]

/-! ## §8: Spectral Evaluation and Reconstruction -/

/-- Spectral evaluation at a point: whether the observer identifies a with 0. -/
def spectralEvalProp {S : Type u} [Semiring S]
    (a : S) (x : ProofSpectrum S) : Prop :=
  x.toCon a 0

/-- The spectral profile of an element. -/
def spectralProfile {S : Type u} [Semiring S]
    (a : S) : ProofSpectrum S → Prop :=
  spectralEvalProp a

/-- Spectral evaluation respects CodeEq at family observers. -/
theorem spectralEval_respects_codeEq {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a b : S}
    (h : CodeEq F a b) (i : Fin F.n)
    (hnt : ∃ c d : S, ¬ (F.cong i) c d) :
    spectralEvalProp a (familyObserver F i hnt) =
    spectralEvalProp b (familyObserver F i hnt) := by
  simp only [spectralEvalProp, familyObserver]
  exact propext ⟨fun ha => (F.cong i).trans ((F.cong i).symm (h i)) ha,
                 fun hb => (F.cong i).trans (h i) hb⟩

/-- **Spectral Separation (Pair Form)**: non-CodeEq elements are separated
by some spectral point. This is the correct formulation using the pair-based
evaluation, not the zero-based one (which requires ring subtraction). -/
theorem spectral_points_separate_classes_pair {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) [sep : SpectralSeparation S F]
    {a b : S} (h : ¬ CodeEq F a b) :
    ∃ x : ProofSpectrum S, ¬ evalEq x a b :=
  sep.separates a b h

/-
**Spectral Separation (Zero Form)**: In a ring (with subtraction),
non-CodeEq elements have distinct zero-profiles. This uses the fact that
in a ring, `c(a,b) ↔ c(a-b, 0)`.
-/
theorem spectral_points_separate_classes_ring {S : Type u} [Ring S]
    (F : FiniteProofObserverFamily S) [sep : SpectralSeparation S F]
    {a b : S} (h : ¬ CodeEq F a b) :
    ∃ x : ProofSpectrum S, spectralEvalProp (a - b) x ≠ spectralEvalProp 0 x := by
  obtain ⟨ x, hx ⟩ := sep.separates a b h;
  contrapose! hx;
  specialize hx x;
  convert x.toCon.add ( hx.mpr _ ) ( x.toCon.refl b ) using 1;
  · rw [ sub_add_cancel ];
  · rw [ zero_add ];
  · exact x.toCon.refl _

/-- Spectral evaluation as a map to observer quotient tuples. -/
def spectralEvalFamily {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (a : S) :
    (i : Fin F.n) → (F.cong i).Quotient :=
  fun i => (F.cong i).toQuotient a

/-
Spectral evaluation equality characterizes CodeEq.
-/
theorem spectralEvalFamily_eq_iff_codeEq {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) (a b : S) :
    spectralEvalFamily F a = spectralEvalFamily F b ↔ CodeEq F a b := by
  simp +decide [ funext_iff, spectralEvalFamily, CodeEq ]

/-
**Reconstruction Theorem (Injectivity)**: spectral evaluation
is injective on CodeEq classes.
-/
theorem spectralEvalFamily_injective_mod_codeEq {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) {a b : S}
    (h : spectralEvalFamily F a = spectralEvalFamily F b) :
    CodeEq F a b :=
  (spectralEvalFamily_eq_iff_codeEq F a b).mp h

/-- The quotient map induced by spectral evaluation. -/
def spectralEvalQuotient {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) :
    (codeEqRingCon F).Quotient → ((i : Fin F.n) → (F.cong i).Quotient) :=
  Quotient.lift (spectralEvalFamily F) (by
    intro a b hab
    ext i
    simp only [spectralEvalFamily, RingCon.eq]
    exact hab i)

/-
**Reconstruction Theorem (Quotient Injectivity)**.
-/
theorem spectralEvalQuotient_injective {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) :
    Injective (spectralEvalQuotient F) := by
  rintro ⟨ a ⟩ ⟨ b ⟩ hab;
  exact Quotient.sound ( spectralEvalFamily_eq_iff_codeEq F a b |>.1 hab )

/-! ## §9: Functoriality -/

/-- Pullback of a ring congruence along a ring homomorphism. -/
def pullbackRingCon {S T : Type u} [Semiring S] [Semiring T]
    (φ : S →+* T) (c : RingCon T) : RingCon S :=
  c.comap φ

/-- specMap for surjective ring homomorphisms. -/
def specMapSurj {S T : Type u} [Semiring S] [Semiring T]
    (φ : S →+* T) (hφ : Surjective φ) (x : ProofSpectrum T) :
    ProofSpectrum S where
  toCon := pullbackRingCon φ x.toCon
  nontrivial := by
    obtain ⟨a, b, hab⟩ := x.nontrivial
    obtain ⟨sa, rfl⟩ := hφ a
    obtain ⟨sb, rfl⟩ := hφ b
    exact ⟨sa, sb, hab⟩

/-
specMap respects identity.
-/
theorem specMap_id {S : Type u} [Semiring S] (x : ProofSpectrum S) :
    specMapSurj (RingHom.id S) surjective_id x = x := by
  ext a b; simp +decide [ specMapSurj ] ;
  exact Iff.rfl

/-
specMap respects composition.
-/
theorem specMap_comp {S T U : Type u} [Semiring S] [Semiring T] [Semiring U]
    (φ : S →+* T) (ψ : T →+* U)
    (hφ : Surjective φ) (hψ : Surjective ψ)
    (x : ProofSpectrum U) :
    specMapSurj φ hφ (specMapSurj ψ hψ x) =
    specMapSurj (ψ.comp φ) (hψ.comp hφ) x := by
  ext;
  exact Iff.rfl

/-
specMap is continuous.
-/
theorem specMapSurj_continuous {S T : Type u} [Semiring S] [Semiring T]
    (φ : S →+* T) (hφ : Surjective φ) :
    @Continuous (ProofSpectrum T) (ProofSpectrum S)
      (spectralTopology T) (spectralTopology S)
      (specMapSurj φ hφ) := by
  refine' continuous_generateFrom_iff.mpr _;
  rintro _ ⟨ a, b, rfl ⟩;
  convert basicOpenPair_isOpen ( φ a ) ( φ b ) using 1

/-
Preimage of a basic open under specMap is a basic open.
-/
theorem specMap_preimage_basicOpen {S T : Type u} [Semiring S] [Semiring T]
    (φ : S →+* T) (hφ : Surjective φ) (a b : S) :
    specMapSurj φ hφ ⁻¹' (basicOpenPair a b) = basicOpenPair (φ a) (φ b) := by
  grind

/-! ## §10: Finite Generation and Compactness -/

/-- A finitely generated proof semiring. -/
class FinitelyGeneratedProofSemiring (S : Type u) [Semiring S] : Prop where
  fg : ∃ (G : Finset S), ∀ a : S, a ∈ Subsemiring.closure (G : Set S)

/-
Compactness when the spectrum is finite.
-/
theorem spectrum_compact_of_finite {S : Type u} [Semiring S]
    [Finite (ProofSpectrum S)] :
    @CompactSpace (ProofSpectrum S) (spectralTopology S) :=
  Finite.compactSpace

/-! ## §11: Bridge to Ultrametric Dynamics -/

/-- A ProofStateContraction induces a DiagStableProofSystem. -/
def diagStableOfContraction {S : Type u}
    (C : ProofStateContraction S) : DiagStableProofSystem S where
  d := C.d
  isUltra := C.isUltra
  F := C.F
  diagonalStable := by
    intro x n
    have hcon := C.contractive
    have hq := C.hq_lt_one
    have hq0 := C.hq_nonneg
    have hnn := C.isUltra.1
    calc C.d (C.F^[n + 2] x) (C.F^[n + 1] x)
        = C.d (C.F (C.F^[n + 1] x)) (C.F (C.F^[n] x)) := by
          congr 1 <;> rw [Function.iterate_succ_apply']
      _ ≤ C.q * C.d (C.F^[n + 1] x) (C.F^[n] x) := hcon _ _
      _ ≤ 1 * C.d (C.F^[n + 1] x) (C.F^[n] x) := by
          apply mul_le_mul_of_nonneg_right hq.le (hnn _ _)
      _ = C.d (C.F^[n + 1] x) (C.F^[n] x) := one_mul _

/-
Iterate pair bound: geometric contraction.
-/
theorem iterate_pair_bound {S : Type u}
    (C : ProofStateContraction S) (x y : S) (n : ℕ) :
    C.d (C.F^[n] x) (C.F^[n] y) ≤ C.q ^ n * C.d x y := by
  induction' n with n ih;
  · simp +decide;
  · simpa only [ pow_succ', mul_assoc, Function.iterate_succ_apply' ] using le_trans ( C.contractive _ _ ) ( mul_le_mul_of_nonneg_left ih C.hq_nonneg )

/-
Adjacent iterates decay geometrically.
-/
theorem iterate_step_bound {S : Type u}
    (C : ProofStateContraction S) (x : S) (n : ℕ) :
    C.d (C.F^[n+1] x) (C.F^[n] x) ≤ C.q ^ n * C.d (C.F x) x := by
  induction' n with n ih;
  · simp +decide;
  · simpa only [ pow_succ', mul_assoc, Function.iterate_succ_apply' ] using le_trans ( C.contractive _ _ ) ( mul_le_mul_of_nonneg_left ih C.hq_nonneg )

/-! ## §12: Main Theorem Package -/

/-
**Proof Semiring Stone Duality Package**: CodeEq is a ring congruence,
spectral evaluation is injective mod CodeEq, and the quotient map is injective.
-/
theorem proof_semiring_stone_duality_package {S : Type u} [Semiring S]
    (F : FiniteProofObserverFamily S) :
    (Equivalence (CodeEq F)) ∧
    (∀ a b : S, spectralEvalFamily F a = spectralEvalFamily F b → CodeEq F a b) ∧
    (Injective (spectralEvalQuotient F)) := by
  exact ⟨ ⟨ codeEq_refl F, codeEq_symm F, codeEq_trans F ⟩, fun a b h => spectralEvalFamily_injective_mod_codeEq F h, spectralEvalQuotient_injective F ⟩

end

end Bridges.Speculative