-- This file is not Lean source: its contents are a stray unified-diff fragment
-- inherited from an earlier cycle (it patches a file under Speculative/AutoResearch).
-- The original text is preserved verbatim below, commented out line by line so that
-- the module parses; nothing has been deleted.

-- --- a/Speculative/AutoResearch/Primitive_Prime_Divisors_for_Composite_Index_Fibonacci_Numbers.lean
-- +++ b/Speculative/AutoResearch/Primitive_Prime_Divisors_for_Composite_Index_Fibonacci_Numbers.lean
-- @@ -99,6 +99,9 @@
--      (show p ∣ Nat.fib (n + 1) from by rwa [← ZMod.natCast_eq_zero_iff]))
--      (by aesop)
--
-- +/-- Key helper: F(np)/F(n) ≡ p · F(n+1)^{p-1} (mod p²).
-- +    Since gcd(F(n+1), p) = 1, Fermat gives F(n+1)^{p-1} ≡ 1 (mod p),
-- +    so F(np)/F(n) ≡ p (mod p²), hence v_p(F(np)/F(n)) = 1. -/
--  -- Wall base case: v_p(F(np)/F(n)) = 1 for odd prime p | F(n)
--  lemma wall_base (n p : ℕ) (hp : Nat.Prime p) (hp2 : p ≠ 2)
--      (hpn : p ∣ Nat.fib n) (hn : 2 ≤ n) :