import Mathlib
import Catalog.Shared.Ispythquadruple.IsPythQuadruple
import Catalog.Shared.HigherPythagorean.LorentzCore

/-!
# The Pythagorean quadruple graph: the `n = 3` Berggren machinery

The catalog definition `IsPythQuadruple a b c d : a² + b² + c² = d²` is the integral null cone of
the Lorentz form of signature `(3,1)`.  Here we build the higher–dimensional analogue of the
Berggren moves on it:

* `quadRefl` — the `4 × 4` integral matrix of the reflection in the all-ones vector `(1,1,1;1)`;
  it is an integral Lorentz automorphism (`quadRefl_isIntegralLorentz`) and acts by
  `(a,b,c,d) ↦ (a−k, b−k, c−k, d−k)` with `k = a+b+c−d` (`quadRefl_mulVec`).
* `content` — the gcd of a quadruple; primitivity is `content = 1`.  It is invariant under the
  reflection, the sign changes and the permutations (`content_move`, `content_neg`, …).
* `Reach` — the reachability relation generated by the reflection, one sign change and two
  transpositions, starting from the root `(1,0,0,1)`.

Main theorems.

* `reach_sound` : everything reachable is a primitive Pythagorean quadruple.
* `reach_of_prim` : **completeness / connectivity** — *every* primitive Pythagorean quadruple with
  non-negative entries and positive height is reachable from `(1,0,0,1)`.  This is the exact
  analogue of Berggren's theorem in dimension three, proved by descent on the height.
* `reach_iff_prim` : the two together.
-/

namespace HigherPythagorean

open Matrix

/-! ## The reflection matrix -/

/-- The reflection of the Lorentz form of signature `(3,1)` in the all-ones vector `(1,1,1;1)`.
This is the dimension-three analogue of the Berggren matrices. -/
def quadRefl : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0, -1, -1, 1; -1, 0, -1, 1; -1, -1, 0, 1; -1, -1, -1, 2]

lemma lorentzJ_three : lorentzJ 3 = !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, -1] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [lorentzJ, Matrix.diagonal, Fin.last, Fin.ext_iff]

/-- `quadRefl` is an integral automorphism of the Lorentz form of signature `(3,1)`. -/
theorem quadRefl_isIntegralLorentz : IsIntegralLorentz quadRefl := by
  unfold IsIntegralLorentz
  rw [lorentzJ_three]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [quadRefl, Matrix.mul_apply, Fin.sum_univ_four]

/-- `quadRefl` is an involution. -/
theorem quadRefl_mul_self : quadRefl * quadRefl = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [quadRefl, Matrix.mul_apply, Fin.sum_univ_four]

/-- The Berggren-type shift attached to a quadruple. -/
def qk (a b c d : ℤ) : ℤ := a + b + c - d

/-- The reflection acts on a quadruple by subtracting `k = a+b+c−d` from every coordinate. -/
theorem quadRefl_mulVec (a b c d : ℤ) :
    quadRefl *ᵥ ![a, b, c, d] =
      ![a - qk a b c d, b - qk a b c d, c - qk a b c d, d - qk a b c d] := by
  ext i
  fin_cases i <;>
    simp [quadRefl, qk, Matrix.mulVec, dotProduct, Fin.sum_univ_four] <;> ring

/-! ## Invariance of the quadruple relation and of the content -/

theorem qmove_pyth {a b c d : ℤ} (h : IsPythQuadruple a b c d) :
    IsPythQuadruple (a - qk a b c d) (b - qk a b c d) (c - qk a b c d) (d - qk a b c d) := by
  unfold IsPythQuadruple qk at *
  linear_combination h

/-- The reflection move is an involution on quadruples. -/
theorem qk_move (a b c d : ℤ) :
    qk (a - qk a b c d) (b - qk a b c d) (c - qk a b c d) (d - qk a b c d) = -qk a b c d := by
  unfold qk; ring

/-- The content (gcd) of a quadruple. -/
def content (a b c d : ℤ) : ℕ := Int.gcd (Int.gcd (Int.gcd a b) c) d

/-- A primitive Pythagorean quadruple. -/
def IsPrimQuad (a b c d : ℤ) : Prop := IsPythQuadruple a b c d ∧ content a b c d = 1

theorem content_dvd_fst (a b c d : ℤ) : (content a b c d : ℤ) ∣ a :=
  dvd_trans (dvd_trans (Int.gcd_dvd_left _ _) (Int.gcd_dvd_left _ _)) (Int.gcd_dvd_left _ _)

theorem content_dvd_snd (a b c d : ℤ) : (content a b c d : ℤ) ∣ b :=
  dvd_trans (dvd_trans (Int.gcd_dvd_left _ _) (Int.gcd_dvd_left _ _)) (Int.gcd_dvd_right _ _)

theorem content_dvd_thd (a b c d : ℤ) : (content a b c d : ℤ) ∣ c :=
  dvd_trans (Int.gcd_dvd_left _ _) (Int.gcd_dvd_right _ _)

theorem content_dvd_fth (a b c d : ℤ) : (content a b c d : ℤ) ∣ d := Int.gcd_dvd_right _ _

theorem dvd_content {g : ℕ} {a b c d : ℤ} (h1 : (g : ℤ) ∣ a) (h2 : (g : ℤ) ∣ b)
    (h3 : (g : ℤ) ∣ c) (h4 : (g : ℤ) ∣ d) : g ∣ content a b c d :=
  Int.dvd_gcd (Int.natCast_dvd_natCast.mpr
    (Int.dvd_gcd (Int.natCast_dvd_natCast.mpr (Int.dvd_gcd h1 h2)) h3)) h4

/-- The content divides the content of the moved quadruple. -/
theorem content_dvd_content_move (a b c d : ℤ) :
    content a b c d ∣
      content (a - qk a b c d) (b - qk a b c d) (c - qk a b c d) (d - qk a b c d) := by
  have hx := content_dvd_fst a b c d
  have hy := content_dvd_snd a b c d
  have hz := content_dvd_thd a b c d
  have hw := content_dvd_fth a b c d
  have hkk : (content a b c d : ℤ) ∣ qk a b c d := by
    unfold qk; exact dvd_sub (dvd_add (dvd_add hx hy) hz) hw
  exact dvd_content (dvd_sub hx hkk) (dvd_sub hy hkk) (dvd_sub hz hkk) (dvd_sub hw hkk)

/-- The content is invariant under the reflection move. -/
theorem content_move (a b c d : ℤ) :
    content (a - qk a b c d) (b - qk a b c d) (c - qk a b c d) (d - qk a b c d) =
      content a b c d := by
  have h1 := content_dvd_content_move a b c d
  have h2 := content_dvd_content_move (a - qk a b c d) (b - qk a b c d) (c - qk a b c d)
    (d - qk a b c d)
  rw [qk_move a b c d] at h2
  have e : ∀ x : ℤ, x - qk a b c d - -qk a b c d = x := by intro x; ring
  simp only [e] at h2
  exact Nat.dvd_antisymm h2 h1

theorem content_neg (a b c d : ℤ) : content (-a) b c d = content a b c d := by
  simp [content, Int.neg_gcd]

theorem content_swap12 (a b c d : ℤ) : content b a c d = content a b c d := by
  simp [content, Int.gcd_comm a b]

theorem content_swap23 (a b c d : ℤ) : content a c b d = content a b c d := by
  simp only [content]
  congr 1
  rw [Int.gcd_assoc, Int.gcd_assoc, Int.gcd_comm c b]

theorem content_abs3 (a b c d : ℤ) : content |a| |b| |c| d = content a b c d := by
  simp [content, Int.gcd, Int.natAbs_abs]

theorem content_zero_zero (t : ℤ) : content 0 0 t t = t.natAbs := by
  simp [content, Int.gcd, Int.natAbs_abs]

/-! ## The reachability relation -/

/-- Reachability from the root `(1,0,0,1)` under the group generated by the all-ones reflection,
the sign change of the first coordinate, and the transpositions of the space coordinates.
This is the dimension-three analogue of the Berggren tree. -/
inductive Reach : ℤ → ℤ → ℤ → ℤ → Prop
  | root : Reach 1 0 0 1
  | neg {a b c d : ℤ} : Reach a b c d → Reach (-a) b c d
  | swap12 {a b c d : ℤ} : Reach a b c d → Reach b a c d
  | swap23 {a b c d : ℤ} : Reach a b c d → Reach a c b d
  | refl {a b c d : ℤ} : Reach a b c d →
      Reach (a - qk a b c d) (b - qk a b c d) (c - qk a b c d) (d - qk a b c d)

theorem Reach.neg2 {a b c d : ℤ} (h : Reach a b c d) : Reach a (-b) c d :=
  ((h.swap12).neg).swap12

theorem Reach.neg3 {a b c d : ℤ} (h : Reach a b c d) : Reach a b (-c) d :=
  ((h.swap23).neg2).swap23

theorem reach_of_abs {a b c d : ℤ} (h : Reach |a| |b| |c| d) : Reach a b c d := by
  rcases abs_choice a with ha | ha <;> rcases abs_choice b with hb | hb <;>
    rcases abs_choice c with hc | hc <;> rw [ha, hb, hc] at h <;>
    first
      | exact h
      | simpa using h.neg
      | simpa using h.neg2
      | simpa using h.neg3
      | simpa using h.neg.neg2
      | simpa using h.neg.neg3
      | simpa using h.neg2.neg3
      | simpa using h.neg.neg2.neg3

/-- **Soundness**: every reachable quadruple is a primitive Pythagorean quadruple. -/
theorem reach_sound {a b c d : ℤ} (h : Reach a b c d) : IsPrimQuad a b c d := by
  induction h with
  | root => exact ⟨by unfold IsPythQuadruple; ring, by decide⟩
  | neg h ih =>
      obtain ⟨h1, h2⟩ := ih
      refine ⟨?_, by rw [content_neg]; exact h2⟩
      unfold IsPythQuadruple at h1 ⊢; linear_combination h1
  | swap12 h ih =>
      obtain ⟨h1, h2⟩ := ih
      refine ⟨?_, by rw [content_swap12]; exact h2⟩
      unfold IsPythQuadruple at h1 ⊢; linear_combination h1
  | swap23 h ih =>
      obtain ⟨h1, h2⟩ := ih
      refine ⟨?_, by rw [content_swap23]; exact h2⟩
      unfold IsPythQuadruple at h1 ⊢; linear_combination h1
  | refl h ih => exact ⟨qmove_pyth ih.1, by rw [content_move]; exact ih.2⟩

/-! ## Descent -/

theorem height_one_aux {t d : ℤ} (ht : t = d) (hd : 0 < d) (h : content 0 0 t d = 1) : d = 1 := by
  subst ht
  rw [content_zero_zero] at h
  omega

/-- If all three pairwise products of the space coordinates vanish, primitivity forces the
degenerate quadruple `(1,0,0,1)` up to permutation, i.e. height one. -/
theorem height_one_of_degenerate {a b c d : ℤ} (ha : 0 ≤ a) (hb : 0 ≤ b) (hc : 0 ≤ c) (hd : 0 < d)
    (h : IsPythQuadruple a b c d) (hab : a * b = 0) (hbc : b * c = 0) (hac : a * c = 0)
    (hcont : content a b c d = 1) : d = 1 := by
  unfold IsPythQuadruple at h
  have key : ∀ t : ℤ, 0 ≤ t → t ^ 2 = d ^ 2 → t = d := by
    intro t ht h2; nlinarith
  rcases mul_eq_zero.mp hab with ha0 | hb0
  · rcases mul_eq_zero.mp hbc with hb0 | hc0
    · -- a = 0, b = 0, so c = d
      have hcd : c = d := key c hc (by rw [ha0, hb0] at h; linarith)
      refine height_one_aux hcd hd ?_
      rw [ha0, hb0] at hcont; exact hcont
    · -- a = 0, c = 0, so b = d
      have hbd : b = d := key b hb (by rw [ha0, hc0] at h; linarith)
      refine height_one_aux hbd hd ?_
      rw [ha0, hc0] at hcont
      rw [content_swap23]; exact hcont
  · rcases mul_eq_zero.mp hac with ha0 | hc0
    · -- b = 0, a = 0, so c = d
      have hcd : c = d := key c hc (by rw [ha0, hb0] at h; linarith)
      refine height_one_aux hcd hd ?_
      rw [ha0, hb0] at hcont; exact hcont
    · -- b = 0, c = 0, so a = d
      have had : a = d := key a ha (by rw [hb0, hc0] at h; linarith)
      refine height_one_aux had hd ?_
      rw [hb0, hc0] at hcont
      rw [content_swap23, content_swap12]; exact hcont

/-- The shift `k = a+b+c−d` is strictly positive for a primitive quadruple of height `> 1`. -/
theorem qk_pos {a b c d : ℤ} (ha : 0 ≤ a) (hb : 0 ≤ b) (hc : 0 ≤ c) (hd : 1 < d)
    (h : IsPythQuadruple a b c d) (hcont : content a b c d = 1) : 0 < qk a b c d := by
  unfold qk
  by_contra hcon
  push_neg at hcon
  have hpyth := h
  unfold IsPythQuadruple at hpyth
  have hsum : a + b + c ≤ d := by linarith
  have hab : a * b = 0 := by nlinarith [mul_nonneg ha hb, mul_nonneg hb hc, mul_nonneg ha hc]
  have hbc : b * c = 0 := by nlinarith [mul_nonneg ha hb, mul_nonneg hb hc, mul_nonneg ha hc]
  have hac : a * c = 0 := by nlinarith [mul_nonneg ha hb, mul_nonneg hb hc, mul_nonneg ha hc]
  have := height_one_of_degenerate ha hb hc (by linarith) h hab hbc hac hcont
  omega

/-- The descended height `d − k = 2d − (a+b+c)` is still positive. -/
theorem sub_qk_pos {a b c d : ℤ} (ha : 0 ≤ a) (hb : 0 ≤ b) (hc : 0 ≤ c) (hd : 0 < d)
    (h : IsPythQuadruple a b c d) : 0 < d - qk a b c d := by
  unfold IsPythQuadruple at h
  unfold qk
  nlinarith [sq_nonneg (a - b), sq_nonneg (b - c), sq_nonneg (a - c), sq_nonneg (a + b + c - 2 * d)]

/-- **Completeness / connectivity.** Every primitive Pythagorean quadruple with non-negative
space coordinates and positive height is reachable from the root `(1,0,0,1)`.  This is the
three-dimensional analogue of Berggren's theorem. -/
theorem reach_of_prim : ∀ (N : ℕ) (a b c d : ℤ), d.toNat ≤ N → 0 ≤ a → 0 ≤ b → 0 ≤ c → 0 < d →
    IsPythQuadruple a b c d → content a b c d = 1 → Reach a b c d := by
  intro N
  induction N with
  | zero => intro a b c d hN _ _ _ hd _ _; omega
  | succ N ih =>
      intro a b c d hN ha hb hc hd h hcont
      rcases eq_or_lt_of_le (show (1 : ℤ) ≤ d by omega) with hd1 | hd1
      · -- base case: height one
        subst hd1
        have h' : a ^ 2 + b ^ 2 + c ^ 2 = 1 := by unfold IsPythQuadruple at h; linarith [h]
        have ha1 : a ≤ 1 := by nlinarith
        have hb1 : b ≤ 1 := by nlinarith
        have hc1 : c ≤ 1 := by nlinarith
        have hcase : (a = 1 ∧ b = 0 ∧ c = 0) ∨ (a = 0 ∧ b = 1 ∧ c = 0) ∨
            (a = 0 ∧ b = 0 ∧ c = 1) := by
          interval_cases a <;> interval_cases b <;> interval_cases c <;> simp_all
        rcases hcase with ⟨rfl, rfl, rfl⟩ | ⟨rfl, rfl, rfl⟩ | ⟨rfl, rfl, rfl⟩
        · exact Reach.root
        · exact Reach.root.swap12
        · exact Reach.root.swap12.swap23
      · -- descent step
        have hkpos : 0 < qk a b c d := qk_pos ha hb hc hd1 h hcont
        have hdk : 0 < d - qk a b c d := sub_qk_pos ha hb hc hd h
        have hmove : IsPythQuadruple (a - qk a b c d) (b - qk a b c d) (c - qk a b c d)
            (d - qk a b c d) := qmove_pyth h
        have habs : IsPythQuadruple |a - qk a b c d| |b - qk a b c d| |c - qk a b c d|
            (d - qk a b c d) := by
          unfold IsPythQuadruple at hmove ⊢
          rw [sq_abs, sq_abs, sq_abs]; exact hmove
        have hc2 : content |a - qk a b c d| |b - qk a b c d| |c - qk a b c d|
            (d - qk a b c d) = 1 := by
          rw [content_abs3, content_move]; exact hcont
        have hsmall : (d - qk a b c d).toNat ≤ N := by omega
        have hR := ih |a - qk a b c d| |b - qk a b c d| |c - qk a b c d| (d - qk a b c d)
          hsmall (abs_nonneg _) (abs_nonneg _) (abs_nonneg _) hdk habs hc2
        have hback := (reach_of_abs hR).refl
        rw [qk_move a b c d] at hback
        have e : ∀ x : ℤ, x - qk a b c d - -qk a b c d = x := by intro x; ring
        simp only [e] at hback
        exact hback

/-- Reachability characterises primitive Pythagorean quadruples in the positive cone. -/
theorem reach_iff_prim {a b c d : ℤ} (ha : 0 ≤ a) (hb : 0 ≤ b) (hc : 0 ≤ c) (hd : 0 < d) :
    Reach a b c d ↔ IsPrimQuad a b c d := by
  refine ⟨reach_sound, ?_⟩
  rintro ⟨h1, h2⟩
  exact reach_of_prim d.toNat a b c d le_rfl ha hb hc hd h1 h2

end HigherPythagorean