/-
# EML Universal Approximation via a Single Exponential Feature

This file is a research contribution to the **EML (Exponential–Multiplicative–Logarithmic)
universal approximation** programme. The abstract Stone–Weierstrass machinery in
`EML.StoneWeierstrassApprox` reduces uniform density of an EML-generated subalgebra of
`C(X, ℝ)` to the *point-separation* property. Here we make that programme concrete by
isolating the smallest EML primitive that already forces density:

> A **single** injective continuous "feature" `g : C(X, ℝ)` — in particular the
> exponential primitive `exp ∘ g` — generates (as an `ℝ`-subalgebra under `+`, `×`,
> scalars) a uniformly dense subspace of `C(X, ℝ)` on every compact space `X`.

In ML terms: one injective exponential neuron, followed by arbitrary polynomial
read-out, is a universal approximator. Specialised to `X = [a,b] ⊆ ℝ`, this says the
**exponential polynomials** `span {e^{n x} : n ∈ ℕ}` are uniformly dense in `C([a,b], ℝ)`.

## Main results

* `separatesPoints_of_injective_mem` — a subalgebra containing one injective function
  separates points.
* `separatesPoints_adjoin_of_separatesPoints` — the subalgebra generated by a
  point-separating *family* separates points.
* `adjoin_singleton_dense` — `Algebra.adjoin ℝ {g}` is dense when `g` is injective.
* `adjoin_singleton_approx` — the ε-approximation form of the above.
* `expCM`, `injective_expCM_comp` — the exponential feature and its injectivity.
* `eml_exp_feature_dense`, `eml_exp_feature_approx` — the single-exponential-feature
  universal approximation theorem and its ε-form.
* `exponentialPolynomials_dense_Icc`, `exponentialPolynomials_approx_Icc` — the
  classical corollary on a compact interval.

-- !-- Lab Notes -- !--
HYPOTHESIS (H1). Stone–Weierstrass density of an EML class should not require the full
expressive power of the EML term algebra; a *single* injective generator ought to
suffice, because adjoining it already produces a point-separating subalgebra.

EXPERIMENT. We reduced "subalgebra A separates points" to "A contains one injective
member" (`separatesPoints_of_injective_mem`). The proof is one line: if `x ≠ y` then
injectivity gives `g x ≠ g y`, and `g ∈ A` witnesses separation. Outcome: H1 confirmed.

INSIGHT. The bottleneck primitive is *injectivity of a feature*, not the richness of
the function class. `exp` is injective on all of `ℝ`, so `exp ∘ g` is injective whenever
`g` is, and `Algebra.adjoin ℝ {exp ∘ g}` is automatically dense. This is strictly
sharper than the syntactic EML route: we never enumerate `+ / × / exp` terms.

FAILURE ANALYSIS. Early attempt tried `Set.SeparatesPoints.mono`; it does not exist in
Mathlib v4.28.0, so the family version `separatesPoints_adjoin_of_separatesPoints` is
proved by unfolding the existential and reusing `Algebra.subset_adjoin`.

CROSS-CHECK. `subalgebra_topologicalClosure_eq_top_of_separatesPoints` needs only
`CompactSpace X` (no `T2Space`), so the interval corollary needs no Hausdorff hypothesis
beyond what `Set.Icc` already provides as a subspace of `ℝ`.
-/
import Mathlib
import EML.StoneWeierstrassApprox

noncomputable section

open ContinuousMap Real Topology

namespace EMLExpFeature

/-! ## Section 1: Point separation from a single injective generator -/

variable {X : Type*} [TopologicalSpace X]

/-- A subalgebra of `C(X, ℝ)` that contains an injective continuous function
separates points. -/
theorem separatesPoints_of_injective_mem
    (A : Subalgebra ℝ C(X, ℝ)) (g : C(X, ℝ)) (hg : g ∈ A)
    (hinj : Function.Injective g) :
    A.SeparatesPoints := by
  intro x y hxy
  exact ⟨g, ⟨g, hg, rfl⟩, fun h => hxy (hinj h)⟩

/-- If a family `S ⊆ C(X, ℝ)` separates points, so does the subalgebra it generates. -/
theorem separatesPoints_adjoin_of_separatesPoints
    (S : Set C(X, ℝ))
    (hS : ((fun f : C(X, ℝ) => (f : X → ℝ)) '' S).SeparatesPoints) :
    (Algebra.adjoin ℝ S).SeparatesPoints := by
  intro x y hxy
  obtain ⟨f, ⟨g, hgS, rfl⟩, hfxy⟩ := hS hxy
  exact ⟨(g : X → ℝ), ⟨g, Algebra.subset_adjoin hgS, rfl⟩, hfxy⟩

/-! ## Section 2: Density of the subalgebra generated by one injective function -/

variable [CompactSpace X]

/-- **One injective generator is universal.**
For compact `X`, the subalgebra generated by a single injective continuous function
is uniformly dense in `C(X, ℝ)`. -/
theorem adjoin_singleton_dense
    (g : C(X, ℝ)) (hinj : Function.Injective g) :
    (Algebra.adjoin ℝ {g}).topologicalClosure = ⊤ :=
  ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints _
    (separatesPoints_of_injective_mem _ g (Algebra.self_mem_adjoin_singleton ℝ g) hinj)

/-- ε-approximation form of `adjoin_singleton_dense`. -/
theorem adjoin_singleton_approx
    (g : C(X, ℝ)) (hinj : Function.Injective g)
    (f : C(X, ℝ)) {ε : ℝ} (hε : 0 < ε) :
    ∃ p : Algebra.adjoin ℝ {g}, ‖(p : C(X, ℝ)) - f‖ < ε :=
  eml_exists_uniform_approx _
    (separatesPoints_of_injective_mem _ g (Algebra.self_mem_adjoin_singleton ℝ g) hinj) f hε

/-! ## Section 3: The exponential feature -/

/-- The exponential primitive as a continuous map `ℝ → ℝ`. -/
def expCM : C(ℝ, ℝ) := ⟨Real.exp, Real.continuous_exp⟩

@[simp] theorem expCM_apply (x : ℝ) : expCM x = Real.exp x := rfl

omit [CompactSpace X] in
/-- Composing the (injective) exponential with an injective feature stays injective. -/
theorem injective_expCM_comp (g : C(X, ℝ)) (hinj : Function.Injective g) :
    Function.Injective (expCM.comp g) := by
  intro x y h
  exact hinj (Real.exp_injective (by simpa [expCM, ContinuousMap.comp_apply] using h))

/-- **Single exponential feature universal approximation.**
For compact `X` and any injective feature `g : C(X, ℝ)`, the subalgebra generated by
the single exponential feature `exp ∘ g` is uniformly dense in `C(X, ℝ)`. -/
theorem eml_exp_feature_dense (g : C(X, ℝ)) (hinj : Function.Injective g) :
    (Algebra.adjoin ℝ {expCM.comp g}).topologicalClosure = ⊤ :=
  adjoin_singleton_dense _ (injective_expCM_comp g hinj)

/-- ε-form of `eml_exp_feature_dense`: every continuous function is uniformly
approximated by a polynomial in `exp ∘ g`. -/
theorem eml_exp_feature_approx (g : C(X, ℝ)) (hinj : Function.Injective g)
    (f : C(X, ℝ)) {ε : ℝ} (hε : 0 < ε) :
    ∃ p : Algebra.adjoin ℝ {expCM.comp g}, ‖(p : C(X, ℝ)) - f‖ < ε :=
  adjoin_singleton_approx _ (injective_expCM_comp g hinj) f hε

/-! ## Section 4: Concrete corollary on a compact interval -/

/-- The coordinate (inclusion) feature on a compact interval `[a,b] ⊆ ℝ`. -/
def iccCoord (a b : ℝ) : C(Set.Icc a b, ℝ) :=
  ⟨fun x => (x : ℝ), continuous_subtype_val⟩

theorem injective_iccCoord (a b : ℝ) : Function.Injective (iccCoord a b) := by
  intro x y h
  exact Subtype.ext (by simpa [iccCoord] using h)

/-- **Exponential polynomials are dense on `[a, b]`.**
The subalgebra generated by `x ↦ exp x` is uniformly dense in `C([a,b], ℝ)`.
Equivalently, finite real linear combinations of `e^{n x}` (`n ∈ ℕ`) approximate
every continuous function on a compact interval. -/
theorem exponentialPolynomials_dense_Icc (a b : ℝ) :
    (Algebra.adjoin ℝ {expCM.comp (iccCoord a b)}).topologicalClosure = ⊤ :=
  eml_exp_feature_dense (iccCoord a b) (injective_iccCoord a b)

/-- ε-form on a compact interval. -/
theorem exponentialPolynomials_approx_Icc (a b : ℝ)
    (f : C(Set.Icc a b, ℝ)) {ε : ℝ} (hε : 0 < ε) :
    ∃ p : Algebra.adjoin ℝ {expCM.comp (iccCoord a b)}, ‖(p : C(Set.Icc a b, ℝ)) - f‖ < ε :=
  eml_exp_feature_approx (iccCoord a b) (injective_iccCoord a b) f hε

/-! ## Section 5: Linear span refinement — finite combinations of `e^{k·g(x)}` -/

-- !-- Lab Notes -- !--
-- HYPOTHESIS (H3). Density should already hold for the *linear span* of the exponential
-- monomials `{ (exp∘g)^k : k ∈ ℕ }`, i.e. one does not need genuine products of distinct
-- features, only powers. EXPERIMENT: `Algebra.adjoin_eq_span` rewrites the generated
-- subalgebra as the submodule span of the multiplicative closure, which for a single
-- generator is exactly its powers (`Submonoid.powers_eq_closure`). Thus the adjoin
-- carrier and the span-of-powers carrier coincide as sets, transporting density.
-- OUTCOME: H3 confirmed — the strict exponential polynomials `∑ cₖ e^{k g(x)}` are dense.

omit [CompactSpace X] in
/-- The carrier of `Algebra.adjoin ℝ {h}` is exactly the linear span of the powers of `h`. -/
theorem adjoin_singleton_coe_eq_span_pow (h : C(X, ℝ)) :
    (Submodule.span ℝ (Set.range (fun k : ℕ => h ^ k)) : Set C(X, ℝ))
      = (Algebra.adjoin ℝ {h} : Set C(X, ℝ)) := by
  have hrange : (Set.range fun k : ℕ => h ^ k)
      = (↑(Submonoid.closure ({h} : Set C(X, ℝ))) : Set _) := by
    rw [← Submonoid.powers_eq_closure]; ext x; simp [Submonoid.mem_powers_iff, eq_comm]
  rw [hrange, ← Algebra.adjoin_eq_span ℝ ({h} : Set C(X, ℝ))]
  rfl

/-- A subalgebra whose topological closure is `⊤` has dense carrier. -/
theorem dense_of_topologicalClosure_eq_top (A : Subalgebra ℝ C(X, ℝ))
    (hA : A.topologicalClosure = ⊤) : Dense ((A : Set C(X, ℝ))) := by
  rw [dense_iff_closure_eq, ← Subalgebra.topologicalClosure_coe, hA]; rfl

omit [CompactSpace X] in
/-- Pointwise value of an exponential monomial: `((exp ∘ g)^k) x = exp (k · g x)`. -/
theorem expCM_comp_pow_apply (g : C(X, ℝ)) (k : ℕ) (x : X) :
    ((expCM.comp g) ^ k) x = Real.exp (k * g x) := by
  simp [expCM, ContinuousMap.pow_apply, ContinuousMap.comp_apply, ← Real.exp_nat_mul]

/-- **Exponential polynomials (linear span form) are dense.**
For compact `X` and injective `g`, the linear span of the exponential monomials
`{ (exp ∘ g)^k : k ∈ ℕ }` is uniformly dense in `C(X, ℝ)`. Equivalently, finite real
linear combinations `∑ cₖ e^{k·g(x)}` approximate every continuous function. -/
theorem exp_monomials_span_dense (g : C(X, ℝ)) (hinj : Function.Injective g) :
    Dense ((Submodule.span ℝ (Set.range (fun k : ℕ => (expCM.comp g) ^ k)) : Set C(X, ℝ))) := by
  rw [adjoin_singleton_coe_eq_span_pow]
  exact dense_of_topologicalClosure_eq_top _ (eml_exp_feature_dense g hinj)

end EMLExpFeature

end