/-
# EML Interpolation Theory: The Monotone Separation Property

The Stone–Weierstrass route to EML universal approximation needs one concrete
ingredient: a single EML function that **separates points** of a compact set.

The mission proposes `g(t) = exp(a)·log(b·t + c)`. This file proves that for
`a, b > 0` (and `c` large enough that `b·t + c > 0` on the domain) this `g` is
*strictly monotone*, hence injective, hence separating. On any interval `[lo, hi]`
the explicit choice `a = 0, b = 1, c = 1 − lo` works: `g(t) = log(t + 1 − lo)`.

We then feed this single separating EML function into the abstract Stone–Weierstrass
machinery of `EML.StoneWeierstrassApprox` to obtain density of the EML-generated
subalgebra in `C([lo,hi], ℝ)`.

## Main results
- `emlSep_strictMonoOn`: `g(t) = exp(a)·log(b·t + c)` is strictly increasing on
  `{t | 0 < b·t + c}` when `a` is arbitrary and `b > 0`.
- `emlSep_separates`: distinct admissible points give distinct values.
- `emlSepCM_separatesPoints`: the subalgebra generated by the single EML function
  `t ↦ log(t + 1 − lo)` separates points of `[lo, hi]`.
- `eml_adjoin_dense_on_Icc`: that subalgebra is uniformly dense in `C([lo,hi], ℝ)`.
-/
import Mathlib
import EML.StoneWeierstrassApprox

noncomputable section

open Real

/-- The candidate EML separating function `g(t) = exp(a)·log(b·t + c)`. -/
def emlSep (a b c t : ℝ) : ℝ := Real.exp a * Real.log (b * t + c)

/-
**Strict monotonicity.** For `b > 0`, the EML function `t ↦ exp(a)·log(b·t + c)`
is strictly increasing on the set where its argument is positive.
-/
theorem emlSep_strictMonoOn (a b c : ℝ) (hb : 0 < b) :
    StrictMonoOn (emlSep a b c) {t : ℝ | 0 < b * t + c} := by
  intro x hx y hy hxy;
  exact mul_lt_mul_of_pos_left ( Real.log_lt_log ( by linarith [ Set.mem_setOf.mp hx ] ) ( by nlinarith [ Set.mem_setOf.mp hx, Set.mem_setOf.mp hy ] ) ) ( Real.exp_pos a )

/-
**Separation property.** Distinct points `x ≠ y` with positive arguments are
sent to distinct values by the EML function `g(t) = exp(a)·log(b·t + c)` when
`b > 0`. This is the Stone–Weierstrass separation hypothesis, realised by a single
EML primitive.
-/
theorem emlSep_separates (a b c : ℝ) (hb : 0 < b) {x y : ℝ}
    (hx : 0 < b * x + c) (hy : 0 < b * y + c) (hxy : x ≠ y) :
    emlSep a b c x ≠ emlSep a b c y := by
  exact fun h => hxy <| StrictMonoOn.injOn ( emlSep_strictMonoOn a b c hb ) hx hy h

/-
On `[lo, hi]` the explicit normalisation `a = 0, b = 1, c = 1 − lo` makes the
argument `t + 1 − lo ≥ 1 > 0`, so the EML function separates the interval.
-/
theorem emlSep_separates_Icc (lo hi : ℝ) {x y : ℝ}
    (hx : x ∈ Set.Icc lo hi) (hy : y ∈ Set.Icc lo hi) (hxy : x ≠ y) :
    emlSep 0 1 (1 - lo) x ≠ emlSep 0 1 (1 - lo) y := by
  apply emlSep_separates;
  · norm_num;
  · linarith [ hx.1, hx.2 ];
  · linarith [ hx.1, hx.2, hy.1, hy.2 ];
  · assumption

/-
The single EML separating function as an element of `C([lo,hi], ℝ)`:
`g(t) = log(t + 1 − lo)`.
-/
def emlSepCM (lo hi : ℝ) : C(Set.Icc lo hi, ℝ) :=
  ⟨fun t => Real.log ((t : ℝ) + 1 - lo), by
    exact continuous_iff_continuousAt.mpr fun x => ContinuousAt.log ( ContinuousAt.sub ( ContinuousAt.add ( continuous_subtype_val.continuousAt ) continuousAt_const ) continuousAt_const ) ( by linarith [ x.2.1 ] )⟩

/-
**Separation in `C([lo,hi], ℝ)`.** The subalgebra generated by the single EML
function `t ↦ log(t + 1 − lo)` separates the points of `[lo, hi]`.
-/
theorem emlSepCM_separatesPoints (lo hi : ℝ) :
    (Algebra.adjoin ℝ {emlSepCM lo hi}).SeparatesPoints := by
  intro x y hxy;
  refine' ⟨ _, ⟨ _, Algebra.subset_adjoin <| Set.mem_singleton _, rfl ⟩, _ ⟩;
  convert emlSep_separates_Icc lo hi x.2 y.2 _ using 1;
  · unfold emlSepCM emlSep; norm_num; congr 1; ring;
  · unfold emlSepCM emlSep; norm_num; congr 1; ring;
  · exact fun h => hxy <| Subtype.ext h

/-- **EML density on an interval.** The subalgebra generated by the single EML
function `t ↦ log(t + 1 − lo)` is uniformly dense in `C([lo,hi], ℝ)`.

This combines the monotone separation property with the abstract Stone–Weierstrass
theorem `eml_topologicalClosure_eq_top_of_separatesPoints` from
`EML.StoneWeierstrassApprox`. -/
theorem eml_adjoin_dense_on_Icc (lo hi : ℝ) :
    (Algebra.adjoin ℝ {emlSepCM lo hi}).topologicalClosure = ⊤ :=
  eml_topologicalClosure_eq_top_of_separatesPoints _ (emlSepCM_separatesPoints lo hi)

/-
-- !-- Lab Notes -- !--

## Hypothesis (Hypothesizer)
Mission claim: `g(t) = exp(a)·log(b·t + c)` separates points for suitable `a,b,c`
because it is strictly monotone for `a, b > 0`. Conjecture this is exactly the
Stone–Weierstrass separation hypothesis, and that a single such EML primitive
suffices to generate a dense subalgebra of `C(K, ℝ)`.

## Experiment (Experimenter)
`g` is a composition `t ↦ b·t + c ↦ log(·) ↦ exp(a)·(·)`. With `b > 0` the affine
part is strictly increasing; `log` is strictly increasing on `(0,∞)`; multiplying
by `exp(a) > 0` preserves strict monotonicity. On `[lo,hi]`, taking `c = 1 − lo`
makes the argument `≥ 1`, so positivity is automatic.

## Analysis (Analyst)
Strict monotonicity ⇒ injectivity ⇒ separation is the clean structural pattern.
The subtle point is *positivity of the argument*: `log` is only monotone on the
positives, so the domain restriction `0 < b·t + c` is load-bearing. The explicit
shift `c = 1 − lo` discharges it uniformly on the interval. This is "true and the
right definition" — no counterexample, the hypotheses are minimal.

## Critique (Critic)
- Not trivial: uses `StrictMonoOn`, `Real.log` monotonicity on positives, and the
  Stone–Weierstrass theorem to pass from separation to density.
- Hidden assumption surfaced: without the positivity domain `g` is *not* monotone
  (e.g. near the pole of `log`), so the guarded statement is essential.
- Genuinely extends the catalog: `eml_adjoin_dense_on_Icc` instantiates the
  abstract `eml_topologicalClosure_eq_top_of_separatesPoints` with a *concrete*
  single-generator EML algebra.

## Synthesis (PI)
A single strictly-monotone EML function suffices for Stone–Weierstrass separation
and therefore density. Combined with `EML.QuadraticApproxRate` (explicit rate for
`x²`), this turns the existential universal-approximation guarantee into a
constructive one with separation by an explicit primitive.
-/
end