import Mathlib

/-!
# The linking-form half of the embedding obstruction for closed three-manifolds

A Phase-A conjecture proposes that a closed connected orientable smooth
three-manifold `Y` embeds smoothly in `S⁴` exactly when the two complementary
regions carry compatible intersection pairings and linking forms.  One half of
that package is purely algebraic and *is* provable: an embedding
`Y ↪ S⁴` splits `S⁴` into `X₁ ∪_Y X₂`, and Alexander duality forces the linking
form of `Y` on the torsion of `H₁(Y; ℤ)` to be **metabolic**, i.e. to admit a
self-annihilating subgroup (`H = H^⊥`).

This file formalizes that algebraic obstruction for the cyclic linking forms
`ℓ_{n,q}(x, y) = q x y / n  (mod 1)` on `ℤ/n`, which are exactly the linking
forms of the lens spaces `L(n, q)`.  The main theorem is

  `exists_metabolizer_iff_isSquare` :
    `ℓ_{n,q}` admits a metabolizer  ↔  `n` is a perfect square,

for every `q` coprime to `n`.  Combined with the (classical, not formalized
here) topological input that an embedded three-manifold has metabolic linking
form, this yields the concrete obstruction `L(n, q)` does not embed in `S⁴`
whenever `n` is not a perfect square — for instance `L(3, 1)`.

The last section records the companion "square order" shadow of Hantzsche's
theorem: a finite abelian group of the form `G × G` has square order, so `ℤ/3`
is not of that shape.

-- !-- Lab Notes -- !--
Hypothesis (Hypothesizer):
The coupled Alexander-duality/linking-form obstruction should have a fully
algebraic core that is testable on lens spaces: metabolicity of the cyclic
linking form.

Experiment (Experimenter):
Subgroups of `ℤ/n` are the divisor subgroups `H_d = { x : d ∣ x }` with `d ∣ n`;
the linking form pairs `H_d` with `H_{n/d}`.  Computing the annihilator gives
`H_d^⊥ = H_{n/d}` (using `gcd(q,n) = 1`), so `H_d = H_d^⊥` iff `d = n / d` iff
`n = d²`.  Sample outputs: `n = 4` has metabolizer `d = 2`; `n = 3, 5, 6, 7, 8`
have none; `n = 9` has `d = 3`.

Analysis (Analyst):
The obstruction is exactly "`n` is a perfect square", uniform in the second lens
parameter `q`; in particular the finer arithmetic of `q` is invisible to this
piece of the coupled obstruction, which shows that the conjecture's
"complementary conditions" cannot be reduced to the linking form alone (e.g.
`L(4,1)` passes this test).  This is a structural pattern: the linking form sees
`|H₁|` up to squares, and the intersection pairing must supply the rest.

Critique (Critic):
The topological input (Alexander duality forcing metabolicity) is *not* assumed
anywhere in the Lean statements — it is only used in the informal reading of the
corollaries; all formal results are theorems about finite cyclic linking forms.
The metabolizer quantifier ranges over *all* subgroups of `ℤ/n`, not just the
divisor subgroups, thanks to `Int.subgroup_cyclic`, so the negative results are
genuine.

Synthesis (Principal Investigator):
The algebraic core of the conjectured coupled obstruction is a clean square-order
criterion; combined with the classical topological input it rules out embeddings
of all lens spaces with non-square first homology.
-- !-- Lab Notes -- !--
-/

namespace LinkingObstruction

/-- The linking form `ℓ_{n,q}(x,y) = q x y / n (mod 1)` on `ℤ/n` vanishes on the
pair of integer representatives `x, y`. -/
def LinkVanishes (n q : ℕ) (x y : ℤ) : Prop := (n : ℤ) ∣ (q : ℤ) * x * y

/-- The subgroup of `ℤ/n` generated by `d`, described by its preimage in `ℤ`. -/
def divSubgroup (d : ℤ) : Set ℤ := {x | d ∣ x}

/-- The annihilator of a subgroup with respect to the linking form. -/
def linkPerp (n q : ℕ) (H : Set ℤ) : Set ℤ := {x | ∀ y ∈ H, LinkVanishes n q x y}

/-- A metabolizer (self-annihilating subgroup) for the linking form. -/
def IsMetabolizer (n q : ℕ) (H : Set ℤ) : Prop := H = linkPerp n q H

/-! ### Divisor subgroups -/

theorem divSubgroup_eq_iff {d e : ℤ} (hd : 0 < d) (he : 0 < e) :
    divSubgroup d = divSubgroup e ↔ d = e := by
  constructor
  · intro h
    have h1 : e ∣ d := by
      have : d ∈ divSubgroup e := by rw [← h]; exact dvd_refl d
      exact this
    have h2 : d ∣ e := by
      have : e ∈ divSubgroup d := by rw [h]; exact dvd_refl e
      exact this
    exact Int.dvd_antisymm hd.le he.le h2 h1
  · rintro rfl; rfl

/-- **Annihilator computation.**  For `d ∣ n` and `q` coprime to `n`, the linking
annihilator of the divisor subgroup `H_d` is `H_{n/d}`. -/
theorem linkPerp_divSubgroup (n q d : ℕ) (hd : 0 < d) (hdn : d ∣ n)
    (hq : Nat.Coprime q n) :
    linkPerp n q (divSubgroup (d : ℤ)) = divSubgroup ((n / d : ℕ) : ℤ) := by
  obtain ⟨e, he⟩ := hdn
  have hd0 : (d : ℤ) ≠ 0 := by exact_mod_cast hd.ne'
  have hne : n / d = e := by
    rw [he]; exact Nat.mul_div_cancel_left e hd
  have hnZ : (n : ℤ) = (d : ℤ) * (e : ℤ) := by exact_mod_cast he
  ext x
  simp only [linkPerp, divSubgroup, Set.mem_setOf_eq, LinkVanishes, hne]
  constructor
  · intro h
    have hx := h d (dvd_refl _)
    -- `n ∣ q * x * d` with `n = d * e` gives `e ∣ q * x`
    have h1 : (e : ℤ) ∣ (q : ℤ) * x := by
      rcases hx with ⟨c, hc⟩
      refine ⟨c, ?_⟩
      have : (d : ℤ) * ((q : ℤ) * x) = (d : ℤ) * ((e : ℤ) * c) := by
        rw [hnZ] at hc; linarith [hc]
      exact mul_left_cancel₀ hd0 this
    -- coprimality of `q` and `n` (hence with `e`) removes `q`
    have hqe : IsCoprime ((q : ℤ)) ((e : ℤ)) := by
      have hcop : Nat.Coprime q e := Nat.Coprime.coprime_dvd_right ⟨d, by rw [he]; ring⟩ hq
      exact Int.isCoprime_iff_gcd_eq_one.mpr hcop
    exact (hqe.symm.dvd_of_dvd_mul_left h1)
  · intro h y hy
    obtain ⟨c, rfl⟩ := h
    obtain ⟨k, rfl⟩ := hy
    refine ⟨(q : ℤ) * c * k, ?_⟩
    rw [hnZ]; ring

/-- **Metabolizer criterion for a divisor subgroup.** -/
theorem isMetabolizer_divSubgroup_iff (n q d : ℕ) (hn : 0 < n) (hd : 0 < d) (hdn : d ∣ n)
    (hq : Nat.Coprime q n) :
    IsMetabolizer n q (divSubgroup (d : ℤ)) ↔ n = d ^ 2 := by
  have hdpos : (0:ℤ) < (d : ℤ) := by exact_mod_cast hd
  have hdiv : 0 < n / d := Nat.div_pos (Nat.le_of_dvd hn hdn) hd
  have hdivpos : (0:ℤ) < ((n / d : ℕ) : ℤ) := by exact_mod_cast hdiv
  rw [IsMetabolizer, linkPerp_divSubgroup n q d hd hdn hq,
    divSubgroup_eq_iff hdpos hdivpos]
  constructor
  · intro h
    have h' : d = n / d := by exact_mod_cast h
    have := Nat.div_mul_cancel hdn
    nlinarith [this, h']
  · intro h
    have : n / d = d := by
      rw [h, pow_two]; exact Nat.mul_div_cancel_left d hd
    rw [this]

/-! ### All subgroups of `ℤ/n` -/

/-- Every subgroup of `ℤ/n` (a subgroup of `ℤ` containing `n`) is a divisor
subgroup `H_d` with `d ∣ n`, `d > 0`. -/
theorem exists_divSubgroup_of_subgroup (n : ℕ) (hn : 0 < n) (H : AddSubgroup ℤ)
    (hnH : (n : ℤ) ∈ H) :
    ∃ d : ℕ, 0 < d ∧ d ∣ n ∧ (H : Set ℤ) = divSubgroup (d : ℤ) := by
  obtain ⟨a, ha⟩ := Int.subgroup_cyclic H
  have hmem : ∀ x : ℤ, x ∈ H ↔ a ∣ x := by
    intro x
    rw [ha, AddSubgroup.mem_closure_singleton]
    constructor
    · rintro ⟨k, rfl⟩; exact ⟨k, by ring⟩
    · rintro ⟨k, rfl⟩; exact ⟨k, by ring⟩
  have han : a ∣ (n : ℤ) := (hmem _).mp hnH
  have ha0 : a ≠ 0 := by
    intro h
    rw [h] at han
    have : (n : ℤ) = 0 := zero_dvd_iff.mp han
    exact absurd (by exact_mod_cast this : n = 0) hn.ne'
  refine ⟨a.natAbs, Int.natAbs_pos.mpr ha0, ?_, ?_⟩
  · have : (a.natAbs : ℤ) ∣ (n : ℤ) := (Int.natAbs_dvd).mpr han
    exact_mod_cast this
  · ext x
    simp only [SetLike.mem_coe, hmem x, divSubgroup, Set.mem_setOf_eq, Int.natAbs_dvd]

/-! ### The main criterion -/

/-- **Main theorem.**  The cyclic linking form `ℓ_{n,q}` on `ℤ/n` (with `q` coprime
to `n`) admits a metabolizer if and only if `n` is a perfect square. -/
theorem exists_metabolizer_iff_isSquare (n q : ℕ) (hn : 0 < n) (hq : Nat.Coprime q n) :
    (∃ H : AddSubgroup ℤ, (n : ℤ) ∈ H ∧ IsMetabolizer n q (H : Set ℤ)) ↔ IsSquare n := by
  constructor
  · rintro ⟨H, hnH, hmeta⟩
    obtain ⟨d, hd, hdn, hHd⟩ := exists_divSubgroup_of_subgroup n hn H hnH
    rw [hHd] at hmeta
    have := (isMetabolizer_divSubgroup_iff n q d hn hd hdn hq).mp hmeta
    exact ⟨d, by rw [this]; ring⟩
  · rintro ⟨m, hm⟩
    have hm0 : 0 < m := by
      rcases Nat.eq_zero_or_pos m with h | h
      · rw [h] at hm; simp at hm; omega
      · exact h
    have hmn : m ∣ n := ⟨m, hm⟩
    have hsq : n = m ^ 2 := by rw [hm]; ring
    refine ⟨AddSubgroup.zmultiples (m : ℤ), ?_, ?_⟩
    · rw [AddSubgroup.mem_zmultiples_iff]
      exact ⟨(m : ℤ), by rw [hsq]; push_cast; ring⟩
    · have hset : (AddSubgroup.zmultiples (m : ℤ) : Set ℤ) = divSubgroup (m : ℤ) := by
        ext x
        simp only [SetLike.mem_coe, AddSubgroup.mem_zmultiples_iff, divSubgroup,
          Set.mem_setOf_eq]
        constructor
        · rintro ⟨k, rfl⟩; exact ⟨k, by ring⟩
        · rintro ⟨k, rfl⟩; exact ⟨k, by ring⟩
      rw [hset]
      exact (isMetabolizer_divSubgroup_iff n q m hn hm0 hmn hq).mpr hsq

theorem not_isSquare_three : ¬ IsSquare (3 : ℕ) := by
  rintro ⟨m, hm⟩
  have hle : m ≤ 3 := by nlinarith
  interval_cases m <;> omega

theorem not_isSquare_six : ¬ IsSquare (6 : ℕ) := by
  rintro ⟨m, hm⟩
  have hle : m ≤ 6 := by nlinarith
  interval_cases m <;> omega

/-- **Concrete obstruction.**  The linking form of the lens space `L(3, q)` admits
no metabolizer; with the classical Alexander-duality input this says that `L(3,q)`
does not embed smoothly in `S⁴`. -/
theorem no_metabolizer_three (q : ℕ) (hq : Nat.Coprime q 3) :
    ¬ ∃ H : AddSubgroup ℤ, ((3 : ℕ) : ℤ) ∈ H ∧ IsMetabolizer 3 q (H : Set ℤ) := by
  rw [exists_metabolizer_iff_isSquare 3 q (by norm_num) hq]
  exact not_isSquare_three

/-- The same obstruction for every non-square order, e.g. `n = 6`. -/
theorem no_metabolizer_six (q : ℕ) (hq : Nat.Coprime q 6) :
    ¬ ∃ H : AddSubgroup ℤ, ((6 : ℕ) : ℤ) ∈ H ∧ IsMetabolizer 6 q (H : Set ℤ) := by
  rw [exists_metabolizer_iff_isSquare 6 q (by norm_num) hq]
  exact not_isSquare_six

/-- Positive control: for `n = 4` a metabolizer does exist, so this piece of the
coupled obstruction does not by itself rule out `L(4, q)`. -/
theorem metabolizer_four (q : ℕ) (hq : Nat.Coprime q 4) :
    ∃ H : AddSubgroup ℤ, ((4 : ℕ) : ℤ) ∈ H ∧ IsMetabolizer 4 q (H : Set ℤ) := by
  rw [exists_metabolizer_iff_isSquare 4 q (by norm_num) hq]
  exact ⟨2, by norm_num⟩

/-! ### Hantzsche's square-order shadow -/

/-- If a finite abelian group `A` splits as `G × G`, its order is a perfect square. -/
theorem isSquare_card_of_equiv_prod_self (A G : Type) [AddCommGroup A] [AddCommGroup G]
    [Fintype A] [Fintype G] (e : A ≃+ G × G) : IsSquare (Fintype.card A) := by
  have h : Fintype.card A = Fintype.card G * Fintype.card G := by
    rw [Fintype.card_congr e.toEquiv, Fintype.card_prod]
  exact ⟨Fintype.card G, h⟩

/-- Consequently `ℤ/3` — the first homology of `L(3,q)` — is not a double, another
form of the same obstruction. -/
theorem no_double_zmod_three (G : Type) [AddCommGroup G] [Fintype G] :
    ¬ Nonempty (ZMod 3 ≃+ G × G) := by
  rintro ⟨e⟩
  have h := isSquare_card_of_equiv_prod_self (ZMod 3) G e
  rw [ZMod.card] at h
  exact not_isSquare_three h

end LinkingObstruction