/-
# Beyond the Noetherian world, and the completion picture

Cycle 3.  Two complementary additions.

1. **Strictly beyond Noetherian.**  The polynomial ring `ℚ[X₀, X₁, X₂, …]` in countably
   many variables is a unique factorisation domain that is *not* Noetherian
   (`not_isNoetherianRing_mvPolynomial`), yet every non-unit there has separated
   principal filtration (`mvPolynomial_isSeparated_of_not_isUnit`).  So the
   `WfDvdMonoid` hypothesis used in the core file really is a strict generalisation of
   the Noetherian hypothesis of the classical Krull intersection theorem, and the
   generalisation has content.

2. **The completion picture.**  Separation of the principal filtration at `a` is exactly
   the injectivity of the canonical map into the `a`-adic completion
   (`isSeparated_iff_injective_adicCompletion`).  This is the categorical formulation of
   the Hausdorff property established in the valuation file.
-/
import Mathlib
import Shared.SeparatedPrincipalFiltration
import Shared.SeparatedPrincipalFiltrationValuation

namespace SeparatedPrincipalFiltration

open MvPolynomial

/-! ## `ℚ[X₀, X₁, …]`: a non-Noetherian UFD with separated principal filtrations -/

/-- The irrelevant ideal of `ℚ[X₀, X₁, …]`, generated by all the variables. -/
def irrelevant : Ideal (MvPolynomial ℕ ℚ) := Ideal.span (Set.range (X : ℕ → MvPolynomial ℕ ℚ))

lemma constantCoeff_eq_zero_of_mem_irrelevant {p : MvPolynomial ℕ ℚ} (hp : p ∈ irrelevant) :
    constantCoeff p = 0 := by
  have hle : irrelevant ≤ RingHom.ker (constantCoeff : MvPolynomial ℕ ℚ →+* ℚ) := by
    rw [irrelevant, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    simp [RingHom.mem_ker]
  simpa [RingHom.mem_ker] using hle hp

/-- The irrelevant ideal is not finitely generated: any finite generating set uses only
finitely many variables, and the evaluation killing all of them but one detects the
missing variable. -/
theorem irrelevant_not_fg : ¬ irrelevant.FG := by
  rintro ⟨T, hT⟩
  classical
  set V : Finset ℕ := T.sup MvPolynomial.vars with hV
  set k : ℕ := (V.sup id) + 1 with hk
  have hkV : k ∉ V := by
    intro hmem
    have : k ≤ V.sup id := Finset.le_sup (f := id) hmem
    omega
  set g : ℕ → ℚ := fun i => if i = k then 1 else 0 with hg
  have hTker : ∀ t ∈ T, eval g t = 0 := by
    intro t ht
    have hvars : ∀ i ∈ t.vars, g i = 0 := by
      intro i hi
      have hiV : i ∈ V := Finset.le_sup (f := MvPolynomial.vars) ht hi
      have : i ≠ k := by rintro rfl; exact hkV hiV
      simp [hg, this]
    have h1 : eval₂Hom (RingHom.id ℚ) g t = (RingHom.id ℚ) (constantCoeff t) :=
      eval₂Hom_eq_constantCoeff_of_vars _ hvars
    have h2 : t ∈ irrelevant := by
      rw [← hT]
      exact Ideal.subset_span ht
    have h3 : eval g t = constantCoeff t := h1
    rw [h3, constantCoeff_eq_zero_of_mem_irrelevant h2]
  have hspan : irrelevant ≤ RingHom.ker (eval g) := by
    rw [← hT, Ideal.span_le]
    intro t ht
    simpa [RingHom.mem_ker] using hTker t ht
  have hXk : (X k : MvPolynomial ℕ ℚ) ∈ irrelevant := Ideal.subset_span ⟨k, rfl⟩
  have := hspan hXk
  rw [RingHom.mem_ker] at this
  simp [hg] at this

/-- `ℚ[X₀, X₁, …]` is not a Noetherian ring. -/
theorem not_isNoetherianRing_mvPolynomial : ¬ IsNoetherianRing (MvPolynomial ℕ ℚ) := by
  intro h
  exact irrelevant_not_fg (IsNoetherian.noetherian irrelevant)

/-- Nevertheless every non-unit of `ℚ[X₀, X₁, …]` has separated principal filtration:
the ring is a UFD, hence a `WfDvdMonoid`. -/
theorem mvPolynomial_isSeparated_of_not_isUnit {a : MvPolynomial ℕ ℚ} (ha : ¬ IsUnit a) :
    IsSeparated a :=
  isSeparated_of_not_isUnit ha

/-- Concretely, `⨅ n, (X₀ⁿ) = 0` in `ℚ[X₀, X₁, …]`. -/
theorem mvPolynomial_X_isSeparated : IsSeparated (X 0 : MvPolynomial ℕ ℚ) :=
  mvPolynomial_isSeparated_of_not_isUnit (X_prime (i := 0)).not_unit

/-- The `X₀`-adic absolute value on the non-Noetherian UFD `ℚ[X₀, X₁, …]`. -/
noncomputable def mvPolynomialAdicAbs : AbsoluteValue (MvPolynomial ℕ ℚ) ℝ :=
  adicAbsoluteValue mvPolynomial_X_isSeparated (X_prime (i := 0))

theorem mvPolynomialAdicAbs_X : mvPolynomialAdicAbs (X 0) = 1 / 2 :=
  adicAbs_self (X_prime (i := 0)).ne_zero

/-! ## Separation as injectivity into the adic completion -/

variable {R : Type*} [CommRing R]

/-- **Completion form of separation.**  `⨅ n, (aⁿ) = 0` if and only if the canonical map
from `R` to its `a`-adic completion is injective. -/
theorem isSeparated_iff_injective_adicCompletion {a : R} :
    IsSeparated a ↔
      Function.Injective (AdicCompletion.of (Ideal.span {a}) R) := by
  rw [AdicCompletion.of_injective_iff]
  exact isSeparated_iff_isHausdorff

/-- In a domain with well-founded divisibility every non-unit gives an injection into the
adic completion. -/
theorem injective_adicCompletion_of_not_isUnit [IsDomain R] [WfDvdMonoid R] {a : R}
    (ha : ¬ IsUnit a) : Function.Injective (AdicCompletion.of (Ideal.span {a}) R) :=
  isSeparated_iff_injective_adicCompletion.mp (isSeparated_of_not_isUnit ha)

end SeparatedPrincipalFiltration