/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aristotle (Harmonic)
-/
import Mathlib

/-!
# Generic contraction sequences for twin-width

A *contraction sequence* of a graph repeatedly merges two vertices until a single
vertex remains.  We model a contraction sequence abstractly as a list of merge
operations `seq : List (V × V)`, where the operation `(a, b)` identifies the two
super-vertices currently containing `a` and `b`.

Two pieces of data make such a list a genuine contraction sequence:

* every operation merges two *distinct* vertices (no self-reference), and
* the operations identify *all* vertices into one final super-vertex, i.e. the
  reflexive–transitive closure of the merge relation is total on `V`.

This file develops the generic *star* contraction sequence built from a linear
ordering of the vertices, and proves the generic length bound
`twinWidth_contraction_bound`, which downstream files reuse instead of re-deriving.
-/

namespace Graph.TwinWidth

variable {V : Type*}

/-- The symmetric relation generated by a list of merge operations. -/
def MergeRel (seq : List (V × V)) (a b : V) : Prop := (a, b) ∈ seq ∨ (b, a) ∈ seq

theorem mergeRel_symm {seq : List (V × V)} {a b : V} (h : MergeRel seq a b) :
    MergeRel seq b a := Or.symm h

theorem mergeRel_symmetric (seq : List (V × V)) : Symmetric (MergeRel seq) :=
  fun _ _ h => Or.symm h

/-- The **star** contraction sequence built from a list of vertices `v₀ :: rest`:
merge the head `v₀` successively with every other vertex.  This realises a
"contract everything into the first vertex" strategy in `|l| - 1` steps. -/
def starSequence : List V → List (V × V)
  | [] => []
  | (v₀ :: rest) => rest.map (fun v => (v₀, v))

@[simp] theorem starSequence_nil : starSequence ([] : List V) = [] := rfl

@[simp] theorem starSequence_cons (v₀ : V) (rest : List V) :
    starSequence (v₀ :: rest) = rest.map (fun v => (v₀, v)) := rfl

/-- The star sequence has length `|l| - 1`. -/
@[simp] theorem starSequence_length (l : List V) : (starSequence l).length = l.length - 1 := by
  cases l with
  | nil => simp
  | cons v₀ rest => simp

/-- Every operation in the star sequence merges two genuinely distinct vertices,
provided the underlying list is non-circular (has no duplicates). -/
theorem starSequence_pairs_ne {l : List V} (h : l.Nodup) :
    ∀ e ∈ starSequence l, e.1 ≠ e.2 := by
  cases l with
  | nil => simp
  | cons v₀ rest =>
    intro e he
    simp only [starSequence_cons, List.mem_map] at he
    obtain ⟨v, hv, rfl⟩ := he
    have hmem : v₀ ∉ rest := (List.nodup_cons.mp h).1
    intro hcontra
    apply hmem
    have : v₀ = v := hcontra
    exact this ▸ hv

/-- Both endpoints of every operation in the star sequence belong to `l`. -/
theorem starSequence_mem (l : List V) :
    ∀ e ∈ starSequence l, e.1 ∈ l ∧ e.2 ∈ l := by
  cases l with
  | nil => simp
  | cons v₀ rest =>
    intro e he
    simp only [starSequence_cons, List.mem_map] at he
    obtain ⟨v, hv, rfl⟩ := he
    exact ⟨List.mem_cons.mpr (Or.inl rfl), List.mem_cons.mpr (Or.inr hv)⟩

/-- Every vertex of `l` is `MergeRel`-related to the head (going *towards* the head). -/
theorem starSequence_toHead {v₀ : V} {rest : List V} {a : V}
    (ha : a ∈ v₀ :: rest) :
    Relation.ReflTransGen (MergeRel (starSequence (v₀ :: rest))) a v₀ := by
  rcases List.mem_cons.mp ha with rfl | ha
  · exact Relation.ReflTransGen.refl
  · refine Relation.ReflTransGen.single ?_
    right
    simp only [starSequence_cons, List.mem_map]
    exact ⟨a, ha, rfl⟩

/-- Every vertex of `l` is `MergeRel`-related from the head (going *from* the head). -/
theorem starSequence_fromHead {v₀ : V} {rest : List V} {a : V}
    (ha : a ∈ v₀ :: rest) :
    Relation.ReflTransGen (MergeRel (starSequence (v₀ :: rest))) v₀ a := by
  rcases List.mem_cons.mp ha with rfl | ha
  · exact Relation.ReflTransGen.refl
  · refine Relation.ReflTransGen.single ?_
    left
    simp only [starSequence_cons, List.mem_map]
    exact ⟨a, ha, rfl⟩

/-- The star sequence identifies all vertices of `l`: any two elements of `l` are
related by the reflexive–transitive closure of the merge relation. -/
theorem starSequence_connects {l : List V} {a b : V} (ha : a ∈ l) (hb : b ∈ l) :
    Relation.ReflTransGen (MergeRel (starSequence l)) a b := by
  cases l with
  | nil => simp at ha
  | cons v₀ rest =>
    exact (starSequence_toHead ha).trans (starSequence_fromHead hb)

/-- **Generic contraction length bound.**  The star contraction sequence built
from any vertex list has length at most twice the number of vertices.  Downstream
constructions invoke this lemma rather than re-deriving a length bound. -/
theorem twinWidth_contraction_bound (l : List V) :
    (starSequence l).length ≤ 2 * l.length := by
  have h := starSequence_length l
  omega

end Graph.TwinWidth