/-
# Cycle 2: the component law, and the hierarchy of marginal-driven bounds

Research thread *Compression Beyond the Pigeonhole Bound*, cycle v19c (second
loop).  Cycle 1 produced three inputs to the Bonferroni machinery:

* `Geometry.CollisionPatternMarginal` — exact marginals of a collision pattern,
  computed through an explicit *collapse map*;
* `Geometry.BonferroniMarginals` — the second-moment (Chung–Erdős) machinery and
  the unconditional bound `k/(M+k-1)`;
* `Geometry.ExactFailureMarginal` — the exact failure law `1-(1-1/M)^k`.

Two questions were left open by that cycle, and both are settled here.

**(A) Is the collapse-map presentation essential?**  No.  The marginal of an
arbitrary collision pattern is `M` to the number of *connected components* of the
pattern viewed as a graph, with no auxiliary data:
`MarginalHierarchy.card_patternEvent_eq_pow_components`.  The collapse maps of
cycle 1 are then merely a computational device for evaluating the component
count, and `MarginalHierarchy.card_quotient_starPattern` shows the two agree by
*deducing* a purely graph-theoretic component count from the two counting laws.

**(B) How do the three lower bounds relate?**  They form a strict hierarchy.
`MarginalHierarchy.second_moment_le_exact` proves that the exact law implies the
second-moment bound (via the integer Bernoulli-type inequality
`MarginalHierarchy.pow_pred_mul_le`), and
`MarginalHierarchy.hashing_bound_hierarchy` assembles the chain

`k/(2M) ≤ k/(M+k-1) ≤ P[failure] = 1-(1-1/M)^k ≤ k/M`

for every typical set, every `M ≥ 1`, and every `k ≤ M+1`.  The Bonferroni
output of the catalog is thus located exactly: it is the weakest member of a
four-term chain whose middle terms use *only* the first two marginals.
-/
import Geometry.BonferroniMarginals
import Geometry.CollisionPatternMarginal
import Geometry.ExactFailureMarginal

namespace MarginalHierarchy

open Finset AlmostLossless CollisionPattern

/-! ## 1. The component law for pattern marginals -/

variable {ι : Type*} [Fintype ι] [DecidableEq ι] {M : ℕ}

/-- The adjacency relation of a collision pattern. -/
def patternRel (P : Finset (ι × ι)) : ι → ι → Prop := fun a b => (a, b) ∈ P

/-- The connectivity equivalence generated by a collision pattern: its classes
are the connected components of the pattern graph. -/
def patternSetoid (P : Finset (ι × ι)) : Setoid ι := Relation.EqvGen.setoid (patternRel P)

/-- A codebook respects a pattern iff it is constant on connected components. -/
theorem mem_patternEvent_iff (P : Finset (ι × ι)) (H : ι → Fin M) :
    H ∈ patternEvent M P ↔ ∀ a b, (patternSetoid P).r a b → H a = H b := by
  simp only [patternEvent, mem_filter, mem_univ, true_and]
  constructor
  · intro h a b hab
    induction hab with
    | rel a b hr => exact h (a, b) hr
    | refl a => rfl
    | symm a b _ ih => exact ih.symm
    | trans a b c _ _ ih1 ih2 => exact ih1.trans ih2
  · intro h p hp
    exact h p.1 p.2 (Relation.EqvGen.rel _ _ hp)

/-- **The component law.**  For an arbitrary collision pattern `P` — an arbitrary
graph on the index set — the probability that a uniformly random codebook
realises every collision of `P` is `M^{-(|ι| - c)}`, where `c` is the number of
connected components of `P`; equivalently the event has cardinality exactly
`M ^ c`.  This is the marginal that any Bonferroni-type expansion of a collision
failure event must be fed, and it depends on the pattern only through its
component count. -/
theorem card_patternEvent_eq_pow_components (P : Finset (ι × ι)) :
    (patternEvent M P).card = M ^ Nat.card (Quotient (patternSetoid P)) := by
  classical
  haveI : Fintype (Quotient (patternSetoid P)) := Fintype.ofFinite _
  let e : {H : ι → Fin M // ∀ a b, (patternSetoid P).r a b → H a = H b}
      ≃ (Quotient (patternSetoid P) → Fin M) :=
    { toFun := fun H => Quotient.lift H.1 (fun a b hab => H.2 a b hab)
      invFun := fun g => ⟨fun a => g (Quotient.mk (patternSetoid P) a), by
        intro a b hab
        exact congrArg g (Quotient.sound hab)⟩
      left_inv := by
        intro H
        apply Subtype.ext
        funext a
        rfl
      right_inv := by
        intro g
        funext q
        induction q using Quotient.inductionOn
        rfl }
  have hcard : (patternEvent M P).card
      = Fintype.card {H : ι → Fin M // ∀ a b, (patternSetoid P).r a b → H a = H b} := by
    rw [Fintype.card_subtype]
    congr 1
    ext H
    simp only [mem_filter, mem_univ, true_and]
    exact mem_patternEvent_iff P H
  rw [hcard, Fintype.card_congr e, Fintype.card_fun, Fintype.card_fin,
    Nat.card_eq_fintype_card]

/-- The star pattern: every member of `T` is joined to `x`. -/
def starPattern (T : Finset ι) (x : ι) : Finset (ι × ι) := T.image (fun y => (y, x))

theorem patternEvent_starPattern (T : Finset ι) (x : ι) :
    patternEvent M (starPattern T x) = starEvent M T x := by
  ext H
  simp only [patternEvent, starEvent, starPattern, mem_filter, mem_univ, true_and, mem_image]
  constructor
  · intro h y hy
    exact h (y, x) ⟨y, hy, rfl⟩
  · rintro h p ⟨y, hy, rfl⟩
    exact h y hy

/-- **A graph-theoretic corollary of the two counting laws.**  Comparing the
component law with the collapse-map computation of cycle 1 *proves* that the
star pattern on `T ∪ {x}` has exactly `|ι| - |T|` connected components — a purely
combinatorial fact here derived from two independent enumerations of the same
event.  (`2 ≤ M` is what makes `M ^ ·` injective.) -/
theorem card_quotient_starPattern (T : Finset ι) (x : ι) (hx : x ∉ T) (hM : 2 ≤ M) :
    Nat.card (Quotient (patternSetoid (starPattern T x))) = Fintype.card ι - T.card := by
  have h1 : (patternEvent M (starPattern T x)).card
      = M ^ Nat.card (Quotient (patternSetoid (starPattern T x))) :=
    card_patternEvent_eq_pow_components _
  have h2 : (patternEvent M (starPattern T x)).card = M ^ (Fintype.card ι - T.card) := by
    rw [patternEvent_starPattern, card_starEvent T x hx]
  have h3 : M ^ Nat.card (Quotient (patternSetoid (starPattern T x)))
      = M ^ (Fintype.card ι - T.card) := by rw [← h1, h2]
  exact Nat.pow_right_injective hM h3

/-! ## 2. The hierarchy of bounds -/

/-- **Integer Bernoulli inequality.**  `(M-1)^j · (M+j) ≤ M^{j+1}` for `M ≥ 1`.
This is the arithmetic content of the statement that the exact failure law is
stronger than the second-moment bound. -/
theorem pow_pred_mul_le (M j : ℕ) (hM : 0 < M) : (M - 1) ^ j * (M + j) ≤ M ^ (j + 1) := by
  induction j with
  | zero => simp
  | succ n ih =>
      have hpos : 0 < M + n := by omega
      have hstep : (M - 1) * (M + n + 1) ≤ M * (M + n) := by
        cases M with
        | zero => omega
        | succ m =>
            simp only [Nat.succ_sub_one]
            nlinarith
      have hmul : (M - 1) ^ (n + 1) * (M + n + 1) * (M + n)
          ≤ M ^ (n + 2) * (M + n) := by
        calc (M - 1) ^ (n + 1) * (M + n + 1) * (M + n)
            = ((M - 1) ^ n * (M + n)) * ((M - 1) * (M + n + 1)) := by ring
          _ ≤ M ^ (n + 1) * (M * (M + n)) := Nat.mul_le_mul ih hstep
          _ = M ^ (n + 2) * (M + n) := by ring
      exact Nat.le_of_mul_le_mul_right hmul hpos

/-- **The exact law implies the second-moment bound.**  For all `M ≥ 1` and all
`k`, `k/(M+k-1) ≤ 1 - (1-1/M)^k`.  Hence
`BonferroniMarginals.hashing_failure_prob_lower` — obtained from two marginals
and Cauchy–Schwarz — is exactly recovered from, and strictly weaker than, the
exact failure law of `ExactFailure.failure_prob_exact`. -/
theorem second_moment_le_exact (M k : ℕ) (hM : 0 < M) :
    (k : ℝ) / ((M : ℝ) + k - 1) ≤ 1 - (1 - 1 / (M : ℝ)) ^ k := by
  have hMpos : (0 : ℝ) < M := by exact_mod_cast hM
  have hM1 : (1 : ℝ) ≤ (M : ℝ) := by exact_mod_cast hM
  rcases Nat.eq_zero_or_pos k with hk0 | hkpos
  · simp [hk0]
  obtain ⟨j, rfl⟩ : ∃ j, k = j + 1 := ⟨k - 1, by omega⟩
  -- integer inequality, cast to `ℝ`
  have hnat := pow_pred_mul_le M j hM
  have hsub : ((M - 1 : ℕ) : ℝ) = (M : ℝ) - 1 := by
    have h1 : (1 : ℕ) ≤ M := hM
    push_cast [Nat.cast_sub h1]; ring
  have hreal : ((M : ℝ) - 1) ^ j * ((M : ℝ) + j) ≤ (M : ℝ) ^ (j + 1) := by
    have h := (Nat.cast_le (α := ℝ)).2 hnat
    push_cast [hsub] at h
    linarith
  -- hence `((M-1)/M)^{j+1} ≤ (M-1)/(M+j)`
  have hden : (0 : ℝ) < (M : ℝ) + j := by positivity
  have hMj : (M : ℝ) + (j + 1 : ℕ) - 1 = (M : ℝ) + j := by push_cast; ring
  have hpow : ((M : ℝ) - 1) ^ (j + 1) * ((M : ℝ) + j) ≤ ((M : ℝ) - 1) * (M : ℝ) ^ (j + 1) := by
    have hM1' : (0 : ℝ) ≤ (M : ℝ) - 1 := by linarith
    calc ((M : ℝ) - 1) ^ (j + 1) * ((M : ℝ) + j)
        = ((M : ℝ) - 1) * (((M : ℝ) - 1) ^ j * ((M : ℝ) + j)) := by ring
      _ ≤ ((M : ℝ) - 1) * (M : ℝ) ^ (j + 1) := by
          exact mul_le_mul_of_nonneg_left hreal hM1'
  have hone : (1 : ℝ) - 1 / (M : ℝ) = ((M : ℝ) - 1) / (M : ℝ) := by field_simp
  have hMk : (0 : ℝ) < (M : ℝ) ^ (j + 1) := by positivity
  rw [hone, div_pow, hMj]
  push_cast
  have hkey : ((M : ℝ) - 1) ^ (j + 1) / (M : ℝ) ^ (j + 1) ≤ ((M : ℝ) - 1) / ((M : ℝ) + j) := by
    rw [div_le_div_iff₀ hMk hden]
    nlinarith [hpow]
  have hfin : ((M : ℝ) - 1) / ((M : ℝ) + j) = 1 - ((j : ℝ) + 1) / ((M : ℝ) + j) := by
    field_simp
    ring
  linarith [hkey, hfin]

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- **The full hierarchy for uniform random hashing.**  For every typical set `S`,
every transmitted string `x`, every `M ≥ 1` and every `k = |S \ {x}| ≤ M+1`
(the Bonferroni regime), the four marginal-driven estimates line up:

`k/(2M)  ≤  k/(M+k-1)  ≤  P[failure]  ≤  k/M`,

the first from `AlmostLossless.card_sum_le_card_biUnion_add_offDiag` (Bonferroni),
the second from Cauchy–Schwarz on the same two marginals, the third from the
exact law, the last from the union bound.  Only the middle inequality needs the
regime hypothesis to be *stated* usefully; the outer ones hold always. -/
theorem hashing_bound_hierarchy (S : Finset α) (x : α) {M : ℕ} (hM : 0 < M)
    (hk : (S.erase x).card ≤ M + 1) :
    ((S.erase x).card : ℝ) / (2 * M)
        ≤ ((S.erase x).card : ℝ) / ((M : ℝ) + (S.erase x).card - 1) ∧
      ((S.erase x).card : ℝ) / ((M : ℝ) + (S.erase x).card - 1)
        ≤ ((failSet S x M).card : ℝ) / ((M : ℝ) ^ Fintype.card α) ∧
      ((failSet S x M).card : ℝ) / ((M : ℝ) ^ Fintype.card α)
        ≤ ((S.erase x).card : ℝ) / (M : ℝ) := by
  refine ⟨BonferroniMarginals.chung_erdos_dominates_bonferroni hM hk, ?_,
    ExactFailure.failure_prob_le_shannon S x hM⟩
  rw [ExactFailure.failure_prob_exact S x hM]
  exact second_moment_le_exact M (S.erase x).card hM

end MarginalHierarchy