import Shared.BerggrenTQC.BoundaryBraiding

/-!
# The `√2` braiding the Berggren spectrum really does support: Ising anyons, and why they are
still not universal

The spectral data of the Berggren tree lives in `ℤ[√2]` (silver ratio `1+√2`, Pell unit
`3+2√2`).  The number `√2 = 2 cos(π/4)` is exactly the Temperley–Lieb loop parameter of the
**Ising** anyon model, so if the Berggren tree supports any anyonic braiding at all, it is the
Ising one.  This file builds that braid representation explicitly out of `√2` and then proves
that it, too, fails the universality criterion — for a completely different reason than the
integral representation of `NonUniversality.lean`: not integrality, but the *Clifford* property.

Main results.

* `ising_braid`: the two explicit unitaries `A = diag(e^{iπ/4}, e^{-iπ/4})` and
  `B = (1 + iX)/√2`, both built from `√2`, satisfy the Artin braid relation `ABA = BAB`;
  `isingRep` packages this as a genuine two-dimensional unitary representation of `B₃`.
* `Amat_unitary`, `Bmat_unitary`, `Amat_pow_eight`, `Bmat_pow_eight`: the generators are
  unitary of order `8` — the root-of-unity structure of Ising anyons.
* `Amat_mem_cliff`, `Bmat_mem_cliff`: both generators normalise the Pauli group, i.e. they are
  Clifford gates.  Explicitly `A X A* = -Y`, `A Y A* = X`, `A Z A* = Z`, `B X B* = X`,
  `B Y B* = -Z`, `B Z B* = Y`.
* `isClosed_cliff`: the set of Clifford matrices is closed.
* `tgate_not_cliff`: the `π/8` gate `T = diag(1, e^{iπ/4})` is unitary but not Clifford.
* `ising_not_dense`: **the Ising braid representation generated by the Berggren spectral unit
  `√2` is not dense in `U(2)`** — its closure misses the `T` gate.  This is the formal version
  of the statement that Ising anyons are not universal by braiding alone; it closes the
  moonshot from the second direction.
-/

namespace BerggrenTQC

open Matrix Complex

/-! ## The scalar `1/√2` -/

/-- The Ising normalisation constant `1/√2 = √2/2`, the square root scale of the Berggren
spectral unit. -/
noncomputable def rr : ℂ := ((Real.sqrt 2 / 2 : ℝ) : ℂ)

theorem sqrt_two_mul_self : Real.sqrt 2 * Real.sqrt 2 = 2 := Real.mul_self_sqrt (by norm_num)

theorem rr_sq : rr * rr = 1 / 2 := by
  have hr : (Real.sqrt 2 / 2) * (Real.sqrt 2 / 2) = 1 / 2 := by
    nlinarith [sqrt_two_mul_self]
  rw [rr, ← Complex.ofReal_mul, hr]
  norm_num

theorem rr_conj : (starRingEnd ℂ) rr = rr := Complex.conj_ofReal _

theorem rr_pos_lt_one : 0 < Real.sqrt 2 / 2 ∧ Real.sqrt 2 / 2 < 1 := by
  have h1 : 0 < Real.sqrt 2 := Real.sqrt_pos.mpr (by norm_num)
  constructor
  · linarith
  · nlinarith [h1, sqrt_two_mul_self]

/-! ## The Ising braid generators -/

/-- `A = diag(e^{iπ/4}, e^{-iπ/4})`, the braiding of the first pair of Ising anyons. -/
noncomputable def Amat : Matrix (Fin 2) (Fin 2) ℂ := !![rr * (1 + I), 0; 0, rr * (1 - I)]

/-- `B = (1 + iX)/√2`, the braiding of the second pair of Ising anyons. -/
noncomputable def Bmat : Matrix (Fin 2) (Fin 2) ℂ := !![rr, rr * I; rr * I, rr]

/-- **The Ising braid relation.**  `√2` really does produce a braid representation. -/
theorem ising_braid : Amat * Bmat * Amat = Bmat * Amat * Bmat := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Bmat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr]

theorem Amat_conjTranspose : Amatᴴ = !![rr * (1 - I), 0; 0, rr * (1 + I)] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Matrix.conjTranspose_apply, rr, Complex.conj_I]
  ring

theorem Bmat_conjTranspose : Bmatᴴ = !![rr, -(rr * I); -(rr * I), rr] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Matrix.conjTranspose_apply, rr, Complex.conj_I]

theorem Amat_unitary : Amatᴴ * Amat = 1 := by
  have h2 := sqrt_two_mul_self
  rw [Amat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Amat_unitary' : Amat * Amatᴴ = 1 := by
  have h2 := sqrt_two_mul_self
  rw [Amat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Bmat_unitary : Bmatᴴ * Bmat = 1 := by
  have h2 := sqrt_two_mul_self
  rw [Bmat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Bmat_unitary' : Bmat * Bmatᴴ = 1 := by
  have h2 := sqrt_two_mul_self
  rw [Bmat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

/-- `A² = diag(i, -i) = iZ`. -/
theorem Amat_sq : Amat * Amat = !![I, 0; 0, -I] := by
  have h2 := sqrt_two_mul_self
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

/-- `B² = iX`. -/
theorem Bmat_sq : Bmat * Bmat = !![0, I; I, 0] := by
  have h2 := sqrt_two_mul_self
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

/-- The Ising braid generators have order `8`. -/
theorem Amat_pow_eight : Amat ^ 8 = 1 := by
  have h2 : Amat ^ 2 = !![I, 0; 0, -I] := by rw [pow_two]; exact Amat_sq
  have h4 : Amat ^ 4 = -1 := by
    have he : Amat ^ 4 = Amat ^ 2 * Amat ^ 2 := by rw [← pow_add]
    rw [he, h2]
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.mul_apply, Fin.sum_univ_two, Complex.I_mul_I]
  have he : Amat ^ 8 = Amat ^ 4 * Amat ^ 4 := by rw [← pow_add]
  rw [he, h4]
  simp

theorem Bmat_pow_eight : Bmat ^ 8 = 1 := by
  have h2 : Bmat ^ 2 = !![0, I; I, 0] := by rw [pow_two]; exact Bmat_sq
  have h4 : Bmat ^ 4 = -1 := by
    have he : Bmat ^ 4 = Bmat ^ 2 * Bmat ^ 2 := by rw [← pow_add]
    rw [he, h2]
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.mul_apply, Fin.sum_univ_two, Complex.I_mul_I]
  have he : Bmat ^ 8 = Bmat ^ 4 * Bmat ^ 4 := by rw [← pow_add]
  rw [he, h4]
  simp

/-! ## The braid representation of `B₃` -/

/-- `A` as a unit of the matrix ring. -/
noncomputable def uA : (Matrix (Fin 2) (Fin 2) ℂ)ˣ := ⟨Amat, Amatᴴ, Amat_unitary', Amat_unitary⟩

/-- `B` as a unit of the matrix ring. -/
noncomputable def uB : (Matrix (Fin 2) (Fin 2) ℂ)ˣ := ⟨Bmat, Bmatᴴ, Bmat_unitary', Bmat_unitary⟩

theorem uA_uB_braid : uA * uB * uA = uB * uA * uB := by
  apply Units.ext
  simpa [uA, uB] using ising_braid

/-- **A genuine braid representation from the Berggren spectral field.**  The assignment
`σ₁ ↦ A`, `σ₂ ↦ B` extends to a homomorphism from the three-strand braid group. -/
noncomputable def isingRep : Braid3 →* (Matrix (Fin 2) (Fin 2) ℂ)ˣ :=
  PresentedGroup.toGroup (f := fun i : Fin 2 => if i = 0 then uA else uB) (by
    rintro r rfl
    have hlift : (FreeGroup.lift fun i : Fin 2 => if i = 0 then uA else uB)
        (FreeGroup.of 0 * FreeGroup.of 1 * FreeGroup.of 0 *
          (FreeGroup.of 1 * FreeGroup.of 0 * FreeGroup.of 1)⁻¹)
        = uA * uB * uA * (uB * uA * uB)⁻¹ := by
      simp
    rw [hlift, mul_inv_eq_one]
    exact uA_uB_braid)

theorem isingRep_braid :
    isingRep (PresentedGroup.of 0) * isingRep (PresentedGroup.of 1) *
        isingRep (PresentedGroup.of 0)
      = isingRep (PresentedGroup.of 1) * isingRep (PresentedGroup.of 0) *
        isingRep (PresentedGroup.of 1) := braid_image isingRep

/-! ## The Pauli group and the Clifford property -/

/-- The Pauli `X`. -/
def Xp : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]
/-- The Pauli `Y`. -/
noncomputable def Yp : Matrix (Fin 2) (Fin 2) ℂ := !![0, -I; I, 0]
/-- The Pauli `Z`. -/
def Zp : Matrix (Fin 2) (Fin 2) ℂ := !![1, 0; 0, -1]

/-- The six signed Pauli matrices. -/
noncomputable def PauliSet : Set (Matrix (Fin 2) (Fin 2) ℂ) := {Xp, -Xp, Yp, -Yp, Zp, -Zp}

theorem pauliSet_finite : PauliSet.Finite := by
  simp only [PauliSet]
  exact (((((Set.finite_singleton _).insert _).insert _).insert _).insert _).insert _

theorem pauliSet_neg {P : Matrix (Fin 2) (Fin 2) ℂ} (hP : P ∈ PauliSet) : -P ∈ PauliSet := by
  simp only [PauliSet, Set.mem_insert_iff, Set.mem_singleton_iff] at hP ⊢
  rcases hP with h | h | h | h | h | h <;> subst h <;> simp

/-- The Clifford condition: conjugation preserves the signed Pauli set. -/
noncomputable def Cliff : Set (Matrix (Fin 2) (Fin 2) ℂ) :=
  {U | U * Xp * Uᴴ ∈ PauliSet ∧ U * Yp * Uᴴ ∈ PauliSet ∧ U * Zp * Uᴴ ∈ PauliSet}

theorem one_mem_cliff : (1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ Cliff := by
  refine ⟨?_, ?_, ?_⟩ <;> simp [PauliSet]

theorem mul_mem_cliff {U V : Matrix (Fin 2) (Fin 2) ℂ} (hU : U ∈ Cliff) (hV : V ∈ Cliff) :
    U * V ∈ Cliff := by
  have key : ∀ P : Matrix (Fin 2) (Fin 2) ℂ, V * P * Vᴴ ∈ PauliSet →
      (U * V) * P * (U * V)ᴴ ∈ PauliSet := by
    intro P hP
    have hassoc : (U * V) * P * (U * V)ᴴ = U * (V * P * Vᴴ) * Uᴴ := by
      rw [Matrix.conjTranspose_mul]
      noncomm_ring
    rw [hassoc]
    simp only [PauliSet, Set.mem_insert_iff, Set.mem_singleton_iff] at hP
    rcases hP with h | h | h | h | h | h <;> rw [h]
    · exact hU.1
    · rw [mul_neg, neg_mul]; exact pauliSet_neg hU.1
    · exact hU.2.1
    · rw [mul_neg, neg_mul]; exact pauliSet_neg hU.2.1
    · exact hU.2.2
    · rw [mul_neg, neg_mul]; exact pauliSet_neg hU.2.2
  exact ⟨key _ hV.1, key _ hV.2.1, key _ hV.2.2⟩

/-- The Clifford matrices form a monoid. -/
noncomputable def CliffMonoid : Submonoid (Matrix (Fin 2) (Fin 2) ℂ) where
  carrier := Cliff
  mul_mem' := mul_mem_cliff
  one_mem' := one_mem_cliff

/-! ### The Ising generators are Clifford -/

theorem Amat_conj_X : Amat * Xp * Amatᴴ = -Yp := by
  have h2 := sqrt_two_mul_self
  rw [Amat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Xp, Yp, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Amat_conj_Y : Amat * Yp * Amatᴴ = Xp := by
  have h2 := sqrt_two_mul_self
  rw [Amat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Xp, Yp, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Amat_conj_Z : Amat * Zp * Amatᴴ = Zp := by
  have h2 := sqrt_two_mul_self
  rw [Amat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Amat, Zp, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Bmat_conj_X : Bmat * Xp * Bmatᴴ = Xp := by
  have h2 := sqrt_two_mul_self
  rw [Bmat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Xp, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Bmat_conj_Y : Bmat * Yp * Bmatᴴ = -Zp := by
  have h2 := sqrt_two_mul_self
  rw [Bmat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Yp, Zp, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Bmat_conj_Z : Bmat * Zp * Bmatᴴ = Yp := by
  have h2 := sqrt_two_mul_self
  rw [Bmat_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Bmat, Yp, Zp, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Amat_mem_cliff : Amat ∈ Cliff := by
  refine ⟨?_, ?_, ?_⟩
  · rw [Amat_conj_X]; exact pauliSet_neg (by simp [PauliSet])
  · rw [Amat_conj_Y]; simp [PauliSet]
  · rw [Amat_conj_Z]; simp [PauliSet]

theorem Bmat_mem_cliff : Bmat ∈ Cliff := by
  refine ⟨?_, ?_, ?_⟩
  · rw [Bmat_conj_X]; simp [PauliSet]
  · rw [Bmat_conj_Y]; exact pauliSet_neg (by simp [PauliSet])
  · rw [Bmat_conj_Z]; simp [PauliSet]

/-- Every positive braid word in the Ising generators is a Clifford gate.  Since the generators
have order `8`, the monoid they generate already contains their inverses, so this covers the
whole image of the braid representation. -/
theorem isingMonoid_le_cliff : Submonoid.closure {Amat, Bmat} ≤ CliffMonoid := by
  rw [Submonoid.closure_le]
  rintro U (rfl | rfl)
  · exact Amat_mem_cliff
  · exact Bmat_mem_cliff

/-! ### The Clifford set is closed, and misses the `T` gate -/

theorem continuous_conj_map (P : Matrix (Fin 2) (Fin 2) ℂ) :
    Continuous (fun U : Matrix (Fin 2) (Fin 2) ℂ => U * P * Uᴴ) := by
  have hH : Continuous (fun U : Matrix (Fin 2) (Fin 2) ℂ => Uᴴ) := by
    refine continuous_pi fun i => continuous_pi fun j => ?_
    simp only [Matrix.conjTranspose_apply]
    exact Complex.continuous_conj.comp ((continuous_apply i).comp (continuous_apply j))
  exact (continuous_id.mul continuous_const).mul hH

theorem isClosed_cliff : IsClosed Cliff := by
  have hP : IsClosed PauliSet := pauliSet_finite.isClosed
  exact (hP.preimage (continuous_conj_map Xp)).inter
    ((hP.preimage (continuous_conj_map Yp)).inter (hP.preimage (continuous_conj_map Zp)))

/-- The `π/8` gate `T = diag(1, e^{iπ/4})`. -/
noncomputable def Tgate : Matrix (Fin 2) (Fin 2) ℂ := !![1, 0; 0, rr * (1 + I)]

theorem Tgate_conjTranspose : Tgateᴴ = !![1, 0; 0, rr * (1 - I)] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Tgate, Matrix.conjTranspose_apply, rr_conj, Complex.conj_I]
  tauto

theorem Tgate_unitary : Tgateᴴ * Tgate = 1 := by
  have h2 := sqrt_two_mul_self
  rw [Tgate_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Tgate, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff, rr] <;>
    nlinarith [h2]

theorem Tgate_conj_X : Tgate * Xp * Tgateᴴ = !![0, rr * (1 - I); rr * (1 + I), 0] := by
  rw [Tgate_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Tgate, Xp, Matrix.mul_apply, Fin.sum_univ_two]

/-- The `T` gate is not Clifford: conjugating `X` by it produces an entry with real part
`1/√2`, which is neither `0` nor `±1`. -/
theorem tgate_not_cliff : Tgate ∉ Cliff := by
  intro h
  have h1 := h.1
  rw [Tgate_conj_X] at h1
  obtain ⟨hpos, hlt⟩ := rr_pos_lt_one
  simp only [PauliSet, Set.mem_insert_iff, Set.mem_singleton_iff] at h1
  rcases h1 with h' | h' | h' | h' | h' | h' <;>
    · have hcomp := congrArg Complex.re (congrFun (congrFun h' 0) 1)
      simp [Xp, Yp, Zp, rr] at hcomp
      all_goals linarith

/-- **The Ising braiding is not universal either.**  The closure of the group generated by the
two Ising braid generators — the only anyonic braiding compatible with the Berggren spectral
field `ℚ(√2)` — misses the `T` gate, hence is not dense in `U(2)`. -/
theorem ising_not_dense :
    Tgate ∉ closure ((Submonoid.closure {Amat, Bmat} : Submonoid (Matrix (Fin 2) (Fin 2) ℂ)) :
      Set (Matrix (Fin 2) (Fin 2) ℂ)) := by
  intro h
  have hsub : ((Submonoid.closure {Amat, Bmat} : Submonoid (Matrix (Fin 2) (Fin 2) ℂ)) :
      Set (Matrix (Fin 2) (Fin 2) ℂ)) ⊆ Cliff := isingMonoid_le_cliff
  exact tgate_not_cliff (isClosed_cliff.closure_subset_iff.mpr hsub h)

end BerggrenTQC