/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Dihedral Symmetry in Cyclotomic Fields

This file establishes the algebraic foundations linking cyclotomic field theory
to dihedral symmetry via the element `ζ + ζ⁻¹`, which generates the maximal
real subfield of a cyclotomic extension.

## Main results

* `zeta_quadratic_relation`: For nonzero `ζ` in a field,
  `ζ² - (ζ + ζ⁻¹) · ζ + 1 = 0`.

* `map_zeta_add_inv_of_map_eq_inv`: An algebra automorphism `σ` with `σ(ζ) = ζ⁻¹`
  fixes `ζ + ζ⁻¹`.

* `adjoin_zeta_add_inv_le_fixedField`: The intermediate field `F(ζ + ζ⁻¹)` is
  contained in the fixed field of any subgroup whose elements send `ζ ↦ ζ⁻¹`.

* `adjoin_zeta_add_inv_le_adjoin_zeta`: `F(ζ + ζ⁻¹) ≤ F(ζ)` whenever `ζ ≠ 0`.

* `isIntegral_zeta_over_adjoin_zeta_add_inv`: `ζ` is integral over the
  intermediate field `F(ζ + ζ⁻¹)`.

## Mathematical context

The involution `ζ ↦ ζ⁻¹` on a cyclotomic extension is the algebraic shadow of
complex conjugation. Its fixed field is the maximal totally real subfield, generated
by `ζ + ζ⁻¹ = 2cos(2π/n)`. The quadratic relation shows the full cyclotomic field
is at most a degree-2 extension of this real subfield — the hallmark of dihedral
symmetry where the reflection (inversion) acts on the rotational (cyclic) structure.
-/

noncomputable section

open Polynomial IntermediateField

/-! ### The fundamental quadratic relation -/

/-
The key algebraic identity: for nonzero `ζ` in a field,
`ζ² - (ζ + ζ⁻¹) * ζ + 1 = 0`.
-/
theorem zeta_quadratic_relation {K : Type*} [Field K] (ζ : K) (hζ : ζ ≠ 0) :
    ζ ^ 2 - (ζ + ζ⁻¹) * ζ + 1 = 0 := by
  grobner

/-
Variant: `ζ² + 1 = (ζ + ζ⁻¹) * ζ`.
-/
theorem zeta_sq_add_one_eq {K : Type*} [Field K] (ζ : K) (hζ : ζ ≠ 0) :
    ζ ^ 2 + 1 = (ζ + ζ⁻¹) * ζ := by
  grind

/-! ### The involution fixes `ζ + ζ⁻¹` -/

/-
An algebra automorphism sending `ζ` to `ζ⁻¹` fixes the sum `ζ + ζ⁻¹`.
-/
theorem map_zeta_add_inv_of_map_eq_inv
    {F K : Type*} [Field F] [Field K] [Algebra F K]
    (σ : K ≃ₐ[F] K) (ζ : K) (hσ : σ ζ = ζ⁻¹) (_hζ : ζ ≠ 0) :
    σ (ζ + ζ⁻¹) = ζ + ζ⁻¹ := by
  simp +decide [← hσ];
  rw [ hσ, add_comm ];
  exact congr_arg₂ ( · + · ) ( by rw [ map_inv₀ ] ; aesop ) rfl

/-! ### Inclusion in the fixed field -/

/-
`F(ζ + ζ⁻¹)` is contained in the fixed field of any subgroup whose
elements all send `ζ` to `ζ⁻¹`.
-/
theorem adjoin_zeta_add_inv_le_fixedField
    {F K : Type*} [Field F] [Field K] [Algebra F K]
    (ζ : K) (_hζ : ζ ≠ 0)
    (H : Subgroup (K ≃ₐ[F] K))
    (hH : ∀ σ : H, (σ : K ≃ₐ[F] K) ζ = ζ⁻¹) :
    IntermediateField.adjoin F ({ζ + ζ⁻¹} : Set K) ≤
      IntermediateField.fixedField H := by
  simp_all +decide;
  exact fun _ _ => add_comm _ _

/-! ### Tower structure: `F(ζ + ζ⁻¹) ≤ F(ζ)` -/

/-
The real generator `ζ + ζ⁻¹` lies in the field generated by `ζ`.
-/
theorem zeta_add_inv_mem_adjoin_zeta
    {F K : Type*} [Field F] [Field K] [Algebra F K]
    (ζ : K) (_hζ : ζ ≠ 0) :
    ζ + ζ⁻¹ ∈ IntermediateField.adjoin F ({ζ} : Set K) := by
  exact Subalgebra.add_mem _ ( IntermediateField.subset_adjoin F { ζ } ( Set.mem_singleton _ ) ) ( IntermediateField.inv_mem _ ( IntermediateField.subset_adjoin F { ζ } ( Set.mem_singleton _ ) ) )

/-
`F(ζ + ζ⁻¹) ≤ F(ζ)`.
-/
theorem adjoin_zeta_add_inv_le_adjoin_zeta
    {F K : Type*} [Field F] [Field K] [Algebra F K]
    (ζ : K) (_hζ : ζ ≠ 0) :
    IntermediateField.adjoin F ({ζ + ζ⁻¹} : Set K) ≤
      IntermediateField.adjoin F ({ζ} : Set K) := by
  exact IntermediateField.adjoin_le_iff.mpr ( Set.singleton_subset_iff.mpr ( by exact IntermediateField.add_mem _ ( IntermediateField.mem_adjoin_simple_self F ζ ) ( IntermediateField.inv_mem _ ( IntermediateField.mem_adjoin_simple_self F ζ ) ) ) )

/-! ### Integrality: `ζ` is integral over `F(ζ + ζ⁻¹)` -/

/-
`ζ` is integral over the intermediate field `F(ζ + ζ⁻¹)`, witnessed by the
monic quadratic `X² - (ζ+ζ⁻¹)X + 1`.
-/
theorem isIntegral_zeta_over_adjoin_zeta_add_inv
    {F K : Type*} [Field F] [Field K] [Algebra F K] (ζ : K) (hζ : ζ ≠ 0) :
    IsIntegral (IntermediateField.adjoin F ({ζ + ζ⁻¹} : Set K)) ζ := by
  -- Consider the monic polynomial $p(x) = x^2 - C(α)x + 1$ where $α = \zeta + \zeta^{-1}$.
  set α : ↥(IntermediateField.adjoin F ({ζ + ζ⁻¹} : Set K)) := ⟨ζ + ζ⁻¹, by
    exact IntermediateField.subset_adjoin F _ ( Set.mem_singleton _ )⟩
  generalize_proofs at *;
  refine' ⟨ Polynomial.X ^ 2 - Polynomial.C α * Polynomial.X + 1, _, _ ⟩;
  · erw [ Polynomial.Monic, Polynomial.leadingCoeff, Polynomial.natDegree_add_C, Polynomial.natDegree_sub_eq_left_of_natDegree_lt ] <;> simp +decide [ Polynomial.coeff_eq_zero_of_natDegree_lt ];
    exact lt_of_le_of_lt ( Polynomial.natDegree_C_mul_le _ _ ) ( by simp +decide );
  · convert zeta_quadratic_relation ζ hζ using 1 ; ring;
    simp +decide [hζ];
    convert zeta_quadratic_relation ζ hζ using 1 ; ring

/-! ### Degree bound -/

/-
The degree of the minimal polynomial of `ζ` over `F(ζ + ζ⁻¹)` divides 2.
-/
theorem minpoly_zeta_degree_le_two
    {F K : Type*} [Field F] [Field K] [Algebra F K] (ζ : K) (hζ : ζ ≠ 0) :
    (minpoly (IntermediateField.adjoin F ({ζ + ζ⁻¹} : Set K)) ζ).natDegree ≤ 2 := by
  -- Since ζ is integral over F(ζ + ζ⁻¹), the minimal polynomial m of ζ over F(ζ + ζ⁻¹) divides any polynomial p with ζ as a root.
  have h_div : minpoly (IntermediateField.adjoin F ({ζ + ζ⁻¹} : Set K)) ζ ∣ (Polynomial.X ^ 2 - Polynomial.C ⟨ζ + ζ⁻¹, by
    exact IntermediateField.subset_adjoin F _ ( Set.mem_singleton _ )⟩ * Polynomial.X + 1) := by
    convert minpoly.isIntegrallyClosed_dvd ( isIntegral_zeta_over_adjoin_zeta_add_inv ζ hζ ) _;
    -- Substitute ζ into the polynomial and simplify.
    simp [Polynomial.aeval_def, zeta_quadratic_relation ζ hζ]
  generalize_proofs at *;
  refine' le_trans ( Polynomial.natDegree_le_of_dvd h_div _ ) _;
  · exact ne_of_apply_ne ( Polynomial.eval 0 ) ( by simp +decide );
  · rw [ Polynomial.natDegree_add_eq_left_of_natDegree_lt ] <;> rw [ Polynomial.natDegree_sub_eq_left_of_natDegree_lt ] <;> norm_num;
    · exact lt_of_le_of_lt ( Polynomial.natDegree_C_mul_le _ _ ) ( by norm_num );
    · exact lt_of_le_of_lt ( Polynomial.natDegree_C_mul_le _ _ ) ( by norm_num )

/-! ### Primitive root specialization -/

/-
For a primitive `n`-th root of unity with `n ≥ 3`, `ζ + ζ⁻¹ ≠ 2`
(equivalently, `ζ ≠ 1`).
-/
theorem primitiveRoot_add_inv_ne_two
    {K : Type*} [Field K] [CharZero K]
    {n : ℕ} (hn : 2 < n)
    (ζ : K) (hζ : IsPrimitiveRoot ζ n) :
    ζ + ζ⁻¹ ≠ 2 := by
  -- Since ζ is a primitive root of unity, we know that ζ ≠ 1.
  have hζ_ne_one : ζ ≠ 1 := by
    exact hζ.ne_one ( by linarith );
  grind

/-
A primitive `n`-th root with `n ≥ 3` is not equal to its inverse.
-/
theorem primitiveRoot_ne_inv
    {K : Type*} [Field K] [CharZero K]
    {n : ℕ} (hn : 2 < n)
    (ζ : K) (hζ : IsPrimitiveRoot ζ n) :
    ζ ≠ ζ⁻¹ := by
  -- If ζ = ζ⁻¹, then squaring both sides would give ζ^2 = 1.
  by_contra h_eq
  have h_sq : ζ^2 = 1 := by
    rw [ eq_comm, inv_eq_one_div, div_eq_iff ] at h_eq <;> norm_num at *;
    · exact mul_self_eq_one_iff.mp h_eq.symm;
    · exact hζ.ne_zero ( by linarith );
  exact absurd ( hζ.2 2 h_sq ) ( by rw [ Nat.dvd_iff_mod_eq_zero, Nat.mod_eq_of_lt ] <;> linarith )

end