/-
# The Berggren Groupoid of Pythagorean Triples

This file was previously an unresolved pointer (`../../Pythagorean/BerggrenGroupoid.lean`)
and therefore did not compile.  It is restored here with a self-contained
development of the *groupoid* structure behind Berggren's tree of Pythagorean
triples, built on the existing catalogue module
`Bridges.BerggrenTrees.BerggrenPythagoreanCore` (whose `bergA/bergB/bergC` moves
and inverses `invA/invB/invC` are reused rather than re-invented).

The three Berggren moves are bijections of `ℤ³` preserving the Lorentz form
`a² + b² − c²`; hence the groupoid they generate acts on the null cone, i.e. on
Pythagorean triples.  `bergConnected` is the equivalence relation generated by
the moves, and the main results say that it is an equivalence relation whose
classes are contained in level sets of the Lorentz form — in particular every
triple connected to `(3,4,5)` is Pythagorean.
-/

import Mathlib
import Bridges.BerggrenTrees.BerggrenPythagoreanCore

namespace BerggrenGroupoid

/-- Uncurried Berggren move `A`. -/
def moveA (p : ℤ × ℤ × ℤ) : ℤ × ℤ × ℤ := bergA p.1 p.2.1 p.2.2

/-- Uncurried Berggren move `B`. -/
def moveB (p : ℤ × ℤ × ℤ) : ℤ × ℤ × ℤ := bergB p.1 p.2.1 p.2.2

/-- Uncurried Berggren move `C`. -/
def moveC (p : ℤ × ℤ × ℤ) : ℤ × ℤ × ℤ := bergC p.1 p.2.1 p.2.2

/-- Uncurried inverse move `A`. -/
def moveA' (p : ℤ × ℤ × ℤ) : ℤ × ℤ × ℤ := invA p.1 p.2.1 p.2.2

/-- Uncurried inverse move `B`. -/
def moveB' (p : ℤ × ℤ × ℤ) : ℤ × ℤ × ℤ := invB p.1 p.2.1 p.2.2

/-- Uncurried inverse move `C`. -/
def moveC' (p : ℤ × ℤ × ℤ) : ℤ × ℤ × ℤ := invC p.1 p.2.1 p.2.2

/-- The Lorentz form as a function of a triple. -/
def lorentz (p : ℤ × ℤ × ℤ) : ℤ := lorentzQ p.1 p.2.1 p.2.2

/-! ## The moves are bijections -/

theorem moveA'_moveA (p : ℤ × ℤ × ℤ) : moveA' (moveA p) = p := by
  obtain ⟨a, b, c⟩ := p
  simpa [moveA, moveA'] using fwd_inv_A a b c

theorem moveB'_moveB (p : ℤ × ℤ × ℤ) : moveB' (moveB p) = p := by
  obtain ⟨a, b, c⟩ := p
  simpa [moveB, moveB'] using fwd_inv_B a b c

theorem moveC'_moveC (p : ℤ × ℤ × ℤ) : moveC' (moveC p) = p := by
  obtain ⟨a, b, c⟩ := p
  simpa [moveC, moveC'] using fwd_inv_C a b c

theorem moveA_moveA' (p : ℤ × ℤ × ℤ) : moveA (moveA' p) = p := by
  obtain ⟨a, b, c⟩ := p
  simpa [moveA, moveA'] using inv_fwd_A a b c

theorem moveB_moveB' (p : ℤ × ℤ × ℤ) : moveB (moveB' p) = p := by
  obtain ⟨a, b, c⟩ := p
  simpa [moveB, moveB'] using inv_fwd_B a b c

theorem moveC_moveC' (p : ℤ × ℤ × ℤ) : moveC (moveC' p) = p := by
  obtain ⟨a, b, c⟩ := p
  simpa [moveC, moveC'] using inv_fwd_C a b c

theorem moveA_bijective : Function.Bijective moveA :=
  Function.bijective_iff_has_inverse.2 ⟨moveA', moveA'_moveA, moveA_moveA'⟩

theorem moveB_bijective : Function.Bijective moveB :=
  Function.bijective_iff_has_inverse.2 ⟨moveB', moveB'_moveB, moveB_moveB'⟩

theorem moveC_bijective : Function.Bijective moveC :=
  Function.bijective_iff_has_inverse.2 ⟨moveC', moveC'_moveC, moveC_moveC'⟩

/-! ## The moves preserve the Lorentz form -/

theorem lorentz_moveA (p : ℤ × ℤ × ℤ) : lorentz (moveA p) = lorentz p := by
  obtain ⟨a, b, c⟩ := p
  simp only [lorentz, moveA, bergA, lorentzQ]
  ring

theorem lorentz_moveB (p : ℤ × ℤ × ℤ) : lorentz (moveB p) = lorentz p := by
  obtain ⟨a, b, c⟩ := p
  simp only [lorentz, moveB, bergB, lorentzQ]
  ring

theorem lorentz_moveC (p : ℤ × ℤ × ℤ) : lorentz (moveC p) = lorentz p := by
  obtain ⟨a, b, c⟩ := p
  simp only [lorentz, moveC, bergC, lorentzQ]
  ring

/-! ## The groupoid generated by the moves -/

/-- One generating move of the Berggren groupoid. -/
inductive BergMove : ℤ × ℤ × ℤ → ℤ × ℤ × ℤ → Prop
  | a (p : ℤ × ℤ × ℤ) : BergMove p (moveA p)
  | b (p : ℤ × ℤ × ℤ) : BergMove p (moveB p)
  | c (p : ℤ × ℤ × ℤ) : BergMove p (moveC p)

/-- Two triples are *Berggren connected* when one can be transformed into the
other by a finite sequence of moves and inverse moves: this is the morphism
relation of the groupoid generated by `BergMove`. -/
def BergConnected : ℤ × ℤ × ℤ → ℤ × ℤ × ℤ → Prop :=
  Relation.EqvGen BergMove

theorem bergConnected_refl (p : ℤ × ℤ × ℤ) : BergConnected p p :=
  Relation.EqvGen.refl p

theorem bergConnected_symm {p q : ℤ × ℤ × ℤ} (h : BergConnected p q) :
    BergConnected q p :=
  Relation.EqvGen.symm _ _ h

theorem bergConnected_trans {p q r : ℤ × ℤ × ℤ}
    (h₁ : BergConnected p q) (h₂ : BergConnected q r) : BergConnected p r :=
  Relation.EqvGen.trans _ _ _ h₁ h₂

theorem bergConnected_equivalence : Equivalence BergConnected :=
  ⟨bergConnected_refl, fun h => bergConnected_symm h, fun h₁ h₂ => bergConnected_trans h₁ h₂⟩

/-- A single move preserves the Lorentz form. -/
theorem lorentz_of_bergMove {p q : ℤ × ℤ × ℤ} (h : BergMove p q) :
    lorentz q = lorentz p := by
  cases h with
  | a => exact lorentz_moveA p
  | b => exact lorentz_moveB p
  | c => exact lorentz_moveC p

/-- **The Lorentz form is a groupoid invariant.** -/
theorem lorentz_of_bergConnected {p q : ℤ × ℤ × ℤ} (h : BergConnected p q) :
    lorentz q = lorentz p := by
  induction h with
  | rel x y hxy => exact lorentz_of_bergMove hxy
  | refl x => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih₁ ih₂ => exact ih₂.trans ih₁

/-- **The groupoid acts on the null cone**: anything connected to a Pythagorean
triple is again a Pythagorean triple. -/
theorem isPythag_of_bergConnected {p q : ℤ × ℤ × ℤ}
    (h : BergConnected p q) (hp : IsPythag p.1 p.2.1 p.2.2) :
    IsPythag q.1 q.2.1 q.2.2 := by
  rw [isPythag_iff_lorentzQ_zero] at hp ⊢
  have := lorentz_of_bergConnected h
  simpa [lorentz, hp] using this

/-- Every triple in the Berggren tree rooted at `(3,4,5)` is Pythagorean. -/
theorem isPythag_of_connected_to_root {q : ℤ × ℤ × ℤ}
    (h : BergConnected (3, 4, 5) q) : IsPythag q.1 q.2.1 q.2.2 := by
  refine isPythag_of_bergConnected h ?_
  simp [IsPythag]

/-- The three classical children of `(3,4,5)` are Berggren connected to it. -/
theorem connected_children :
    BergConnected (3, 4, 5) (5, 12, 13) ∧
    BergConnected (3, 4, 5) (21, 20, 29) ∧
    BergConnected (3, 4, 5) (15, 8, 17) := by
  refine ⟨?_, ?_, ?_⟩
  · have h : BergMove ((3 : ℤ), (4 : ℤ), (5 : ℤ)) (moveA (3, 4, 5)) := BergMove.a _
    have hval : moveA ((3 : ℤ), (4 : ℤ), (5 : ℤ)) = (5, 12, 13) := by
      simp [moveA, bergA]
    rw [hval] at h
    exact Relation.EqvGen.rel _ _ h
  · have h : BergMove ((3 : ℤ), (4 : ℤ), (5 : ℤ)) (moveB (3, 4, 5)) := BergMove.b _
    have hval : moveB ((3 : ℤ), (4 : ℤ), (5 : ℤ)) = (21, 20, 29) := by
      simp [moveB, bergB]
    rw [hval] at h
    exact Relation.EqvGen.rel _ _ h
  · have h : BergMove ((3 : ℤ), (4 : ℤ), (5 : ℤ)) (moveC (3, 4, 5)) := BergMove.c _
    have hval : moveC ((3 : ℤ), (4 : ℤ), (5 : ℤ)) = (15, 8, 17) := by
      simp [moveC, bergC]
    rw [hval] at h
    exact Relation.EqvGen.rel _ _ h

end BerggrenGroupoid