/-
  Natural Gradient Convergence on Dually Flat Manifolds: Definitions
  ==================================================================

  Core definitions for formalizing natural gradient dynamics in information
  geometry, including Bregman divergences, dually flat structure, natural
  gradient updates, and convergence-relevant quantities.

  These definitions build on `Geometry.InformationGeometry.Defs` and provide
  the infrastructure for proving convergence theorems in
  `Geometry.InformationGeometry.NaturalGradient.Convergence`.
-/

import Mathlib

open Finset BigOperators

noncomputable section

/-! ## Bregman Divergence -/

/-- The Bregman divergence generated by a differentiable convex function `ψ`
    with gradient map `gradψ`:
      D_ψ(x, y) = ψ(x) - ψ(y) - ⟨∇ψ(y), x - y⟩
    This is the fundamental geometric quantity in dually flat geometry. -/
def BregmanDiv {d : ℕ}
    (ψ : (Fin d → ℝ) → ℝ)
    (gradψ : (Fin d → ℝ) → (Fin d → ℝ))
    (x y : Fin d → ℝ) : ℝ :=
  ψ x - ψ y - ∑ i : Fin d, gradψ y i * (x i - y i)

/-! ## Harmonic Step Sizes -/

/-- Harmonic step size: α_t = 1/(t+1). -/
def harmonicStep (t : ℕ) : ℝ := 1 / ((t : ℝ) + 1)

/-- Harmonic sum: H(t) = ∑_{k=0}^{t-1} 1/(k+1) = ∑_{k=1}^{t} 1/k.
    This is the partial harmonic series. -/
def harmonicSum : ℕ → ℝ
  | 0 => 0
  | t + 1 => harmonicSum t + harmonicStep t

/-! ## Natural Gradient System -/

/-- A dually flat natural gradient system bundles all the data needed to
    define and analyze natural gradient iterations on an exponential family.

    This structure encodes:
    - A convex potential `ψ` (log-partition function)
    - Its gradient `gradψ` (expectation parameters η = ∇ψ(θ))
    - The Fisher information matrix `I(θ) = Hess ψ(θ)`
    - A loss function `L`
    - The natural gradient direction `natGradDir θ = I(θ)⁻¹ ∇L(θ)` -/
structure IsDuallyFlatNaturalGradientSystem (d : ℕ) where
  /-- Log-partition (convex potential) -/
  ψ : (Fin d → ℝ) → ℝ
  /-- Gradient of ψ (expectation parameter map) -/
  gradψ : (Fin d → ℝ) → (Fin d → ℝ)
  /-- Loss function -/
  L : (Fin d → ℝ) → ℝ
  /-- Natural gradient direction: I(θ)⁻¹ ∇L(θ) -/
  natGradDir : (Fin d → ℝ) → (Fin d → ℝ)

/-- One step of natural gradient descent:
      θ_{t+1} = θ_t - α · natGradDir(θ_t) -/
def NaturalGradientStep {d : ℕ}
    (S : IsDuallyFlatNaturalGradientSystem d)
    (α : ℝ) (θ : Fin d → ℝ) : Fin d → ℝ :=
  fun i => θ i - α * S.natGradDir θ i

/-- The sequence of natural gradient iterates with given step sizes. -/
def ngdSequence {d : ℕ}
    (S : IsDuallyFlatNaturalGradientSystem d)
    (stepSize : ℕ → ℝ)
    (θ₀ : Fin d → ℝ) : ℕ → (Fin d → ℝ)
  | 0 => θ₀
  | t + 1 => NaturalGradientStep S (stepSize t) (ngdSequence S stepSize θ₀ t)

/-- The sequence of natural gradient iterates with harmonic step sizes. -/
def ngdHarmonicSeq {d : ℕ}
    (S : IsDuallyFlatNaturalGradientSystem d)
    (θ₀ : Fin d → ℝ) : ℕ → (Fin d → ℝ) :=
  ngdSequence S harmonicStep θ₀

/-! ## Relative Smoothness -/

/-- Relative smoothness of L in the Fisher metric: a constant `C` such that
    the natural gradient step satisfies a one-step Bregman descent inequality.
    This abstracts the key analytic condition needed for convergence. -/
structure RelativeSmoothInFisherMetric {d : ℕ}
    (S : IsDuallyFlatNaturalGradientSystem d)
    (C : ℝ) : Prop where
  /-- The one-step descent inequality:
      D_ψ(θstar, θ_{t+1}) ≤ D_ψ(θstar, θ_t) - α(L(θ_t) - L(θstar)) + C·α² -/
  descent_ineq : ∀ (θstar θ : Fin d → ℝ) (α : ℝ),
    0 ≤ α →
    BregmanDiv S.ψ S.gradψ θstar (NaturalGradientStep S α θ) ≤
    BregmanDiv S.ψ S.gradψ θstar θ - α * (S.L θ - S.L θstar) + C * α ^ 2

/-! ## Convexity in Expectation Coordinates -/

/-- A loss function is convex in expectation coordinates if
    L(θ) = L̃(η(θ)) where L̃ is convex and η = ∇ψ. -/
def ExpectationCoordinateConvex {d : ℕ}
    (S : IsDuallyFlatNaturalGradientSystem d) : Prop :=
  ∃ dualLoss : (Fin d → ℝ) → ℝ,
    (∀ θ, S.L θ = dualLoss (S.gradψ θ)) ∧
    ConvexOn ℝ Set.univ dualLoss

/-! ## Accelerated Dual Natural Gradient -/

/-- Accelerated dual natural gradient system: operates in η-coordinates
    with Nesterov-type momentum. -/
structure AcceleratedDualNGD (d : ℕ) where
  /-- Dual iterate sequence -/
  η : ℕ → (Fin d → ℝ)
  /-- Momentum sequence -/
  y : ℕ → (Fin d → ℝ)
  /-- Step sizes -/
  α : ℕ → ℝ
  /-- Momentum coefficients -/
  β : ℕ → ℝ

/-! ## Bregman Lyapunov Energy -/

/-- The Bregman Lyapunov energy at time t, measuring distance to optimum. -/
def BregmanLyapunov {d : ℕ}
    (S : IsDuallyFlatNaturalGradientSystem d)
    (θstar : Fin d → ℝ)
    (θseq : ℕ → (Fin d → ℝ)) (t : ℕ) : ℝ :=
  BregmanDiv S.ψ S.gradψ θstar (θseq t)

end