/-
# Topological Quantum Computing: Braiding Universality — Extensions

This module **extends** `Catalog.Speculative.AutoResearch.BraidingUniversality`
(Cycle 4471cf7c) with new, fully-proved structural results about the algebraic
and number-theoretic kernel of anyon-braiding universality. The parent file
established:
* `BraidingUniversality.burau_braid_relation` — the reduced Burau matrices of
  `B₃` satisfy the Yang–Baxter braid relation;
* `BraidingUniversality.burau_det₁`/`burau_det₂` — both generators have
  determinant `-t`;
* `BraidingUniversality.phaseGate_orbit_dense` /
  `BraidingUniversality.fibonacci_phase_not_dense` — the irrationality
  dichotomy for density of a single phase gate on the torus;
* `BraidingUniversality.su2_braiding_dense` — the full `SU(2)` density
  *conjecture* (still open, left as `sorry`, requires the classification of
  closed subgroups of `SU(2)`).

Here we add four genuinely new theorems that strengthen this foundation into a
*group-representation* statement and a *sharp order dichotomy*:

1. **Burau invertibility, witnessed (`burauSigma₁_mul_inv`, `burau_isUnit₁`).**
   We exhibit the explicit inverse matrix of `σ₁` and prove it is a two-sided
   inverse for `t ≠ 0`, upgrading `burau_det₁` from "determinant `≠ 0`" to a
   constructive unit witness in `GL₂(ℂ)`.

2. **The full twist is central and scalar (`burau_fullTwist_scalar`,
   `burau_fullTwist_central`).** The Burau image of the full twist `(σ₁σ₂)³`
   — the generator of the center `Z(B₃)` — is exactly the scalar matrix
   `t³ · I`. This is the linear shadow of the *framing anomaly / topological
   spin* of the anyon, and it implies the full twist commutes with every gate.

3. **Markov-trace value of the full twist (`burau_fullTwist_trace`).** Its
   (unnormalized Markov) trace is `2t³`, the elementary input to the Jones
   polynomial of the closure of `(σ₁σ₂)³` (a torus link).

4. **Sharp order dichotomy on the torus (`rational_phase_finite_order`,
   `irrational_phase_injective`).** A phase gate has *finite order* exactly
   when its phase is rational, and its orbit map is *injective* (infinite
   order) exactly when the phase is irrational. This converts the parent file's
   density dichotomy into the corresponding subgroup-order dichotomy, making the
   Fibonacci `4/5` obstruction precise: order dividing `5`.

We also re-derive, as a corollary of the parent's `phaseGate_orbit_dense`, that
the irrational phase `√2` yields a dense braiding gate (`sqrt2_phase_dense`),
illustrating cross-use of the catalog result.
-/
import Mathlib
import Catalog.Speculative.AutoResearch.BraidingUniversality

open Matrix

namespace BraidingUniversality

noncomputable section

/-! ## I. Burau invertibility, witnessed

`burau_det₁` only says `det = -t ≠ 0`. Here we produce the explicit inverse and
prove it is two-sided, so the Burau map provably lands in the unit group of the
matrix ring (i.e. `GL₂(ℂ)`) — the precise sense in which braiding gives a
*group* representation of `B₃`. -/

/-- The explicit inverse matrix of the first Burau generator `σ₁` (valid for
`t ≠ 0`). -/
def burauSigma₁Inv (t : ℂ) : Matrix (Fin 2) (Fin 2) ℂ := !![-t⁻¹, t⁻¹; 0, 1]

-- !-- σ₁ · σ₁⁻¹ = I -- !--
-- !-- Entrywise expansion; the only nontrivial entry cancels via t·t⁻¹ = 1 (field_simp). -- !--
/-- `burauSigma₁Inv` is a right inverse of `burauSigma₁` for `t ≠ 0`. -/
theorem burauSigma₁_mul_inv (t : ℂ) (ht : t ≠ 0) :
    burauSigma₁ t * burauSigma₁Inv t = (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [burauSigma₁, burauSigma₁Inv, Matrix.mul_apply, Fin.sum_univ_two] <;>
    field_simp <;> ring

-- !-- σ₁⁻¹ · σ₁ = I -- !--
-- !-- Same entrywise expansion on the other side. -- !--
/-- `burauSigma₁Inv` is a left inverse of `burauSigma₁` for `t ≠ 0`. -/
theorem burauSigma₁_inv_mul (t : ℂ) (ht : t ≠ 0) :
    burauSigma₁Inv t * burauSigma₁ t = (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [burauSigma₁, burauSigma₁Inv, Matrix.mul_apply, Fin.sum_univ_two] <;>
    field_simp

-- !-- σ₁ is a unit in the matrix ring -- !--
-- !-- det σ₁ = -t (burau_det₁) is a nonzero scalar, so isUnit_iff_isUnit_det applies. -- !--
/-- The first Burau generator is a **unit** of the matrix ring `M₂(ℂ)` for
`t ≠ 0`, i.e. an element of `GL₂(ℂ)`. Upgrades `burau_det₁`. -/
theorem burau_isUnit₁ (t : ℂ) (ht : t ≠ 0) : IsUnit (burauSigma₁ t) := by
  rw [Matrix.isUnit_iff_isUnit_det, burau_det₁]
  exact (isUnit_iff_ne_zero).2 (by simpa using ht)

/-! ## II. The full twist `(σ₁σ₂)³` is scalar, hence central

The center of `B₃` is the infinite cyclic group generated by the **full twist**
`Δ² = (σ₁σ₂)³`. Under the Burau representation it must therefore map to a matrix
commuting with the whole image; we compute it exactly: it is the scalar `t³ · I`.
Physically `t³` is the linear avatar of the anyon's topological spin / framing
anomaly. -/

-- !-- Full twist is scalar -- !--
-- !-- Expand (σ₁σ₂)³ entrywise; direct computation gives !![t³,0;0,t³] = t³ • I. -- !--
/-- **Full twist is scalar.** The Burau image of the central element
`(σ₁σ₂)³ ∈ Z(B₃)` is exactly `t³ · I`. -/
theorem burau_fullTwist_scalar (t : ℂ) :
    (burauSigma₁ t * burauSigma₂ t) ^ 3
      = (t ^ 3) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  simp only [pow_succ, pow_zero, one_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [burauSigma₁, burauSigma₂, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.smul_apply]

-- !-- Full twist is central -- !--
-- !-- Being a scalar matrix t³•I, it commutes with every M: smul_mul/mul_smul. -- !--
/-- **Full twist is central.** Because its Burau image is scalar, the full twist
commutes with every gate `M` in the representation. This is the linear form of
`(σ₁σ₂)³ ∈ Z(B₃)`. -/
theorem burau_fullTwist_central (t : ℂ) (M : Matrix (Fin 2) (Fin 2) ℂ) :
    (burauSigma₁ t * burauSigma₂ t) ^ 3 * M
      = M * (burauSigma₁ t * burauSigma₂ t) ^ 3 := by
  rw [burau_fullTwist_scalar]
  rw [Matrix.smul_mul, Matrix.mul_smul, one_mul, Matrix.mul_one]

-- !-- Markov trace of the full twist -- !--
-- !-- trace (t³ • I₂) = t³ · trace I₂ = t³ · 2. -- !--
/-- **Markov-trace value.** The (unnormalized) trace of the Burau full twist is
`2t³`; this is the elementary trace input feeding the Jones polynomial of the
closure of `(σ₁σ₂)³` (a torus link). -/
theorem burau_fullTwist_trace (t : ℂ) :
    Matrix.trace ((burauSigma₁ t * burauSigma₂ t) ^ 3) = 2 * t ^ 3 := by
  rw [burau_fullTwist_scalar, Matrix.trace_smul, Matrix.trace_one]
  simp [Fintype.card_fin]
  ring

-- !-- Lab Notebook: burau_fullTwist_scalar / _central / _trace -- !--
-- !-- Hypothesis: the central full twist (σ₁σ₂)³ acts as a scalar in reduced Burau. -- !--
-- !-- Result: it equals t³ • I exactly, hence commutes with all gates; trace = 2t³. -- !--
-- !-- Insight: the center Z(B₃) = ⟨(σ₁σ₂)³⟩ is sent to the SCALARS — the abelian -- !--
-- !--   part of GL₂. This is precisely why the full twist carries no quantum-gate -- !--
-- !--   information beyond a global phase: scalar matrices are global phases, the -- !--
-- !--   framing/topological-spin anomaly of the anyon. -- !--
-- !-- Failure analysis: none; the computation is a polynomial identity closed by -- !--
-- !--   entrywise simp after Fin.sum_univ_two unfolding. -- !--
-- !-- End Lab Notebook -- !--

/-! ## III. Sharp order dichotomy on the maximal torus

The parent file proved *density* of a phase orbit is equivalent to irrationality
of the phase. Here we prove the companion *order* dichotomy at the level of the
group element itself: rational phase ⇒ finite order; irrational phase ⇒ the
orbit map is injective (infinite order). Together these pin down the structure of
the cyclic subgroup generated by a single braiding phase gate. -/

-- !-- Rational phase has finite order -- !--
-- !-- q • (k/q) = k and ↑(k:ℝ) = 0 in AddCircle 1 since k is an integer multiple of 1. -- !--
/-- **Rational phase ⇒ finite order.** A phase gate with rational phase `k/q`
(period `1`) satisfies `q • (k/q) = 0` on the torus; its order divides `q`. The
Fibonacci `4/5` obstruction is the case `k = 4, q = 5`. -/
theorem rational_phase_finite_order (k : ℤ) (q : ℕ) (hq : 0 < q) :
    (q : ℤ) • (((k : ℝ) / q : ℝ) : AddCircle (1 : ℝ)) = 0 := by
  rw [← AddCircle.coe_zsmul, AddCircle.coe_eq_zero_iff]
  refine ⟨k, ?_⟩
  have hq' : (q : ℝ) ≠ 0 := by exact_mod_cast hq.ne'
  simp only [zsmul_eq_mul]
  push_cast
  field_simp

-- !-- Irrational phase has infinite order -- !--
-- !-- n•a = m•a ⇒ (n-m)a ∈ ℤ; if n≠m then a = j/(n-m) is rational, contradiction. -- !--
/-- **Irrational phase ⇒ infinite order.** If the phase `a` is irrational, the
orbit map `n ↦ n • a` on the torus is injective, so the generated cyclic
subgroup is free of rank one (infinite). This is the order-theoretic companion
of `phaseGate_orbit_dense`. -/
theorem irrational_phase_injective {a : ℝ} (h : Irrational a) :
    Function.Injective (fun n : ℤ => n • ((a : AddCircle (1 : ℝ)))) := by
  intro n m hnm
  simp only at hnm
  rw [← sub_eq_zero, ← sub_smul, ← AddCircle.coe_zsmul,
    AddCircle.coe_eq_zero_iff] at hnm
  obtain ⟨j, hj⟩ := hnm
  simp only [zsmul_eq_mul, mul_one] at hj
  by_contra hne
  have hd : ((n : ℝ) - m) ≠ 0 := by
    simp only [ne_eq, sub_eq_zero]
    exact_mod_cast fun hh => hne (by exact_mod_cast hh)
  apply h
  refine ⟨(j : ℚ) / (n - m : ℚ), ?_⟩
  push_cast at hj ⊢
  rw [div_eq_iff hd]
  linarith [hj]

-- !-- Lab Notebook: order dichotomy -- !--
-- !-- Hypothesis: finite order ↔ rational phase, dual to the density dichotomy. -- !--
-- !-- Result: rational k/q ⇒ q-torsion; irrational ⇒ injective orbit (infinite order). -- !--
-- !-- Insight: this is the SAME number-theoretic split as density, now read on the -- !--
-- !--   subgroup itself: rational phases generate finite cyclic groups (never dense), -- !--
-- !--   irrational phases generate Z (dense). The Fibonacci 4/5 lands in the finite -- !--
-- !--   bucket (order | 5), re-deriving fibonacci_phase_not_dense at the group level. -- !--
-- !-- Failure analysis: the cast of the rational witness j/(n-m) needed div_eq_iff -- !--
-- !--   rather than eq_div_iff; otherwise straightforward. -- !--
-- !-- End Lab Notebook -- !--

/-! ## IV. Cross-use of the catalog density result -/

-- !-- √2 phase is dense -- !--
-- !-- √2 is irrational (irrational_sqrt_two), so phaseGate_orbit_dense applies directly. -- !--
/-- **Corollary (irrational braiding phase is universal on the torus).** A phase
gate at the irrational angle `√2` has dense orbit on the torus — a positive
companion to the Fibonacci `4/5` counterexample, obtained directly from the
parent theorem `phaseGate_orbit_dense`. -/
theorem sqrt2_phase_dense :
    DenseRange (fun n : ℤ => n • ((Real.sqrt 2 : AddCircle (1 : ℝ)))) :=
  phaseGate_orbit_dense irrational_sqrt_two

/-! ## V. Generalization & boundary of the best theorem

The "best" theorem here is `burau_fullTwist_scalar` (the full twist is the
scalar `t³ · I`). Two natural follow-ups: -/

/-- **Generalization.** The `k`-th power of the full twist is the scalar
`t^(3k) · I`, so the whole center `Z(B₃) ≅ ℤ` maps into the scalar subgroup
`{t^(3k) · I}`. Derived from `burau_fullTwist_scalar` via `smul_pow`. -/
theorem burau_fullTwist_pow_scalar (t : ℂ) (k : ℕ) :
    ((burauSigma₁ t * burauSigma₂ t) ^ 3) ^ k
      = (t ^ (3 * k)) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  rw [burau_fullTwist_scalar, smul_pow, one_pow, ← pow_mul, mul_comm 3 k]

/-- **Boundary case.** At `t = 0` the Burau generators degenerate: the would-be
inverse `burauSigma₁Inv` is no longer an inverse (determinant `-t = 0`), so the
representation leaves `GL₂(ℂ)`. Concretely the full twist collapses to the zero
matrix, witnessing the breakdown of universality at the degenerate loop value. -/
theorem burau_fullTwist_degenerate :
    (burauSigma₁ (0 : ℂ) * burauSigma₂ (0 : ℂ)) ^ 3
      = (0 : Matrix (Fin 2) (Fin 2) ℂ) := by
  rw [burau_fullTwist_scalar]
  simp

end

end BraidingUniversality