import Mathlib

/-! # CatalogBuild.Speculative.AutoResearch.non_archimedean_factoring_oracle

Auto-generated by CycleMaster (Pi-Agent + Aristotle).
Domain: AI
Novelty: 0.85
Experiment: 2f4f3678
Date: 2026-04-25T04:30:21.046986+00:00
-/

/-
A p-adic lifting scheme that factors integers by analyzing the Newton polygon of a polynomial over Q_p.

Mathematical Concept: Use Hensel's lemma and p-adic valuation to construct a factoring oracle.
-/

/- The original theorem statement below is **false**: it claims that every natural number n > 1
   can be written as a product of two factors both strictly greater than 1. This fails for
   all prime numbers (e.g., n = 2, 3, 5, 7, ...). A prime p > 1 has no factorization
   p = a * b with a > 1 and b > 1.

theorem pAdic_factoring_oracle {p : ℕ} [Fact p.Prime] (n : ℕ) (hn : n > 1) :
    ∃ a b : ℕ, a * b = n ∧ a > 1 ∧ b > 1 := by
  sorry
-/

/-- Corrected version: A composite number (n > 1 and not prime) can always be
    non-trivially factored into two factors, each greater than 1.
    This is the mathematically correct formulation of the "factoring oracle" idea:
    composite numbers admit non-trivial factorizations. -/
theorem pAdic_factoring_oracle {p : ℕ} [Fact p.Prime] (n : ℕ) (hn : n > 1)
    (hc : ¬ Nat.Prime n) :
    ∃ a b : ℕ, a * b = n ∧ a > 1 ∧ b > 1 := by
  rcases Nat.exists_dvd_of_not_prime2 hn hc with ⟨k, hk₁, hk₂⟩
  exact ⟨k, n / k,
    by rw [Nat.mul_div_cancel' hk₁],
    Nat.one_lt_iff_ne_zero_and_ne_one.mpr ⟨by aesop_cat, by aesop_cat⟩,
    by nlinarith [Nat.div_mul_cancel hk₁]⟩
