import Mathlib

/-! # Stone Duality: a Boolean algebra is the clopen algebra of its Stone space

This file proves the object-level core of **Stone duality**: every Boolean algebra `B`
is isomorphic (as a Boolean algebra, hence as an order) to the Boolean algebra of
**clopen** subsets of its *Stone space*.

We realise the Stone space of `B` concretely as the **prime spectrum of the Boolean ring**
associated to `B`:
`StoneSpace B := PrimeSpectrum (AsBoolRing B)`.
Mathlib already equips this with a compact topology and the bridge
`BooleanAlgebra ↔ BooleanRing` (`AsBoolRing`, `toBoolRing`, `ofBoolRing`).

The *Stone map* sends `b : B` to the basic open `D(toBoolRing b)`, which is **clopen**
because in a Boolean ring `D(r)` has open complement `D(1 + r)`.  We prove that this map
is a Boolean-algebra homomorphism, that it is injective (Stone representation, via existence
of prime ideals avoiding any nonzero element), and that it is surjective onto the clopen
algebra (via compactness: every clopen is a finite union of basic opens).  Assembling these
gives the order isomorphism `B ≃o Clopens (StoneSpace B)`.

This bridges **logic** (Boolean algebras) and **topology** (Stone spaces / spectra), the
classical content of M. H. Stone's representation theorem.

-- !-- Lab Notebook -- !--
Hypothesis: Realising the Stone space as `PrimeSpectrum (AsBoolRing B)` lets us reuse
  Mathlib's commutative-ring spectrum API (`basicOpen`, `compactSpace`, `exists_le_maximal`)
  so that Stone duality becomes a short bridge rather than a from-scratch Zorn development.
Result: The Stone map `b ↦ D(toBoolRing b)` is a bijective Boolean homomorphism onto
  `Clopens (StoneSpace B)`; the order isomorphism `stoneOrderIso` is produced with `sorry = 0`.
Insight: The reduction "clopen ⇒ basic open" uses only two ring facts — idempotents have no
  nonzero nilpotents (so `D(r) = ∅ ↔ r = 0`) and `D(f) ∪ D(g) = D(f ⊔ g)` — plus compactness.
Failure analysis: Working directly with order ideals would have required hand-rolling the
  Boolean prime ideal theorem via Zorn; the ring spectrum route avoids that entirely.
-/

noncomputable section

open PrimeSpectrum TopologicalSpace

namespace StoneDuality

variable {R : Type*} [BooleanRing R]

/-! ### Basic opens of a Boolean ring spectrum are clopen -/

/-
!-- In a Boolean ring `r(1+r) = r + r² = r + r = 0` and `r + (1+r) = 1`, so for a prime `p`
exactly one of `r, 1+r` lies in `p`; hence the complement of `D(r)` is `D(1+r)`. -- !--
-/
theorem basicOpen_compl_eq (r : R) :
    (↑(basicOpen r) : Set (PrimeSpectrum R))ᶜ = ↑(basicOpen (1 + r)) := by
  simp +decide [basicOpen, Set.ext_iff]
  intro x
  constructor
  · intro hr h1r
    have h_contra : 1 ∈ x.asIdeal := by
      simpa using x.asIdeal.add_mem h1r (x.asIdeal.neg_mem hr)
    exact x.2.ne_top (by rw [Ideal.eq_top_iff_one]; exact h_contra)
  · have h_mem : (r * (1 + r)) ∈ x.asIdeal := by
      simp +decide
    exact fun h => x.2.mem_or_mem h_mem |> Or.resolve_right <| by simpa using h

/-
!-- `D(r)` is open (it is a basic open) and closed (its complement `D(1+r)` is open). -- !--
-/
theorem isClopen_basicOpen (r : R) :
    IsClopen (↑(basicOpen r) : Set (PrimeSpectrum R)) := by
  constructor
  · convert isClosed_compl_iff.mpr (basicOpen (1 + r)).isOpen
    rw [← basicOpen_compl_eq, compl_compl]
  · fconstructor
    exact {r}
    aesop

/-
!-- `D(f) ∪ D(g) = D(f ⊔ g)` where `f ⊔ g = f + g + f*g`: the ideal generated by `f ⊔ g`
equals the one generated by `{f,g}`, so they cut out the same basic open. -- !--
-/
theorem basicOpen_sup_eq (f g : R) :
    (↑(basicOpen f) ∪ ↑(basicOpen g) : Set (PrimeSpectrum R))
      = ↑(basicOpen (f + g + f * g)) := by
  ext x; simp
  constructor <;> intro h
  · cases' h with hf hg
    · intro hfg
      have hfg' : f * (f + g + f * g) = f := by
        simp +decide [mul_add, BooleanRing.mul_self]
        simp +decide [← mul_assoc, BooleanRing.mul_self]
        simp +decide [add_assoc, BooleanRing.add_self]
      exact hf (hfg' ▸ Ideal.mul_mem_left _ _ hfg)
    · contrapose! hg
      have := x.asIdeal.mul_mem_left g hg
      simp_all +decide [mul_add, mul_comm, mul_left_comm]
      simp_all +decide [BooleanRing.mul_self]
      simp_all +decide [add_assoc, add_left_comm, BooleanRing.add_self]
  · contrapose! h
    exact Ideal.add_mem _ (Ideal.add_mem _ h.1 h.2) (Ideal.mul_mem_right _ _ h.1)

/-
!-- A nonzero element of a Boolean ring is not nilpotent (it is idempotent), so `D(r) ≠ ∅`;
pick any point of it to get a prime avoiding `r`. -- !--
-/
theorem exists_prime_not_mem {r : R} (hr : r ≠ 0) :
    ∃ p : PrimeSpectrum R, r ∉ p.asIdeal := by
  -- `r ≠ 0` ⇒ `basicOpen r ≠ ∅`, since a basic open of a non-nilpotent element is nonempty.
  have h_basicOpen_nonempty : (basicOpen r : Set (PrimeSpectrum R)) ≠ ∅ := by
    have h_nilpotent : ¬IsNilpotent r := by
      rintro ⟨n, hn⟩
      cases ‹ℕ› <;> simp_all +decide [pow_succ]
      · exact hr (by rw [← one_mul r, hn, MulZeroClass.zero_mul])
      · induction ‹ℕ› <;> simp_all +decide [pow_succ, mul_assoc]
        simp_all +decide [BooleanRing.mul_self]
    contrapose! h_nilpotent
    convert PrimeSpectrum.basicOpen_eq_bot_iff _ |>.1 _
    exact SetLike.ext' h_nilpotent
  exact Set.nonempty_iff_ne_empty.2 h_basicOpen_nonempty

/-
!-- Every clopen subset of the spectrum of a Boolean ring is a basic open: it is open and
compact (closed in a compact space), so a finite union of basic opens, and a finite union
of basic opens is the basic open of the corresponding ring `⊔`. -- !--
-/
theorem exists_eq_basicOpen_of_isClopen {K : Set (PrimeSpectrum R)} (hK : IsClopen K) :
    ∃ r : R, K = ↑(basicOpen r) := by
  grind +suggestions

end StoneDuality

/-! ### The Stone space of a Boolean algebra and the Stone map -/

namespace StoneDuality

variable {B : Type*} [BooleanAlgebra B]

/-- The **Stone space** of a Boolean algebra `B`, realised as the prime spectrum of the
associated Boolean ring.  It is compact (and, in fact, a profinite/Stone space). -/
abbrev StoneSpace (B : Type*) [BooleanAlgebra B] : Type _ := PrimeSpectrum (AsBoolRing B)

/-- The **Stone map**: `b : B` maps to the clopen set `D(toBoolRing b)` of its Stone space. -/
def stoneClopen (b : B) : Clopens (StoneSpace B) :=
  ⟨↑(basicOpen (toBoolRing b)), isClopen_basicOpen _⟩

@[simp] theorem coe_stoneClopen (b : B) :
    (↑(stoneClopen b) : Set (StoneSpace B)) = ↑(basicOpen (toBoolRing b)) := rfl

/-! ### The Stone map is a Boolean-algebra homomorphism -/

theorem stoneClopen_bot : stoneClopen (⊥ : B) = ⊥ := by
  ext; simp +decide [stoneClopen]

theorem stoneClopen_top : stoneClopen (⊤ : B) = ⊤ := by
  ext x; simp [stoneClopen]

theorem stoneClopen_inf (a b : B) :
    stoneClopen (a ⊓ b) = stoneClopen a ⊓ stoneClopen b := by
  ext; simp +decide [stoneClopen, basicOpen_mul]

theorem stoneClopen_sup (a b : B) :
    stoneClopen (a ⊔ b) = stoneClopen a ⊔ stoneClopen b := by
  apply Clopens.ext
  convert basicOpen_sup_eq (toBoolRing a) (toBoolRing b) |> Eq.symm using 2
  convert coe_stoneClopen (a ⊔ b) using 2
  congr 1
  convert symmDiff_symmDiff_inf a b using 1

theorem stoneClopen_compl (a : B) :
    stoneClopen aᶜ = (stoneClopen a)ᶜ := by
  ext p
  constructor <;> intro h <;> have := p.2.1 <;> simp_all +decide
  · contrapose! h
    have h_compl : toBoolRing a * toBoolRing aᶜ = 0 := by
      simp +decide [← toBoolRing_inf]
    exact p.2.mem_or_mem (h_compl.symm ▸ p.1.zero_mem) |> Or.resolve_left <| by simpa using h
  · rw [show toBoolRing aᶜ = toBoolRing a + 1 by
          convert toBoolRing_symmDiff a ⊤ using 1
          simp +decide [symmDiff]]
    exact fun h' => this (by rw [Ideal.eq_top_iff_one]; simpa using p.asIdeal.sub_mem h' h)

/-! ### Injectivity (Stone representation theorem) -/

/-
!-- If `a ≠ b` then `a ⊓ bᶜ ≠ ⊥` or `b ⊓ aᶜ ≠ ⊥`; a prime witnessing the corresponding
nonzero ring element separates the two clopens, so the Stone map is injective. -- !--
-/
theorem stoneClopen_injective :
    Function.Injective (stoneClopen : B → Clopens (StoneSpace B)) := by
  intro a b hab
  have h_eq : a ⊓ bᶜ = ⊥ ∧ b ⊓ aᶜ = ⊥ := by
    have h_eq : stoneClopen (a ⊓ bᶜ) = ⊥ ∧ stoneClopen (b ⊓ aᶜ) = ⊥ := by
      grind +suggestions
    have h_eq : ∀ c : B, stoneClopen c = ⊥ → c = ⊥ := by
      intro c hc; contrapose! hc; simp_all +decide
      have := StoneDuality.exists_prime_not_mem
        (show toBoolRing c ≠ 0 from by simpa [toBoolRing_bot] using hc)
      obtain ⟨p, hp⟩ := this
      exact ne_of_apply_ne (fun x => x.1)
        (Set.Nonempty.ne_empty ⟨p, by simpa [StoneDuality.coe_stoneClopen] using hp⟩)
    exact ⟨h_eq _ (by tauto), h_eq _ (by tauto)⟩
  refine le_antisymm ?_ ?_ <;> simp_all +decide [← sdiff_eq]

/-! ### Surjectivity onto the clopen algebra -/

theorem stoneClopen_surjective :
    Function.Surjective (stoneClopen : B → Clopens (StoneSpace B)) := by
  intro K
  obtain ⟨r, hr⟩ := exists_eq_basicOpen_of_isClopen K.isClopen'
  use ofBoolRing r
  ext p
  simp
  convert Set.ext_iff.mp hr p using 1
  · aesop
  · exact Set.ext_iff.mp hr p

/-! ### `stoneClopen` is an order embedding -/

theorem stoneClopen_le_iff (a b : B) :
    stoneClopen a ≤ stoneClopen b ↔ a ≤ b := by
  rw [← inf_eq_left, ← inf_eq_left]
  rw [← stoneClopen_inf, stoneClopen_injective.eq_iff]

/-! ### Main theorem: Stone duality (object level) -/

/-- **Stone duality (object level).**  Every Boolean algebra `B` is order-isomorphic — and
hence Boolean-algebra isomorphic — to the algebra of clopen subsets of its Stone space. -/
def stoneOrderIso : B ≃o Clopens (StoneSpace B) where
  toEquiv := Equiv.ofBijective stoneClopen ⟨stoneClopen_injective, stoneClopen_surjective⟩
  map_rel_iff' := stoneClopen_le_iff _ _

@[simp] theorem stoneOrderIso_apply (b : B) : stoneOrderIso b = stoneClopen b := rfl

end StoneDuality