import Mathlib
import Tropical.Relu.Relu

/-! # Tropical rational representation of feedforward ReLU networks

This file gives a semantic compiler from finite feedforward scalar ReLU circuits to
quotients (differences) of max-plus tropical polynomials.  It builds on the catalog's
`relu` definition.

A `TropicalPolynomial n` is generated by affine forms, tropical addition (`max`),
ordinary addition (tropical multiplication), and multiplication by a nonnegative
scalar.  A tropical rational function is represented in subtractive normal form
`p - q`.  Arbitrary signed neural weights are handled by exchanging numerator and
denominator when a weight is negative.
-/

noncomputable section

open Finset BigOperators

namespace TropicalNeuralDuality

/-- Generalized max-plus tropical polynomials on `ℝⁿ`. -/
inductive TropicalPolynomial (n : ℕ) where
  | affine (weight : Fin n → ℝ) (bias : ℝ)
  | add (left right : TropicalPolynomial n)
  | max (left right : TropicalPolynomial n)
  | scale (coefficient : ℝ) (nonnegative : 0 ≤ coefficient)
      (poly : TropicalPolynomial n)

/-- Evaluation of a generalized tropical polynomial. -/
def TropicalPolynomial.eval {n : ℕ} : TropicalPolynomial n → (Fin n → ℝ) → ℝ
  | .affine weight bias, x => ∑ i, weight i * x i + bias
  | .add p q, x => p.eval x + q.eval x
  | .max p q, x => Max.max (p.eval x) (q.eval x)
  | .scale c _ p, x => c * p.eval x

/-- The zero tropical polynomial. -/
def TropicalPolynomial.zero (n : ℕ) : TropicalPolynomial n :=
  .affine (fun _ => 0) 0

/-- A constant tropical polynomial. -/
def TropicalPolynomial.const (n : ℕ) (c : ℝ) : TropicalPolynomial n :=
  .affine (fun _ => 0) c

@[simp] theorem TropicalPolynomial.eval_zero (n : ℕ) (x : Fin n → ℝ) :
    (TropicalPolynomial.zero n).eval x = 0 := by
  simp [TropicalPolynomial.zero, TropicalPolynomial.eval]

@[simp] theorem TropicalPolynomial.eval_const (n : ℕ) (c : ℝ) (x : Fin n → ℝ) :
    (TropicalPolynomial.const n c).eval x = c := by
  simp [TropicalPolynomial.const, TropicalPolynomial.eval]

/-- A tropical rational expression in subtractive normal form. -/
structure TropicalRational (n : ℕ) where
  numerator : TropicalPolynomial n
  denominator : TropicalPolynomial n

/-- Evaluation of a tropical rational expression. -/
def TropicalRational.eval {n : ℕ} (r : TropicalRational n) (x : Fin n → ℝ) : ℝ :=
  r.numerator.eval x - r.denominator.eval x

/-- Embed a tropical polynomial as a tropical rational expression. -/
def TropicalRational.ofPolynomial {n : ℕ} (p : TropicalPolynomial n) :
    TropicalRational n := ⟨p, .zero n⟩

/-- Addition in subtractive normal form. -/
def TropicalRational.add {n : ℕ} (r s : TropicalRational n) : TropicalRational n :=
  ⟨.add r.numerator s.numerator, .add r.denominator s.denominator⟩

/-- Add a real constant to a tropical rational expression. -/
def TropicalRational.addConst {n : ℕ} (r : TropicalRational n) (b : ℝ) :
    TropicalRational n :=
  TropicalRational.add r (TropicalRational.ofPolynomial (.const n b))

/-- Signed scalar multiplication.  A negative scalar exchanges the two parts. -/
def TropicalRational.smul {n : ℕ} (c : ℝ) (r : TropicalRational n) :
    TropicalRational n :=
  if hc : 0 ≤ c then
    ⟨.scale c hc r.numerator, .scale c hc r.denominator⟩
  else
    ⟨.scale (-c) (neg_nonneg.mpr (le_of_not_ge hc)) r.denominator,
      .scale (-c) (neg_nonneg.mpr (le_of_not_ge hc)) r.numerator⟩

/-- ReLU closure: `max (p - q) 0 = max p q - q`. -/
def TropicalRational.relu {n : ℕ} (r : TropicalRational n) : TropicalRational n :=
  ⟨.max r.numerator r.denominator, r.denominator⟩

@[simp] theorem TropicalRational.eval_ofPolynomial {n : ℕ}
    (p : TropicalPolynomial n) (x : Fin n → ℝ) :
    (TropicalRational.ofPolynomial p).eval x = p.eval x := by
  simp [TropicalRational.eval, TropicalRational.ofPolynomial]

@[simp] theorem TropicalRational.eval_add {n : ℕ} (r s : TropicalRational n)
    (x : Fin n → ℝ) :
    (TropicalRational.add r s).eval x = r.eval x + s.eval x := by
  simp [TropicalRational.eval, TropicalRational.add, TropicalPolynomial.eval]
  ring

@[simp] theorem TropicalRational.eval_addConst {n : ℕ} (r : TropicalRational n)
    (b : ℝ) (x : Fin n → ℝ) :
    (TropicalRational.addConst r b).eval x = r.eval x + b := by
  simp [TropicalRational.addConst]

@[simp] theorem TropicalRational.eval_smul {n : ℕ} (c : ℝ) (r : TropicalRational n)
    (x : Fin n → ℝ) :
    (TropicalRational.smul c r).eval x = c * r.eval x := by
  by_cases hc : 0 ≤ c
  · simp [TropicalRational.smul, hc, TropicalRational.eval,
      TropicalPolynomial.eval]
    ring
  · simp [TropicalRational.smul, hc, TropicalRational.eval,
      TropicalPolynomial.eval]
    ring

@[simp] theorem TropicalRational.eval_relu {n : ℕ} (r : TropicalRational n)
    (x : Fin n → ℝ) :
    (TropicalRational.relu r).eval x = _root_.relu (r.eval x) := by
  simp only [TropicalRational.relu, TropicalRational.eval,
    TropicalPolynomial.eval, relu]
  unfold _root_.relu
  by_cases h : r.numerator.eval x ≤ r.denominator.eval x
  · rw [max_eq_right h, sub_self, max_eq_right (sub_nonpos.mpr h)]
  · have h' : r.denominator.eval x ≤ r.numerator.eval x := le_of_not_ge h
    rw [max_eq_left h', max_eq_left (sub_nonneg.mpr h')]

/-- A finite feedforward scalar ReLU circuit.  `linearCombination` permits an
arbitrary finite fan-in of previously constructed subnetworks, and `reluNode`
adds a ReLU gate.  Thus the syntax directly models finite feedforward DAGs after
unfolding shared nodes to a tree. -/
inductive ReLUNetwork (n : ℕ) where
  | affine (weight : Fin n → ℝ) (bias : ℝ)
  | linearCombination {m : ℕ} (weight : Fin m → ℝ)
      (nodes : Fin m → ReLUNetwork n) (bias : ℝ)
  | reluNode (input : ReLUNetwork n)

/-- Functional semantics of a feedforward ReLU circuit. -/
def ReLUNetwork.eval {n : ℕ} : ReLUNetwork n → (Fin n → ℝ) → ℝ
  | .affine weight bias, x => ∑ i, weight i * x i + bias
  | .linearCombination weight nodes bias, x =>
      ∑ i, weight i * (nodes i).eval x + bias
  | .reluNode input, x => relu (input.eval x)

/-- Sum a list of tropical rational expressions. -/
def TropicalRational.sum {n : ℕ} : List (TropicalRational n) → TropicalRational n
  | [] => .ofPolynomial (.zero n)
  | r :: rs => .add r (TropicalRational.sum rs)

@[simp] theorem TropicalRational.eval_sum {n : ℕ} (rs : List (TropicalRational n))
    (x : Fin n → ℝ) :
    (TropicalRational.sum rs).eval x = (rs.map fun r => r.eval x).sum := by
  induction rs with
  | nil => simp [TropicalRational.sum]
  | cons r rs ih => simp [TropicalRational.sum, ih]

/-- Exact compiler from feedforward ReLU circuits to tropical rational expressions. -/
def compile {n : ℕ} : ReLUNetwork n → TropicalRational n
  | .affine weight bias => .ofPolynomial (.affine weight bias)
  | .linearCombination weight nodes bias =>
      .addConst (.sum (List.ofFn fun i => .smul (weight i) (compile (nodes i)))) bias
  | .reluNode input => .relu (compile input)

/-- **Tropical–neural duality.** Every finite feedforward ReLU circuit computes
exactly the difference of two generalized max-plus tropical polynomials. -/
theorem compile_correct {n : ℕ} (network : ReLUNetwork n) (x : Fin n → ℝ) :
    (compile network).eval x = network.eval x := by
  induction network with
  | affine weight bias =>
      simp [compile, ReLUNetwork.eval, TropicalPolynomial.eval]
  | @linearCombination m weight nodes bias ih =>
      simp only [compile, TropicalRational.eval_addConst,
        TropicalRational.eval_sum, List.map_ofFn, List.sum_ofFn,
        ReLUNetwork.eval]
      congr 1
      apply Finset.sum_congr rfl
      intro i hi
      change (TropicalRational.smul (weight i) (compile (nodes i))).eval x = _
      rw [TropicalRational.eval_smul, ih i]
  | reluNode input ih =>
      simp [compile, ReLUNetwork.eval, ih]

/-- Extensional form of the representation theorem. -/
theorem every_relu_network_is_tropical_rational {n : ℕ} (network : ReLUNetwork n) :
    ∃ p q : TropicalPolynomial n,
      ∀ x : Fin n → ℝ, network.eval x = p.eval x - q.eval x := by
  refine ⟨(compile network).numerator, (compile network).denominator, ?_⟩
  intro x
  exact (compile_correct network x).symm

/-- ReLU does not increase the denominator in the constructive representation:
the denominator of the compiled ReLU node is definitionally the previous one. -/
theorem compile_relu_denominator {n : ℕ} (network : ReLUNetwork n) :
    (compile (.reluNode network)).denominator = (compile network).denominator := by
  simp [compile, TropicalRational.relu]

end TropicalNeuralDuality