from fractions import Fraction
from typing import List, Set, Tuple

Monomial = Tuple[Fraction, Set[int]]
Polynomial = List[Monomial]

def in_variable_ideal(poly: Polynomial, s: Set[int]) -> bool:
    """True iff poly lies in the ideal generated by { x_i : i in s }.

    Applies phi_s (x_i = 0 for i in s) and tests whether the residue vanishes.
    """
    residue: Polynomial = [(c, sup) for (c, sup) in poly if not (sup & s)]
    return all(c == 0 for c, _ in residue)
