import Mathlib

/-!
# The finite-ultrafilter core of Arrow's theorem

This file isolates the combinatorial obstruction behind Arrow's theorem.  For a fixed
ordered pair of alternatives, a coalition is called decisive when its unanimous ranking
forces the social ranking.  The standard Arrow argument shows that the decisive
coalitions form an ultrafilter.  The results below formalize the remaining, purely
structural step: every ultrafilter on a finite electorate is generated by one voter, and
full voter-anonymity is therefore impossible as soon as two distinct voters exist.

No differential-geometric assumptions are used.  Thus any proposed curvature account
of Arrow's theorem must first derive this ultrafilter structure from its geometric
hypotheses; curvature alone cannot replace the decisive-coalition argument.
-/

open Set Filter

namespace ConsensusCurvature

variable {V : Type*}

/-- A coalition is decisive when it belongs to the given ultrafilter of decisive
coalitions. -/
def Decisive (U : Ultrafilter V) (S : Set V) : Prop := S ∈ U

/-- On a finite electorate, the decisive coalitions are exactly those containing one
fixed voter.  This voter is the dictator supplied by the finite-ultrafilter argument. -/
theorem finite_decisive_coalitions_are_dictatorial [Finite V] (U : Ultrafilter V) :
    ∃ d : V, ∀ S : Set V, Decisive U S ↔ d ∈ S := by
  obtain ⟨d, hd⟩ := Ultrafilter.eq_pure_of_finite U
  exact ⟨d, fun S => by rw [hd, Decisive, Ultrafilter.mem_pure]⟩

/-- The voter generating a principal decisive-coalition ultrafilter is unique. -/
theorem decisive_dictator_unique (U : Ultrafilter V) {d e : V}
    (hd : ∀ S : Set V, Decisive U S ↔ d ∈ S)
    (he : ∀ S : Set V, Decisive U S ↔ e ∈ S) : d = e := by
  have hdec : Decisive U ({d} : Set V) := (hd {d}).2 (by simp)
  have he_mem : e ∈ ({d} : Set V) := (he {d}).1 hdec
  exact (Set.mem_singleton_iff.mp he_mem).symm

/-- Renaming voters transports a coalition by direct image.  An anonymous decisive
coalition system is invariant under every such renaming. -/
def Anonymous (U : Ultrafilter V) : Prop :=
  ∀ σ : Equiv.Perm V, ∀ S : Set V, Decisive U (σ '' S) ↔ Decisive U S

/-- A principal decisive-coalition system cannot be anonymous if there is another voter:
the permutation swapping the dictator with that voter changes decisiveness of the
singleton coalition. -/
theorem principal_not_anonymous (U : Ultrafilter V) {d e : V} (hne : e ≠ d)
    (hd : ∀ S : Set V, Decisive U S ↔ d ∈ S) : ¬ Anonymous U := by
  intro hAnon
  letI := Classical.decEq V
  have hswap := hAnon (Equiv.swap d e) ({d} : Set V)
  simp [hd, hne.symm] at hswap

/-- **Finite anonymity impossibility.**  A finite electorate with at least two distinct
voters admits no anonymous ultrafilter of decisive coalitions.  Combined with the
standard Arrow reduction from Pareto and IIA to a decisive-coalition ultrafilter, this is
the final step forcing dictatorship and excluding anonymity. -/
theorem no_anonymous_decisive_ultrafilter [Finite V] (v w : V) (hvw : v ≠ w) :
    ¬ ∃ U : Ultrafilter V, Anonymous U := by
  rintro ⟨U, hAnon⟩
  obtain ⟨d, hd⟩ := finite_decisive_coalitions_are_dictatorial U
  by_cases hvd : v = d
  · have hwd : w ≠ d := by
      intro h
      exact hvw (hvd.trans h.symm)
    exact principal_not_anonymous U hwd hd hAnon
  · exact principal_not_anonymous U hvd hd hAnon

/-- A finite decisive-coalition ultrafilter has exactly one decisive singleton.  This
sharpens existence of a dictator into a canonical characterization. -/
theorem exists_unique_decisive_singleton [Finite V] (U : Ultrafilter V) :
    ∃! d : V, Decisive U ({d} : Set V) := by
  obtain ⟨d, hd⟩ := finite_decisive_coalitions_are_dictatorial U
  refine ⟨d, (hd {d}).2 (by simp), ?_⟩
  intro e he
  have hmem : d ∈ ({e} : Set V) := (hd {e}).1 he
  exact (Set.mem_singleton_iff.mp hmem).symm

/-- Every electorate indexed by `Fin n` with at least two voters satisfies the anonymity
impossibility. -/
theorem no_anonymous_decisive_ultrafilter_fin (n : ℕ) (hn : 2 ≤ n) :
    ¬ ∃ U : Ultrafilter (Fin n), Anonymous U := by
  let v : Fin n := ⟨0, by omega⟩
  let w : Fin n := ⟨1, by omega⟩
  apply no_anonymous_decisive_ultrafilter v w
  simp [v, w]

end ConsensusCurvature