import Mathlib
import Cryptography.BiOrderSeparation

/-!
# Coherent Composition Loops and Cryptographic Hybrids

Ordinary categories require composition to be associative as an equality.  This
module studies a controlled weakening in which parallel composites are related
by a proposition-valued 2-cell.  Such structures are precisely the locally thin,
one-object fragment of bicategory theory: associators and unitors are present,
while every coherence diagram commutes because parallel 2-cells are unique.

The distinction between equality and coherent equivalence is witnessed by an
explicit three-arrow composition table.  Its two triple composites differ as
arrows, although an invertible 2-cell relates them.  Passing to equivalence
classes strictifies the composition.  Finally, reassociation chains are linked
to the hybrid method from cryptography: an observer stable under each coherent
rewrite has total distinguishing drift bounded by the sum of local drifts.
-/

open Finset BigOperators

namespace CausalLoops

/-- Composition with proposition-valued invertible 2-cells.  Congruence says
that horizontal composition respects 2-cells; the remaining fields are the
associator and unitors of a locally thin one-object bicategory. -/
structure ControlledComposition (M : Type*) extends Setoid M where
  comp : M → M → M
  unit : M
  comp_respects : ∀ {a a' b b'}, a ≈ a' → b ≈ b' → comp a b ≈ comp a' b'
  associator : ∀ a b c, comp (comp a b) c ≈ comp a (comp b c)
  left_unitor : ∀ a, comp unit a ≈ a
  right_unitor : ∀ a, comp a unit ≈ a

namespace ControlledComposition

variable {M : Type*} (C : ControlledComposition M)

/-- A 2-cell is a proof of the chosen equivalence relation. -/
abbrev Cell (a b : M) : Prop := C.r a b

/-- Vertical composition of 2-cells. -/
def vcomp {a b c : M} (α : C.Cell a b) (β : C.Cell b c) : C.Cell a c :=
  C.iseqv.trans α β

/-- Inversion of a 2-cell. -/
def inv {a b : M} (α : C.Cell a b) : C.Cell b a := C.iseqv.symm α

/-- Horizontal composition of 2-cells. -/
def hcomp {a a' b b' : M} (α : C.Cell a a') (β : C.Cell b b') :
    C.Cell (C.comp a b) (C.comp a' b') := C.comp_respects α β

/-- In the locally thin setting every pair of parallel 2-cells agrees.  Thus
pentagon, triangle, and all higher pasting diagrams commute automatically. -/
theorem parallel_cells_unique {a b : M} (α β : C.Cell a b) : α = β := by
  apply Subsingleton.elim

/-- The two composites around Mac Lane's associator pentagon are equal as
2-cells.  The statement records the exact fivefold source and target. -/
theorem associator_pentagon (a b c d : M)
    (upper lower : C.Cell
      (C.comp (C.comp (C.comp a b) c) d)
      (C.comp a (C.comp b (C.comp c d)))) :
    upper = lower := by
  exact C.parallel_cells_unique upper lower

/-- Formal expressions whose internal nodes represent weak composition. -/
inductive Expr (M : Type*) where
  | atom : M → Expr M
  | node : Expr M → Expr M → Expr M

/-- Evaluation of a parenthesized expression. -/
def Expr.eval : Expr M → M
  | .atom a => a
  | .node x y => C.comp (Expr.eval x) (Expr.eval y)

/-- Reassociation is generated by the associator, its inverse, transitivity,
and congruence inside either argument. -/
inductive Reassoc (M : Type*) : Expr M → Expr M → Prop
  | refl (x) : Reassoc M x x
  | symm {x y} : Reassoc M x y → Reassoc M y x
  | trans {x y z} : Reassoc M x y → Reassoc M y z → Reassoc M x z
  | left {x y} (z) : Reassoc M x y → Reassoc M (.node x z) (.node y z)
  | right (x) {y z} : Reassoc M y z → Reassoc M (.node x y) (.node x z)
  | assoc (x y z) : Reassoc M (.node (.node x y) z) (.node x (.node y z))

/-- Every syntactic reassociation is interpreted by an invertible 2-cell. -/
theorem reassoc_sound {x y : Expr M} (h : Reassoc M x y) :
    C.Cell (Expr.eval C x) (Expr.eval C y) := by
  induction h with
  | refl x => exact C.iseqv.refl _
  | symm h ih => exact C.iseqv.symm ih
  | trans h₁ h₂ ih₁ ih₂ => exact C.iseqv.trans ih₁ ih₂
  | left z h ih => exact C.comp_respects ih (C.iseqv.refl _)
  | right x h ih => exact C.comp_respects (C.iseqv.refl _) ih
  | assoc x y z => exact C.associator _ _ _

/-- The strict quotient of arrows by invertible 2-cells. -/
abbrev StrictQuotient := Quotient C.toSetoid

/-- Composition descends to the strict quotient. -/
def quotientComp : C.StrictQuotient → C.StrictQuotient → C.StrictQuotient :=
  Quotient.map₂ C.comp (by
    intro a a' ha b b' hb
    exact C.comp_respects ha hb)

/-- The descended composition is strictly associative. -/
theorem quotientComp_assoc (x y z : C.StrictQuotient) :
    C.quotientComp (C.quotientComp x y) z =
      C.quotientComp x (C.quotientComp y z) := by
  induction x using Quotient.inductionOn with
  | _ a =>
    induction y using Quotient.inductionOn with
    | _ b =>
      induction z using Quotient.inductionOn with
      | _ c =>
        change Quotient.mk C.toSetoid (C.comp (C.comp a b) c) =
          Quotient.mk C.toSetoid (C.comp a (C.comp b c))
        exact Quotient.sound (C.associator a b c)

/-- The image of the weak unit is a strict left identity. -/
theorem quotientComp_unit_left (x : C.StrictQuotient) :
    C.quotientComp (Quotient.mk _ C.unit) x = x := by
  induction x using Quotient.inductionOn with
  | _ a =>
    change Quotient.mk C.toSetoid (C.comp C.unit a) = Quotient.mk C.toSetoid a
    exact Quotient.sound (C.left_unitor a)

/-- The image of the weak unit is a strict right identity. -/
theorem quotientComp_unit_right (x : C.StrictQuotient) :
    C.quotientComp x (Quotient.mk _ C.unit) = x := by
  induction x using Quotient.inductionOn with
  | _ a =>
    change Quotient.mk C.toSetoid (C.comp a C.unit) = Quotient.mk C.toSetoid a
    exact Quotient.sound (C.right_unitor a)

end ControlledComposition

/-! ## A concrete non-associative composition loop -/

/-- Three arrows suffice to separate strict equality from coherent equivalence. -/
inductive LoopArrow where
  | e | a | b
  deriving DecidableEq, Repr

/-- A unital but non-associative composition table. -/
def loopComp : LoopArrow → LoopArrow → LoopArrow
  | .e, y => y
  | .a, .e => .a
  | .b, .e => .b
  | .a, .a => .b
  | .a, .b => .a
  | .b, .a => .e
  | .b, .b => .b

/-- The indiscrete 2-cell relation makes every pair of arrows coherently
isomorphic; this is the smallest locally thin environment exposing the failure
of equality without obstructing coherence. -/
def loopControlled : ControlledComposition LoopArrow where
  r := fun _ _ => True
  iseqv := by
    constructor
    · intro x; trivial
    · intro x y h; trivial
    · intro x y z hxy hyz; trivial
  comp := loopComp
  unit := .e
  comp_respects := by intros; trivial
  associator := by intros; trivial
  left_unitor := by intros; trivial
  right_unitor := by intros; trivial

/-- Composition genuinely fails associativity at the arrow level. -/
theorem loopComp_not_associative :
    loopComp (loopComp .a .a) .a ≠ loopComp .a (loopComp .a .a) := by
  intro h
  cases h

/-- Nevertheless the unequal triple composites are connected by an invertible
2-cell, so the failure is controlled rather than arbitrary. -/
theorem loopComp_associator_cell :
    loopControlled.Cell (loopComp (loopComp .a .a) .a)
      (loopComp .a (loopComp .a .a)) := by
  exact loopControlled.associator .a .a .a

/-- Strictification identifies the two unequal composites in the quotient. -/
theorem loopComp_strictifies :
    Quotient.mk loopControlled.toSetoid (loopComp (loopComp .a .a) .a) =
      Quotient.mk loopControlled.toSetoid (loopComp .a (loopComp .a .a)) := by
  exact Quotient.sound loopComp_associator_cell

/-! ## Catalog bridge: bounded traces and coherent syntax -/

/-- A bounded right-principal-ideal trace for arbitrary arrow alphabets. -/
def atomicRightTrace {A : Type*} (R : ℕ) (w : List A) : Set (List A) :=
  {z | z.length ≤ R ∧ ∃ t, z = w ++ t}

/-- The bounded right-principal-ideal argument from the catalog remains a
complete fingerprint after arrows are embedded as atomic composition
expressions.  The proof reuses the catalog's generic mutual-prefix rigidity. -/
theorem bounded_trace_separates_atomic_loops {R : ℕ} {w w' : List LoopArrow}
    (hw : w.length ≤ R) (hw' : w'.length ≤ R)
    (htrace : atomicRightTrace R w = atomicRightTrace R w') :
    w.map ControlledComposition.Expr.atom =
      w'.map ControlledComposition.Expr.atom := by
  have hwmem : w ∈ atomicRightTrace R w := ⟨hw, [], by simp⟩
  have hw'mem : w' ∈ atomicRightTrace R w' := ⟨hw', [], by simp⟩
  rw [htrace] at hwmem
  rw [← htrace] at hw'mem
  have hwords : w = w' := mutual_prefix_eq hwmem.2 hw'mem.2
  subst w'
  rfl

/-! ## Cryptographic bridge: coherent rewrites as hybrid games -/

/-- The real-valued hybrid telescope, proved by induction from the triangle
inequality. -/
theorem real_hybrid_telescope
    {k : ℕ} (prob : Fin (k + 2) → ℝ) :
    |prob ⟨0, by omega⟩ - prob ⟨k + 1, by omega⟩| ≤
      ∑ i : Fin (k + 1),
        |prob ⟨i.val, by omega⟩ - prob ⟨i.val + 1, by omega⟩| := by
  induction' k with k ih <;> simp_all +decide [Fin.sum_univ_castSucc]
  specialize ih (fun i => prob i.castSucc)
  simp_all +decide
  exact le_trans (abs_sub_le _ _ _) (by linarith!)

/-- A chain of coherent reassociations behaves like a cryptographic hybrid
sequence.  If a real-valued observer changes by at most `δ` under each adjacent
2-cell, then the endpoint distinguishing gap is at most `(k+1)δ`.

Its telescope is proved above, while the local bounds are supplied by
bicategorical reassociation soundness. -/
theorem reassociation_hybrid_bound {M : Type*} (C : ControlledComposition M)
    (k : ℕ) (E : Fin (k + 2) → ControlledComposition.Expr M)
    (chain : ∀ i : Fin (k + 1), ControlledComposition.Reassoc M (E i.castSucc) (E i.succ))
    (score : M → ℝ) (δ : ℝ)
    (stable : ∀ {x y}, C.Cell x y → |score x - score y| ≤ δ) :
    |score (ControlledComposition.Expr.eval C (E ⟨0, by omega⟩)) -
      score (ControlledComposition.Expr.eval C (E ⟨k + 1, by omega⟩))| ≤
        (k + 1 : ℕ) * δ := by
  let prob : Fin (k + 2) → ℝ :=
    fun i => score (ControlledComposition.Expr.eval C (E i))
  have ht := real_hybrid_telescope prob
  have hs : ∑ i : Fin (k + 1),
      |prob ⟨i.val, by omega⟩ - prob ⟨i.val + 1, by omega⟩| ≤
      ∑ _i : Fin (k + 1), δ := by
    apply Finset.sum_le_sum
    intro i hi
    exact stable (C.reassoc_sound (chain i))
  exact le_trans ht (by simpa [prob] using hs)

-- !-- Lab Notes -- !--
/-
Hypothesis.  Associativity up to invertible, proposition-valued 2-cells should
strictify after quotienting, while still permitting visibly unequal composites
before quotienting.  Coherent rewrite chains should also support hybrid-style
quantitative bounds for observational leakage.

Experiment.  A three-arrow unital table was tested at the triple `(a,a,a)`.
The left composite is `e` and the right composite is `a`.  Equipping the table
with indiscrete 2-cells supplies associators and unitors.  General reassociation
syntax was then interpreted into arbitrary controlled compositions.

Analysis.  The quotient theorem confirms that the obstruction is intensional:
associativity becomes equality after identifying 2-isomorphic arrows.  The
reassociation induction isolates the structural ingredients—associator,
inverse, transitivity, and whiskering.  The hybrid theorem shows that coherence
also controls accumulated observational drift.

Critique.  Associativity merely "up to some isomorphism" is not, by itself, a
bicategory: naturality, unitors, and pentagon/triangle coherence are additional
requirements.  The exact result here is deliberately restricted to locally thin
one-object bicategories, where proof irrelevance forces all parallel coherence
diagrams to commute.  It does not claim that arbitrary weak composition data or
every unspecified loop-tolerant algebra automatically forms a higher category.
The indiscrete example maximizes 2-cell availability, so it witnesses strict
inequality but not a nontrivial 2-cell obstruction.

Synthesis.  Controlled composition, structural reassociation soundness,
proposition-valued coherence, strictification, an explicit non-associative
example, and a cryptographic hybrid bound form one connected hierarchy.  The
next step is to replace local thinness by typed categories of 2-cells and prove
the pentagon without proof irrelevance.
-/
-- !-- End Lab Notes -- !--

#print axioms ControlledComposition.reassoc_sound
#print axioms ControlledComposition.quotientComp_assoc
#print axioms loopComp_not_associative
#print axioms bounded_trace_separates_atomic_loops
#print axioms loopComp_strictifies
#print axioms reassociation_hybrid_bound

end CausalLoops