#!/usr/bin/env python3
"""
algorithms.py — Core algorithms for generation defect LDP computations.

Implements:
  1. Partition function computation for arbitrary finite groups
  2. Asymptotic pressure (cumulant generating function)
  3. Legendre-transform rate function via numerical optimization
  4. Binary KL divergence (exact rate for i.i.d. Bernoulli defect)
  5. Fekete's lemma for subadditive sequences
"""

from math import log, exp, gcd
from typing import List, Tuple, Callable, Optional
import itertools


# ============================================================
# 1. Finite Group Generation Testing
# ============================================================

def closure_size(generators: List[int], group_table: List[List[int]], 
                 group_size: int) -> int:
    """Compute |<generators>| using the Cayley table.
    
    Args:
        generators: list of group element indices
        group_table: n×n multiplication table
        group_size: order of the group
    
    Returns:
        Size of the subgroup generated by the given elements.
    
    Time complexity: O(|G|² · |<generators>|)
    Space complexity: O(|G|)
    """
    if not generators:
        return 1  # trivial subgroup
    
    elements = {0}  # identity (index 0)
    frontier = set(generators)
    
    while frontier - elements:
        elements |= frontier
        new_frontier = set()
        for a in elements:
            for b in elements:
                prod = group_table[a][b]
                if prod not in elements:
                    new_frontier.add(prod)
        frontier = new_frontier
        if not frontier:
            break
    
    return len(elements)


def is_generating_pair_cyclic(g: int, h: int, n: int) -> bool:
    """Check if (g, h) generates Z/nZ.
    
    A pair generates Z/nZ iff gcd(g, h, n) = 1.
    
    Time complexity: O(log n)
    """
    return gcd(g, gcd(h, n)) == 1


def nongeneration_probability_cyclic(n: int) -> float:
    """Compute q = P(random pair doesn't generate Z/nZ).
    
    Uses Euler's totient function relationship:
    P(generates) = 1 - sum_{d|n, d>1} mu(d)/d²
    
    For direct computation, we enumerate all pairs.
    
    Time complexity: O(n²)
    """
    total = n * n
    nongen = sum(1 for g in range(n) for h in range(n) 
                 if not is_generating_pair_cyclic(g, h, n))
    return nongen / total


# ============================================================
# 2. Partition Function
# ============================================================

def one_step_partition_from_q(q: float, t: float) -> float:
    """Compute Z_1(t) for a group with nongeneration probability q.
    
    Z_1(t) = |G|² · [(1-q) · exp(0) + q · exp(t)]
           = |G|² · [(1-q) + q·exp(t)]
    
    For the normalized (probability) version:
    E[exp(t·δ)] = (1-q) + q·exp(t)
    
    Args:
        q: nongeneration probability
        t: inverse temperature parameter
    
    Returns:
        Normalized MGF value (without |G|² factor)
    
    Time complexity: O(1)
    """
    return (1 - q) + q * exp(t)


def direct_power_partition(q: float, n: int, t: float, 
                           card_sq: Optional[int] = None) -> float:
    """Compute Z_n(t) = Z_1(t)^n for the direct power G^n.
    
    Uses the exact product factorization theorem.
    
    Args:
        q: nongeneration probability for a single pair
        n: power (number of coordinates)
        t: inverse temperature
        card_sq: |G|² if unnormalized partition is desired
    
    Returns:
        Z_n(t) value
    
    Time complexity: O(log n) via fast exponentiation
    """
    z1 = one_step_partition_from_q(q, t)
    if card_sq is not None:
        z1 *= card_sq
    return z1 ** n


# ============================================================
# 3. Asymptotic Pressure (Cumulant Generating Function)
# ============================================================

def asymptotic_pressure(q: float, t: float) -> float:
    """Compute Λ(t) = log E[exp(t·δ)] = log[(1-q) + q·exp(t)].
    
    This is the cumulant generating function (CGF) of the
    single-step Bernoulli(q) defect variable.
    
    Properties (proved in Lean 4):
    - Λ(0) = 0
    - Λ is convex on all of ℝ
    - Λ is nondecreasing on [0,∞) when q > 0
    - Λ'(0) = q (the mean defect)
    
    Time complexity: O(1)
    """
    return log((1 - q) + q * exp(t))


def asymptotic_pressure_derivative(q: float, t: float) -> float:
    """Compute Λ'(t) = q·exp(t) / [(1-q) + q·exp(t)].
    
    This is the "tilted mean" — the expected defect under the
    exponentially tilted measure.
    """
    mgf = (1 - q) + q * exp(t)
    return q * exp(t) / mgf


def asymptotic_pressure_second_derivative(q: float, t: float) -> float:
    """Compute Λ''(t) = variance of defect under tilted measure.
    
    Λ''(t) = q(1-q)·exp(t) / [(1-q) + q·exp(t)]²
    
    This is always > 0 when 0 < q < 1, confirming strict convexity.
    """
    mgf = (1 - q) + q * exp(t)
    return q * (1 - q) * exp(t) / (mgf ** 2)


# ============================================================
# 4. Rate Function (Legendre Transform)
# ============================================================

def rate_function_exact(q: float, alpha: float) -> float:
    """Compute I(α) = α·log(α/q) + (1-α)·log((1-α)/(1-q)).
    
    This is the binary Kullback-Leibler divergence D(Ber(α) ‖ Ber(q)),
    which is the exact rate function for i.i.d. Bernoulli(q) variables
    by Cramér's theorem.
    
    Properties:
    - I(α) ≥ 0 for all α ∈ [0,1]
    - I(q) = 0 (minimum at the mean)
    - I is strictly convex on (0,1)
    - I(0) = -log(1-q), I(1) = -log(q)
    
    Args:
        q: nongeneration probability (0 < q < 1)
        alpha: deviation level (0 ≤ α ≤ 1)
    
    Returns:
        Rate function value I(α)
    
    Time complexity: O(1)
    """
    if alpha <= 0:
        return -log(1 - q) if q < 1 else float('inf')
    if alpha >= 1:
        return -log(q) if q > 0 else float('inf')
    
    result = 0.0
    if alpha > 0:
        result += alpha * log(alpha / q)
    if alpha < 1:
        result += (1 - alpha) * log((1 - alpha) / (1 - q))
    return result


def rate_function_numerical(q: float, alpha: float, 
                            num_points: int = 2000) -> float:
    """Compute I(α) = sup_t {t·α - Λ(t)} numerically.
    
    Uses a grid search over t values. For verification purposes:
    should match rate_function_exact to high precision.
    
    Time complexity: O(num_points)
    """
    best = float('-inf')
    for i in range(num_points):
        t = -20 + 80 * i / (num_points - 1)
        val = t * alpha - asymptotic_pressure(q, t)
        best = max(best, val)
    return best


def rate_function_optimal_t(q: float, alpha: float) -> float:
    """Find the optimal tilting parameter t* such that Λ'(t*) = α.
    
    Solving: q·exp(t) / [(1-q) + q·exp(t)] = α
    gives: exp(t*) = α(1-q) / (q(1-α))
    hence: t* = log(α(1-q) / (q(1-α)))
    
    This is the optimal Chernoff parameter.
    """
    if alpha <= 0 or alpha >= 1:
        return float('inf') if alpha >= 1 else float('-inf')
    return log(alpha * (1 - q) / (q * (1 - alpha)))


# ============================================================
# 5. Fekete's Lemma
# ============================================================

def fekete_limit(a: Callable[[int], float], N: int = 1000) -> float:
    """Estimate the limit of a(n)/n for a subadditive sequence.
    
    By Fekete's lemma, if a(m+n) ≤ a(m) + a(n), then
    lim_{n→∞} a(n)/n = inf_{n≥1} a(n)/n.
    
    We approximate by computing inf over n = 1, ..., N.
    
    Args:
        a: subadditive sequence function
        N: number of terms to check
    
    Returns:
        Estimated limit
    
    Time complexity: O(N · T(a)) where T(a) is cost of evaluating a
    """
    return min(a(n) / n for n in range(1, N + 1))


def verify_subadditivity(a: Callable[[int], float], N: int = 50) -> bool:
    """Check subadditivity a(m+n) ≤ a(m) + a(n) for m,n ≤ N.
    
    Time complexity: O(N²)
    """
    for m in range(1, N + 1):
        for n in range(1, N + 1):
            if a(m + n) > a(m) + a(n) + 1e-10:
                return False
    return True


# ============================================================
# Example Usage
# ============================================================

if __name__ == "__main__":
    print("Generation Defect LDP — Algorithm Demonstrations")
    print("=" * 60)
    
    # Z/6Z
    q = nongeneration_probability_cyclic(6)
    print(f"\nZ/6Z: q = {q:.6f}")
    
    # Pressure curve
    print("\nPressure Λ(t):")
    for t in [0, 1, 2, 5]:
        print(f"  t={t}: Λ(t) = {asymptotic_pressure(q, t):.6f}, "
              f"Λ'(t) = {asymptotic_pressure_derivative(q, t):.6f}, "
              f"Λ''(t) = {asymptotic_pressure_second_derivative(q, t):.6f}")
    
    # Rate function comparison
    print("\nRate function comparison (exact vs numerical):")
    for alpha in [0.1, 0.2, q, 0.5, 0.8]:
        I_exact = rate_function_exact(q, alpha)
        I_num = rate_function_numerical(q, alpha)
        t_opt = rate_function_optimal_t(q, alpha)
        print(f"  α={alpha:.4f}: I_exact={I_exact:.6f}, "
              f"I_numerical={I_num:.6f}, t*={t_opt:.4f}")
    
    # Subadditivity verification
    print("\nSubadditivity of log Z_n for Z/6Z:")
    a = lambda n: n * asymptotic_pressure(q, 1.0)  # additive, hence subadditive
    print(f"  Subadditive: {verify_subadditivity(a, 20)}")
    print(f"  Fekete limit: {fekete_limit(a, 100):.6f}")
    print(f"  Exact limit:  {asymptotic_pressure(q, 1.0):.6f}")
