"""
Algorithms for k-Tuple Möbius Inversion on Finite Group Lattices

Implements:
1. Subgroup lattice construction for S_n
2. Möbius function computation via top-down recursion
3. Hall k-Eulerian function φ_k(G) via Möbius inversion
4. Generating probability P_{n,k} computation

Time complexity:
  - Subgroup enumeration: O(n!^2) for S_n (pairwise closure)
  - Möbius function: O(s^2) where s = number of subgroups
  - φ_k via Möbius: O(s) once Möbius values are known
  - Brute force φ_k: O(n!^k · n · n!) (exponential in k)
"""

from itertools import permutations, product
from typing import Dict, FrozenSet, List, Set, Tuple
from collections import defaultdict


def compose(p: Tuple[int, ...], q: Tuple[int, ...]) -> Tuple[int, ...]:
    """Compose permutations: (p ∘ q)(i) = p(q(i)).

    Time: O(n)

    >>> compose((1, 0), (1, 0))
    (0, 1)
    """
    return tuple(p[q[i]] for i in range(len(p)))


def inverse(p: Tuple[int, ...]) -> Tuple[int, ...]:
    """Compute inverse permutation.

    Time: O(n)

    >>> inverse((1, 2, 0))
    (2, 0, 1)
    """
    inv = [0] * len(p)
    for i, v in enumerate(p):
        inv[v] = i
    return tuple(inv)


def closure(generators: List[Tuple[int, ...]], n: int) -> FrozenSet[Tuple[int, ...]]:
    """Compute the subgroup generated by a set of permutations.

    Algorithm: BFS-style saturation. Repeatedly multiply known elements
    by generators and their inverses until no new elements are found.

    Time: O(|⟨generators⟩| · |generators| · n) per iteration,
          O(|⟨generators⟩|^2 · |generators| · n) total.

    >>> sorted(closure([(1, 0, 2)], 3))
    [(0, 1, 2), (1, 0, 2)]
    """
    e = tuple(range(n))
    group: Set[Tuple[int, ...]] = {e}
    for g in generators:
        group.add(g)

    changed = True
    while changed:
        changed = False
        new = set()
        for g in list(group):
            for h in generators:
                for elem in [compose(g, h), compose(h, g),
                             compose(g, inverse(h)), compose(inverse(h), g)]:
                    if elem not in group and elem not in new:
                        new.add(elem)
                        changed = True
        group.update(new)
    return frozenset(group)


def enumerate_subgroups(n: int) -> List[FrozenSet[Tuple[int, ...]]]:
    """Enumerate all subgroups of S_n by computing closures of pairs.

    Algorithm: For each pair (σ, τ) ∈ S_n × S_n, compute ⟨σ, τ⟩.
    Collect all distinct subgroups.

    Time: O(n!^2 · n! · n) = O(n!^3 · n)
    Space: O(s · n!) where s = number of subgroups

    >>> len(enumerate_subgroups(3))
    6
    """
    perms = list(permutations(range(n)))
    subgroups: Set[FrozenSet[Tuple[int, ...]]] = set()

    # Trivial subgroup
    subgroups.add(frozenset([tuple(range(n))]))

    # Cyclic subgroups
    for p in perms:
        subgroups.add(closure([p], n))

    # Two-generated subgroups
    for i, p in enumerate(perms):
        for q in perms[i:]:
            subgroups.add(closure([p, q], n))

    return list(subgroups)


def compute_moebius_function(
    subgroups: List[FrozenSet],
    top: FrozenSet
) -> Dict[FrozenSet, int]:
    """Compute the Möbius function μ(H, G) for all subgroups H ≤ G.

    Algorithm (top-down recursion):
      μ(G, G) = 1
      μ(H, G) = -Σ_{K: H ⊂ K ≤ G} μ(K, G)

    Time: O(s^2) where s = number of subgroups
    Space: O(s)

    Pseudocode:
      MOEBIUS(subgroups, G):
        Sort subgroups by |H| descending
        μ[G] ← 1
        For H in sorted order (H ≠ G):
          μ[H] ← -Σ_{K > H, K ∈ subgroups} μ[K]
        Return μ
    """
    sorted_subs = sorted(subgroups, key=lambda s: len(s), reverse=True)
    mu: Dict[FrozenSet, int] = {}

    for H in sorted_subs:
        if H == top:
            mu[H] = 1
        else:
            mu[H] = -sum(
                mu[K] for K in sorted_subs
                if K != H and H.issubset(K) and K in mu
            )
    return mu


def hall_k_eulerian(
    n: int,
    k: int,
    subgroups: List[FrozenSet] = None,
    mu: Dict[FrozenSet, int] = None
) -> int:
    """Compute the Hall k-Eulerian function φ_k(S_n) via Möbius inversion.

    Formula: φ_k(G) = Σ_{H ≤ G} μ(H, G) · |H|^k

    Time: O(s) given precomputed Möbius values
    Space: O(1) additional

    Args:
        n: Degree of symmetric group
        k: Tuple length
        subgroups: Precomputed subgroup list (optional)
        mu: Precomputed Möbius values (optional)

    Returns:
        Number of ordered k-tuples generating S_n

    >>> hall_k_eulerian(2, 2)
    3
    >>> hall_k_eulerian(3, 2)
    18
    """
    if subgroups is None:
        subgroups = enumerate_subgroups(n)
    perms = list(permutations(range(n)))
    top = frozenset(perms)
    if mu is None:
        mu = compute_moebius_function(subgroups, top)

    return sum(mu[H] * len(H) ** k for H in subgroups)


def generating_probability(n: int, k: int) -> float:
    """Compute P_{n,k} = φ_k(S_n) / n!^k.

    Time: O(s) given precomputed values

    >>> generating_probability(2, 2)
    0.75
    """
    from math import factorial
    phi = hall_k_eulerian(n, k)
    return phi / factorial(n) ** k


def verify_partition_identity(n: int, k: int) -> bool:
    """Verify the partition identity |H|^k = Σ_{K≤H} φ_k(K) for all H ≤ S_n.

    Time: O(s^2 · n!^k)

    >>> verify_partition_identity(2, 2)
    True
    >>> verify_partition_identity(3, 2)
    True
    """
    perms = list(permutations(range(n)))
    subgroups = enumerate_subgroups(n)

    # Compute φ_k for each subgroup by brute force
    phi_k: Dict[FrozenSet, int] = {}
    for H in subgroups:
        h_list = list(H)
        count = 0
        for combo in product(h_list, repeat=k):
            if closure(list(combo), len(perms[0])) == H:
                count += 1
        phi_k[H] = count

    # Verify partition identity for each subgroup
    for H in subgroups:
        lhs = len(H) ** k
        rhs = sum(phi_k[K] for K in subgroups if K.issubset(H))
        if lhs != rhs:
            return False
    return True


if __name__ == "__main__":
    import doctest
    doctest.testmod()

    print("Hall k-Eulerian function values:")
    for n in [2, 3]:
        subgroups = enumerate_subgroups(n)
        perms = list(permutations(range(n)))
        top = frozenset(perms)
        mu = compute_moebius_function(subgroups, top)

        print(f"\n  S_{n} ({len(perms)} elements, {len(subgroups)} subgroups):")
        for k in range(1, 5):
            phi = hall_k_eulerian(n, k, subgroups, mu)
            prob = phi / len(perms) ** k
            print(f"    φ_{k}(S_{n}) = {phi:6d}  "
                  f"P_{{{n},{k}}} = {prob:.6f}")
