#!/usr/bin/env python3
"""
algorithms.py — Algorithms for the Mathematical Uncanny Valley

Type-hinted implementations of the core algorithms:
1. Valley detection in trust functions
2. Suspicion sensitivity estimation from data
3. Epistemic barrier computation
4. Valley depth and minimum location
"""

from typing import Callable, Optional
import math


def suspicion_fn(r: float) -> float:
    """The suspicion function S(r) = r²(1-r).

    Models the level of suspicion generated by a proof at rigor level r.
    Maximum at r = 2/3 with value 4/27.

    Args:
        r: Rigor level in [0, 1]

    Returns:
        Suspicion level in [0, 4/27]
    """
    return r ** 2 * (1.0 - r)


def valley_model(alpha: float, r: float) -> float:
    """The uncanny valley trust model U(r) = r - α·S(r).

    Args:
        alpha: Suspicion sensitivity (α ≥ 0)
        r: Rigor level in [0, 1]

    Returns:
        Trust level
    """
    return r - alpha * suspicion_fn(r)


def valley_detect(
    f: Callable[[float], float],
    n: int = 1000,
    a: float = 0.0,
    b: float = 1.0
) -> Optional[tuple[float, float]]:
    """Detect whether a function exhibits the valley property on [a, b].

    Samples f at n+1 equally spaced points and checks if any interior
    sample falls below both endpoint values.

    Args:
        f: The function to test
        n: Number of intervals (n+1 sample points)
        a: Left endpoint
        b: Right endpoint

    Returns:
        (r_valley, f(r_valley)) if valley found, None otherwise
    """
    f_a = f(a)
    f_b = f(b)
    threshold = min(f_a, f_b)

    best_r: Optional[float] = None
    best_val: float = threshold

    for i in range(1, n):
        r = a + (b - a) * i / n
        val = f(r)
        if val < threshold and val < best_val:
            best_r = r
            best_val = val

    if best_r is not None:
        return (best_r, best_val)
    return None


def estimate_alpha(
    data: list[tuple[float, float]],
) -> float:
    """Estimate suspicion sensitivity α from empirical (rigor, trust) data.

    Uses least-squares: minimize Σᵢ (tᵢ - U_α(rᵢ))² over α ≥ 0.

    Closed-form solution:
        α̂ = Σᵢ (rᵢ - tᵢ)·S(rᵢ) / Σᵢ S(rᵢ)²

    Args:
        data: List of (rigor_level, trust_level) pairs

    Returns:
        Estimated α (clamped to be ≥ 0)
    """
    numerator = 0.0
    denominator = 0.0

    for r, t in data:
        s = suspicion_fn(r)
        numerator += (r - t) * s
        denominator += s * s

    if denominator < 1e-15:
        return 0.0

    alpha = numerator / denominator
    return max(0.0, alpha)


def compute_valley_depth(alpha: float, n: int = 100000) -> float:
    """Compute the valley depth for the valley model U_α.

    Valley depth = min(U(0), U(1)) - min{U(r) : r ∈ [0,1]}.

    Args:
        alpha: Suspicion sensitivity
        n: Number of sample points

    Returns:
        Valley depth (positive means valley exists)
    """
    endpoint_min = min(valley_model(alpha, 0.0), valley_model(alpha, 1.0))

    min_val = endpoint_min
    for i in range(n + 1):
        r = i / n
        val = valley_model(alpha, r)
        min_val = min(min_val, val)

    return endpoint_min - min_val


def find_valley_minimum_analytic(alpha: float) -> Optional[tuple[float, float]]:
    """Find the valley minimum analytically for U_α(r) = r - αr²(1-r).

    The critical points satisfy U'(r) = 1 - α(2r - 3r²) = 0,
    i.e., 3αr² - 2αr + 1 = 0.

    The valley minimum (smaller root) is:
        r_min = (1 - √(1 - 3/α)) / 3    (requires α > 3)

    The valley exists only for α > 4.

    Args:
        alpha: Suspicion sensitivity

    Returns:
        (r_min, U(r_min)) if valley exists (α > 4), None otherwise
    """
    if alpha <= 4.0:
        return None

    discriminant = 1.0 - 3.0 / alpha
    if discriminant < 0:
        return None

    r_min = (1.0 + math.sqrt(discriminant)) / 3.0
    u_min = valley_model(alpha, r_min)
    return (r_min, u_min)


def epistemic_barrier_threshold(
    S: Callable[[float], float],
    n: int = 100000
) -> float:
    """Compute the critical α threshold for a general suspicion function.

    The threshold is α* = 1/M where M = max{S(r) : r ∈ [0,1]}.

    Args:
        S: Suspicion function with S(0) = S(1) = 0
        n: Number of sample points

    Returns:
        Critical threshold α*
    """
    max_s = 0.0
    for i in range(n + 1):
        r = i / n
        s = S(r)
        max_s = max(max_s, s)

    if max_s < 1e-15:
        return float('inf')

    return 1.0 / max_s


def compute_epistemic_barrier(alpha: float) -> dict[str, float]:
    """Compute epistemic barrier properties for the valley model.

    Args:
        alpha: Suspicion sensitivity (must be > 4 for barrier to exist)

    Returns:
        Dictionary with peak_rigor, height, width, valley_min_rigor, valley_min_trust
    """
    result: dict[str, float] = {
        'alpha': alpha,
        'peak_rigor': 2.0 / 3.0,
        'peak_suspicion': 4.0 / 27.0,
    }

    if alpha > 4:
        vm = find_valley_minimum_analytic(alpha)
        if vm is not None:
            r_min, u_min = vm
            result['valley_min_rigor'] = r_min
            result['valley_min_trust'] = u_min
            result['valley_depth'] = -u_min  # depth below 0 = U(0)
            result['barrier_height'] = alpha / 8 - 0.5  # U(0) - U(1/2) = -(1/2 - α/8)
        result['has_valley'] = True
    else:
        result['has_valley'] = False

    return result


if __name__ == "__main__":
    # Quick demonstrations
    print("Valley Detection:")
    for alpha in [3.0, 4.0, 5.0, 8.0]:
        result = valley_detect(lambda r, a=alpha: valley_model(a, r))
        print(f"  α={alpha}: {'Valley at r={:.4f}'.format(result[0]) if result else 'No valley'}")

    print("\nAlpha Estimation from synthetic data:")
    import random
    random.seed(42)
    true_alpha = 6.0
    synthetic_data = [
        (r / 10, valley_model(true_alpha, r / 10) + random.gauss(0, 0.05))
        for r in range(11)
    ]
    est_alpha = estimate_alpha(synthetic_data)
    print(f"  True α = {true_alpha}, Estimated α = {est_alpha:.4f}")

    print("\nAnalytic Valley Minima:")
    for alpha in [5.0, 8.0, 12.0, 20.0]:
        vm = find_valley_minimum_analytic(alpha)
        if vm:
            print(f"  α={alpha:5.1f}: r_min={vm[0]:.6f}, U(r_min)={vm[1]:+.6f}")
