#!/usr/bin/env python3
"""Numerical demonstrations for ideal arithmetic in the semiring of naturals."""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd
from typing import Iterable, Sequence


@dataclass(frozen=True)
class MembershipCertificate:
    """A nonnegative coefficient vector representing a target."""

    target: int
    generators: tuple[int, ...]
    coefficients: tuple[int, ...]

    @property
    def value(self) -> int:
        return sum(c * g for c, g in zip(self.coefficients, self.generators))


def normalize_generators(generators: Iterable[int]) -> tuple[int, ...]:
    """Return sorted, distinct, nonnegative generators."""
    values = tuple(sorted(set(generators)))
    if any(g < 0 for g in values):
        raise ValueError("Ideal generators must be nonnegative")
    return values


def ideal_membership_certificate(
    generators: Sequence[int], target: int
) -> MembershipCertificate | None:
    """Find a nonnegative additive representation of target, if one exists.

    Dynamic programming takes O(len(generators) * target) time and O(target)
    memory.  The predecessor array reconstructs a checkable certificate.
    """
    gens = normalize_generators(g for g in generators if g > 0)
    if target < 0:
        return None
    if target == 0:
        return MembershipCertificate(0, gens, (0,) * len(gens))
    predecessor: list[tuple[int, int] | None] = [None] * (target + 1)
    reachable = [False] * (target + 1)
    reachable[0] = True
    for value in range(target + 1):
        if not reachable[value]:
            continue
        for index, generator in enumerate(gens):
            nxt = value + generator
            if nxt <= target and not reachable[nxt]:
                reachable[nxt] = True
                predecessor[nxt] = (value, index)
    if not reachable[target]:
        return None
    coefficients = [0] * len(gens)
    cursor = target
    while cursor > 0:
        step = predecessor[cursor]
        if step is None:
            raise RuntimeError("Broken predecessor chain")
        cursor, index = step
        coefficients[index] += 1
    return MembershipCertificate(target, gens, tuple(coefficients))


def ideal_elements_up_to(generators: Sequence[int], bound: int) -> set[int]:
    """Compute all members of a finitely generated ideal up to bound."""
    if bound < 0:
        return set()
    gens = normalize_generators(g for g in generators if g > 0)
    reachable = {0}
    for value in range(bound + 1):
        if value in reachable:
            reachable.update(value + g for g in gens if value + g <= bound)
    return reachable


def product_generators(left: Sequence[int], right: Sequence[int]) -> tuple[int, ...]:
    """Generate the product ideal from all pairwise products."""
    return normalize_generators(a * b for a in left for b in right)


def reduce_generators(generators: Sequence[int]) -> tuple[int, ...]:
    """Remove generators already generated by the remaining smaller values."""
    result: list[int] = []
    for candidate in normalize_generators(generators):
        if candidate == 0:
            continue
        if ideal_membership_certificate(result, candidate) is None:
            result.append(candidate)
    return tuple(result)


def ideals_equal_through_bound(
    left_generators: Sequence[int], right_generators: Sequence[int], bound: int
) -> bool:
    """Compare two generated ideals on the finite interval [0, bound]."""
    return ideal_elements_up_to(left_generators, bound) == ideal_elements_up_to(
        right_generators, bound
    )


def verify_integrality_witness(
    ideal_generators: Sequence[int], element: int, witness_generators: Sequence[int]
) -> dict[int, MembershipCertificate]:
    """Verify <element>*D is contained in A*D on finite generators.

    Returns one additive certificate for each generator element*d of <element>*D.
    Raises ValueError if any required membership fails.
    """
    ad_generators = product_generators(ideal_generators, witness_generators)
    certificates: dict[int, MembershipCertificate] = {}
    for d in normalize_generators(witness_generators):
        target = element * d
        certificate = ideal_membership_certificate(ad_generators, target)
        if certificate is None:
            raise ValueError(f"No certificate found for {target} in A*D")
        certificates[target] = certificate
    return certificates


def format_certificate(certificate: MembershipCertificate) -> str:
    """Render a membership certificate as an additive identity."""
    terms = [
        f"{coefficient}*{generator}"
        for coefficient, generator in zip(
            certificate.coefficients, certificate.generators
        )
        if coefficient
    ]
    return f"{certificate.target} = " + (" + ".join(terms) if terms else "0")


def conductor_from_scan(generators: Sequence[int], search_limit: int = 5000) -> int | None:
    """Find the conductor when gcd is one, using a finite consecutive-run test."""
    gens = normalize_generators(g for g in generators if g > 0)
    if not gens:
        return None
    common_gcd = 0
    for generator in gens:
        common_gcd = gcd(common_gcd, generator)
    if common_gcd != 1:
        return None
    reachable = ideal_elements_up_to(gens, search_limit)
    run = min(gens)
    for start in range(search_limit - run + 1):
        if all(value in reachable for value in range(start, start + run)):
            return start
    return None


def main() -> None:
    """Run the noncancellation, integrality, and bounded-membership demos."""
    a = (5, 17)
    b = (5, 17, 43)
    c = (5, 11, 19, 23)

    print("IDEAL ARITHMETIC IN THE NATURAL NUMBERS")
    print("=" * 48)
    cert_43 = ideal_membership_certificate(a, 43)
    print(f"43 belongs to <5,17>: {cert_43 is not None}")
    print("43 belongs to <5,17,43>: True")

    ac = product_generators(a, c)
    bc = product_generators(b, c)
    print(f"\nRaw generators of A*C: {ac}")
    print(f"Raw generators of B*C: {bc}")

    certificates = verify_integrality_witness(a, 43, c)
    print("\nCertificates absorbing every extra 43*C generator into A*C:")
    for target in sorted(certificates):
        certificate = certificates[target]
        assert certificate.value == target
        print("  " + format_certificate(certificate))

    reduced_ac = reduce_generators(ac)
    reduced_bc = reduce_generators(bc)
    print(f"\nReduced generators of A*C: {reduced_ac}")
    print(f"Reduced generators of B*C: {reduced_bc}")
    print(f"The reduced product presentations agree: {reduced_ac == reduced_bc}")

    bound = 1200
    finite_equality = ideals_equal_through_bound(ac, bc, bound)
    print(f"Products agree on [0,{bound}]: {finite_equality}")
    assert finite_equality

    conductor_a = conductor_from_scan(a)
    conductor_c = conductor_from_scan(c)
    print(f"\nConductor detected for <5,17>: {conductor_a}")
    print(f"Conductor detected for <5,11,19,23>: {conductor_c}")
    print("\nConclusion: A != B, while the finite certificates prove A*C = B*C.")
    print("They also certify that 43 is integral over A with witness C.")


if __name__ == "__main__":
    main()
