"""
Fork-Pinning: numerical demonstrations
======================================

Self-contained numerical companion to "Fork-Pinning: An Information-Theoretic
Criterion for Congruence Determination of Prime Splitting".

Everything here is elementary and dependency-free (standard library only).

What is demonstrated
--------------------
1.  The Chebotarev model: exact fork information for the Galois groups
    C3, S3, S4 and A5, compared with the closed forms
        cyclic cubic   I = H = log 3 - (2/3) log 2        = 0.9183 bits
        S3 cubic       I = (4/3)log2 + (1/2)log3 - (5/6)log5 = 0.1909 bits
        S4 quartic     I = (3/2)log2 - (5/8)log5          = 0.0488 bits
        A5             I = 0 for every fork
2.  The fork-pinning criterion: pinned  <=>  invariant under commutators
    <=>  factors through the abelianization.  Decided by direct enumeration.
3.  Empirical verification on real primes:
        x^3 + x^2 - 2x - 1 splits completely  <=>  p = +-1 mod 7   (exact)
        x^3 + x + 1        has no congruence rule; only the sign is visible
        x^4 - x - 1        root counts 4:2:1:0 in ratio 1:6:8:9 out of 24
4.  Capacity: I <= log 2 for any binary fork, attained exactly at balanced
    pinned forks; in S_n only by the sign and its negation.
5.  The coset profile  Phi(d) = h(d) - h(2d)/2: sharp bound for an
    index-two conductor, strictly increasing, Phi(d)/d -> log 2,
    Phi(d)/h(d) -> 0.
6.  The semiprime barrier: universal dial D(n), the quadratic collapse
    n^2 D(n) -> 1 - log 2 = 0.30685, and the exactly-zero which-factor wall.

Run:  python3 demo.py
"""

from __future__ import annotations

import itertools
import math
from typing import Callable, Dict, Iterable, List, Sequence, Tuple

Perm = Tuple[int, ...]

LOG2 = math.log(2.0)


# ---------------------------------------------------------------------------
# Information theory on a finite uniform space
# ---------------------------------------------------------------------------

def eta(t: float) -> float:
    """-t log t, with eta(0) = 0."""
    return 0.0 if t <= 0.0 else -t * math.log(t)


def entropy(values: Sequence[object]) -> float:
    """Entropy (nats) of the empirical law of a list of outcomes."""
    n = len(values)
    counts: Dict[object, int] = {}
    for v in values:
        counts[v] = counts.get(v, 0) + 1
    return sum(eta(c / n) for c in counts.values())


def mutual_information(xs: Sequence[object], ys: Sequence[object]) -> float:
    """I(X;Y) = H(X) + H(Y) - H(X,Y) in nats, for paired samples."""
    return entropy(xs) + entropy(ys) - entropy(list(zip(xs, ys)))


def bits(nats: float) -> float:
    return nats / LOG2


def binary_entropy(d: float) -> float:
    return eta(d) + eta(1.0 - d)


# ---------------------------------------------------------------------------
# Permutation groups as explicit lists of tuples
# ---------------------------------------------------------------------------

def symmetric_group(n: int) -> List[Perm]:
    return [tuple(p) for p in itertools.permutations(range(n))]


def compose(a: Perm, b: Perm) -> Perm:
    """(a*b)(i) = a(b(i))."""
    return tuple(a[b[i]] for i in range(len(a)))


def inverse(a: Perm) -> Perm:
    out = [0] * len(a)
    for i, ai in enumerate(a):
        out[ai] = i
    return tuple(out)


def sign(a: Perm) -> int:
    """+1 or -1, computed from the parity of the number of transpositions."""
    seen = [False] * len(a)
    parity = 0
    for i in range(len(a)):
        if not seen[i]:
            j, length = i, 0
            while not seen[j]:
                seen[j] = True
                j = a[j]
                length += 1
            parity += length - 1
    return 1 if parity % 2 == 0 else -1


def alternating_group(n: int) -> List[Perm]:
    return [p for p in symmetric_group(n) if sign(p) == 1]


def cycle_type(a: Perm) -> Tuple[int, ...]:
    seen = [False] * len(a)
    parts: List[int] = []
    for i in range(len(a)):
        if not seen[i]:
            j, length = i, 0
            while not seen[j]:
                seen[j] = True
                j = a[j]
                length += 1
            parts.append(length)
    return tuple(sorted(parts))


def commutator_subgroup(group: Sequence[Perm]) -> List[Perm]:
    """Subgroup generated by all commutators [g,h] = g h g^-1 h^-1."""
    gens = {compose(compose(g, h), compose(inverse(g), inverse(h)))
            for g in group for h in group}
    identity = tuple(range(len(group[0])))
    closure = {identity}
    frontier = [identity]
    while frontier:
        x = frontier.pop()
        for s in gens:
            y = compose(x, s)
            if y not in closure:
                closure.add(y)
                frontier.append(y)
    return sorted(closure)


# ---------------------------------------------------------------------------
# The fork-pinning criterion, decided by enumeration
# ---------------------------------------------------------------------------

def is_commutator_invariant(group: Sequence[Perm],
                            fork: Callable[[Perm], bool]
                            ) -> Tuple[bool, Tuple[Perm, Perm] | None]:
    """Test Y(g c) = Y(g) for all g in G, c in [G,G]; return a witness if not."""
    comm = commutator_subgroup(group)
    for g in group:
        for c in comm:
            if fork(compose(g, c)) != fork(g):
                return False, (g, c)
    return True, None


def fork_report(name: str,
                group: Sequence[Perm],
                observable: Callable[[Perm], object],
                fork: Callable[[Perm], bool],
                closed_form: float | None = None) -> None:
    xs = [observable(g) for g in group]
    ys = [fork(g) for g in group]
    h_y = entropy(ys)
    info = mutual_information(xs, ys)
    pinned_fraction = info / h_y if h_y > 0 else float("nan")
    invariant, witness = is_commutator_invariant(group, fork)
    print(f"  {name}")
    print(f"     P[fork] = {sum(ys)}/{len(ys)} = {sum(ys)/len(ys):.6f}")
    print(f"     H(fork) = {bits(h_y):.6f} bits")
    print(f"     I(obs;fork) = {bits(info):.6f} bits", end="")
    if closed_form is not None:
        print(f"   (closed form {bits(closed_form):.6f} bits,"
              f" |diff| = {abs(bits(info) - bits(closed_form)):.2e})")
    else:
        print()
    print(f"     pinned fraction I/H = {pinned_fraction:.6f}")
    print(f"     commutator-invariant (=> pinnable): {invariant}"
          + ("" if invariant else f"   witness g,c with Y(gc) != Y(g): {witness}"))


# ---------------------------------------------------------------------------
# 1-2.  Exact values for C3, S3, S4, A5
# ---------------------------------------------------------------------------

def demo_galois_groups() -> None:
    print("=" * 78)
    print("1-2.  EXACT FORK INFORMATION IN THE CHEBOTAREV MODEL")
    print("=" * 78)

    # (a) cyclic cubic: G = C3, realised as the 3-cycles acting on 3 points.
    c3: List[Perm] = [(0, 1, 2), (1, 2, 0), (2, 0, 1)]
    closed_c3 = math.log(3) - (2 / 3) * LOG2
    print("\n (a) Cyclic cubic field, G = C3  (e.g. x^3 + x^2 - 2x - 1, conductor 7)")
    fork_report("fork [1,1,1] (Frobenius trivial), observable = full residue class",
                c3, lambda g: g, lambda g: g == (0, 1, 2), closed_c3)

    # (b) S3 cubic: only the sign is visible.
    s3 = symmetric_group(3)
    closed_s3 = (4 / 3) * LOG2 + 0.5 * math.log(3) - (5 / 6) * math.log(5)
    print("\n (b) S3 cubic  (e.g. x^3 + x + 1, discriminant -31), G^ab = C2")
    fork_report("fork [1,1,1], observable = sign",
                s3, sign, lambda g: g == (0, 1, 2), closed_s3)
    identity_deficit = entropy([g == (0, 1, 2) for g in s3]) - 0.5 * closed_c3
    print(f"     structural identity  I = H(fork) - H(1/3)/2 :"
          f" {bits(identity_deficit):.6f} bits  vs  {bits(closed_s3):.6f} bits")

    # the A3 face is exactly flat
    a3 = alternating_group(3)
    flat = mutual_information([sign(g) for g in a3], [g == (0, 1, 2) for g in a3])
    print(f"     A3-face fork (restrict to even permutations): I = {bits(flat):.6f} bits")

    # (c) S4 quartic
    s4 = symmetric_group(4)
    closed_s4 = 1.5 * LOG2 - (5 / 8) * math.log(5)
    print("\n (c) S4 quartic  (e.g. x^4 - x - 1, discriminant -283)")
    counts = {k: 0 for k in range(5)}
    for g in s4:
        counts[sum(1 for i in range(4) if g[i] == i)] += 1
    print(f"     fixed-point counts 4:2:1:0 = {counts[4]}:{counts[2]}:{counts[1]}:{counts[0]}"
          f" out of 24   (predicted 1:6:8:9)")
    fork_report("fork 'has a root', observable = sign",
                s4, sign, lambda g: any(g[i] == i for i in range(4)), closed_s4)
    a4 = alternating_group(4)
    for label, f in [("[1,1,1,1] vs rest (even face)", lambda g: g == (0, 1, 2, 3)),
                     ("[2,2] vs rest (even face)", lambda g: cycle_type(g) == (2, 2)),
                     ("[1,3] vs rest (even face)", lambda g: cycle_type(g) == (1, 3))]:
        val = mutual_information([sign(g) for g in a4], [f(g) for g in a4])
        print(f"     within-face fork {label:32s} I = {bits(val):.6f} bits")

    # (d) A5 is congruence-blind
    a5 = alternating_group(5)
    comm5 = commutator_subgroup(a5)
    print("\n (d) A5 closure: perfect group")
    print(f"     |[A5,A5]| = {len(comm5)} = |A5| = {len(a5)}  => abelianization trivial")
    for label, f in [("has a fixed point", lambda g: any(g[i] == i for i in range(5))),
                     ("is a 5-cycle", lambda g: cycle_type(g) == (5,)),
                     ("is the identity", lambda g: g == (0, 1, 2, 3, 4))]:
        val = mutual_information([sign(g) for g in a5], [f(g) for g in a5])
        print(f"     fork '{label:20s}'  I(any abelian character) = {bits(val):.6f} bits")


# ---------------------------------------------------------------------------
# 3.  Empirical verification on real primes
# ---------------------------------------------------------------------------

def primes_up_to(limit: int) -> List[int]:
    sieve = bytearray([1]) * (limit + 1)
    sieve[0:2] = b"\x00\x00"
    for i in range(2, int(limit ** 0.5) + 1):
        if sieve[i]:
            sieve[i * i::i] = bytearray(len(sieve[i * i::i]))
    return [i for i in range(limit + 1) if sieve[i]]


def count_roots_mod_p(coeffs: Sequence[int], p: int) -> int:
    """Number of x in F_p with sum coeffs[i] x^i = 0 (coeffs in ascending degree)."""
    total = 0
    for x in range(p):
        acc = 0
        xp = 1
        for c in coeffs:
            acc = (acc + c * xp) % p
            xp = (xp * x) % p
        if acc == 0:
            total += 1
    return total


def demo_primes(limit: int = 60000) -> None:
    print()
    print("=" * 78)
    print(f"3.  EMPIRICAL VERIFICATION ON PRIMES UP TO {limit}")
    print("=" * 78)
    ps = [p for p in primes_up_to(limit) if p > 5]

    # (a) cyclic cubic of conductor 7 : x^3 + x^2 - 2x - 1
    f1 = (-1, -2, 1, 1)
    good = [p for p in ps if p % 7 != 0]
    split = [count_roots_mod_p(f1, p) == 3 for p in good]
    residue = [p % 7 for p in good]
    rule = [r in (1, 6) for r in residue]
    exceptions = sum(1 for a, b in zip(split, rule) if a != b)
    print("\n (a) x^3 + x^2 - 2x - 1  (cyclic cubic, conductor 7)")
    print(f"     primes tested: {len(good)}")
    print(f"     'splits completely  <=>  p = +-1 mod 7' exceptions: {exceptions}")
    print(f"     density of totally split: {sum(split)/len(split):.6f}  (predicted 1/3)")
    print(f"     I(p mod 7 ; fork)  = {bits(mutual_information(residue, split)):.6f} bits"
          f"   (theory {bits(math.log(3) - (2/3)*LOG2):.6f})")
    control = [p % 5 for p in good]
    print(f"     I(p mod 5 ; fork)  = {bits(mutual_information(control, split)):.6f} bits"
          f"   (coprime control: predicted 0, small positive = finite-sample bias)")
    types = {}
    for p in good:
        r = count_roots_mod_p(f1, p)
        types[r] = types.get(r, 0) + 1
    print(f"     root-count histogram: {dict(sorted(types.items()))}"
          f"   (Galois cubic: only 0 or 3 roots, never exactly 1)")

    # (b) S3 cubic : x^3 + x + 1, discriminant -31
    f2 = (1, 1, 0, 1)
    good2 = [p for p in ps if p % 31 != 0]
    split2 = [count_roots_mod_p(f2, p) == 3 for p in good2]
    res31 = [p % 31 for p in good2]
    # the sign of the Frobenius = Legendre symbol of the discriminant -31
    legendre = [pow((-31) % p, (p - 1) // 2, p) == 1 for p in good2]
    print("\n (b) x^3 + x + 1  (S3 closure, discriminant -31), G^ab = C2")
    print(f"     density of totally split: {sum(split2)/len(split2):.6f}  (predicted 1/6)")
    i_sign = mutual_information(legendre, split2)
    i_mod = mutual_information(res31, split2)
    theory_s3 = (4 / 3) * LOG2 + 0.5 * math.log(3) - (5 / 6) * math.log(5)
    print(f"     I(sign ; fork)     = {bits(i_sign):.6f} bits   (theory {bits(theory_s3):.6f})")
    print(f"     I(p mod 31 ; fork) = {bits(i_mod):.6f} bits   (excess over the sign is"
          f" finite-sample bias: {bits(i_mod - i_sign):+.6f})")
    qr = [i for i, s in enumerate(legendre) if s]
    face = [split2[i] for i in qr]
    print(f"     on the quadratic-residue face, density of [1,1,1] ="
          f" {sum(face)/len(face):.6f}  (predicted 1/3, and the face fork is flat)")

    # (c) S4 quartic : x^4 - x - 1, discriminant -283
    f3 = (-1, -1, 0, 0, 1)
    good3 = [p for p in ps if p % 283 != 0]
    nroots = [count_roots_mod_p(f3, p) for p in good3]
    hist = {k: nroots.count(k) for k in (0, 1, 2, 4)}
    m = len(good3)
    print("\n (c) x^4 - x - 1  (S4 closure, discriminant -283)")
    print("     root-count densities  (predicted 4:2:1:0 = 1/24 : 6/24 : 8/24 : 9/24)")
    for k, pred in [(4, 1 / 24), (2, 6 / 24), (1, 8 / 24), (0, 9 / 24)]:
        print(f"       {k} roots: measured {hist[k]/m:.5f}   predicted {pred:.5f}")
    hasroot = [r > 0 for r in nroots]
    legendre3 = [pow((-283) % p, (p - 1) // 2, p) == 1 for p in good3]
    theory_s4 = 1.5 * LOG2 - (5 / 8) * math.log(5)
    print(f"     I(sign ; has root) = {bits(mutual_information(legendre3, hasroot)):.6f} bits"
          f"   (theory {bits(theory_s4):.6f})")
    even = [i for i, s in enumerate(legendre3) if s]
    face4 = [nroots[i] for i in even]
    d1 = sum(1 for r in face4 if r == 4) / len(face4)
    d2 = sum(1 for r in face4 if r == 0) / len(face4)
    d3 = sum(1 for r in face4 if r == 1) / len(face4)
    print(f"     even-face densities [1,1,1,1] / [2,2] / [1,3] ="
          f" {d1:.4f} / {d2:.4f} / {d3:.4f}   (predicted 1/12, 3/12, 8/12)")


# ---------------------------------------------------------------------------
# 4.  Capacity of a binary fork
# ---------------------------------------------------------------------------

def demo_capacity() -> None:
    print()
    print("=" * 78)
    print("4.  CAPACITY OF A BINARY FORK:  I <= log 2, attained iff determined + balanced")
    print("=" * 78)
    for n in (2, 3, 4):
        group = symmetric_group(n)
        attaining: List[str] = []
        # enumerate all forks of S_n that are measurable w.r.t. the sign
        for label, fork in [("sign", lambda g: sign(g) == 1),
                            ("not sign", lambda g: sign(g) == -1),
                            ("constant true", lambda g: True),
                            ("constant false", lambda g: False),
                            ("is identity", lambda g: g == tuple(range(len(g)))),
                            ("has a fixed point",
                             lambda g: any(g[i] == i for i in range(len(g))))]:
            xs = [sign(g) for g in group]
            ys = [fork(g) for g in group]
            info = mutual_information(xs, ys)
            tag = "  <-- attains capacity" if abs(info - LOG2) < 1e-12 else ""
            if tag:
                attaining.append(label)
            print(f"   S{n}: fork {label:20s} I(sign;fork) = {bits(info):.6f} bits{tag}")
        print(f"   S{n}: forks attaining log 2 among those tested: {attaining}")
        print(f"       P[sign = +1] = {sum(1 for g in group if sign(g) == 1)/len(group):.4f}"
              f"  (balanced, as required)\n")


# ---------------------------------------------------------------------------
# 5.  The coset profile of an index-two conductor
# ---------------------------------------------------------------------------

def coset_profile(d: float) -> float:
    """Phi(d) = h(d) - h(2d)/2, the sharp bound for a balanced observable."""
    return binary_entropy(d) - binary_entropy(2 * d) / 2


def demo_profile() -> None:
    print("=" * 78)
    print("5.  THE EXTREMAL COSET PROFILE  Phi(d) = h(d) - h(2d)/2")
    print("=" * 78)
    print("     d        Phi(d) [bits]   Phi(d)/d      Phi(d)/h(d)   |Phi - d log2| <= 4d^2")
    for d in (0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.49, 0.5):
        phi = coset_profile(d)
        frac = phi / binary_entropy(d) if d > 0 else 0.0
        err = abs(phi - d * LOG2)
        ok = "ok" if d > 0.25 or err <= 4 * d * d + 1e-15 else "FAIL"
        print(f"   {d:6.3f}   {bits(phi):12.6f}   {phi/d:10.6f}   {frac:11.6f}   {ok}")
    print(f"     Phi(1/2) = {bits(coset_profile(0.5)):.6f} bits = log 2 : capacity reached")
    print("     strictly increasing on [0, 1/2]: "
          f"{all(coset_profile(d) < coset_profile(d + 0.001) for d in [i/1000 for i in range(0, 499)])}")

    # Sharpness: a single-coset fork attains the profile exactly.
    s4 = symmetric_group(4)
    xs = [sign(g) for g in s4]
    for label, fork in [("identity only (single coset, d = 1/24)",
                         lambda g: g == (0, 1, 2, 3)),
                        ("double transpositions (single coset, d = 3/24)",
                         lambda g: cycle_type(g) == (2, 2)),
                        ("transpositions (single coset, d = 6/24)",
                         lambda g: cycle_type(g) == (1, 1, 2))]:
        ys = [fork(g) for g in s4]
        d = sum(ys) / len(ys)
        print(f"   {label:48s} I = {bits(mutual_information(xs, ys)):.6f}"
              f"  Phi(d) = {bits(coset_profile(d)):.6f}")


# ---------------------------------------------------------------------------
# 6.  The semiprime barrier
# ---------------------------------------------------------------------------

def semiprime_dial(n: float) -> float:
    """Closed form D(n) of the semiprime-level mutual information (nats)."""
    return math.log(n) + (
        -(2 * n - 1) * math.log(2 * n - 1)
        + (n - 1) * (3 - 2 * n) * math.log(n - 1)
        + 2 * (n - 1) * LOG2
        + ((n - 1) * (n - 2) * math.log(n - 2) if n > 2 else 0.0)
    ) / (n * n)


def demo_semiprime() -> None:
    print()
    print("=" * 78)
    print("6.  THE SEMIPRIME BARRIER")
    print("=" * 78)

    # Brute-force check of the closed form on C3 x C3 and on S3 x S3.
    for name, group, mul, ident in [
        ("C3", [0, 1, 2], lambda a, b: (a + b) % 3, 0),
        ("S3", symmetric_group(3), compose, (0, 1, 2)),
        ("C4", [0, 1, 2, 3], lambda a, b: (a + b) % 4, 0),
        ("S4", symmetric_group(4), compose, (0, 1, 2, 3)),
    ]:
        pairs = [(a, b) for a in group for b in group]
        classes = [mul(a, b) for a, b in pairs]
        or_fork = [a == ident or b == ident for a, b in pairs]
        first = [a for a, _ in pairs]
        n = len(group)
        i_or = mutual_information(classes, or_fork)
        i_which = mutual_information(classes, first)
        print(f"\n   G = {name}, n = {n}")
        print(f"     I(class of N ; [p splits OR q splits]) = {bits(i_or):.6f} bits"
              f"   closed form {bits(semiprime_dial(n)):.6f}")
        print(f"     P[OR] = {sum(or_fork)}/{n*n} = {(2*n-1)}/{n*n}")
        print(f"     collapse bound 1/((2n-1)(n-1)) = "
              f"{bits(1/((2*n-1)*(n-1))):.6f} bits   (satisfied: {i_or <= 1/((2*n-1)*(n-1))})")
        print(f"     WHICH-FACTOR WALL  I(class of N ; first factor) = {bits(i_which):.3e} bits"
              f"   (exactly 0)")

    print("\n   Universal dial and the sharp constant  n^2 D(n) -> 1 - log 2 = "
          f"{1 - LOG2:.6f}")
    print("     n        D(n) [bits]      n^2 D(n) [nats]   |n^2 D - (1-log2)|")
    for n in (2, 3, 4, 5, 10, 24, 60, 120, 1000, 10 ** 5):
        d = semiprime_dial(float(n))
        print(f"   {n:7d}   {bits(d):13.8f}   {n*n*d:15.8f}   {abs(n*n*d - (1-LOG2)):.6f}")
    print(f"     exact value at n = 2 : 4 D(2) = 3 log(4/3) = {3*math.log(4/3):.6f}"
          f"  (computed {4*semiprime_dial(2.0):.6f})")
    print("     budget n^2 D(n) < 1 for all n: "
          f"{all(n*n*semiprime_dial(float(n)) < 1 for n in range(2, 500))}")

    # The k-factor wall.
    print("\n   k-factor wall (products of k+1 uniform elements of C3):")
    g = [0, 1, 2]
    for k in (1, 2, 3):
        tuples = list(itertools.product(g, repeat=k + 1))
        prod = [sum(t) % 3 for t in tuples]
        stat = [any(x == 0 for x in t[:k]) for t in tuples]
        print(f"     k = {k}:  I(class of the product ; 'some of the first {k} splits')"
              f" = {bits(mutual_information(prod, stat)):.3e} bits")


def main() -> None:
    demo_galois_groups()
    demo_primes()
    demo_capacity()
    demo_profile()
    demo_semiprime()
    print()
    print("=" * 78)
    print("All demonstrations complete.")
    print("=" * 78)


if __name__ == "__main__":
    main()
