#!/usr/bin/env python3
"""Numerical demonstrations of relative entropy dimension.

The script uses only Python's standard library. It computes path counts and
logarithmic volumes, checks the entropy power law, verifies entropy-weighted
composition, illustrates repetition invariance, and contrasts weighted with
naive depth-based averaging.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import exp, fsum, isclose, log, prod
from typing import Iterable, Sequence

Profile = Sequence[int]


def validate_profile(profile: Profile, name: str = "profile") -> None:
    """Require a finite profile of positive integer branching numbers."""
    if any(not isinstance(x, int) or isinstance(x, bool) or x < 1 for x in profile):
        raise ValueError(f"{name} must contain only positive integers")


def path_count(profile: Profile) -> int:
    """Return the exact number of paths generated by a branching profile."""
    validate_profile(profile)
    return prod(profile)


def log_volume(profile: Profile) -> float:
    """Return the additive logarithmic path volume of a profile."""
    validate_profile(profile)
    return fsum(log(x) for x in profile)


def profile_dimension(ambient: Profile, successful: Profile) -> float:
    """Compute successful logarithmic volume divided by ambient volume."""
    validate_profile(ambient, "ambient")
    validate_profile(successful, "successful")
    denominator = log_volume(ambient)
    if denominator == 0.0:
        raise ValueError("ambient logarithmic volume must be nonzero")
    return log_volume(successful) / denominator


def validate_pruning(ambient: Profile, successful: Profile) -> None:
    """Check equal length and coordinatewise inequalities 1 <= s_i <= b_i."""
    validate_profile(ambient, "ambient")
    validate_profile(successful, "successful")
    if len(ambient) != len(successful):
        raise ValueError("ambient and successful profiles must have equal length")
    if any(s > b for b, s in zip(ambient, successful)):
        raise ValueError("successful branching cannot exceed ambient branching")


def repeat_profile(profile: Profile, repetitions: int) -> list[int]:
    """Concatenate a profile with itself a specified number of times."""
    validate_profile(profile)
    if repetitions < 0:
        raise ValueError("repetitions must be nonnegative")
    return list(profile) * repetitions


def weighted_phase_dimension(phases: Iterable[tuple[Profile, Profile]]) -> float:
    """Compose phases using ambient logarithmic volumes as weights."""
    numerator = 0.0
    denominator = 0.0
    seen = False
    for ambient, successful in phases:
        validate_pruning(ambient, successful)
        volume = log_volume(ambient)
        if volume == 0.0:
            raise ValueError("each phase must have positive ambient volume")
        numerator += log_volume(successful)
        denominator += volume
        seen = True
    if not seen:
        raise ValueError("at least one phase is required")
    return numerator / denominator


@dataclass(frozen=True)
class ProfileReport:
    """Computed invariants for one pruned ambient/successful profile pair."""

    ambient_count: int
    successful_count: int
    ambient_volume: float
    successful_volume: float
    dimension: float
    entropy_deficit: float


def analyze_profile(ambient: Profile, successful: Profile) -> ProfileReport:
    """Validate and summarize a coordinatewise-pruned profile pair."""
    validate_pruning(ambient, successful)
    a_volume = log_volume(ambient)
    if a_volume == 0.0:
        raise ValueError("ambient logarithmic volume must be positive")
    s_volume = log_volume(successful)
    return ProfileReport(
        ambient_count=path_count(ambient),
        successful_count=path_count(successful),
        ambient_volume=a_volume,
        successful_volume=s_volume,
        dimension=s_volume / a_volume,
        entropy_deficit=a_volume - s_volume,
    )


def print_report(title: str, ambient: Profile, successful: Profile) -> None:
    """Print a readable profile report and numerical power-law residual."""
    report = analyze_profile(ambient, successful)
    reconstructed = exp(report.dimension * log(report.ambient_count))
    print(f"\n{title}")
    print(f"  ambient profile:       {list(ambient)}")
    print(f"  successful profile:    {list(successful)}")
    print(f"  path counts:           {report.ambient_count} ambient, "
          f"{report.successful_count} successful")
    print(f"  logarithmic volumes:   {report.ambient_volume:.9f} ambient, "
          f"{report.successful_volume:.9f} successful")
    print(f"  relative dimension:    {report.dimension:.9f}")
    print(f"  entropy deficit:       {report.entropy_deficit:.9f}")
    print(f"  power-law check:       ambient^D = {reconstructed:.9f}")
    assert isclose(reconstructed, report.successful_count, rel_tol=1e-12)
    assert 0.0 <= report.dimension <= 1.0


def main() -> None:
    """Run four demonstrations of the principal identities."""
    print("RELATIVE ENTROPY DIMENSION: NUMERICAL DEMONSTRATIONS")

    ambient = [2, 3, 5, 2]
    successful = [1, 2, 2, 2]
    print_report("1. Nonstationary entropy power law", ambient, successful)

    phase_1 = ([2], [2])
    phase_2 = ([16], [2])
    weighted = weighted_phase_dimension([phase_1, phase_2])
    concatenated = profile_dimension(phase_1[0] + phase_2[0],
                                     phase_1[1] + phase_2[1])
    naive = (profile_dimension(*phase_1) + profile_dimension(*phase_2)) / 2
    print("\n2. Information weighting versus depth weighting")
    print(f"  phase dimensions:      1 and 1/4")
    print(f"  naive equal average:   {naive:.9f}")
    print(f"  entropy-weighted mean: {weighted:.9f}")
    print(f"  direct concatenation:  {concatenated:.9f}")
    assert isclose(weighted, 2 / 5, rel_tol=1e-12)
    assert isclose(weighted, concatenated, rel_tol=1e-12)
    assert not isclose(naive, concatenated, rel_tol=1e-12)

    base_ambient = [2, 5, 3]
    base_successful = [1, 2, 3]
    base_dimension = profile_dimension(base_ambient, base_successful)
    repeated_dimension = profile_dimension(
        repeat_profile(base_ambient, 7), repeat_profile(base_successful, 7)
    )
    print("\n3. Repetition invariance")
    print(f"  one-block dimension:   {base_dimension:.9f}")
    print(f"  seven-block dimension: {repeated_dimension:.9f}")
    assert isclose(base_dimension, repeated_dimension, rel_tol=1e-12)

    period = 8
    double_branch_levels = {0, 2, 5}
    binary_ambient = [2] * period
    binary_successful = [2 if i in double_branch_levels else 1 for i in range(period)]
    periodic_dimension = profile_dimension(binary_ambient, binary_successful)
    print("\n4. Periodic binary specialization")
    print(f"  levels retaining two branches: {len(double_branch_levels)} of {period}")
    print(f"  computed dimension:            {periodic_dimension:.9f}")
    print(f"  predicted fraction:            {len(double_branch_levels) / period:.9f}")
    assert isclose(periodic_dimension, len(double_branch_levels) / period,
                   rel_tol=1e-12)

    print("\nAll numerical checks passed.")


if __name__ == "__main__":
    main()
