"""
Numerical demonstrations for pairing-based signatures.

This module builds an explicit, finite, *bilinear pairing* and uses it to exhibit,
on concrete numbers, every result of the accompanying paper:

    1. Bilinearity and the scalar-transport laws.
    2. BLS signature completeness and verification.
    3. Short aggregate signatures and batch verification.
    4. The rogue-key forgery on naive same-message aggregation, and the
       distinct-message defense that blocks it.
    5. The MOV transport of the source-group discrete log into the target group.
    6. An alternating pairing and its antisymmetry.

The "source group" G is the additive cyclic group Z_n (scalar multiplication is
multiplication mod n).  The "target group" T is the order-n multiplicative
subgroup of (Z_p)^* generated by a fixed element gt, where n divides p - 1.
The pairing is e(a, b) = gt^(a*b mod n), which is biadditive and nondegenerate.

Everything is self-contained: standard library only, full type hints.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


# --------------------------------------------------------------------------- #
# Number-theoretic helpers
# --------------------------------------------------------------------------- #
def is_prime(m: int) -> bool:
    """Deterministic trial-division primality test (sufficient for small m)."""
    if m < 2:
        return False
    if m % 2 == 0:
        return m == 2
    d = 3
    while d * d <= m:
        if m % d == 0:
            return False
        d += 2
    return True


def find_prime_with_subgroup(n: int) -> int:
    """Return the smallest prime p > n with n | (p - 1) (so (Z_p)^* has order n)."""
    k = 1
    while True:
        p = k * n + 1
        if p > n and is_prime(p):
            return p
        k += 1


def element_of_order(n: int, p: int) -> int:
    """Return an element of exact order n in the multiplicative group (Z_p)^*."""
    exponent = (p - 1) // n
    for base in range(2, p):
        candidate = pow(base, exponent, p)
        if candidate != 1 and pow(candidate, n, p) == 1:
            # Confirm exact order n by checking no proper divisor kills it.
            if all(pow(candidate, n // q, p) != 1 for q in prime_factors(n)):
                return candidate
    raise RuntimeError("no element of the requested order found")


def prime_factors(m: int) -> set[int]:
    """Return the set of distinct prime factors of m."""
    factors: set[int] = set()
    d = 2
    while d * d <= m:
        while m % d == 0:
            factors.add(d)
            m //= d
        d += 1
    if m > 1:
        factors.add(m)
    return factors


# --------------------------------------------------------------------------- #
# The bilinear pairing  e(a, b) = gt^(a * b mod n)
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Pairing:
    """A concrete bilinear pairing from Z_n into the order-n subgroup of (Z_p)^*."""

    n: int   # order of the source group G = Z_n
    p: int   # prime defining the target field (Z_p)^*
    gt: int  # generator of the order-n target subgroup

    @classmethod
    def build(cls, n: int) -> "Pairing":
        if not is_prime(n):
            raise ValueError("for nondegeneracy choose n prime in this model")
        p = find_prime_with_subgroup(n)
        gt = element_of_order(n, p)
        return cls(n=n, p=p, gt=gt)

    def smul(self, x: int, point: int) -> int:
        """Scalar multiplication x . point in the additive group G = Z_n."""
        return (x * point) % self.n

    def add(self, a: int, b: int) -> int:
        """Group addition in G = Z_n."""
        return (a + b) % self.n

    def neg(self, a: int) -> int:
        """Group negation in G = Z_n."""
        return (-a) % self.n

    def e(self, a: int, b: int) -> int:
        """The pairing value e(a, b) in the target group T."""
        return pow(self.gt, (a * b) % self.n, self.p)

    def t_mul(self, u: int, v: int) -> int:
        """Multiplication in the target group T."""
        return (u * v) % self.p


# --------------------------------------------------------------------------- #
# 1. Bilinearity and scalar transport
# --------------------------------------------------------------------------- #
def demo_bilinearity(P: Pairing) -> None:
    print("== 1. Bilinearity and scalar transport ==")
    a, b, q, x = 7, 13, 9, 5
    lhs = P.e(P.add(a, b), q)
    rhs = P.t_mul(P.e(a, q), P.e(b, q))
    print(f"  e(a+b, q) = {lhs},  e(a,q)*e(b,q) = {rhs},  equal = {lhs == rhs}")
    # e(x.p, q) = e(p, q)^x
    lhs2 = P.e(P.smul(x, a), q)
    rhs2 = pow(P.e(a, q), x, P.p)
    print(f"  e(x.p, q) = {lhs2},  e(p,q)^x = {rhs2},  equal = {lhs2 == rhs2}")
    print(f"  e(0, q) = {P.e(0, q)} (unit law)\n")


# --------------------------------------------------------------------------- #
# 2. BLS signatures
# --------------------------------------------------------------------------- #
def demo_bls(P: Pairing) -> None:
    print("== 2. BLS signature completeness ==")
    g, x, msg_hash = 1, 23, 11          # generator g, secret key x, hash H
    pub = P.smul(x, g)                   # public key X = x.g
    sig = P.smul(x, msg_hash)            # signature sigma = x.H
    ok = P.e(sig, g) == P.e(msg_hash, pub)
    print(f"  public key X = {pub}, signature sigma = {sig}")
    print(f"  verify  e(sigma,g) = {P.e(sig, g)} == e(H,X) = {P.e(msg_hash, pub)} : {ok}")
    forged = (sig + 1) % P.n
    bad = P.e(forged, g) == P.e(msg_hash, pub)
    print(f"  a tampered signature verifies: {bad}\n")


# --------------------------------------------------------------------------- #
# 3. Aggregate signatures and batch verification
# --------------------------------------------------------------------------- #
def demo_aggregate(P: Pairing) -> None:
    print("== 3. Short aggregate signatures + batch verification ==")
    g = 1
    secrets = [23, 41, 8, 67, 19]
    hashes = [11, 30, 52, 5, 88]        # distinct messages
    pubs = [P.smul(x, g) for x in secrets]
    sigs = [P.smul(x, h) for x, h in zip(secrets, hashes)]

    # Aggregate signature: one group element, the sum of all signatures.
    agg = 0
    for s in sigs:
        agg = P.add(agg, s)

    # Verifier computes the product of per-signer pairings.
    prod = 1
    for h, X in zip(hashes, pubs):
        prod = P.t_mul(prod, P.e(h, X))

    ok = P.e(agg, g) == prod
    print(f"  {len(secrets)} signers compress to one element sigma_agg = {agg}")
    print(f"  e(sigma_agg, g) = {P.e(agg, g)} == product = {prod} : {ok}")

    # Batch verification of individually valid signatures.
    lhs = 1
    for s in sigs:
        lhs = P.t_mul(lhs, P.e(s, g))
    print(f"  batch:  prod e(sigma_i,g) = {lhs} == prod e(H_i,X_i) = {prod} : {lhs == prod}\n")


# --------------------------------------------------------------------------- #
# 4. The rogue-key attack and the distinct-message defense
# --------------------------------------------------------------------------- #
def demo_rogue_key(P: Pairing) -> None:
    print("== 4. Rogue-key attack and its defense ==")
    g, H = 1, 11
    honest_secret = 23
    X1 = P.smul(honest_secret, g)        # honest public key (secret unknown to attacker)

    # Attacker: pick w, register rogue key X2 = w.g - X1, forge sigma = w.H.
    w = 37
    X2 = P.add(P.smul(w, g), P.neg(X1))  # rogue key, no honest secret used
    forged_sig = P.smul(w, H)            # forged aggregate signature

    summed_key = P.add(X1, X2)           # naive verifier collapses keys
    attack_ok = P.e(forged_sig, g) == P.e(H, summed_key)
    print(f"  rogue key X2 = {X2}, X1 + X2 = {summed_key} = w.g = {P.smul(w, g)}")
    print(f"  NAIVE same-message verify passes (forgery!): {attack_ok}")

    # Defense: keep per-signer pairings separate (distinct messages).
    H1, H2 = 11, 52
    # The honest signer 1 produces a real signature; the attacker cannot supply a
    # valid separate factor for its rogue key on a distinct message without the
    # corresponding discrete log.
    sig1 = P.smul(honest_secret, H1)
    separate_lhs = P.t_mul(P.e(sig1, g), P.e(forged_sig, g))
    separate_rhs = P.t_mul(P.e(H1, X1), P.e(H2, X2))
    print(f"  DISTINCT-message separated check accepts forgery: "
          f"{separate_lhs == separate_rhs}\n")


# --------------------------------------------------------------------------- #
# 5. The MOV reduction
# --------------------------------------------------------------------------- #
def demo_mov(P: Pairing) -> None:
    print("== 5. MOV transport of the discrete log ==")
    g = 1
    secret = 29
    X = P.smul(secret, g)
    u = P.e(g, g)                        # base in target group
    v = P.e(X, g)                        # v = u^secret
    # Solve the target-group discrete log by brute force (small group).
    recovered = next(k for k in range(P.n) if pow(u, k, P.p) == v)
    print(f"  e(g,g) = {u}, e(x.g, g) = {v}")
    print(f"  recovered secret = {recovered}, true secret = {secret % P.n}, "
          f"match = {recovered == secret % P.n}\n")


# --------------------------------------------------------------------------- #
# 6. An alternating pairing on Z_n^2 and its antisymmetry
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class AlternatingPairing:
    """Alternating pairing on G = Z_n^2 via the 2x2 determinant in the exponent."""

    n: int
    p: int
    gt: int

    @classmethod
    def build(cls, n: int) -> "AlternatingPairing":
        base = Pairing.build(n)
        return cls(n=n, p=base.p, gt=base.gt)

    def e(self, u: tuple[int, int], v: tuple[int, int]) -> int:
        det = (u[0] * v[1] - u[1] * v[0]) % self.n
        return pow(self.gt, det, self.p)


def demo_alternating(A: AlternatingPairing) -> None:
    print("== 6. Alternating pairing and antisymmetry ==")
    P = (3, 5)
    Q = (7, 2)
    self_pair = A.e(P, P)
    anti = (A.e(P, Q) * A.e(Q, P)) % A.p
    print(f"  e(P, P) = {self_pair} (alternating: should be 1)")
    print(f"  e(P,Q)*e(Q,P) = {anti} (antisymmetry: should be 1)\n")


def main() -> None:
    P = Pairing.build(n=101)
    print(f"Pairing model: G = Z_{P.n}, T = order-{P.n} subgroup of (Z_{P.p})^*, "
          f"gt = {P.gt}\n")
    demo_bilinearity(P)
    demo_bls(P)
    demo_aggregate(P)
    demo_rogue_key(P)
    demo_mov(P)
    demo_alternating(AlternatingPairing.build(n=101))


if __name__ == "__main__":
    main()
