"""Escher Staircases: numerical demonstrations.

An *Escher staircase* in a commutative ring is an infinite strictly ascending chain
of ideals

    I_0  <  I_1  <  I_2  <  ...

that "loops back": the meet (intersection) of the whole ascending tower equals the
bottom rung, and in the flagship examples that bottom rung is the zero ideal {0}.  A
commutative ring admits such a staircase if and only if it is NOT Noetherian.

This script demonstrates, with fully explicit finite windows:

  1. The tail-vanishing staircase  S_n = {f : f_k = 0 for all k >= n}  in the
     product ring of integer sequences, with the indicator witness separating each
     step and the loop-back to {0}.

  2. The variable staircase  V_n = <x_0, ..., x_{n-1}>  in the polynomial ring in
     countably many variables, with monomial-ideal membership tested by divisibility.

  3. The product transfer law: R x S has a staircase iff a factor does.

  4. The collapse: each rung V_n is a proper ideal of the polynomial ring, but
     generates the WHOLE fraction field once nonzero elements become invertible.

Everything is self-contained; no third-party libraries are required.
"""

from __future__ import annotations

from typing import Callable, Dict, List, Sequence, Set, Tuple


# ---------------------------------------------------------------------------
# 1. The tail-vanishing staircase  S_n  in the product ring of integer sequences
# ---------------------------------------------------------------------------

# We model a "finitely supported" integer sequence as a dict {index: value} with
# only nonzero entries stored.  A sequence f belongs to S_n iff every stored index
# is < n (i.e. f_k = 0 for all k >= n).

Sequence_ = Dict[int, int]


def in_tail_zero_ideal(f: Sequence_, n: int) -> bool:
    """Return True iff f in S_n, i.e. f_k = 0 for all k >= n."""
    return all(index < n for index, value in f.items() if value != 0)


def indicator(n: int) -> Sequence_:
    """The indicator sequence e_n: value 1 at position n, 0 elsewhere."""
    return {n: 1}


def demo_tail_staircase(depth: int = 6) -> None:
    """Certify that S_0 < S_1 < ... is a strictly ascending, looping staircase."""
    print("=" * 70)
    print("1. Tail-vanishing staircase  S_n  in the ring of integer sequences")
    print("=" * 70)
    for n in range(depth):
        e = indicator(n)  # witness for the strict jump S_n < S_{n+1}
        in_next = in_tail_zero_ideal(e, n + 1)
        in_here = in_tail_zero_ideal(e, n)
        strict = in_next and not in_here
        print(
            f"  e_{n} = (1 at pos {n})  in S_{n+1}: {in_next},  in S_{n}: {in_here}"
            f"   =>  S_{n} < S_{n+1}: {strict}"
        )
    # loop-back: only the zero sequence lies in S_0, hence in the whole meet.
    only_zero_in_S0 = in_tail_zero_ideal({}, 0) and not in_tail_zero_ideal({0: 1}, 0)
    print(f"  S_0 = {{0}} (only the zero sequence): {only_zero_in_S0}")
    print("  => meet of all S_n = S_0 = {0}: the staircase loops back.\n")


# ---------------------------------------------------------------------------
# 2. The variable staircase  V_n = <x_0, ..., x_{n-1}>  (monomial ideals)
# ---------------------------------------------------------------------------

# A monomial in x_0, x_1, ... is an exponent vector, stored as a tuple of
# (variable_index, exponent) pairs with positive exponents, sorted by index.
# A monomial m lies in the monomial ideal generated by variables in a set S iff
# some variable x_i with i in S divides m, i.e. m has positive exponent at i.

Monomial = Tuple[Tuple[int, int], ...]


def monomial(**powers: int) -> Monomial:
    """Build a monomial from keyword powers, e.g. monomial(x0=2, x1=1)."""
    items = []
    for name, exp in powers.items():
        if exp > 0:
            items.append((int(name[1:]), exp))
    return tuple(sorted(items))


def variable(i: int) -> Monomial:
    """The bare variable x_i as a monomial."""
    return ((i, 1),)


def in_variable_ideal(m: Monomial, gens: Set[int]) -> bool:
    """Return True iff monomial m lies in the ideal generated by {x_i : i in gens}."""
    return any(exp > 0 and idx in gens for idx, exp in m)


def demo_variable_staircase(depth: int = 6) -> None:
    """Certify x_n in V_{n+1} \\ V_n, so V_0 < V_1 < ... is strictly ascending."""
    print("=" * 70)
    print("2. Variable staircase  V_n = <x_0, ..., x_{n-1}>  in k[x_0, x_1, ...]")
    print("=" * 70)
    for n in range(depth):
        gens_next: Set[int] = set(range(n + 1))  # V_{n+1} = <x_0,...,x_n>
        gens_here: Set[int] = set(range(n))      # V_n     = <x_0,...,x_{n-1}>
        xn = variable(n)
        in_next = in_variable_ideal(xn, gens_next)
        in_here = in_variable_ideal(xn, gens_here)
        print(
            f"  x_{n}  in V_{n+1}: {in_next},  in V_{n}: {in_here}"
            f"   =>  V_{n} < V_{n+1}: {in_next and not in_here}"
        )
    print("  V_0 = <empty> = {0}; meet of all V_n = V_0 = {0}: loops back.\n")


# ---------------------------------------------------------------------------
# 3. The product transfer law:  Esc(R x S)  <=>  Esc(R) or Esc(S)
# ---------------------------------------------------------------------------

def escher_product(has_staircase_R: bool, has_staircase_S: bool) -> bool:
    """The transfer law: a finite product has a staircase iff some factor does."""
    return has_staircase_R or has_staircase_S


def demo_product_law() -> None:
    print("=" * 70)
    print("3. Product transfer law:  Esc(R x S)  <=>  Esc(R) or Esc(S)")
    print("=" * 70)
    cases: List[Tuple[str, bool, str, bool]] = [
        ("Q[x_0,x_1,...]", True, "Q", False),   # staircase x none
        ("Q", False, "Q", False),               # none x none
        ("Q[x_0,x_1,...]", True, "Z^N", True),  # staircase x staircase
        ("Z_p", False, "Q[x_0,x_1,...]", True), # none x staircase
    ]
    for nameR, escR, nameS, escS in cases:
        result = escher_product(escR, escS)
        witness = (
            "left coordinate" if escR else "right coordinate" if escS else "none"
        )
        print(
            f"  ({nameR}) x ({nameS}):  Esc = {result}"
            f"   (witnessing coordinate: {witness})"
        )
    print()


# ---------------------------------------------------------------------------
# 4. The collapse:  V_n proper in the ring, but = (1) in the fraction field
# ---------------------------------------------------------------------------

def rung_generates_unit_in_field(gens: Set[int]) -> bool:
    """In a field every nonzero ideal is the whole ring: a nonempty rung swells to (1)."""
    return len(gens) > 0


def demo_collapse(depth: int = 6) -> None:
    """Track each rung V_n as an ideal of the ring vs. the fraction field."""
    print("=" * 70)
    print("4. The collapse:  Q[x_0,x_1,...]  ↪  Q(x_0,x_1,...)  (fraction field)")
    print("=" * 70)
    print("  rung    in the ring         in the fraction field")
    for n in range(1, depth):
        gens: Set[int] = set(range(n))
        # In the polynomial ring V_n is a PROPER ideal (does not contain 1):
        proper_in_ring = not in_variable_ideal(monomial(), gens)  # 1 = empty monomial
        # In the field every nonzero element is invertible, so V_n = (1):
        unit_in_field = rung_generates_unit_in_field(gens)
        print(
            f"  V_{n}     proper: {proper_in_ring!s:<12} "
            f"equals whole field (1): {unit_in_field}"
        )
    print("  => the infinite strict tower downstairs collapses to a single level"
          " upstairs.\n")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> None:
    print()
    print("ESCHER STAIRCASES: infinite ascending ideal chains that loop back")
    print("(a ring admits one iff it is NOT Noetherian)\n")
    demo_tail_staircase()
    demo_variable_staircase()
    demo_product_law()
    demo_collapse()
    print("All demonstrations completed.")


if __name__ == "__main__":
    main()
