"""
Numerical demonstrations for:

    Infinite Sign Changes of Symmetric Power L-Function Coefficients
    over Sums of m Squares, for All Even m.

This self-contained script illustrates the structural backbone of the result:

  1. The representation sets  S_m = { n : n is a sum of m squares }  are NESTED:
         S_2 subset S_3 subset S_4 subset ...
     (pad a representation with zero coordinates).

  2. They SATURATE at m = 4 (Lagrange's four-square theorem):
         S_m = all natural numbers,   for every m >= 4.

  3. NESTING transfers sign changes of any real sequence from S_2 to every S_m,
     so the whole family collapses to the single base case m = 2.

  4. A two-sided partial-sum OSCILLATION criterion: if the running totals of a
     sequence are unbounded above and below, the sequence changes sign forever.

We use a concrete, fully inlined toy Hecke-like sequence (the normalized
coefficients of the weight-12 cusp form's symmetric square, computed via the
standard Hecke recursion on Ramanujan's tau) purely to make the phenomena
visible; all qualitative conclusions are model-independent.

Run:  python demo.py
"""

from __future__ import annotations

from math import isqrt
from typing import Dict, List, Set, Tuple


# ---------------------------------------------------------------------------
# 1. Representability as a sum of m squares
# ---------------------------------------------------------------------------

def is_sum_of_m_squares(m: int, n: int) -> bool:
    """Return True iff n can be written as x_1^2 + ... + x_m^2 with x_i >= 0.

    Uses the saturation shortcut (every n is a sum of 4 squares, hence of m
    squares for m >= 4) and a bounded dynamic-programming search otherwise.
    """
    if n < 0 or m < 0:
        return False
    if m == 0:
        return n == 0
    if m >= 4:  # Lagrange + padding: S_m = N for m >= 4
        return True
    # reachable[t] = set of values expressible as a sum of exactly t squares, <= n
    squares: List[int] = [s * s for s in range(isqrt(n) + 1)]
    reachable: Set[int] = {0}
    for _ in range(m):
        nxt: Set[int] = set()
        for value in reachable:
            for sq in squares:
                if value + sq <= n:
                    nxt.add(value + sq)
        reachable = nxt
    return n in reachable


def representation_set(m: int, upper: int) -> List[int]:
    """List of n in [0, upper] that are sums of m squares."""
    return [n for n in range(upper + 1) if is_sum_of_m_squares(m, n)]


# ---------------------------------------------------------------------------
# 2. A concrete arithmetic sequence (toy model of lambda_{sym^j f})
# ---------------------------------------------------------------------------

def ramanujan_tau(limit: int) -> Dict[int, int]:
    """Compute Ramanujan's tau(n) for 1 <= n <= limit.

    tau is the coefficient sequence of the weight-12 cusp form Delta.  We build
    it from prime-power values (via the Hecke recursion) and multiplicativity.
    """
    # tau at prime powers is generated by  tau(p^{k+1}) = tau(p) tau(p^k)
    #   - p^{11} tau(p^{k-1}).  We need tau(p) for primes p <= limit.
    def sieve(bound: int) -> List[int]:
        flags = [True] * (bound + 1)
        flags[0:2] = [False, False]
        for i in range(2, isqrt(bound) + 1):
            if flags[i]:
                for j in range(i * i, bound + 1, i):
                    flags[j] = False
        return [i for i in range(2, bound + 1) if flags[i]]

    # Known small tau at primes (Delta = q prod (1-q^n)^24).  We compute tau(p)
    # directly from the q-expansion of Delta to avoid hardcoding.
    tau_full = delta_q_expansion(limit)
    primes = sieve(limit)

    tau: Dict[int, int] = {1: 1}
    for p in primes:
        # fill prime powers p^k <= limit
        pk = p
        tp = tau_full[p]
        tau[p] = tp
        prev, cur = 1, tp  # tau(p^0)=1, tau(p^1)=tp
        power = p
        while power * p <= limit:
            nxt = tp * cur - (p ** 11) * prev
            power *= p
            tau[power] = nxt
            prev, cur = cur, nxt
    # multiplicativity
    for n in range(2, limit + 1):
        if n in tau:
            continue
        # factor n
        val = 1
        rem = n
        for p in primes:
            if p * p > rem:
                break
            if rem % p == 0:
                pk = 1
                while rem % p == 0:
                    rem //= p
                    pk *= p
                val *= tau[pk]
        if rem > 1:
            val *= tau[rem]
        tau[n] = val
    return tau


def delta_q_expansion(limit: int) -> List[int]:
    """Coefficients tau(n) of Delta = q * prod_{n>=1} (1 - q^n)^24, up to `limit`.

    Returns a list T with T[n] = tau(n) for 1 <= n <= limit (T[0] unused).
    """
    # prod (1 - q^n)^24 as a power series up to degree limit-1, then shift by q.
    size = limit  # we need Delta up to q^limit => product up to q^{limit-1}
    prod = [0] * (size)
    prod[0] = 1
    for n in range(1, size):
        # multiply current product by (1 - q^n)^24 = sum C(24,k)(-1)^k q^{nk}
        # do it 24 times by (1 - q^n)
        for _ in range(24):
            for d in range(size - 1, n - 1, -1):
                prod[d] -= prod[d - n]
    # Delta(q) = q * prod  =>  tau(n) = prod[n-1]
    tau = [0] * (limit + 1)
    for n in range(1, limit + 1):
        tau[n] = prod[n - 1]
    return tau


def sym2_coefficients(limit: int) -> Dict[int, float]:
    """A normalized 'symmetric-square-like' real sequence a(n).

    We use the sign-carrying normalized Hecke eigenvalue lambda(n) = tau(n)/n^{11/2}
    (a real sequence in [-2 d(n), 2 d(n)] by Deligne) as a faithful stand-in for
    lambda_{sym^j f}; its signs are exactly those of tau(n), which oscillate.
    """
    tau = ramanujan_tau(limit)
    return {n: tau[n] / (n ** 5.5) for n in range(1, limit + 1)}


# ---------------------------------------------------------------------------
# 3. Sign changes over a set
# ---------------------------------------------------------------------------

def sign_change_stats(a: Dict[int, float], sample: List[int]) -> Tuple[int, int, int]:
    """Return (num_positive, num_negative, num_adjacent_sign_changes) of a over
    the increasing sample set."""
    vals = [a[n] for n in sample if n in a and a[n] != 0.0]
    pos = sum(1 for v in vals if v > 0)
    neg = sum(1 for v in vals if v < 0)
    changes = sum(1 for x, y in zip(vals, vals[1:]) if x * y < 0)
    return pos, neg, changes


# ---------------------------------------------------------------------------
# 4. Oscillation engine: two-sided unbounded partial sums
# ---------------------------------------------------------------------------

def partial_sum_records(a: Dict[int, float], sample: List[int]) -> Tuple[float, float]:
    """Track running maxima/minima of the partial sums of a over the sample."""
    total = 0.0
    hi, lo = 0.0, 0.0
    for n in sample:
        total += a.get(n, 0.0)
        hi = max(hi, total)
        lo = min(lo, total)
    return hi, lo


# ---------------------------------------------------------------------------
# Main demonstration
# ---------------------------------------------------------------------------

def main() -> None:
    upper = 2000
    print("=" * 70)
    print("Sign changes over sums of m squares  --  numerical demonstration")
    print("=" * 70)

    # ---- (A) Nesting and saturation of the representation sets -------------
    print("\n[A] Representation sets S_m = { n <= %d : sum of m squares }" % upper)
    sets = {m: set(representation_set(m, upper)) for m in range(2, 7)}
    for m in range(2, 7):
        print(f"    |S_{m}| = {len(sets[m]):5d}"
              f"    (density {len(sets[m])/(upper+1):.3f})")
    print("\n    Nesting check  S_2 ⊆ S_3 ⊆ S_4 ⊆ S_5 ⊆ S_6:")
    for m in range(2, 6):
        print(f"      S_{m} ⊆ S_{m+1}?  {sets[m].issubset(sets[m+1])}")
    print("\n    Saturation check  S_m = {0..%d} for m >= 4:" % upper)
    full = set(range(upper + 1))
    for m in range(4, 7):
        print(f"      S_{m} = all naturals?  {sets[m] == full}")

    # ---- (B) Sign changes transfer from S_2 to every S_m -----------------
    print("\n[B] Sign changes of a normalized Hecke sequence a(n) over S_m")
    a = sym2_coefficients(upper)
    for m in range(2, 7):
        sample = sorted(sets[m])
        pos, neg, changes = sign_change_stats(a, sample)
        print(f"    m={m}:  #positive={pos:5d}  #negative={neg:5d}"
              f"  adjacent sign changes={changes:5d}")
    print("\n    Both signs occur many times for every m  =>  infinitely many")
    print("    sign changes, consistent with the reduction to the base case m=2.")

    # ---- (C) Collapse for m >= 4 -----------------------------------------
    print("\n[C] Collapse: for m >= 4 the S_m-count equals the all-integers count")
    all_sample = list(range(1, upper + 1))
    p0, n0, c0 = sign_change_stats(a, all_sample)
    p4, n4, c4 = sign_change_stats(a, sorted(sets[4]))
    print(f"    over all n<= {upper}:  #pos={p0}  #neg={n0}  changes={c0}")
    print(f"    over S_4        :  #pos={p4}  #neg={n4}  changes={c4}")
    print(f"    identical?  {(p0, n0, c0) == (p4, n4, c4)}")

    # ---- (D) Oscillation engine -----------------------------------------
    print("\n[D] Two-sided unbounded partial sums (oscillation engine)")
    for m in [2, 4]:
        hi, lo = partial_sum_records(a, sorted(sets[m]))
        print(f"    m={m}:  max partial sum = {hi:+.4f}   min partial sum = {lo:+.4f}")
    print("    Partial sums climb above 0 and sink below 0  =>  the sequence")
    print("    cannot be eventually one-signed (Theorem: oscillation engine).")

    print("\nDone.")


if __name__ == "__main__":
    main()
