"""Numerical demonstration of the No-Stretching Theorem for hypercube labelings.

Two complementary settings are illustrated.

(A) THE CORE THEOREM. Let G be a connected graph and ell a labeling of its
    vertices by the corners of the binary Hamming hypercube Q_k (length-k strings
    over GF(2), adjacency = Hamming distance 1). Suppose ell is EDGE-GENTLE: every
    edge of G has endpoints whose labels are equal or differ in exactly one
    coordinate. Then

        d_{Q_k}(ell(u), ell(v)) = Hamming(ell(u), ell(v)) <= d_G(u, v)

    for all u, v: the labeling never stretches distances. (It may contract them.)

(B) THE EDGE-PARTITION SOURCE. Sorting E(G) into t classes and recording
    class-parities of walks modulo the cycle space gives a labeling into the
    quotient (Z/2)^t / C, of dimension k = t - rank(A), where A is the
    cycle-class parity matrix over GF(2). Here the relevant target is the CAYLEY
    GRAPH H on the quotient group generated by the images of the t edge classes:
    every edge of G moves the label by exactly one generator, so by the same
    push-forward argument d_H(ell(u), ell(v)) <= d_G(u, v). When the class images
    are independent coordinate directions (e.g. the Djokovic-Winkler relation on a
    partial cube), H is exactly the standard Hamming hypercube and the two
    settings coincide.

The module is fully self-contained (standard library only), uses type hints, and
inlines every helper.
"""

from __future__ import annotations

from collections import deque
from itertools import combinations
from typing import Dict, List, Set, Tuple

Vertex = int
Edge = Tuple[Vertex, Vertex]
Graph = Dict[Vertex, List[Vertex]]
BitVec = Tuple[int, ...]


# --------------------------------------------------------------------------- #
# Hamming distance and the hypercube metric (Theorem: d_{Q_k} = Hamming).
# --------------------------------------------------------------------------- #
def hamming_distance(x: BitVec, y: BitVec) -> int:
    """Number of coordinates in which two GF(2) vectors differ."""
    if len(x) != len(y):
        raise ValueError("vectors must have equal length")
    return sum(1 for a, b in zip(x, y) if a != b)


# --------------------------------------------------------------------------- #
# Graph utilities.
# --------------------------------------------------------------------------- #
def build_graph(n: int, edges: List[Edge]) -> Graph:
    """Adjacency-list undirected graph on vertices 0..n-1."""
    g: Graph = {v: [] for v in range(n)}
    for u, v in edges:
        g[u].append(v)
        g[v].append(u)
    return g


def bfs_distances(g: Graph, source: Vertex) -> Dict[Vertex, int]:
    """Single-source shortest-path distances by breadth-first search."""
    dist: Dict[Vertex, int] = {source: 0}
    queue: deque[Vertex] = deque([source])
    while queue:
        u = queue.popleft()
        for w in g[u]:
            if w not in dist:
                dist[w] = dist[u] + 1
                queue.append(w)
    return dist


def all_pairs_distances(g: Graph) -> Dict[Vertex, Dict[Vertex, int]]:
    """All-pairs shortest-path distances via repeated BFS."""
    return {v: bfs_distances(g, v) for v in g}


# --------------------------------------------------------------------------- #
# GF(2) linear algebra for the cycle space.
# --------------------------------------------------------------------------- #
def gf2_row_reduce(rows: List[int]) -> List[int]:
    """Gaussian elimination over GF(2) on bitmask-encoded rows.

    Returns a list of pivot rows (a basis of the row space). Each row is an
    integer whose bit j is the j-th coordinate.
    """
    basis: List[int] = []
    for r in rows:
        cur = r
        for b in basis:
            cur = min(cur, cur ^ b)
        if cur:
            basis.append(cur)
            basis.sort(reverse=True)
    return basis


# --------------------------------------------------------------------------- #
# Edge-gentleness check for a labeling into the Hamming hypercube.
# --------------------------------------------------------------------------- #
def is_edge_gentle(edges: List[Edge], label: Dict[Vertex, BitVec]) -> bool:
    """True iff every edge has endpoints at Hamming distance 0 or 1."""
    return all(hamming_distance(label[u], label[v]) <= 1 for u, v in edges)


# --------------------------------------------------------------------------- #
# The edge-partition parity-quotient labeling (raw labels, quotient, generators).
# --------------------------------------------------------------------------- #
def edge_partition_labeling(
    n: int,
    edges: List[Edge],
    edge_class: Dict[Edge, int],
    num_classes: int,
    root: Vertex = 0,
) -> Tuple[Dict[Vertex, BitVec], List[BitVec], int]:
    """Construct the parity-quotient labeling of vertices.

    Returns (label, generators, k):
      * label[v] : the k-bit quotient label of v (surviving coordinates),
      * generators : the images of the t edge classes in the quotient (the
        generating set of the Cayley graph H),
      * k = t - rank(A) : the quotient dimension.
    """
    g = build_graph(n, edges)

    def class_of(u: int, v: int) -> int:
        e = (u, v) if (u, v) in edge_class else (v, u)
        return edge_class[e]

    # 1. Raw labels via spanning-tree BFS; raw[v] is a bitmask over t classes.
    raw: Dict[Vertex, int] = {root: 0}
    tree_edges: Set[Edge] = set()
    queue: deque[Vertex] = deque([root])
    while queue:
        u = queue.popleft()
        for w in g[u]:
            if w not in raw:
                j = class_of(u, w)
                raw[w] = raw[u] ^ (1 << j)
                tree_edges.add((min(u, w), max(u, w)))
                queue.append(w)

    # 2. Cycle space: each non-tree edge {u,w} contributes raw[u] ^ raw[w] ^ e_j.
    cycle_rows: List[int] = []
    for u, v in edges:
        key = (min(u, v), max(u, v))
        if key in tree_edges:
            continue
        j = class_of(u, v)
        cycle_rows.append(raw[u] ^ raw[v] ^ (1 << j))
    basis = gf2_row_reduce(cycle_rows)
    rank_a = len(basis)

    # 3. Quotient: keep the non-pivot ("surviving") coordinates.
    pivot_coords = {b.bit_length() - 1 for b in basis}
    surviving = [j for j in range(num_classes) if j not in pivot_coords]

    def reduce_mod_cycle(vec: int) -> int:
        cur = vec
        for b in basis:
            cur = min(cur, cur ^ b)
        return cur

    def to_bits(vec: int) -> BitVec:
        reduced = reduce_mod_cycle(vec)
        return tuple((reduced >> j) & 1 for j in surviving)

    label: Dict[Vertex, BitVec] = {v: to_bits(raw[v]) for v in range(n)}
    generators = [to_bits(1 << j) for j in range(num_classes)]
    k = num_classes - rank_a
    return label, generators, k


def cayley_distances(k: int, generators: List[BitVec]) -> Dict[BitVec, int]:
    """Word-length distances from the identity in the Cayley graph on (Z/2)^k
    generated by `generators` (zero generators ignored). BFS over the group."""
    gens = [g for g in generators if any(g)]
    start: BitVec = tuple(0 for _ in range(k))
    dist: Dict[BitVec, int] = {start: 0}
    queue: deque[BitVec] = deque([start])
    while queue:
        x = queue.popleft()
        for g in gens:
            y = tuple(a ^ b for a, b in zip(x, g))
            if y not in dist:
                dist[y] = dist[x] + 1
                queue.append(y)
    return dist


def cayley_distance(
    a: BitVec, b: BitVec, cayley_from_id: Dict[BitVec, int]
) -> int:
    """Distance between two group elements = word length of their difference."""
    diff = tuple(x ^ y for x, y in zip(a, b))
    return cayley_from_id[diff]


# --------------------------------------------------------------------------- #
# Verification routines.
# --------------------------------------------------------------------------- #
def verify_no_stretching_hamming(
    n: int, edges: List[Edge], label: Dict[Vertex, BitVec]
) -> Tuple[bool, int]:
    """For an edge-gentle labeling: check Hamming(label) <= d_G everywhere.
    Returns (ok, total_defect) with total_defect = sum of (d_G - Hamming) >= 0."""
    dist = all_pairs_distances(build_graph(n, edges))
    ok, total_defect = True, 0
    for u, v in combinations(range(n), 2):
        dg, dh = dist[u][v], hamming_distance(label[u], label[v])
        ok = ok and (dh <= dg)
        total_defect += dg - dh
    return ok, total_defect


def verify_no_stretching_cayley(
    n: int,
    edges: List[Edge],
    label: Dict[Vertex, BitVec],
    k: int,
    generators: List[BitVec],
) -> Tuple[bool, int]:
    """For an edge-partition labeling: check d_H(label) <= d_G everywhere, where
    H is the Cayley graph generated by the class images."""
    dist = all_pairs_distances(build_graph(n, edges))
    cay = cayley_distances(k, generators)
    ok, total_defect = True, 0
    for u, v in combinations(range(n), 2):
        dg = dist[u][v]
        dh = cayley_distance(label[u], label[v], cay)
        ok = ok and (dh <= dg)
        total_defect += dg - dh
    return ok, total_defect


# --------------------------------------------------------------------------- #
# Examples.
# --------------------------------------------------------------------------- #
def example_cube_dist_equals_hamming() -> None:
    """Confirm d_{Q_k} = Hamming on random hypercube pairs (Q3)."""
    import random

    print("=" * 70)
    print("Example 1: hypercube distance equals Hamming distance (Q3)")
    random.seed(0)
    k = 3
    g = build_graph(
        2 ** k,
        [(x, x ^ (1 << i)) for x in range(2 ** k) for i in range(k)
         if x < (x ^ (1 << i))],
    )
    dist = all_pairs_distances(g)
    bits = lambda x: tuple((x >> i) & 1 for i in range(k))
    all_match = True
    for _ in range(6):
        a, b = random.randrange(2 ** k), random.randrange(2 ** k)
        gd, hd = dist[a][b], hamming_distance(bits(a), bits(b))
        all_match = all_match and (gd == hd)
        print(f"  x={bits(a)} y={bits(b)}  d_Q={gd}  Hamming={hd}")
    print(f"  all pairs match: {all_match}")


def example_edge_gentle_contraction() -> None:
    """A directly-defined edge-gentle labeling that strictly contracts.

    Path 0-1-2-3-4 labeled by parity ell(v) = (v mod 2) in Q1. Each edge flips the
    single coordinate (edge-gentle), but endpoints two apart collapse to equal
    labels: no-stretching holds and the defect is strictly positive."""
    print("=" * 70)
    print("Example 2: edge-gentle parity labeling of P5 into Q1 (core theorem)")
    n = 5
    edges: List[Edge] = [(0, 1), (1, 2), (2, 3), (3, 4)]
    label: Dict[Vertex, BitVec] = {v: (v % 2,) for v in range(n)}
    for v in range(n):
        print(f"  label[{v}] = {label[v]}")
    print(f"  edge-gentle: {is_edge_gentle(edges, label)}")
    ok, defect = verify_no_stretching_hamming(n, edges, label)
    print(f"  no-stretching holds: {ok};  total contraction defect: {defect}")
    print("  (defect > 0  =>  the labeling genuinely contracts, never stretches)")


def example_partition_path() -> None:
    """Path P4, each edge its own class: isometric partial-cube embedding."""
    print("=" * 70)
    print("Example 3: edge partition of P4, each edge its own class")
    n = 4
    edges: List[Edge] = [(0, 1), (1, 2), (2, 3)]
    edge_class = {(0, 1): 0, (1, 2): 1, (2, 3): 2}
    label, gens, k = edge_partition_labeling(n, edges, edge_class, 3)
    for v in range(n):
        print(f"  label[{v}] = {label[v]}")
    print(f"  quotient dimension k = {k};  class generators = {gens}")
    print(f"  edge-gentle (Hamming cube): {is_edge_gentle(edges, label)}")
    ok, defect = verify_no_stretching_cayley(n, edges, label, k, gens)
    print(f"  no-stretching (Cayley H) holds: {ok};  total defect: {defect}")
    print("  (defect 0  =>  isometric: P4 is a partial cube)")


def example_partition_c4() -> None:
    """4-cycle, Djokovic-Winkler partition: isometric into the Hamming cube Q2."""
    print("=" * 70)
    print("Example 4: Djokovic-Winkler partition of C4 (opposite edges paired)")
    n = 4
    edges: List[Edge] = [(0, 1), (1, 2), (2, 3), (3, 0)]
    edge_class = {(0, 1): 0, (2, 3): 0, (1, 2): 1, (3, 0): 1}
    label, gens, k = edge_partition_labeling(n, edges, edge_class, 2)
    for v in range(n):
        print(f"  label[{v}] = {label[v]}")
    print(f"  quotient dimension k = {k};  class generators = {gens}")
    print(f"  edge-gentle (Hamming cube): {is_edge_gentle(edges, label)}")
    ok, defect = verify_no_stretching_cayley(n, edges, label, k, gens)
    print(f"  no-stretching (Cayley H) holds: {ok};  total defect: {defect}")
    print("  (class images are standard basis  =>  H is the Hamming cube Q2)")


def example_partition_triangle() -> None:
    """Triangle K3: each edge its own class. The QUOTIENT labeling into the
    standard Hamming cube is NOT edge-gentle and would stretch; but the proper
    target is the Cayley graph H (here K4), in which no-stretching holds. This
    shows why the target generating set matters."""
    print("=" * 70)
    print("Example 5: triangle K3, each edge its own class")
    n = 3
    edges: List[Edge] = [(0, 1), (1, 2), (2, 0)]
    edge_class = {(0, 1): 0, (1, 2): 1, (2, 0): 2}
    label, gens, k = edge_partition_labeling(n, edges, edge_class, 3)
    for v in range(n):
        print(f"  label[{v}] = {label[v]}")
    print(f"  quotient dimension k = {k};  class generators = {gens}")
    print(f"  edge-gentle into standard Hamming cube: {is_edge_gentle(edges, label)}")
    ok_h, def_h = verify_no_stretching_hamming(n, edges, label)
    print(f"  -> standard Hamming cube: no-stretching holds: {ok_h} "
          f"(defect {def_h}; NEGATIVE means a STRETCH, hypothesis violated)")
    ok_c, def_c = verify_no_stretching_cayley(n, edges, label, k, gens)
    print(f"  -> Cayley graph H (K4): no-stretching holds: {ok_c} "
          f"(defect {def_c})")
    print("  (lesson: the no-stretching target is the Cayley graph of the class")
    print("   images; in the Hamming cube the labeling must first be edge-gentle)")


if __name__ == "__main__":
    example_cube_dist_equals_hamming()
    example_edge_gentle_contraction()
    example_partition_path()
    example_partition_c4()
    example_partition_triangle()
    print("=" * 70)
    print("All demonstrations complete.")
