"""
demo.py -- Digit sums of periodic base-b expansions of 1/p.

Numerical demonstrations of two exact digit-sum laws for the base-b expansion
of 1/p, where p is prime and p does not divide b:

  * Full-Period Law (b a primitive root mod p, i.e. ord_p(b) = p-1):
        digit sum of one period = (b-1)(p-1)/2.

  * Half-Period Law (ord_p(b) = (p-1)/2 and p = 1 mod 4):
        digit sum of one period = (b-1)(p-1)/4.

Both are instances of the Master Formula:
        digit sum = (b-1) * s / p,
where s is the sum of the elements of the cyclic subgroup generated by b in
the nonzero residues modulo p.

All functions are self-contained and use exact integer arithmetic.
"""

from __future__ import annotations

from typing import List, Tuple


def is_prime(n: int) -> bool:
    """Deterministic trial-division primality test."""
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    d = 3
    while d * d <= n:
        if n % d == 0:
            return False
        d += 2
    return True


def multiplicative_order(p: int, b: int) -> int:
    """Least L >= 1 with b^L = 1 (mod p); requires gcd(b, p) = 1."""
    r = b % p
    k = 1
    while r != 1:
        r = (r * b) % p
        k += 1
    return k


def period_digits(p: int, b: int) -> List[int]:
    """One full period of base-b digits of 1/p via long division."""
    length = multiplicative_order(p, b)
    r = 1 % p
    digits: List[int] = []
    for _ in range(length):
        digits.append((b * r) // p)
        r = (b * r) % p
    return digits


def digit_sum(p: int, b: int) -> int:
    """Sum of the digits in one period of the base-b expansion of 1/p."""
    return sum(period_digits(p, b))


def subgroup_generated(p: int, b: int) -> List[int]:
    """The cyclic subgroup <b> of the nonzero residues modulo p."""
    orbit: List[int] = []
    r = 1 % p
    for _ in range(multiplicative_order(p, b)):
        orbit.append(r)
        r = (r * b) % p
    return orbit


def master_formula(p: int, b: int) -> int:
    """(b-1) * s / p, where s = sum of the subgroup generated by b."""
    s = sum(subgroup_generated(p, b))
    num = (b - 1) * s
    assert num % p == 0, "master formula must yield an integer"
    return num // p


def full_period_formula(p: int, b: int) -> int:
    """(b-1)(p-1)/2, the predicted digit sum for a primitive-root base."""
    return (b - 1) * (p - 1) // 2


def half_period_formula(p: int, b: int) -> int:
    """(b-1)(p-1)/4, the predicted digit sum for a half-period base, p = 1 mod 4."""
    return (b - 1) * (p - 1) // 4


def classify(p: int, b: int) -> str:
    """Return 'full', 'half', or 'other' for the order of b modulo p."""
    order = multiplicative_order(p, b)
    if order == p - 1:
        return "full"
    if order == (p - 1) // 2:
        return "half"
    return "other"


def demo_full_period() -> None:
    print("=" * 68)
    print("FULL-PERIOD LAW:  ord_p(b) = p-1  =>  digit sum = (b-1)(p-1)/2")
    print("=" * 68)
    b = 10
    for p in [7, 17, 19, 23, 29, 47, 59, 61, 97, 109]:
        if not is_prime(p) or b % p == 0 or classify(p, b) != "full":
            continue
        ds = digit_sum(p, b)
        pred = full_period_formula(p, b)
        status = "OK" if ds == pred else "MISMATCH"
        print(f"  p={p:>4}  b={b}  period len={multiplicative_order(p,b):>3}"
              f"  digit sum={ds:>5}  formula={pred:>5}  [{status}]")


def demo_half_period() -> None:
    print("=" * 68)
    print("HALF-PERIOD LAW:  ord_p(b)=(p-1)/2, p=1 mod 4  =>  (b-1)(p-1)/4")
    print("=" * 68)
    b = 10
    for p in range(5, 400):
        if not is_prime(p) or b % p == 0 or p % 4 != 1 or classify(p, b) != "half":
            continue
        ds = digit_sum(p, b)
        pred = half_period_formula(p, b)
        status = "OK" if ds == pred else "MISMATCH"
        print(f"  p={p:>4}  b={b}  period len={multiplicative_order(p,b):>3}"
              f"  digit sum={ds:>5}  formula={pred:>5}  [{status}]")


def demo_master_formula() -> None:
    print("=" * 68)
    print("MASTER FORMULA:  digit sum = (b-1) * (subgroup sum) / p  (any order)")
    print("=" * 68)
    for (p, b) in [(37, 10), (41, 10), (73, 10), (101, 10), (7, 3), (13, 5), (11, 2)]:
        if not is_prime(p) or b % p == 0:
            continue
        ds = digit_sum(p, b)
        pred = master_formula(p, b)
        status = "OK" if ds == pred else "MISMATCH"
        print(f"  p={p:>4}  b={b:>2}  order={multiplicative_order(p,b):>3}"
              f"  regime={classify(p,b):>5}  digit sum={ds:>5}"
              f"  master={pred:>5}  [{status}]")


def demo_midy_complement() -> None:
    print("=" * 68)
    print("MIDY COMPLEMENT:  full period halves sum digitwise to (b-1)")
    print("=" * 68)
    b = 10
    for p in [7, 17, 19, 23]:
        if classify(p, b) != "full":
            continue
        digs = period_digits(p, b)
        half = len(digs) // 2
        first, second = digs[:half], digs[half:]
        col_sums = [x + y for x, y in zip(first, second)]
        ok = all(c == b - 1 for c in col_sums)
        print(f"  p={p:>3}  first={''.join(map(str,first))}"
              f"  second={''.join(map(str,second))}"
              f"  column sums all {b-1}? {ok}")


def demo_average_digit() -> None:
    print("=" * 68)
    print("CENTRAL MEAN:  average digit = (b-1)/2 in both symmetric regimes")
    print("=" * 68)
    b = 10
    for p in [7, 13, 17, 19, 89]:
        digs = period_digits(p, b)
        avg = sum(digs) / len(digs)
        print(f"  p={p:>3}  regime={classify(p,b):>5}  length={len(digs):>3}"
              f"  average digit={avg:.4f}  target={(b-1)/2}")


def main() -> None:
    demo_full_period()
    print()
    demo_half_period()
    print()
    demo_master_formula()
    print()
    demo_midy_complement()
    print()
    demo_average_digit()


if __name__ == "__main__":
    main()
