"""
Rigidity of the Donoho-Stark uncertainty principle on finite abelian groups
===========================================================================

Numerical demonstrations, in pure Python (standard library only).

Setting
-------
A finite abelian group is presented as a tuple of moduli, e.g. ``(12,)`` for
Z/12 and ``(3, 3)`` for Z/3 x Z/3.  Its elements are tuples of residues.  The
dual group is identified with the group itself via the pairing

    chi_k(x) = exp(2*pi*i * sum_j k_j x_j / n_j),

and the (unnormalised) Fourier transform is

    fhat(k) = sum_x conj(chi_k(x)) f(x).

With N = |G|, the Donoho-Stark uncertainty principle states

    |supp f| * |supp fhat| >= N          for every f != 0,

and the rigidity theorem proved in the accompanying paper says that equality
holds exactly for the modulated coset indicators

    f = c * chi * 1_{a+H},   H <= G a subgroup, a in G, chi a character, c != 0.

The demonstrations below verify, numerically:

  1. modulated coset indicators are extremal, with the predicted spectrum
     chi + H^perp and the predicted flat modulus ||f||_1 / |supp f|;
  2. extremality is self-dual (the transform of an extremal is extremal);
  3. an indicator function is extremal iff its set is a coset (exhaustive
     search over all nonempty subsets of a small group);
  4. the arithmetic gap: if |supp f| divides N and f is not extremal, then
     the uncertainty product exceeds N by at least |supp f|;
  5. the prime-order dichotomy: extremals in prime order are scaled Dirac
     deltas or scaled characters;
  6. the bi-flat counterexample: on the self-dual group K x K^ the evaluation
     pairing (the discrete chirp) has |f| == 1 everywhere and |fhat| == sqrt(N)
     everywhere, yet its uncertainty product is N^2, the maximum possible;
  7. recovery of the phase subgroup from the spectrum, and the fact that it
     equals the group of periods of the support.
"""

from __future__ import annotations

import cmath
import itertools
import math
from typing import Dict, Iterable, List, Sequence, Tuple

Elt = Tuple[int, ...]
Group = Tuple[int, ...]
Func = Dict[Elt, complex]

TOL: float = 1e-9


# --------------------------------------------------------------------------
# Basic group and Fourier machinery
# --------------------------------------------------------------------------
def elements(group: Group) -> List[Elt]:
    """All elements of the group Z/n_1 x ... x Z/n_k, in lexicographic order."""
    return [tuple(t) for t in itertools.product(*(range(n) for n in group))]


def order(group: Group) -> int:
    """The order N = |G| of the group."""
    return math.prod(group)


def add(group: Group, x: Elt, y: Elt) -> Elt:
    """Group addition, componentwise modulo the respective moduli."""
    return tuple((a + b) % n for a, b, n in zip(x, y, group))


def sub(group: Group, x: Elt, y: Elt) -> Elt:
    """Group subtraction, componentwise modulo the respective moduli."""
    return tuple((a - b) % n for a, b, n in zip(x, y, group))


def pairing(group: Group, k: Elt, x: Elt) -> complex:
    """The character value chi_k(x) = exp(2*pi*i * sum_j k_j x_j / n_j)."""
    theta = 2.0 * math.pi * sum(kj * xj / n for kj, xj, n in zip(k, x, group))
    return cmath.exp(1j * theta)


def dft(group: Group, f: Func) -> Func:
    """Unnormalised Fourier transform: fhat(k) = sum_x conj(chi_k(x)) f(x)."""
    els = elements(group)
    return {
        k: sum(pairing(group, k, x).conjugate() * f[x] for x in els) for k in els
    }


def support(group: Group, f: Func) -> List[Elt]:
    """The set of points where f is nonzero (numerically, above TOL)."""
    return [x for x in elements(group) if abs(f[x]) > TOL]


def uncertainty_product(group: Group, f: Func) -> int:
    """|supp f| * |supp fhat|."""
    return len(support(group, f)) * len(support(group, dft(group, f)))


def is_extremal(group: Group, f: Func) -> bool:
    """True iff |supp f| * |supp fhat| == |G| (with f != 0)."""
    return len(support(group, f)) > 0 and uncertainty_product(group, f) == order(group)


def l1_norm(group: Group, f: Func) -> float:
    """The l^1 norm sum_x |f(x)|."""
    return sum(abs(f[x]) for x in elements(group))


# --------------------------------------------------------------------------
# Subgroups, cosets, annihilators
# --------------------------------------------------------------------------
def subgroup_generated(group: Group, gens: Sequence[Elt]) -> List[Elt]:
    """The subgroup of G generated by the given elements (closure under +)."""
    zero: Elt = tuple(0 for _ in group)
    seen = {zero}
    frontier = [zero]
    while frontier:
        current = frontier.pop()
        for g in gens:
            nxt = add(group, current, g)
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return sorted(seen)


def all_subgroups(group: Group) -> List[Tuple[Elt, ...]]:
    """All subgroups of G, found by closing every subset of generators."""
    els = elements(group)
    found = set()
    # every subgroup of a finite abelian group of small rank is generated by
    # at most rank(G) elements; two generators suffice for the groups used here
    for r in range(0, 3):
        for gens in itertools.combinations(els, r):
            found.add(tuple(subgroup_generated(group, gens)))
    return sorted(found, key=lambda h: (len(h), h))


def annihilator(group: Group, H: Sequence[Elt]) -> List[Elt]:
    """H^perp = { k : chi_k(h) = 1 for all h in H }."""
    return [
        k
        for k in elements(group)
        if all(abs(pairing(group, k, h) - 1.0) < TOL for h in H)
    ]


def is_coset(group: Group, S: Sequence[Elt]) -> bool:
    """True iff the nonempty set S is a coset a + H of some subgroup H."""
    if not S:
        return False
    a = S[0]
    shifted = sorted(sub(group, s, a) for s in S)
    # a shifted copy is a subgroup iff it is closed under addition
    shifted_set = set(shifted)
    return all(add(group, u, v) in shifted_set for u in shifted for v in shifted)


def coset_modulation(
    group: Group, H: Sequence[Elt], a: Elt, chi: Elt, c: complex
) -> Func:
    """The modulated coset indicator f = c * chi_chi * 1_{a+H}."""
    Hset = set(H)
    return {
        x: (c * pairing(group, chi, x) if sub(group, x, a) in Hset else 0j)
        for x in elements(group)
    }


def indicator(group: Group, S: Iterable[Elt]) -> Func:
    """The 0/1 indicator function of a subset S of G."""
    Sset = set(S)
    return {x: (1.0 + 0j if x in Sset else 0j) for x in elements(group)}


def phase_subgroup(group: Group, f: Func) -> List[Elt]:
    """
    { z : chi_k(z) = chi_k0(z) for every k in supp fhat },
    where k0 is the first spectral frequency.  For an extremal f this is the
    period group of supp f.
    """
    spectrum = support(group, dft(group, f))
    k0 = spectrum[0]
    return [
        z
        for z in elements(group)
        if all(
            abs(pairing(group, k, z) - pairing(group, k0, z)) < TOL for k in spectrum
        )
    ]


def period_group(group: Group, S: Sequence[Elt]) -> List[Elt]:
    """{ z : S + z = S }, the group of periods of the set S."""
    Sset = set(S)
    return [z for z in elements(group) if {add(group, s, z) for s in Sset} == Sset]


# --------------------------------------------------------------------------
# Demonstrations
# --------------------------------------------------------------------------
def demo_coset_modulations_are_extremal() -> None:
    """1. Modulated coset indicators saturate the uncertainty principle."""
    print("=" * 76)
    print("1. Modulated coset indicators are extremal")
    print("=" * 76)
    group: Group = (12,)
    N = order(group)
    print(f"G = Z/12,  N = {N}\n")
    header = f"{'|H|':>4} {'a':>6} {'chi':>4} {'|supp f|':>9} {'|supp fhat|':>12} {'product':>8} {'|f| on supp':>12}"
    print(header)
    print("-" * len(header))
    for H in all_subgroups(group):
        a: Elt = (5,)
        chi: Elt = (3,)
        c = 2.0 * cmath.exp(0.7j)
        f = coset_modulation(group, H, a, chi, c)
        S = support(group, f)
        A = support(group, dft(group, f))
        modulus = {round(abs(f[x]), 9) for x in S}
        predicted = l1_norm(group, f) / len(S)
        assert len(S) * len(A) == N
        assert len(modulus) == 1 and abs(modulus.pop() - predicted) < 1e-8
        assert sorted(A) == sorted(
            add(group, chi, k) for k in annihilator(group, H)
        ), "spectrum must be chi + H^perp"
        print(
            f"{len(H):>4} {str(a):>6} {str(chi):>4} {len(S):>9} {len(A):>12} "
            f"{len(S) * len(A):>8} {predicted:>12.6f}"
        )
    print("\nEvery product equals N = 12; the spectrum is exactly chi + H^perp;")
    print("and |f| is constant on the support with value ||f||_1 / |supp f|.\n")


def demo_self_duality() -> None:
    """2. The Fourier transform of an extremal is extremal."""
    print("=" * 76)
    print("2. Extremality is self-dual")
    print("=" * 76)
    group: Group = (3, 3)
    N = order(group)
    H = subgroup_generated(group, [(1, 0)])
    f = coset_modulation(group, H, (0, 2), (1, 1), 1.5 - 0.5j)
    fhat = dft(group, f)
    p1 = uncertainty_product(group, f)
    p2 = uncertainty_product(group, fhat)
    print(f"G = Z/3 x Z/3,  N = {N},  H = <(1,0)> of order {len(H)}")
    print(f"  uncertainty product of f     : {p1}")
    print(f"  uncertainty product of fhat  : {p2}")
    assert p1 == N and p2 == N
    print("Both equal N: the extremal family is closed under the transform.\n")


def demo_indicator_extremal_iff_coset() -> None:
    """3. Exhaustive check: 1_S is extremal iff S is a coset."""
    print("=" * 76)
    print("3. An indicator function is extremal exactly when its set is a coset")
    print("=" * 76)
    group: Group = (6,)
    els = elements(group)
    N = order(group)
    extremal_sets: List[Tuple[Elt, ...]] = []
    mismatches = 0
    for r in range(1, N + 1):
        for S in itertools.combinations(els, r):
            ext = is_extremal(group, indicator(group, S))
            cos = is_coset(group, S)
            if ext != cos:
                mismatches += 1
            if ext:
                extremal_sets.append(S)
    print(f"G = Z/6: searched all {2 ** N - 1} nonempty subsets.")
    print(f"  extremal subsets : {len(extremal_sets)}")
    print(f"  mismatches with 'is a coset' : {mismatches}")
    for S in extremal_sets:
        print(f"    {sorted(x[0] for x in S)}")
    assert mismatches == 0
    print("The extremal sets are precisely the 12 cosets of the 4 subgroups.\n")


def demo_gap_theorem() -> None:
    """4. The arithmetic gap above the extremal locus."""
    print("=" * 76)
    print("4. Gap theorem: no near-extremal regime when |supp f| divides N")
    print("=" * 76)
    group: Group = (8,)
    els = elements(group)
    N = order(group)
    worst = None
    checked = 0
    for r in (1, 2, 4, 8):  # the divisors of 8
        for S in itertools.combinations(els, r):
            f = indicator(group, S)
            prod = uncertainty_product(group, f)
            if prod == N:
                continue
            checked += 1
            assert prod >= N + r, (S, prod)
            excess = prod - N
            if worst is None or excess < worst[1]:
                worst = (S, excess, r)
    print(f"G = Z/8, N = {N}.  Checked {checked} non-extremal 0/1 signals whose")
    print("support size divides N.  In every case the uncertainty product exceeded")
    print("N by at least |supp f|.")
    if worst is not None:
        S, excess, r = worst
        print(
            f"  smallest excess observed: {excess} (support size {r}, "
            f"set {sorted(x[0] for x in S)})"
        )
    print()


def demo_prime_dichotomy() -> None:
    """5. In prime order the only extremals are deltas and characters."""
    print("=" * 76)
    print("5. Prime-order dichotomy")
    print("=" * 76)
    group: Group = (7,)
    els = elements(group)
    N = order(group)
    sizes = set()
    for r in range(1, N + 1):
        for S in itertools.combinations(els, r):
            if is_extremal(group, indicator(group, S)):
                sizes.add(len(S))
    print(f"G = Z/7, N = {N} prime.")
    print(f"  support sizes of extremal 0/1 signals: {sorted(sizes)}")
    assert sizes == {1, 7}
    # a scaled character is extremal with full support and a single frequency
    chi: Elt = (3,)
    f = {x: 2.5 * pairing(group, chi, x) for x in els}
    A = support(group, dft(group, f))
    print(f"  scaled character chi_3: |supp f| = {len(support(group, f))}, "
          f"|supp fhat| = {len(A)} (frequency {A[0][0]})")
    assert is_extremal(group, f)
    print("Only the two degenerate cases survive: scaled Dirac deltas (support 1)")
    print("and scaled characters (support 7).  Nothing lies in between.\n")


def demo_biflat_counterexample() -> None:
    """6. The chirp: flat in space, flat in frequency, maximally non-extremal."""
    print("=" * 76)
    print("6. Bi-flatness does NOT imply extremality: the discrete chirp")
    print("=" * 76)
    for n in (2, 3, 4, 5):
        group: Group = (n, n)  # G = K x K^ with K = Z/n
        N = order(group)
        f: Func = {
            (x, y): cmath.exp(2j * math.pi * x * y / n) for (x, y) in elements(group)
        }
        fhat = dft(group, f)
        mods_f = {round(abs(v), 8) for v in f.values()}
        mods_fhat = {round(abs(v), 8) for v in fhat.values()}
        prod = uncertainty_product(group, f)
        assert mods_f == {1.0}
        assert mods_fhat == {round(float(n), 8)}
        assert prod == N * N
        print(
            f"  K = Z/{n}:  N = |G| = {N:>3};  |f| == {mods_f.pop():.1f} on all of G;  "
            f"|fhat| == {mods_fhat.pop():.1f} = sqrt(N) on all of G^;"
        )
        print(
            f"            uncertainty product = {prod} = N^2, while the bound is N = {N}"
        )
    print("\nBoth flatness conditions hold in the strongest possible form, yet the")
    print("function is as far from extremal as any function can be.  Rigidity is a")
    print("statement about phase coupling across the spectrum, not about moduli.\n")


def demo_phase_subgroup_recovery() -> None:
    """7. The phase subgroup recovered from the spectrum is the period group."""
    print("=" * 76)
    print("7. The phase subgroup is intrinsic: it is the period group of the support")
    print("=" * 76)
    group: Group = (2, 6)
    N = order(group)
    print(f"G = Z/2 x Z/6, N = {N}\n")
    header = f"{'subgroup H':>28} {'|H|':>4} {'recovered':>10} {'periods':>8} {'match':>6}"
    print(header)
    print("-" * len(header))
    for H in all_subgroups(group):
        a: Elt = (1, 1)
        f = coset_modulation(group, H, a, (1, 2), 3.0j)
        recovered = sorted(phase_subgroup(group, f))
        periods = sorted(period_group(group, support(group, f)))
        agree = recovered == periods == sorted(H)
        label = "{" + ",".join(f"{h}" for h in sorted(H)[:3]) + ("...}" if len(H) > 3 else "}")
        print(
            f"{label:>28} {len(H):>4} {len(recovered):>10} {len(periods):>8} "
            f"{'yes' if agree else 'NO':>6}"
        )
        assert agree
    print("\nIn every case the subgroup extracted from the spectrum coincides with")
    print("the group of periods of the support and with the subgroup used to build f.\n")


def main() -> None:
    print()
    print("#" * 76)
    print("#  Rigidity of the Donoho-Stark uncertainty principle: numerical demos  #")
    print("#" * 76)
    print()
    demo_coset_modulations_are_extremal()
    demo_self_duality()
    demo_indicator_extremal_iff_coset()
    demo_gap_theorem()
    demo_prime_dichotomy()
    demo_biflat_counterexample()
    demo_phase_subgroup_recovery()
    print("All assertions passed.")


if __name__ == "__main__":
    main()
