#!/usr/bin/env python3
"""
Straight lines in the hyperbolic picture of the Pythagorean tree
================================================================

Numerical demonstration of the results on the hyperbolic geometry of Euclid
seeds (m, n) with 0 < n < m, gcd(m, n) = 1, m + n odd, each seed being drawn
as the upper half-plane point

    z(m, n) = (n + i) / m,

with the base point i = z(1, 0) as the centre of the picture.

Everything below is elementary and self-contained: only `math`, `fractions`
and `itertools` from the standard library are used.

Run:  python3 demo.py
"""

from __future__ import annotations

import math
from fractions import Fraction
from math import gcd, isqrt
from typing import Dict, Iterator, List, Tuple

Seed = Tuple[int, int]

# --------------------------------------------------------------------------
# 0.  Seeds and the half-plane embedding
# --------------------------------------------------------------------------


def is_seed(m: int, n: int) -> bool:
    """Is (m, n) a Euclid seed: 0 < n < m, coprime, of opposite parity?"""
    return 0 < n < m and gcd(m, n) == 1 and (m + n) % 2 == 1


def triple(m: int, n: int) -> Tuple[int, int, int]:
    """The primitive Pythagorean triple (a, b, c) generated by the seed."""
    return (m * m - n * n, 2 * m * n, m * m + n * n)


def cosh_dist(m: float, n: float, mp: float, npp: float) -> float:
    """Master identity: cosh d(z(m,n), z(m',n')).

    cosh d = 1 + ((n m' - n' m)^2 + (m - m')^2) / (2 m m').
    """
    return 1.0 + ((n * mp - npp * m) ** 2 + (m - mp) ** 2) / (2.0 * m * mp)


def hyp_dist(m: float, n: float, mp: float, npp: float) -> float:
    """Hyperbolic distance between two seed nodes."""
    return math.acosh(cosh_dist(m, n, mp, npp))


def dist_base(m: float, n: float) -> float:
    """Distance from the centre i = z(1,0): cosh d = (m^2 + n^2 + 1)/(2m)."""
    return math.acosh((m * m + n * n + 1.0) / (2.0 * m))


def dist_direct(m: float, n: float, mp: float, npp: float) -> float:
    """Distance computed straight from the half-plane metric, as a control."""
    x1, y1 = n / m, 1.0 / m
    x2, y2 = npp / mp, 1.0 / mp
    num = (x1 - x2) ** 2 + (y1 - y2) ** 2
    return math.acosh(1.0 + num / (2.0 * y1 * y2))


# --------------------------------------------------------------------------
# 1.  The master identity and the ring theorem
# --------------------------------------------------------------------------


def demo_master_identity() -> None:
    print("=" * 72)
    print("1.  MASTER IDENTITY  cosh d = 1 + ((n m' - n' m)^2 + (m - m')^2)/(2 m m')")
    print("=" * 72)
    pairs = [((2, 1), (3, 2)), ((5, 2), (29, 12)), ((4, 3), (41, 32)), ((7, 4), (12, 5))]
    worst = 0.0
    for (m, n), (mp, npp) in pairs:
        a = hyp_dist(m, n, mp, npp)
        b = dist_direct(m, n, mp, npp)
        worst = max(worst, abs(a - b))
        print(f"  ({m:>3},{n:>3}) -> ({mp:>3},{npp:>3}):  formula {a:.12f}   metric {b:.12f}")
    print(f"  maximal discrepancy over the sample: {worst:.2e}\n")


def demo_ring_theorem() -> None:
    print("=" * 72)
    print("2.  RING THEOREM   (1/2) log c  <  d(i, z(m,n))  <  (1/2) log 2c")
    print("=" * 72)
    print("     residual rho = d - (1/2) log c must lie in (0, (1/2) log 2 = 0.3465736)")
    lo, hi = 1.0, 0.0
    count = 0
    for m in range(2, 400):
        for n in range(1, m):
            if not is_seed(m, n):
                continue
            c = m * m + n * n
            rho = dist_base(m, n) - 0.5 * math.log(c)
            lo, hi = min(lo, rho), max(hi, rho)
            count += 1
    print(f"  seeds tested: {count}")
    print(f"  min residual  = {lo:.9f}   (> 0)")
    print(f"  max residual  = {hi:.9f}   (< {0.5 * math.log(2):.9f})\n")


# --------------------------------------------------------------------------
# 2.  The collinearity calculus
# --------------------------------------------------------------------------


def gram(c1: float, c2: float, c3: float) -> float:
    """Gram / Cayley-Menger invariant of three cosh-distances."""
    return 2 * c1 * c2 * c3 - c1 * c1 - c2 * c2 - c3 * c3 + 1.0


def seed_det(m1: int, n1: int, m2: int, n2: int, m3: int, n3: int) -> int:
    """Integer determinant of the rows (n_i^2 + 1, n_i m_i, m_i^2)."""
    return (
        (n1 * n1 + 1) * (n2 * m2 * m3 * m3 - m2 * m2 * n3 * m3)
        - (n1 * m1) * ((n2 * n2 + 1) * m3 * m3 - m2 * m2 * (n3 * n3 + 1))
        + m1 * m1 * ((n2 * n2 + 1) * n3 * m3 - n2 * m2 * (n3 * n3 + 1))
    )


def gram_of_nodes(p: Seed, q: Seed, r: Seed) -> float:
    c1 = cosh_dist(p[0], p[1], q[0], q[1])
    c2 = cosh_dist(q[0], q[1], r[0], r[1])
    c3 = cosh_dist(p[0], p[1], r[0], r[1])
    return gram(c1, c2, c3)


def demo_arithmetic_bridge() -> None:
    print("=" * 72)
    print("3.  ARITHMETIC BRIDGE   Phi = (Delta / (2 m1 m2 m3))^2")
    print("=" * 72)
    triples = [
        ((1, 0), (2, 1), (5, 3)),      # golden line: exactly collinear
        ((1, 0), (5, 2), (29, 12)),    # silver line: exactly collinear
        ((1, 0), (3, 2), (25, 18)),    # rational line rho = 2/3
        ((1, 0), (2, 1), (12, 5)),     # middle spine of the tree: NOT collinear
        ((2, 1), (3, 2), (4, 3)),      # generic triangle
    ]
    for p, q, r in triples:
        phi = gram_of_nodes(p, q, r)
        det = seed_det(p[0], p[1], q[0], q[1], r[0], r[1])
        pred = (det / (2.0 * p[0] * q[0] * r[0])) ** 2
        d1 = hyp_dist(*p, *q)
        d2 = hyp_dist(*q, *r)
        d3 = hyp_dist(*p, *r)
        print(f"  {p} {q} {r}:  Delta = {det:>10}   Phi = {phi:.3e}   "
              f"(Delta/2m1m2m3)^2 = {pred:.3e}")
        print(f"        d1 + d2 - d3 = {d1 + d2 - d3:+.3e}")
    print()


def demo_middle_spine_defect() -> None:
    print("=" * 72)
    print("4.  THE FAKE LINE:  Gram defect of (i, (m,n), M(m,n)) is exactly 1")
    print("=" * 72)
    p: Seed = (2, 1)
    for _ in range(5):
        q = (2 * p[0] + p[1], p[0])          # Berggren middle move
        phi = gram_of_nodes((1, 0), p, q)
        det = seed_det(1, 0, p[0], p[1], q[0], q[1])
        print(f"  i, {p!s:>10}, {q!s:>10}:  Delta = {det:>10}, "
              f"Delta/(2 m1 m2 m3) = {det / (2 * p[0] * q[0]):+.6f},  Phi = {phi:.6f}")
        p = (2 * q[0] + q[1], q[0])          # two moves = one silver Pell step
    print("  the defect is the universal constant 1 -- the middle spine only looks straight\n")


# --------------------------------------------------------------------------
# 3.  The radial invariant, the pencil, and the metallic ratios
# --------------------------------------------------------------------------


def radial(m: int, n: int) -> Fraction:
    """Radial invariant rho(m,n) = (m^2 - n^2 - 1)/(m n)."""
    return Fraction(m * m - n * n - 1, m * n)


def metallic(k: float) -> float:
    """k-th metallic ratio lambda_k = (k + sqrt(k^2+4))/2."""
    return (k + math.sqrt(k * k + 4.0)) / 2.0


def pell_step(k: int, p: Seed) -> Seed:
    m, n = p
    return ((k * k + 1) * m + k * n, k * m + n)


def pell_orbit(k: int, length: int) -> List[Seed]:
    out: List[Seed] = [(1, 0)]
    for _ in range(length):
        out.append(pell_step(k, out[-1]))
    return out


def demo_pell_lines() -> None:
    print("=" * 72)
    print("5.  THE INTEGRAL LINES  m^2 - k m n - n^2 = 1  AND THEIR QUANTIZED SPACING")
    print("=" * 72)
    for k in range(1, 6):
        orb = pell_orbit(k, 4)
        step = 2.0 * math.log(metallic(k))
        ds = [dist_base(m, n) for m, n in orb[1:]]
        seeds = ["T" if is_seed(m, n) else "F" for m, n in orb[1:]]
        print(f"  k = {k}: orbit {orb[1:]}")
        print(f"        step = arcosh(1 + k^2/2) = {math.acosh(1 + k * k / 2):.6f}"
              f"  = 2 log lambda_k = {step:.6f}")
        print(f"        distances from i: " + ", ".join(f"{d:.4f}" for d in ds)
              + f"   (multiples of the step: "
              + ", ".join(f"{d / step:.3f}" for d in ds) + ")")
        print(f"        Euclid seed? {' '.join(seeds)}"
              + ("   (period-3 pattern, odd k)" if k % 2 else "   (all seeds, even k)"))
    print()


def demo_ideal_endpoints_and_growth() -> None:
    print("=" * 72)
    print("6.  IDEAL ENDPOINTS  n_j/m_j -> 1/lambda_k  AND HYPOTENUSE GROWTH")
    print("=" * 72)
    for k in (1, 2, 3):
        lam = metallic(k)
        orb = pell_orbit(k, 4)[1:]
        print(f"  k = {k}:  1/lambda_k = {1 / lam:.9f}")
        for j, (m, n) in enumerate(orb, start=1):
            c = m * m + n * n
            print(f"        j = {j}: (m,n) = ({m},{n})  n/m = {n / m:.9f}"
                  f"   c = {c:<10} lambda^(4j)/2 = {lam ** (4 * j) / 2:<14.3f}"
                  f" lambda^(4j) = {lam ** (4 * j):.3f}")
    print()


def demo_counting_law() -> None:
    print("=" * 72)
    print("7.  COUNTING LAW   N_k(R) = floor(R / (2 log lambda_k)) + 1")
    print("=" * 72)
    R = 10.0
    total = 0
    for k in range(1, 11):
        step = 2.0 * math.log(metallic(k))
        n_k = math.floor(R / step) + 1
        brute = sum(1 for (m, n) in pell_orbit(k, 40) if dist_base(m, n) <= R + 1e-12)
        total += n_k
        print(f"  k = {k:>2}:  step = {step:.6f}   N_k({R:g}) = {n_k}   (direct count {brute})")
    print(f"  total over k <= 10 : {total}   -- linear in R, while the number of")
    print(f"  seeds inside the same ball grows like e^(2R).\n")


def demo_metallic_gap() -> None:
    print("=" * 72)
    print("8.  THE METALLIC GAP:  step lengths increase, infimum 2 log phi")
    print("=" * 72)
    print("   k |  lambda_k  | 2 log lambda_k | lambda_k^4")
    for k in range(1, 7):
        lam = metallic(k)
        print(f"  {k:>2} | {lam:>10.6f} | {2 * math.log(lam):>14.6f} | {lam ** 4:>10.4f}")
    print(f"  golden bound 2 log phi = {2 * math.log(metallic(1)):.6f};"
          f"  lambda_k^4 > 6 for all k >= 1\n")


def demo_horocycle_rigidity() -> None:
    print("=" * 72)
    print("9.  HOROCYCLE RIGIDITY:  the horocycle im = 1/m carries finitely many seeds")
    print("=" * 72)
    row = []
    for m in range(2, 13):
        row.append((m, sum(1 for n in range(1, m) if is_seed(m, n))))
    print("  m       : " + " ".join(f"{m:>3}" for m, _ in row))
    print("  #seeds  : " + " ".join(f"{c:>3}" for _, c in row))
    print("  always at most m - 1, in contrast with the infinitely many seeds on"
          " every geodesic of the pencil\n")


# --------------------------------------------------------------------------
# 4.  Rational lines, alignment classes, the square-discriminant dichotomy
# --------------------------------------------------------------------------


def rat_step(a: int, b: int, s: int, u: int, p: Seed) -> Seed:
    m, n = p
    return (s * m + b * u * n, b * u * m + (s - a * u) * n)


def find_unit(a: int, b: int, bound: int = 4_000_000) -> Tuple[int, int] | None:
    """Smallest positive solution of s^2 - a s u - b^2 u^2 = 1 (brute force)."""
    for u in range(1, bound):
        disc = (a * u) ** 2 + 4 * (b * b * u * u + 1)
        r = isqrt(disc)
        if r * r != disc:
            continue
        if (a * u + r) % 2 == 0:
            s = (a * u + r) // 2
            if s > 0:
                return (s, u)
    return None


def demo_rational_lines() -> None:
    print("=" * 72)
    print("10. RATIONAL LINES  b m^2 - a m n - b n^2 = b  AND THEIR AUTOMORPHISMS")
    print("=" * 72)
    for (a, b), start in [((1, 1), (2, 1)), ((2, 3), (3, 2)), ((1, 2), (4, 3)),
                          ((2, 1), (5, 2)), ((1, 3), (6, 5))]:
        unit = find_unit(a, b)
        assert unit is not None
        s, u = unit
        step = math.acosh(s - a * u / 2)
        pts = [start]
        for _ in range(3):
            pts.append(rat_step(a, b, s, u, pts[-1]))
        seeds = [p for p in pts if is_seed(*p)]
        print(f"  rho = {a}/{b}:  disc a^2+4b^2 = {a * a + 4 * b * b}"
              f"   unit (s,u) = ({s},{u})   step = arcosh({s - Fraction(a * u, 2)})"
              f" = {step:.6f}")
        print(f"        orbit of {start}: {pts}")
        print(f"        radial invariants: "
              + ", ".join(str(radial(*p)) for p in pts))
        print(f"        genuine Euclid seeds among them: {seeds}")
    print()


def demo_alignment_classes() -> None:
    print("=" * 72)
    print("11. ALIGNMENT CLASSES:  same radial invariant  <=>  exactly collinear with i")
    print("=" * 72)
    classes: Dict[Fraction, List[Seed]] = {}
    for m in range(2, 1200):
        for n in range(1, m):
            if is_seed(m, n):
                classes.setdefault(radial(m, n), []).append((m, n))
    top = sorted(classes.items(), key=lambda kv: (-len(kv[1]), kv[0]))[:6]
    for rho, members in top:
        a, b = rho.numerator, rho.denominator
        print(f"  rho = {str(rho):>5}  disc = {a * a + 4 * b * b:>6}"
              f"  members with m < 1200: {members}")
        if len(members) >= 3:
            p, q, r = members[0], members[1], members[2]
            d1, d2, d3 = hyp_dist(*p, *q), hyp_dist(*q, *r), hyp_dist(*p, *r)
            print(f"        collinearity check on {p},{q},{r}: "
                  f"d1 + d2 - d3 = {d1 + d2 - d3:+.2e},  Delta = "
                  f"{seed_det(*p, *q, *r)}")
    print()


def demo_square_discriminant() -> None:
    print("=" * 72)
    print("12. SQUARE-DISCRIMINANT DICHOTOMY")
    print("=" * 72)
    print("   Claim: for 0 < n < m the number (m^2 - n^2 - 1)^2 + (2 m n)^2 is never a square.")
    hits = 0
    tested = 0
    for m in range(2, 700):
        for n in range(1, m):
            tested += 1
            v = (m * m - n * n - 1) ** 2 + (2 * m * n) ** 2
            r = isqrt(v)
            if r * r == v:
                hits += 1
                print(f"        counterexample at ({m},{n})!")
    print(f"   pairs tested: {tested};  square discriminants found: {hits}")
    print("   Empty square-discriminant lines (the conic factors into two linear forms):")
    for a, b, e, f in [(0, 1, 1, 1), (3, 2, 1, 2), (8, 3, 1, 3), (5, 6, 2, 3), (16, 15, 3, 5)]:
        sols = [(m, n) for m in range(1, 400) for n in range(1, 400)
                if b * m * m - a * m * n - b * n * n == b]
        print(f"        rho = {a}/{b}: disc = {a * a + 4 * b * b} = {isqrt(a * a + 4 * b * b)}^2,"
              f"  ({e} m - {f} n)({f} m + {e} n) = {e * f},"
              f"  positive solutions with m,n < 400: {len(sols)}")
    print()


# --------------------------------------------------------------------------
# 5.  Hypercycles: the other family of visually straight curves
# --------------------------------------------------------------------------


def dist_to_vline(m: float, n: float, a: float) -> float:
    """Distance from z(m,n) to the vertical geodesic Re = a: arsinh(|x-a|/y)."""
    return math.asinh(abs(n / m - a) * m)


def demo_hypercycles() -> None:
    print("=" * 72)
    print("13. HYPERCYCLES:  A n + B m + C = 0  =>  constant distance arsinh|C/A|")
    print("=" * 72)
    print("   right spine (n fixed): distance to Re = 0 is arsinh(n)")
    for n in (1, 2, 3):
        row = [(m, dist_to_vline(m, n, 0.0)) for m in range(n + 1, n + 20, 2)]
        vals = {round(d, 12) for _, d in row}
        print(f"        n = {n}: arsinh(n) = {math.asinh(n):.9f}, "
              f"distinct measured values: {len(vals)} -> {next(iter(vals)):.9f}")
    print("   left spine (m, m-1): distance to Re = 1 is arsinh(1) = "
          f"{math.asinh(1):.9f}")
    for m in range(2, 8):
        print(f"        (m,n) = ({m},{m - 1}): {dist_to_vline(m, m - 1, 1.0):.9f}")
    print()


def main() -> None:
    demo_master_identity()
    demo_ring_theorem()
    demo_arithmetic_bridge()
    demo_middle_spine_defect()
    demo_pell_lines()
    demo_ideal_endpoints_and_growth()
    demo_counting_law()
    demo_metallic_gap()
    demo_horocycle_rigidity()
    demo_rational_lines()
    demo_alignment_classes()
    demo_square_discriminant()
    demo_hypercycles()


if __name__ == "__main__":
    main()
