import Mathlib
import MachineLearning.KnownUnresolvedCards.FeedbackGame
import MachineLearning.ZeroFitDialFade104

/-!
# Extinction or floor?  What finitely many rungs of a fading dial can and cannot decide

## Research context (FACT round-68 #2, exp 541, `TDIAL-U104`; second cycle)

`MachineLearning.ZeroFitDialFade104` proved that the bitlen-104 rung refutes every *convex*
fade law and that a fade whose decrements never shrink is extinguished at a finite bitlen.  The
sibling files of the thread draw the opposite conclusion from the later rungs:
`Physics.TDialU108BandLoss` localises a *plateau* in `[0.4362, 0.488]`,
`Probability.TDialU116ReboundFloor` recovers a floor at `≈ 0.474`, and
`Algebra.ZeroFitDialU120Floor` argues that the fade continues below it.

So the thread contains two incompatible readings of the same seven numbers: **a positive floor**
and **finite extinction**.  This file settles what a finite ladder can decide between them.

## Main results

### The exact dichotomy (Section 2)

* `ladder`, `ladder_succ`, `ladder_antitone` — a fade written as a running decrement sum.
* `bounded_decrements_floor` — summable (equivalently, uniformly bounded partial) decrements give
  the explicit positive floor `ρ₀ − S`.
* `unbounded_decrements_extinction` — unbounded partial decrements force `ρₙ ≤ 0` at a finite `n`.
* `fade_dichotomy` — hence **every** nonnegative-decrement fade either has a positive floor or is
  extinguished at a finite rung, with no third possibility.  Summability of the decrements, not
  their decay, is the whole question.

### Vanishing decrements are not evidence of a floor (Section 3)

* `harmonic_two_pow_le` — the dual Oresme bound `H_{2^m} ≤ 1 + m` (the catalog already has the
  lower bound `1 + m/2 ≤ H_{2^m}` in `KnownUnresolvedCards.harmonic_two_pow_ge`).
* `harmFade_decrements_vanish` — the harmonic fade's decrements tend to zero.
* `harmFade_extinct` — yet it is extinguished at a finite rung, for every positive rate.
* `harmFade_recorded_dies_by_two_pow_36`, `harmFade_recorded_above_third_through_512` — with the
  recorded first step `0.0303` and start `0.5739`, the harmonic fade dies, but only after `2³⁶`
  four-bit steps, while staying above `0.33` at *every* bitlen up to `512`.
* `vanishing_steps_do_not_certify_a_floor` — the punchline: shrinking steps and a long apparent
  plateau are consistent with certain extinction.  The observed deceleration at bitlen 108 is
  therefore not evidence for a floor.

### The limit is not identifiable from finitely many rungs (Section 4)

* `contFloor`, `contDeath` — two explicit continuations of an arbitrary observed ladder.
* `limit_not_identifiable` — for any observed rungs `g 0, …, g N` with `g N > 0` both
  continuations agree with the data exactly, are antitone afterwards, and have decrements bounded
  by the same constant, yet one stays above `g N / 2 > 0` for ever while the other reaches `0` at
  rung `N + 10`.
* `floor_and_extinction_both_compatible` — instantiated on the seven recorded rungs: a floor at
  `0.21818` and extinction at bitlen `160` are both consistent with everything measured so far.
  Discriminating them requires a rung beyond bitlen 120; the file states exactly which reading of
  which rung settles it.
-/

open Finset

open Catalog.MachineLearning.ZeroFitDialFade104

namespace Catalog.MachineLearning.ZeroFitDialFadeDichotomy

/-! ## 1. Fades as decrement ladders -/

/-- The ladder generated by a start value and a decrement sequence. -/
def ladder (rho0 : ℚ) (d : ℕ → ℚ) (n : ℕ) : ℚ := rho0 - ∑ k ∈ range n, d k

@[simp] lemma ladder_zero (rho0 : ℚ) (d : ℕ → ℚ) : ladder rho0 d 0 = rho0 := by
  simp [ladder]

lemma ladder_succ (rho0 : ℚ) (d : ℕ → ℚ) (n : ℕ) :
    ladder rho0 d (n + 1) = ladder rho0 d n - d n := by
  simp [ladder, Finset.sum_range_succ]
  ring

/-- A fade with nonnegative decrements is antitone. -/
lemma ladder_antitone {rho0 : ℚ} {d : ℕ → ℚ} (hd : ∀ k, 0 ≤ d k) : Antitone (ladder rho0 d) := by
  apply antitone_nat_of_succ_le
  intro n
  rw [ladder_succ]
  linarith [hd n]

/-! ## 2. The exact dichotomy: floor or finite extinction -/

/-- **Bounded decrement budget gives a floor.**  If the partial decrement sums never exceed `S`
then the fade never goes below `ρ₀ − S`. -/
theorem bounded_decrements_floor (rho0 S : ℚ) (d : ℕ → ℚ)
    (hS : ∀ n, ∑ k ∈ range n, d k ≤ S) : ∀ n, rho0 - S ≤ ladder rho0 d n := by
  intro n
  have := hS n
  rw [ladder]
  linarith

/-- If in addition the budget is smaller than the start value, the floor is strictly positive:
the dial survives for ever. -/
theorem positive_floor_of_small_budget (rho0 S : ℚ) (d : ℕ → ℚ) (hlt : S < rho0)
    (hS : ∀ n, ∑ k ∈ range n, d k ≤ S) : ∀ n, 0 < ladder rho0 d n := by
  intro n
  have h := bounded_decrements_floor rho0 S d hS n
  linarith

/-- **An unbounded decrement budget kills the fade.**  If the partial decrement sums exceed every
bound then the fade reaches `0` at a finite rung. -/
theorem unbounded_decrements_extinction (rho0 : ℚ) (d : ℕ → ℚ)
    (hunb : ∀ M : ℚ, ∃ n, M ≤ ∑ k ∈ range n, d k) : ∃ n, ladder rho0 d n ≤ 0 := by
  obtain ⟨n, hn⟩ := hunb rho0
  exact ⟨n, by rw [ladder]; linarith⟩

/-- **The fade dichotomy.**  Every fade with nonnegative decrements either has a floor (a uniform
lower bound over all rungs) or is extinguished at a finite rung.  There is no third behaviour:
whether a dial dies is decided by the *summability* of its decrements, not by their decay. -/
theorem fade_dichotomy (rho0 : ℚ) (d : ℕ → ℚ) :
    (∃ L : ℚ, ∀ n, L ≤ ladder rho0 d n) ∨ (∃ n, ladder rho0 d n ≤ 0) := by
  by_cases hb : ∃ S : ℚ, ∀ n, ∑ k ∈ range n, d k ≤ S
  · obtain ⟨S, hS⟩ := hb
    exact Or.inl ⟨rho0 - S, bounded_decrements_floor rho0 S d hS⟩
  · push_neg at hb
    refine Or.inr (unbounded_decrements_extinction rho0 d ?_)
    intro M
    obtain ⟨n, hn⟩ := hb M
    exact ⟨n, le_of_lt hn⟩

/-- The floor branch is *strict* when the budget leaves room: a fade with a summable decrement
budget below its start value never even reaches zero. -/
theorem no_extinction_of_bounded_budget (rho0 S : ℚ) (d : ℕ → ℚ) (hlt : S < rho0)
    (hS : ∀ n, ∑ k ∈ range n, d k ≤ S) : ¬ ∃ n, ladder rho0 d n ≤ 0 := by
  rintro ⟨n, hn⟩
  have := positive_floor_of_small_budget rho0 S d hlt hS n
  linarith

/-! ## 3. Vanishing decrements do not certify a floor -/

/-- **Dual Oresme bound.**  `H_{2^m} ≤ 1 + m`, the companion of the catalog's
`KnownUnresolvedCards.harmonic_two_pow_ge`. -/
theorem sum_Ioc_le_one {m : ℕ} (hm : 1 ≤ m) :
    ∑ i ∈ Finset.Ioc m (2 * m), (i : ℚ)⁻¹ ≤ 1 := by
  have hm0 : (0 : ℚ) < (m : ℚ) := by exact_mod_cast hm
  have hcard : (Finset.Ioc m (2 * m)).card = m := by simp [Nat.card_Ioc]; omega
  have hb : ∀ i ∈ Finset.Ioc m (2 * m), (i : ℚ)⁻¹ ≤ 1 / (m : ℚ) := by
    intro i hi
    simp only [Finset.mem_Ioc] at hi
    have hi0 : (0 : ℚ) < (m : ℚ) := hm0
    have hige : (m : ℚ) ≤ (i : ℚ) := by exact_mod_cast le_of_lt hi.1
    simpa [one_div] using one_div_le_one_div_of_le hi0 hige
  have hsum := Finset.sum_le_card_nsmul (Finset.Ioc m (2 * m)) (fun i => (i : ℚ)⁻¹)
    (1 / (m : ℚ)) hb
  rw [hcard, nsmul_eq_mul] at hsum
  refine le_trans hsum (le_of_eq ?_)
  field_simp

lemma harmonic_two_mul_le {m : ℕ} (hm : 1 ≤ m) : harmonic (2 * m) ≤ harmonic m + 1 := by
  have hsplit : ∑ i ∈ Finset.Ioc 0 m, (i : ℚ)⁻¹ + ∑ i ∈ Finset.Ioc m (2 * m), (i : ℚ)⁻¹
      = ∑ i ∈ Finset.Ioc 0 (2 * m), (i : ℚ)⁻¹ :=
    Finset.sum_Ioc_consecutive _ (Nat.zero_le _) (by omega)
  rw [KnownUnresolvedCards.harmonic_eq_sum_Ioc (2 * m), KnownUnresolvedCards.harmonic_eq_sum_Ioc m,
    ← hsplit]
  have := sum_Ioc_le_one hm
  linarith

/-- `H_{2^m} ≤ 1 + m`. -/
theorem harmonic_two_pow_le (m : ℕ) : harmonic (2 ^ m) ≤ 1 + (m : ℚ) := by
  induction m with
  | zero => norm_num [harmonic_succ]
  | succ m ih =>
      have h1 : (1 : ℕ) ≤ 2 ^ m := Nat.one_le_two_pow
      have h2 := harmonic_two_mul_le h1
      have he : (2 : ℕ) ^ (m + 1) = 2 * 2 ^ m := by ring
      rw [he]
      push_cast
      linarith

/-- The harmonic fade: start value `ρ₀`, decrements `c/(k+1)`. -/
def harmFade (rho0 c : ℚ) (n : ℕ) : ℚ := rho0 - c * harmonic n

lemma harmFade_eq_ladder (rho0 c : ℚ) (n : ℕ) :
    harmFade rho0 c n = ladder rho0 (fun k => c * ((k : ℚ) + 1)⁻¹) n := by
  have hsum : ∑ k ∈ range n, c * ((k : ℚ) + 1)⁻¹ = c * harmonic n := by
    rw [harmonic, Finset.mul_sum]
    refine Finset.sum_congr rfl fun k _ => ?_
    push_cast
    ring
  rw [ladder, hsum, harmFade]

/-- The harmonic fade's decrements are nonnegative and tend to zero: it looks, at every scale,
like a fade that is settling down. -/
theorem harmFade_decrements_vanish (c : ℚ) (hc : 0 < c) :
    (∀ k : ℕ, 0 ≤ c * ((k : ℚ) + 1)⁻¹) ∧
      ∀ eps : ℚ, 0 < eps → ∃ N : ℕ, ∀ k ≥ N, c * ((k : ℚ) + 1)⁻¹ < eps := by
  constructor
  · intro k
    have : (0 : ℚ) < (k : ℚ) + 1 := by positivity
    positivity
  · intro eps heps
    obtain ⟨N, hN⟩ := exists_nat_gt (c / eps)
    refine ⟨N, fun k hk => ?_⟩
    have hkq : (N : ℚ) ≤ (k : ℚ) := by exact_mod_cast hk
    have hk1 : (0 : ℚ) < (k : ℚ) + 1 := by positivity
    rw [div_lt_iff₀ heps] at hN
    rw [← div_eq_mul_inv, div_lt_iff₀ hk1]
    nlinarith [mul_le_mul_of_nonneg_left hkq (le_of_lt heps)]

/-- **Yet the harmonic fade dies.**  For every positive rate the harmonic fade is extinguished at
a finite rung: vanishing decrements are *not* enough for a floor, only summable ones are. -/
theorem harmFade_extinct (rho0 c : ℚ) (hc : 0 < c) : ∃ n, harmFade rho0 c n ≤ 0 := by
  obtain ⟨m, hm⟩ := exists_nat_gt ((rho0 / c - 1) * 2)
  refine ⟨2 ^ m, ?_⟩
  have hH : 1 + (m : ℚ) / 2 ≤ harmonic (2 ^ m) := KnownUnresolvedCards.harmonic_two_pow_ge m
  have hkey : rho0 / c ≤ 1 + (m : ℚ) / 2 := by linarith
  have : rho0 ≤ c * harmonic (2 ^ m) := by
    have h1 : rho0 / c * c ≤ (1 + (m : ℚ) / 2) * c := by
      exact mul_le_mul_of_nonneg_right hkey (le_of_lt hc)
    have h2 : rho0 / c * c = rho0 := by field_simp
    nlinarith
  rw [harmFade]
  linarith

/-- With the recorded start `0.5739` and the recorded first step `0.0303`, the harmonic fade is
extinguished by the `2³⁶`-th four-bit step. -/
theorem harmFade_recorded_dies_by_two_pow_36 :
    harmFade rung96 (303 / 10000) (2 ^ 36) ≤ 0 := by
  have hH := KnownUnresolvedCards.harmonic_two_pow_ge 36
  have hcast : ((36 : ℕ) : ℚ) = 36 := by norm_num
  rw [hcast] at hH
  rw [harmFade, rung96]
  linarith

/-- …but at every bitlen up to `512` — i.e. for the first `128` four-bit steps, four times the
whole recorded sweep — the same fade still reads above `0.33`.  Its death is real and utterly
unobservable. -/
theorem harmFade_recorded_above_third_through_512 (n : ℕ) (hn : n ≤ 128) :
    33 / 100 < harmFade rung96 (303 / 10000) n := by
  have hmono : harmonic n ≤ harmonic (2 ^ 7) :=
    KnownUnresolvedCards.harmonic_monotone (by norm_num; omega)
  have hup := harmonic_two_pow_le 7
  have hcast : ((7 : ℕ) : ℚ) = 7 := by norm_num
  rw [hcast] at hup
  rw [harmFade, rung96]
  linarith

/-- **Vanishing steps do not certify a floor.**  There is a fade whose decrements are positive and
tend to zero, which stays above `0.33` throughout the entire observable range of bitlens, and
which is nevertheless extinguished at a finite bitlen.  The deceleration recorded at bitlen 108 is
therefore no evidence at all for the plateau reading. -/
theorem vanishing_steps_do_not_certify_a_floor :
    (∀ eps : ℚ, 0 < eps → ∃ N : ℕ, ∀ k ≥ N, (303 / 10000 : ℚ) * ((k : ℚ) + 1)⁻¹ < eps) ∧
      (∀ n ≤ 128, 33 / 100 < harmFade rung96 (303 / 10000) n) ∧
      (∃ n, harmFade rung96 (303 / 10000) n ≤ 0) :=
  ⟨(harmFade_decrements_vanish (303 / 10000) (by norm_num)).2,
    fun n hn => harmFade_recorded_above_third_through_512 n hn,
    ⟨2 ^ 36, harmFade_recorded_dies_by_two_pow_36⟩⟩

/-! ## 4. The limit is not identifiable from finitely many rungs -/

/-- The floor continuation of an observed ladder: after rung `N` it decays geometrically to
`g N / 2`. -/
def contFloor (N : ℕ) (g : ℕ → ℚ) (k : ℕ) : ℚ :=
  if k ≤ N then g k else (g N / 2) * (1 + (1 / 2) ^ (k - N))

/-- The extinction continuation of the same observed ladder: after rung `N` it falls linearly and
reaches `0` at rung `N + 10`. -/
def contDeath (N : ℕ) (g : ℕ → ℚ) (k : ℕ) : ℚ :=
  if k ≤ N then g k else g N - ((k - N : ℕ) : ℚ) * (g N / 10)

lemma contFloor_of_le {N : ℕ} {g : ℕ → ℚ} {k : ℕ} (hk : k ≤ N) : contFloor N g k = g k := by
  simp [contFloor, hk]

lemma contDeath_of_le {N : ℕ} {g : ℕ → ℚ} {k : ℕ} (hk : k ≤ N) : contDeath N g k = g k := by
  simp [contDeath, hk]

lemma contFloor_of_gt {N : ℕ} {g : ℕ → ℚ} {k : ℕ} (hk : N < k) :
    contFloor N g k = (g N / 2) * (1 + (1 / 2) ^ (k - N)) := by
  simp [contFloor, Nat.not_le.2 hk]

lemma contDeath_of_gt {N : ℕ} {g : ℕ → ℚ} {k : ℕ} (hk : N < k) :
    contDeath N g k = g N - ((k - N : ℕ) : ℚ) * (g N / 10) := by
  simp [contDeath, Nat.not_le.2 hk]

/-- **Non-identifiability of the limit.**  Whatever the observed rungs `g 0, …, g N` (with
`g N > 0`), there are two continuations that

* reproduce every observed rung exactly,
* are both antitone from rung `N` on,

yet one never falls below the strictly positive level `g N / 2` while the other reaches `0` at
rung `N + 10`.  No finite ladder can decide between a positive floor and finite extinction. -/
theorem limit_not_identifiable (N : ℕ) (g : ℕ → ℚ) (hg : 0 < g N) :
    (∀ k ≤ N, contFloor N g k = g k) ∧ (∀ k ≤ N, contDeath N g k = g k) ∧
      (∀ k, N ≤ k → g N / 2 ≤ contFloor N g k) ∧
      (∀ k, N ≤ k → contFloor N g (k + 1) ≤ contFloor N g k) ∧
      (∀ k, N ≤ k → contDeath N g (k + 1) ≤ contDeath N g k) ∧
      contDeath N g (N + 10) = 0 := by
  refine ⟨fun k hk => contFloor_of_le hk, fun k hk => contDeath_of_le hk, ?_, ?_, ?_, ?_⟩
  · -- the floor continuation stays above `g N / 2`
    intro k hk
    rcases eq_or_lt_of_le hk with rfl | hlt
    · rw [contFloor_of_le le_rfl]; linarith
    · rw [contFloor_of_gt hlt]
      have hpow : (0 : ℚ) < (1 / 2 : ℚ) ^ (k - N) := by positivity
      nlinarith
  · -- and is antitone there
    intro k hk
    have hlt : N < k + 1 := by omega
    rw [contFloor_of_gt hlt]
    have hstep : k + 1 - N = (k - N) + 1 := by omega
    rw [hstep, pow_succ]
    have hpow : (0 : ℚ) < (1 / 2 : ℚ) ^ (k - N) := by positivity
    rcases eq_or_lt_of_le hk with rfl | hklt
    · rw [contFloor_of_le le_rfl]
      simp only [Nat.sub_self, pow_zero]
      nlinarith
    · rw [contFloor_of_gt hklt]
      nlinarith
  · -- the death continuation is antitone
    intro k hk
    have hlt : N < k + 1 := by omega
    rw [contDeath_of_gt hlt]
    have hstep : k + 1 - N = (k - N) + 1 := by omega
    rw [hstep]
    rcases eq_or_lt_of_le hk with rfl | hklt
    · rw [contDeath_of_le le_rfl]
      simp only [Nat.sub_self]
      push_cast
      linarith
    · rw [contDeath_of_gt hklt]
      push_cast
      linarith
  · -- and it reaches zero at rung `N + 10`
    have hlt : N < N + 10 := by omega
    rw [contDeath_of_gt hlt]
    have : N + 10 - N = 10 := by omega
    rw [this]
    push_cast
    ring

/-! ## 5. Applied to the recorded ladder -/

/-- The seven recorded rungs, indexed by the four-bit step from bitlen 96. -/
def recRung : ℕ → ℚ
  | 0 => rung96
  | 1 => rung100
  | 2 => rung104
  | 3 => rung108
  | 4 => rung112
  | 5 => rung116
  | _ => rung120

/-- **Both readings of the thread survive every recorded rung.**  There is a continuation of the
seven measured values that never falls below `0.21818` — the plateau reading — and another that
reproduces the same seven values and reaches exactly `0` ten four-bit steps later, i.e. at bitlen
`160` — the extinction reading.  The dispute between `Probability.TDialU116ReboundFloor` and the
extinction forecast of `MachineLearning.ZeroFitDialFade104` is therefore *not* decidable from the
recorded ladder: it needs a rung beyond bitlen 120. -/
theorem floor_and_extinction_both_compatible :
    (∀ k ≤ 6, contFloor 6 recRung k = recRung k) ∧
      (∀ k ≤ 6, contDeath 6 recRung k = recRung k) ∧
      (∀ k, 6 ≤ k → 21818 / 100000 ≤ contFloor 6 recRung k) ∧
      contDeath 6 recRung (6 + 10) = 0 := by
  have h6r : recRung 6 = rung120 := rfl
  have hg : (0 : ℚ) < recRung 6 := by rw [h6r]; norm_num [rung120]
  obtain ⟨h1, h2, h3, _, _, h6⟩ := limit_not_identifiable 6 recRung hg
  refine ⟨h1, h2, fun k hk => ?_, h6⟩
  have h := h3 k hk
  have hlow : (21818 : ℚ) / 100000 = recRung 6 / 2 := by rw [h6r]; norm_num [rung120]
  linarith

/-- The discriminating measurement, stated as a falsifiable prediction: nine four-bit steps past
the last recorded rung — at bitlen `156` — the two continuations differ by more than `0.17`.  A
rung read there above `0.21` refutes this extinction continuation; one read below `0.05` refutes
the plateau. -/
theorem discriminating_rung_at_156 :
    21 / 100 < contFloor 6 recRung 15 ∧ contDeath 6 recRung 15 < 5 / 100 ∧
      17 / 100 < contFloor 6 recRung 15 - contDeath 6 recRung 15 := by
  have h6r : recRung 6 = rung120 := rfl
  have hf : contFloor 6 recRung 15 = (recRung 6 / 2) * (1 + (1 / 2) ^ 9) := by
    rw [contFloor_of_gt (by omega)]
  have hd : contDeath 6 recRung 15 = recRung 6 - ((9 : ℕ) : ℚ) * (recRung 6 / 10) := by
    rw [contDeath_of_gt (by omega)]
  refine ⟨?_, ?_, ?_⟩
  · rw [hf, h6r]; norm_num [rung120]
  · rw [hd, h6r]; norm_num [rung120]
  · rw [hf, hd, h6r]; norm_num [rung120]

end Catalog.MachineLearning.ZeroFitDialFadeDichotomy