/-
Copyright (c) 2025 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Finitely generated modules over a power-series ring are Λ-torsion

Let `R` be an integral domain and let `M` be a module over the power-series ring
`R⟦X⟧` (the completed group algebra / Iwasawa algebra `Λ ≅ ℤₚ[[T]]` is the
prototypical example, with `R = ℤₚ`).  Write `φ : M → M` for the `R`-linear
endomorphism induced by multiplication by `T = X`.

The classical structure theory of Iwasawa modules rests on the following
observation: if `M` is **finitely generated over the coefficient ring `R`**, then
`φ` is an `R`-linear endomorphism of a finite `R`-module, so by Cayley–Hamilton
(`LinearMap.exists_monic_and_aeval_eq_zero`) it satisfies a non-zero (indeed
monic) polynomial `q ∈ R[T]`.  Interpreting `q(φ) = 0` back inside `R⟦X⟧` shows
that the *non-zero* element `q(T) ∈ R⟦X⟧` annihilates every element of `M`; that
is, `M` is `Λ`-torsion.

## A remark on the hypothesis

The informal statement ("`M` finitely generated **over `R⟦X⟧`**") is, taken
literally, false: `M = R⟦X⟧` is generated by `1` as a module over itself, yet
multiplication by `T` on the domain `R⟦X⟧` is annihilated only by the zero
polynomial.  The genuine theorem — and the one that feeds Cayley–Hamilton — is
the statement with `M` finitely generated **over the coefficient ring `R`**
(`Module.Finite R M`), which is exactly the hypothesis used below.  This matches
the standard fact in Iwasawa theory that a finitely generated `Λ`-module that is
in addition finitely generated over `ℤₚ` is `Λ`-torsion.

## Main results

* `IwasawaTorsion.phiT` — the `R`-linear endomorphism "multiply by `X`".
* `IwasawaTorsion.aeval_phiT_apply` — evaluating a polynomial `q` at `φ` is the
  same as multiplying by the power series `q(T) = (q : R⟦X⟧)`.
* `IwasawaTorsion.exists_monic_aeval_phiT_eq_zero` — the monic annihilating
  polynomial coming from Cayley–Hamilton.
* `IwasawaTorsion.exists_ne_zero_aeval_phiT_eq_zero` — a non-zero polynomial `q`
  with `q(φ) = 0`.
* `IwasawaTorsion.isTorsion_of_finite` — `M` is annihilated by a non-zero element
  of `R⟦X⟧`, i.e. `M` is `Λ`-torsion.
-/
import Mathlib

open Polynomial PowerSeries

namespace IwasawaTorsion

variable {R : Type*} [CommRing R] [IsDomain R]
variable {M : Type*} [AddCommGroup M] [Module R M] [Module (PowerSeries R) M]
  [IsScalarTower R (PowerSeries R) M]

/-- The `R`-linear endomorphism of `M` induced by multiplication by `T = X` in
the power-series ring `R⟦X⟧`.  This is `φ` in the discussion above. -/
noncomputable def phiT : Module.End R M := Algebra.lsmul R R M (PowerSeries.X : PowerSeries R)

omit [IsDomain R] in
@[simp] lemma phiT_apply (x : M) : (phiT : Module.End R M) x = (PowerSeries.X : PowerSeries R) • x :=
  rfl

omit [IsDomain R] in
/-- Evaluating a polynomial at `φ` factors as the coercion `R[X] → R⟦X⟧` followed
by the scalar action of `R⟦X⟧` on `M`.  Both sides are `R`-algebra homomorphisms
`R[X] →ₐ[R] Module.End R M`, so it suffices to check they agree on `X`. -/
lemma aeval_phiT_eq :
    (Polynomial.aeval (phiT : Module.End R M)) =
      (Algebra.lsmul R R M).comp (Polynomial.coeToPowerSeries.algHom R) := by
  apply Polynomial.algHom_ext
  simp [phiT]

omit [IsDomain R] in
/-- The endomorphism `q(φ)` acts on `x : M` as multiplication by the power series
`q(T) = (q : R⟦X⟧)`. -/
lemma aeval_phiT_apply (q : Polynomial R) (x : M) :
    (Polynomial.aeval (phiT : Module.End R M)) q x = (q : PowerSeries R) • x := by
  rw [aeval_phiT_eq]
  rfl

/-- **Cayley–Hamilton for `φ`.**  If `M` is finitely generated over the
coefficient ring `R`, then `φ = phiT` satisfies a *monic* polynomial over `R`. -/
omit [IsDomain R] in
lemma exists_monic_aeval_phiT_eq_zero [Module.Finite R M] :
    ∃ q : Polynomial R, q.Monic ∧ Polynomial.aeval (phiT : Module.End R M) q = 0 :=
  LinearMap.exists_monic_and_aeval_eq_zero R (phiT : Module.End R M)

/-- A non-zero polynomial `q ∈ R[T]` with `q(φ) = 0` on `M`, obtained from the
monic Cayley–Hamilton polynomial (a monic polynomial over a non-trivial ring is
non-zero). -/
theorem exists_ne_zero_aeval_phiT_eq_zero [Module.Finite R M] :
    ∃ q : Polynomial R, q ≠ 0 ∧ Polynomial.aeval (phiT : Module.End R M) q = 0 := by
  obtain ⟨q, hmonic, hq⟩ := exists_monic_aeval_phiT_eq_zero (R := R) (M := M)
  exact ⟨q, hmonic.ne_zero, hq⟩

/-- **Main theorem.**  A module `M` over the power-series ring `R⟦X⟧` that is
finitely generated over the integral domain `R` is `Λ`-torsion: it is annihilated
by a non-zero element of `R⟦X⟧`, namely the image `q(T)` of a non-zero polynomial
`q` with `q(φ) = 0`. -/
theorem isTorsion_of_finite [Module.Finite R M] :
    ∃ s : PowerSeries R, s ≠ 0 ∧ ∀ x : M, s • x = 0 := by
  obtain ⟨q, hq0, hq⟩ := exists_ne_zero_aeval_phiT_eq_zero (R := R) (M := M)
  refine ⟨(q : PowerSeries R), ?_, ?_⟩
  · -- `q ↦ (q : R⟦X⟧)` is injective, so the coerced power series is non-zero.
    intro h
    exact hq0 (Polynomial.coe_injective R (by simpa using h))
  · -- `q(T) • x = q(φ) x = 0`.
    intro x
    have h2 := aeval_phiT_apply q x
    rw [hq, LinearMap.zero_apply] at h2
    exact h2.symm

end IwasawaTorsion