/-
Copyright (c) 2026 Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Integrated Information: a rigorous core for Φ (phi)

This file develops a self-contained, fully formal mathematical core for
*Integrated Information Theory* (IIT). In IIT the central quantity is `Φ`
("phi"), the amount of information generated by a system *above and beyond*
the information generated independently by its parts. The mathematical heart
of `Φ` is the **mutual information across a cut** of the system, and the
*integrated information* of the system is the value of this quantity at the
**Minimum Information Partition** (MIP) — the cut that is "least integrated".

We model a system state as a finite probability distribution `FinDist α`
and define:

* `FinDist.mutualInfo P` — the mutual information of a joint distribution on
  `α × β`, i.e. the KL divergence between `P` and the product of its marginals.
* `FinDist.Indep P` — independence of the two halves (the system *factorizes*
  across this cut).
* `FinDist.phiCut P p` — the integrated information across the cut induced by a
  predicate `p` on the element index set (the bipartition of elements).
* `FinDist.Phi P cuts` — the minimum information partition value over a finite
  nonempty family of candidate cuts.

Main results:

* `mutualInfo_nonneg` : `0 ≤ I(P)` (Gibbs' inequality).
* `mutualInfo_eq_zero_iff` : `I(P) = 0 ↔ P` factorizes (independence).
* `mutualInfo_swap` : mutual information is symmetric between a part and its
  complement.
* `Phi_nonneg` : `Φ ≥ 0`.
* `Phi_eq_zero_iff` : `Φ = 0 ↔` some cut in the family is independent — i.e. a
  system is *integrated* (`Φ > 0`) exactly when it cannot be decomposed into
  independent parts along any of the candidate cuts.

-- !-- Lab Notes -- !--
-- Hypothesis: the entire IIT notion of "integration" reduces to the classical
-- fact that mutual information (KL to product of marginals) is nonnegative and
-- vanishes iff independent. Φ at the MIP is then a min of such quantities, so
-- `Φ ≥ 0` and `Φ = 0 ↔ ∃ decomposing cut` follow structurally.
-- Strategy: isolate the analysis in two *pure-real* per-term lemmas
-- (`klterm_ge`, `klterm_eq_iff`) built from `Real.log_le_sub_one_of_pos` and its
-- strict cousin, then do only Finset bookkeeping at the distribution level.
-/

open Finset BigOperators

namespace IIT

/-! ## Pure-real per-term KL lemmas

The summand of the KL divergence is `p * log (p / (m₁ m₂))`. We bound it below
by the "tangent line" `p - m₁ m₂` and characterise equality. Here `p` is a joint
mass and `m₁, m₂` are the corresponding marginal masses, so `0 ≤ p ≤ m₁` and
`0 ≤ p ≤ m₂`. -/

/--
Tangent-line lower bound for one KL summand.
-/
theorem klterm_ge {p m1 m2 : ℝ} (hp : 0 ≤ p) (h1 : p ≤ m1) (h2 : p ≤ m2) :
    p - m1 * m2 ≤ p * Real.log (p / (m1 * m2)) := by
  rcases eq_or_lt_of_le hp with ( rfl | hp );
  · nlinarith;
  · have := Real.log_le_sub_one_of_pos ( show 0 < ( m1 * m2 ) / p by exact div_pos ( mul_pos ( lt_of_lt_of_le hp h1 ) ( lt_of_lt_of_le hp h2 ) ) hp );
    rw [ show p / ( m1 * m2 ) = ( m1 * m2 / p ) ⁻¹ by rw [ inv_div ], Real.log_inv ] ; nlinarith [ mul_div_cancel₀ ( m1 * m2 ) hp.ne' ]

/--
Equality in the tangent-line bound holds exactly at the product point.
-/
theorem klterm_eq_iff {p m1 m2 : ℝ} (hp : 0 ≤ p) (h1 : p ≤ m1) (h2 : p ≤ m2) :
    p * Real.log (p / (m1 * m2)) = p - m1 * m2 ↔ p = m1 * m2 := by
  by_cases h3 : p = 0;
  · by_cases hm1 : m1 = 0 <;> by_cases hm2 : m2 = 0 <;> simp_all +decide;
  · constructor;
    · intro h_eq
      have h_log_eq : Real.log (p / (m1 * m2)) = 1 - (m1 * m2) / p := by
        grind;
      have h_contra : Real.log (m1 * m2 / p) = m1 * m2 / p - 1 := by
        rw [ Real.log_div ] at * <;> first |linarith|aesop;
      have := Real.log_lt_sub_one_of_pos ( show 0 < m1 * m2 / p by exact div_pos ( mul_pos ( lt_of_lt_of_le ( lt_of_le_of_ne hp ( Ne.symm h3 ) ) h1 ) ( lt_of_lt_of_le ( lt_of_le_of_ne hp ( Ne.symm h3 ) ) h2 ) ) ( lt_of_le_of_ne hp ( Ne.symm h3 ) ) );
      grind;
    · aesop

/-! ## Finite distributions and marginals -/

/-- A finite probability distribution on a finite type `α`. -/
structure FinDist (α : Type*) [Fintype α] where
  /-- The probability mass function. -/
  prob : α → ℝ
  /-- Probabilities are nonnegative. -/
  nonneg : ∀ a, 0 ≤ prob a
  /-- Probabilities sum to one. -/
  sum_one : ∑ a, prob a = 1

namespace FinDist

variable {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]

/-- Pushforward of a distribution along an equivalence (relabeling of states). -/
def map (e : α ≃ β) (P : FinDist α) : FinDist β where
  prob b := P.prob (e.symm b)
  nonneg b := P.nonneg _
  sum_one := by
    rw [Equiv.sum_comp e.symm P.prob]; exact P.sum_one

/-- First marginal of a joint distribution on `α × β`. -/
def fst (P : FinDist (α × β)) : FinDist α where
  prob a := ∑ b, P.prob (a, b)
  nonneg a := Finset.sum_nonneg fun b _ => P.nonneg _
  sum_one := by
    rw [← Fintype.sum_prod_type]; exact P.sum_one

/-- Second marginal of a joint distribution on `α × β`. -/
def snd (P : FinDist (α × β)) : FinDist β where
  prob b := ∑ a, P.prob (a, b)
  nonneg b := Finset.sum_nonneg fun a _ => P.nonneg _
  sum_one := by
    rw [Finset.sum_comm, ← Fintype.sum_prod_type]; exact P.sum_one

/-- The mutual information of a joint distribution `P` on `α × β`: the KL
divergence from `P` to the product of its marginals. This is the basic
"integrated information across a cut" of IIT. -/
noncomputable def mutualInfo (P : FinDist (α × β)) : ℝ :=
  ∑ a, ∑ b, P.prob (a, b) *
    Real.log (P.prob (a, b) / ((P.fst).prob a * (P.snd).prob b))

/-- The two halves of `P` are independent (the system factorizes across the cut). -/
def Indep (P : FinDist (α × β)) : Prop :=
  ∀ a b, P.prob (a, b) = (P.fst).prob a * (P.snd).prob b

/-- A marginal probability dominates each joint entry: `P(a,b) ≤ P.fst a`. -/
theorem prob_le_fst (P : FinDist (α × β)) (a : α) (b : β) :
    P.prob (a, b) ≤ (P.fst).prob a :=
  Finset.single_le_sum (f := fun b => P.prob (a, b)) (fun _ _ => P.nonneg _)
    (Finset.mem_univ b)

/-- A marginal probability dominates each joint entry: `P(a,b) ≤ P.snd b`. -/
theorem prob_le_snd (P : FinDist (α × β)) (a : α) (b : β) :
    P.prob (a, b) ≤ (P.snd).prob b :=
  Finset.single_le_sum (f := fun a => P.prob (a, b)) (fun _ _ => P.nonneg _)
    (Finset.mem_univ a)

/-- The product of the two marginals sums to one. -/
theorem sum_marg_prod (P : FinDist (α × β)) :
    ∑ a, ∑ b, (P.fst).prob a * (P.snd).prob b = 1 := by
  simp_rw [← Finset.mul_sum]
  rw [← Finset.sum_mul, (P.fst).sum_one, (P.snd).sum_one, one_mul]

/-- Gibbs' inequality: mutual information is nonnegative. -/
theorem mutualInfo_nonneg (P : FinDist (α × β)) : 0 ≤ mutualInfo P := by
  have key : ∀ a, ∀ b,
      (P.prob (a, b) - (P.fst).prob a * (P.snd).prob b) ≤
      P.prob (a, b) *
        Real.log (P.prob (a, b) / ((P.fst).prob a * (P.snd).prob b)) := by
    intro a b
    exact klterm_ge (P.nonneg _) (P.prob_le_fst a b) (P.prob_le_snd a b)
  have h1 : ∑ a, ∑ b,
      (P.prob (a, b) - (P.fst).prob a * (P.snd).prob b) ≤ mutualInfo P := by
    apply Finset.sum_le_sum; intro a _
    apply Finset.sum_le_sum; intro b _
    exact key a b
  have h2 : ∑ a, ∑ b,
      (P.prob (a, b) - (P.fst).prob a * (P.snd).prob b) = 0 := by
    simp_rw [Finset.sum_sub_distrib]
    have e1 : ∑ a, ∑ b, P.prob (a, b) = 1 := by
      rw [← Fintype.sum_prod_type]; exact P.sum_one
    rw [e1, P.sum_marg_prod, sub_self]
  linarith [h1, h2]

/--
The mutual information vanishes iff the system factorizes (independence).
-/
theorem mutualInfo_eq_zero_iff (P : FinDist (α × β)) :
    mutualInfo P = 0 ↔ Indep P := by
  constructor;
  · intro h_mutualInfo_zero
    have h_sum_zero : ∑ a, ∑ b, (P.prob (a, b) * Real.log (P.prob (a, b) / ((P.fst).prob a * (P.snd).prob b)) - (P.prob (a, b) - (P.fst).prob a * (P.snd).prob b)) = 0 := by
      convert sub_eq_zero.mpr h_mutualInfo_zero using 1;
      simp +decide [ FinDist.mutualInfo, FinDist.sum_marg_prod ];
      rw [ ← Fintype.sum_prod_type, P.sum_one, sub_self ];
    rw [ Finset.sum_eq_zero_iff_of_nonneg ] at h_sum_zero;
    · intro a b; specialize h_sum_zero a; rw [ Finset.sum_eq_zero_iff_of_nonneg ] at h_sum_zero <;> simp_all +decide [ Finset.sum_sub_distrib ] ;
      · grind +suggestions;
      · intro i; have := klterm_ge ( P.nonneg ( a, i ) ) ( P.prob_le_fst a i ) ( P.prob_le_snd a i ) ; linarith;
    · exact fun a _ => Finset.sum_nonneg fun b _ => sub_nonneg_of_le <| klterm_ge ( P.nonneg _ ) ( P.prob_le_fst _ _ ) ( P.prob_le_snd _ _ );
  · simp_all +decide [ FinDist.mutualInfo, FinDist.Indep ]

/-- Mutual information is symmetric between a part and its complement. -/
theorem mutualInfo_swap (P : FinDist (α × β)) :
    mutualInfo (P.map (Equiv.prodComm α β)) = mutualInfo P := by
  unfold FinDist.mutualInfo
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl (fun a _ => Finset.sum_congr rfl (fun b _ => ?_))
  simp only [FinDist.map, FinDist.fst, FinDist.snd, Equiv.prodComm_symm,
    Equiv.prodComm_apply, Prod.swap_prod_mk]
  rw [mul_comm (∑ x, P.prob (x, b)) (∑ x, P.prob (a, x)), mul_comm]

/-! ## Witnesses: zero and positive integration

We show the theory is non-vacuous on both sides: a product (already factorized)
system has zero mutual information, while a perfectly correlated pair of bits is
genuinely integrated (positive mutual information).

-- !-- Lab Notes -- !--
-- Hypothesis: positivity of `Φ` should be *witnessable* by a concrete maximally
-- correlated system, and zero by a product. Experiment: the correlated-bits
-- distribution `P(0,0)=P(1,1)=1/2` is not independent (joint 1/2 vs marginal
-- product 1/4), so `mutualInfo > 0` follows from nonnegativity + the zero-iff
-- characterization without computing the actual value `log 2`. This confirms
-- the qualitative content of IIT ("integration is real") is fully captured.
-/

/-- The product (independent) joint distribution of `p` and `q`. -/
def prod (p : FinDist α) (q : FinDist β) : FinDist (α × β) where
  prob x := p.prob x.1 * q.prob x.2
  nonneg x := mul_nonneg (p.nonneg _) (q.nonneg _)
  sum_one := by
    rw [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, q.sum_one, mul_one, p.sum_one]

/-- The first marginal of a product is the first factor. -/
theorem prod_fst_prob (p : FinDist α) (q : FinDist β) (a : α) :
    ((prod p q).fst).prob a = p.prob a := by
  show (∑ b, p.prob a * q.prob b) = p.prob a
  rw [← Finset.mul_sum Finset.univ q.prob (p.prob a), q.sum_one, mul_one]

/-- The second marginal of a product is the second factor. -/
theorem prod_snd_prob (p : FinDist α) (q : FinDist β) (b : β) :
    ((prod p q).snd).prob b = q.prob b := by
  show (∑ a, p.prob a * q.prob b) = q.prob b
  rw [← Finset.sum_mul Finset.univ p.prob (q.prob b), p.sum_one, one_mul]

/-- A product distribution is independent. -/
theorem indep_prod (p : FinDist α) (q : FinDist β) : Indep (prod p q) := by
  intro a b
  rw [prod_fst_prob, prod_snd_prob]; rfl

/-- A product (already factorized) system carries zero mutual information. -/
theorem mutualInfo_prod (p : FinDist α) (q : FinDist β) :
    mutualInfo (prod p q) = 0 :=
  (mutualInfo_eq_zero_iff _).2 (indep_prod p q)

/-- The maximally correlated pair of bits: `P(0,0) = P(1,1) = 1/2`. -/
noncomputable def correlatedBits : FinDist (Bool × Bool) where
  prob x := if x.1 = x.2 then (1 : ℝ) / 2 else 0
  nonneg x := by split <;> norm_num
  sum_one := by
    simp only [Fintype.sum_prod_type, Fintype.sum_bool]
    norm_num

/--
The correlated bits are *not* independent: the system is integrated.
-/
theorem correlatedBits_not_indep : ¬ Indep correlatedBits := by
  intro h; have := h Bool.true Bool.true; simp +decide [ FinDist.fst, FinDist.snd ] at this;
  unfold correlatedBits at this; norm_num at this;

/--
A perfectly correlated pair of bits has strictly positive mutual
information: a concrete witness that integrated information can be positive.
-/
theorem mutualInfo_correlatedBits_pos : 0 < mutualInfo correlatedBits := by
  convert lt_of_le_of_ne ( mutualInfo_nonneg _ ) _ using 1;
  rw [ Ne, eq_comm, IIT.FinDist.mutualInfo_eq_zero_iff ];
  convert IIT.FinDist.correlatedBits_not_indep

/-! ## The Minimum Information Partition (MIP) and `Φ`

A *system* is a joint distribution over the product `∀ i, σ i` of per-element state
spaces indexed by a finite set `ι`. A **cut** is a subset `S ⊆ ι` of elements;
it splits the system state into the `S`-part and the complementary part via
`Equiv.piEquivPiSubtypeProd`. The integrated information across the cut is the
mutual information of the resulting bipartite distribution, and `Φ` is the
minimum of these values over a chosen nonempty family of candidate cuts — the
value at the Minimum Information Partition.

-- !-- Lab Notes -- !--
-- Design choice: encode a bipartition as a `Finset ι` (one side `S`) rather than
-- as a `Prop`-predicate; this gives `DecidablePred (· ∈ S)` for free and lets the
-- candidate family be a `Finset (Finset ι)`, so `Φ` is a clean `Finset.inf'`.
-- Insight: every structural property of `Φ` (nonnegativity; vanishing iff some
-- cut decomposes the system) is inherited from the bipartite `mutualInfo`
-- results through the order-theoretic behaviour of `inf'` on nonnegative data.
-/

variable {ι : Type*} [Fintype ι] [DecidableEq ι] {σ : ι → Type*}
  [∀ i, Fintype (σ i)]

/-- The integrated information across the cut given by the subset `S ⊆ ι`:
the mutual information of the system state viewed as a bipartite distribution
over the `S`-part and its complement. -/
noncomputable def phiCut (P : FinDist (∀ i, σ i)) (S : Finset ι) : ℝ :=
  mutualInfo (P.map (Equiv.piEquivPiSubtypeProd (· ∈ S) σ))

/-- The system factorizes across the cut `S` (the two sides are independent). -/
def CutIndep (P : FinDist (∀ i, σ i)) (S : Finset ι) : Prop :=
  Indep (P.map (Equiv.piEquivPiSubtypeProd (· ∈ S) σ))

/-- Integrated information across any cut is nonnegative. -/
theorem phiCut_nonneg (P : FinDist (∀ i, σ i)) (S : Finset ι) :
    0 ≤ phiCut P S :=
  mutualInfo_nonneg _

/-- A cut carries zero integrated information iff the system decomposes across it. -/
theorem phiCut_eq_zero_iff (P : FinDist (∀ i, σ i)) (S : Finset ι) :
    phiCut P S = 0 ↔ CutIndep P S :=
  mutualInfo_eq_zero_iff _

/-- `Φ`: the integrated information of the system, i.e. the value of `phiCut` at
the Minimum Information Partition over a nonempty family of candidate cuts. -/
noncomputable def Phi (P : FinDist (∀ i, σ i)) (cuts : Finset (Finset ι))
    (hne : cuts.Nonempty) : ℝ :=
  cuts.inf' hne (fun S => phiCut P S)

/--
`Φ ≥ 0`.
-/
theorem Phi_nonneg (P : FinDist (∀ i, σ i)) (cuts : Finset (Finset ι))
    (hne : cuts.Nonempty) : 0 ≤ Phi P cuts hne := by
  exact Finset.le_inf' _ _ fun x hx => phiCut_nonneg P x

/--
`Φ = 0` exactly when some candidate cut decomposes the system into
independent parts. Equivalently, the system is *integrated* (`Φ > 0`) iff it
cannot be split into independent parts along any candidate cut.
-/
theorem Phi_eq_zero_iff (P : FinDist (∀ i, σ i)) (cuts : Finset (Finset ι))
    (hne : cuts.Nonempty) :
    Phi P cuts hne = 0 ↔ ∃ S ∈ cuts, CutIndep P S := by
  -- By definition of `Phi`, we have `Phi P cuts hne = cuts.inf' hne (fun S => phiCut P S)`.
  unfold Phi;
  constructor <;> intro h;
  · obtain ⟨ S, hS ⟩ := Finset.exists_mem_eq_inf' hne ( fun S => P.phiCut S );
    exact ⟨ S, hS.1, by rw [ ← phiCut_eq_zero_iff ] ; linarith ⟩;
  · refine' le_antisymm _ _;
    · obtain ⟨ S, hS₁, hS₂ ⟩ := h;
      exact le_trans ( Finset.inf'_le _ hS₁ ) ( phiCut_eq_zero_iff P S |>.2 hS₂ ▸ le_rfl );
    · exact Phi_nonneg P cuts hne

end FinDist

end IIT