import Mathlib
import Novelty.ZeroFitDialU64
import Novelty.TDialU100RangeShape

/-!
# The fluctuation spectrum of the range ceiling: powers of two are the unique minimisers

## Research context (FACT round-67 #2, exp 540, cycle 2)

`Novelty.TDialU100RangeShape` shows that the tie ceiling of the trailing-zero dial for uniform
draws from `{0,…,n−1}` is `6/7 + (6n/7 − devE n)/(n³ − n)`, where the *ceiling defect*
`devE n = Σ mⱼ³ − n³/7` satisfies `−n²/2 ≤ devE n ≤ 6/7` and depends only on the odd part
of `n`.  That leaves two structural questions, which this cycle answers.

1. *Which ranges are extremal?*  `devE_eq_iff_two_pow`: the defect attains its maximum `6/7`
   **exactly** at the powers of two.  Equivalently, power-of-two ranges are the unique
   minimisers of the tie ceiling: every other range sits strictly higher, and by
   `Novelty.TDialU100RangeShape.odd_range_gap_lower` typically an order of `n` higher.
2. *How large can the fluctuation be?*  `devE_ge_sharp` improves the lower bound to
   `devE n ≥ −(3/7)n²`, and `devE_fibonacci_like_family` shows that the constant `3/7` cannot
   be improved: along the family `nⱼ = 2^{j+1} + 1` (whose halving chain
   `n ↦ (n+1)/2` stays odd all the way down) the defect satisfies
   `devE nⱼ ≤ −(3/7)nⱼ² + (3/7)nⱼ + 12/7`, so `devE nⱼ / nⱼ² → −3/7`.
   The geometric series `1 + 1/4 + 1/16 + ⋯ = 4/3` behind that constant is
   `(9/28)·(4/3) = 3/7`: the fluctuation is a *self-similar* (Takagi-type) phenomenon whose
   amplitude is fixed by the 2-adic scaling, not by anything about the dial.
3. *Consequences for the ceiling.*  `ceiling_excess_le` and `ceiling_excess_family_ge` pin the
   excess `ρ²(n) − 6/7` between `2/(5n)` and `1/(2n)` for the extremal family: the excess is
   `Θ(1/n)`, with optimal constant `3/7`, whereas for `n = 2^b` it is `Θ(1/n²)`.
4. `u100_ceiling_window` records the numerical consequence at bitlen 100: across all draw-range
   sizes near `2¹⁰⁰` the ceiling lives in a window of width below `10⁻²⁹` around `6/7`, thirty
   orders of magnitude narrower than the recorded 4-bit erosion step `0.030`.
-/

open Finset

namespace Catalog.Novelty.TDialU100FluctuationSpectrum

open Catalog.Novelty.ZeroFitDialU64
open Catalog.Novelty.TDialU100RangeShape

/-! ## 1. Powers of two are exactly the maximisers of the defect -/

/-- **Extremality characterisation.**  The ceiling defect equals its maximal value `6/7`
precisely at the powers of two; equivalently, the power-of-two ranges are the unique minimisers
of the Spearman tie ceiling among all draw ranges. -/
theorem devE_eq_iff_two_pow (n : ℕ) (hn : 1 ≤ n) : devE n = 6 / 7 ↔ ∃ b : ℕ, n = 2 ^ b := by
  constructor
  · intro h
    induction n using Nat.strong_induction_on with
    | _ n ih =>
      rcases Nat.even_or_odd n with ⟨m, hm⟩ | ⟨a, ha⟩
      · have hm1 : 1 ≤ m := by omega
        have hn2 : n = 2 * m := by omega
        subst hn2
        have hEm : devE m = 6 / 7 := by rw [← devE_even m hm1]; exact h
        obtain ⟨b, hb⟩ := ih m (by omega) hm1 hEm
        exact ⟨b + 1, by rw [hb]; ring⟩
      · rcases Nat.eq_zero_or_pos a with rfl | ha1
        · exact ⟨0, by omega⟩
        · exfalso
          subst ha
          have hle : devE (2 * a + 1) ≤ 6 / 7 - ((2 * a + 1 : ℕ) : ℚ) ^ 2 / 7 := devE_odd_le a ha1
          have hpos : (0 : ℚ) < ((2 * a + 1 : ℕ) : ℚ) ^ 2 / 7 := by
            have : (1 : ℚ) ≤ ((2 * a + 1 : ℕ) : ℚ) := by
              have : (1 : ℕ) ≤ 2 * a + 1 := by omega
              exact_mod_cast this
            positivity
          rw [h] at hle
          linarith
  · rintro ⟨b, rfl⟩
    exact devE_two_pow b

/-! ## 2. The sharp fluctuation constant -/

/-- **Sharp lower bound on the defect.**  `devE n ≥ −(3/7)n²` for every `n`.  The constant
`3/7 = (9/28)·(4/3)` is the value of the geometric series generated by the odd step. -/
theorem devE_ge_sharp (n : ℕ) : -(3 / 7) * ((n : ℚ)) ^ 2 ≤ devE n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · rw [devE_zero]; norm_num
    rcases Nat.even_or_odd n with ⟨m, hm⟩ | ⟨a, ha⟩
    · have hm1 : 1 ≤ m := by omega
      have hn2 : n = 2 * m := by omega
      subst hn2
      rw [devE_even m hm1]
      have h := ih m (by omega)
      have hm0 : (0 : ℚ) ≤ (m : ℚ) := by positivity
      push_cast
      nlinarith
    · rcases Nat.eq_zero_or_pos a with rfl | ha1
      · simp only [Nat.mul_zero, Nat.zero_add] at ha
        subst ha
        rw [devE_one]
        norm_num
      · subst ha
        rw [devE_odd a ha1]
        have h := ih (a + 1) (by omega)
        have ha0 : (1 : ℚ) ≤ (a : ℚ) := by exact_mod_cast ha1
        push_cast at h ⊢
        nlinarith

/-- One step of the extremal family: `n ↦ 2n − 1` keeps the halving chain odd. -/
lemma devE_double_sub_one (m : ℕ) (hm : 2 ≤ m) :
    devE (2 * m - 1) = devE m - (9 * ((m : ℚ) - 1) ^ 2 + 3 * ((m : ℚ) - 1)) / 7 := by
  obtain ⟨a, rfl⟩ : ∃ a, m = a + 1 := ⟨m - 1, by omega⟩
  have ha1 : 1 ≤ a := by omega
  have hrw : 2 * (a + 1) - 1 = 2 * a + 1 := by omega
  rw [hrw, devE_odd a ha1]
  have : ((a : ℚ) + 1) - 1 = (a : ℚ) := by ring
  push_cast
  rw [this]

/-- **The extremal family.**  Along `nⱼ = 2^{j+1} + 1` the defect obeys
`devE nⱼ ≤ −(3/7)nⱼ² + (3/7)nⱼ + 12/7`, so `devE nⱼ / nⱼ² → −3/7` and the constant of
`devE_ge_sharp` is optimal. -/
theorem devE_extremal_family (j : ℕ) :
    devE (2 ^ (j + 1) + 1)
      ≤ -(3 / 7) * ((2 ^ (j + 1) + 1 : ℕ) : ℚ) ^ 2 + (3 / 7) * ((2 ^ (j + 1) + 1 : ℕ) : ℚ)
        + 12 / 7 := by
  induction j with
  | zero =>
      have h3 : devE 3 = -(6 / 7) := by
        have h := devE_odd 1 (by norm_num)
        norm_num [devE_even 1 (by norm_num), devE_one] at h ⊢
        linarith [h]
      norm_num [h3]
  | succ k ih =>
      set m : ℕ := 2 ^ (k + 1) + 1 with hm
      have hm2 : 2 ≤ m := by
        have : (2 : ℕ) ≤ 2 ^ (k + 1) := Nat.one_lt_two_pow (by omega)
        omega
      have hnext : 2 ^ (k + 1 + 1) + 1 = 2 * m - 1 := by
        rw [hm, pow_succ]
        have : (1 : ℕ) ≤ 2 ^ (k + 1) := Nat.one_le_two_pow
        omega
      rw [hnext, devE_double_sub_one m hm2]
      have hmq : (2 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm2
      have hcast : ((2 * m - 1 : ℕ) : ℚ) = 2 * (m : ℚ) - 1 := by
        have h1 : 1 ≤ 2 * m := by omega
        push_cast [Nat.cast_sub h1]
        ring
      rw [hcast]
      nlinarith [ih]

/-! ## 3. Consequences for the ceiling -/

/-- The ceiling excess over `6/7` is at most `1/(2n)` for every range of size `n ≥ 13`. -/
theorem ceiling_excess_le (n : ℕ) (hn : 13 ≤ n) :
    spearmanSq (rangeBlocks n) - 6 / 7 ≤ 1 / (2 * (n : ℚ)) := by
  have h2 : 2 ≤ n := by omega
  have hq : (13 : ℚ) ≤ (n : ℚ) := by exact_mod_cast hn
  have hn2 : (2 : ℚ) ≤ (n : ℚ) := by linarith
  have hden : (0 : ℚ) < (n : ℚ) ^ 3 - (n : ℚ) := cube_sub_self_pos hn2
  have hE := devE_ge_sharp n
  rw [range_spearmanSq n h2]
  have hstep : (6 * (n : ℚ) / 7 - devE n) / ((n : ℚ) ^ 3 - (n : ℚ)) ≤ 1 / (2 * (n : ℚ)) := by
    rw [div_le_div_iff₀ hden (by linarith)]
    nlinarith
  linarith

/-- Along the extremal family the excess is at least `2/(5n)`: the `Θ(1/n)` order and the
constant `3/7` of `devE_ge_sharp` are both realised. -/
theorem ceiling_excess_family_ge (j : ℕ) (hj : 5 ≤ j) :
    2 / (5 * ((2 ^ (j + 1) + 1 : ℕ) : ℚ))
      ≤ spearmanSq (rangeBlocks (2 ^ (j + 1) + 1)) - 6 / 7 := by
  set n : ℕ := 2 ^ (j + 1) + 1 with hn
  have hbig : 64 ≤ n := by
    have : (2 : ℕ) ^ 6 ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
    have h64 : (2 : ℕ) ^ 6 = 64 := by norm_num
    omega
  have h2 : 2 ≤ n := by omega
  have hq : (64 : ℚ) ≤ (n : ℚ) := by exact_mod_cast hbig
  have hn2 : (2 : ℚ) ≤ (n : ℚ) := by linarith
  have hden : (0 : ℚ) < (n : ℚ) ^ 3 - (n : ℚ) := cube_sub_self_pos hn2
  have hE : devE n ≤ -(3 / 7) * ((n : ℚ)) ^ 2 + (3 / 7) * ((n : ℚ)) + 12 / 7 :=
    devE_extremal_family j
  rw [range_spearmanSq n h2]
  have hstep : 2 / (5 * (n : ℚ)) ≤ (6 * (n : ℚ) / 7 - devE n) / ((n : ℚ) ^ 3 - (n : ℚ)) := by
    rw [div_le_div_iff₀ (by linarith) hden]
    nlinarith
  linarith

/-- **The bitlen-100 ceiling window.**  Over all draw-range sizes `n` with `2¹⁰⁰ ≤ n`, the tie
ceiling lies in `(6/7, 6/7 + 10⁻²⁹)`: a window thirty orders of magnitude narrower than the
recorded 4-bit erosion step `0.030`.  The fluctuation studied above is real but invisible at
bitlen 100 — which is why the exact extremal analysis, not a crude estimate, is what rules
range shape out as the cause of the band miss. -/
theorem u100_ceiling_window (n : ℕ) (hn : 2 ^ 100 ≤ n) :
    6 / 7 < spearmanSq (rangeBlocks n) ∧ spearmanSq (rangeBlocks n) < 6 / 7 + 1 / 10 ^ 29 := by
  have h2 : 2 ≤ n := le_trans (by norm_num) hn
  exact ⟨range_ceiling_gt n h2, by
    have h := range_shape_negligible_at_100 n hn
    linarith⟩

end Catalog.Novelty.TDialU100FluctuationSpectrum