import Mathlib

/-!
# The Atkin-Lehner group of a squarefree integer

This file develops, from first principles, the algebraic backbone of the theory of
**Atkin–Lehner involutions** on Shimura curves, in the elementary form that is used in
the Giampietro–Darmon factorization program.

For a squarefree integer `N > 1`, the Atkin–Lehner involutions `w_d` are indexed by the
Hall divisors `d ∣ N` (for squarefree `N`, *all* divisors are Hall divisors), and their
composition law is
`w_d ∘ w_e = w_{d ⋆ e}` where `d ⋆ e = d * e / gcd (d, e) ^ 2`.

We prove:

* `ALG` : an abstract model of the Atkin–Lehner group as the finite subsets of a type
  under **symmetric difference**, given a genuine `AddCommGroup` structure
  (`ALG.instAddCommGroup`).
* `ALG.two_torsion` : every Atkin–Lehner element is an involution, so the group is an
  elementary abelian `2`-group.
* `ALG.card_ALG` : the group has order `2 ^ (number of generators)`.
* `AtkinLehner.alMul_prod` : the *realization theorem* — the concrete arithmetic
  operation `⋆` on products of primes is exactly symmetric difference of the prime
  supports. This identifies the concrete Atkin–Lehner group of `N` with the abstract
  model `ALG` on the prime factors of `N`.
* `AtkinLehner.card_divisors_squarefree` : the Atkin–Lehner group of `N` has order
  `2 ^ ω(N)`, matching the number of divisors of `N`.
* `AtkinLehner.moebius_eq_one_iff_even` : the hypothesis "`N` has an even number of prime
  factors" appearing in the Giampietro–Darmon theorem is equivalent to `μ(N) = 1`.
* `AtkinLehner.genusZeroExamples` : the classical genus-zero levels `N ∈ {6, 10, 22}`
  are squarefree with an even number of prime factors.
-/

open scoped Classical

/-- The abstract Atkin–Lehner group model on a type `ι`: the finite subsets of `ι`
under symmetric difference. This is (non-canonically) the elementary abelian `2`-group
generated by the points of `ι`. -/
def ALG (ι : Type*) : Type _ := Finset ι

namespace ALG
variable {ι : Type*}

/-- The underlying finset of an element of the Atkin–Lehner group. -/
def toF : ALG ι → Finset ι := id
/-- Package a finset as an element of the Atkin–Lehner group. -/
def ofF : Finset ι → ALG ι := id

@[simp] lemma toF_ofF (s : Finset ι) : toF (ofF s) = s := rfl
@[simp] lemma ofF_toF (a : ALG ι) : ofF (toF a) = a := rfl

lemma toF_injective : Function.Injective (toF : ALG ι → Finset ι) := fun _ _ h => h

noncomputable instance : Zero (ALG ι) := ⟨ofF ∅⟩
noncomputable instance : Add (ALG ι) := ⟨fun a b => ofF (symmDiff (toF a) (toF b))⟩
noncomputable instance : Neg (ALG ι) := ⟨id⟩

@[simp] lemma toF_add (a b : ALG ι) : toF (a + b) = symmDiff (toF a) (toF b) := rfl
@[simp] lemma toF_zero : toF (0 : ALG ι) = (∅ : Finset ι) := rfl
@[simp] lemma toF_neg (a : ALG ι) : toF (-a) = toF a := rfl

noncomputable instance instAddCommGroup : AddCommGroup (ALG ι) where
  add_assoc a b c := toF_injective (by simp [symmDiff_assoc])
  zero_add a := toF_injective (by simp)
  add_zero a := toF_injective (by simp)
  add_comm a b := toF_injective (by simp [symmDiff_comm])
  neg_add_cancel a := toF_injective (by simp)
  nsmul := nsmulRec
  zsmul := zsmulRec

/-- Every Atkin–Lehner element is an involution: the group is an elementary abelian
`2`-group. -/
theorem two_torsion (x : ALG ι) : x + x = 0 := toF_injective (by simp)

/-- The order of the Atkin–Lehner group on a finite generating type is `2` raised to the
number of generators. -/
theorem card_ALG [Fintype ι] : Nat.card (ALG ι) = 2 ^ Fintype.card ι := by
  show Nat.card (Finset ι) = _
  rw [Nat.card_eq_fintype_card, Fintype.card_finset]

end ALG

namespace AtkinLehner
open Nat ArithmeticFunction

/-- The Atkin–Lehner composition law on natural numbers:
`d ⋆ e = d * e / gcd (d, e) ^ 2`. On divisors of a squarefree `N` this is the
composition of the involutions `w_d` and `w_e`. -/
def alMul (d e : ℕ) : ℕ := d * e / (Nat.gcd d e) ^ 2

@[simp] lemma alMul_comm (d e : ℕ) : alMul d e = alMul e d := by
  simp [alMul, Nat.mul_comm, Nat.gcd_comm]

@[simp] lemma alMul_one (d : ℕ) : alMul d 1 = d := by
  simp [alMul]

/-- Each Atkin–Lehner element squares to the identity `w_1`. -/
@[simp] lemma alMul_self {d : ℕ} (hd : d ≠ 0) : alMul d d = 1 := by
  have : Nat.gcd d d = d := Nat.gcd_self d
  simp only [alMul, this, pow_two]
  exact Nat.div_self (by positivity)

/-
**Key gcd computation.** For finsets `A`, `B` of primes, the gcd of the products of
their elements is the product over the intersection.
-/
lemma gcd_prod_primes (A B : Finset ℕ)
    (hA : ∀ p ∈ A, p.Prime) (hB : ∀ p ∈ B, p.Prime) :
    Nat.gcd (∏ p ∈ A, p) (∏ p ∈ B, p) = ∏ p ∈ (A ∩ B), p := by
  refine' Nat.dvd_antisymm _ _;
  · rw [ ← Finset.prod_inter_mul_prod_diff A B ];
    refine' Nat.Coprime.dvd_of_dvd_mul_right _ ( Nat.gcd_dvd_left _ _ );
    refine' Nat.Coprime.coprime_dvd_left ( Nat.gcd_dvd_right _ _ ) _;
    exact Nat.Coprime.prod_left fun p hp => Nat.Coprime.prod_right fun q hq => by have := Nat.coprime_primes ( hB p hp ) ( hA q ( Finset.mem_sdiff.mp hq |>.1 ) ) ; aesop;
  · exact Nat.dvd_gcd ( by apply_rules [ Finset.prod_dvd_prod_of_subset, Finset.inter_subset_left ] ) ( by apply_rules [ Finset.prod_dvd_prod_of_subset, Finset.inter_subset_right ] )

/-
**Realization theorem.** The concrete Atkin–Lehner operation `⋆` on products of
distinct primes realizes the symmetric difference of the prime supports. This is the
isomorphism between the concrete Atkin–Lehner group of `N` and the abstract model `ALG`
on the primes dividing `N`.
-/
theorem alMul_prod (A B : Finset ℕ)
    (hA : ∀ p ∈ A, p.Prime) (hB : ∀ p ∈ B, p.Prime) :
    alMul (∏ p ∈ A, p) (∏ p ∈ B, p) = ∏ p ∈ (symmDiff A B), p := by
  refine' Nat.div_eq_of_eq_mul_left _ _;
  · exact pow_pos ( Nat.gcd_pos_of_pos_left _ ( Finset.prod_pos fun p hp => Nat.Prime.pos ( hA p hp ) ) ) _;
  · rw [ gcd_prod_primes A B hA hB ];
    rw [ show symmDiff A B = ( A \ B ) ∪ ( B \ A ) by rfl, Finset.prod_union ];
    · rw [ ← Finset.prod_inter_mul_prod_diff A B, ← Finset.prod_inter_mul_prod_diff B A ];
      rw [ Finset.inter_comm ] ; ring;
    · exact disjoint_sdiff_sdiff

/-
For squarefree `N`, the number of divisors of `N` — equivalently the order of the
Atkin–Lehner group of `N` — is `2 ^ ω(N)`.
-/
theorem card_divisors_squarefree {N : ℕ} (hN : Squarefree N) :
    N.divisors.card = 2 ^ N.primeFactors.card := by
  convert Nat.card_divisors ?_ using 1;
  · rw [ Finset.prod_congr rfl fun x hx => by rw [ hN.natFactorization_le_one x |>.antisymm ( Nat.pos_of_ne_zero <| Finsupp.mem_support_iff.mp hx ) ] ] ; simp +decide;
  · aesop

/-- The order of the abstract Atkin–Lehner group on the primes dividing `N` equals the
number of divisors of a squarefree `N`. -/
theorem AL_group_order (N : ℕ) :
    Nat.card (ALG {p : ℕ // p ∈ N.primeFactors}) = 2 ^ N.primeFactors.card := by
  rw [ALG.card_ALG, Fintype.card_coe]

/-- For squarefree `N`, the number of (distinct) prime factors of `N` in the
`ArithmeticFunction` sense agrees with the cardinality of `N.primeFactors`. -/
lemma cardFactors_eq {N : ℕ} (hN : Squarefree N) :
    cardFactors N = N.primeFactors.card := by
  have h0 : N ≠ 0 := hN.ne_zero
  have := (ArithmeticFunction.cardDistinctFactors_eq_cardFactors_iff_squarefree h0).mpr hN
  rw [← this, ArithmeticFunction.cardDistinctFactors_apply, Nat.primeFactors, List.toFinset]
  rfl

/-- **The Giampietro–Darmon parity hypothesis.** For squarefree `N`, the condition that
`N` has an even number of prime factors is equivalent to `μ(N) = 1`. -/
theorem moebius_eq_one_iff_even {N : ℕ} (hN : Squarefree N) :
    moebius N = 1 ↔ Even N.primeFactors.card := by
  rw [ArithmeticFunction.moebius_apply_of_squarefree hN, cardFactors_eq hN]
  constructor
  · intro h
    by_contra hodd
    rw [Nat.not_even_iff_odd] at hodd
    rw [Odd.neg_one_pow hodd] at h
    norm_num at h
  · intro h
    rw [Even.neg_one_pow h]

/-- A product of two distinct primes is squarefree with exactly two prime factors. -/
lemma squarefree_two_primes {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) :
    Squarefree (p * q) ∧ (p * q).primeFactors.card = 2 := by
  refine ⟨?_, ?_⟩
  · rw [Nat.squarefree_mul_iff]
    exact ⟨(Nat.coprime_primes hp hq).mpr hpq, hp.prime.squarefree, hq.prime.squarefree⟩
  · rw [Nat.primeFactors_mul hp.ne_zero hq.ne_zero, hp.primeFactors, hq.primeFactors,
      Finset.card_union_of_disjoint (by simp [hpq])]
    simp

/-- The classical Giampietro–Darmon genus-zero levels `N ∈ {6, 10, 22}` are squarefree
with an even number of prime factors (so `μ(N) = 1`). -/
theorem genusZeroExamples :
    (Squarefree 6 ∧ Even (Nat.primeFactors 6).card) ∧
    (Squarefree 10 ∧ Even (Nat.primeFactors 10).card) ∧
    (Squarefree 22 ∧ Even (Nat.primeFactors 22).card) := by
  have h6 := squarefree_two_primes (p := 2) (q := 3) (by norm_num) (by norm_num) (by norm_num)
  have h10 := squarefree_two_primes (p := 2) (q := 5) (by norm_num) (by norm_num) (by norm_num)
  have h22 := squarefree_two_primes (p := 2) (q := 11) (by norm_num) (by norm_num) (by norm_num)
  norm_num at h6 h10 h22
  refine ⟨⟨h6.1, ?_⟩, ⟨h10.1, ?_⟩, ⟨h22.1, ?_⟩⟩
  · rw [h6.2]; decide
  · rw [h10.2]; decide
  · rw [h22.2]; decide

end AtkinLehner