/-
# The Euler Brick Tree, IV: a verified bounded search along the tree

Two things are done here.

* A *general local criterion*: if for some modulus `p` the quartic
  `w⁴ + 16u²v²` is a nonsquare in `ZMod p`, then the brick generated by the
  triple `(u,v,w)` is not a perfect cuboid.  This is the abstract engine behind
  the mod-7 obstruction of `Tropical.EulerBrickTree.Obstruction`.

* A *bounded search along the tree's growth*: every one of the `40` nodes of
  the Berggren tree of depth at most `3` is exhibited explicitly with its
  reachability proof, and for each of them the perfect-cuboid condition is
  refuted by trapping the quartic `c⁴ + 16a²b²` strictly between two
  consecutive squares.  Thus the first four levels of the brick tree contain no
  perfect cuboid, and the refutation is a Lean proof, not a numerical search.
-/
import Mathlib
import Tropical.EulerBrickTree.Core
import Tropical.EulerBrickTree.Descent
import Tropical.EulerBrickTree.Obstruction

namespace EulerBrickTree

/-! ## Tools -/

/-- An integer strictly between two consecutive squares is not a square. -/
theorem not_square_between {n k : ℤ} (hk : 0 ≤ k) (h1 : k ^ 2 < n) (h2 : n < (k + 1) ^ 2) :
    ¬ ∃ s : ℤ, n = s ^ 2 := by
  rintro ⟨s, rfl⟩
  have habs : |s| ^ 2 = s ^ 2 := sq_abs s
  have hs0 : 0 ≤ |s| := abs_nonneg s
  have h3 : k < |s| := by nlinarith
  have h4 : k + 1 ≤ |s| := by omega
  nlinarith

/-- **General local criterion.**  A modulus in which the quartic is a nonsquare
refutes the perfect-cuboid condition for the whole generated brick. -/
theorem brick_not_perfect_of_local_nonsquare (p : ℕ) [NeZero p] {u v w : ℤ}
    (h : IsPT u v w) (hw : w ≠ 0)
    (hns : ∀ S : ZMod p,
      ((w : ZMod p) ^ 4 + 16 * (u : ZMod p) ^ 2 * (v : ZMod p) ^ 2) ≠ S ^ 2) :
    ¬ IsPerfectCuboid (brick u v w).1 (brick u v w).2.1 (brick u v w).2.2 := by
  intro hperf
  obtain ⟨s, hs⟩ := (brick_perfect_iff h hw).mp hperf
  refine hns ((s : ℤ) : ZMod p) ?_
  have hc := congrArg (fun t : ℤ => (t : ZMod p)) hs
  push_cast at hc
  exact hc

/-- Reachability step along the first generator, in equational form. -/
theorem treeReach_stepA {a b c a' b' c' : ℤ} (h : TreeReach a b c)
    (e : bergA a b c = (a', b', c')) : TreeReach a' b' c' := by
  have h2 := TreeReach.stepA h
  rw [e] at h2
  simpa using h2

/-- Reachability step along the second generator, in equational form. -/
theorem treeReach_stepB {a b c a' b' c' : ℤ} (h : TreeReach a b c)
    (e : bergB a b c = (a', b', c')) : TreeReach a' b' c' := by
  have h2 := TreeReach.stepB h
  rw [e] at h2
  simpa using h2

/-- Reachability step along the third generator, in equational form. -/
theorem treeReach_stepC {a b c a' b' c' : ℤ} (h : TreeReach a b c)
    (e : bergC a b c = (a', b', c')) : TreeReach a' b' c' := by
  have h2 := TreeReach.stepC h
  rw [e] at h2
  simpa using h2

/-- Refuting a node: trap the quartic between consecutive squares. -/
theorem node_not_perfect {a b c k : ℤ} (h : TreeReach a b c) (hk : 0 ≤ k)
    (h1 : k ^ 2 < c ^ 4 + 16 * a ^ 2 * b ^ 2)
    (h2 : c ^ 4 + 16 * a ^ 2 * b ^ 2 < (k + 1) ^ 2) :
    ¬ IsPerfectCuboid (brick a b c).1 (brick a b c).2.1 (brick a b c).2.2 := by
  rw [treeBrick_perfect_iff h]
  exact not_square_between hk h1 h2

/-! ## The 40 nodes of depth at most three -/

theorem reach_3_4_5 : TreeReach 3 4 5 := TreeReach.root

theorem reach_5_12_13 : TreeReach 5 12 13 :=
  treeReach_stepA reach_3_4_5 (by norm_num [bergA])

theorem reach_21_20_29 : TreeReach 21 20 29 :=
  treeReach_stepB reach_3_4_5 (by norm_num [bergB])

theorem reach_15_8_17 : TreeReach 15 8 17 :=
  treeReach_stepC reach_3_4_5 (by norm_num [bergC])

theorem reach_7_24_25 : TreeReach 7 24 25 :=
  treeReach_stepA reach_5_12_13 (by norm_num [bergA])

theorem reach_55_48_73 : TreeReach 55 48 73 :=
  treeReach_stepB reach_5_12_13 (by norm_num [bergB])

theorem reach_45_28_53 : TreeReach 45 28 53 :=
  treeReach_stepC reach_5_12_13 (by norm_num [bergC])

theorem reach_39_80_89 : TreeReach 39 80 89 :=
  treeReach_stepA reach_21_20_29 (by norm_num [bergA])

theorem reach_119_120_169 : TreeReach 119 120 169 :=
  treeReach_stepB reach_21_20_29 (by norm_num [bergB])

theorem reach_77_36_85 : TreeReach 77 36 85 :=
  treeReach_stepC reach_21_20_29 (by norm_num [bergC])

theorem reach_33_56_65 : TreeReach 33 56 65 :=
  treeReach_stepA reach_15_8_17 (by norm_num [bergA])

theorem reach_65_72_97 : TreeReach 65 72 97 :=
  treeReach_stepB reach_15_8_17 (by norm_num [bergB])

theorem reach_35_12_37 : TreeReach 35 12 37 :=
  treeReach_stepC reach_15_8_17 (by norm_num [bergC])

theorem reach_9_40_41 : TreeReach 9 40 41 :=
  treeReach_stepA reach_7_24_25 (by norm_num [bergA])

theorem reach_105_88_137 : TreeReach 105 88 137 :=
  treeReach_stepB reach_7_24_25 (by norm_num [bergB])

theorem reach_91_60_109 : TreeReach 91 60 109 :=
  treeReach_stepC reach_7_24_25 (by norm_num [bergC])

theorem reach_105_208_233 : TreeReach 105 208 233 :=
  treeReach_stepA reach_55_48_73 (by norm_num [bergA])

theorem reach_297_304_425 : TreeReach 297 304 425 :=
  treeReach_stepB reach_55_48_73 (by norm_num [bergB])

theorem reach_187_84_205 : TreeReach 187 84 205 :=
  treeReach_stepC reach_55_48_73 (by norm_num [bergC])

theorem reach_95_168_193 : TreeReach 95 168 193 :=
  treeReach_stepA reach_45_28_53 (by norm_num [bergA])

theorem reach_207_224_305 : TreeReach 207 224 305 :=
  treeReach_stepB reach_45_28_53 (by norm_num [bergB])

theorem reach_117_44_125 : TreeReach 117 44 125 :=
  treeReach_stepC reach_45_28_53 (by norm_num [bergC])

theorem reach_57_176_185 : TreeReach 57 176 185 :=
  treeReach_stepA reach_39_80_89 (by norm_num [bergA])

theorem reach_377_336_505 : TreeReach 377 336 505 :=
  treeReach_stepB reach_39_80_89 (by norm_num [bergB])

theorem reach_299_180_349 : TreeReach 299 180 349 :=
  treeReach_stepC reach_39_80_89 (by norm_num [bergC])

theorem reach_217_456_505 : TreeReach 217 456 505 :=
  treeReach_stepA reach_119_120_169 (by norm_num [bergA])

theorem reach_697_696_985 : TreeReach 697 696 985 :=
  treeReach_stepB reach_119_120_169 (by norm_num [bergB])

theorem reach_459_220_509 : TreeReach 459 220 509 :=
  treeReach_stepC reach_119_120_169 (by norm_num [bergC])

theorem reach_175_288_337 : TreeReach 175 288 337 :=
  treeReach_stepA reach_77_36_85 (by norm_num [bergA])

theorem reach_319_360_481 : TreeReach 319 360 481 :=
  treeReach_stepB reach_77_36_85 (by norm_num [bergB])

theorem reach_165_52_173 : TreeReach 165 52 173 :=
  treeReach_stepC reach_77_36_85 (by norm_num [bergC])

theorem reach_51_140_149 : TreeReach 51 140 149 :=
  treeReach_stepA reach_33_56_65 (by norm_num [bergA])

theorem reach_275_252_373 : TreeReach 275 252 373 :=
  treeReach_stepB reach_33_56_65 (by norm_num [bergB])

theorem reach_209_120_241 : TreeReach 209 120 241 :=
  treeReach_stepC reach_33_56_65 (by norm_num [bergC])

theorem reach_115_252_277 : TreeReach 115 252 277 :=
  treeReach_stepA reach_65_72_97 (by norm_num [bergA])

theorem reach_403_396_565 : TreeReach 403 396 565 :=
  treeReach_stepB reach_65_72_97 (by norm_num [bergB])

theorem reach_273_136_305 : TreeReach 273 136 305 :=
  treeReach_stepC reach_65_72_97 (by norm_num [bergC])

theorem reach_85_132_157 : TreeReach 85 132 157 :=
  treeReach_stepA reach_35_12_37 (by norm_num [bergA])

theorem reach_133_156_205 : TreeReach 133 156 205 :=
  treeReach_stepB reach_35_12_37 (by norm_num [bergB])

theorem reach_63_16_65 : TreeReach 63 16 65 :=
  treeReach_stepC reach_35_12_37 (by norm_num [bergC])

/-! ## No perfect cuboid in the first four levels -/

/-- Node `(3,4,5)`: the quartic equals `2929`, strictly between `54²` and `55²`. -/
theorem not_perfect_3_4_5 :
    ¬ IsPerfectCuboid (brick 3 4 5).1 (brick 3 4 5).2.1 (brick 3 4 5).2.2 :=
  node_not_perfect reach_3_4_5 (k := 54) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(5,12,13)`: the quartic equals `86161`, strictly between `293²` and `294²`. -/
theorem not_perfect_5_12_13 :
    ¬ IsPerfectCuboid (brick 5 12 13).1 (brick 5 12 13).2.1 (brick 5 12 13).2.2 :=
  node_not_perfect reach_5_12_13 (k := 293) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(21,20,29)`: the quartic equals `3529681`, strictly between `1878²` and `1879²`. -/
theorem not_perfect_21_20_29 :
    ¬ IsPerfectCuboid (brick 21 20 29).1 (brick 21 20 29).2.1 (brick 21 20 29).2.2 :=
  node_not_perfect reach_21_20_29 (k := 1878) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(15,8,17)`: the quartic equals `313921`, strictly between `560²` and `561²`. -/
theorem not_perfect_15_8_17 :
    ¬ IsPerfectCuboid (brick 15 8 17).1 (brick 15 8 17).2.1 (brick 15 8 17).2.2 :=
  node_not_perfect reach_15_8_17 (k := 560) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(7,24,25)`: the quartic equals `842209`, strictly between `917²` and `918²`. -/
theorem not_perfect_7_24_25 :
    ¬ IsPerfectCuboid (brick 7 24 25).1 (brick 7 24 25).2.1 (brick 7 24 25).2.2 :=
  node_not_perfect reach_7_24_25 (k := 917) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(55,48,73)`: the quartic equals `139911841`, strictly between `11828²` and `11829²`. -/
theorem not_perfect_55_48_73 :
    ¬ IsPerfectCuboid (brick 55 48 73).1 (brick 55 48 73).2.1 (brick 55 48 73).2.2 :=
  node_not_perfect reach_55_48_73 (k := 11828) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(45,28,53)`: the quartic equals `33292081`, strictly between `5769²` and `5770²`. -/
theorem not_perfect_45_28_53 :
    ¬ IsPerfectCuboid (brick 45 28 53).1 (brick 45 28 53).2.1 (brick 45 28 53).2.2 :=
  node_not_perfect reach_45_28_53 (k := 5769) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(39,80,89)`: the quartic equals `218492641`, strictly between `14781²` and `14782²`. -/
theorem not_perfect_39_80_89 :
    ¬ IsPerfectCuboid (brick 39 80 89).1 (brick 39 80 89).2.1 (brick 39 80 89).2.2 :=
  node_not_perfect reach_39_80_89 (k := 14781) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(119,120,169)`: the quartic equals `4078425121`, strictly between `63862²` and `63863²`. -/
theorem not_perfect_119_120_169 :
    ¬ IsPerfectCuboid (brick 119 120 169).1 (brick 119 120 169).2.1 (brick 119 120 169).2.2 :=
  node_not_perfect reach_119_120_169 (k := 63862) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(77,36,85)`: the quartic equals `175144369`, strictly between `13234²` and `13235²`. -/
theorem not_perfect_77_36_85 :
    ¬ IsPerfectCuboid (brick 77 36 85).1 (brick 77 36 85).2.1 (brick 77 36 85).2.2 :=
  node_not_perfect reach_77_36_85 (k := 13234) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(33,56,65)`: the quartic equals `72492289`, strictly between `8514²` and `8515²`. -/
theorem not_perfect_33_56_65 :
    ¬ IsPerfectCuboid (brick 33 56 65).1 (brick 33 56 65).2.1 (brick 33 56 65).2.2 :=
  node_not_perfect reach_33_56_65 (k := 8514) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(65,72,97)`: the quartic equals `438967681`, strictly between `20951²` and `20952²`. -/
theorem not_perfect_65_72_97 :
    ¬ IsPerfectCuboid (brick 65 72 97).1 (brick 65 72 97).2.1 (brick 65 72 97).2.2 :=
  node_not_perfect reach_65_72_97 (k := 20951) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(35,12,37)`: the quartic equals `4696561`, strictly between `2167²` and `2168²`. -/
theorem not_perfect_35_12_37 :
    ¬ IsPerfectCuboid (brick 35 12 37).1 (brick 35 12 37).2.1 (brick 35 12 37).2.2 :=
  node_not_perfect reach_35_12_37 (k := 2167) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(9,40,41)`: the quartic equals `4899361`, strictly between `2213²` and `2214²`. -/
theorem not_perfect_9_40_41 :
    ¬ IsPerfectCuboid (brick 9 40 41).1 (brick 9 40 41).2.1 (brick 9 40 41).2.2 :=
  node_not_perfect reach_9_40_41 (k := 2213) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(105,88,137)`: the quartic equals `1718316961`, strictly between `41452²` and `41453²`. -/
theorem not_perfect_105_88_137 :
    ¬ IsPerfectCuboid (brick 105 88 137).1 (brick 105 88 137).2.1 (brick 105 88 137).2.2 :=
  node_not_perfect reach_105_88_137 (k := 41452) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(91,60,109)`: the quartic equals `618143761`, strictly between `24862²` and `24863²`. -/
theorem not_perfect_91_60_109 :
    ¬ IsPerfectCuboid (brick 91 60 109).1 (brick 91 60 109).2.1 (brick 91 60 109).2.2 :=
  node_not_perfect reach_91_60_109 (k := 24862) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(105,208,233)`: the quartic equals `10579065121`, strictly between `102854²` and `102855²`. -/
theorem not_perfect_105_208_233 :
    ¬ IsPerfectCuboid (brick 105 208 233).1 (brick 105 208 233).2.1 (brick 105 208 233).2.2 :=
  node_not_perfect reach_105_208_233 (k := 102854) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(297,304,425)`: the quartic equals `163056157729`, strictly between `403802²` and `403803²`. -/
theorem not_perfect_297_304_425 :
    ¬ IsPerfectCuboid (brick 297 304 425).1 (brick 297 304 425).2.1 (brick 297 304 425).2.2 :=
  node_not_perfect reach_297_304_425 (k := 403802) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(187,84,205)`: the quartic equals `5713960849`, strictly between `75590²` and `75591²`. -/
theorem not_perfect_187_84_205 :
    ¬ IsPerfectCuboid (brick 187 84 205).1 (brick 187 84 205).2.1 (brick 187 84 205).2.2 :=
  node_not_perfect reach_187_84_205 (k := 75590) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(95,168,193)`: the quartic equals `5463033601`, strictly between `73912²` and `73913²`. -/
theorem not_perfect_95_168_193 :
    ¬ IsPerfectCuboid (brick 95 168 193).1 (brick 95 168 193).2.1 (brick 95 168 193).2.2 :=
  node_not_perfect reach_95_168_193 (k := 73912) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(207,224,305)`: the quartic equals `43053513409`, strictly between `207493²` and `207494²`. -/
theorem not_perfect_207_224_305 :
    ¬ IsPerfectCuboid (brick 207 224 305).1 (brick 207 224 305).2.1 (brick 207 224 305).2.2 :=
  node_not_perfect reach_207_224_305 (k := 207493) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(117,44,125)`: the quartic equals `668171089`, strictly between `25849²` and `25850²`. -/
theorem not_perfect_117_44_125 :
    ¬ IsPerfectCuboid (brick 117 44 125).1 (brick 117 44 125).2.1 (brick 117 44 125).2.2 :=
  node_not_perfect reach_117_44_125 (k := 25849) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(57,176,185)`: the quartic equals `2781607009`, strictly between `52740²` and `52741²`. -/
theorem not_perfect_57_176_185 :
    ¬ IsPerfectCuboid (brick 57 176 185).1 (brick 57 176 185).2.1 (brick 57 176 185).2.2 :=
  node_not_perfect reach_57_176_185 (k := 52740) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(377,336,505)`: the quartic equals `321770479969`, strictly between `567248²` and `567249²`. -/
theorem not_perfect_377_336_505 :
    ¬ IsPerfectCuboid (brick 377 336 505).1 (brick 377 336 505).2.1 (brick 377 336 505).2.2 :=
  node_not_perfect reach_377_336_505 (k := 567248) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(299,180,349)`: the quartic equals `61180962001`, strictly between `247347²` and `247348²`. -/
theorem not_perfect_299_180_349 :
    ¬ IsPerfectCuboid (brick 299 180 349).1 (brick 299 180 349).2.1 (brick 299 180 349).2.2 :=
  node_not_perfect reach_299_180_349 (k := 247347) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(217,456,505)`: the quartic equals `221701723489`, strictly between `470852²` and `470853²`. -/
theorem not_perfect_217_456_505 :
    ¬ IsPerfectCuboid (brick 217 456 505).1 (brick 217 456 505).2.1 (brick 217 456 505).2.2 :=
  node_not_perfect reach_217_456_505 (k := 470852) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(697,696,985)`: the quartic equals `4706674991329`, strictly between `2169487²` and `2169488²`. -/
theorem not_perfect_697_696_985 :
    ¬ IsPerfectCuboid (brick 697 696 985).1 (brick 697 696 985).2.1 (brick 697 696 985).2.2 :=
  node_not_perfect reach_697_696_985 (k := 2169487) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(459,220,509)`: the quartic equals `230274330961`, strictly between `479869²` and `479870²`. -/
theorem not_perfect_459_220_509 :
    ¬ IsPerfectCuboid (brick 459 220 509).1 (brick 459 220 509).2.1 (brick 459 220 509).2.2 :=
  node_not_perfect reach_459_220_509 (k := 479869) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(175,288,337)`: the quartic equals `53540477761`, strictly between `231388²` and `231389²`. -/
theorem not_perfect_175_288_337 :
    ¬ IsPerfectCuboid (brick 175 288 337).1 (brick 175 288 337).2.1 (brick 175 288 337).2.2 :=
  node_not_perfect reach_175_288_337 (k := 231388) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(319,360,481)`: the quartic equals `264539521921`, strictly between `514334²` and `514335²`. -/
theorem not_perfect_319_360_481 :
    ¬ IsPerfectCuboid (brick 319 360 481).1 (brick 319 360 481).2.1 (brick 319 360 481).2.2 :=
  node_not_perfect reach_319_360_481 (k := 514334) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(165,52,173)`: the quartic equals `2073607441`, strictly between `45536²` and `45537²`. -/
theorem not_perfect_165_52_173 :
    ¬ IsPerfectCuboid (brick 165 52 173).1 (brick 165 52 173).2.1 (brick 165 52 173).2.2 :=
  node_not_perfect reach_165_52_173 (k := 45536) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(51,140,149)`: the quartic equals `1308558001`, strictly between `36173²` and `36174²`. -/
theorem not_perfect_51_140_149 :
    ¬ IsPerfectCuboid (brick 51 140 149).1 (brick 51 140 149).2.1 (brick 51 140 149).2.2 :=
  node_not_perfect reach_51_140_149 (k := 36173) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(275,252,373)`: the quartic equals `96196718641`, strictly between `310155²` and `310156²`. -/
theorem not_perfect_275_252_373 :
    ¬ IsPerfectCuboid (brick 275 252 373).1 (brick 275 252 373).2.1 (brick 275 252 373).2.2 :=
  node_not_perfect reach_275_252_373 (k := 310155) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(209,120,241)`: the quartic equals `13437504961`, strictly between `115920²` and `115921²`. -/
theorem not_perfect_209_120_241 :
    ¬ IsPerfectCuboid (brick 209 120 241).1 (brick 209 120 241).2.1 (brick 209 120 241).2.2 :=
  node_not_perfect reach_209_120_241 (k := 115920) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(115,252,277)`: the quartic equals `19324785841`, strictly between `139013²` and `139014²`. -/
theorem not_perfect_115_252_277 :
    ¬ IsPerfectCuboid (brick 115 252 277).1 (brick 115 252 277).2.1 (brick 115 252 277).2.2 :=
  node_not_perfect reach_115_252_277 (k := 139013) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(403,396,565)`: the quartic equals `509397876529`, strictly between `713721²` and `713722²`. -/
theorem not_perfect_403_396_565 :
    ¬ IsPerfectCuboid (brick 403 396 565).1 (brick 403 396 565).2.1 (brick 403 396 565).2.2 :=
  node_not_perfect reach_403_396_565 (k := 713721) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(273,136,305)`: the quartic equals `30709464769`, strictly between `175241²` and `175242²`. -/
theorem not_perfect_273_136_305 :
    ¬ IsPerfectCuboid (brick 273 136 305).1 (brick 273 136 305).2.1 (brick 273 136 305).2.2 :=
  node_not_perfect reach_273_136_305 (k := 175241) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(85,132,157)`: the quartic equals `2621787601`, strictly between `51203²` and `51204²`. -/
theorem not_perfect_85_132_157 :
    ¬ IsPerfectCuboid (brick 85 132 157).1 (brick 85 132 157).2.1 (brick 85 132 157).2.2 :=
  node_not_perfect reach_85_132_157 (k := 51203) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(133,156,205)`: the quartic equals `8653772689`, strictly between `93025²` and `93026²`. -/
theorem not_perfect_133_156_205 :
    ¬ IsPerfectCuboid (brick 133 156 205).1 (brick 133 156 205).2.1 (brick 133 156 205).2.2 :=
  node_not_perfect reach_133_156_205 (k := 93025) (by norm_num) (by norm_num) (by norm_num)

/-- Node `(63,16,65)`: the quartic equals `34107649`, strictly between `5840²` and `5841²`. -/
theorem not_perfect_63_16_65 :
    ¬ IsPerfectCuboid (brick 63 16 65).1 (brick 63 16 65).2.1 (brick 63 16 65).2.2 :=
  node_not_perfect reach_63_16_65 (k := 5840) (by norm_num) (by norm_num) (by norm_num)

/-- The list of all `40` tree nodes of depth at most three. -/
def nodesDepthLe3 : List (ℤ × ℤ × ℤ) :=
  [(3, 4, 5),
   (5, 12, 13),
   (21, 20, 29),
   (15, 8, 17),
   (7, 24, 25),
   (55, 48, 73),
   (45, 28, 53),
   (39, 80, 89),
   (119, 120, 169),
   (77, 36, 85),
   (33, 56, 65),
   (65, 72, 97),
   (35, 12, 37),
   (9, 40, 41),
   (105, 88, 137),
   (91, 60, 109),
   (105, 208, 233),
   (297, 304, 425),
   (187, 84, 205),
   (95, 168, 193),
   (207, 224, 305),
   (117, 44, 125),
   (57, 176, 185),
   (377, 336, 505),
   (299, 180, 349),
   (217, 456, 505),
   (697, 696, 985),
   (459, 220, 509),
   (175, 288, 337),
   (319, 360, 481),
   (165, 52, 173),
   (51, 140, 149),
   (275, 252, 373),
   (209, 120, 241),
   (115, 252, 277),
   (403, 396, 565),
   (273, 136, 305),
   (85, 132, 157),
   (133, 156, 205),
   (63, 16, 65)]

/-- **Bounded search theorem.**  No node of the Berggren tree of depth at most
three carries a perfect cuboid: the space-diagonal condition fails at each of
the first `40` nodes, with an explicit pair of consecutive squares trapping the
quartic. -/
theorem no_perfect_cuboid_depth_le_three :
    ∀ t ∈ nodesDepthLe3,
      ¬ IsPerfectCuboid (brick t.1 t.2.1 t.2.2).1 (brick t.1 t.2.1 t.2.2).2.1
        (brick t.1 t.2.1 t.2.2).2.2 := by
  intro t ht
  simp only [nodesDepthLe3, List.mem_cons, List.not_mem_nil, or_false] at ht
  rcases ht with rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl
  · exact not_perfect_3_4_5
  · exact not_perfect_5_12_13
  · exact not_perfect_21_20_29
  · exact not_perfect_15_8_17
  · exact not_perfect_7_24_25
  · exact not_perfect_55_48_73
  · exact not_perfect_45_28_53
  · exact not_perfect_39_80_89
  · exact not_perfect_119_120_169
  · exact not_perfect_77_36_85
  · exact not_perfect_33_56_65
  · exact not_perfect_65_72_97
  · exact not_perfect_35_12_37
  · exact not_perfect_9_40_41
  · exact not_perfect_105_88_137
  · exact not_perfect_91_60_109
  · exact not_perfect_105_208_233
  · exact not_perfect_297_304_425
  · exact not_perfect_187_84_205
  · exact not_perfect_95_168_193
  · exact not_perfect_207_224_305
  · exact not_perfect_117_44_125
  · exact not_perfect_57_176_185
  · exact not_perfect_377_336_505
  · exact not_perfect_299_180_349
  · exact not_perfect_217_456_505
  · exact not_perfect_697_696_985
  · exact not_perfect_459_220_509
  · exact not_perfect_175_288_337
  · exact not_perfect_319_360_481
  · exact not_perfect_165_52_173
  · exact not_perfect_51_140_149
  · exact not_perfect_275_252_373
  · exact not_perfect_209_120_241
  · exact not_perfect_115_252_277
  · exact not_perfect_403_396_565
  · exact not_perfect_273_136_305
  · exact not_perfect_85_132_157
  · exact not_perfect_133_156_205
  · exact not_perfect_63_16_65

end EulerBrickTree