#!/usr/bin/env python3
"""
algorithms.py — Core algorithms for Cayley graph spectral analysis.

Implements:
1. Subgroup closure computation via BFS (O(|G|·|S|))
2. Cayley graph adjacency matrix construction
3. Spectral gap computation via eigenvalue decomposition
4. Canonical path construction for specific generator families
5. Dirichlet energy and variance computation
6. Trace method for closed walk counting

All algorithms include type hints and docstrings.
"""

import numpy as np
from typing import Tuple, List, Set, Dict, Optional, Callable
from itertools import permutations
from math import factorial


# ──────────────────────────────────────────────────────────────
# 1. Permutation Group Operations
# ──────────────────────────────────────────────────────────────

def compose_perm(p: tuple, q: tuple) -> tuple:
    """Compose permutations: (p∘q)(i) = p(q(i)).

    Time: O(n), Space: O(n)

    >>> compose_perm((1,0,2), (2,0,1))
    (0, 1, 2)  # No, actually: p(q(0))=p(2)=2, p(q(1))=p(0)=1, p(q(2))=p(1)=0
    """
    return tuple(p[q[i]] for i in range(len(p)))


def inverse_perm(p: tuple) -> tuple:
    """Inverse permutation.

    Time: O(n), Space: O(n)
    """
    n = len(p)
    inv = [0] * n
    for i in range(n):
        inv[p[i]] = i
    return tuple(inv)


def identity_perm(n: int) -> tuple:
    """Identity permutation on {0,...,n-1}."""
    return tuple(range(n))


# ──────────────────────────────────────────────────────────────
# 2. Subgroup Closure (BFS)
# ──────────────────────────────────────────────────────────────

def closure_bfs(generators: List[tuple], n: int) -> Set[tuple]:
    """Compute the subgroup generated by `generators` using BFS.

    Algorithm:
        Initialize visited = {e}, frontier = {e}.
        While frontier is non-empty:
            For each g in frontier, for each s in generators ∪ generators⁻¹:
                If s·g ∉ visited: add to visited and next_frontier.
        Return visited.

    Time: O(|⟨S⟩| · |S|), Space: O(|⟨S⟩|)
    """
    e = identity_perm(n)
    all_gens = list(generators) + [inverse_perm(s) for s in generators]
    visited = {e}
    frontier = [e]
    while frontier:
        next_frontier = []
        for g in frontier:
            for s in all_gens:
                h = compose_perm(s, g)
                if h not in visited:
                    visited.add(h)
                    next_frontier.append(h)
        frontier = next_frontier
    return visited


def generates_symmetric_group(sigma: tuple, tau: tuple) -> bool:
    """Check whether σ and τ generate S_n.

    Time: O(n! · n), Space: O(n!)
    """
    n = len(sigma)
    return len(closure_bfs([sigma, tau], n)) == factorial(n)


# ──────────────────────────────────────────────────────────────
# 3. Cayley Graph Adjacency Matrix
# ──────────────────────────────────────────────────────────────

def cayley_adjacency_matrix(
    generators: List[tuple],
    n: int,
    normalize: bool = True
) -> Tuple[np.ndarray, List[tuple], Dict[tuple, int]]:
    """Build the (normalized) adjacency matrix of Cay(G, S).

    The generator set S is the union of generators and their inverses.

    Args:
        generators: List of group generators.
        n: Size of permutations (acting on {0,...,n-1}).
        normalize: If True, divide by |S| to get a stochastic matrix.

    Returns:
        (A, elements, index): adjacency matrix, element list, element-to-index map.

    Time: O(n! · |S| · n), Space: O((n!)²)
    """
    # Symmetric closure
    gen_set = set()
    for g in generators:
        gen_set.add(g)
        gen_set.add(inverse_perm(g))
    gen_list = list(gen_set)
    d = len(gen_list)

    elements = sorted(permutations(range(n)))
    index = {p: i for i, p in enumerate(elements)}
    N = len(elements)

    A = np.zeros((N, N))
    for i, g in enumerate(elements):
        for s in gen_list:
            j = index[compose_perm(s, g)]
            A[i, j] += 1.0

    if normalize:
        A /= d
    return A, elements, index


# ──────────────────────────────────────────────────────────────
# 4. Spectral Analysis
# ──────────────────────────────────────────────────────────────

def compute_spectrum(A: np.ndarray) -> np.ndarray:
    """Compute all eigenvalues of symmetric matrix A, sorted decreasingly.

    Time: O(N³), Space: O(N²)
    """
    eigenvalues = np.linalg.eigvalsh(A)
    return np.sort(eigenvalues)[::-1]


def spectral_gap(A: np.ndarray) -> float:
    """Compute the spectral gap: 1 - λ₂.

    The spectral gap measures how quickly a random walk on the
    corresponding graph converges to the uniform distribution.

    Time: O(N³), Space: O(N²)
    """
    eigs = compute_spectrum(A)
    return float(1.0 - eigs[1])


def alon_boppana_bound(degree: int) -> float:
    """Compute the Alon-Boppana lower bound on λ₂ for d-regular graphs.

    For an infinite family of d-regular graphs:
        λ₂ ≥ 2√(d-1)/d - o(1)

    So gap ≤ 1 - 2√(d-1)/d.
    """
    return 1.0 - 2 * np.sqrt(degree - 1) / degree


# ──────────────────────────────────────────────────────────────
# 5. Dirichlet Energy and Variance
# ──────────────────────────────────────────────────────────────

def dirichlet_energy(
    f: np.ndarray,
    A: np.ndarray,
    elements: List[tuple],
    generators: List[tuple],
    n: int
) -> float:
    """Compute the Dirichlet energy E_S(f) = Σ_x Σ_{s∈S} (f(sx) - f(x))².

    Time: O(N · |S| · n), Space: O(N)
    """
    gen_set = set()
    for g in generators:
        gen_set.add(g)
        gen_set.add(inverse_perm(g))

    index = {p: i for i, p in enumerate(elements)}
    energy = 0.0
    for i, x in enumerate(elements):
        for s in gen_set:
            j = index[compose_perm(s, x)]
            energy += (f[j] - f[i]) ** 2
    return energy


def compute_variance(f: np.ndarray) -> float:
    """Compute the variance of f over the uniform distribution.

    Var(f) = (1/|G|) Σ (f(x) - f̄)²
    """
    return float(np.var(f))


def averaging_operator(
    f: np.ndarray,
    A: np.ndarray
) -> np.ndarray:
    """Apply the Cayley averaging operator: Af = A @ f.

    Time: O(N²), Space: O(N)
    """
    return A @ f


# ──────────────────────────────────────────────────────────────
# 6. Trace Method
# ──────────────────────────────────────────────────────────────

def trace_power(A: np.ndarray, k: int) -> float:
    """Compute tr(A^k), the trace of the k-th power of A.

    For a normalized adjacency matrix, tr(A^(2k))/|G| counts the
    expected number of closed walks of length 2k starting from
    a random vertex.

    Time: O(N³ · log k) using matrix exponentiation, Space: O(N²)
    """
    return float(np.trace(np.linalg.matrix_power(A, k)))


def closed_walk_excess(A: np.ndarray, k: int) -> float:
    """Compute the normalized closed-walk excess:
    tr(A^(2k))/|G| - 1.

    This quantity is related to the spectral gap: if all nontrivial
    eigenvalues are ≤ 1-ε, then tr(A^(2k))/|G| - 1 ≤ (1-ε)^(2k) · |G|.
    """
    N = A.shape[0]
    return trace_power(A, 2 * k) / N - 1.0


# ──────────────────────────────────────────────────────────────
# 7. L² Contraction Verification
# ──────────────────────────────────────────────────────────────

def verify_l2_contraction(
    A: np.ndarray,
    f: np.ndarray,
    num_steps: int = 20
) -> List[float]:
    """Verify L² contraction: ‖A^k f‖₂² should decrease.

    Returns the sequence of ‖A^k f_0‖₂² where f_0 = f - mean(f).

    Time: O(num_steps · N²), Space: O(N)
    """
    f0 = f - np.mean(f)  # Project to mean-zero subspace
    norms = [float(np.sum(f0 ** 2))]
    current = f0.copy()
    for _ in range(num_steps):
        current = A @ current
        norms.append(float(np.sum(current ** 2)))
    return norms


# ──────────────────────────────────────────────────────────────
# 8. Canonical Path Construction (for standard generators)
# ──────────────────────────────────────────────────────────────

def canonical_path_standard(
    x: tuple, y: tuple, n: int
) -> List[tuple]:
    """Compute a canonical path from x to y using bubble sort.

    Uses adjacent transpositions to sort x⁻¹y, which gives a path
    in Cay(S_n, {(01), (01)⁻¹, cycle, cycle⁻¹}).

    This is a simplified version that uses only adjacent transpositions.

    Time: O(n²), Space: O(n²)
    """
    target = compose_perm(inverse_perm(x), y)  # y·x⁻¹... no, x⁻¹·y
    # Actually we need compose_perm(y, inverse_perm(x)) for left multiplication
    # But for path: we need l such that l·x = y, so l = y·x⁻¹
    perm = list(compose_perm(y, inverse_perm(x)))
    path = []
    # Bubble sort to decompose into adjacent transpositions
    for i in range(n):
        for j in range(n - 1, i, -1):
            if perm[j-1] > perm[j]:
                perm[j-1], perm[j] = perm[j], perm[j-1]
                # Record the transposition (j-1, j)
                swap = list(range(n))
                swap[j-1], swap[j] = swap[j], swap[j-1]
                path.append(tuple(swap))
    return path


# ──────────────────────────────────────────────────────────────
# Example usage
# ──────────────────────────────────────────────────────────────

if __name__ == '__main__':
    n = 5
    print(f"Algorithms demo for S_{n}")
    print(f"|S_{n}| = {factorial(n)}")

    # Standard generators
    tau = tuple((i + 1) % n for i in range(n))  # long cycle
    sigma = list(range(n)); sigma[0], sigma[1] = sigma[1], sigma[0]
    sigma = tuple(sigma)  # swap (0 1)

    print(f"\nGenerators: σ={sigma}, τ={tau}")
    print(f"Generates S_{n}: {generates_symmetric_group(sigma, tau)}")

    # Build Cayley graph
    A, elems, idx = cayley_adjacency_matrix([sigma, tau], n)
    print(f"\nAdjacency matrix shape: {A.shape}")

    # Spectrum
    eigs = compute_spectrum(A)
    gap = spectral_gap(A)
    print(f"Spectral gap: {gap:.6f}")
    print(f"Top 10 eigenvalues: {eigs[:10].round(4)}")

    # Alon-Boppana
    ab = alon_boppana_bound(4)
    print(f"Alon-Boppana gap bound: {ab:.6f}")

    # Dirichlet energy
    f = np.random.randn(len(elems))
    E = dirichlet_energy(f, A, elems, [sigma, tau], n)
    print(f"\nDirichlet energy of random f: {E:.4f}")

    # L² contraction
    norms = verify_l2_contraction(A, f, 20)
    print(f"L² norms (first 10 steps): {[f'{x:.4f}' for x in norms[:10]]}")
    print(f"Contraction ratio (step 1): {norms[1]/norms[0]:.6f}")
    print(f"Expected ratio from gap: {(1-gap)**2:.6f}")

    # Trace method
    for k in [2, 3, 4]:
        excess = closed_walk_excess(A, k)
        print(f"Closed walk excess k={k}: {excess:.6f}")
