"""
Algorithms for the Periodic Table of Finite Groups.

Provides type-hinted implementations of:
- Derived series computation
- Lower central series computation
- Derived depth
- Group valence (minimal normal subgroup count)
- Periodic table entry construction
- Quantitative periodic law verification
"""

from __future__ import annotations
from typing import FrozenSet, List, Set, Tuple, Dict, Optional
from itertools import product as cartesian_product
from math import gcd
from functools import reduce
from collections import Counter


# A group element is an int; a group is represented by its multiplication table.
Element = int


class FiniteGroup:
    """A finite group represented by its Cayley (multiplication) table.

    Elements are integers 0, 1, ..., n-1 where 0 is the identity.
    """

    def __init__(self, table: List[List[int]], name: str = "G") -> None:
        self.n = len(table)
        self.table = table
        self.name = name
        self._inv_cache: Dict[int, int] = {}

    def mul(self, a: Element, b: Element) -> Element:
        """Multiply two elements."""
        return self.table[a][b]

    def inv(self, a: Element) -> Element:
        """Compute the inverse of an element."""
        if a not in self._inv_cache:
            for b in range(self.n):
                if self.table[a][b] == 0:
                    self._inv_cache[a] = b
                    break
        return self._inv_cache[a]

    def commutator(self, a: Element, b: Element) -> Element:
        """Compute [a, b] = a * b * a^{-1} * b^{-1}."""
        return self.mul(self.mul(self.mul(a, b), self.inv(a)), self.inv(b))

    def order(self) -> int:
        """Return the order of the group."""
        return self.n

    def elements(self) -> List[Element]:
        """Return all elements."""
        return list(range(self.n))

    def is_normal(self, subgroup: FrozenSet[Element]) -> bool:
        """Check if a subgroup is normal."""
        for g in range(self.n):
            for h in subgroup:
                conjugate = self.mul(self.mul(g, h), self.inv(g))
                if conjugate not in subgroup:
                    return False
        return True

    def subgroup_generated_by(self, generators: Set[Element]) -> FrozenSet[Element]:
        """Compute the subgroup generated by a set of elements."""
        subgroup = set(generators)
        subgroup.add(0)  # identity
        changed = True
        while changed:
            changed = False
            new_elements: Set[Element] = set()
            for a in subgroup:
                for b in subgroup:
                    prod = self.mul(a, b)
                    if prod not in subgroup:
                        new_elements.add(prod)
                        changed = True
                inv_a = self.inv(a)
                if inv_a not in subgroup:
                    new_elements.add(inv_a)
                    changed = True
            subgroup.update(new_elements)
        return frozenset(subgroup)

    def commutator_subgroup(
        self, h_set: FrozenSet[Element], k_set: FrozenSet[Element]
    ) -> FrozenSet[Element]:
        """Compute [H, K] = subgroup generated by all [h, k] for h in H, k in K."""
        commutators: Set[Element] = set()
        for h in h_set:
            for k in k_set:
                commutators.add(self.commutator(h, k))
        return self.subgroup_generated_by(commutators)

    def center(self) -> FrozenSet[Element]:
        """Compute the center Z(G)."""
        center_elems: Set[Element] = set()
        for g in range(self.n):
            if all(self.table[g][h] == self.table[h][g] for h in range(self.n)):
                center_elems.add(g)
        return frozenset(center_elems)


def derived_series(g: FiniteGroup, max_steps: int = 100) -> List[FrozenSet[Element]]:
    """Compute the derived series D^0(G) ⊇ D^1(G) ⊇ ... until stabilization.

    D^0(G) = G, D^{n+1}(G) = [D^n(G), D^n(G)].
    """
    top = frozenset(range(g.n))
    series = [top]
    current = top
    for _ in range(max_steps):
        next_term = g.commutator_subgroup(current, current)
        series.append(next_term)
        if next_term == current:
            break
        current = next_term
    return series


def lower_central_series(
    g: FiniteGroup, max_steps: int = 100
) -> List[FrozenSet[Element]]:
    """Compute the lower central series γ_1(G) ⊇ γ_2(G) ⊇ ... until stabilization.

    γ_1(G) = G, γ_{n+1}(G) = [γ_n(G), G].
    """
    top = frozenset(range(g.n))
    series = [top]
    current = top
    for _ in range(max_steps):
        next_term = g.commutator_subgroup(current, top)
        series.append(next_term)
        if next_term == current:
            break
        current = next_term
    return series


def derived_depth(g: FiniteGroup) -> Optional[int]:
    """Compute the derived depth of G (None if not solvable)."""
    series = derived_series(g)
    trivial = frozenset([0])
    for i, term in enumerate(series):
        if term == trivial:
            return i
    return None


def is_solvable(g: FiniteGroup) -> bool:
    """Check if G is solvable."""
    return derived_depth(g) is not None


def is_nilpotent(g: FiniteGroup) -> bool:
    """Check if G is nilpotent."""
    series = lower_central_series(g)
    trivial = frozenset([0])
    return any(term == trivial for term in series)


def all_subgroups(g: FiniteGroup) -> List[FrozenSet[Element]]:
    """Enumerate all subgroups of G (brute force for small groups)."""
    subgroups: Set[FrozenSet[Element]] = set()
    subgroups.add(frozenset([0]))
    subgroups.add(frozenset(range(g.n)))
    for a in range(g.n):
        subgroups.add(g.subgroup_generated_by({a}))
    for a in range(g.n):
        for b in range(a + 1, g.n):
            subgroups.add(g.subgroup_generated_by({a, b}))
    return list(subgroups)


def minimal_normal_subgroups(g: FiniteGroup) -> List[FrozenSet[Element]]:
    """Find all minimal normal subgroups of G."""
    normal_subs = [s for s in all_subgroups(g) if g.is_normal(s) and len(s) > 1]
    minimal: List[FrozenSet[Element]] = []
    for n_sub in normal_subs:
        is_minimal = True
        for other in normal_subs:
            if other < n_sub and len(other) > 1:
                is_minimal = False
                break
        if is_minimal:
            minimal.append(n_sub)
    return minimal


def group_valence(g: FiniteGroup) -> int:
    """Compute the group valence (number of minimal normal subgroups)."""
    return len(minimal_normal_subgroups(g))


def omega(n: int) -> int:
    """Compute Ω(n) = number of prime factors of n with multiplicity."""
    if n <= 1:
        return 0
    count = 0
    d = 2
    while d * d <= n:
        while n % d == 0:
            count += 1
            n //= d
        d += 1
    if n > 1:
        count += 1
    return count


def prime_factorization(n: int) -> Dict[int, int]:
    """Compute the prime factorization of n."""
    factors: Dict[int, int] = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors[d] = factors.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        factors[n] = factors.get(n, 0) + 1
    return factors


class PeriodicTableEntry:
    """A periodic table entry for a finite group."""

    def __init__(self, g: FiniteGroup) -> None:
        self.name = g.name
        self.order = g.order()
        self.period = derived_depth(g)  # None if not solvable
        self.valence = group_valence(g)
        self.center_order = len(g.center())
        self.solvable = is_solvable(g)
        self.nilpotent = is_nilpotent(g)
        self.omega = omega(self.order)
        self.prime_factors = prime_factorization(self.order)

    def verify_periodic_law(self) -> Optional[bool]:
        """Verify the Quantitative Periodic Law: d(G) ≤ Ω(|G|)."""
        if self.period is None:
            return None  # Not solvable
        return self.period <= self.omega

    def __repr__(self) -> str:
        sol_str = "solvable" if self.solvable else "non-solvable"
        nil_str = ", nilpotent" if self.nilpotent else ""
        return (
            f"PeriodicTableEntry({self.name}: order={self.order}, "
            f"period={self.period}, valence={self.valence}, "
            f"|Z|={self.center_order}, {sol_str}{nil_str})"
        )


# --- Standard group constructors ---

def cyclic_group(n: int) -> FiniteGroup:
    """Construct the cyclic group Z/nZ."""
    table = [[(i + j) % n for j in range(n)] for i in range(n)]
    return FiniteGroup(table, f"Z/{n}Z")


def symmetric_group_3() -> FiniteGroup:
    """Construct S₃ (symmetric group on 3 elements).

    Elements: 0=e, 1=(12), 2=(13), 3=(23), 4=(123), 5=(132)
    """
    # Cayley table for S3
    table = [
        [0, 1, 2, 3, 4, 5],
        [1, 0, 4, 5, 2, 3],
        [2, 5, 0, 4, 3, 1],
        [3, 4, 5, 0, 1, 2],
        [4, 3, 1, 2, 5, 0],
        [5, 2, 3, 1, 0, 4],
    ]
    return FiniteGroup(table, "S₃")


def klein_four() -> FiniteGroup:
    """Construct the Klein four-group V₄ ≅ Z/2Z × Z/2Z."""
    table = [
        [0, 1, 2, 3],
        [1, 0, 3, 2],
        [2, 3, 0, 1],
        [3, 2, 1, 0],
    ]
    return FiniteGroup(table, "V₄")


def direct_product(g: FiniteGroup, h: FiniteGroup) -> FiniteGroup:
    """Construct the direct product G × H."""
    n = g.n * h.n
    table = [[0] * n for _ in range(n)]
    for (a1, a2) in cartesian_product(range(g.n), range(h.n)):
        for (b1, b2) in cartesian_product(range(g.n), range(h.n)):
            i = a1 * h.n + a2
            j = b1 * h.n + b2
            c1 = g.mul(a1, b1)
            c2 = h.mul(a2, b2)
            table[i][j] = c1 * h.n + c2
    return FiniteGroup(table, f"{g.name} × {h.name}")
