/-
# The Unary Sheffer Function: Formal Foundations

This file formalizes the core mathematical theory underlying the
Unary Sheffer Function concept — a single univariate function σ that,
composed with affine transformations, can generate (approximate)
all elementary functions.

## Main Results

1. **Polynomial Limitation Theorem**: Polynomial activations cannot escape
   the polynomial class — any composition of a degree-d polynomial with
   affine maps yields a polynomial of degree ≤ d^n (after n compositions).

2. **Softplus Properties**: The softplus function σ(x) = log(1 + exp(x))
   is smooth, monotone, and exhibits both exponential and linear regimes.

3. **Exponential Approximation**: For large shift parameter c,
   exp(c) · softplus(x - c) approximates exp(x) on compact intervals.

4. **Composition Algebra Structure**: The set of functions generated by
   composing σ with affine maps forms a monoid under composition.
-/

import Mathlib

open Real

/-! ## Part 1: The Polynomial Limitation Theorem

If σ is a polynomial, then any finite composition of σ with affine maps
is again a polynomial. This proves that non-polynomial activations are
*necessary* for generating non-polynomial functions. -/

/-- Composition of a polynomial with an affine function yields a polynomial. -/
theorem Polynomial.comp_affine_is_poly {R : Type*} [CommRing R]
    (p : Polynomial R) (a b : R) :
    ∃ q : Polynomial R, ∀ x : R, q.eval x = p.eval (a * x + b) := by
  exact ⟨p.comp (Polynomial.C a * Polynomial.X + Polynomial.C b), fun x => by simp [Polynomial.eval_comp]⟩

/-
The degree of a polynomial composed with an affine map is bounded
    by the degree of the original polynomial.
-/
theorem Polynomial.degree_comp_affine_le {R : Type*} [CommRing R] [NoZeroDivisors R]
    (p : Polynomial R) (a b : R) :
    (p.comp (Polynomial.C a * Polynomial.X + Polynomial.C b)).natDegree ≤ p.natDegree := by
  by_cases ha : a = 0;
  · by_cases hp : p = 0 <;> simp +decide [ ha, hp ];
  · simp +decide [ Polynomial.natDegree_comp, Polynomial.natDegree_add_eq_left_of_natDegree_lt, ha ]

/-- If σ is a degree-d polynomial and A is affine, then σ ∘ A is
    a polynomial of degree ≤ d. Iterating n times, the degree stays ≤ d.
    This means polynomial activations can never produce functions of
    higher complexity — the fundamental limitation. -/
theorem poly_activation_stays_poly (p : Polynomial ℝ) (a b : ℝ) :
    ∃ q : Polynomial ℝ, q.natDegree ≤ p.natDegree ∧
    ∀ x : ℝ, q.eval x = p.eval (a * x + b) := by
  exact ⟨p.comp (Polynomial.C a * Polynomial.X + Polynomial.C b),
    Polynomial.degree_comp_affine_le p a b,
    fun x => by simp [Polynomial.eval_comp]⟩

/-! ## Part 2: Softplus — The Candidate Sheffer Function

The softplus function σ(x) = log(1 + exp(x)) is our primary candidate
for the Unary Sheffer Function. We establish its key analytic properties. -/

/-- The softplus function: σ(x) = log(1 + exp(x)) -/
noncomputable def softplus (x : ℝ) : ℝ := Real.log (1 + Real.exp x)

/-
1 + exp(x) > 0 for all x, the key positivity lemma for softplus.
-/
theorem one_plus_exp_pos (x : ℝ) : (1 : ℝ) + Real.exp x > 0 := by
  positivity

/-
Softplus is strictly positive for all x.
-/
theorem softplus_pos (x : ℝ) : softplus x > 0 := by
  exact Real.log_pos ( by linarith [ Real.exp_pos x ] )

/-
Softplus is strictly monotone increasing.
-/
theorem softplus_strictMono : StrictMono softplus := by
  exact fun x y hxy => Real.log_lt_log ( by positivity ) ( by linarith [ Real.exp_lt_exp.2 hxy ] )

/-
Softplus satisfies the identity: softplus(x) = x + softplus(-x).
    This is equivalent to log(1 + e^x) = x + log(1 + e^{-x}).
-/
theorem softplus_reflection (x : ℝ) : softplus x = x + softplus (-x) := by
  unfold softplus;
  rw [ ← Real.log_exp x, ← Real.log_mul ( by positivity ) ( by positivity ), mul_add, ← Real.exp_add ] ; norm_num ; ring;

/-
The derivative of softplus is the sigmoid function.
-/
theorem softplus_deriv (x : ℝ) :
    HasDerivAt softplus (Real.exp x / (1 + Real.exp x)) x := by
  convert HasDerivAt.log ( HasDerivAt.add ( hasDerivAt_const _ _ ) ( Real.hasDerivAt_exp x ) ) _ using 1 <;> norm_num;
  positivity

/-
Softplus is differentiable everywhere.
-/
theorem softplus_differentiable : Differentiable ℝ softplus := by
  exact fun _ => ( softplus_deriv _ ) |> HasDerivAt.differentiableAt

/-
Lower bound: softplus(x) ≥ 0 for all x (trivially, since log(1+e^x) ≥ log(1) = 0).
-/
theorem softplus_nonneg (x : ℝ) : softplus x ≥ 0 := by
  exact le_of_lt ( softplus_pos x )

/-
Upper bound in the exponential regime: for x ≤ 0, softplus(x) ≤ exp(x).
-/
theorem softplus_le_exp_of_nonpos (x : ℝ) (_hx : x ≤ 0) : softplus x ≤ Real.exp x := by
  exact le_trans ( Real.log_le_sub_one_of_pos ( by positivity ) ) ( by norm_num )

/-
Lower bound in the linear regime: softplus(x) ≥ x for all x
    (since log(1 + e^x) ≥ log(e^x) = x).
-/
theorem softplus_ge_id (x : ℝ) : softplus x ≥ x := by
  have h_exp : Real.exp x ≤ 1 + Real.exp x := by
    linarith;
  exact Real.le_log_iff_exp_le ( by positivity ) |>.2 h_exp

/-
Softplus at zero equals log 2.
-/
theorem softplus_zero : softplus 0 = Real.log 2 := by
  unfold softplus; norm_num;

/-! ## Part 3: Exponential Approximation Theorem

The key result: softplus can approximate the exponential function
through affine pre/post-composition. Specifically:
  exp(c) · softplus(x - c) → exp(x) as c → ∞
on any compact interval. -/

/-
For any x, the shifted softplus exp(c) · softplus(x - c)
    converges to exp(x) as c → ∞. This is the pointwise version.
-/
theorem softplus_approx_exp_pointwise (x : ℝ) :
    Filter.Tendsto (fun c => Real.exp c * softplus (x - c)) Filter.atTop
      (nhds (Real.exp x)) := by
  -- Set $u(c) = \exp(x-c)$. As $c \to \infty$, $u \to 0$.
  set u : ℝ → ℝ := fun c => Real.exp (x - c)
  have hu_tendsto_zero : Filter.Tendsto u Filter.atTop (nhds 0) := by
    exact Real.tendsto_exp_atBot.comp <| Filter.tendsto_atTop_atBot.mpr fun y => ⟨ x - y, fun z hz => by linarith ⟩;
  -- We need to show that $\lim_{c \to \infty} \frac{\log(1 + u(c))}{u(c)} = 1$.
  have h_log_lim : Filter.Tendsto (fun c => (Real.log (1 + u c)) / u c) Filter.atTop (nhds 1) := by
    have h_log_lim : Filter.Tendsto (fun u => Real.log (1 + u) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
      simpa [ div_eq_inv_mul ] using Real.hasDerivAt_log one_ne_zero |> HasDerivAt.tendsto_slope_zero_right;
    refine h_log_lim.comp <| Filter.tendsto_inf.mpr ⟨ hu_tendsto_zero, Filter.tendsto_principal.mpr <| Filter.Eventually.of_forall fun c => Real.exp_pos _ ⟩;
  convert h_log_lim.const_mul ( Real.exp x ) using 2 <;> norm_num [ softplus ] ; ring;
  rw [ ← div_eq_mul_inv, eq_div_iff ] <;> first | positivity | rw [ show x = x - ‹ℝ› + ‹ℝ› by ring, Real.exp_add ] ; ring;
  ring!

/-! ## Part 4: Composition Algebra Structure

The functions generated by composing softplus with affine maps
form a structured algebraic object. -/

/-- An affine-softplus expression: either an affine function, or a composition
    of softplus with affine-softplus expressions. -/
inductive ShefferExpr : Type where
  | affine : ℝ → ℝ → ShefferExpr         -- ax + b
  | activate : ShefferExpr → ShefferExpr   -- σ(·)
  | comp : ShefferExpr → ShefferExpr → ShefferExpr  -- f ∘ g

/-- Evaluate a Sheffer expression at a point. -/
noncomputable def ShefferExpr.eval : ShefferExpr → ℝ → ℝ
  | .affine a b => fun x => a * x + b
  | .activate e => fun x => softplus (e.eval x)
  | .comp f g => fun x => f.eval (g.eval x)

/-
Every Sheffer expression produces a differentiable function.
-/
theorem ShefferExpr.differentiable (e : ShefferExpr) :
    Differentiable ℝ e.eval := by
  induction e;
  · exact differentiable_id.const_mul _ |> Differentiable.add <| differentiable_const _;
  · exact Differentiable.comp ( show Differentiable ℝ ( fun x => Real.log ( 1 + Real.exp x ) ) by exact Differentiable.log ( by norm_num [ Real.differentiable_exp ] ) fun x => by positivity ) ‹_›;
  · exact Differentiable.comp ‹_› ‹_›

/-
The composition of two differentiable Sheffer expressions is differentiable.
-/
theorem ShefferExpr.comp_differentiable (f g : ShefferExpr) :
    Differentiable ℝ (ShefferExpr.comp f g).eval := by
  exact f.differentiable.comp g.differentiable

/-! ## Part 5: Non-Polynomial Theorem

Softplus is not a polynomial — this is essential for escaping
the polynomial limitation. -/

/-
Softplus is not equal to any polynomial function on ℝ.
    Proof idea: A polynomial of degree d grows like x^d, but
    softplus grows linearly. More precisely, softplus is bounded
    below by 0 and above by x + log(2) for x ≥ 0, so it would
    have to be degree 1, but no degree-1 polynomial matches softplus
    (since softplus(x) → 0⁺ as x → -∞, while ax+b → -∞).
-/
theorem softplus_not_polynomial :
    ¬ ∃ (p : Polynomial ℝ), ∀ x : ℝ, p.eval x = softplus x := by
  -- Assume for contradiction that there exists a polynomial p such that p.eval x = softplus x for all x.
  by_contra h
  obtain ⟨p, hp⟩ := h

  -- Since softplus is strictly positive and grows linearly for large x, the polynomial p must also be strictly positive and grow linearly.
  have h_pos : ∀ x, 0 < p.eval x := by
    exact fun x => hp x ▸ softplus_pos x
  have h_linear : Filter.Tendsto (fun x => p.eval x) Filter.atBot (nhds 0) := by
    simp_all +decide [ softplus ];
    convert Filter.Tendsto.log ( tendsto_const_nhds.add ( Real.tendsto_exp_atBot ) ) _ using 2 <;> norm_num;
  -- Since p is a polynomial of degree d ≥ 2, it must grow without bound as x goes to negative infinity.
  have h_poly_growth : Filter.Tendsto (fun x => |p.eval x|) Filter.atBot Filter.atTop := by
    have h_poly_growth : Filter.Tendsto (fun x => |p.eval (-x)|) Filter.atTop Filter.atTop := by
      have h_poly_growth : Polynomial.degree (p.comp (Polynomial.X * -1)) > 0 := by
        by_cases h_const : p.natDegree = 0;
        · rw [ Polynomial.eq_C_of_natDegree_eq_zero h_const ] at hp h_pos h_linear ; aesop;
        · rw [ Polynomial.degree_eq_natDegree ] <;> norm_num [ Polynomial.natDegree_comp, Polynomial.natDegree_mul', h_const ];
          · exact Nat.pos_of_ne_zero h_const;
          · aesop;
      have := Polynomial.abs_tendsto_atTop ( p.comp ( Polynomial.X * -1 ) ) ; aesop;
    convert h_poly_growth.comp Filter.tendsto_neg_atBot_atTop using 2 ; norm_num;
  exact not_tendsto_atTop_of_tendsto_nhds ( h_linear.abs ) h_poly_growth