/-
# Hilbert class fields of a field with Klein four class group

`Catalog/NumberTheory/HilbertClassFieldDescent.lean` classifies the intermediate fields of a
Hilbert class field datum `e : Gal(H/K) ≃* Cl(𝒪_K)` by the subgroups of the ideal class group.
`Catalog/NumberTheory/CyclicClassGroupDescent.lean` makes this explicit when `Cl(𝒪_K)` is cyclic.
This file settles the smallest non-cyclic case, `Cl(𝒪_K) ≃ ℤ/2 × ℤ/2` (which occurs e.g. for
`K = ℚ(√-21)`, of class number `4`):

* `card_subgroup_V` : the Klein four group has exactly five subgroups;
* `card_intermediateField_of_kleinFour` : a Hilbert class field datum for a field with Klein four
  class group has exactly five intermediate fields;
* `finrank_eq_one_or_two_or_four` : each of them has degree `1`, `2` or `4` over `K`;
* `exists_three_quadratic_intermediateField` : exactly three of them are quadratic, and together
  with `K` itself and `H` these are all of them
  (`intermediateField_eq_of_kleinFour`).

Together these confirm the predicted degree multiset `{1, 2, 2, 2, 4}`.
-/

import Catalog.NumberTheory.HilbertClassFieldDescent

open NumberField

namespace KleinFourClassField

/-- The Klein four group, written multiplicatively. -/
abbrev V := Multiplicative (ZMod 2 × ZMod 2)

/-- The first nontrivial element of the Klein four group. -/
def va : V := Multiplicative.ofAdd ((1, 0) : ZMod 2 × ZMod 2)

/-- The second nontrivial element of the Klein four group. -/
def vb : V := Multiplicative.ofAdd ((0, 1) : ZMod 2 × ZMod 2)

/-- The third nontrivial element of the Klein four group. -/
def vc : V := Multiplicative.ofAdd ((1, 1) : ZMod 2 × ZMod 2)

theorem V_cases (x : V) : x = 1 ∨ x = va ∨ x = vb ∨ x = vc := by
  revert x; decide

theorem V_mul_self (x : V) : x * x = 1 := by
  revert x; decide

theorem card_V : Nat.card V = 4 := by
  rw [Nat.card_eq_fintype_card]; decide

theorem va_ne_one : va ≠ 1 := by decide

theorem vb_ne_one : vb ≠ 1 := by decide

theorem vc_ne_one : vc ≠ 1 := by decide

theorem va_mul_vb : va * vb = vc := by decide

theorem va_mul_vc : va * vc = vb := by decide

theorem vb_mul_vc : vb * vc = va := by decide

/-- The order-two subgroup generated by a nontrivial element of `V` consists of `1` and that
element. -/
theorem mem_zpowers_iff {x : V} (hx : x ≠ 1) (y : V) :
    y ∈ Subgroup.zpowers x ↔ y = 1 ∨ y = x := by
  unfold Subgroup.zpowers
  simp
  constructor
  · rintro ⟨n, rfl⟩
    have hx2 : x ^ (2 : ℤ) = 1 := by rw [show (2 : ℤ) = 1 + 1 by decide, zpow_add, V_mul_self]
    rw [← Int.emod_add_mul_ediv n 2]
    rw [zpow_add, zpow_mul]
    simp_all
    have hmod : n % 2 = 0 ∨ n % 2 = 1 := by omega
    rcases hmod with h | h <;> [left; right] <;> rw [h] <;> simp
  · rintro (rfl | rfl)
    · exact ⟨0, by simp⟩
    · exact ⟨1, by simp⟩

theorem card_zpowers {x : V} (hx : x ≠ 1) : Nat.card (Subgroup.zpowers x) = 2 := by
  rw [Nat.card_zpowers]
  have h2 : x ^ 2 = 1 := by rw [pow_two]; exact V_mul_self x
  exact orderOf_eq_prime h2 hx

/-- **Classification of the subgroups of the Klein four group.** -/
theorem subgroup_cases (S : Subgroup V) :
    S = ⊥ ∨ S = Subgroup.zpowers va ∨ S = Subgroup.zpowers vb ∨
      S = Subgroup.zpowers vc ∨ S = ⊤ := by
  classical
  have hV : Nat.card V = 4 := card_V
  have hS_dvd : Nat.card S ∣ 4 := by rw [← hV]; exact Subgroup.card_subgroup_dvd_card S
  have hS_le : Nat.card S ≤ 4 := Nat.le_of_dvd (by norm_num) hS_dvd
  have hne0 : Nat.card S ≠ 0 := Nat.ne_of_gt (Nat.pos_of_dvd_of_pos hS_dvd (by norm_num : 0 < 4))
  match hn : Nat.card S with
  | 0 => contradiction
  | 1 =>
    left
    have hset : (S : Set V) = {1} := by
      rw [Set.eq_singleton_iff_unique_mem]
      refine ⟨S.one_mem, fun x hx => ?_⟩
      by_contra hne
      have htwo : 2 ≤ Nat.card S := by
        have h1 : ({1, x} : Set V) ⊆ (S : Set V) := by
          intro y hy
          simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
          exact hy.elim (fun h => by rw [h]; exact S.one_mem) (fun h => by rw [h]; exact hx)
        have h2 : Set.ncard ({1, x} : Set V) = 2 := Set.ncard_pair (Ne.symm hne)
        have h3 : Set.ncard (S : Set V) = Nat.card S := by
          rw [Set.ncard_eq_toFinset_card']
          simp [Nat.card_eq_fintype_card]
        linarith [Set.ncard_le_ncard h1, h3]
      omega
    exact Subgroup.ext fun x => by rw [Set.ext_iff] at hset; simpa using hset x
  | 2 =>
    -- S has exactly 2 elements: 1 and some non-identity element
    -- Find an element different from 1
    have hS_ne_top : S ≠ ⊤ := by
      intro h
      rw [h] at hn
      simp at hn
    have ⟨x, hxS, hxne⟩ : ∃ x : V, x ∈ S ∧ x ≠ 1 := by
      by_contra h
      push_neg at h
      have : (S : Set V) = {1} := by
        ext y; simp [Set.mem_singleton_iff]; exact ⟨h y, fun h => h.symm ▸ S.one_mem⟩
      have hSbot : S = ⊥ := by
        apply Subgroup.ext
        simp only [Subgroup.mem_bot]
        intro y
        have := Set.ext_iff.mp this y
        simp at this
        exact this
      simp [hSbot] at hn
    -- x has order 2, so S = zpowers x
    have hx2 : x * x = 1 := V_mul_self x
    have hSzp : S = Subgroup.zpowers x := by
      apply le_antisymm
      · intro y hy
        by_contra hny
        -- If y ∉ zpowers x = {1, x}, then y ≠ 1 and y ≠ x
        have hy1 : y ≠ 1 := fun h => by simp [h] at hny
        have hyx : y ≠ x := fun h => hny (h ▸ Subgroup.mem_zpowers x)
        -- So {1, x, y} ⊆ S with 3 distinct elements
        have hsub : ({1, x, y} : Set V) ⊆ (S : Set V) := by
          intro z hz
          simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
          rcases hz with rfl | rfl | rfl <;> [exact S.one_mem; exact hxS; exact hy]
        have hcard3 : ({1, x, y} : Set V).ncard = 3 := by
          rw [Set.ncard_eq_toFinset_card']
          simp only [Set.toFinset_insert, Set.toFinset_singleton]
          rw [Finset.card_insert_of_notMem (by simp [hxne.symm, hy1.symm]),
              Finset.card_insert_of_notMem (by simp [hyx.symm]),
              Finset.card_singleton]
        have hSncard : (S : Set V).ncard = 2 := by
          rw [Set.ncard_eq_toFinset_card']
          rw [Set.toFinset_card]
          rwa [Nat.card_eq_fintype_card] at hn
        have := Set.ncard_le_ncard hsub
        omega
      · exact Subgroup.zpowers_le.mpr hxS
    -- Now determine which of va, vb, vc equals x
    rcases V_cases x with rfl | rfl | rfl | rfl
    · exact absurd rfl hxne
    · right; left; exact hSzp
    · right; right; left; exact hSzp
    · right; right; right; left; exact hSzp
  | 3 =>
    have : 3 ∣ 4 := hn ▸ hS_dvd
    norm_num at this
  | 4 =>
    right; right; right; right
    exact Subgroup.eq_top_of_card_eq S (by rw [hn, hV])
  | _ + 5 => omega

theorem zpowers_va_ne_zpowers_vb : Subgroup.zpowers va ≠ Subgroup.zpowers vb := by
  intro h
  have hmem : va ∈ Subgroup.zpowers vb := h ▸ Subgroup.mem_zpowers va
  rcases (mem_zpowers_iff vb_ne_one va).1 hmem with h1 | h1 <;> revert h1 <;> decide

theorem zpowers_va_ne_zpowers_vc : Subgroup.zpowers va ≠ Subgroup.zpowers vc := by
  intro h
  have hmem : va ∈ Subgroup.zpowers vc := h ▸ Subgroup.mem_zpowers va
  rcases (mem_zpowers_iff vc_ne_one va).1 hmem with h1 | h1 <;> revert h1 <;> decide

theorem zpowers_vb_ne_zpowers_vc : Subgroup.zpowers vb ≠ Subgroup.zpowers vc := by
  intro h
  have hmem : vb ∈ Subgroup.zpowers vc := h ▸ Subgroup.mem_zpowers vb
  rcases (mem_zpowers_iff vc_ne_one vb).1 hmem with h1 | h1 <;> revert h1 <;> decide

theorem zpowers_ne_bot {x : V} (hx : x ≠ 1) : Subgroup.zpowers x ≠ ⊥ := by
  intro h
  exact hx (by simpa [h] using Subgroup.mem_zpowers x)

theorem zpowers_ne_top {x : V} (hx : x ≠ 1) : Subgroup.zpowers x ≠ ⊤ := by
  intro h
  have h1 : Nat.card (Subgroup.zpowers x) = 2 := card_zpowers hx
  rw [h] at h1
  have h4 : Nat.card (⊤ : Subgroup V) = 4 := by
    rw [Nat.card_congr (Subgroup.topEquiv (G := V)).toEquiv]; exact card_V
  omega

theorem bot_ne_top_V : (⊥ : Subgroup V) ≠ ⊤ := by
  intro h
  have hmem : va ∈ (⊥ : Subgroup V) := by rw [h]; exact Subgroup.mem_top va
  exact va_ne_one (by simpa using hmem)

/-- **The Klein four group has exactly five subgroups.** -/
theorem card_subgroup_V : Nat.card (Subgroup V) = 5 := by
  have h := subgroup_cases
  have h1 : (⊥ : Subgroup V) ≠ Subgroup.zpowers va := (zpowers_ne_bot va_ne_one).symm
  have h2 : (⊥ : Subgroup V) ≠ Subgroup.zpowers vb := (zpowers_ne_bot vb_ne_one).symm
  have h3 : (⊥ : Subgroup V) ≠ Subgroup.zpowers vc := (zpowers_ne_bot vc_ne_one).symm
  have h4 : (⊥ : Subgroup V) ≠ ⊤ := bot_ne_top_V
  have h5 : Subgroup.zpowers va ≠ Subgroup.zpowers vb := zpowers_va_ne_zpowers_vb
  have h6 : Subgroup.zpowers va ≠ Subgroup.zpowers vc := zpowers_va_ne_zpowers_vc
  have h7 : Subgroup.zpowers va ≠ ⊤ := zpowers_ne_top va_ne_one
  have h8 : Subgroup.zpowers vb ≠ Subgroup.zpowers vc := zpowers_vb_ne_zpowers_vc
  have h9 : Subgroup.zpowers vb ≠ ⊤ := zpowers_ne_top vb_ne_one
  have h10 : Subgroup.zpowers vc ≠ ⊤ := zpowers_ne_top vc_ne_one
  have hfin : (Set.univ : Set (Subgroup V)).Finite := Set.finite_univ
  have hset : (Set.univ : Set (Subgroup V)) = {⊥, Subgroup.zpowers va, Subgroup.zpowers vb, Subgroup.zpowers vc, ⊤} := by
    ext S
    simp [h S]
  -- Use the classification to build a bijection with a 5-element type
  let g : Fin 5 → Subgroup V := fun n =>
    match n with
    | 0 => (⊥ : Subgroup V)
    | 1 => Subgroup.zpowers va
    | 2 => Subgroup.zpowers vb
    | 3 => Subgroup.zpowers vc
    | 4 => ⊤
  have hsurj : Function.Surjective g := by
    intro S
    rcases h S with hS | hS | hS | hS | hS
    · exact ⟨0, hS.symm⟩
    · exact ⟨1, hS.symm⟩
    · exact ⟨2, hS.symm⟩
    · exact ⟨3, hS.symm⟩
    · exact ⟨4, hS.symm⟩
  have hinj : Function.Injective g := by
    intro a b hab
    fin_cases a <;> fin_cases b <;> simp_all [g]
  have hbij : Function.Bijective g := ⟨hinj, hsurj⟩
  rw [← Nat.card_congr (Equiv.ofBijective g hbij), Nat.card_fin]

/-- The index of a subgroup of `V` is `4`, `2` or `1`. -/
theorem index_cases (S : Subgroup V) : S.index = 4 ∨ S.index = 2 ∨ S.index = 1 := by
  have h := Subgroup.card_mul_index S
  have hV : Nat.card V = 4 := card_V
  rw [hV] at h
  have hind_dvd : S.index ∣ 4 := h ▸ dvd_mul_left _ _
  have hle : S.index ≤ 4 := Nat.le_of_dvd (by norm_num) hind_dvd
  interval_cases S.index <;> simp_all

section ClassField

variable (K : Type*) [Field K] [NumberField K]
  (H : Type*) [Field H] [Algebra K H] [FiniteDimensional K H] [IsGalois K H]
  (e : (H ≃ₐ[K] H) ≃* ClassGroup (RingOfIntegers K))
  (E : ClassGroup (RingOfIntegers K) ≃* V)

include e E in
/-- **Five intermediate fields.**  If the class group of `K` is a Klein four group, then a
Hilbert class field datum for `K` has exactly five intermediate fields. -/
theorem card_intermediateField_of_kleinFour :
    Nat.card (IntermediateField K H) = 5 := by
  rw [HilbertClassFieldDescent.card_intermediateField_eq_card_subgroup K H e,
    Nat.card_congr (MulEquiv.mapSubgroup E).toEquiv, card_subgroup_V]

include e E in
/-- **The possible degrees.**  Every intermediate field of the datum has degree `1`, `2` or `4`
over `K`. -/
theorem finrank_eq_one_or_two_or_four (L : IntermediateField K H) :
    Module.finrank K L = 1 ∨ Module.finrank K L = 2 ∨ Module.finrank K L = 4 := by
  have hidx : Module.finrank K L
      = ((HilbertClassFieldDescent.artinImage K H e L).map E.toMonoidHom).index := by
    rw [HilbertClassFieldDescent.finrank_eq_index K H e L]
    exact (Subgroup.index_map_of_bijective (f := E.toMonoidHom) E.bijective _).symm
  have := index_cases ((HilbertClassFieldDescent.artinImage K H e L).map E.toMonoidHom)
  omega

/-- The class field attached to the subgroup of `Cl(𝒪_K)` corresponding to `x ∈ V`. -/
noncomputable def quadField (x : V) : IntermediateField K H :=
  HilbertClassFieldDescent.classField K H e
    ((Subgroup.zpowers x).comap E.toMonoidHom)

omit [NumberField K] in
/-- The index in the class group of the preimage of a subgroup of `V` equals its index in `V`. -/
theorem index_comap_equiv (S : Subgroup V) : (S.comap E.toMonoidHom).index = S.index :=
  Subgroup.index_comap_of_surjective S E.surjective

theorem finrank_quadField {x : V} (hx : x ≠ 1) :
    Module.finrank K (quadField K H e E x) = 2 := by
  have hcard : Nat.card (Subgroup.zpowers x) = 2 := card_zpowers hx
  have hmul : Nat.card (Subgroup.zpowers x) * (Subgroup.zpowers x).index = Nat.card V :=
    Subgroup.card_mul_index _
  rw [hcard, card_V] at hmul
  rw [quadField, HilbertClassFieldDescent.finrank_classField K H e, index_comap_equiv K E]
  omega

theorem quadField_injective {x y : V} (hx : x ≠ 1) (hy : y ≠ 1)
    (h : quadField K H e E x = quadField K H e E y) : x = y := by
  have h1 : (Subgroup.zpowers x).comap E.toMonoidHom
      = (Subgroup.zpowers y).comap E.toMonoidHom := by
    have := congrArg (HilbertClassFieldDescent.artinImage K H e) h
    rwa [quadField, quadField, HilbertClassFieldDescent.artinImage_classField,
      HilbertClassFieldDescent.artinImage_classField] at this
  have h2 : Subgroup.zpowers x = Subgroup.zpowers y :=
    (MulEquiv.comapSubgroup E).injective h1
  have hmem : x ∈ Subgroup.zpowers y := h2 ▸ Subgroup.mem_zpowers x
  rcases (mem_zpowers_iff hy x).1 hmem with h3 | h3
  · exact absurd h3 hx
  · exact h3

include e E in
/-- **Three quadratic intermediate fields.**  A Hilbert class field datum for a field with Klein
four class group has three pairwise distinct quadratic intermediate fields. -/
theorem exists_three_quadratic_intermediateField :
    ∃ L₁ L₂ L₃ : IntermediateField K H,
      L₁ ≠ L₂ ∧ L₁ ≠ L₃ ∧ L₂ ≠ L₃ ∧
      Module.finrank K L₁ = 2 ∧ Module.finrank K L₂ = 2 ∧ Module.finrank K L₃ = 2 := by
  refine ⟨quadField K H e E va, quadField K H e E vb, quadField K H e E vc, ?_, ?_, ?_,
    finrank_quadField K H e E va_ne_one, finrank_quadField K H e E vb_ne_one,
    finrank_quadField K H e E vc_ne_one⟩
  · intro h; exact absurd (quadField_injective K H e E va_ne_one vb_ne_one h) (by decide)
  · intro h; exact absurd (quadField_injective K H e E va_ne_one vc_ne_one h) (by decide)
  · intro h; exact absurd (quadField_injective K H e E vb_ne_one vc_ne_one h) (by decide)

/-- **Complete list of intermediate fields.**  Every intermediate field of the datum is `K`, `H`,
or one of the three quadratic class fields. -/
theorem intermediateField_eq_of_kleinFour (L : IntermediateField K H) :
    L = ⊥ ∨ L = quadField K H e E va ∨ L = quadField K H e E vb ∨
      L = quadField K H e E vc ∨ L = ⊤ := by
  have hbot : HilbertClassFieldDescent.artinImage K H e ⊥ = ⊤ := by
    rw [← HilbertClassFieldDescent.ofDual_intermediateFieldOrderIso_apply K H e]
    simp
  have htop : HilbertClassFieldDescent.artinImage K H e ⊤ = ⊥ := by
    rw [← HilbertClassFieldDescent.ofDual_intermediateFieldOrderIso_apply K H e]
    simp
  have hquad : ∀ x : V, HilbertClassFieldDescent.artinImage K H e (quadField K H e E x)
      = (Subgroup.zpowers x).comap E.toMonoidHom := fun x => by
    rw [quadField, HilbertClassFieldDescent.artinImage_classField]
  set S := HilbertClassFieldDescent.artinImage K H e L with hS
  have hSeq : S = (S.map E.toMonoidHom).comap E.toMonoidHom :=
    (Subgroup.comap_map_eq_self_of_injective E.injective S).symm
  rcases subgroup_cases (S.map E.toMonoidHom) with hT | hT | hT | hT | hT
  · refine Or.inr (Or.inr (Or.inr (Or.inr ?_)))
    refine HilbertClassFieldDescent.artinImage_injective K H e ?_
    rw [← hS, htop, hSeq, hT]
    ext c; simp
  · refine Or.inr (Or.inl (HilbertClassFieldDescent.artinImage_injective K H e ?_))
    rw [← hS, hquad, hSeq, hT]
  · refine Or.inr (Or.inr (Or.inl (HilbertClassFieldDescent.artinImage_injective K H e ?_)))
    rw [← hS, hquad, hSeq, hT]
  · refine Or.inr (Or.inr (Or.inr (Or.inl
      (HilbertClassFieldDescent.artinImage_injective K H e ?_))))
    rw [← hS, hquad, hSeq, hT]
  · refine Or.inl (HilbertClassFieldDescent.artinImage_injective K H e ?_)
    rw [← hS, hbot, hSeq, hT]
    ext c; simp

end ClassField

end KleinFourClassField