/-
# Locality ascent along a module-finite algebra

This file supplies the structural input demanded by conjecture **D2** of the Solomon-zeta
thread (`Catalog/Shared/SolomonZeta/`): a criterion for a *module-finite algebra over a local
ring* to be local, with no completeness, noetherianity or nilpotence hypothesis.

`Shared.SolomonZeta.GroupAlgebra` proves that a commutative ring with a maximal ideal all of
whose elements are nilpotent is local; that covers `𝔽_p[G]` but not `ℤ_p[G]`, where `p` itself
is not nilpotent.  The correct replacement is *nilpotence modulo the maximal ideal of the base*
together with module-finiteness, the missing invertibility being supplied by Nakayama's lemma:

* `SolomonZeta.isUnit_of_span_sup_map_maximalIdeal_eq_top` — if `xΛ + 𝔪_R Λ = Λ` and `Λ` is a
  module-finite algebra over the local ring `R`, then `x` is a unit of `Λ`;
* `SolomonZeta.isUnit_one_sub_of_pow_mem` — if some power of `a` lies in `𝔪_R Λ`, then `1 - a`
  is a unit (a geometric-series identity plus the previous item);
* `SolomonZeta.isLocalRing_of_isMaximal_of_pow_mem` — **locality ascent**: if `J ⊆ Λ` is a
  maximal ideal each of whose elements has a power in `𝔪_R Λ`, then `Λ` is local, and
  `SolomonZeta.maximalIdeal_eq_of_isMaximal_of_pow_mem` identifies `𝔪_Λ = J`.

The statement is sharp in the sense that both hypotheses are used: module-finiteness enters only
through Nakayama, and the `J`-elements' powers only through the geometric series.
-/
import Catalog.Shared.SolomonZeta.GroupAlgebra

namespace SolomonZeta

open IsLocalRing

variable {R Λ : Type*} [CommRing R] [IsLocalRing R] [CommRing Λ] [Algebra R Λ]
  [Module.Finite R Λ]

/-- **Nakayama's unit criterion.**  Let `Λ` be a module-finite algebra over a commutative local
ring `R`.  If the ideal generated by `x` together with `𝔪_R Λ` is all of `Λ`, then `x` is a
unit. -/
theorem isUnit_of_span_sup_map_maximalIdeal_eq_top {x : Λ}
    (h : Ideal.span {x} ⊔ (maximalIdeal R).map (algebraMap R Λ) = ⊤) : IsUnit x := by
  rw [← Ideal.span_singleton_eq_top, ← Submodule.restrictScalars_eq_top_iff (S := R)]
  have hmap : ∀ z : Λ, z ∈ (maximalIdeal R).map (algebraMap R Λ) →
      z ∈ (maximalIdeal R) • (⊤ : Submodule R Λ) := by
    intro z hz
    rw [Ideal.smul_top_eq_map]
    exact hz
  have hsub : (Ideal.span {x}).restrictScalars R ⊔ (maximalIdeal R) • (⊤ : Submodule R Λ) = ⊤ := by
    refine le_antisymm le_top fun y _ => ?_
    have h1 : (1 : Λ) ∈ Ideal.span {x} ⊔ (maximalIdeal R).map (algebraMap R Λ) :=
      h ▸ Submodule.mem_top
    rw [Submodule.mem_sup] at h1
    obtain ⟨u, hu, v, hv, huv⟩ := h1
    have hy : y = y * u + y * v := by rw [← mul_add, huv, mul_one]
    rw [hy]
    exact Submodule.add_mem _
      (Submodule.mem_sup_left (show y * u ∈ Ideal.span {x} from Ideal.mul_mem_left _ _ hu))
      (Submodule.mem_sup_right (hmap _ (Ideal.mul_mem_left _ _ hv)))
  rw [← IsLocalRing.map_mkQ_eq_top]
  have hbot : Submodule.map ((maximalIdeal R) • (⊤ : Submodule R Λ)).mkQ
      ((maximalIdeal R) • (⊤ : Submodule R Λ)) = ⊥ := by
    refine le_antisymm ?_ bot_le
    rintro _ ⟨z, hz, rfl⟩
    simpa using hz
  have hmapped := congrArg (Submodule.map ((maximalIdeal R) • (⊤ : Submodule R Λ)).mkQ) hsub
  rwa [Submodule.map_sup, Submodule.map_top, Submodule.range_mkQ, hbot, sup_bot_eq] at hmapped

/-- If some power of `a` lies in `𝔪_R Λ`, then `1 - a` is a unit of `Λ`: the geometric series
`(1-a)(1 + a + ⋯ + a^{N-1}) = 1 - a^N` puts `1` into `(1-a)Λ + 𝔪_R Λ`. -/
theorem isUnit_one_sub_of_pow_mem {a : Λ} {N : ℕ}
    (ha : a ^ N ∈ (maximalIdeal R).map (algebraMap R Λ)) : IsUnit (1 - a) := by
  refine isUnit_of_span_sup_map_maximalIdeal_eq_top (R := R) (eq_top_iff.2 ?_)
  rw [← Ideal.span_singleton_one, Ideal.span_le, Set.singleton_subset_iff]
  refine Submodule.mem_sup.2 ⟨(1 - a) * (∑ i ∈ Finset.range N, a ^ i),
    Ideal.mul_mem_right _ _ (Ideal.subset_span rfl), a ^ N, ha, ?_⟩
  rw [mul_neg_geom_sum]
  ring

/-- **Locality ascent.**  Let `R` be a commutative local ring and `Λ` a module-finite commutative
`R`-algebra.  If `Λ` has a maximal ideal `J` such that every element of `J` has some power in
`𝔪_R Λ` — i.e. `J/𝔪_R Λ` is a nil ideal of `Λ/𝔪_R Λ` — then `Λ` is local.

This is the non-nilpotent replacement of `SolomonZeta.isLocalRing_of_isMaximal_of_nil`: over
`R = ℤ_p` the element `p` is not nilpotent, but it lies in `𝔪_R Λ`, and Nakayama's lemma
supplies the invertibility that nilpotence used to supply. -/
theorem isLocalRing_of_isMaximal_of_pow_mem (J : Ideal Λ) (hJ : J.IsMaximal)
    (hpow : ∀ a ∈ J, ∃ N : ℕ, a ^ N ∈ (maximalIdeal R).map (algebraMap R Λ)) :
    IsLocalRing Λ := by
  haveI : Nontrivial Λ := by
    rcases subsingleton_or_nontrivial Λ with hs | hs
    · exact absurd ((Ideal.eq_top_iff_one J).2
        (by rw [Subsingleton.elim (1 : Λ) 0]; exact J.zero_mem)) hJ.ne_top
    · exact hs
  refine IsLocalRing.of_isUnit_or_isUnit_one_sub_self fun a => ?_
  by_cases ha : a ∈ J
  · obtain ⟨N, hN⟩ := hpow a ha
    exact Or.inr (isUnit_one_sub_of_pow_mem (R := R) hN)
  · obtain ⟨y, i, hi, hyi⟩ := hJ.exists_inv ha
    obtain ⟨N, hN⟩ := hpow i hi
    have h1 : y * a = 1 - i := by linear_combination hyi
    have hu : IsUnit (y * a) := by rw [h1]; exact isUnit_one_sub_of_pow_mem (R := R) hN
    exact Or.inl (isUnit_of_mul_isUnit_right hu)

/-- Under the hypotheses of `SolomonZeta.isLocalRing_of_isMaximal_of_pow_mem`, the maximal ideal
of `Λ` is `J`. -/
theorem maximalIdeal_eq_of_isMaximal_of_pow_mem (J : Ideal Λ) (hJ : J.IsMaximal)
    (hpow : ∀ a ∈ J, ∃ N : ℕ, a ^ N ∈ (maximalIdeal R).map (algebraMap R Λ)) :
    letI := isLocalRing_of_isMaximal_of_pow_mem J hJ hpow
    maximalIdeal Λ = J := by
  letI := isLocalRing_of_isMaximal_of_pow_mem J hJ hpow
  exact (IsLocalRing.eq_maximalIdeal hJ).symm

end SolomonZeta