import Mathlib

/-!
# A finite algebraic Landauer chain for proof search

This file gives a deliberately finite, model-relative formulation.  A depth-`n`
binary proof search has `2^n` candidate certificates.  Selecting one certificate
and resetting one one-bit rejection flag for every other candidate performs
`2^n - 1` elementary erasures.  The results do **not** claim a lower bound for
all deductive systems; they prove one for the explicit exhaustive-verification
model defined below.
-/

noncomputable section

open Finset BigOperators

namespace ProofErasureChain

/-- Candidate certificates generated by `n` binary creation choices. -/
abbrev Certificate (n : ℕ) := Fin (2 ^ n)

/-- The number of one-bit rejection flags reset after retaining one certificate. -/
def erasedFlags (n : ℕ) : ℕ := Fintype.card (Certificate n) - 1

/-- Landauer work for resetting `m` one-bit flags. -/
def landauerWork (k T : ℝ) (m : ℕ) : ℝ := k * T * Real.log 2 * m

/-
The first nontrivial accounting identity: selecting one of `2^n` candidates
resets exactly `2^n - 1` rejection flags.
-/
theorem erasedFlags_exact (n : ℕ) : erasedFlags n = 2 ^ n - 1 := by
  unfold erasedFlags; aesop;

/-
The exact count gives the affine doubling law for one extra binary choice.
-/
theorem erasedFlags_succ (n : ℕ) : erasedFlags (n + 1) = 2 * erasedFlags n + 1 := by
  simp +arith +decide [erasedFlags_exact];
  zify ; norm_num ; ring

/-
The affine doubling law implies that erasure events dominate creation choices.
-/
theorem creation_le_erasure (n : ℕ) : n ≤ erasedFlags n := by
  induction' n with n ih <;> simp_all +decide [ erasedFlags_succ ];
  grind +qlia

/-
From depth four onward the separation is already strict by a factor greater than two.
-/
theorem twice_creation_lt_erasure (n : ℕ) (hn : 4 ≤ n) :
    2 * n < erasedFlags n := by
  induction hn <;> simp_all +decide;
  grind +suggestions

/-
In fact the erasure-event count has the exact exponential closed form.  This
restates the first identity together with the strict separation so later physical
results carry both facts explicitly.
-/
theorem exponential_erasure_certificate (n : ℕ) (hn : 4 ≤ n) :
    erasedFlags n = 2 ^ n - 1 ∧ 2 * n < erasedFlags n := by
  exact ⟨erasedFlags_exact n, twice_creation_lt_erasure n hn⟩

/-
The thermodynamic charge of exhaustive verification is exactly one Landauer
unit `kT ln 2` per rejected candidate.
-/
theorem verification_work_exact (k T : ℝ) (n : ℕ) (hn : 4 ≤ n) :
    landauerWork k T (erasedFlags n) = k * T * Real.log 2 * (2 ^ n - 1) ∧
      2 * n < erasedFlags n := by
  convert exponential_erasure_certificate n hn using 1;
  norm_num [ landauerWork, erasedFlags ]

/-
At nonnegative scale and temperature, exact accounting yields a lower bound
by the work associated with the `n` created binary choices.
-/
theorem verification_landauer_lower_bound (k T : ℝ) (n : ℕ) (hn : 4 ≤ n)
    (hk : 0 ≤ k) (hT : 0 ≤ T) :
    k * T * Real.log 2 * n ≤ landauerWork k T (erasedFlags n) := by
  have hsep := (verification_work_exact k T n hn).2
  have hcount : n ≤ erasedFlags n := by omega
  unfold landauerWork
  exact mul_le_mul_of_nonneg_left (by exact_mod_cast hcount) (by positivity)

/-- Programs of length strictly below `n`, represented by a disjoint union of
all binary words of lengths `0,...,n-1`. -/
abbrev ShortProgram (n : ℕ) := Σ i : Fin n, Fin (2 ^ (i : ℕ))

/-
There are exactly `2^n - 1` binary programs of length below `n`.
-/
theorem shortProgram_card (n : ℕ) : Nat.card (ShortProgram n) = 2 ^ n - 1 := by
  exact Eq.symm ( Nat.sub_eq_of_eq_add <| by exact Nat.recOn n ( by norm_num ) fun n ih => by simp +decide [ Fin.sum_univ_castSucc, pow_succ' ] at * ; linarith )

/-
Finite Kolmogorov counting obstruction: no coding sends every depth-`n`
certificate injectively to a strictly shorter binary program.
-/
theorem no_uniform_short_description (n : ℕ) :
    ¬ ∃ encode : Certificate n → ShortProgram n, Function.Injective encode := by
  intro h
  obtain ⟨encode, h_encode⟩ := h
  have h_card : Nat.card (Fin (2^n)) ≤ Nat.card (ShortProgram n) := by
    apply_rules [ Nat.card_le_card_of_injective ];
  have := shortProgram_card n; simp_all +decide ;
  exact not_le_of_gt ( Nat.sub_lt ( by norm_num ) ( by norm_num ) ) h_card

/-
A sub-exhaustive verifier always leaves an unqueried certificate.
-/
theorem hidden_certificate (n : ℕ) (queried : Finset (Certificate n))
    (hbudget : queried.card < 2 ^ n) :
    ∃ c : Certificate n, c ∉ queried := by
  contrapose! hbudget;
  rw [ show queried = Finset.univ from Finset.eq_univ_of_forall hbudget ] ; simp +decide [ Finset.card_univ ]

/-
Final synthesis.  The same binary family simultaneously exhibits exact
exponential erasure-event growth, a Landauer work lower bound, finite
Kolmogorov incompressibility, and an adversarial verification obstruction.
-/
theorem thermodynamic_proof_witness (k T : ℝ) (n : ℕ) (hn : 4 ≤ n)
    (hk : 0 ≤ k) (hT : 0 ≤ T) :
    erasedFlags n = 2 ^ n - 1 ∧
    2 * n < erasedFlags n ∧
    k * T * Real.log 2 * n ≤ landauerWork k T (erasedFlags n) ∧
    (¬ ∃ encode : Certificate n → ShortProgram n, Function.Injective encode) ∧
    ∀ queried : Finset (Certificate n), queried.card < 2 ^ n →
      ∃ c : Certificate n, c ∉ queried := by
  exact ⟨ exponential_erasure_certificate n hn |>.1, exponential_erasure_certificate n hn |>.2, verification_landauer_lower_bound k T n hn hk hT, no_uniform_short_description n, fun queried hq => hidden_certificate n queried hq ⟩

end ProofErasureChain