/-
# Polynomial Diophantine Tuples with a `k`-th Power Condition

We study the following configuration.  Fix a commutative ring `R`, an exponent
`k : ℕ`, and a shift `n : R`.  A set `A ⊆ R` has the **`k`-th power Diophantine
property `D_k(n)`** when for every pair of distinct elements `a b ∈ A` the shifted
product `a * b + n` is a perfect `k`-th power in `R`.  Classically (`R = ℤ`,
`k = 2`) these are the Diophantine `m`-tuples of Diophantus, Fermat and Euler.

The research target is the conjecture that over `R = F[x]` (with `F` an
algebraically closed field of characteristic `0` and `n ≠ 0`) any such set has at
most six elements, *unless* `n` is a perfect `k`-th power and `A` lies in the
principal ideal generated by a `k`-th root of `n`.

This file isolates and proves three structural facts that explain *why the
hypotheses of that conjecture are exactly the right ones*:

* `algClosed_constants_dioSet` / `algClosed_dioSet_arbitrarily_large`:
  over an algebraically closed field **every** set of *constants* is a `D_k(n)`
  set, so among constants there is no size bound at all.  The conjecture must
  therefore genuinely use the *degree* (polynomial) structure of `F[x]`.
* `sameDeg_dioSet_two_dvd`:  a **degree rigidity** constraint — if all members of
  a `D_k(n)` set are polynomials of one common degree `d ≥ 1` and `deg n < 2d`,
  then `k ∣ 2d`.  This is a genuine obstruction (e.g. `k = 3` forces `3 ∣ d`).
* `zero_and_nonzero_forces_kthPower` together with `dioSet_insert_zero_of_kthPower`:
  a `D_k(n)` set may be extended by `0` **iff** `n` is a perfect `k`-th power,
  precisely matching the exceptional clause of the conjecture.

-- !-- Lab Notes — Team loop -- !--
-- !-- Hypothesis (Hypothesizer): five conjectures were floated. (i) constants over
--     an algebraically closed field are always a Diophantine set (surprising: it
--     kills any bound before degrees enter); (ii) a fixed common degree forces a
--     divisibility `k ∣ 2d`; (iii) the `0`-extension is possible exactly when `n`
--     is a `k`-th power; (iv) a false attempt: "gcd(a,b) ∣ n for distinct members"
--     (dropped, see Analysis); (v) the full `≤ 6` bound (left open). -- !--
-- !-- Experiment (Experimenter): over ℚ[x], k=2, n=1 we checked {0, x, x+2} and
--     {0} ∪ {constants}; constants always work by k-th roots; degree parity forced
--     `2 ∣ 2d` trivially but `k=3` genuinely rules out odd `d`. -- !--
-- !-- Analysis (Analyst): (i)-(iii) survived as clean theorems. Conjecture (iv)
--     ("common factor of two members divides n") is FALSE: from `ab + n = c^k`,
--     a common factor `g` of `a,b` gives `g ∣ c^k - n`, not `g ∣ n`, so no such
--     divisibility holds; it needed a *different* definition (coprimality of `a`
--     with `n`) and was discarded. The degree argument is the load-bearing insight:
--     `natDegree (c^k) = k * natDegree c` is the only place `k` enters. -- !--
-- !-- Critique (Critic): none of the three theorems is vacuous. `sameDeg` needs
--     `1 ≤ d` (else `a` could be `0` and `natDegree_mul` fails) and `deg n < 2d`
--     (else the top terms could cancel); both hypotheses are load-bearing. The
--     `0`-extension iff is proved in both directions, not just the easy one. -- !--
-- !-- Synthesis (PI): the three results delimit the conjecture — constants are the
--     only source of unboundedness, degrees give the arithmetic obstruction, and
--     the `k`-th-power exception is forced by the element `0`. Open: the `≤ 6`
--     bound for nonconstant tuples (see FUTURE_DIRECTIONS.md). -- !--
-/
import Mathlib

open Polynomial

namespace PolyDioTuple

variable {R : Type*} [CommRing R]

/-- A set `A ⊆ R` has the **`k`-th power Diophantine property `D_k(n)`**: for all
distinct `a b ∈ A`, the shifted product `a * b + n` is a perfect `k`-th power. -/
def IsKthPowerDioSet (k : ℕ) (n : R) (A : Set R) : Prop :=
  ∀ ⦃a⦄, a ∈ A → ∀ ⦃b⦄, b ∈ A → a ≠ b → ∃ c : R, a * b + n = c ^ k

/-- `D_k(n)` is inherited by subsets. -/
theorem IsKthPowerDioSet.mono {k : ℕ} {n : R} {A B : Set R}
    (h : IsKthPowerDioSet k n B) (hAB : A ⊆ B) : IsKthPowerDioSet k n A :=
  fun _ ha _ hb hne => h (hAB ha) (hAB hb) hne

/-!
## 1.  Constants over an algebraically closed field give no bound

Over an algebraically closed field every element is a `k`-th power (`k ≥ 1`), so
`a * b + n` is automatically a `k`-th power: *every* set of constants is a
`D_k(n)` set.  Hence the size bound of the conjecture cannot hold among constants
and must exploit the polynomial degree structure of `F[x]`.
-/

/-- Over an algebraically closed field, **every** set of constants is a `D_k(n)`
set for every `k ≥ 1` and every shift `n`. -/
theorem algClosed_constants_dioSet {F : Type*} [Field F] [IsAlgClosed F]
    {k : ℕ} (hk : 0 < k) (n : F) (A : Set F) : IsKthPowerDioSet k n A := by
  intro a _ b _ _
  obtain ⟨c, hc⟩ := IsAlgClosed.exists_pow_nat_eq (a * b + n) hk
  exact ⟨c, hc.symm⟩

/-- Consequently, over an infinite algebraically closed field there are `D_k(n)`
sets of arbitrarily large (finite) cardinality: no absolute size bound holds
among constants. -/
theorem algClosed_dioSet_arbitrarily_large {F : Type*} [Field F] [IsAlgClosed F]
    [Infinite F] {k : ℕ} (hk : 0 < k) (n : F) (N : ℕ) :
    ∃ s : Finset F, N < s.card ∧ IsKthPowerDioSet k n (↑s : Set F) := by
  obtain ⟨s, hs⟩ := Infinite.exists_subset_card_eq F (N + 1)
  exact ⟨s, by omega, algClosed_constants_dioSet hk n _⟩

/-!
## 2.  Degree rigidity in `F[x]`

If all members of a `D_k(n)` set of polynomials share one common degree `d ≥ 1`
and the shift has smaller degree than the product `deg n < 2d`, then the leading
terms cannot cancel, so `deg(a*b+n) = 2d`; being a `k`-th power forces `k ∣ 2d`.
-/

/-- The degree of `a * b + n` is divisible by `k` for any distinct `a b` in a
`D_k(n)` set of polynomials (`k`-th powers have degree divisible by `k`). -/
theorem dioSet_natDegree_dvd {F : Type*} [Field F] {k : ℕ} {n : F[X]}
    {A : Set F[X]} (h : IsKthPowerDioSet k n A) {a b : F[X]}
    (ha : a ∈ A) (hb : b ∈ A) (hne : a ≠ b) :
    k ∣ (a * b + n).natDegree := by
  obtain ⟨c, hc⟩ := h ha hb hne
  rw [hc, natDegree_pow]
  exact Dvd.intro _ rfl

/-- **Degree rigidity.**  If every member of a `D_k(n)` set has the fixed degree
`d ≥ 1` and `deg n < 2d`, then `k ∣ 2d`. -/
theorem sameDeg_dioSet_two_dvd {F : Type*} [Field F] {k d : ℕ} {n : F[X]}
    {A : Set F[X]} (h : IsKthPowerDioSet k n A)
    (hd : 1 ≤ d) (hn : n.natDegree < 2 * d)
    (hdeg : ∀ p ∈ A, p.natDegree = d)
    {a b : F[X]} (ha : a ∈ A) (hb : b ∈ A) (hne : a ≠ b) :
    k ∣ 2 * d := by
  have hane : a ≠ 0 := by
    intro h0; rw [h0] at ha; have := hdeg 0 ha; simp at this; omega
  have hbne : b ≠ 0 := by
    intro h0; rw [h0] at hb; have := hdeg 0 hb; simp at this; omega
  have hprod : (a * b).natDegree = 2 * d := by
    rw [natDegree_mul hane hbne, hdeg a ha, hdeg b hb]; ring
  have hsum : (a * b + n).natDegree = 2 * d := by
    rw [natDegree_add_eq_left_of_natDegree_lt (by rw [hprod]; exact hn), hprod]
  have := dioSet_natDegree_dvd h ha hb hne
  rwa [hsum] at this

/-!
## 3.  The `0`-extension and the `k`-th power exception

Adjoining `0` to a `D_k(n)` set requires `0 * a + n = n` to be a `k`-th power.
This makes precise the exceptional clause: `0` may be added **iff** `n` is a
perfect `k`-th power.
-/

/-- If a `D_k(n)` set contains `0` together with some nonzero element, then `n`
must be a perfect `k`-th power. -/
theorem zero_and_nonzero_forces_kthPower {k : ℕ} {n : R} {A : Set R}
    (h : IsKthPowerDioSet k n A) (h0 : (0 : R) ∈ A) {a : R}
    (ha : a ∈ A) (hne : a ≠ 0) : ∃ c : R, n = c ^ k := by
  obtain ⟨c, hc⟩ := h h0 ha (Ne.symm hne)
  exact ⟨c, by rw [← hc, zero_mul, zero_add]⟩

/-- Conversely, if `n` is a perfect `k`-th power then any `D_k(n)` set may be
extended by `0` and remains a `D_k(n)` set. -/
theorem dioSet_insert_zero_of_kthPower {k : ℕ} {n : R} {A : Set R}
    (h : IsKthPowerDioSet k n A) (hn : ∃ c : R, n = c ^ k) :
    IsKthPowerDioSet k n (insert 0 A) := by
  obtain ⟨c, hc⟩ := hn
  intro x hx y hy hne
  rcases hx with hx | hx
  · exact ⟨c, by rw [hx, zero_mul, zero_add, hc]⟩
  · rcases hy with hy | hy
    · exact ⟨c, by rw [hy, mul_zero, zero_add, hc]⟩
    · exact h hx hy hne

/-- **Characterization of the `0`-extension.**  For a `D_k(n)` set `A` containing
a nonzero element, `insert 0 A` is a `D_k(n)` set **iff** `n` is a perfect
`k`-th power — exactly the exceptional clause of the conjecture. -/
theorem dioSet_insert_zero_iff {k : ℕ} {n : R} {A : Set R}
    (h : IsKthPowerDioSet k n A) {a : R} (ha : a ∈ A) (hne : a ≠ 0) :
    IsKthPowerDioSet k n (insert 0 A) ↔ ∃ c : R, n = c ^ k := by
  constructor
  · intro hins
    exact zero_and_nonzero_forces_kthPower hins (Set.mem_insert 0 A)
      (Set.mem_insert_of_mem 0 ha) hne
  · exact dioSet_insert_zero_of_kthPower h

end PolyDioTuple